### ISSUE TITLE
Wildcard permission ignores negative exceptions

### ISSUE THREAD

**Issue by memetrollsXD** [Melledy/Grasscutter#1000]
https://github.com/Grasscutters/Grasscutter/blob/8819cca3e2176e5c9e25ed768bdb46a343d8e497/src/main/java/emu/grasscutter/game/Account.java#L145

![image](https://user-images.githubusercontent.com/27217031/169362819-00e4341b-8977-4e52-af1b-a8435152aaa7.png)

**Comment by memetrollsXD** [comment]
CC @omg-xtao because he has worked on permission system before

**Comment by omg-xtao** [comment]
https://github.com/Grasscutters/Grasscutter/blob/8819cca3e2176e5c9e25ed768bdb46a343d8e497/src/main/java/emu/grasscutter/command/commands/AccountCommand.java#L52

The account create command will automatically grant * privileges.
