### ISSUE TITLE
Full offline support

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#1004]
The original God official is expected to update version 2.7 in the near future. Can we continue to play Grasscutter with version 2.7 client? If not, can you implement full offline support for 2.6 clients? When the network is completely offline, the client will report error code 4201 (Baidu translation)

**Comment by YukariChiba** [comment]
> original God

nice translation lol

**Comment by Adelaide114514** [comment]
so?2.7Grasscutter还能玩吗

**Comment by kamiluor** [comment]
I guess that the server that checks for updates and the game server should not be the same server or link. After my tests, there are two situations:
1. When the computer is connected to the mobile phone hotspot and the mobile phone data is turned off (that is, disconnected from the network), an error "4201" will be reported when opening the game. (I tried to spoof the client by simulating the state of being connected to the network, but it failed, but this may be a Windows policy problem).
2. When the game is successfully logged in and entered into the game, disconnect all networks, and it will not be dropped, and you can transfer, play copies, and switch worlds normally.
3. If you open the game without using the launcher, there will also be an update check, and you cannot connect to the local server even when the network is disconnected.
     There should be two ways to check for updates, one is the launcher, and the other should be in the game program. In other words, after 10 days, the official update of Genshin Impact 2.7 may change the encryption, making the existing version (v1.1.0) of Grasscutter unusable, unless there is a way to keep the existing client at version 2.6 ( That is, the update check request before logging in to the game is hijacked and transferred to the local server, and the return value is added to the local server to deceive the client "no need to update"); or the official "Genshin Impact" has not changed the encryption, so the update of Grasscutter will become easier.
It's just.... At this stage, the return value of the update check server has not been decrypted.

**Comment by GanyusLeftHorn** [comment]
Full offline play is already supported in the latest dev build.

**Comment by kamiluor** [comment]
> Full offline play is already supported in the latest dev build.

Is it Grasscutter v1.1.2dev version?When my friend used "grasscutter v1.1.2dev" before, it was not able to run completely offline. When logging into the game without connecting to the network, an error "4201" will be reported.

**Comment by Adelaide114514** [comment]
> 最新的开发版本已经支持完全离线播放。

是什么版本？也就是可以保存在2.6版本？那如果要玩服务器的话可以断网等待检查更新后然后再连接网络发送请求至服务器？

**Comment by nn5864312** [comment]
so,2.7后即使服务端加密，至少仍可以保留2.6版本继续游玩和修复是吗

**Comment by kamiluor** [comment]
There is currently no support for complete offline operation. It is recommended to back up the 2.6 version of the client and wait for the update message on GitHub

**Comment by qingchunnh** [comment]
现在可以算是完全离线，登录是要解析域名

**Comment by Pull256** [comment]
之前我提过这个Issue，也通过代理软件进行了简单的分析，希望对这个有帮助
I mentioned this issue before and also did a brief analysis via proxy software, hope that helps with this.
https://github.com/Grasscutters/Grasscutter/issues/326

**Comment by Birdulon** [comment]
Currently works when proxying all traffic, might be missing some domains from the current script.
