### ISSUE TITLE
[Bug] 深渊九层怪物打到第九只后就不能再生成

### ISSUE THREAD

**Issue by CSXFanMeng** [Melledy/Grasscutter#1007]
使用指令解锁全部楼层后，可进入别的楼层目前只测试了12层，打完第一间后别的间也不能进入
Grasscutter version: 1.1.2-dev

**Comment by xmgnew** [comment]
Translate: spiral abyss floor 9 issues, monsters not spawning after defeating them. The same problem appears at higher floors, such as floor 12. 
Note: This bug is already exists from dev 1.1.0
