### ISSUE TITLE
A mystery type of network pack from game client

### ISSUE THREAD

**Issue by zhaodice** [Melledy/Grasscutter#1018]
When I try connect game server that was deployed remote network, game shows "Connection time out" , I have captured game pack but it astonishes me , the client sent too many mystery packs over and over again while it is connecting.
why it is mystery pack?because that are abnormal KCP packs.

example, PACK DATA:
` 000000ff 00000000 00000000 499602d2 ffffffff  `

a standard KCP pack's length is > 24 but it is 20 bytes so that kcp cannot recognized this format, leading to connection failure finally.
I want to finger out what is it.

![mystery](https://user-images.githubusercontent.com/63996691/169573277-c9bbdbd6-0b82-408f-9d7a-dff5253d64b1.PNG)

**Comment by zhaodice** [comment]
![mystery](https://user-images.githubusercontent.com/63996691/169573645-59774e57-15db-4193-98f5-60d52c6c5fa9.PNG)
[1.zip](https://github.com/Grasscutters/Grasscutter/files/8742005/1.zip)
 there is pcapng

**Comment by AZthemute** [comment]
This packet is sent while starting the game right? And that 1.zip is the packet?

**Comment by zhaodice** [comment]
> This packet is sent while starting the game right? And that 1.zip is the packet?

yes, When the game shows " Start Game" buttion,I click after I start capture

**Comment by zhaodice** [comment]
![1](https://user-images.githubusercontent.com/63996691/169576983-de6f25db-4f09-4400-8411-18b3509c95d8.PNG)
![2](https://user-images.githubusercontent.com/63996691/169576991-0c9cb5c0-a637-4f5e-a219-e90674aa7343.PNG)
This a packs screenshot when games works.
The game sent `000000ff 00000000 00000000 499602d2 ffffffff` too.
but `00000145 ac31368b aa60cf04 499602d2 14514545` responded

**Comment by zhaodice** [comment]
This pcapng when I login successfully
[2.zip](https://github.com/Grasscutters/Grasscutter/files/8742253/2.zip)

**Comment by zhaodice** [comment]
new connection failure :

[3.zip](https://github.com/Grasscutters/Grasscutter/files/8743271/3.zip)
![new](https://user-images.githubusercontent.com/63996691/169590650-3d0b6b56-b1d9-4edc-b83e-a293be31cdd4.PNG)

**Comment by AZthemute** [comment]
> new connection failure :
> 
> [3.zip](https://github.com/Grasscutters/Grasscutter/files/8743271/3.zip) ![new](https://user-images.githubusercontent.com/63996691/169590650-3d0b6b56-b1d9-4edc-b83e-a293be31cdd4.PNG)

What did you do to cause this one?

**Comment by zhaodice** [comment]
> What did you do to cause this one

I deployed Grasscutters in remote machine which is in Intranet, and exposed a public port for v2ray(vmess) to establish network tunnel.v2ray would create local socks5 proxy.
use tun2sock create virtual network to connect the local socks5 proxy.
so client connects the remote server by this chain :

client->tun2sock(virtual network) -> v2ray(socks5 proxy) -> a public port -> remote server

**Comment by LADIlib** [comment]
@zhaodice Standart KCP packet header is 24 bytes, GI has 28 bytes

**Comment by LADIlib** [comment]
and that 20 bytes is handshake to know that server needs to create session

**Comment by AZthemute** [comment]
> > What did you do to cause this one
> 
> I deployed Grasscutters in remote machine which is in Intranet, and exposed a public port for v2ray(vmess) to establish network tunnel.v2ray would create local socks5 proxy. use tun2sock create virtual network to connect the local socks5 proxy. so client connects the remote server by this chain :
> 
> client->tun2sock(virtual network) -> v2ray(socks5 proxy) -> a public port -> remote server

Ah, so not running locally. I see.

**Comment by zhaodice** [comment]
> and that 20 bytes is handshake to know that server needs to create session

I think it is kcp library problem but I don't know to resolve

it looks like a handshake program but no implement

https://github.com/Grasscutters/Grasscutter/blob/stable/src/main/java/emu/grasscutter/netty/KcpHandshaker.java

**Comment by zhaodice** [comment]
> and that 20 bytes is handshake to know that server needs to create session

yes, I think Grasscutter dosen't recognize 20 bytes handshake pack from remote server

**Comment by nigpo** [comment]
This also cause #944 problem, session may compute as a different device that already connected.

**Comment by zhaodice** [comment]
> This also cause #944 problem, session may compute as a different device that already connected.

我已经找到问题了，是协议库的问题
如果网络延迟较大，UDP端口发生变化，那么协议库就会发生bug，它识别不了端口变化的客户端是同一个客户端，白瞎了KCP的conv机制
这就是为什么127.0.0.1搭建没问题但远程可能出问题的原因！
我已经把协议库改好了，基本上修复了，当然，只是屎上加屎

**Comment by FlourishingWorld** [comment]
这是自己实现的一套KCP“连接状态”的控制报文，因为UDP的无连接特性，原生的KCP无法实时感知到当前“连接状态”，具体协议事件类型你可以参考如下
![enet](https://user-images.githubusercontent.com/31504849/170975640-51f8bcfd-e0ee-467a-acc6-452959819920.PNG)
另外，我最近在用golang重构，用的是kcp-go开源库，但是对部分源码进行了改造，与客户端兼容性还不错
