### ISSUE TITLE
[Bug] Game problem

### ISSUE THREAD

**Issue by swarswa** [Melledy/Grasscutter#1020]
The server is built. Two people are in the same game and scene, but they can't see each other. Is there any operation error

**Comment by jerryfangr** [comment]
It's not a face-to-face talk, i suggest you provide branch name & version etc...
[How To Ask Questions The Smart Way](http://www.catb.org/~esr/faqs/smart-questions.html)

**Comment by memetrollsXD** [comment]
Please resubmit the issue with more context
