### ISSUE TITLE
[Bug] login with 404

### ISSUE THREAD

**Issue by dlutor** [Melledy/Grasscutter#1021]
I used the development branch. After creating an account, there was a 404 error in login. What's going on?
Windows environment, local port
![image](https://user-images.githubusercontent.com/32326842/169640291-d635d0c6-7300-4973-a029-1f79aa84e480.png)
![image](https://user-images.githubusercontent.com/32326842/169640297-c27f2c0a-b030-47ef-91ea-2f75576a7779.png)
![image](https://user-images.githubusercontent.com/32326842/169640299-4a560f8c-4d36-4492-8148-69f7775c0296.png)
![image](https://user-images.githubusercontent.com/32326842/169640351-e8184ff4-017e-4708-85b7-51e8b8749c52.png)

config.json
{
  "folderStructure": {
    "resources": "./resources/",
    "data": "./data/",
    "packets": "./packets/",
    "scripts": "./resources/scripts/",
    "plugins": "./plugins/"
  },
  "databaseInfo": {
    "server": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    },
    "game": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    }
  },
  "language": {
    "language": "zh_CN",
    "fallback": "en_US",
    "document": "EN"
  },
  "account": {
    "autoCreate": true,
    "defaultPermissions": ["server"],
    "maxPlayer": -1
  },
  "server": {
    "debugLevel": "NONE",
    "runMode": "HYBRID",
    "http": {
      "bindAddress": "0.0.0.0",
      "accessAddress": "0.0.0.0",
      "bindPort": 443,
      "accessPort": 0,
      "encryption": {
        "useEncryption": true,
        "useInRouting": true,
        "keystore": "./keystore.p12",
        "keystorePassword": "123456"
      },
      "policies": {
        "cors": {
          "enabled": false,
          "allowedOrigins": [
            "*"
          ]
        }
      },
      "files": {
        "indexFile": "./index.html",
        "errorFile": "./404.html"
      }
    },
    "game": {
      "bindAddress": "0.0.0.0",
      "accessAddress": "0.0.0.0",
      "bindPort": 22102,
      "accessPort": 0,
      "enableConsole": true,
      "gameOptions": {
        "inventoryLimits": {
          "weapons": 2000,
          "relics": 2000,
          "materials": 2000,
          "furniture": 2000,
          "all": 30000
        },
        "avatarLimits": {
          "singlePlayerTeam": 4,
          "multiplayerTeam": 4
        },
        "worldEntityLimit": 1000,
        "watchGachaConfig": false,
        "enableShopItems": true,
        "staminaUsage": true,
        "rates": {
          "adventureExp": 1.0,
          "mora": 1.0,
          "leyLines": 1.0
        }
      },
      "joinOptions": {
        "welcomeEmotes": [
          2007,
          1002,
          4010
        ],
        "welcomeMessage": "Welcome to a Grasscutter server.",
        "welcomeMail": {
          "title": "Welcome to Grasscutter!",
          "content": "Hi there!\r\nFirst of all, welcome to Grasscutter. If you have any issues, please let us know so that Lawnmower can help you! \r\n\r\nCheck out our:\r\n\u003ctype\u003d\"browser\" text\u003d\"Discord\" href\u003d\"https://discord.gg/T5vZU6UyeG\"/\u003e\n",
          "sender": "Lawnmower",
          "items": [
            {
              "itemId": 13509,
              "itemCount": 1,
              "itemLevel": 1
            },
            {
              "itemId": 201,
              "itemCount": 99999,
              "itemLevel": 1
            }
          ]
        }
      },
      "serverAccount": {
        "avatarId": 10000007,
        "nameCardId": 210001,
        "adventureRank": 1,
        "worldLevel": 0,
        "nickName": "Server",
        "signature": "Welcome to Grasscutter!"
      }
    },
    "dispatch": {
      "regions": [],
      "defaultName": "Grasscutter"
    }
  },
  "version": 3
}

**Comment by dlutor** [comment]
i used fidder, and it work

**Comment by worship-dog** [comment]
I have the same problem, how do you use the fidder to solve this problem?could you help me?
我也遇到了同样的问题，请问你是怎样使用fidder来解决这个问题的呢?你能帮帮我吗?

> i used fidder, and it work
