### ISSUE TITLE
[Bug] Chinese garbling issue for server welcoming messages./服务器消息中文乱码

### ISSUE THREAD

**Issue by FeletexGee** [Melledy/Grasscutter#1028]
**Describe the bug**
I've found that if I set texts of welcome messages,welcome mails,etc. in Chinese(in .\config.json),they would be garbled.That's actually annoying.Hope the issue could be fixed speedily. :-)
**Current branch**
  Grasscutter version: 1.1.0-dev
  Git Hash: 658ee3b
**Screenshots**

![原神 2022_5_22 1_00_41](https://user-images.githubusercontent.com/69303837/169661945-e892b0be-aa01-4fa4-9dcd-8375ddc85245.png)
![原神 2022_5_22 1_00_52](https://user-images.githubusercontent.com/69303837/169661947-cf174eaa-d8b8-456f-895d-4669a036170f.png)
![原神 2022_5_22 1_01_01](https://user-images.githubusercontent.com/69303837/169661948-fe11f562-8140-41c7-859c-b798e1242fd2.png)

**Comment by izhuolin** [comment]
If you use Windows system. Please send him the config.json character encoding into GB2312, if you are using a Linux system converts a character encoding UTF8, please

**Comment by FeletexGee** [comment]
> If you use Windows system. Please send him the config.json character encoding into GB2312, if you are using a Linux system converts a character encoding UTF8, please

I'm sorry that I ignored the encode.:-(
