### ISSUE TITLE
[Feature Request] 增加简单的放置系统

### ISSUE THREAD

**Issue by 66hh** [Melledy/Grasscutter#1031]
**Is your feature request related to a problem? Please describe.**

使用与spawn命令相同的包制作放置系统
**Describe the solution you'd like**

修改UseItem增加家具放置（按下使用按钮后原地放置家具），从HomeWorldFurnitureExcelConfigData.json中获取家具的GadGet ID 并用spwan命令相同的包刷出家具，并加家具的位置信息加入数据库中
**Describe alternatives you've considered**

**Additional context**

**Comment by SleepyAsh0191** [comment]
Translate: Add place feature into teapot.

Make a placement feature using the same package as the spawn command

Modify UseItem to add furniture placement (put the furniture in place after pressing the use button), get the GadGet ID of the furniture from HomeWorldFurnitureExcelConfigData.json and use the same package with the spawn command to summon the furniture, and add the location information of the furniture to the database

**Comment by Akka0** [comment]
You can experience  #1258 , the home system instead

**Comment by zhaodice** [comment]
fixed in https://github.com/Grasscutters/Grasscutter/pull/1258
