### ISSUE TITLE
[Bug] Java not found

### ISSUE THREAD

**Issue by ultard** [Melledy/Grasscutter#1032]
script start_config.cmd trying to set java path a java version thath does not installed (java 1.8), but i have java SE 18

`
set JAVA_PATH=C:\Program Files\Java\jdk1.8.0_202\bin\
set MITMDUMP_PATH=%CUR_PATH%
set MONGODB_PATH=%CUR_PATH%
`

i fixed this by changing the java directory
`set JAVA_PATH=%JAVA_HOME%\bin\`

  Grasscutter version: 1.1.0
  Git Hash: 658ee3b

**Comment by KingRainbow44** [comment]
while yes, it is a bug, its a very minor one.
additionally, startup scripts *might* be removed in the future.
if you want this bug fixed, feel free to submit a PR.
