### ISSUE TITLE
[Feature Request] Support record saboteur of server.

### ISSUE THREAD

**Issue by nigpo** [Melledy/Grasscutter#1043]
[Problem]
Server's saboteurs may not be recorded after they done harmful thing, so we should record all user command by logback.
[Reference]
#1019

**Comment by AZthemute** [comment]
I don't understand... what do you mean?

**Comment by Birdulon** [comment]
Closing due to recommendation in https://github.com/Grasscutters/Grasscutter/pull/1019#issuecomment-1134911218
