### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by starlayer** [Melledy/Grasscutter#1046]
**Did you look for other closed issues that have the same problem?**

这大概是一个新问题，前几页没看到有类似的issues
This is probably a new issue, I didn't see any similar issues on the previous pages

**Describe the bug**

更换jar后，之前的数据全部丢失，注册新账号后选择玩家性别后断开与服务器的链接，再次进入游戏时卡死，服务端报错如截图
已确认问题发生在 3a39545 ，此前的版本注册没有出现问题
After replacing the jar, all the previous data was lost, after registering a new account and selecting the gender of the player, the link with the server was disconnected, and the game was stuck when entering again, and the server side reported errors as in the screenshot
The problem was confirmed to have occurred in 3a39545, previous versions registered without problems

**Which branch did you use?**

  Grasscutter version: 1.1.2-dev
  Git Hash: 3a39545

**Screenshots**

![image](https://user-images.githubusercontent.com/93354132/169923823-a050cfd5-444b-4212-b6ed-4e9f62facdf4.png)

**Additional context**

此前使用的版本Hash大概是 afbeaf3，或是更往前的版本
The previous version of Hash used was probably afbeaf3, or earlier
(translated by Deepl)

**Comment by ShigemoriHakura** [comment]
Fixed #1048

**Comment by ShigemoriHakura** [comment]
Codex new account issues has been fixed #1048 
新账号的图鉴系统已经修了，#1048
