### ISSUE TITLE
[Feature Request] Log the amount of historical players online in a server

### ISSUE THREAD

**Issue by Stevwrz** [Melledy/Grasscutter#1051]
**Is your feature request related to a problem? Please describe.**
Log the amount of online players on the server so it would be more intuitive and be easier to troubleshoot problems.
**Describe the solution you'd like**
Automatically perform something like a /list uid every set amount of time like 30 minute. Then the amount of players online historically would be stored in the log.

**Comment by TurtleIdiot** [comment]
Alternatively, support could be added for some sort of HTTP endpoint for a logging system life Prometheus or Grafana
This also has the benefit of having a very nice and clean dashboard like graphana with line graphs and whatnot

**Comment by 4Benj** [comment]
This can easily be done though a plugin and, in my opinion, shouldn’t be done within base GC. I did something like this for gcgm but unfortunately, I have been unable to work on it for the past couple weeks.

**Comment by KingRainbow44** [comment]
> This can easily be done though a plugin and, in my opinion, shouldn’t be done within base GC.
