### ISSUE TITLE
[Bug] In-game garbled

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1052]
Setting configuration file Simplified Chinese will generate garbled error
For example, Signature and NickName, etc.
This seems to be an error
（556885  Update zh-CN.json）

**Comment by victor-lcr** [comment]
你需要使用GB2312编码来编辑Grasscutters的配置文件

**Comment by ZXAS007** [comment]
在未来是否可以免去这样步骤?直接使用UTF-8?

**Comment by ZXAS007** [comment]
在未来是否可以免去这样步骤?直接使用UTF-8?

**Comment by 4Benj** [comment]
Any examples?

**Comment by 4Benj** [comment]
Closed due to inactivity
