### ISSUE TITLE
[Bug] Gacha Banner error on PC, working fine on IOS

### ISSUE THREAD

**Issue by socbaysky** [Melledy/Grasscutter#1057]
I got error on PC:
![image](https://user-images.githubusercontent.com/5350936/170256436-abfa584d-4fc2-4ae3-adca-da1dd98edf00.png)

But working fine on IOS:

![image](https://user-images.githubusercontent.com/5350936/170242605-27d86872-e785-4290-9cc2-0598306ed118.png)

**Comment by memetrollsXD** [comment]
This is a client side issue. Play on official server, download resources and restart Grasscutter.
