### ISSUE TITLE
[Bug] The amount of energy particles generated by off-field skills are abnormal

### ISSUE THREAD

**Issue by 1-lavender-1** [Melledy/Grasscutter#1062]
**Did you look for other closed issues that have the same problem?**

Yes
**Describe the bug**

The probability of generating energy particles by off-field skills like Kokomi, Zhongli, and Raiden Shogun are far less than normal. Even I change the chance of generating particles to 100, there are still times when no particles are generated. It seems like there is an ICD for generating particles.

**Which branch did you use?**

Grasscutter version: 1.1.2-dev

**Screenshots**

(No particles are generated)
![33790afebe86c408ccf803fe9e1da61](https://user-images.githubusercontent.com/104431284/170499014-a049d6a1-bfd1-4738-8a3a-bab99ce7c51a.jpg)

**Additional context**

(Even I change the chance to 100)
![image](https://user-images.githubusercontent.com/104431284/170498292-7a493c5f-1af1-464e-9aec-33a439a5817a.png)

**Comment by Logictc** [comment]
I know a couple on-field skills are not generating properly. which off-field skill are you referring to?

**Comment by GanyusLeftHorn** [comment]
You will have to be a bit more specific here. Which character, and what do you mean by "abnormal"? How many are generated, and how many do you think should be?

**Comment by 1-lavender-1** [comment]
> You will have to be a bit more specific here. Which character, and what do you mean by "abnormal"? How many are generated, and how many do you think should be?

I have edited the issue to describe the bug more specific, thanks!

**Comment by 1-lavender-1** [comment]
> I know a couple on-field skills are not generating properly. which off-field skill are you referring to?

 As far as I have tested, Kokomi, Zhongli, Raiden Shogun and Albedo all encountered this issue.

**Comment by Logictc** [comment]
There actually is ICD for generating particles, client handles that, for Raiden it is 0.8 seconds, and for every E attach there is 50% chance it generates 1 particle, and 50% chance generates 0 particles. However I am now suspecting when it generate 0 particles the client won't even send the call, you will be observing a 25% chance for Raiden E to generate 1 particle if that is the case.

**Comment by Logictc** [comment]
I just tested, confirmed it is at 25% right now, will fix this by not handle 0 particle generation on server side.

**Comment by Seeker14491** [comment]
I think this can be closed now, as https://github.com/Grasscutters/Grasscutter/pull/1063 has been merged.
