### ISSUE TITLE
[Bug] Ubuntu VPS got high CPU with enableScriptInBigWorld = true

### ISSUE THREAD

**Issue by socbaysky** [Melledy/Grasscutter#1065]
When enableScriptInBigWorld = true in config.json:

![image](https://user-images.githubusercontent.com/5350936/170625744-918528ea-fba7-4918-9dbe-03d012538f20.png)

Only 10 member online:

![image](https://user-images.githubusercontent.com/5350936/170625786-d843a16b-8d3b-4105-9654-6c7796e11030.png)

**Comment by JarvisQin** [comment]
我也是，当他们在刷怪的时候，后台会报错，jvm占用很多的cpu

**Comment by JarvisQin** [comment]
![Uploading QQ图片20220527121625.png…]()

**Comment by Scirese** [comment]
似乎就是这样，开启脚本后服务器资源占用会很高，尤其是你这还有10个人在线

**Comment by lunaticwhat** [comment]
temporary closed to clean up the work space.
