### ISSUE TITLE
[Feature Request]请问任务系统与秘境正常通关的修复难度是否很高 

### ISSUE THREAD

**Issue by nn5864312** [Melledy/Grasscutter#1066]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minhngoc25a** [comment]
它最终将被添加。请耐心等待。

-----

It will eventually be added. Just wait patiently.

**Comment by Akka0** [comment]
The answer is yes obviously.
There are 194 function in ScriptLib need to impl, some functions have lots of usages which would take much time.

**Comment by KiminaNatsuki** [comment]
> The answer is yes obviously. There are 194 function in ScriptLib need to impl, some functions have lots of usages which would take much time.
