### ISSUE TITLE
Version 2.7 does not work

### ISSUE THREAD

**Issue by rainbowwarmth** [Melledy/Grasscutter#1067]
When will you update the proto of Genshin Impact 2.7? After pre-downloading and installing it today, Grasscutters using 2.7 will let you download another 10GB resource pack
 Grasscutter version: 1.0.2-dev

**Comment by 4Benj** [comment]
Grasscutter will not be updated to 2.7 until it gets released to the public.

**Comment by memetrollsXD** [comment]
Why are you even trying to update right now? Wait for release 🥴
