### ISSUE TITLE
[Bug] Talents and constellations related to energy recharge fail to work

### ISSUE THREAD

**Issue by WhisperWithDelight** [Melledy/Grasscutter#1068]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

Talents and constellations related to energy recharge fail to work, like Raiden's talent 2, Jean's talent 2, Ayato's talent 2, Yae C1, Itto C2, and Kazuha C4,

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by memetrollsXD** [comment]
This is a suggestion instead of a bug, these things haven't been implemented yet
