### ISSUE TITLE
[Bug] No meat dropped when I killed a wild pig

### ISSUE THREAD

**Issue by zhaodice** [Melledy/Grasscutter#1071]
No meat dropped when I killed a wild pig, ~~console show warning~~
~~`16:58:37 <WARN:EnergyManager> No drop data for dropId 22000100 found. `~~(solved)
It maybe a clue about meat generation logic

**Comment by zhaodice** [comment]
killing the bird also shows 
` <WARN:EnergyManager> No drop data for dropId 22001000 found.`

**Comment by GanyusLeftHorn** [comment]
Oh, I forgot to check for energy drops whether the "monster" is actually a monster. I'll fix that later, thank you for the report.

**Comment by zhaodice** [comment]
> Oh, I forgot to check for energy drops whether the "monster" is actually a monster. I'll fix that later, thank you for the report.

Thanks, but I want to find out how to make meat appeared when animal dead, I wait 2.7 release.

**Comment by GanyusLeftHorn** [comment]
> Thanks, but I want to find out how to make meat appeared when animal dead, I wait 2.7 release.

You should be able to make boar (and other wild animals) drop meat by adding the necessary information to `data/Drop.json`.
