### ISSUE TITLE
[Feature Request] Can we experience the characters and maps of version 2.7 in advance?

### ISSUE THREAD

**Issue by eormal** [Melledy/Grasscutter#1074]
I hope the developers can verify whether the pre-download opened by Mihoyo is a complete data package? Can we experience the characters and maps of version 2.7 in advance?

**Comment by Adelaide114514** [comment]
2.7的bin好像有人发出来了，我不知道能不能用，目前的割草机2.7的可以用？

**Comment by minhngoc25a** [comment]
Grasscutter will not support 2.7 anytime soon. It would take a long time. There's no ETA for this.

**Comment by Adelaide114514** [comment]
but,2.7的请求拉取不是已经做了一部分了吗，即使很简陋我也愿意尝试2.7

>

**Comment by minhngoc25a** [comment]
That's just the name of the branch. According to the devs, 2.7 will not come anytime soon.

**Comment by Adelaide114514** [comment]
可是有人说2.8也已经做的一部分了，我也见过进入2.7的图片视频

> 这只是分支的名称。根据开发人员的说法，2.7 不会很快到来。

**Comment by minhngoc25a** [comment]
Dude, get a life. If the developers said that, it doesn't matter what people said anymore. The "people" that you said don't develop Grasscutter. And also, English, please, don't turn this into a Chinatown.

**Comment by AZthemute** [comment]
> That's just the name of the branch. According to the devs, 2.7 will not come anytime soon.

What's the branch for then?

**Comment by zhaodice** [comment]
> > That's just the name of the branch. According to the devs, 2.7 will not come anytime soon.
> 
> What's the branch for then?

Position preservation for the future pull requests.

**Comment by victor-lcr** [comment]
> 可是有人说2.8也已经做的一部分了，我也见过进入2.7的图片视频
> 
> > 这只是分支的名称。根据开发人员的说法，2.7 不会很快到来。

You might as well try it yourself instead of asking useless questions here
