### ISSUE TITLE
[Bug] 2.6数据不能迁移2.7

### ISSUE THREAD

**Issue by JarvisQin** [Melledy/Grasscutter#1086]
2.6的账号，输入后2.7进入会新开另一个账号，uid变了，但是数据库中的playerid没了。
或者存在另一种情况，进入后白屏，后台报错。
![image](https://user-images.githubusercontent.com/35295796/170830959-5f84449d-b105-4d74-8b80-5ea1790f54d9.png)

**Comment by jackey670** [comment]
请问如何体验2.7版本
