### ISSUE TITLE
[Bug]Clicking to enter in the Rift doesn't work at all

### ISSUE THREAD

**Issue by kuyoos** [Melledy/Grasscutter#1090]
The dev1.1.2 resources compiled with source code are downloaded from Wiki
Where is the problem

在秘境中点击进入没用任何反应
用源码编译出的dev1.1.2 resources在Wiki里下载的
请问是哪里出现了问题

**Comment by AZthemute** [comment]
What is Rift?

什么是裂谷？(谷歌翻译)

**Comment by kuyoos** [comment]
地牢或者秘境
Dungeon or Rift

**Comment by kuyoos** [comment]
地牢或者秘境
Dungeon or Rift

**Comment by memetrollsXD** [comment]
Do other dungeons work?

Not all lua files are perfect, so it may be that some domains are broken

**Comment by kuyoos** [comment]
> 其他地牢可以吗？
> 
> 并非所有lua文件都是完美的，所以可能是某些域被破坏了

目前测试来看有一定几率可以进入地牢.我只进入了第一关.进入其他地牢的时候点击没有作用
According to the current test, there is a certain probability of entering the dungeon. I can only enter the first level. Clicking when entering other dungeons has no effect
