### ISSUE TITLE
Friendship level issue | Fetter issue

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#110]
Hello, 

I just recently update my grasscutter to the latest version and I encountered one issue.

Friendship level is automatically 10, although I never set friendship XP.

I tried purging my database and create a new account to see if the issue is gone but sadly, it was still present. Whatever I do.

I'm really annoyed at this issue since there's too many exclamation marks in characters selection. 
(The exclamation mark is coming from this)
![image](https://user-images.githubusercontent.com/86816436/164645785-2df68fff-d907-4bb0-bd64-eb52183d73c8.png)

That's all, thanks.

**Comment by keitarogg** [comment]
I thought it was on purpose

**Comment by Yazawazi** [comment]
Yes, this is intentional. Friendship level is still in progress, so it is currently set to the highest level and experience value.

**Comment by Yazawazi** [comment]
I'm working on the character fetter system: #124

**Comment by Yazawazi** [comment]
This problem is now solved in the development branch. You can use `/setfetterlevel [level]` to set your current character's fetter level and be able to collect rewards normally.

**Comment by memetrollsXD** [comment]
Fixed in #124 

Switch to development branch using `git checkout development` or wait until it's merged to stable
