### ISSUE TITLE
[Feature Request] 请求修复每周副本，来获取突破材料

### ISSUE THREAD

**Issue by JarvisQin** [Melledy/Grasscutter#1103]
在world-script版本中，周本可以进入并击杀boss，但并不能获得掉落材料。
在dev版本中，可以进入副本但boss并未出现。

**Comment by q1176854020** [comment]
改掉落就可以了

**Comment by HangbinYang** [comment]
> 

有没有什么工具可以快速修改掉落？json文件里面内容太多太多了，纯指令刷材料又没啥意思

**Comment by lunaticwhat** [comment]
temporary closed to clean up the work space.
