### ISSUE TITLE
[Feature Request] Use Kotlin for dev

### ISSUE THREAD

**Issue by EugenFeuer** [Melledy/Grasscutter#1104]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I’m an Android/iOS developer, and I usually use kt as my main Android APP development language. So it’s just a suggestion to use kt in Grasscutter because it can not only easily mix with Java, but much  much more powerful, brief, maintainable than Java.

**Describe alternatives you've considered**

**Additional context**

**Comment by 4Benj** [comment]
No #323
