### ISSUE TITLE
[Bug] 严重回档bug和无限发送领取请求

### ISSUE THREAD

**Issue by qinastar** [Melledy/Grasscutter#1105]
在多人反馈下，一些操作后似乎将造成无法存档。
主要反馈是说在神像回血数次后，将触发（并未100%确定）
---
此外，在一些领取界面：邮件、冒险奖励等地方，可以通过限制网速等方式来无限请求领取。

**Comment by Secretboy-SMR** [comment]
你最好说英文/You'd better speak English

**Comment by Secretboy-SMR** [comment]
具体哪些操作？

**Comment by zhaodice** [comment]
> 具体哪些操作？

Disconnect network, quickly click the reward button, will get item repeatedly

**Comment by zhaodice** [comment]
很简单就是领取的时候没有判断，服务端那边判断一下发现重复领取，拒了就行了
