### ISSUE TITLE
How can create account

### ISSUE THREAD

**Issue by JamZhemge** [Melledy/Grasscutter#111]
![image](https://user-images.githubusercontent.com/73025829/164651266-f42dd701-909e-476e-9d45-7dd093238f39.png)

**Comment by alt3ri** [comment]
Go to discord's [#support](https://discord.com/channels/965284035985305680/965284036333424722/966959360947388446) channel first please.

**Comment by JamZhemge** [comment]
ok

**Comment by Scirese** [comment]
Please close the issue.

**Comment by BaiSugar** [comment]
Irrelevant questions please do not speak here
