### ISSUE TITLE
错误[Bug] 

### ISSUE THREAD

**Issue by YansHJ** [Melledy/Grasscutter#1111]
在百度云的Windows Server 2019上运行代理和服务端，当远程主机运行客户端通过windows代理到Windows server 2019的8080端口时，客户端显示“正在下载资源”，之后显示“错误4206”，无法连接上服务端，而服务端则一直在报错

**Comment by zhaodice** [comment]
一看就是根证书没安装，原神客户端察觉到服务器的https证书是假的就握手失败了，你仔细看错误：handshake failed

**Comment by zhaodice** [comment]
自己用IE浏览器打开[mihoyo.com](https://account.mihoyo.com/) 什么时候显示grasscutter而且浏览器不瞎BB危险了显示绿锁什么时候就正确了。

**Comment by YansHJ** [comment]
> 

对，我发现了，好像这个代理mitmproxy需要证书，但是查了一下还是不知道该怎么解决，不太熟悉这个东西，你有什么解决办法吗，求教一下

**Comment by YansHJ** [comment]
> 对，我发现了，好像需要授权，但是查了一下还是不知道这个证书怎么解决，什么问题解决这个问题，你有什么问题，求教

**Comment by zhaodice** [comment]
> > 
> 
> 对，我发现了，好像这个代理mitmproxy需要证书，但是查了一下还是不知道该怎么解决，不太熟悉这个东西，你有什么解决办法吗，求教一下

你电脑有浏览器吗？打开 https://account.mihoyo.com/ 告诉你证书危险
你无视，继续访问，然后点击地址栏，查看证书，然后点安装证书，选择根存储

**Comment by zhaodice** [comment]
![image](https://user-images.githubusercontent.com/63996691/171018064-5901ab4e-df83-4691-888e-f0e67598fc92.png)

**Comment by zhaodice** [comment]
![image](https://user-images.githubusercontent.com/63996691/171018208-f4bc6c7a-ce46-49fe-8dc1-c73c4ba20f6f.png)
![image](https://user-images.githubusercontent.com/63996691/171018268-77ba73fb-c614-4152-b2c8-c8f567b59e88.png)
此处应该有个安装

**Comment by YansHJ** [comment]
> https://account.mihoyo.com/

我在客户端的主机上看到有一个导出证书，我导出为xxx.cer，之后应该怎么导入到服务端的主机上呢

**Comment by YansHJ** [comment]
> ![image](https://user-images.githubusercontent.com/63996691/171018208-f4bc6c7a-ce46-49fe-8dc1-c73c4ba20f6f.png) ![image](https://user-images.githubusercontent.com/63996691/171018268-77ba73fb-c614-4152-b2c8-c8f567b59e88.png) 此处应该有个安装

我在客户端的主机上看到有一个导出证书，我导出为xxx.cer，之后应该怎么导入到服务端的主机上呢

**Comment by zhaodice** [comment]
@YansHJ 我让你打开 https://account.mihoyo.com/ ，不是真让你打开github看它证书

**Comment by zhaodice** [comment]
正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书

**Comment by YansHJ** [comment]
> 正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书

但是他没有告诉我证书错误，无论是本机还是服务器上。。。

**Comment by zhaodice** [comment]
> > 正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书
> 
> 但是他没有告诉我证书错误，无论是本机还是服务器上。。。

那么它现在显示什么？正常的网页？如果是这样那么你就失败了

**Comment by zhaodice** [comment]
只有你游玩的电脑显示如下，才能代表grasscutter正式接管了你电脑的游戏
![image](https://user-images.githubusercontent.com/63996691/171020416-ec2909c6-081e-4201-8229-804bd708a416.png)

**Comment by YansHJ** [comment]
> > > 正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书
> > 
> > 
> > 但是他没有告诉我证书错误，无论是本机还是服务器上。。。
> 
> 那么它现在显示什么？正常的网页？如果是这样那么你就失败了

是正常的网页，我使用的是mitmproxy做的代理

**Comment by zhaodice** [comment]
> > > > 正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书
> > > 
> > > 
> > > 但是他没有告诉我证书错误，无论是本机还是服务器上。。。
> > 
> > 
> > 那么它现在显示什么？正常的网页？如果是这样那么你就失败了
> 
> 是正常的网页，我使用的是mitmproxy做的代理

那你肯定失败了，哎呀，其实可以不用mitmproxy的，你是在哪里架设的私服？游玩的电脑，还是远端服务器？

**Comment by zhaodice** [comment]
```
127.0.0.1 api-os-takumi.mihoyo.com
127.0.0.1 hk4e-api-os-static.mihoyo.com
127.0.0.1 hk4e-sdk-os.mihoyo.com
127.0.0.1 dispatchosglobal.yuanshen.com
127.0.0.1 osusadispatch.yuanshen.com
127.0.0.1 account.mihoyo.com
127.0.0.1 log-upload-os.mihoyo.com
127.0.0.1 dispatchcntest.yuanshen.com
127.0.0.1 devlog-upload.mihoyo.com
127.0.0.1 webstatic.mihoyo.com
127.0.0.1 log-upload.mihoyo.com
127.0.0.1 hk4e-sdk.mihoyo.com
127.0.0.1 api-beta-sdk.mihoyo.com
127.0.0.1 api-beta-sdk-os.mihoyo.com
127.0.0.1 cnbeta01dispatch.yuanshen.com
127.0.0.1 dispatchcnglobal.yuanshen.com
127.0.0.1 cnbeta02dispatch.yuanshen.com
127.0.0.1 sdk-os-static.mihoyo.com
127.0.0.1 webstatic-sea.mihoyo.com
127.0.0.1 hk4e-sdk-os-static.hoyoverse.com
127.0.0.1 webstatic-sea.hoyoverse.com
127.0.0.1 sdk-os-static.hoyoverse.com
127.0.0.1 api-account-os.hoyoverse.com
127.0.0.1 hk4e-sdk-os.hoyoverse.com
127.0.0.1 uspider.yuanshen.com
```
如果你是本机游玩，修改`C:\Windows\System32\drivers\etc\hosts`如上就可以了

**Comment by zhaodice** [comment]
并保证证书正确（https://account.mihoyo.com/ 显示grasscutter就没问题）

**Comment by YansHJ** [comment]
> > > > > 正常情况下你现在打开https://account.mihoyo.com/ 应该告诉你证书错误，这时你再装证书
> > > > 
> > > > 
> > > > 但是他没有告诉我证书错误，无论是本机还是服务器上。。。
> > > 
> > > 
> > > 那么它现在显示什么？正常的网页？如果是这样那么你就失败了
> > 
> > 
> > 是正常的网页，我使用的是mitmproxy做的代理
> 
> 那你肯定失败了，哎呀，其实可以不用mitmproxy的，你是在哪里架设的私服？游玩的电脑，还是远端服务器？

不对不对，刚才远端服务器程序崩掉了，我重新启动了一下显示“访问的不是私密链接，可能会窃取xxxx”，之后点击继续前往，就会显示“Welcome to Grasscutter”

**Comment by zhaodice** [comment]
@YansHJ 
啊对对对，现在你就差最后一步了，你想办法按我上述说的，浏览器显示证书，然后选择根证书，安装它

**Comment by YansHJ** [comment]
> 并保证证书正确（https://account.mihoyo.com/ 显示grasscutter就没问题）

是远端，远程的服务器架设的服务端，之后我本地的电脑客户端去连接的

**Comment by YansHJ** [comment]
> 并保证证书正确（https://account.mihoyo.com/ 显示grasscutter就没问题）

是远端，远程的服务器架设的服务端，之后我本地的电脑客户端去连接的

**Comment by zhaodice** [comment]
![image](https://user-images.githubusercontent.com/63996691/171021394-44fdd323-e416-4e4c-ad19-6ef111e6f6c2.png)
![image](https://user-images.githubusercontent.com/63996691/171021430-b2ad66c5-3d42-472a-a439-d769fb8cac69.png)

我这个是正常的，你这个地方应该是告诉你证书不安全

**Comment by zhaodice** [comment]
点进去，把证书装好，安装的时候选择”受信任的根证书机构“什么的

**Comment by zhaodice** [comment]
然后刷新浏览器，它应该变成正常的绿锁，显示和我一样，证书有效，这时你应该可以进游戏了

**Comment by YansHJ** [comment]
> 点进去，把证书装好，安装的时候选择”受信任的根证书机构“什么的
![~QTG%JR8Z7(BXVD B{{AD7G](https://user-images.githubusercontent.com/56545309/171021658-78cd07f1-c70b-4222-9d97-472804fb2c84.png)
![J0ZSU7UWQAJ0EWX(8P 9`45](https://user-images.githubusercontent.com/56545309/171021875-2c95a219-e0ba-4695-9d84-a97a017322bf.png)

我这里好像没有你说的那样，没有看到证书

**Comment by zhaodice** [comment]
@YansHJ 详细信息呢

**Comment by zhaodice** [comment]
详细信息有个复制到文件，把cer文件复制出来，然后双击cer文件，安装

**Comment by YansHJ** [comment]
> 详细信息有个复制到文件，把cer文件复制出来，然后双击cer文件，安装
![4INK55G1WI}1@{VJ)A3L0%M](https://user-images.githubusercontent.com/56545309/171023032-8f58f470-85b5-4b59-b960-d1b345c28e76.png)
![U{{IWK51A81XN9A%6%(G`G7](https://user-images.githubusercontent.com/56545309/171023036-9e0262d5-c680-4675-bcce-8f6da2e7870e.png
![L4LK_H(8R$D~{9JGWBJMZ}D](https://user-images.githubusercontent.com/56545309/171023042-84dae97a-3d8e-48d2-8280-0bed18ed89fe.png)
)
![@@NU(Y_UGX02~75S)2$1PU9](https://user-images.githubusercontent.com/56545309/171023045-0eedae8f-99d5-40d6-bc7d-0a460a95e27f.png)

确实导入成功了，是我的步骤不对吗，导入之后访问还是显示刚才的错误，和红色的提示

**Comment by YansHJ** [comment]
我是应该在本地安装，还是在远程服务端安装这个证书呢

**Comment by YansHJ** [comment]
我是应该在本地安装，还是在远程服务端安装这个证书呢

**Comment by zhaodice** [comment]
> 我是应该在本地安装，还是在远程服务端安装这个证书呢

哪台系统玩游戏，哪台系统就要安装

**Comment by YansHJ** [comment]
> > 我是应该在本地安装，还是在远程服务端安装这个证书呢
> 
> 哪台系统玩游戏，哪台系统就要安装

对的，我是在本地客户端的主机上安装了，之后重新访问那个页面还是一样的红色提示

**Comment by zhaodice** [comment]
安装证书是为了让【游戏的客户端所在的电脑】信任你的私服，毕竟它是假的，不是官方的，所以必须强迫你的游戏电脑信任它

你的服务器不需要安装任何东西，需要的是游戏机的信任！！

**Comment by zhaodice** [comment]
> > > 我是应该在本地安装，还是在远程服务端安装这个证书呢
> > 
> > 
> > 哪台系统玩游戏，哪台系统就要安装
> 
> 对的，我是在本地客户端的主机上安装了，之后重新访问那个页面还是一样的红色提示

重启浏览器呢？

**Comment by YansHJ** [comment]
> > > > 我是应该在本地安装，还是在远程服务端安装这个证书呢
> > > 
> > > 
> > > 哪台系统玩游戏，哪台系统就要安装
> > 
> > 
> > 对的，我是在本地客户端的主机上安装了，之后重新访问那个页面还是一样的红色提示
> 
> 重启浏览器呢？

还是红色的提示，重启了浏览器，并且尝试用其他浏览器依旧是红色的提示

**Comment by zhaodice** [comment]
> > > > > 我是应该在本地安装，还是在远程服务端安装这个证书呢
> > > > 
> > > > 
> > > > 哪台系统玩游戏，哪台系统就要安装
> > > 
> > > 
> > > 对的，我是在本地客户端的主机上安装了，之后重新访问那个页面还是一样的红色提示
> > 
> > 
> > 重启浏览器呢？
> 
> 还是红色的提示，重启了浏览器，并且尝试用其他浏览器依旧是红色的提示

你安装的时候存储区域选的什么?

**Comment by YansHJ** [comment]
> > > > > > 我是应该在本地安装，还是在远程服务端安装这个证书呢
> > > > > 
> > > > > 
> > > > > 哪台系统玩游戏，哪台系统就要安装
> > > > 
> > > > 
> > > > 对的，我是在本地客户端的主机上安装了，之后重新访问那个页面还是一样的红色提示
> > > 
> > > 
> > > 重启浏览器呢？
> > 
> > 
> > 还是红色的提示，重启了浏览器，并且尝试用其他浏览器依旧是红色的提示
> 
> 你安装的时候存储区域选的什么?

“受信任的根证书颁发机构”

**Comment by zhaodice** [comment]
安装选的当前用户还是所有用户

**Comment by YansHJ** [comment]
> 安装选的当前用户还是所有用户

本地计算机，应该是所有用户

**Comment by YansHJ** [comment]
> 安装选的当前用户还是所有用户
![LZN_WRIZ~4%GM7T7O%N2K)G](https://user-images.githubusercontent.com/56545309/171025282-9670b59e-8993-4367-aa99-05120f2ef32d.png)

**Comment by zhaodice** [comment]
你这个问题吧，我也是第一次见，要不要再试试看重启电脑，虽然可能没什么用……主要是怎么说，你这个证书也有问题，它的结构很奇怪，没有根证书签发机构，光一个域名

**Comment by YansHJ** [comment]
> 你这个问题吧，我也是第一次见，要不要再试试看重启电脑，虽然可能没什么用……主要是怎么说，你这个证书也有问题，它的结构很奇怪，没有根证书签发机构，光一个域名
![@L2WIU){DLJ@~PNK8(BI@YO](https://user-images.githubusercontent.com/56545309/171025428-64d2e8dd-bcee-4bd2-b73c-53fe115fb45f.png)


我在正常访问时导出的证书是有这些信息的，而在红色提示下导出的证书是刚才那样只有域名

**Comment by zhaodice** [comment]
如果有条件的话你自己生成一个自签名的根证书也好……不过挺复杂的，一时半会说不明白……

**Comment by zhaodice** [comment]
> > 你这个问题吧，我也是第一次见，要不要再试试看重启电脑，虽然可能没什么用……主要是怎么说，你这个证书也有问题，它的结构很奇怪，没有根证书签发机构，光一个域名
> > ![@L2WIU){DLJ@~PNK8(BI@YO](https://user-images.githubusercontent.com/56545309/171025428-64d2e8dd-bcee-4bd2-b73c-53fe115fb45f.png)
> 
> 我在正常访问时导出的证书是有这些信息的，而在红色提示下导出的证书是刚才那样只有域名

这个你点安装证书试试看

**Comment by zhaodice** [comment]
安装证书后，安装证书这四个字会消失，点证书路径会告诉你证书没问题

**Comment by zhaodice** [comment]
哦对了 你这个截图好像是子证书吧……你需要点证书路径，找到最上面那个，你应该应该是GeoTrus ，然后点击它，查看证书

**Comment by zhaodice** [comment]
确保是根证书你再装

**Comment by zhaodice** [comment]
子证书我记得装不上

**Comment by YansHJ** [comment]
> 确保是根证书你再装

红色提示下只有一个，正常访问的情况下是有三个树枝的，我重新下载正常情况下的证书试试看

**Comment by YansHJ** [comment]
> 确保是根证书你再装

红色提示下只有一个，正常访问的情况下是有三个树枝的，我重新下载正常情况下的证书试试看

**Comment by zhaodice** [comment]
确实那问题可能就出在你自签名根证书有问题了……我的建议是你本地先搭，别搞远程服务器那么骚的操作，本地直接改hosts就行了不需要什么mitmproxy

**Comment by YansHJ** [comment]
> 确实那问题可能就出在你自签名根证书有问题了……我的建议是你本地先搭，别搞远程服务器那么骚的操作，本地直接改hosts就行了不需要什么mitmproxy
![EKS PP7VE39VIRX3}Y3F~PH](https://user-images.githubusercontent.com/56545309/171026836-aa229b18-f747-4333-bb9e-f30c037afebe.png)


本地有测试过，不需要改任何设置就可以进去，另外这个证书安装之后，“安装证书”还在，并且访问依旧是红色提示.....

**Comment by YansHJ** [comment]
> 确实那问题可能就出在你自签名根证书有问题了……我的建议是你本地先搭，别搞远程服务器那么骚的操作，本地直接改hosts就行了不需要什么mitmproxy
![EKS PP7VE39VIRX3}Y3F~PH](https://user-images.githubusercontent.com/56545309/171026836-aa229b18-f747-4333-bb9e-f30c037afebe.png)


本地有测试过，不需要改任何设置就可以进去，另外这个证书安装之后，“安装证书”还在，并且访问依旧是红色提示.....

**Comment by zhaodice** [comment]
> > 确实那问题可能就出在你自签名根证书有问题了……我的建议是你本地先搭，别搞远程服务器那么骚的操作，本地直接改hosts就行了不需要什么mitmproxy
> > ![EKS PP7VE39VIRX3}Y3F~PH](https://user-images.githubusercontent.com/56545309/171026836-aa229b18-f747-4333-bb9e-f30c037afebe.png)
> 
> 本地有测试过，不需要改任何设置就可以进去，另外这个证书安装之后，“安装证书”还在，并且访问依旧是红色提示.....

你这个是正常证书，不是mitmproxy生成的

**Comment by zhaodice** [comment]
如果实在弄不明白我不介意把我弄好的私服给你连着玩

**Comment by YansHJ** [comment]
> 如果实在弄不明白我不介意把我弄好的私服给你连着玩

其实我主要是想自己搭一下，玩都是次要的，因为本地也可以玩，不过还是谢谢你

**Comment by YansHJ** [comment]
> > > 确实那问题可能就出在你自签名根证书有问题了……我的建议是你本地先搭，别搞远程服务器那么骚的操作，本地直接改hosts就行了不需要什么mitmproxy
> > > ![EKS PP7VE39VIRX3}Y3F~PH](https://user-images.githubusercontent.com/56545309/171026836-aa229b18-f747-4333-bb9e-f30c037afebe.png)
> > 
> > 
> > 本地有测试过，不需要改任何设置就可以进去，另外这个证书安装之后，“安装证书”还在，并且访问依旧是红色提示.....
> 
> 你这个是正常证书，不是mitmproxy生成的

在红色提示下点开证书哪里没有办法“查看证书”，所以没有办法保存证书

**Comment by zhaodice** [comment]
讲真mitmproxy这玩意我当时也没搭成功，我是自己用VPN管道+自签证书+hosts修改实现的远程私服，可能没什么参考价值，困了先去睡了

**Comment by AZthemute** [comment]
您是否只是尝试重新安装证书？

我不起作用，您可以尝试删除所有内容并从零开始。

**Comment by YansHJ** [comment]
> 讲真mitmproxy这玩意我当时也没搭成功，我是自己用VPN管道+自签证书+hosts修改实现的远程私服，可能没什么参考价值，困了先去睡了

谢谢！晚安

**Comment by YansHJ** [comment]
> 您是否只是尝试重新安装证书？
> 
> 我不起作用，您可以尝试删除所有内容并从零开始。

您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了

**Comment by YansHJ** [comment]
> 您是否只是尝试重新安装证书？
> 
> 我不起作用，您可以尝试删除所有内容并从零开始。

您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了

**Comment by AZthemute** [comment]
> > 您是否只是尝试重新安装证书？
> > 我不起作用，您可以尝试删除所有内容并从零开始。
> 
> 您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了

好吧，那不是解决方案...

我知道Windows中有一个显示证书的程序，但是我以前没有使用过它，也不知道该程序中的证书在哪里显示。

**Comment by AZthemute** [comment]
> > > 您是否只是尝试重新安装证书？
> > > 我不起作用，您可以尝试删除所有内容并从零开始。
> > 
> > 
> > 您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了
> 
> 好吧，那不是解决方案...
> 
> 我知道Windows中有一个显示证书的程序，但是我以前没有使用过它，也不知道该程序中的证书在哪里显示。

![image](https://user-images.githubusercontent.com/104761702/171030274-71c1834f-3aeb-490a-bcd5-3840900d93ee.png)
尝试运行certmgr.msc，看看是否在这里。（我正在使用翻译 - 对不起，它是英语的）

**Comment by YansHJ** [comment]
> > > > 您是否只是尝试重新安装证书？
> > > > 我不起作用，您可以尝试删除所有内容并从零开始。
> > > 
> > > 
> > > 您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了
> > 
> > 
> > 好吧，那不是解决方案...
> > 我知道Windows中有一个显示证书的程序，但是我以前没有使用过它，也不知道该程序中的证书在哪里显示。
> 
> ![image](https://user-images.githubusercontent.com/104761702/171030274-71c1834f-3aeb-490a-bcd5-3840900d93ee.png) 尝试运行certmgr.msc，看看是否在这里。（我正在使用翻译 - 对不起，它是英语的）

非常感谢你！我想我突然解决了这个问题，在连接到远端服务器的代理时访问http://mitm.it/，他会自动弹出下载证书的页面，安装下载的证书就可以，尝试过后解决了4206的问题，但是却出现了连接超时的新问题，正在想办法解决

**Comment by YansHJ** [comment]
> > > > 您是否只是尝试重新安装证书？
> > > > 我不起作用，您可以尝试删除所有内容并从零开始。
> > > 
> > > 
> > > 您说的删除所有内容重新开始是指什么？服务端的话我有重新安装过很多次了
> > 
> > 
> > 好吧，那不是解决方案...
> > 我知道Windows中有一个显示证书的程序，但是我以前没有使用过它，也不知道该程序中的证书在哪里显示。
> 
> ![image](https://user-images.githubusercontent.com/104761702/171030274-71c1834f-3aeb-490a-bcd5-3840900d93ee.png) 尝试运行certmgr.msc，看看是否在这里。（我正在使用翻译 - 对不起，它是英语的）

非常感谢你！我想我突然解决了这个问题，在连接到远端服务器的代理时访问http://mitm.it/，他会自动弹出下载证书的页面，安装下载的证书就可以，尝试过后解决了4206的问题，但是却出现了连接超时的新问题，正在想办法解决

**Comment by AZthemute** [comment]
这是一种解脱 - 我很高兴现在可以工作！ 您可以显示连接超时错误还是您认为可以自己解决这个问题？

**Comment by YansHJ** [comment]
> 这是一种解脱 - 我很高兴现在可以工作！ 您可以显示连接超时错误还是您认为可以自己解决这个问题？

这个问题也已经解决掉了，只需要在配置文件里“publicip”和“port”填写对应的ip和端口就行了，感谢！

**Comment by YansHJ** [comment]
> 讲真mitmproxy这玩意我当时也没搭成功，我是自己用VPN管道+自签证书+hosts修改实现的远程私服，可能没什么参考价值，困了先去睡了

我昨天晚上弄好了证书可以进去游戏了，但是早上起来再试的时候显示要更新资源，你的服务器有这个提示吗？我已经在官服哪里预载了，但是连接自己的服务器时游戏内还需要再下载10G的资源
