### ISSUE TITLE
开始游戏一直在下载更新 Start the game and keep downloading updates 

### ISSUE THREAD

**Issue by YansHJ** [Melledy/Grasscutter#1116]
### Discussed in https://github.com/Grasscutters/Grasscutter/discussions/1115

<div type='discussions-op-text'>

<sup>Originally posted by **YansHJ** May 31, 2022</sup>
使用的远端服务端，本地主机客户端形式，今天本来官服要更新，本地已经提前下载预载更新包并解压，但是连接服务器时显示还需要下载10GB资源，请问这个该如何解决呢
![_KL4NR~L$OY~7QGAAJFI}JS](https://user-images.githubusercontent.com/56545309/171070161-552057e6-1384-4c09-8c2a-44375cd5684f.png)
</div>

**Comment by YansHJ** [comment]
The remote server used is in the form of a local host client. Today, the official server was supposed to be updated. The local has downloaded and decompressed the preloaded update package in advance, but it still needs to download 10GB resources when connecting to the server. How can I solve this problem

**Comment by YansHJ** [comment]
在更新一段时间后，显示下载失败或网络错误，退出重进后游戏会卡住，变成白屏，客户端一键修复却显示没有问题

After updating for a period of time, the download failure or network error is displayed. After exiting and entering again, the game will get stuck and become a white screen. The client can repair it with one click, but it shows no problem

**Comment by YansHJ** [comment]
之后我从客户端“删除下载资源”之后，游戏可以正常进入，但连接自己的服务器时又需要重新开始下载10G的资源

After I "delete the download resources" from the client, the game can enter normally, but when I connect to my own server, I need to restart downloading 10g resources

**Comment by YansHJ** [comment]
但其实客户端已经存在关于中国服务器的更新资源包，连接到自己的服务器之后却需要重新开始下载更新资源包，这里的更新资源包是否是以国际版本为准的？有什么办法可以让中国版本更新的资源包生效吗

But in fact, the client already has the update resource package for the Chinese server. After connecting to its own server, it needs to start downloading the update resource package again. Is the update resource package here based on the international version? Is there any way to make the resource pack updated by the Chinese version effective

**Comment by zhaodice** [comment]
已经合到dev了，再试试看?

**Comment by YansHJ** [comment]
> 已经合到dev了，再试试看?

需要从dev分支重新下载服务端，然后配置代理吗

**Comment by YansHJ** [comment]
> 已经合到dev了，再试试看?

dev-world-script吗

**Comment by YansHJ** [comment]
> 已经合到dev了，再试试看?

可能还得打扰你一下，我按你说的拉了v1.1.2-dev的代码之后，重新部署了服务器和代理，这个时候可以正常登陆了，并且可以到达“点击进入”的地方，这个时候点击进入会白屏一阵子，然后会弹出来一个“网络响应超时，是否重新登录”的提示，游戏服务端日志也反复的出现“connect”和“disconnect”，是我的代理出了问题吗
