### ISSUE TITLE
[Bug] 2.7点击进入游戏后无限白屏 出现网络连接超时提醒

### ISSUE THREAD

**Issue by rplord** [Melledy/Grasscutter#1118]
使用游戏自带更新 Lan代理连接 [Grasscutter]版本1.1.2

**Comment by zhaodice** [comment]
2.7已经合到dev了，再试试看?

**Comment by a15546787953** [comment]
是Code里那个1.1.2-dev吗

**Comment by rplord** [comment]
> 是Code里那个1.1.2-dev吗

是

**Comment by rplord** [comment]
> 2.7已经合到dev了，再试试看?

没用 还是白屏

**Comment by YansHJ** [comment]
> > 2.7已经合到dev了，再试试看?
> 
> 没用 还是白屏

尝试关闭防火墙

**Comment by xmgnew** [comment]
白屏可能是数据库问题，2.6版本跟2.7版本数据库不兼容，我之前也遇到过这个问题

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**
 
GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord] (https://discord.gg/T5vZU6UyeG) ，里面有专门的中文频道。
