### ISSUE TITLE
v1.1.2-dev进入游戏长时间白屏弹出“网络响应超时”[Bug] 

### ISSUE THREAD

**Issue by YansHJ** [Melledy/Grasscutter#1124]
服务端使用的是v1.1.2-dev，在服务器关闭所有防火墙情况下，连接服务器可以正常登录，之后点击进入游戏会长时间处于白屏状态，之后弹出“网络响应超时，是否重新登陆”
The server uses v1.1.2-dev. when the server shuts down all firewalls, the connected server can log in normally. After clicking to enter the game, it will be in a white screen for a long time, and then the "network response timeout, whether to log in again" pop up
![QQ截图20220531132924](https://user-images.githubusercontent.com/56545309/171100778-ab61d73f-4322-414b-ac60-a532f7086521.png)
![QQ截图20220531133155](https://user-images.githubusercontent.com/56545309/171100786-2ea07e11-c9a8-4902-9148-7aaa9fb65f32.png)
![`(F~FAO%T1QT(_ E6LEXK T](https://user-images.githubusercontent.com/56545309/171100790-e03a2e07-e8e4-4d6c-b6ce-b322e688ecf4.png)
![B05(6Y% 9APOV}(WH`07WHB](https://user-images.githubusercontent.com/56545309/171100980-780a212b-e614-4faa-bfcf-b62e6b13a71f.png)

**Comment by YansHJ** [comment]
![`(F~FAO%T1QT(_ E6LEXK T](https://user-images.githubusercontent.com/56545309/171103118-90888168-1861-45a9-b507-fe504e613d34.png)

**Comment by AZthemute** [comment]
您在本地运行吗？ 我的看起来像这样。
![image](https://user-images.githubusercontent.com/104761702/171111335-c71a5af9-8d95-49c3-8833-b30a91603777.png)
![image](https://user-images.githubusercontent.com/104761702/171111375-f4a2c16c-a7de-4b3a-a3e1-e318250ce5ee.png)

**Comment by YansHJ** [comment]
> 您在本地运行吗？ 我的看起来像这样。 ![image](https://user-images.githubusercontent.com/104761702/171111335-c71a5af9-8d95-49c3-8833-b30a91603777.png) ![image](https://user-images.githubusercontent.com/104761702/171111375-f4a2c16c-a7de-4b3a-a3e1-e318250ce5ee.png)

不，我是远程机器运行服务端，本地机器运行客户端，服务端与客户端不在同一台机器上

**Comment by AZthemute** [comment]
啊，好吧...我没有经验，对不起。

但是，当数据库损坏时，我已经得到了这个白屏。 您可以尝试制作一个新帐户，以防问题以某种方式与此相关。

**Comment by YansHJ** [comment]
> 啊，好吧...我没有经验，对不起。
> 
> 但是，当数据库损坏时，我已经得到了这个白屏。 您可以尝试制作一个新帐户，以防问题以某种方式与此相关。

好的，还是很感谢你，我重新创建一个账户之后再尝试一下

**Comment by AZthemute** [comment]
哦，最后一件事，请确保您的游戏和服务器都在2.7上。 我想过期的游戏或服务器可能会引起此问题。

**Comment by YansHJ** [comment]
> 哦，最后一件事，请确保您的游戏和服务器都在2.7上。 我想过期的游戏或服务器可能会引起此问题。

服务器时v1.1.2-dev的版本，游戏客户端也是最新的，但是我也不确定会不会是这方面的影响

**Comment by zhaodice** [comment]
安卓端显示"网络错误"不知道是不是更新了加强了ssl验证

**Comment by AZthemute** [comment]
> > 哦，最后一件事，请确保您的游戏和服务器都在2.7上。 我想过期的游戏或服务器可能会引起此问题。
> 
> 服务器时v1.1.2-dev的版本，游戏客户端也是最新的，但是我也不确定会不会是这方面的影响

那应该没关系。


> 安卓端显示"网络错误"不知道是不是更新了加强了ssl验证

因此，您是说您需要先登录实际游戏？

**Comment by YansHJ** [comment]
> 安卓端显示"网络错误"不知道是不是更新了加强了ssl验证

你那边也出现问题了吗，我这边是在登陆进入游戏后白屏，然后提示“网络响应异常”

**Comment by YansHJ** [comment]
> > > 哦，最后一件事，请确保您的游戏和服务器都在2.7上。 我想过期的游戏或服务器可能会引起此问题。
> > 
> > 
> > 服务器时v1.1.2-dev的版本，游戏客户端也是最新的，但是我也不确定会不会是这方面的影响
> 
> 那应该没关系。
> 
> > 安卓端显示"网络错误"不知道是不是更新了加强了ssl验证
> 
> 因此，您是说您需要先登录实际游戏？

我用新建的账户登录游戏后，也出现了一样的问题

**Comment by AZthemute** [comment]
> 我用新建的账户登录游戏后，也出现了一样的问题

抱歉，这不是问题，我不确定该怎么办。 也许如果您不能登录官方服务器，那可能是问题所在，但我不确定。

**Comment by YansHJ** [comment]
> > 我用新建的账户登录游戏后，也出现了一样的问题
> 
> 抱歉，这不是问题，我不确定该怎么办。 也许如果您不能登录官方服务器，那可能是问题所在，但我不确定。

我有尝试登陆过官方服务器，是可以正常登陆的，还是很感谢你

**Comment by zhaodice** [comment]
> > > 哦，最后一件事，请确保您的游戏和服务器都在2.7上。 我想过期的游戏或服务器可能会引起此问题。
> > 
> > 
> > 服务器时v1.1.2-dev的版本，游戏客户端也是最新的，但是我也不确定会不会是这方面的影响
> 
> 那应该没关系。
> 
> > 安卓端显示"网络错误"不知道是不是更新了加强了ssl验证
> 
> 因此，您是说您需要先登录实际游戏？

1.I login official server and update successfull
2.switching to grasscutter server
3.login failure,it shows "network error"

**Comment by zhaodice** [comment]
奇怪了，明明用浏览器打开显示grasscutter啊，证书也正常，发生什么事了!

**Comment by YansHJ** [comment]
我发现了一个新的状况，当我创建了一个UID为1111111的账户后，我用这个新的账户去登录时，服务端日志显示的却是“UID 100004”，我不确定这个是不是对现状有什么影响

**Comment by YansHJ** [comment]
> 奇怪了，明明用浏览器打开显示grasscutter啊，证书也正常，发生什么事了!

我这边也是一切正常，昨天凌晨v.1.1最后成功登陆上去也正常进入游戏，早上官服更新之后进私服就显示“下载资源”，更新到v.1.1.2-dev之后又出现了现在这个“网络响应超时”的提示

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**
 
GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord] (https://discord.gg/T5vZU6UyeG) ，里面有专门的中文频道。
