### ISSUE TITLE
[Feature Request] /sendbroadcast command

### ISSUE THREAD

**Issue by crowity** [Melledy/Grasscutter#1126]
Can someone make /sendbroadcast command like this
![Screenshot 2022-05-31 123001](https://user-images.githubusercontent.com/104195873/171141873-202d49cb-cbe5-4e97-97c1-d7775f6e4ac3.png)
?

**Comment by lunaticwhat** [comment]
already in making ;)

**Comment by crowity** [comment]
Oh, Thank you then
