### ISSUE TITLE
[Feature Request] command usage is confusing

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1134]
**Is your feature request related to a problem? Please describe.**

command usage is confusing, especially when uid is required
**Describe the solution you'd like**

hope to change
**Describe alternatives you've considered**

use uid directly or add @
**Additional context**

**Comment by AZthemute** [comment]
What command are you talking about? If you mean commands in general can we have an example?

**Comment by Birdulon** [comment]
Might need translations for https://github.com/Grasscutters/Grasscutter/wiki/Commands#targeting
