### ISSUE TITLE
[Feature Request] Quests / Missions / Story

### ISSUE THREAD

**Issue by TropicLegend** [Melledy/Grasscutter#1138]
**Is your feature request related to a problem? Please describe.**
Playing on my Grasscutter Server is already very fun. But it gets boring after some time. I would like to be able to play quests /  the story.
**Describe the solution you'd like**

I would like to be able to play the / some of the quests. The story of the anime game is very fun. Combined with the Grasscutter Server it would be awesome.
**Describe alternatives you've considered**

I could also imagine some custom quests or maybe a plugin that adds the story quests.
**Additional context**

none

**Comment by GiRx8** [comment]
Please read the wiki etc, quests are there just have to start them manually, it’s currently being worked on :)

**Comment by TropicLegend** [comment]
> Please read the wiki etc, quests are there just have to start them manually, it’s currently being worked on :)

Could you please send a link to that?

**Comment by TropicLegend** [comment]
> Please read the wiki etc, quests are there just have to start them manually, it’s currently being worked on :)

oh, and thanks for the information. I found it.
Thank your for your help

**Comment by Scirese** [comment]
This will depends on how far the `dev-world-script` branch can go :(
It might be very difficult to implement this feature...
And anime game may remove lua scripts from client  in 2.8

**Comment by AZthemute** [comment]
> This will depends on how far the `dev-world-script` branch can go :( It might be very difficult to implement this feature... And anime game may remove lua scripts from client in 2.8

Why would they remove it?

**Comment by 4Benj** [comment]
> Why would they remove it

Unneeded junk on client and to fuck with PS devs

**Comment by Birdulon** [comment]
> Why would they remove it?

They had no reason to include most of it in the first place. Beta for upcoming version has most of them removed.

**Comment by lunaticwhat** [comment]
This is will/might be implement in the future. 
We cannot be 100% sure that it will be implemented because it's not easy to do and need alot of things before that.
