### ISSUE TITLE
[Feature Request] Spawn a monster with infinite HP

### ISSUE THREAD

**Issue by CarterLi** [Melledy/Grasscutter#1141]
**Is your feature request related to a problem? Please describe.**

Grasscutter is a good place to test characters and practice combos. However the problem is that enemies are too weak ( even with 200 level ) since we all have C6R5 and perfect artifacts.

**Describe the solution you'd like**

I'd like to have a target that can't move and have infinite HP.

**Describe alternatives you've considered**

`/spawn 24010101 1 200` every time

**Additional context**

N/A

**Comment by Liujunhua007** [comment]
+1

**Comment by daxiwow** [comment]
+1

**Comment by millet6** [comment]
\Server2.8\grasscutter\resources\ExcelBinOutput\MonsterExcelConfigData.json 你可以修改怪物初始属性 You can modify the monster's initial attributes

**Comment by Birdulon** [comment]
`/spawn <monsterId> 0hp` creates monsters with infinite hp as of #1777 (08f361954a1232656e37f92d4b579c3b4856c9f5)
