### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by davidebic** [Melledy/Grasscutter#1143]
When downloading resources (no clue why it needs to) it will repeatedly disconnect the client. After rebooting the client it won't even open anymore.

**Comment by korcher** [comment]
I have the same

**Comment by Octelly** [comment]
Same issue

**Comment by lunaticwhat** [comment]
Next time please make sure to create an issue with more detailed informations especially which branch you have used. 
You can visit our Discord server for support with this issue because I believe it wasn't GC fault.

**Comment by davidebic** [comment]
> 

The discord is at max users. I cannot join. I would have asked there if I could.

**Comment by lunaticwhat** [comment]
> > 
> 
> The discord is at max users. I cannot join. I would have asked there if I could.

That can't be. Our server is still joinable can you please check if you are at 100 servers limitation ?
