### ISSUE TITLE
[Bug]Clicking to enter in the Rift doesn't work at all

### ISSUE THREAD

**Issue by Aesthetical2004** [Melledy/Grasscutter#1144]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by TukanDev** [comment]
Instructions unclear reproduced error -69420 instead

**Comment by KiminaNatsuki** [comment]
"the rift"
aka he means domains lol

**Comment by KingRainbow44** [comment]
please fill out the bug report template correctly, then make another issue. this issue could exist on stable, but not on development, etc.
