### ISSUE TITLE
[Feature Request] How to modify a drop in a dungeon？

### ISSUE THREAD

**Issue by StillMi** [Melledy/Grasscutter#1146]
I want to know how to modify the drop in the dungeon instead of just dropping the mora

**Comment by Thaddeus5555555** [comment]
Approve

**Comment by Birdulon** [comment]
If you want regular enemy drops in domains, you can just remove this check https://github.com/Grasscutters/Grasscutter/blob/f6d01928180c0756d87497df703d1fb35eb8cc5c/src/main/java/emu/grasscutter/game/world/Scene.java#L405-L408
i.e. replace it with `if (target instanceof EntityMonster) { `

**Comment by KiminaNatsuki** [comment]
> If you want regular enemy drops in domains, you can just remove this check
> 
> https://github.com/Grasscutters/Grasscutter/blob/f6d01928180c0756d87497df703d1fb35eb8cc5c/src/main/java/emu/grasscutter/game/world/Scene.java#L405-L408
> 
> 
> i.e. replace it with `if (target instanceof EntityMonster) { `

i think he meant domain rewards and not enemy drop

**Comment by Birdulon** [comment]
> i think he meant domain rewards and not enemy drop

I don't know any domains that drop mora but I guess the one-time ones might. I guess domain enemies don't normally drop mora either.

**Comment by StillMi** [comment]
> > i think he meant domain rewards and not enemy drop
> 
> I don't know any domains that drop mora but I guess the one-time ones might. I guess domain enemies don't normally drop mora either.

I mean the drop of the relic Dungeon
It does not refer to the dropped items of the monster itself, but how to modify the reward part after completing the dungeon

**Comment by jitfaced** [comment]
You can modify /data/Drop.json to change droplists of monsters. As to dungeon rewards, maybe in other json file?

**Comment by lingzn12** [comment]
I also want to know how to solve this problem.

**Comment by lingzn12** [comment]
If there is a solution, please @ me.

**Comment by KiminaNatsuki** [comment]
Closing inactive issues to clear up workspaces.
