### ISSUE TITLE
[Bug] Error when loading json and huge file download.

### ISSUE THREAD

**Issue by DesertStar1706** [Melledy/Grasscutter#1159]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**
I got the same errors when loading json files, It's happen with AvatarCurveExcelConfigData.json, MonsterCurveExcelConfigData.json and WeaponCurveExcelConfigData.json. (Screenshot 1)

And when I login, the game force me to download additional 20~25GB files. It's alway stop at ~14%. (Screenshot 2)

**Which branch did you use?**
Stable v1.1.1

**Screenshots**

![image](https://user-images.githubusercontent.com/59309732/171626374-dd4ee4e8-b14b-47bd-832c-8598f6f0a513.png)
![image](https://user-images.githubusercontent.com/59309732/171626354-0988b3e2-d07a-4295-be8a-391ffb5d251f.png)

**Additional context**

**Comment by tamilpp25** [comment]
This happened to me when I used stable branch use development instead that might fix it

**Comment by AZthemute** [comment]
Download grasscutter resources again.

Also open the game on the OFFICIAL server first instead of grasscutter to make sure it is fully up to date, as the game gets daily small patches after every large patch.

**Comment by ElysionAbyss** [comment]
> Download grasscutter resources again.
> 
> Also open the game on the OFFICIAL server first instead of grasscutter to make sure it is fully up to date, as the game gets daily small patches after every large patch.

It's no use.

**Comment by FSKiller** [comment]
Stable version is on 2.6 if you updated the game you won't be able to use the stable branch. Switch to development
