### ISSUE TITLE
[Bug] 严重回档问题/Severe non-saving data problems

### ISSUE THREAD

**Issue by qinastar** [Melledy/Grasscutter#1162]
//抱歉上个is说的不明确，重新说明一下，也有人说过是数据库连接过多，但是我在16H32G50M服务器和腾讯云的8H16G都测试过，占用很低也会。
//English part from the translation, may not be accurate

以下是来自多人测试结果：
神像可以去回血复活但是不能原地下线 
回血复活后 去其他地方没有存档行为就下线也会死回档

存档行为可以是 抽卡 打怪掉的原石 风印
我复活回血 然后去了刷怪点抽了个卡 不会回档 这个我试了4次
复活回血去刷怪点 打怪看到捡了 原石 风印后下线 也不会回档 这个我试了4次
复活回血 然后啥也不干 就传送了一下一次就死回档

我试了一小时进死回档的概率不大 可能联机也有bug
但是神像上下线 吸血后啥也不干就挪了位置的百分百回
不过都是浅回 抽个卡  甚至打个怪捡掉落的东西就不回了

The idol can go back to the blood to revive but can not go offline in place 
After the resurrection of blood to go elsewhere without archiving behavior will also die back to the file

Archiving behavior can be card draw, fight the original stone dropped by the monsters wind seal
I resurrected blood and then went to the point of drawing a card will not return to the file I tried 4 times
Resurrected to blood to go to the brush point, see the monsters pick up the original stone, wind seal after going offline also will not return to the file this I tried 4 times
resurrect blood and then do nothing but teleport once to die back to the file

I tried for an hour into the probability of dying back into the file is not large, perhaps online also has a bug
But the idol up and down the line after the blood sucking do nothing to move the location of 100% back
But are shallow back to draw a card or even a monster to pick up the dropped things will not return

Translated with www.DeepL.com/Translator (free version)

**Comment by zhaodice** [comment]
我试过，我在测试私服的时候，跑几步路测试了几下，然后结束服务器，重新再测试的时候发现自己回到了原地，可能是数据刷写有时间间隔？

**Comment by zhaodice** [comment]
回档bug发生时有重启过服务器吗

**Comment by qinastar** [comment]
没有重启过，一直开着的

> 回档bug发生时有重启过服务器吗

**Comment by zhaodice** [comment]
死回档是什么意思？退出重新进游戏就回档了还是？

**Comment by qinastar** [comment]
应该是指一直被回档循环，无法保存游戏了

> 死回档是什么意思？退出重新进游戏就回档了还是？

**Comment by zhaodice** [comment]
嗯，我想了解一下，无法保存游戏的状态：

1.无法保存游戏是指退出游戏重新进发现回档吗？
2.出现死回档通常需要做什么才能解除这个状态？
3.死回档发生时控制台有没有错误输出？
4.死回档时CPU占用和内存占用情况是什么？

**Comment by qinastar** [comment]
要不你发个联系方式，你上我服务器看看？

> 嗯，我想了解一下，无法保存游戏的状态：
> 
> 1.无法保存游戏是指退出游戏重新进发现回档吗？ 2.出现死回档通常需要做什么才能解除这个状态？ 3.死回档发生时控制台有没有错误输出？ 4.死回档时CPU占用和内存占用情况是什么？

**Comment by zhaodice** [comment]
q357826834

**Comment by AldarisX** [comment]
自己写个插件定时保存下player就好了。
退出游戏的逻辑有，直接照搬

**Comment by zhaodice** [comment]
> AldarisX

问题的根源在于服务端根本没有处理好多个客户端登陆同一个账号的情况，导致数据竞争，我已经修了（增强了顶号机制）
