### ISSUE TITLE
[Bug] 客户端已断开连接

### ISSUE THREAD

**Issue by glimjoe** [Melledy/Grasscutter#1167]
Discord无法发送短信，只能在这里问了
进入游戏点石门一片白屏，日志显示如下
09:30:36 <INFO:RegionHandler> [Dispatch] Client [0:0:0:0:0:0:0:1] request: query_region_list
09:30:38 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试使用 token 登录
09:30:38 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 已通过 token 登录，UID 为 10001
09:30:38 <INFO:DispatchHandler> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试登录
09:30:38 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 交换 token 成功
09:30:38 <INFO:DispatchHandler> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试登录
09:30:38 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa
09:30:45 <INFO:GameSession> 客户端 127.0.0.1 已连接
09:31:15 <INFO:GameSession> 客户端 127.0.0.1 已断开连接
09:31:16 <INFO:GameSession> 客户端 127.0.0.1 已连接

**Which branch did you use?**
  Grasscutter version: 1.1.2-dev
  Git Hash: 82775b4
![image](https://user-images.githubusercontent.com/3189762/171770540-7820e0a7-1c27-4b30-9052-07b89bff1f9d.png)

**Comment by zhaodice** [comment]
这是2.6吧

**Comment by AkkaXdXd** [comment]
https://nightly.link/Grasscutters/Grasscutter/workflows/build/development/Grasscutter.zip

update resources and data

**Comment by qingchunnh** [comment]
游戏版本 数据库里账号的版本 bin文件用的什么版本你都不说？

**Comment by Radminister** [comment]
大佬请问我第一次安装， 我也出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。

**Comment by glimjoe** [comment]
> 这是2.6吧



> 游戏版本 数据库里账号的版本 bin文件用的什么版本你都不说？

对不起两位。。。确实是资源错了。。。
