### ISSUE TITLE
[question] How to get Shougun into 2 state?

### ISSUE THREAD

**Issue by xiaomoL444** [Melledy/Grasscutter#1170]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

![image](https://user-images.githubusercontent.com/69074564/171803265-657356d8-d417-488f-a702-2a4cd6cb68b4.png)

**Additional context**

How to get her into 2 state?

i am using google translate

**Comment by MukeshKalaga** [comment]
The shogun 2nd state is a different monster
U need spawn monster with name "Raiden Ei"

**Comment by xiaomoL444** [comment]
> The shogun 2nd state is a different monster
U need spawn monster with name "Raiden Ei"

![image](https://user-images.githubusercontent.com/69074564/171814091-068a8218-4ad3-4982-947a-5c845dff8070.png)
it doesn't seem to work

**Comment by AZthemute** [comment]
The second state doesn't spawn automatically. What they mean is that the second state has to be manually spawned.
