### ISSUE TITLE
[Bug] Party roles cannot be removed

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1172]
Uninstalling the last character of team 3 will cause the game to freeze and the operation will fail

**Comment by Birdulon** [comment]
Can't reproduce on my end.
Something I noticed while testing is that with larger party sizes, removing the fourth member in the party menu will bring the fifth member into that slot. It may be possible that some of the weird placeholder avatars don't crash the game when added to the party but cause problems if they end up on the party screen, this might be related.

If you can reproduce this, feel free to reopen this issue with instructions.
