### ISSUE TITLE
[Bug] The character picture book cannot be opened

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1173]
The character picture book cannot be opened after using the /giveall command

**Comment by LDAsuku** [comment]
After some experimenting I figured out that this is caused by having costume id `0` in the player's `costumeList`, which was probably caused by having bad/old resources. I cannot reproducible this issue with latest Grasscutter and latest resources.

Editing the database manually fixes the issue.

**Comment by ZXAS007** [comment]
I want to delete the database again ..., alas, forget it, anyway, the holy relics need to be redirected
