### ISSUE TITLE
Compilation Error After pull  #114

### ISSUE THREAD

**Issue by Scirese** [Melledy/Grasscutter#118]
Compilation Error After pull  #114

/home/kiana/Grasscutter/src/main/java/emu/grasscutter/tools/Tools.java:34: 错误: 对于FileReader(java.lang.String,java.nio.charset.Charset), 找不到合适的构造器
                try (FileReader fileReader = new FileReader(Utils.toFilePath(Grasscutter.getConfig().RESOURCE_FOLDER + "TextMap/TextMapEN.json"), StandardCharsets.UTF_8)) {
                                             ^
    构造器 java.io.FileReader.FileReader(java.lang.String)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 java.io.FileReader.FileReader(java.io.File)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 java.io.FileReader.FileReader(java.io.FileDescriptor)不适用
      (实际参数列表和形式参数列表长度不同)
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/tools/Tools.java:40: 错误: 对于PrintWriter(java.lang.String,java.nio.charset.Charset), 找不到合适的构造器
                try (PrintWriter writer = new PrintWriter(fileName, StandardCharsets.UTF_8)) {
                                          ^
    构造器 java.io.PrintWriter.PrintWriter(java.io.Writer,boolean)不适用
      (参数不匹配; java.lang.String无法转换为java.io.Writer)
    构造器 java.io.PrintWriter.PrintWriter(java.io.OutputStream,boolean)不适用
      (参数不匹配; java.lang.String无法转换为java.io.OutputStream)
    构造器 java.io.PrintWriter.PrintWriter(java.nio.charset.Charset,java.io.File)不适用
      (参数不匹配; java.lang.String无法转换为java.nio.charset.Charset)
    构造器 java.io.PrintWriter.PrintWriter(java.lang.String,java.lang.String)不适用
      (参数不匹配; java.nio.charset.Charset无法转换为java.lang.String)
    构造器 java.io.PrintWriter.PrintWriter(java.io.File,java.lang.String)不适用
      (参数不匹配; java.lang.String无法转换为java.io.File)
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
2 个错误

>

**Comment by MlgmXyysd** [comment]
caused by https://github.com/Grasscutters/Grasscutter/pull/108

**Comment by MlgmXyysd** [comment]
caused by https://github.com/Grasscutters/Grasscutter/pull/108

**Comment by Scirese** [comment]
> caused by #108

how can  I fix it？

**Comment by MlgmXyysd** [comment]
just revert it

**Comment by Scirese** [comment]
> just revert it

ok
