### ISSUE TITLE
[Issue] Client disconnected 客户端 IP地址 已断开连接

### ISSUE THREAD

**Issue by ifloppy** [Melledy/Grasscutter#1188]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

Often disconnects when player joins game
经常在瓦加加入游戏时断开连接

**Which branch did you use?**

Actions https://github.com/Grasscutters/Grasscutter/actions/runs/2436914039

**Screenshots**

![image](https://user-images.githubusercontent.com/68799904/171970909-6f4a77dd-6b9f-41a3-ab14-32ddbb5dc7e6.png)

**Additional context**

![image](https://user-images.githubusercontent.com/68799904/171970917-1211f855-1a1a-4256-82ba-974946714a2d.png)
MongoDB is running normally
Using java 18

**Comment by zhaodice** [comment]
是第一次登陆还是重复登录?

**Comment by ifloppy** [comment]
> 是第一次登陆还是重复登录?

登录此前登陆过的账户时遇到

**Comment by zhaodice** [comment]
我看一下吧，这个顶号逻辑是我写的，我昨天晚上测试没发生问题，可以互相顶号

能具体说一下怎么复现的吗

**Comment by zhaodice** [comment]
什么叫瓦加加入游戏

**Comment by zhaodice** [comment]
是你一个人玩游戏还是多个人玩

**Comment by ifloppy** [comment]
> 什么叫瓦加加入游戏

玩家加入游戏，打错字了。多个人玩，但是互相没有顶号

**Comment by zhaodice** [comment]
能说以下稳定的复现过程吗，具体怎么做的

**Comment by ifloppy** [comment]
> 能说以下稳定的复现过程吗，具体怎么做的

启动除草机：java -jar grasscutter.jar

代理：whistle+proxifier

前面进游戏的时候会提示服务器错误，现在进去白屏然后超时，控制台中有报错
![image](https://user-images.githubusercontent.com/68799904/171974269-da036363-981f-4739-bdad-3814aaf7fd10.png)
![image](https://user-images.githubusercontent.com/68799904/171974346-82775df8-af62-41a2-8301-f71cbe6419cd.png)

**Comment by zhaodice** [comment]
试一下这个
https://github.com/Grasscutters/Grasscutter/actions/runs/2438103146
完事告诉我有没有解决问题

**Comment by zhaodice** [comment]
我加了个判断，在踢出重复登陆用户的同时会判断是否是同一个会话，是同一个会话就不属于重复登陆，不踢

**Comment by ifloppy** [comment]
> 试一下这个 https://github.com/Grasscutters/Grasscutter/actions/runs/2438103146 完事告诉我有没有解决问题

十分感谢。看起来问题已经得到了解决

**Comment by ifloppy** [comment]
> 我加了个判断，在踢出重复登陆用户的同时会判断是否是同一个会话，是同一个会话就不属于重复登陆，不踢

问题再一次出现，有人说一分钟断开连接一次
![image](https://user-images.githubusercontent.com/68799904/171978618-a0ffe745-7456-430a-b153-63dca397e3b3.png)
控制台中依然出现报错
![image](https://user-images.githubusercontent.com/68799904/171978875-0fc86638-d83b-4cd7-ba93-386a2b4f7dd3.png)

**Comment by zhaodice** [comment]
那是否出现kicked字样的报错？

**Comment by ifloppy** [comment]
> 那是否出现kicked字样的报错？

没有看到有关kicked的信息

**Comment by zhaodice** [comment]
看起来和我的代码无关，那么掉线的时候有没有什么征兆？比如右上角的ping开始转圈圈什么的，还是立即断

**Comment by ifloppy** [comment]
> 看起来和我的代码无关，那么掉线的时候有没有什么征兆？比如右上角的ping开始转圈圈什么的，还是立即断

没有征兆，直接断开连接

**Comment by zhaodice** [comment]
一共多少人在玩？

**Comment by ifloppy** [comment]
> 一共多少人在玩？

同时在线人数不超过3人，已注册的账户数量两百多个

**Comment by zhaodice** [comment]
> > 一共多少人在玩？
> 
> 同时在线人数不超过3人，已注册的账户数量两百多个

我好像又找到原因了，我稍后测试完pr一下

**Comment by zhaodice** [comment]
好了，试试看这个构建
https://github.com/Grasscutters/Grasscutter/runs/6736241573?check_suite_focus=true

**Comment by zhaodice** [comment]
没有问题可以等等，先游玩1小时，直到一直没有问题了就可以close了，我看得见

**Comment by zhaodice** [comment]
嗯...好像还是有点问题，白屏了，我再看看

**Comment by zhaodice** [comment]
https://github.com/Grasscutters/Grasscutter/runs/6736483362?check_suite_focus=true
好了，我自己用两个号来回切换顶号加同时登陆测试了5~6次，应该没有问题了
