### ISSUE TITLE
[Issue] 更新最新版的dev分支的服务端，客户端一直连接超时。Update the latest version of dev branch server, the client has been connection timeout

### ISSUE THREAD

**Issue by zizxzy** [Melledy/Grasscutter#1189]
Grasscutter version: 1.1.2-dev
在更新最新版的dev分支的服务端之后，我在本地window电脑搭建服务端，本地客户端可以正常使用。但是在云服务器搭建服务端，并且云服务器已允许443、8888、22102以及80端口通过防火墙，本地客户端一直连接超时。
After updating the server of dev branch of the latest version, I set up the server on the local Window computer, and the local client can be used normally,. But I set up the server on the cloud server, and the cloud server has allowed port 443 8888 22102 and port 80 to pass the firewall, but the connection of the local client has timed out.
![Snipaste_2022-06-04_09-15-26](https://user-images.githubusercontent.com/43310343/171977030-7d934f93-c90d-447f-a1d5-77f5bd608f89.png)
![Snipaste_2022-06-04_10-49-45](https://user-images.githubusercontent.com/43310343/171977053-736b95d3-a51d-4590-a80b-135597bada6d.png)

**Comment by zhaodice** [comment]
服务端有日志吗，还有，具体是哪个构建

**Comment by zhaodice** [comment]
https://github.com/Grasscutters/Grasscutter/runs/6735529443?check_suite_focus=true
可以先使用这个构建，看看有没有出问题，让我确认一下原因

**Comment by zizxzy** [comment]
> 服务端有日志吗，还有，具体是哪个构建

服务端日志并没有明显的报错，只有客户端在尝试登录的日志输出
![Snipaste_2022-06-04_11-28-26](https://user-images.githubusercontent.com/43310343/171979045-d5a146a3-f729-4ca1-bf56-40f1788e5a14.png)
使用的构建是通过`git clone -b development https://github.com/Grasscutters/Grasscutter.git`拉取的代码

**Comment by zhaodice** [comment]
> > 服务端有日志吗，还有，具体是哪个构建
> 
> 服务端日志并没有明显的报错，只有客户端在尝试登录的日志输出 ![Snipaste_2022-06-04_11-28-26](https://user-images.githubusercontent.com/43310343/171979045-d5a146a3-f729-4ca1-bf56-40f1788e5a14.png) 使用的构建是通过`git clone -b development https://github.com/Grasscutters/Grasscutter.git`拉取的代码

这不是被你按Ctrl+C退出了吗

**Comment by zhaodice** [comment]
这是linux服务器吗？

**Comment by zhaodice** [comment]
`tcpdump -i any udp port 22102`
在linux系统下使用这个命令，监听通往22102的数据包，看看有没有数据过来，如果没有，那就是你的线路有问题，客户端无法抵达服务器的22102端口

**Comment by zizxzy** [comment]
> > > 服务端有日志吗，还有，具体是哪个构建
> > 
> > 
> > 服务端日志并没有明显的报错，只有客户端在尝试登录的日志输出 ![Snipaste_2022-06-04_11-28-26](https://user-images.githubusercontent.com/43310343/171979045-d5a146a3-f729-4ca1-bf56-40f1788e5a14.png) 使用的构建是通过`git clone -b development https://github.com/Grasscutters/Grasscutter.git`拉取的代码
> 
> 这不是被你按Ctrl+C退出了吗

是的，最后按了退出而已，在登录期间并没有主动停止服务端的服务。

**Comment by zhaodice** [comment]
你用tcpdump监听一下数据包看看吧，判断一下是否有数据进来

**Comment by zhaodice** [comment]
你疯了？22102是UDP协议！！能连上才闹鬼了
![image](https://user-images.githubusercontent.com/63996691/171980752-d090e20b-693e-4092-b54d-d3a40afe95c6.png)

**Comment by zizxzy** [comment]
> 你疯了？22102是UDP协议！！能连上才闹鬼了 ![image](https://user-images.githubusercontent.com/63996691/171980752-d090e20b-693e-4092-b54d-d3a40afe95c6.png)

感谢大佬！！抱歉没注意协议问题。

**Comment by miaomiao2970** [comment]
我在此跪地感谢这位大佬。。。
