### ISSUE TITLE
[Issue] [GCAuth] 客户端 LYC 试图使用无效的一次性令牌登录。

### ISSUE THREAD

**Issue by Xiao-yux** [Melledy/Grasscutter#1191]
![image](https://user-images.githubusercontent.com/79674967/171991376-d8500c05-8c43-47ba-baeb-2de10003a4ce.png)
![image](https://user-images.githubusercontent.com/79674967/171991390-f6a113d6-12ea-434f-aee0-401e06e0169b.png)
I can still enter the game last night. Today, I updated the latest version (DEV).

**Comment by Xiao-yux** [comment]
What is the problem?

**Comment by Xiao-yux** [comment]
我就只换了最新的Grasscutter-Dev端就 无法登录游戏了，换回原来的也登录不了了

**Comment by AldarisX** [comment]
> 我就只换了最新的Grasscutter-Dev端就 无法登录游戏了，换回原来的也登录不了了

我用我自己的OAuth插件试了下没问题的，建议到GCAuth那边提（我代码都是照着GCAuth抄的）
I tried using my own OAuth plug-in. It's OK. I suggest going to GCAuth

**Comment by Radminister** [comment]
大佬请问我第一次安装， 我也出现了<WARN:AbstractHandler> No Server set for PrefixableHandler@1bb172dd{STARTING}（就是您的第二张图里的红色警告）是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。

**Comment by AldarisX** [comment]
> 大佬请问我第一次安装， 我也出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}（就是您的第二张图里的红色警告）是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。



> What is the problem?

更新GCAuth看看

**Comment by Xiao-yux** [comment]
问题解决了。（把GCAuth插件删了）

**Comment by Xiao-yux** [comment]
> 大佬请问我第一次安装， 我也出现了WARN：AbstractHandler No Server set for PrefixableHandler@1bb172dd{START}（就是您的第二张图里的红色警告）是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException： 提供了一个无效的参数。


4201是代理的问题，可能没有代理上？
