### ISSUE TITLE
[Bug] BUG REPORT all character with heal affects unable heal HP

### ISSUE THREAD

**Issue by CarrotHB** [Melledy/Grasscutter#1192]
all character with heal affects unable heal HP

**Comment by Adelaide114514** [comment]
应该是你核心落后了，2.6版本的已经修复过了2.7还不清楚

**Comment by CarrotHB** [comment]
> 应该是你核心落后了，2.6版本的已经修复过了2.7还不清楚

2.7 version heal skill dont work

**Comment by Liujunhua007** [comment]
我也是2.7，没修复啊

**Comment by Adelaide114514** [comment]
2.7确实还没有修复

**Comment by memetrollsXD** [comment]
Healing isn't implemented yet

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
