### ISSUE TITLE
Can't attack with skill, ult, or normal attack[Issue] 

### ISSUE THREAD

**Issue by Thunderings** [Melledy/Grasscutter#1197]
**Did you look for other closed issues that have the same problem?**
 Yes, and none have any solutions provided.

**Describe the issue**
 Every character in the game, other than the traveler picked at the beginning of the game, is unable to attack, use an elemental skill, or use their ultimate. I've researched information in the Discord server, I've checked for related issues in the Wiki... I've found many people having the same issue but no solution has been listed anywhere for me.

**Which branch did you use?**
 Stable

**Screenshots**
 
![image](https://user-images.githubusercontent.com/46850221/172033190-5dddd4f5-6ad4-4262-8dbb-49199e841797.png)
![image](https://user-images.githubusercontent.com/46850221/172033211-f42d2afd-0f38-4118-b2c6-9a776b963374.png)

**Additional context**
 I just want to figure this out so I can actually play around more in the server. Once I figure this out, I have solved all my issues by researching for answers before asking for help.

PS. Lawnmower bot is broken so I can't verify. Found the password on the Wiki but oh well, not that it matters when that bot is broken lol

**Comment by GanyusLeftHorn** [comment]
Try restarting your server.

**Comment by Thunderings** [comment]
I am thoroughly shocked that this actually worked... I've tried it before like 5 times and it didn't solve the issue... This is ridiculous, whatever lol

Thank you...

**Comment by zhaodice** [comment]
You need update resources folder with 2.7
