### ISSUE TITLE
[Bug] 深渊无法正确进入

### ISSUE THREAD

**Issue by qinastar** [Melledy/Grasscutter#1198]
如果当前深渊有人，那么点击按钮不会有反应（控制台会显示尝试进入，但是角色名字不对）
也许是不支持多个玩家进入，也许是错误的将别人送进去（有些人上线就在深渊里）

**Comment by basaka2022** [comment]
单人玩还好，人多就这样。

**Comment by mengguyi** [comment]
深渊在官服里就是不让联机的

**Comment by zhaodice** [comment]
> 深渊在官服里就是不让联机的

他的意思是，多人同时玩一个服务器(各自玩各自的世界)情况下只能一个人玩深渊，其他人进去就会乱传人

**Comment by zhaodice** [comment]
我也遇到过，就是玩着玩着突然就被传送进深渊里了，就很奇怪

**Comment by a15807495562** [comment]
Please use English

**Comment by QiuQian17** [comment]
深渊第九层一间怪刷新不完全导致后面打不了……可有解决？
