### ISSUE TITLE
[Bug] 部分角色被动天赋无效

### ISSUE THREAD

**Issue by Liujunhua007** [Melledy/Grasscutter#1199]
1.胡桃Q不能回血，E不会掉血
2.夜兰根据队伍不同元素增加生命值上限这个天赋无效
可能其他的还有，目前暂未发现，大家一起发现然后修改了吧~~~~

**Comment by Radminister** [comment]
大佬请问我第一次安装， 我也出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}（是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。

**Comment by jitfaced** [comment]
不止这些，数据库里修改currentHp与currentEnergy并不会同步到服务器里去，当然能量这个可能是我个人的问题（没见到别人提过）

**Comment by WhisperWithDelight** [comment]
所有和生命值有关的技能/命座功能全都还未开发

All skills/constellations related to HP are not implemented yet
