### ISSUE TITLE
it happens a error after login

### ISSUE THREAD

**Issue by qwertroot12345** [Melledy/Grasscutter#120]
after login screen,it returns error code  4206

**Comment by memetrollsXD** [comment]
It looks like the server isn't receiving HTTP requests from the game. Check your proxy settings (Fiddler, mitmproxy, etc)

**Comment by qwertroot12345** [comment]
do the ps choose the different version of the game?(such as zh/global/tw.hk,etc).if not ,it's very thankful to give a setting example below.

**Comment by qwertroot12345** [comment]
do the ps choose the different version of the game?(such as zh/global/tw.hk,etc).if not ,it's very thankful to give a setting example below.

**Comment by qwertroot12345** [comment]
> It looks like the server isn't receiving HTTP requests from the game. Check your proxy settings (Fiddler, mitmproxy, etc)

i found reason by http-pack,the log shows:

"frame": "",
  "stackTrace": "MoleMole.SuperDebug:LogToServerInternal(Boolean, String, LogType, Boolean, Int32, Int32, ErrorLevel, ErrorCategory, String, String)\nMoleMole.SuperDebug:LogToServer(LogType, String, Boolean, Int32, ErrorLevel, ErrorCategory, String, Boolean, Int32, String)\nMoleMole.SuperDebug:VeryImportantError(String, ErrorLevel, ErrorCategory, String, Boolean, Int32, Int32, String)\nPJFNILCOKCI:MoveNext()\nUnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)\n",
  "logStr": "**[RegionDispatch] Get Connect Error 'Error getting response stream (Write: The authentication or decryption has failed.):** SendFailure' for:https://127.0.0.1:443/query_cur_region?version=CNRELWin2.6.0&lang=2&platform=3&binary=1&time=825&channel_id=1&sub_channel_id=1&account_type=1&dispatchSeed=227fa47da8ce7dca statusCode:0 contentLength:0 contentType:",
  "logType": "Error",

how to fix it?

**Comment by MlgmXyysd** [comment]
ignore ssl verification

**Comment by guch8017** [comment]
Hey, I got the same issue. I have tried both Fiddler and Charles. It seems that the client successfully sent the 'query_region_list' request to the local server, but it didn't make a get request to the path 'query_cur_region' before it provide an error code 4206, which should be under the same hostname (dispatchosglobal.yuanshen.com:443).

**Comment by fumbling644o** [comment]
@guch8017 @qwertroot12345

Possible solutions:

1. Switch to Java 8u202 _as the documentation says you need to use_
2. Switch to the `development` branch and use Java 16 or newer. It has a different `keystore.p12` file that actually works on newer versions of Java.

**Comment by MlgmXyysd** [comment]
> Hey, I got the same issue. I have tried both Fiddler and Charles. It seems that the client successfully sent the 'query_region_list' request to the local server, but it didn't make a get request to the path 'query_cur_region' before it provide an error code 4206, which should be under the same hostname (dispatchosglobal.yuanshen.com:443).

Usually this is because of `query_region_list` returned an incorrect address. Try to change the `dispatchpublicip` to `dispatchosglobal.yuanshen.com` or `dispatchcnglobal.yuanshen.com`, the proxy daemon will automatically process this address to the correct host.

**Comment by guch8017** [comment]
> 

I tried to change this in config.json and then it provide an web connection timeout error. But after I changed it back to 127.0.0.1 it works. I don't know what happened but thanks for your answer.

**Comment by lihe07** [comment]
I also had this problem the first time I ran it. I figured out that it is caused by my local proxy settings.
I solved it by using the `start.cmd`.

**Comment by alt3ri** [comment]
Yes, by using the `start.cmd` file, it will automatically setup the proxy for you.

**Comment by Alan-Raddam** [comment]
> > Hey, I got the same issue. I have tried both Fiddler and Charles. It seems that the client successfully sent the 'query_region_list' request to the local server, but it didn't make a get request to the path 'query_cur_region' before it provide an error code 4206, which should be under the same hostname (dispatchosglobal.yuanshen.com:443).
> 
> Usually this is because of `query_region_list` returned an incorrect address. Try to change the `dispatchpublicip` to `dispatchosglobal.yuanshen.com` or `dispatchcnglobal.yuanshen.com`, the proxy daemon will automatically process this address to the correct host.

When using fiddler, this solved my problem when changing to dispatchosglobal.yuanshen.com. Restart the game is needed.

**Comment by KingRainbow44** [comment]
this isn't a support forum, go to the discord for support.
