### ISSUE TITLE
求教进入游戏问题

### ISSUE THREAD

**Issue by Radminister** [Melledy/Grasscutter#1204]
大佬请问我第一次安装， 出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}
![管理员_  Grasscutter 2022_6_6 10_06_18](https://user-images.githubusercontent.com/71959720/172082989-607468bd-0d0e-4c09-b354-01abf5e28542.png)
（是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。关了加速器，再重新启动游戏后能输入账户密码，但是登陆时显示登陆中转了几圈就没了。有一次好不容易登上了开门的时候显示账户验证失败12-4301总之就是啊登不上去，呜呜呜。

**Comment by Kurtivan2223** [comment]
If you set false in cdn mode in mojoconsole.json it will prompt that. Its no big issue as it won't affect your gameplay or server

**Comment by Kurtivan2223** [comment]
```
WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd
```

It doesnt affect anything


Also it might be a proxy issue, your proxy

**Comment by limchiawei9539** [comment]
确保你的打开次序正确。
server->proxy(我用的是mitmproxy)->game
行不通就全都重启

我都用自己制作的bat文件打开，方便

server_start.bat
-------------
@echo OFF
java -jar grasscutter-1.1.2-dev.jar
-------------

proxy_start.bat
-------------
@echo OFF
mitmdump -s proxy.py -k
-------------

proxy的设置（在network and  settings 那里）
![image](https://user-images.githubusercontent.com/43591034/172154362-9121fde2-a91d-417c-a77e-8c581e885cf1.png)

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
