### ISSUE TITLE
是否能为国内用户开通一个QQ交流群？

### ISSUE THREAD

**Issue by lovevol404** [Melledy/Grasscutter#1205]
国内的用户量还是比较多的吧，是否有考虑新增一个QQ群用来交流？

**Comment by CK-Tex** [comment]
![图片](https://user-images.githubusercontent.com/16620756/172091684-224dd356-4038-47fe-9df6-b000cda6e10c.png)
讨论请到Discord，这个地方是用于反馈开发相关问题的。
For discussion purposes please check Discord. Issue section is for escalation or feedback of development related topics.

**Comment by lovevol404** [comment]
@CK-Tex 作为国内用户，无法正常使用Discord，才在这里提出的这个问题。当然，如果违反了规范，可以关了这个 issue

**Comment by totallynotnochi** [comment]
@lovevol404 安装个VPN。Discord 有个支持中文的 server。https://discord.gg/8hj35Qn7

**Comment by zhaodice** [comment]
我qq已经连续因为提到"协议""数据包""逆向"这类字样被封了两个号了，真心不建议搞这玩意，搭个梯很难吗?一个php免费空间都能搭
https://github.com/koalabearguo/php-proxy

**Comment by Akka0** [comment]
No，你是想被真人快抓吗

**Comment by lovevol404** [comment]
因为我注册discord手机号无法使用，才提出的这个问题。此问题终结

**Comment by TomyJan** [comment]
我的建议是我们线下开一个集会门店吧
