### ISSUE TITLE
Failed to create gacha mappings.

### ISSUE THREAD

**Issue by 1011382654** [Melledy/Grasscutter#1207]
`
F:\Grasscutter>java -version
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

F:\Grasscutter>java -jar grasscutter.jar -handbook
17:38:21 <INFO:DataLoader> Creating default '.\data\gacha\mappings.js' data
17:38:22 <WARN:DataLoader> Failed to create gacha mappings.
java.lang.NullPointerException
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at emu.grasscutter.tools.Tools.getAvailableLanguage(Tools.java:45)
        at emu.grasscutter.tools.Tools.getLanguageOption(Tools.java:51)
        at emu.grasscutter.tools.Tools.createGmHandbook(Tools.java:35)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:89)
`

###  If I ignore it and continue running Java -jar grasscutter jar

`
17:49:55 <WARN:HttpServer> [Dispatch] 无法连接路由
java.lang.IllegalArgumentException: External file at '.\data\gacha\mappings.js' not found.
        at io.javalin.http.SinglePageHandler.add(SinglePageHandler.kt:33)
        at io.javalin.core.JavalinConfig.addSinglePageRoot(JavalinConfig.java:137)
        at express.Express.useStaticFallback(Express.java:85)
        at emu.grasscutter.server.http.handlers.GachaHandler.applyRoutes(GachaHandler.java:38)
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:121)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:136)
17:49:55 <WARN:HandbookRequestHandler> Resource does not exist: TextMap/TextMapEN.json
17:49:55 <WARN:GachaMappingRequestHandler> Resource does not exist: TextMap/TextMapEN.json
17:49:55 <INFO:Server> jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.3+8-LTS-111
17:49:56 <INFO:SslContextFactory> x509=X509@5909ae90(keystore_entry,h=[mydomain.com, localhost],w=[]) for Server@4489f60f[provider=null,keyStore=file:///F:/Grasscutter/keystore.p12,trustStore=null]
17:49:56 <INFO:AbstractConnector> Started ServerConnector@ef86c72{SSL, (ssl, http/1.1)}{0.0.0.0:443}
17:49:56 <INFO:Server> Started @5247ms
17:49:56 <INFO:Express> Server listening on http://0.0.0.0:443

`

**Comment by Kurtivan2223** [comment]
Put resources folder in the same directory

**Comment by 1011382654** [comment]
> Put resources folder in the same directory

I follow the steps here  https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server

When I first run "Java -jar grasscutter.jar", I am prompted to copy binoutput and excelbinoutput to the resource folder. I have followed the prompts.

Do you mean these two folders? It already exists.
Grasscutter/resources/BinOutput
Grasscutter/resources/ExcelBinOutput

**Comment by Kurtivan2223** [comment]
> > Put resources folder in the same directory
> 
> I follow the steps here https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server
> 
> When I first run "Java -jar grasscutter.jar", I am prompted to copy binoutput and excelbinoutput to the resource folder. I have followed the prompts.
> 
> Do you mean these two folders? It already exists. Grasscutter/resources/BinOutput Grasscutter/resources/ExcelBinOutput

You need to download resources if you havent and extract to same directory as .jar.

Then run server.

Resources_main/Resources -> resources

**Comment by 1011382654** [comment]
> > > 将资源文件夹放在同一目录中
> > 
> > 
> > 我按照这里的步骤https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server
> > 当我第一次运行“Java -jar Grasscutter.jar”时，系统提示我将 binoutput 和 excelbinoutput 复制到资源文件夹。我已按照提示进行操作。
> > 你是说这两个文件夹吗？它已经存在。Grasscutter/资源/BinOutput Grasscutter/资源/ExcelBinOutput
> 
> 如果没有，则需要下载资源并解压缩到与 .jar 相同的目录。
> 
> 然后运行服务器。
> 
> Resources_main/资源 -> 资源

After decompressing all the resource files, it runs normally. Thank you!
