### ISSUE TITLE
[Feature Request] HP features

### ISSUE THREAD

**Issue by Skitteyy** [Melledy/Grasscutter#1212]
I think we really need all the features characters have that use hp, like Jean healing on hit or burst, Hu Tao losing hp when her E is activated and gaining hp on burst, Xiao losing hp in burst mode, Kuki Shinobu losing hp when skill activated and her skill healing etc.

**Comment by lassedds** [comment]
It is being worked on but this stuff takes a while

**Comment by Skitteyy** [comment]
Oh okay! I can imagine it does take a while. Also wanted to ask if there's any way we can get Daily Comissions and working Domain Drops? Let me know if this is the wrong place to ask in.

**Comment by AZthemute** [comment]
> Oh okay! I can imagine it does take a while. Also wanted to ask if there's any way we can get Daily Comissions and working Domain Drops? Let me know if this is the wrong place to ask in.

No. That's also not implemented yet.

**Comment by KiminaNatsuki** [comment]
Closing inactive issues to clear up workspaces.

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
