### ISSUE TITLE
[feature suggest]Automate Download  

### ISSUE THREAD

**Issue by SunshineCloudTech** [Melledy/Grasscutter#1214]
when i deploy this project ,i find it should put BinOutput and ExcelBinOutput to  resources folder ,then the server can be start. 
why not add an config file to set about the version of gesnhin and automatly download the  BinOutput and ExcelBinOutput to the resource folder .

**Comment by SunshineCloudTech** [comment]
automatly download the BinOutput and ExcelBinOutput from mihoyo/hoyoverse server to the resource folder .

**Comment by Skitteyy** [comment]
Better Idea: just download the resources https://github.com/Koko-boya/Grasscutter_Resources

**Comment by lunaticwhat** [comment]
Sorry It won't never made.
