### ISSUE TITLE
[Issue] 无法抽卡

### ISSUE THREAD

**Issue by daxiwow** [Melledy/Grasscutter#1216]
1.12开发版

**Comment by daxiwow** [comment]
服务器内部错误

**Comment by daxiwow** [comment]
![77777](https://user-images.githubusercontent.com/54258434/172330980-6a011f1b-1d64-4a73-8ba7-30e699cf7e7a.jpg)

**Comment by daxiwow** [comment]
At first, it was normal. Later, I added the original stone. After drawing cards for many times, it didn't work

**Comment by black-zero358** [comment]
看看背包满了？
在设置里面修改上限

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
