### ISSUE TITLE
账号验证失败，12-4301[Issue] 

### ISSUE THREAD

**Issue by imio1314** [Melledy/Grasscutter#1217]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
