### ISSUE TITLE
支持IPv6吗？

### ISSUE THREAD

**Issue by qjxjdj** [Melledy/Grasscutter#1220]
如题

**Comment by zhaodice** [comment]
我认为是支持的，ipv6的支持取决于网卡而不是应用

**Comment by Scirese** [comment]
支持，但使用ipv6连接时最好把地址解析到域名

**Comment by q847633684** [comment]
我使用的就是ipv6地址，但是客户端的网络必须要有ipv6

**Comment by Melodramma** [comment]
> 



> 我使用的就是ipv6地址，但是客户端的网络必须要有ipv6

config.json咋配置的ipv6，我把ipv6填进去game/server之后客户端能登陆，点开大门就白屏了
