### ISSUE TITLE
Connection Time-out

### ISSUE THREAD

**Issue by MomentQYC** [Melledy/Grasscutter#1221]
**Did you look for other closed issues that have the same problem?**

Those issues didn't solve my problem.
**Describe the bug**

I built the server with the latest dev version on the remote server, changed all 127.0.0.1 in config.json to server IP, and modified the port. The client can log in, but entering the game will display a connection timeout. The server has no security group, and no firewall is set. The server packet capture shows that it can receive UDP requests from the client, and the server process only shows that the client is trying to log in.
**Screenshots**

![image](https://user-images.githubusercontent.com/62551256/172610836-7c47cb6c-6e1b-4a3c-a2e3-68720878bc3d.png)
![image](https://user-images.githubusercontent.com/62551256/172611861-e7ad53f3-e39a-496b-a721-7321ffc27eff.png)

**Additional context**

You can communicate with me in Chinese.
可以使用中文进行交流

**Comment by zhaodice** [comment]
是哪一个构建

**Comment by zhaodice** [comment]
那个improve KCP library 的构建只是个草稿，还没开发完并入 请认准development这个仓库的构建。

**Comment by MomentQYC** [comment]
> 那个improve KCP library 的构建只是个草稿，还没开发完并入 请认准development这个仓库的构建。

就是这个仓库直接git clone，然后出现的这个问题

**Comment by zhaodice** [comment]
> > 那个improve KCP library 的构建只是个草稿，还没开发完并入 请认准development这个仓库的构建。
> 
> 就是这个仓库直接git clone，然后出现的这个问题

1.你是本机搭建还是远程服务器搭建
2.你这个tcpdump是在服务端执行吗

**Comment by zhaodice** [comment]
我从图上看见的信息是，服务端可以正确接受来自客户端的信息，但出于某种原因，服务端没能成功对外发送回应包

**Comment by zhaodice** [comment]
所以在你的config.json文件中，服务端的端口和ip是否正确?

**Comment by MomentQYC** [comment]
> 所以在你的config.json文件中，服务端的端口和ip是否正确?

抱歉前面有点事，现在一一解答
我是在有公网IP的远程服务器搭建的，抓包行为是在服务器执行的
config.json关于IP和端口的部分如下，已知端口未被占用，且IP正确
![image](https://user-images.githubusercontent.com/62551256/172654936-463910d7-fbf0-4bef-93e9-e03b0136e19f.png)
![image](https://user-images.githubusercontent.com/62551256/172655136-6342ed8e-420a-4c75-aaf6-a2ef42e8b643.png)

**Comment by WorldlineChanger** [comment]
release中的1.1.2-dev版本jar文件有问题，换一个jar
使用https://nightly.link/Grasscutters/Grasscutter/workflows/build/development/Grasscutter.zip
或https://github.com/Grasscutters/Grasscutter/actions/runs/2438691606

**Comment by WorldlineChanger** [comment]
> release中的1.1.2-dev版本jar文件有问题，换一个jar 使用https://nightly.link/Grasscutters/Grasscutter/workflows/build/development/Grasscutter.zip 或https://github.com/Grasscutters/Grasscutter/actions/runs/2438691606

第一个链接的构建版本亲测没有问题了，推荐试试

**Comment by MomentQYC** [comment]
> 

![image](https://user-images.githubusercontent.com/62551256/172745462-afd89dd9-589b-4c00-b78c-9d9d00628610.png)
出现了新的问题，以前并没有的
没有找到keys及文件夹内含的文件
或许是版本不同导致配置什么的都不一样？
请问该怎么解决

**Comment by KiminaNatsuki** [comment]
This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

GitHub Issue 不是技術支持論壇。需要技術支持請去 Discord(https://discord.gg/T5vZU6UyeG) ，裡面有專門的中文頻道。

**Comment by a876691666** [comment]
我有同样的问题，远程服务器是可以收到UDP请求的，但是客户端还是连接超时
