### ISSUE TITLE
[Feature Request] How to modify avatarlimit？

### ISSUE THREAD

**Issue by Liujunhua007** [Melledy/Grasscutter#1227]
I saw this option in the config file. When I changed it to > 4, I entered the game and found that there was no change. How can I achieve the avatar limit > 4?
[](url)
![QQ截图20220609034129](https://user-images.githubusercontent.com/62129047/172706229-beeb9e2c-8fe9-440a-a222-a258248c0ba9.png)

**Comment by Skitteyy** [comment]
You've done it correctly. Now in-game type in the chat /team add character id slot (just type the id of the character. so Ayaka for example would be 1002 and the command already has the 100 written. so just type /team add 2 5 to add Ayaka with the id 2 to the 5th slot. Sorry im bad at explaining). To remove a character type /team remove slot (if I want to remove Ayaka now I do /team remove 5).

Hope I could help with my bad explaining.

You can use your keys 1-5 to switch to characters, you would need to manually switch to 6 and above (ALT and move the cursor)

Character IDs can be found in the Handbook or use the Lawnmower Discord bot in GC Discord

**Comment by Liujunhua007** [comment]
Thank you.I type "team add 10000065 5",then succeed.
