### ISSUE TITLE
 [22:24:07] [[34mINFO[0;39m] Place a copy of 'GenshinData' in the resources folder.

### ISSUE THREAD

**Issue by b9348** [Melledy/Grasscutter#123]
what can i do
git clone GenshinData, i did it

**Comment by KingRainbow44** [comment]
this error message is a bit misleading, **which is why you need to read the [wiki](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server)**

**Comment by b9348** [comment]
> this error message is a bit misleading, **which is why you need to read the [wiki](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server)**

Note: If you are running in the project's root directory (ie. you cloned the repo from GitHub and you are running the server in that folder), these files will be already be present.
cloned ， but still error[
![1](https://user-images.githubusercontent.com/41979647/164735695-7af7dc8b-b110-43b8-8a5c-ac80b5f889cb.png)
](url)

**Comment by ghost** [comment]
That's wrong.

![image](https://user-images.githubusercontent.com/86816436/164736385-fc8e8747-0405-4787-8232-65aa5dbf703e.png)

**Comment by ghost** [comment]
I suggest reading the instructions properly.

**Comment by alt3ri** [comment]
This is so _dumb_

**Comment by lilmayofuksu** [comment]
brain _aneurysm_

**Comment by b9348** [comment]
may '&gt; ， ， ，' need wiki , some occupations use =&gt;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月22日(星期五) 晚上10:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter]  [22:24:07] [[34mINFO[0;39m] Place a copy of &#39;GenshinData&#39; in the resources folder. (Issue #123)





 
brain aneurysm
 
&mdash;
