### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by MomentQYC** [Melledy/Grasscutter#1230]
**Is your feature request related to a problem? Please describe.**

No
**Describe the solution you'd like**

Add the main plot function similar to the official version, instead of unlocking the places that should not be unlocked according to the plot at the beginning.（添加类似官方版本的主线剧情功能，而不是一开始就解锁了按照剧情本不应该解锁的地方。）
**Describe alternatives you've considered**

Ditto
**Additional context**

可以使用中文交流，简中->繁中->English

**Comment by zhaodice** [comment]
等script 2.7看一下

**Comment by KingRainbow44** [comment]
Due to this issue being inactive, I will be closing it. Feel free to create another issue.
