### ISSUE TITLE
[Bug] Character healing skill has no effect

### ISSUE THREAD

**Issue by lingzn12** [Melledy/Grasscutter#1231]
I found a problem.
The role replying to HP cannot reply to HP.
I hope to fix this bug as soon as possible.

**Comment by 2y8e9h22** [comment]
**nb**

**Comment by HenryStrike** [comment]
Reply? You mean Healing right?
Do not use google translate LOL

**Comment by WorldlineChanger** [comment]
Trans: Heal

**Comment by zhaodice** [comment]
How humour the Chinglish is!

**Comment by lingzn12** [comment]
> 清真英语是多么幽默啊！
.
