### ISSUE TITLE
[Feature Request] 其他游戏单机的实现

### ISSUE THREAD

**Issue by Adelaide114514** [Melledy/Grasscutter#1238]
如何实现其他游戏的单机或者说是破解版本
How to implement stand-alone or cracked versions of other games

**Comment by casksteven** [comment]
现在的feature request真是越来越奇怪了

**Comment by dianwangwin** [comment]
> 如何实现其他游戏的单机或者说是破解版本 How to implement stand-alone or cracked versions of other games

使用你的脑子以解决问题

**Comment by casksteven** [comment]
https://blog.tomys.top/2022-04/genshintj/
可以看看评论区

**Comment by zhaodice** [comment]
欢乐提问区

**Comment by WorldlineChanger** [comment]
> https://blog.tomys.top/2022-04/genshintj/ 可以看看评论区

难绷

**Comment by kongqi404** [comment]
乐

**Comment by Saint-Theana** [comment]
> 如何实现其他游戏的单机或者说是破解版本 How to implement stand-alone or cracked versions of other games

lay down on your bed,close the light,close your eyes,and maybe then you would get what you want in the wonderland.

**Comment by lingzn12** [comment]
> https://blog.tomys.top/2022-04/genshintj/ 可以看看评论区

暴躁老哥

**Comment by Becods** [comment]
![image.png](https://s2.loli.net/2022/06/13/UlHEdK6jcifbL8h.png)

**Comment by Jay12358** [comment]
您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物

**Comment by QianXiao12138** [comment]
> 您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物

把宝箱功能关了呢？能出现怪物吗？

**Comment by Jay12358** [comment]
> 关了可以出现怪物， 但是完全相同的文件在自己的电脑系统上一切正常，可以出现宝箱和怪物等

**Comment by Jay12358** [comment]
可以出现怪物，我检查了一切可以检查的，完全相同的包放在我的电脑上就可以正常运行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 晚上8:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Grasscutters/Grasscutter] [Feature Request] 其他游戏单机的实现 (Issue #1238)




  
您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物
  
把宝箱功能关了呢？能出现怪物吗？

**Comment by QianXiao12138** [comment]
> 可以出现怪物，我检查了一切可以检查的，完全相同的包放在我的电脑上就可以正常运行
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月13日(周一) 晚上8:13 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Grasscutters/Grasscutter] [Feature Request] 其他游戏单机的实现 (Issue #1238) 您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物 把宝箱功能关了呢？能出现怪物吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

但是云服务器上就是不行。。。我也是这样

**Comment by Jay12358** [comment]
貌似是服务器配置的问题，我2核2G跑lua的时候直接100%占用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 晚上8:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Grasscutters/Grasscutter] [Feature Request] 其他游戏单机的实现 (Issue #1238)




  
可以出现怪物，我检查了一切可以检查的，完全相同的包放在我的电脑上就可以正常运行
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年6月13日(周一) 晚上8:13 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Grasscutters/Grasscutter] [Feature Request] 其他游戏单机的实现 (Issue #1238) 您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物 把宝箱功能关了呢？能出现怪物吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
但是云服务器上就是不行。。。我也是这样

**Comment by lingzn12** [comment]
> 您好请问一下在服务器上运行jar包大世界内容对服务器的要求是怎样的呢，我用了Windows server2012和2016都无法正常运行大世界的内容，表现在当把config.json里面的对应项改成true的时候大世界直接不刷新任何怪物

您好我想问一下开启宝箱的具体参数是什么。

**Comment by Jay12358** [comment]
2核肯定不够了，4核应该可以，运存4g以上应该也够了，很贵的，不如尝试搞到公网ip.用自己的电脑作为服务端



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月13日(周一) 晚上9:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Grasscutters/Grasscutter] [Feature Request] 其他游戏单机的实现 (Issue #1238)




   
您好我想问一下开启宝箱的具体参数吗？
