### ISSUE TITLE
[Bug] can not enable database authentication

### ISSUE THREAD

**Issue by dzy32** [Melledy/Grasscutter#1241]
define database url variable is constant , when I enable database authentication, start the service and report an error
**Which branch did you use?**
start the server use java -jar grasscutter-1.1.2.jar
  Grasscutter version: 1.1.2 
  branch：[development]
  Git Hash: 992742d7469072630d0bdb25968e21dca379ef99

**Screenshots**
the log error 
`com.mongodb.MongoCommandException: Command failed with error 13 (Unauthorized): 'not authorized on grasscutter to execute command `

**Comment by zhaodice** [comment]
edit your config.json file, find follows:
```
"databaseInfo": {
    "server": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    },
    "game": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    }
  }
```
you must change it to:
```
"databaseInfo": {
    "server": {
      "connectionUri": "mongodb://username:password@localhost:27017",
      "collection": "grasscutter"
    },
    "game": {
      "connectionUri": "mongodb://username:password@localhost:27017",
      "collection": "grasscutter"
    }
  }
```
obviously, `username ` and `password` should be replaced with yours

**Comment by dzy32** [comment]
> 编辑您的 config.json 文件，找到以下内容：
> 
> ```
> "databaseInfo": {
>     "server": {
>       "connectionUri": "mongodb://localhost:27017",
>       "collection": "grasscutter"
>     },
>     "game": {
>       "connectionUri": "mongodb://localhost:27017",
>       "collection": "grasscutter"
>     }
>   }
> ```
> 
> 您必须将其更改为：
> 
> ```
> "databaseInfo": {
>     "server": {
>       "connectionUri": "mongodb://username:password@localhost:27017",
>       "collection": "grasscutter"
>     },
>     "game": {
>       "connectionUri": "mongodb://username:password@localhost:27017",
>       "collection": "grasscutter"
>     }
>   }
> ```
> 
> 显然，`username `应该`password`用你的替换

I have followed the configuration you said, the connection to the database is successful, but the execution of the operation reports an error, this is the screenshot
![image](https://user-images.githubusercontent.com/40918862/173183415-9f36954b-5ec8-4e7a-8175-a1a3a71ce358.png)
and my configure like this，now my server version is tag ：1.2.0 Git Hash：e5dd407a641a8f5d1e0ccf94f3d943e702bb7a4b
> ```
> "databaseInfo": {
>     "server": {
>       "connectionUri": "mongodb://username:password@localhost:27017/?authSource=grasscutter",
>       "collection": "grasscutter"
>     },
>     "game": {
>       "connectionUri": "mongodb://username:password@localhost:27017/?authSource=grasscutter",
>       "collection": "grasscutter"
>     }
>   }
> ```

**Comment by zhaodice** [comment]
you need give writing and reading permission to your mongodb user!

**Comment by dzy32** [comment]
> you need give writing and reading permission to your mongodb user!

thanks，I get it,.  The user role I use to connect to the database is useradmin  which has no  writing and reading permission. It should be wrong.
