### ISSUE TITLE
[Bug] 在七天神像无法交互的情况下（至少我的无法进行交互），该如何改变主角属性？在命令列表中的人物id里，我并没有发现有不同元素的主角，请问你们是怎么解决的？

### ISSUE THREAD

**Issue by lentarest** [Melledy/Grasscutter#1242]

**Comment by lentarest** [comment]
In the case that the Seven Heavenly Gods cannot interact (at least mine), how can I change the protagonist attributes? In the character id in the command list, I did not find the protagonist with different elements, how did you solve it?
（machine translation）

**Comment by kxmlqsql** [comment]
我是这样解决的，因为现在worldscripts并没有与dev合并，所以神像基本不可用，你需要在resource里自行更改

**Comment by Akka0** [comment]
七天神像交互在 #1055 已实现
