### ISSUE TITLE
卡池问题[Bug] 

### ISSUE THREAD

**Issue by jinghuashang** [Melledy/Grasscutter#1243]
我将服务器更新到了最新版本，但却没有2.7版本夜兰的池子，反而夜兰专武池子倒是有

**Comment by lingzn12** [comment]
请尝试编辑卡池，据我所知可以通过卡池文件进行调整。

**Comment by lingzn12** [comment]
尝试调整data目录下的Banners.json文件对卡池做出调整。

**Comment by jinghuashang** [comment]
> 尝试调整data目录下的Banners.json文件对卡池做出调整。

具体怎么改哦?

**Comment by jinghuashang** [comment]
> 尝试调整data目录下的Banners.json文件对卡池做出调整。

池子有了，但却是代码叫A081这个咋改哦

**Comment by zhaodice** [comment]
或者直接把data文件夹改个名，叫它重新生成

**Comment by lingzn12** [comment]
> > 尝试调整data目录下的Banners.json文件对卡池做出调整。
> 
> 具体怎么改哦?

https://wwb.lanzout.com/i3Yuw06ax1qh

**Comment by moondls** [comment]
data文件夹删掉，运行服务端会重新生成data文件夹，这个就是最新的。如果没有夜兰的池子，那就是服务端最新并没有添加这个，需要你自己添加
