### ISSUE TITLE
注册账号到选主角的界面，输入名字点“确定”时弹出“与服务器断开链接”

### ISSUE THREAD

**Issue by yutalex** [Melledy/Grasscutter#1249]
注册账号到选主角的界面，输入名字点“确定”时弹出“与服务器断开链接”
服务端的错误信息为： <ERROR:HandlerSetPlayerBornDataReq> No avatar data found! Please check your ExcelBinOutput folder.
重新下载并覆盖ExcelBinOutput也没用

**Comment by zhaodice** [comment]
检查config.json里resource文件夹的大小写

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
