### ISSUE TITLE
[Bug] 卡池问题

### ISSUE THREAD

**Issue by jinghuashang** [Melledy/Grasscutter#1252]
抽卡时显示内部服务器错误

**Comment by zhaodice** [comment]
因为你背包满了

**Comment by jinghuashang** [comment]
我背包并没有满啊

**Comment by zhaodice** [comment]
> 我背包并没有满啊

你要不检查一下，反正出现这个问题多半是因为没有容量了

**Comment by zhaodice** [comment]
或者换个新号看能不能抽，如果新号不能抽那就是100%的bug

**Comment by jinghuashang** [comment]
> 或者换个新号看能不能抽，如果新号不能抽那就是100%的bug
新号倒是能

**Comment by jinghuashang** [comment]
> > 我背包并没有满啊
> 
> 你要不检查一下，反正出现这个问题多半是因为没有容量了

还真的是背包满了
