### ISSUE TITLE
[Feature Request] 人物技能没有办法回血正常嘛，深渊刷怪刷一半就停止了，第九层则是无限刷怪

### ISSUE THREAD

**Issue by a1515155** [Melledy/Grasscutter#1255]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dianwangwin** [comment]
use another fork

**Comment by DA21S321D** [comment]
Maybe the lua scripts is unfinished,

**Comment by xiaohuailve** [comment]
> 使用另一个叉子

Is there a branch path

**Comment by xiaohuailve** [comment]
> use another fork

Is there a branch path

**Comment by dianwangwin** [comment]
> > use another fork
> 
> Is there a branch path

akka0's bigworld fork

**Comment by KiminaNatsuki** [comment]
Duplicated issues.
