### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by SentientIrisu** [Melledy/Grasscutter#1276]
I'm not asking for much I just wanna be able to spawn NPC's (Kokomi, Dvalin etc)

**Comment by gawgua** [comment]
Dvalin is NPC now, I guess

**Comment by totallynotnochi** [comment]
malding severely from this ngl

**Comment by KiminaNatsuki** [comment]
no

**Comment by KingRainbow44** [comment]
kimi herself has spoken
