### ISSUE TITLE
[Bug] /crash/dataUpload 无法链接

### ISSUE THREAD

**Issue by Misakami** [Melledy/Grasscutter#1288]
版本号
Grasscutter version: 1.2.0-e5dd407a

账号注册并登录成功以后，下载更新出错。代理软件使用fiddler。已信任证书。
![image](https://user-images.githubusercontent.com/22981008/174235559-a7f68bb0-a919-4d92-8e3c-c2827b63fcdd.png)
![image](https://user-images.githubusercontent.com/22981008/174235598-44865c92-5c29-4bfc-8540-ebfbff5d7583.png)

**Comment by Misakami** [comment]
尝试加入discord来获取帮助，但是貌似并不能给国内手机号发送短信验证

**Comment by zhaodice** [comment]
fiddler我搭好了也这样，时好时坏，原因未知，最后我直接上VPN稳定解决了

**Comment by KiminaNatsuki** [comment]
This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
