### ISSUE TITLE
哥哥（空）什么时候才能点命座啊QAQ

### ISSUE THREAD

**Issue by Jelen0126** [Melledy/Grasscutter#1297]

**Comment by zhaodice** [comment]
也许要等鸡吃完了米，狗舔完了面，火烧断了锁

——才有可能（？

**Comment by KiminaNatsuki** [comment]
我怎麼記得好像可以點？？

**Comment by zhaodice** [comment]
> 我怎麼記得好像可以點？？

是可以，但部分命座还没效果

**Comment by Jelen0126** [comment]
？






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月17日(星期五) 晚上9:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter] 哥哥（空）什么时候才能点命座啊QAQ (Issue #1297)






也许要等鸡吃完了米，狗舔完了面，火烧断了锁

——才有可能（？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by Jelen0126** [comment]
emmm点不了诶QAQ




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Grasscutters/Grasscutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 晚上9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Grasscutters/Grasscutter] 哥哥（空）什么时候才能点命座啊QAQ (Issue #1297)





  
我怎麼記得好像可以點？？
  
是可以，但部分命座还没效果

**Comment by zhaodice** [comment]
那就只能等大佬实现了这个，大家都是无偿pr的，没必要催~别急

**Comment by KiminaNatsuki** [comment]
> 那就只能等大佬实现了这个，大家都是无偿pr的，没必要催~别急
