### ISSUE TITLE
Can I merge the "dev-world-scripts" branch into the "development" branch?

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1299]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KiminaNatsuki** [comment]
no
dev world is too unstable too be merged

**Comment by Birdulon** [comment]
In the meantime check out this fork https://github.com/Akka0/Grasscutter/tree/2.7-world-script
