### ISSUE TITLE
Attempting to run GC on Linux doesn't work

### ISSUE THREAD

**Issue by KingRainbow44** [Melledy/Grasscutter#13]
This is because GC is hardcoded to use the file separator `\` (how it is on Windows).
UNIX-based operating systems use `/` as the file seperator.
Example: `File folder = new File(Grasscutter.getConfig().RESOURCE_FOLDER + "BinOutput\\Avatar\\");`

**Comment by MlgmXyysd** [comment]
just change hardcoded `\` to `File.separator`
