### ISSUE TITLE
最新开发版可以开启2.7版本世界宝箱了吗

### ISSUE THREAD

**Issue by lingzn12** [Melledy/Grasscutter#1305]
如能请告诉我方法，感激不尽。

**Comment by dianwangwin** [comment]
手动开启大世界

**Comment by lingzn12** [comment]
> 手动开启大世界

具体步骤？是改配置文件吗大佬。

**Comment by Aemeath5** [comment]
配置文件里面搜索
enableScriptInBigWorld    把false改成
true

**Comment by lingzn12** [comment]
> 配置文件里面搜索 enableScriptInBigWorld 把false改成 true
好的谢谢我去尝试一下

**Comment by lingzn12** [comment]
> 配置文件里面搜索 enableScriptInBigWorld 把false改成 true

十分感谢宝箱已能刷新
