### ISSUE TITLE
希望添加剧情和任务系统，目前没有任务，也没有怪，只有史莱姆[Feature Request] 

### ISSUE THREAD

**Issue by changjiuxiong** [Melledy/Grasscutter#1315]
希望添加剧情和任务系统，目前没有任务，也没有怪，只有史莱姆

**Comment by zhaodice** [comment]
我觉得吧这个还没完善

**Comment by zhaodice** [comment]
怪是有的，你可以去某些地方，享受一人单挑一群的感觉

**Comment by zhaodice** [comment]
![image](https://user-images.githubusercontent.com/63996691/174466975-0a2fd3e4-ae78-4842-bd31-2c070bd46b5f.png)
你可以去这个地方看看，到时候别哭着来喊妈妈就好 ^_^

**Comment by liyutg** [comment]
为啥我还能抓晶蝶打史莱姆

**Comment by dianwangwin** [comment]
> 希望添加剧情和任务系统，目前没有任务，也没有怪，只有史莱姆

希望你可以提交一个pr

**Comment by dongriiiii** [comment]
你活在上世纪？

**Comment by a1515155** [comment]
添加任务这难度我觉得有点高，倒是用代码刷出来过任务，有的能做，有的不能做甚至无法用代码结束。

**Comment by lunaticwhat** [comment]
yes those feature will/might be added in the feature !
