### ISSUE TITLE
[Bug] The last chest could not be opened, making it impossible to complete the game

### ISSUE THREAD

**Issue by liyutg** [Melledy/Grasscutter#1317]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

最后一个宝箱无法打开，造成没法通关

**Which branch did you use?**

**Screenshots**

![image](https://user-images.githubusercontent.com/23010064/174471606-d8e3ccac-0a87-487d-994e-81f49df36282.png)
![image](https://user-images.githubusercontent.com/23010064/174471613-4f713513-f0ef-45c8-aefb-7cda643b3c9c.png)

**Additional context**

**Comment by wl23333** [comment]
宝箱打不开是因为ChestReward.json没用配置宝箱掉落信息。
副本不能通关是因为脚本问题。
不是因为宝箱打不开才不能过关

脚本得等大佬们慢慢修复了

**Comment by Roly-lol** [comment]
I have fixed it in my fork

**Comment by liyutg** [comment]
old Fe ！six six six ！

**Comment by liyutg** [comment]
https://github.com/Grasscutters/Grasscutter/pull/1350

**Comment by Roly-lol** [comment]
https://github.com/Akka0/Grasscutter/compare/2.7-world-script...xiao-Roly:2.7-world-script

**Comment by Akka0** [comment]
这个无法通关不是宝箱的问题

官服中你可以不开最后的宝箱直接离开秘境

**Comment by KingRainbow44** [comment]
Due to this issue being inactive, I will be closing it. Feel free to make a new issue.
