### ISSUE TITLE
Help-seeking role cannot attack.

### ISSUE THREAD

**Issue by LuoTianTime** [Melledy/Grasscutter#132]
I got the character, but the character can't hold a weapon and can't release the skill normally. After releasing the skill, the character will get stuck and can't move. Is there any solution?

**Comment by damywise** [comment]
Can you send a video?
(I won't help btw, just want to see some context)

**Comment by KingRainbow44** [comment]
this is an issue with the character you're using and the decompiled binaries you've provided.
see the wiki's [installation section](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server) for more information.

**Comment by liaoyijing** [comment]
Please check if there is the corresponding JSON file mapping to your char in `\resources\BinOutput\Avatar`. I met the same question, and I find out that seems like these JSON descriptions should include all the characters and will have 121 of them. Check the release file and recopy the entire folder.
