### ISSUE TITLE
[Bug] pull之后（22年6月20日）圣遗物匣、助力礼包无法正常开启

### ISSUE THREAD

**Issue by Moss-Tony** [Melledy/Grasscutter#1320]
暂时未发现有其它issues提交相同问题

6月20日Git pull 后，无法开启圣遗物匣和助力礼包。在此之前是正常的。

Grasscutter version: 1.2.1-dev

开启圣遗物匣提示“服务器内部错误”
开启助力礼包，相应物品没有被入库

**Comment by Moss-Tony** [comment]
有人反馈最早在6月18日git pull后，就无法正常开启助力礼包了

**Comment by mIwaYuhang** [comment]
不理解你的意思，是商品中的礼包吗？是的话请在data目录中替换ShopChest.json
[ShopChest.zip](https://github.com/Grasscutters/Grasscutter/files/8937041/ShopChest.zip)

**Comment by lingzn12** [comment]
> 有人反馈最早在6月18日git pull后，就无法正常开启助力礼包了

我也遇到过同样的问题，我怀疑圣遗物匣是在修复合成台时出的问题。助力礼包暂时不清楚。

**Comment by Moss-Tony** [comment]
> 不理解你的意思，是商品中的礼包吗？是的话请在data目录中替换ShopChest.json [ShopChest.zip](https://github.com/Grasscutters/Grasscutter/files/8937041/ShopChest.zip)

我是直接Git pull的，理论上来讲应该与库中的json相同，它也的确是一样的

**Comment by mIwaYuhang** [comment]
> > 不理解你的意思，是商品中的礼包吗？是的话请在data目录中替换ShopChest.json [ShopChest.zip](https://github.com/Grasscutters/Grasscutter/files/8937041/ShopChest.zip)
> 
> 我是直接Git pull的，理论上来讲应该与库中的json相同，它也的确是一样的

仅此而已的话，请替换上面我为你发送的文件解压包，替换data中的对应文件即可解决问题
