### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by 501657109** [Melledy/Grasscutter#1323]
**The Roles Panel properties do not match the actual properties**

**For example, the actual damage of a normal attack is 50% different from the damage of the panel**

** Grasscutter version: 1.2.0**

**Hope there is a big guy who can tell the solution thank you**

**Comment by dianwangwin** [comment]
> **The Roles Panel properties do not match the actual properties**
> 
> **For example, the actual damage of a normal attack is 50% different from the damage of the panel**
> 
> ** Grasscutter version: 1.2.0**
> 
> **Hope there is a big guy who can tell the solution thank you**

考虑怪的防御。。。

**Comment by 501657109** [comment]
防御我算进去了，如果但看钟离的话21级的钟离面板516的伤害，实际伤害除去暴击加成和普通攻击第一段倍率的话计算下来只有302的数值

**Comment by 501657109** [comment]
> 防御我算进去了，如果但看钟离的话21级的钟离面板516的伤害，实际伤害除去暴击加成和普通攻击第一段倍率的话计算下来只有302的数值

**Comment by KingRainbow44** [comment]
please use the proper issue format.
