### ISSUE TITLE
[Bug] Blessing system damaged

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1326]
The currency required for the lottery becomes Mora, the button interface cannot be clicked, and the suspended animation is stuck.![IMG_20220620_155723.jpg](https://user-images.githubusercontent.com/69531154/174553169-8cdcb79e-dbc7-4395-ae93-96247893ee27.jpg)

1.2.1-dev-24bf5af

**Comment by KiminaNatsuki** [comment]
(Perhaps you should just use chinese instead of the machine translation next time.)

**Comment by dianwangwin** [comment]
> The currency required for the lottery becomes Mora, the button interface cannot be clicked, and the suspended animation is stuck.![IMG_20220620_155723.jpg](https://user-images.githubusercontent.com/69531154/174553169-8cdcb79e-dbc7-4395-ae93-96247893ee27.jpg)
> 
> 1.2.1-dev-24bf5af

check for resource

**Comment by KiminaNatsuki** [comment]
Nah, it's a duplicate of #1325
