### ISSUE TITLE
[Bug] Elemental resonance failed to work unless I re-setup current team

### ISSUE THREAD

**Issue by WhisperWithDelight** [Melledy/Grasscutter#1327]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

When I log in the game, all elemental resonance fail to work. But if i change a current team member or deploy another team, it will work again.

**Which branch did you use?**

**Screenshots**

(There are 3 hydro in the team, but no incoming healing bonus)
![image](https://user-images.githubusercontent.com/106378104/174556531-841d186d-fa79-4266-8994-cc7f61e02eab.png)

**Additional context**

**Comment by AZthemute** [comment]
To recreatre, I had to enable a different resonance first. But this is happening on the newest dev build.

**Comment by lunaticwhat** [comment]
try create another account. lastest dev-build should caused some issue on old account that created since last stable build

**Comment by millet6** [comment]
> 

最新的开发版 从哪里下载

**Comment by KingRainbow44** [comment]
Due to this issue being inactive, I will be closing it. Feel free to make a new issue.

**Comment by Birdulon** [comment]
Fixed by `e8cbb89`
