### ISSUE TITLE
[Bug] The quantity attribute of the give command is invalid

### ISSUE THREAD

**Issue by ZXAS007** [Melledy/Grasscutter#1328]
When using the give command to give Mora or Rough Stone (probably all items) only 1 regardless of the quantity set

**Comment by KiminaNatsuki** [comment]
Can people actually follow the format?

**Comment by suntech-group** [comment]
me 2

**Comment by ZXAS007** [comment]
Measured in version 1.2.2-dev-81079ce and not fixed

**Comment by Birdulon** [comment]
81079ce is on some branch of @Akka0's fork I think? Anyway the problem #1333 addressed doesn't seem to be present in there so I'm assuming this is to do with the removal of positional quantity argument from give command. Quantity can now only be set using `[x<quantity>]` (previously this was an optional way of setting it).
