### ISSUE TITLE
.jar file not communicating with MongoDB server

### ISSUE THREAD

**Issue by wizmeister777** [Melledy/Grasscutter#133]
Steps taken during startup process:
MongoDB service started from cmd
MongoDBCompass opened to verify server status, successfully connected to localhost:27017 (picture attached to verify connection)
Attempted to run grasscutter.jar (pre-packaged version), received error message below

Persists after disabling windows firewall, allowing MongoDB to connect to all local ports, and running the cmd as admin; Windows 11 OS with MongoDB 5.0.7 and JDK 8.0

![image](https://user-images.githubusercontent.com/31963844/164845035-50e1291c-e128-4e1f-8d11-4567a215c2d2.png)
![image](https://user-images.githubusercontent.com/31963844/164845056-45eaee9c-9cf1-435f-bd19-06c606b5f198.png)

**Comment by omg-xtao** [comment]
Are you sure you're using JDK-8u202 ?
```
java -version
java version "1.8.0_202"
```

**Comment by wizmeister777** [comment]
I'm on base Java 8:

java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

Should I upgrade?

**Comment by wizmeister777** [comment]
> Are you sure you're using JDK-8u202 ?
> 
> ```
> java -version
> java version "1.8.0_202"
> ```

I'm on base Java 8:

java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

Should I upgrade?

**Comment by omg-xtao** [comment]
> > Are you sure you're using JDK-8u202 ?
> > ```
> > java -version
> > java version "1.8.0_202"
> > ```
> 
> I'm on base Java 8:
> 
> java -version java version "1.8.0" Java(TM) SE Runtime Environment (build 1.8.0-b132) Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
> 
> Should I upgrade?

Yes.

**Comment by Koko-boya** [comment]
> > > Are you sure you're using JDK-8u202 ?
> > > ```
> > > java -version
> > > java version "1.8.0_202"
> > > ```
> > 
> > 
> > I'm on base Java 8:
> > java -version java version "1.8.0" Java(TM) SE Runtime Environment (build 1.8.0-b132) Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)
> > Should I upgrade?
> 
> Yes.

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

Java 8 Version 202 is Needed to run grasscutter 
Download Link: https://mirrors.huaweicloud.com/java/jdk/8u202-b08/
