### ISSUE TITLE
[Bug] 大世界功能报错

### ISSUE THREAD

**Issue by lingzn12** [Melledy/Grasscutter#1336]
<img width="1104" alt="捕获" src="https://user-images.githubusercontent.com/61488096/174799925-37134d5a-3543-4a58-9db0-490401c98f9f.PNG">
在我靠近爆炎树时会出现这个报错，但当我上线位置就在爆炎树旁边时却能够加载。其他的地方不清楚。

**Comment by suntech-group** [comment]
me too.

**Comment by Akka0** [comment]
试试 #1355 还会存在问题吗

**Comment by lingzn12** [comment]
> 我也是。

来吧我的朋友，试试解决办法。

**Comment by lingzn12** [comment]
> 试试 #1355 还会存在问题吗

好的，大佬

**Comment by lingzn12** [comment]
> 试试 #1355 还会存在问题吗

我现在并没有遇到相关错误，感谢大佬的更新。
