### ISSUE TITLE
[Bug] 2 bugs.

### ISSUE THREAD

**Issue by suntech-group** [Melledy/Grasscutter#1363]
1. The dragon keeps reappearing in the ruins. 
2. Unable to climb the dragon's neck.
![image](https://user-images.githubusercontent.com/61503516/175506722-6bfed4e9-d6c2-400d-a764-d4cc8ebc79c2.png)
fix it PLS.🙏🏻

**Comment by GanyusLeftHorn** [comment]
Please follow the issue template and use a descriptive title.
