### ISSUE TITLE
[Bug] The big world function cannot destroy the wooden box

### ISSUE THREAD

**Issue by lingzn12** [Melledy/Grasscutter#1364]
大世界功能无法破坏障碍物，可有修复办法？

**Comment by KiminaNatsuki** [comment]
Known problem already, you may wait for some other person to fix it.
~~(also we prefer our issue tracker to be english only so)~~

**Comment by lingzn12** [comment]
> 已知问题已经，您可以等待其他人来解决它。 ~（我们也希望我们的问题跟踪器只有英语）所以）~

good.
