### ISSUE TITLE
[Feature Request] 希望能添加神樱树功能awa

### ISSUE THREAD

**Issue by Jelen0126** [Melledy/Grasscutter#1372]

**Comment by KiminaNatsuki** [comment]
(Translation: Hope there's Sacred Sakura tree function that you can upgrade)

**Comment by Arikatsu** [comment]
kimi help

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
