### ISSUE TITLE
Can you customize the default permissions for players to enter the server?

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1383]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Roly-lol** [comment]
![RT( MH_1D`P~D0{7I7__TNE](https://user-images.githubusercontent.com/90933865/175816057-228457eb-ae92-4330-be1c-393861597d1d.png)

**Comment by Roly-lol** [comment]
class里的默认权限优先级高于config.json
![QQ截图20220626212130](https://user-images.githubusercontent.com/90933865/175816165-4fb2ea1d-775c-434b-a59c-6d2e6703981f.png)

**Comment by ERthereal** [comment]
> class里的默认权限优先级高于config.json ![QQ截图20220626212130](https://user-images.githubusercontent.com/90933865/175816165-4fb2ea1d-775c-434b-a59c-6d2e6703981f.png)

如果不设置config.json更改account.addPermission("*")这段可以吗？
感谢您的回复

**Comment by Roly-lol** [comment]
> > class里的默认权限优先级高于config.json![QQ截图20220626212130](https://user-images.githubusercontent.com/90933865/175816165-4fb2ea1d-775c-434b-a59c-6d2e6703981f.png)
> 
> 如果不设置config.json更改account.addPermission（“*”）这段可以吗？ 感谢您的回复

如果你需要新玩家自动注册的话，只需要设置config.json的权限就可以了。account.addPermission（“*”）这段是在控制台使用account命令注册时添加的权限

**Comment by 1234567890qwertyuiop914** [comment]
> 

我懂了，如果只需要setworldlevel和heal权限
写入config.json是不是像这样
![image](https://user-images.githubusercontent.com/58130955/175816754-946f8d8e-eef3-40ba-b7b7-a5eb3d1d39c8.png)
那么account.addPermission（“*”）默认2个权限又是怎么改呢？

**Comment by ERthereal** [comment]
> > > class里的默认权限优先级高于config.json![QQ截图20220626212130](https://user-images.githubusercontent.com/90933865/175816165-4fb2ea1d-775c-434b-a59c-6d2e6703981f.png)
> > 
> > 
> > 如果不设置config.json更改account.addPermission（“*”）这段可以吗？ 感谢您的回复
> 
> 如果你需要新玩家自动注册的话，只需要设置config.json的权限就可以了。account.addPermission（“*”）这段是在控制台使用account命令注册时添加的权限

改config.json是不是这样
![image](https://user-images.githubusercontent.com/58130955/175817074-137318b6-a4cc-42fd-a77b-9302333417ad.png)
那么account.addPermission（“*”）默认2个权限又是怎么改呢？

**Comment by Roly-lol** [comment]
![QQ截图20220626214326](https://user-images.githubusercontent.com/90933865/175817142-9e60f770-e5f5-4f56-92ba-992abc031d52.png)
改config如图所示，class里的account.addPermission（“*”）这一行可以直接删掉

**Comment by Roly-lol** [comment]
https://github.com/Grasscutters/Grasscutter/pull/1359    设置世界等级建议参考这个

**Comment by ERthereal** [comment]
> #1359 设置世界等级建议参考这个

十分感谢您的回复和解答！

**Comment by KiminaNatsuki** [comment]
> > #1359 设置世界等级建议参考这个
> 
> 十分感谢您的回复和解答！

Since the Issue is already answered, I will be closing this down.
