### ISSUE TITLE
How to modify the upper limit of monsters generated by players

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1387]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Roly-lol** [comment]
Just modify sceneEntityLimit
\Grasscutter\config.json
![QQ截图20220627145001](https://user-images.githubusercontent.com/90933865/175877133-12909228-6d0e-477b-953f-686c9bc6fb7d.png)
