### ISSUE TITLE
[Bug] 无限刷怪导致卡顿

### ISSUE THREAD

**Issue by basaka2022** [Melledy/Grasscutter#1388]
![2JHH(Y@%R85_E2_7}}_XDJ](https://user-images.githubusercontent.com/105022556/175832908-e048d54e-7c57-48e0-a399-cfee60b62a7f.png)
很 不少地方都会出现这种情况
世界数据中的箱子等物品不能被破坏，感觉也是无限刷新

**Comment by 2y8e9h22** [comment]
你得说清楚呀，你用的什么版本。
什么是无限刷怪？。。
没看懂

**Comment by basaka2022** [comment]
就是怪越来越多，最后满屏都是，还继续不停出来新的怪

**Comment by basaka2022** [comment]
版本是1.2.2-dev 最新的

**Comment by basaka2022** [comment]
![%54F3@$~452HNGR@Q)IEAZF](https://user-images.githubusercontent.com/105022556/175833658-4c67f8a2-9fa4-4e9a-aa0a-0094fa7b62e9.png)

**Comment by shelby-xyz** [comment]
要么跑脱离战斗，要么用Q一次性解决干净就没有了

**Comment by Akka0** [comment]
Closed due to #1429 merged
