### ISSUE TITLE
Your project becomes a tool for others to make money.

### ISSUE THREAD

**Issue by Roly-lol** [Melledy/Grasscutter#1390]
As the picture shows, they built a grasscutter for charging, and credited themselves for various updates, shameless.

![宣传图片](https://user-images.githubusercontent.com/90933865/175901906-7f86de78-19db-4b5e-8b52-1a6e8d0eac47.JPG)
![赞助变强套餐](https://user-images.githubusercontent.com/90933865/175901910-d4b4bc81-124d-440f-b671-3aac06e238cd.png)
![Screenshot_20220627_164820](https://user-images.githubusercontent.com/90933865/175901919-2f32564a-8334-47eb-9f50-f72b2dde0fc2.jpg)
![Screenshot_20220627_164836](https://user-images.githubusercontent.com/90933865/175901923-4c6e82c9-1598-4271-903e-52bf45210280.jpg)
![Screenshot_20220627_164842](https://user-images.githubusercontent.com/90933865/175901936-d212fb9f-c127-454f-b0c9-d14318d9f749.jpg)
![Screenshot_20220627_164849](https://user-images.githubusercontent.com/90933865/175901939-ba4b3170-4451-409a-9c1e-02829e96b2eb.jpg)
![Screenshot_20220627_164933](https://user-images.githubusercontent.com/90933865/175901944-85b142f7-2dc9-4872-bdc2-2145f594c6b5.jpg)
![Screenshot_20220627_164939](https://user-images.githubusercontent.com/90933865/175901948-8867b382-d216-4713-a1ca-a63f0fbb228f.jpg)
![拉人逆天法](https://user-images.githubusercontent.com/90933865/175901952-d37c3076-d16b-4617-8e99-72ed7b1e3d6a.png)
![Screenshot_2022_0627_164908](https://user-images.githubusercontent.com/90933865/175901971-1804eb56-7be2-4736-ab86-2a2414d531a1.jpg)
![Screenshot_2022_0627_164922](https://user-images.githubusercontent.com/90933865/175901975-90983722-59db-47d1-be23-2ce5c848f825.jpg)
![Screenshot_20220627_164616](https://user-images.githubusercontent.com/90933865/175901978-62b1b4f9-c635-4441-9aaf-54f50473bd6c.jpg)
![Screenshot_20220627_164656](https://user-images.githubusercontent.com/90933865/175901985-b3c51b34-20e5-4acc-a945-8feff11fa7e9.jpg)

**Comment by ttxs25830** [comment]
I'm sorry? It's a bug? Maybe the "bug" lable is for people to report when the program does not work as it expected instead of for you to report what bad things done by this project?

**Comment by zhaodice** [comment]
this issue should be closed
1.它不是bug
2.他们只是利用信息差赚钱而已
3.他们的行为与我们无关
