### ISSUE TITLE
[Feature Request] Add a function to delete specified items.

### ISSUE THREAD

**Issue by Asayu233** [Melledy/Grasscutter#1392]
## 关于删除指定的某些物品的功能

sorry, my english sucks...

### 如果这个功能已经存在但我不知道，请告诉我！如果没有，请继续阅读。
**If there is already a function that can delete specified items, please let me know! If not, read on.**

---------------------------------------------------------------
之前的 give 命令在给予负数的物品时会使其数量超上限(42亿)而从零开始重新计算，通过这种方式可以较为方便的**删除某种物品**。但现在，新的 give 命令不再支持这些，物品给予的上限被设定为9999，超过上限也不再会归零，所以删除某种物品变得很麻烦。
我的建议是，**添加一个新命令**( _例如 /delete \<物品ID> [数量]_ )用来删除某种物品，或者给 give 命令**反向给予物品**的功能。

The previous give command to give negative items will make it zero after it exceeds the upper limit, **some items can be deleted** through this. But now the new give command fixes these, the number of items that can be given is limited to 9999, and it will not return to zero if it exceeds the upper limit, so deleting some items can become troublesome.
My suggestion would be to **add a new command** ( _e.g. /delete \<itemID> [amount]_ ) to delete some items, or **add a feature to the give command**: giving negative items to delete them.

before ( ver.22/06/25 )
![1](https://user-images.githubusercontent.com/76391894/175900366-ce17a96f-6330-4176-9dc8-3637fdd24341.png)

---------------------------------------------------------------
-The "destroy" button on the bottom left?
-It can't destroy every thing.
-The clear command?
-It will destroy everything.

thanks!!

**Comment by 2y8e9h22** [comment]
你在搞笑？

**Comment by KiminaNatsuki** [comment]
![image](https://user-images.githubusercontent.com/34180607/176060880-c1208fa0-77ae-47ca-8402-6c817195378b.png)

**Comment by lingzn12** [comment]
> ![image](https://user-images.githubusercontent.com/34180607/176060880-c1208fa0-77ae-47ca-8402-6c817195378b.png)

來自Kimi的的疑問。我認為這個指令可有可無，私人服務器並不是長久之計，若衹是增加大佬們的負擔，這就閑的很沒必要了。

**Comment by KiminaNatsuki** [comment]
> > ![image](https://user-images.githubusercontent.com/34180607/176060880-c1208fa0-77ae-47ca-8402-6c817195378b.png)
> 
> 
> 
> 來自Kimi的的疑問。

一定有疑問的...

**Comment by Liujunhua007** [comment]
直接下载一个navicat登录mogodb，去里面删不就好了？

**Comment by lunaticwhat** [comment]
just edit directly in the database ( using mongoDB compass) it is the best way to temporaty resolve this issue

**Comment by KiminaNatsuki** [comment]
> just edit directly in the database ( using mongoDB compass) it is the best way to temporaty resolve this issue
