### ISSUE TITLE
[Bug] Java Fill up the CPU for no reason

### ISSUE THREAD

**Issue by Aemeath5** [Melledy/Grasscutter#1397]
Java,Fill up the CUP for no reason，After rebooting, it works fine, but after a while, this problem will occur again，May I ask what causes this problem and how to solve it。
![Screenshot_2022-06-28-12-22-19-381_com microsoft rdc android beta](https://user-images.githubusercontent.com/84051485/176093605-fb9ec2c0-3d0b-4dea-95d3-262547030e30.jpg)

**Comment by akbaryahya** [comment]
This may be because the lua script problem in the latest version is too much trouble, I also had this problem, I'm currently testing with https://github.com/Grasscutters/Grasscutter/pull/1340 it's much better now but it's too early to say that so please try for a few days

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
(Notices: you can disable your lua scripts in order to not java kill your pc instantly)
