### ISSUE TITLE
[Bug]Enter the Dungeon (Abyss)

### ISSUE THREAD

**Issue by simple-shadow** [Melledy/Grasscutter#1399]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

when i trying to enter the Enter the Dungeon (Abyss)，there are some bugs ,anybody know why?
here is the bug report:
https://pastebin.com/g8ZAQLTY
**Which branch did you use?**

  Grasscutter version: 1.2.2-dev-df85e0ac
  Git Hash: df85e0ac

**Screenshots**

**Additional context**

thanks
my os : archlinux for arm64
java version:openjdk 17.0.3

**Comment by lunaticwhat** [comment]
it's already a known issue with abyss/domains/dungeons.
