### ISSUE TITLE
[Bug] 请教大佬们如何正确的书写星辉兑换的配置

### ISSUE THREAD

**Issue by AUndead** [Melledy/Grasscutter#1400]
在写入商城配置的时候发现不能正确的像往常NPC商店一样添加商品,请求大佬们给我个正确的星辉书写配置方法
如何添加一个商品的卡槽。。。
Google Translate:
`When writing the mall configuration, I found that I could not correctly add products as usual in NPC stores. I asked the bosses to give me a correct configuration method of Xinghui
How to add a product card slot...`

  Grasscutter version: 1.2.2-dev
  Git Hash: 1d388b0

**原配置**
**Original profile in shop.json**
```
[
  {
	"shopId": 1001,
    "items": [
      {
        "goodsId": 5066630,
        "goodsItem": {
          "id": 10000026,
          "count": 1
        },
        "hcoin": 10003,
		"mcoin": 1042,
        "buyLimit": 0,
        "beginTime": 1575129600,
        "endTime": 2051193600,
        "minLevel": 4,
        "maxLevel": 99,
        "costItemList": [
          {
            "id": 221,
            "count": 300
          }
        ]
      }
	]
  }
]
```
**原配置**
**Original profile in shop.json**
![#01](https://user-images.githubusercontent.com/68094548/176346142-8161e2be-5345-4b27-b6ba-a407f1069a04.png)

![#1](https://user-images.githubusercontent.com/68094548/176346018-6cb914a7-d01a-43ac-9f61-5ae0bba5b547.png)

**Comment by HangbinYang** [comment]
我也有相同疑问，现在发现是复制一个已存在的商品，改goodsid不行，但对一个已存在的商品调整goodsitem或者价格之类的是可以的，我怀疑客户端写死了那些goodsid...

**Comment by AUndead** [comment]
> 我也有同样的疑问，现在发现是复制一个已经存在的商品，改好的商品不能写死价格，但对一个已经存在的商品调整好的网站或者之类的商品可以的，我怀疑客户端有那些商品...

为什么我尝试复制一个已经存在的商品也改不了它的价格...

**Comment by HangbinYang** [comment]
> > 我也有同样的疑问，现在发现是复制一个已经存在的商品，改好的商品不能写死价格，但对一个已经存在的商品调整好的网站或者之类的商品可以的，我怀疑客户端有那些商品...
> 
> 为什么我尝试复制一个已经存在的商品也改不了它的价格...
我并不是复制一个新的数据来修改价格，而是在原来已有的某个物品数据上修改价格，新增是不起作用的，不知道为啥

**Comment by AUndead** [comment]
> > > 我也有同样的疑问，现在发现是复制一个已经存在的商品，改好的商品不能写死价格，但对一个已经存在的商品调整好的网站或者之类的商品可以的，我怀疑客户端有那些商品...
> > 
> > 
> > 为什么我尝试复制一个已经存在的商品也改不了它的价格...
> > 我并不是复制一个新的数据来修改价格，而是在原来已有的某个物品数据上修改价格，新增是不起作用的，不知道为啥

原来已有的物品数据在哪改,能指个路么,我想去试试！

**Comment by HangbinYang** [comment]
> > > > 我也有同样的疑问，现在发现是复制一个已经存在的商品，改好的商品不能写死价格，但对一个已经存在的商品调整好的网站或者之类的商品可以的，我怀疑客户端有那些商品...
> > > 
> > > 
> > > 为什么我尝试复制一个已经存在的商品也改不了它的价格...
> > > 我并不是复制一个新的数据来修改价格，而是在原来已有的某个物品数据上修改价格，新增是不起作用的，不知道为啥
> 
> 原来已有的物品数据在哪改,能指个路么,我想去试试！

resources/ExcelBinOutput/ShopGoodsExcelConfigData.json里面，找shopType为1001的数据，目前我尝试下来，只有将原本已存在的商品替换成其他商品（不能修改goodsId），我怀疑客户端是写死了，如果你尝试出来有新的办法，记得告诉我一下

**Comment by AUndead** [comment]
> > > > > 我也有同样的疑问，现在发现是复制一个已经存在的商品，改好的商品不能写死价格，但对一个已经存在的商品调整好的网站或者之类的商品可以的，我怀疑客户端有那些商品...
> > > > 
> > > > 
> > > > 为什么我尝试复制一个已经存在的商品也改不了它的价格...
> > > > 我并不是复制一个新的数据来修改价格，而是在原来已有的某个物品数据上修改价格，新增是不起作用的，不知道为啥
> > 
> > 
> > 原来已有的物品数据在哪改,能指个路么,我想去试试！
> 
> resources/ExcelBinOutput/ShopGoodsExcelConfigData.json里面，找shopType为1001的数据，目前我尝试下来，只有将原本已存在的商品替换成其他商品（不能修改goodsId），我怀疑客户端是写死了，如果你尝试出来有新的办法，记得告诉我一下

花费数小时的琢磨,我终于弄出来了,但是还是不能添加商品(其实也是没有去试),只是能替换没有使用的卡槽
![#1](https://user-images.githubusercontent.com/68094548/176619817-c64201f8-b071-4c12-bb0c-69a42f6a56e5.png)

**Comment by AUndead** [comment]
> 

解决办法是
resources/ExcelBinOutput/ShopGoodsExcelConfigData.json里面原配置是这样的
`
   {
        "goodsId": 102005,
        "subTagNameTextMapHash": 760875338,
        "subTabId": 2,
        "shopType": 1001,
        "rotateId": 10201,
        "itemCount": 1,
        "costItems": [
            {
                "id": 221,
                "count": 34
            },
            {},
            {},
            {}
        ],
        "buyLimit": 1,
        "refreshType": "SHOP_REFRESH_MONTHLY",
        "refreshParam": 1,
        "beginTime": "2020-10-01 04:00:01",
        "endTime": "2035-01-01 00:00:00",
        "preconditionParamList": [
            "",
            ""
        ],
        "minShowLevel": 1,
        "minPlayerLevel": 4,
        "maxPlayerLevel": 99,
        "sortLevel": 9,
        "platformTypeList": []
    },`
在花费数小时的测试中,我发现有一个id很奇怪，而且物品ID没有搜索到,并且物品id的单词是"rotateId": 10201,这样的样式，只要把它这样修改:
`        "itemId": 1027,`
然后重启割草机就完美解决卡槽孔缺的问题

**Comment by HangbinYang** [comment]
> 
确实是可以解决卡槽空缺的问题，但并不能新增其他你想要的东西，比如把一把五星武器新增进去，只能去修改已有卡槽的itemid，不知道为什么不能新增

**Comment by AUndead** [comment]
> > 
> 
> 确实是可以解决卡槽空缺的问题，但并不能新增其他你想要的东西，比如把一把五星武器新增进去，只能去修改已有卡槽的itemid，不知道为什么不能新增

确实,我发现每一个特定的物品ID都有它专属的subTagNameTextMapHash,这个我自定义了发现也完全没有效果,也不知道怎么算出来这个ID的

**Comment by AUndead** [comment]
> > 
> 
> 确实是可以解决卡槽空缺的问题，但并不能新增其他你想要的东西，比如把一把五星武器新增进去，只能去修改已有卡槽的itemid，不知道为什么不能新增

确实,无法现每一个特定的物品ID都有它专属的subTagNameTextMapHash,这个我自定义了发现也完全没有效果,也不知道怎么算出来这个ID的

**Comment by HangbinYang** [comment]
> 
修改subTagNameTextMapHash没有任何作用，但是如果修改的goodsId就会导致物品从商城消失，所以我估计是客户端写死了那些商城id？不知道如何鉴别

**Comment by AUndead** [comment]
> > 
> 
> 修改 subTagNameTextMap 的任何作用，但是，所以那些物品没有从商城删除，所以我估计是客户端写死了商城 ID？

很有可能，感觉这问题很难解决了,还是把它关闭了吧，我有时间我琢磨琢磨看看
