### ISSUE TITLE
宝箱被攻击会消失[Bug] 

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1405]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by xNissX233** [comment]
I have the same issue. Chests will disappear when hit by an attack or skill. They just vanish and don't drop anything.

**Comment by Liujunhua007** [comment]
为什么我用action最新那个没宝箱...怎么开启呀

**Comment by lniuua** [comment]
攻击某些树木和可以互动的实体也会消失

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
