### ISSUE TITLE
大世界物资采集功能和宝箱功能如何同时开启

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1406]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by Liujunhua007** [comment]
怎么开启？在哪设置

**Comment by lingzn12** [comment]
？很显然，采集功能并不是写在lua脚本中，大佬有说过！大世界功能的话，配置文件里。

**Comment by Liujunhua007** [comment]
> ？很显然，采集功能并不是写在lua脚本中，大佬有说过！大世界功能的话，配置文件里。

哪个配置文件压，config看了眼，没有啊

**Comment by lniuua** [comment]
开启宝箱功能，大世界采集物就会消失

**Comment by zhaodice** [comment]
大世界脚本和采集物不可兼得，因为它们两个本质上是做同一个事情，只是大世界脚本拉了，它显示不出采集物(其实它是有的)
