### ISSUE TITLE
[Bug] 一次只能给予一个物品

### ISSUE THREAD

**Issue by AXAZXFAXA** [Melledy/Grasscutter#1408]
如题 改数量也没有,包括give all一次也只能拿一件物品

**Comment by Birdulon** [comment]
`用法：give <物品ID|角色ID|"all"(全部)|"weapons"(武器)|"mats"(材料)|"avatars"(角色)> [x<数量>] [lv<等级>] [r<精炼>]`
`give all [x<数量>]`
#1328 #1325

**Comment by AXAZXFAXA** [comment]
没用

**Comment by AXAZXFAXA** [comment]
> `用法：give <物品ID|角色ID|"all"(全部)|"weapons"(武器)|"mats"(材料)|"avatars"(角色)> [x<数量>] [lv<等级>] [r<精炼>]` `give all [x<数量>]` #1328 #1325

没用
dev版本这样,换回发行版就没这种bug了,应该不是我的问题

**Comment by sjzjams** [comment]
1.2.2dev 版本，give @100001 102 x100002  是可以的
