### ISSUE TITLE
[Bug] As soon as I enter the game, the CMD  prompt an error 

### ISSUE THREAD

**Issue by Liujunhua007** [Melledy/Grasscutter#1410]
Grasscutter version: 1.2.2-dev-f00cdd4
Git Hash: [d8d80f3130f313](https://github.com/Grasscutters/Grasscutter/actions/runs/2591739679)

![QQ截图20220701100808](https://user-images.githubusercontent.com/62129047/176809942-011720ff-5a83-48da-9ae5-8d945001d420.png)

**Comment by Birdulon** [comment]
image didn't upload?

**Comment by KingRainbow44** [comment]
this is a known issue with `Grasscutter_Resources` and the lua scripts in general.
