### ISSUE TITLE
[Bug] A large number of monsters of various kinds will be generated in some areas 部分区域会生成大量多种类的怪物

### ISSUE THREAD

**Issue by AUndead** [Melledy/Grasscutter#1416]
**Did you look for other closed issues that have the same problem?**

控制台出现错误信息并且很多区域生成大量多种类的怪物
Error messages appear on the console and a large number of monsters of various kinds are generated in many areas

**Describe the bug**
![#01err](https://user-images.githubusercontent.com/68094548/176983719-16d55893-780d-4523-b33c-5669a50f3219.png)

**Which branch did you use?**
  Grasscutter version: 1.2.2-dev
  Git Hash: d7776ed

**Screenshots**
![#0551](https://user-images.githubusercontent.com/68094548/176983504-65b11766-58f8-4f1f-ac85-b832b9e542bf.png)

**Additional context**
配置文件没有写入该多种类型的怪物生成配置
The configuration file does not write the various types of monster generation configuration

**Comment by lunaticwhat** [comment]
It's a known issue with monster spawn scripts!

**Comment by AUndead** [comment]
> 

我想去除部分区域的重复种类怪物它能修改么？
I want to remove duplicate monsters in some areas. Can it be modified?

**Comment by lunaticwhat** [comment]
> > 
> 
> I want to remove some areas of duplicate types of monsters Can it be modified? I want to remove duplicate monsters in some areas. Can it be modified?

yes you can, but you need to find out where are those in the game scripts. for now a temporary solution to this is just clear those monster with /killall if it occurred.

**Comment by akbaryahya** [comment]
it seems because function https://github.com/Grasscutters/Grasscutter/blob/7e7f1e11e0a0d96409a48bde6b1506a76de3f6f5/src/main/java/emu/grasscutter/scripts/SceneScriptManager.java#L348  is still not working and some scripts duplication with "checkSpawns" and "checkBlocks"

**Comment by SakuraYuki2K** [comment]
去配置里面把"enableScriptInBigWorld": false  改成true试试咯.....
