### ISSUE TITLE
release a Dockerflie？

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#142]
An amazing Job!
let's use docker to simplified the configuration process（╹◡╹）?

**Comment by lihe07** [comment]
I don't think this environment is very troublesome to configure(just my personal opinion)
The external dependencies are not complicated

**Comment by alphagocc** [comment]
Honestly, a docker image will be very convenient for many people to use

**Comment by insoxin** [comment]
I'll get right to work on it.

**Comment by ghost** [comment]
Now the project has too many issues about the environment. Like link error, java code error and so on.
It's a better way that run the server in a Linux docker, and then users only need to set the clients and redirect the traffic.

Problems about the server part can be reduced.

**Comment by StoneMoe** [comment]
See pull request #255

**Comment by Becods** [comment]
[HelloGrasscutter/HelloGrasscutter](https://github.com/HelloGrasscutter/HelloGrasscutter)

**Comment by luaneko** [comment]
[Grassdocker][1] is my attempt to create a proper Docker image for Grasscutter. To quote the README:

> This repository provides a Dockerfile that can be used to build a completely self-contained Docker image for Grasscutter. It tracks the **development branch** and is confirmed to be working with Genshin 2.6.
>
> The resulting image is about 1.4 GB in size and has:
>
> - All required resources (bins, excels, etc.) baked into the image
> - Fixed reliquary excels with weight props
> - Proper image layering and multistaged build
> - Proper TLS root and server certificates with DNS names for `mihoyo.com`, `yuanshen.com` and `hoyoverse.com`
> - No unnecessary dependencies in the resulting image

[1]: https://github.com/chiyadev/Grassdocker
