### ISSUE TITLE
公告配置文件中的 interval 值貌似不会生效，更改后还是以默认的间隔发送公告 [Bug] 

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1424]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by Akka0** [comment]
a little mistake🥲

**Comment by Birdulon** [comment]
Should be fixed by #1428
