### ISSUE TITLE
my bad, close plz

### ISSUE THREAD

**Issue by b9348** [Melledy/Grasscutter#1426]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

![1](https://user-images.githubusercontent.com/41979647/177027509-e3533a7f-09f3-4f8b-abc0-0fe58d4406ea.png)
![2](https://user-images.githubusercontent.com/41979647/177027511-29c53892-ca9f-4b7d-b4c7-4a9a1b49b5a8.png)
GC version : git clone 
server & mongod running
proxy use : https://github.com/liujiaqi7998/genshinclienthelper
![3](https://user-images.githubusercontent.com/41979647/177027535-179bed5c-b8e2-4836-9e7b-a8d380be64a7.png)

UI : genshen impact global version UI 
password use 1
 when i login , game must be updating
game version : CN latest

**Comment by b9348** [comment]
when i closed proxy, game is working for CN server

**Comment by b9348** [comment]
my bad, i didn't download RELEASE 1.12

**Comment by Birdulon** [comment]
You can close your own issues btw
