### ISSUE TITLE
请求添加一个可以记录服务器所有玩家使用指令情况的功能[Feature Request] 

### ISSUE THREAD

**Issue by lniuua** [Melledy/Grasscutter#1435]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lniuua** [comment]
防止恶意玩家给正常玩家添加凯特角色，导致无法正常游戏

**Comment by SunsetMkt** [comment]
Translation: [Feature Request] Command Usage Logger for All Players, which makes it easy to find destructive operations

**Comment by jie65535** [comment]
> 防止恶意玩家给正常玩家添加凯特角色，导致无法正常游戏

如果仅仅是这个目的，你需要的做的是管控权限，不要让普通玩家拥有指定目标玩家的权限。

---
> Prevent malicious players from adding Kate characters to normal players, causing the game to fail

If this is the only purpose, what you need to do is to control the authority, and don't let ordinary players have the authority to designate target players.
