### ISSUE TITLE
[Bug] Speciality foods not working when it should give you double of the dishes

### ISSUE THREAD

**Issue by xNissX233** [Melledy/Grasscutter#1442]
Specialty foods are working when you set a character that gives you a special dish (for example Klee, Fish-Flavored Toast), but when you set a character that has a probability of giving you double of the same food you are cooking, it never gives you anything else apart from the ones you cooked.
For example, if you set Barbara to cook a restoration food, it always gives you the same amount of food that you cooked, instead of randomly (12% chance) giving you double of them.

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
