### ISSUE TITLE
[Bug] 胡桃开E不扣血，魈开大招不扣血，新版无限能量指令在新的jar文件中无法正常关闭，追忆4件套的效果无法触发

### ISSUE THREAD

**Issue by devhxizm** [Melledy/Grasscutter#1445]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by KingRainbow44** [comment]
please follow the issue format, then make another issue.
