### ISSUE TITLE
[Bug] 胡桃和魈的扣血bug，还有追忆圣遗物的效果，伤害打不满的问题

### ISSUE THREAD

**Issue by devhxizm** [Melledy/Grasscutter#1448]
昨天测试的时候发现，胡桃开启E技能不会自动扣血，魈开启大招不会自动掉血(虽然没什么影响）,宵宫带上4件追忆圣遗物之后开启E技能不会按照追忆4件套的效果扣除能量以达到加伤的效果，所以怀疑追忆套有bug，希望能修复一下。还有一个是伤害打不满的问题，昨晚测试胡桃伤害的时候发现胡桃满命的伤害不如0命打的高，怀疑高命座的效果并没有加入到角色本身属性上。

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
