### ISSUE TITLE
Error 4206

### ISSUE THREAD

**Issue by Scirese** [Melledy/Grasscutter#145]
After I login ,it pops Error 4206.
Im using the latest dev branch.

Server log:
[16:35:08] [INFO] Game Server started on port 22102
[16:35:11] [INFO] [Dispatch] Client localhost/127.0.0.1:40396 is trying to log in via token
[16:35:11] [INFO] [Dispatch] Client localhost/127.0.0.1:40396 logged in via token as 10002
[16:35:11] [INFO] [Dispatch] Client localhost/127.0.0.1:40410 succeed to exchange combo token

Mitm log:
127.0.0.1:43226: client connect
127.0.0.1:43226: error establishing server connection: [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43226: POST http://localhost:8888/log
 << [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43226: client disconnect
127.0.0.1:43230: client connect
127.0.0.1:43230: error establishing server connection: [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43230: POST http://localhost:8888/log
 << [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43230: client disconnect
127.0.0.1:43234: client connect
127.0.0.1:43234: error establishing server connection: [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43234: POST http://localhost:8888/log
 << [Errno 111] Connect call failed ('127.0.0.1', 8888)
127.0.0.1:43234: client disconnect

java Version
openjdk version "16.0.2" 2021-07-20
OpenJDK Runtime Environment Microsoft-25298 (build 16.0.2+7)
OpenJDK 64-Bit Server VM Microsoft-25298 (build 16.0.2+7, mixed mode)ion

**Comment by lihe07** [comment]
Check port number 8888
If there are no problem, this port should be accessible and it is part of the Grasscutter service.

**Comment by Scirese** [comment]
> Check port number 8888 If there are no problem, this port should be accessible and it is part of the Grasscutter service.

Connection refused.(NO Firewall)
it seems grasscutter is not using this port.

**Comment by alt3ri** [comment]
maybe you didn't use that port?

**Comment by Scirese** [comment]
> maybe you didn't use that port?

Yes，seems grasscutter is not using this port

**Comment by MlgmXyysd** [comment]
send your `config.json` here

**Comment by Scirese** [comment]
> send your `config.json` here

https://pastebin.com/3vnpkeww

**Comment by memetrollsXD** [comment]
Perhaps something is wrong with the certificate? That it doesn't trust it

**Comment by Scirese** [comment]
> Perhaps something is wrong with the certificate? That it doesn't trust it

the certificate of mitmproxy? I putted it in system trust store and trusted it properly.

**Comment by memetrollsXD** [comment]
Also the p12 certificate provided by Grasscutter?

**Comment by Scirese** [comment]
> Also the p12 certificate provided by Grasscutter?

perhaps no,How can i trust it on android?

**Comment by AlexAnorak** [comment]
same problem on pc

**Comment by MlgmXyysd** [comment]
> > send your `config.json` here
> 
> https://pastebin.com/3vnpkeww

"PublicIp" can't be "127.0.0.1" unless you are running server & client on the same device

**Comment by Scirese** [comment]
Now its Error 4201

**Comment by jinmvp** [comment]
I got 4201 error now.

**Comment by Scirese** [comment]
its my local dns issue ,closing it

**Comment by czy20010112** [comment]
> its my local dns issue ,closing it

also 4201 , could i please tell me how to solve it? many thanks

**Comment by xia0ji233** [comment]
> > > send your `config.json` here
> > 
> > 
> > https://pastebin.com/3vnpkeww
> 
> "PublicIp" can't be "127.0.0.1" unless you are running server & client on the same device

I got the same problem,but there are no item named "Publiclp",Maybe it is "accessAddress" now？
I'll try later.
