### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Aesthetical2004** [Melledy/Grasscutter#1453]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Map??

**Comment by Birdulon** [comment]
what??

**Comment by 2y8e9h22** [comment]
?

**Comment by KiminaNatsuki** [comment]
???

**Comment by alt3ri** [comment]
huh
