### ISSUE TITLE
[Bug] Gift bag invalid

### ISSUE THREAD

**Issue by zhcii** [Melledy/Grasscutter#1454]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

I found the gift bag invalid when playing, and I didn't get any items after using it. How to fix this problem?
**Which branch did you use?**

Grasscutter-1.2.2-dev
Git Hash: f45e01d
**Screenshots**

![Genshin Impact Screenshot 2022 07 07 - 16 28 38 86](https://user-images.githubusercontent.com/105128114/177732555-364f7a9c-77d9-417b-9c14-aa2daf67230a.png)

**Additional context**

**Comment by lunaticwhat** [comment]
its not implemented yet.

**Comment by lingzn12** [comment]
尚未添加这个功能。

**Comment by mIwaYuhang** [comment]
这是相同的问题，不应该重复出现#1320

**Comment by mIwaYuhang** [comment]
> 这是相同的问题，不应该重复出现#1320

并且在#1320中提过这个问题的修复方案，请尝试

**Comment by zhcii** [comment]
> > 这是相同的问题，不应该重复出现#1320
> 
> 并且在#1320中提过这个问题的修复方案，请尝试

谢谢，我居然还翻译成英文。。。

**Comment by KiminaNatsuki** [comment]
Since this has been answered already, I will be closing this down.
