### ISSUE TITLE
[Bug] 合作模式中出现角色释放技能或元素爆发在同伴视角会卡顿

### ISSUE THREAD

**Issue by zxl-qq927489674** [Melledy/Grasscutter#1460]
<!--- Example: 

grasscutter-1.2.2-dev

--

**Additional context**
在合作的模式下，角色释放技能或元素爆发，在同伴视角会出现卡顿情况。这个情况在ping良好也会出现

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
