### ISSUE TITLE
Discord crashing and domains not working

### ISSUE THREAD

**Issue by MARKSMAN69** [Melledy/Grasscutter#1463]
My discord will suddenly restart itself and get locked in the loading screen so I have to restart the game to let discord load and keep doing that.
![image](https://user-images.githubusercontent.com/36036713/177861437-6546d2c3-f76d-4999-81e2-5b7d03711b79.png)
Also I tried doing the thundering fury domain and it got to 10/15 kills and nothing spawned so I could not complete the domain.

**Comment by SpikeHD** [comment]
Any problems with Discord are unrelated to Grasscutter, and are instead likely a problem with your proxy configuration.

**Comment by gawgua** [comment]
your proxy sucks, use Fiddler

**Comment by Thereallo1026** [comment]
skill issue

**Comment by MARKSMAN69** [comment]
alright fair

**Comment by MARKSMAN69** [comment]
okay what about the domains though so I need to reopen that?

**Comment by SpikeHD** [comment]
Create a new issue.
