### ISSUE TITLE
[Bug] 深渊12层第一间下半没有怪，也不能完整的通过深渊

### ISSUE THREAD

**Issue by daxiwow** [Melledy/Grasscutter#1470]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
