### ISSUE TITLE
[Feature Request] 建议增加对sqlite数据库的支持

### ISSUE THREAD

**Issue by oncebeloved** [Melledy/Grasscutter#1471]
建议增加对sqlite数据库的支持，方便在本地化服务运行
It is suggested to increase the support for sqlite database to facilitate the operation of localization services.

**Comment by ZhiShengYuan** [comment]
SQLITE对于此类应用并不太适合，而且会极大的增加工作量，且性能不佳
I don't consider that using SQLite in this project is a good idea for the mongo DB offer JSON save and load, and it's wont have good performance even in the single-player scene; BTW,adding SQLite support would create a lot of unnecessary work and MongoDB local deployment is not very difficult

**Comment by nitrog0d** [comment]
This is a good idea imo, less stuff to install in your PC if you're not a developer
I myself don't like running MongoDB on my computer (I tried using an external MongoDB Database but at the time GC didn't support SSL for them, I don't know if it does now though), it's also a Windows service (which I know it can be disabled at installation) and it's running on the background all the time

**Comment by ZhiShengYuan** [comment]
> This is a good idea imo, less stuff to install in your PC if you're not a developer
> I myself don't like running MongoDB on my computer (I tried using an external MongoDB Database but at the time GC didn't support SSL for them, I don't know if it does now though), it's also a Windows service (which I know it can be disabled at installation) and it's running on the background all the time

Well,but I still think that it’s unneeded because this software may run better in server but not client
Btw,I’m glad to see the support of SQLite even maraidb ,that I can use existing Marian instead adding a mongodb server

**Comment by Akka0** [comment]
but currently gc used morphia is a mongo ORM😢

**Comment by KiminaNatsuki** [comment]
Please follow the issue format first, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
