### ISSUE TITLE
[Bug] 攻击部分可交互实体会使其消失

### ISSUE THREAD

**Issue by z7087** [Melledy/Grasscutter#1476]
**Did you look for other closed issues that have the same problem?**

  https://github.com/Grasscutters/Grasscutter/issues/1405

**Describe the bug**

  当我持续攻击宝箱或部分可被攻击到的实体时，实体一段时间后会消失。

**Which branch did you use?**

  https://github.com/Grasscutters/Grasscutter/actions/runs/2641261047
  Grasscutter version: 1.2.2-dev
  Git Hash: 0141dce

**Screenshots**

![11111](https://user-images.githubusercontent.com/75190047/178110848-82154153-6fdb-4916-a511-daafb4222521.png)
![22222](https://user-images.githubusercontent.com/75190047/178110961-076854b9-80eb-4dca-855a-48db6c1dcbc9.png)

**Additional context**

**Comment by wumulong-469** [comment]
![Screenshot_2022-07-10-07-08-46-277_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/57058163/178125723-cc702d30-4e24-4189-ac5f-8be06fb59365.jpg)

![Screenshot_2022-07-10-07-08-59-617_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/57058163/178125728-cb243dd3-0db9-4fc1-809e-4181ac62758a.jpg)

我也发现了，机关可以打掉。矿好像也遵循这个道理，用单手剑或者长枪挖矿没掉落，在黄条还没打完直接消失。

**Comment by zhaodice** [comment]
已修复 https://github.com/Grasscutters/Grasscutter/pull/1606
