### ISSUE TITLE
Remove events, inventory, character icon when playing Spiral Abyss

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1481]
Hi, I would like to remove these 3 icons when at Spiral Abyss.

These 3 are:
- Events icon
- Inventory icon
- Character icon

I want them to be gone while at Abyss only, without affecting other dungeons. Is there any way on the code to do this?

That's all, thanks.

**Comment by akatatsu27** [comment]
most GUI elements, including those you mentioned, are managed by the OpenState system, which I implement the framework for in PR #1483, however I'm not familiar with how abyss works, so someone else would have to implement the triggers to remove and add these icons

**Comment by fnthinklevi** [comment]
I don't think it's necessary. You should focus on achieving the operability of the task.

**Comment by ghost** [comment]
> I don't think it's necessary. You should focus on achieving the operability of the task.

yeah, it's not that necessary. But I used to record vids and share screenshots, it will be sus if those buttons that I mentioned appeared on Spiral Abyss while recording or doing ss.

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。

Extra:
![image](https://user-images.githubusercontent.com/34180607/179308716-bd450355-f200-4b91-bc00-19ee64d4627d.png)
