### ISSUE TITLE
Unable to login after do gacha

### ISSUE THREAD

**Issue by MlgmXyysd** [Melledy/Grasscutter#149]
![image](https://user-images.githubusercontent.com/17919858/164889238-fef26812-aa6d-4906-b5d1-d4f0affb8658.png)

![image](https://user-images.githubusercontent.com/17919858/164889233-7c0a3131-c49c-4c24-a54d-efbbee6cc12d.png)

At the same time, the dispatch account is lost.

It seems that the database has gone wrong. Restarting the server and database server not work.

No exceptions reported on the console.

**Comment by lunaticwhat** [comment]
can you send me your mongo database might take a look at it @lunatic#1911 discord

**Comment by alt3ri** [comment]
set WatchGacha = false in config. I was just encountered that

**Comment by MlgmXyysd** [comment]
> set WatchGacha = false in config. I was just encountered that

already false

**Comment by alt3ri** [comment]
that's weird

**Comment by lhhxxxxx** [comment]
check the bond_ip of mongodb, add localhost to it or change it to 0.0.0.0

**Comment by KingRainbow44** [comment]
stale issue. will close. feel free to reopen if the bug still persists.
