### ISSUE TITLE
[Feature Request] Add "continue challenge" and clear time on domains (except Spiral Abyss)

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1496]
Hi, I would like to suggest adding "continue challenge" button and clear time (not necessary) on domains. 

PS: I know I can do !dungeon [domain id] but typing and typing again on console is very tiring and consumes time. 

Pics:

GC:
![image](https://user-images.githubusercontent.com/86816436/178404391-4cb4571b-d286-4e27-ab2d-469c21a15c31.png)

Official:
![image](https://user-images.githubusercontent.com/86816436/178404462-b51884b1-6cbe-46dd-8b1d-2c3dbeb89862.png)

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。

**Comment by KiminaNatsuki** [comment]
Extra:
![image](https://user-images.githubusercontent.com/34180607/179308238-b47ed3c7-d3ec-4e19-a090-77a77cebab23.png)
