### ISSUE TITLE
[Bug] 4214

### ISSUE THREAD

**Issue by cfuncode** [Melledy/Grasscutter#1502]
![image](https://user-images.githubusercontent.com/36926346/178626941-06d54136-7510-4640-b6a4-1adff2f49cc2.png)

Can't connect

**Comment by gszshdzz** [comment]
+1

**Comment by dahisea** [comment]
Because of “New version need patch  And the Grasscutter Server isn't update to 2.8(fake)

**Comment by eternalcomet** [comment]
you need to patch metadata or UserAssembly.dll of your game file.a new version of the unofficial launcher cultivation may have a solution soon.

**Comment by thelegendaryjohn** [comment]
Wait... Grasscutter isn't updated to 2.8? I have a similar problem and I think it was because I (accidentally) updated the game files to ver 2.8

**Comment by Birdulon** [comment]
> Wait... Grasscutter isn't updated to 2.8?

https://github.com/Grasscutters/Grasscutter/tree/2.8 is up for testing. You will need to use Cultivation if you aren't using it already, as the dispatch login process has changed.

**Comment by thelegendaryjohn** [comment]
Isn't Grasscutter 1.2.0 an older ver though? I have the Cultivation launcher, which has an option to install Grasscutter and its dependencies, and the jar file is 1.2.2-dev. It certainly looks like an experimental ver. yes, but it's still the newer ver. (maybe), so it should support Genshin 2.8, right?

**Comment by GanyusLeftHorn** [comment]
No, you specifically need to use the 2.8 branch (https://github.com/Grasscutters/Grasscutter/tree/2.8) for 2.8 support. Everything else is still on 2.7.

**Comment by hello886** [comment]
> No, you specifically need to use the 2.8 branch (https://github.com/Grasscutters/Grasscutter/tree/2.8) for 2.8 support. Everything else is still on 2.7.

My 2.8 still shows 4214

**Comment by 4Benj** [comment]
Make sure you download the [Client Patching PR](https://github.com/Grasscutters/Cultivation/pull/22) of Cultivation and compile it.

**Comment by 4Benj** [comment]
> Isn't Grasscutter 1.2.0 an older ver though? I have the Cultivation launcher, which has an option to install Grasscutter and its dependencies, and the jar file is 1.2.2-dev. It certainly looks like an experimental ver. yes, but it's still the newer ver. (maybe), so it should support Genshin 2.8, right?

Cultivation doesn't automatically download the 2.8 branch. You will have to download and compile manually

**Comment by thelegendaryjohn** [comment]
> Make sure you download the [Client Patching PR](https://github.com/Grasscutters/Cultivation/pull/22)

Why does this look so scary? Is that too much of a risk?

**Comment by 4Benj** [comment]
> Why does this look so scary? Is that too much of a risk?

The only risk is if that if you don't restore your metadata, you run the risk of getting your account banned. 
Apart from UA patching, we can't do anything else because of the changes made in 2.8...

**Comment by GanyusLeftHorn** [comment]
There certainly is a risk. If you don't feel comfortable using this in it's current state and/or don't know what you are doing, I would advise you to stay away for now.

**Comment by thelegendaryjohn** [comment]
> There certainly is a risk. If you don't feel comfortable using this in it's current state and/or don't know what you are doing, I would advise you to stay away for now.

So its current state is a WIP? So now, I have to wait for (if there will be) a stable release of Grasscutter for 2.8?

**Comment by thelegendaryjohn** [comment]
> > Why does this look so scary? Is that too much of a risk?
> 
> The only risk is if that if you don't restore your metadata, you run the risk of getting your account banned. Apart from UA patching, we can't do anything else because of the changes made in 2.8...

1. So the only risk is getting banned if I don't strictly follow the instruction?
2. What if I make a copy of the entire game data folder on another place on my PC and launch the game from there instead? So then I should have 2 separate ver of Genshin, unmodified and modified?

**Comment by MonianHello** [comment]
> 1. So the only risk is getting banned if I don't strictly follow the instruction?
> 2. What if I make a copy of the entire game data folder on another place on my PC and launch the game from there instead? So then I should have 2 separate ver of Genshin, unmodified and modified?

Even if the file is not modified, I still recommend **not** to use grasscutter on devices that play with your HoYoverse account.No one knows whether your data will be submitted to mihoyo in the 2.8 version,It's really UNPREDICTABLE.

**Comment by thelegendaryjohn** [comment]
Oh ok, got it!

**Comment by RTBSG** [comment]
2.8+
Cultivation1.0.
![Z)9}E@%S`Y~RB4PDUT809P1](https://user-images.githubusercontent.com/82012493/178727174-d3fc8187-4818-4a92-839f-cc74a5954465.png)
2

**Comment by LiuQixuan** [comment]
I found error after debugging.The sever(version 2.7) can't resolve url about '127.0.0.1/crash/dataUpload ',I think let server return `{"code":0}` can solution this problem. but I no time read the server code. Who have the detail doc for the project?

**Comment by thelegendaryjohn** [comment]
> > 1. So the only risk is getting banned if I don't strictly follow the instruction?
> > 2. What if I make a copy of the entire game data folder on another place on my PC and launch the game from there instead? So then I should have 2 separate ver of Genshin, unmodified and modified?
> 
> Even if the file is not modified, I still recommend **not** to use grasscutter on devices that play with your HoYoverse account.No one knows whether your data will be submitted to mihoyo in the 2.8 version,It's really UNPREDICTABLE.

So... I can make a copy of the whole game data folder, but on a another PC?

**Comment by github5524** [comment]
现在 有没有人成功设置服务器 进入 关心

**Comment by SpikeHD** [comment]
> > > 1. So the only risk is getting banned if I don't strictly follow the instruction?
> > > 2. What if I make a copy of the entire game data folder on another place on my PC and launch the game from there instead? So then I should have 2 separate ver of Genshin, unmodified and modified?
> > 
> > 
> > Even if the file is not modified, I still recommend **not** to use grasscutter on devices that play with your HoYoverse account.No one knows whether your data will be submitted to mihoyo in the 2.8 version,It's really UNPREDICTABLE.
> 
> So... I can make a copy of the whole game data folder, but on a another PC?

An easier method would likely be to dual-boot a second copy of Windows to play your other version of the game.

**Comment by millet6** [comment]
Resolved, view tutorial b站 原神2.8国际服启动器电脑端教程
https://www.bilibili.com/video/BV15T411J7n7?share_source=copy_web

**Comment by github5524** [comment]
安卓grasscutter 是否有最新可用版本

**Comment by thelegendaryjohn** [comment]
恐怕现在不适用于 Android

**Comment by L4cache** [comment]
> Resolved, view tutorial b站 原神2.8国际服启动器电脑端教程 https://www.bilibili.com/video/BV15T411J7n7?share_source=copy_web

The launcher mentioned in the video is this one: https://github.com/gc-toolkit/OceanLauncher
I personally don't want to use a launcher, so I patched the game then use my old way to log in to the grasscutter, seems there's no problem. Of course, be sure to do the patch on a separate copy.
Further more, you can manually *replace* the file in yuanshen_data\managed\metadata.

**Comment by millet6** [comment]
> > Resolved, view tutorial b站 原神2.8国际服启动器电脑端教程 https://www.bilibili.com/video/BV15T411J7n7?share_source=copy_web
> 
> The launcher mentioned in the video is this one: https://github.com/gc-toolkit/OceanLauncher I personally don't want to use a launcher, so I patched the game then use my old way to log in to the grasscutter, seems there's no problem. Of course, be sure to do the patch on a separate copy. Further more, you can manually _replace_ the file in yuanshen_data\managed\metadata.

Directly replaceable app   D:\yuanshen\Genshin Impact\Genshin Impact game\GenshinImpact_Data\Managed\Metadata\global-metadata.dat

**Comment by Needdaima** [comment]
> 
新的metadata.dat在哪找

**Comment by eternalcomet** [comment]
修补global-metadata.dat文件
[国际服.zip](https://github.com/577fkj/GenshinProxy/files/9107929/default.zip)

[国服.zip](https://github.com/577fkj/GenshinProxy/files/9107927/default.zip)
。

**Comment by eternalcomet** [comment]
> > 
> 
> 新的metadata.dat在哪找

[国际服.zip](https://github.com/577fkj/GenshinProxy/files/9107929/default.zip)

[国服.zip](https://github.com/577fkj/GenshinProxy/files/9107927/default.zip)
。

**Comment by KiminaNatsuki** [comment]
The current issues has been solved by a lot of people already so I will be closing this down.

**Comment by FlameMaster** [comment]
so,I still 4214
