### ISSUE TITLE
[Bug] Failed to create gacha mappings and Relic properties are missing weights

### ISSUE THREAD

**Issue by Liujunhua007** [Melledy/Grasscutter#1506]
**Describe the bug**
Run grasscutter.jar and report errors.

**Which branch did you use?**

  Grasscutter version: 1.2.2-dev
  Git Hash: https://github.com/Grasscutters/Grasscutter/actions/runs/2661623719

**Screenshots**

![QQ截图20220713173555](https://user-images.githubusercontent.com/62129047/178703463-4aafc28d-2e90-4054-b9c9-1edd3a6ea51f.png)
![QQ截图20220713173543](https://user-images.githubusercontent.com/62129047/178703471-26e71593-df92-4e69-9e12-99490d1d4eda.png)

**Additional context**

Error when log in

**Comment by mofayukeji** [comment]
服务端游戏版本2.7，游戏版本2.8
server game version 2.7，game version 2.8
至于缺失权重是另一个问题，说明你没好好看教程

**Comment by VAGUE000** [comment]
You probably don't have new resources. https://github.com/Koko-boya/Grasscutter_Resources/tree/2.8
Anyway, the best thing to do is to wait for Cultivation to get updated.

**Comment by Liujunhua007** [comment]
Ok,But I update to https://github.com/Grasscutters/Grasscutter/actions/runs/2661955213 
It is now 2.8 ,But I can't still log in

**Comment by millet6** [comment]
Resolved, view tutorial b站 原神2.8国际服启动器电脑端教程
https://www.bilibili.com/video/BV15T411J7n7?share_source=copy_web

**Comment by Ljzd-PRO** [comment]
同样，Failed to create gacha mappings，客户端版本2.8。代理重定向、SSL等都没问题。
不知道会不会和`resources`目录有关。
```
Your choice:[EN] chs
03:04:01 <WARN:DataLoader> Failed to create gacha mappings.
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.util.Map.get(Object)" is null
03:04:01 <INFO:Grasscutter> 正在启动 Grasscutter...
03:04:01 <INFO:Grasscutter> 游戏版本：2.8.0
03:04:01 <INFO:Grasscutter> Grasscutter 版本：1.2.3-dev-d6e6aa4
03:04:01 <INFO:ResourceLoader> 正在加载 resources...
03:04:03 <INFO:ResourceLoader> 完成加载 resources。
03:04:11 <INFO:HttpServer> [Dispatch] 服务器已在端口 433 上启动
03:04:11 <INFO:GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。如果你是付费购买的，那你已经被骗了。项目地址：https://github.com/Grasscutters/Grasscutter
03:04:11 <INFO:GameServer> 游戏服务器已在端口 22102 上启动
03:04:11 <INFO:Grasscutter> 加载完成！输入 "help" 查看命令列表
```

**Comment by Ljzd-PRO** [comment]
> 同样，Failed to create gacha mappings，客户端版本2.8。代理重定向、SSL等都没问题。 不知道会不会和`resources`目录有关。
> 
> ```
> Your choice:[EN] chs
> 03:04:01 <WARN:DataLoader> Failed to create gacha mappings.
> java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.util.Map.get(Object)" is null
> 03:04:01 <INFO:Grasscutter> 正在启动 Grasscutter...
> 03:04:01 <INFO:Grasscutter> 游戏版本：2.8.0
> 03:04:01 <INFO:Grasscutter> Grasscutter 版本：1.2.3-dev-d6e6aa4
> 03:04:01 <INFO:ResourceLoader> 正在加载 resources...
> 03:04:03 <INFO:ResourceLoader> 完成加载 resources。
> 03:04:11 <INFO:HttpServer> [Dispatch] 服务器已在端口 433 上启动
> 03:04:11 <INFO:GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。如果你是付费购买的，那你已经被骗了。项目地址：https://github.com/Grasscutters/Grasscutter
> 03:04:11 <INFO:GameServer> 游戏服务器已在端口 22102 上启动
> 03:04:11 <INFO:Grasscutter> 加载完成！输入 "help" 查看命令列表
> ```

https://github.com/Grasscutters/Grasscutter/actions/runs/2726397297

2.7的jar核心搭配2.8的resources似乎不会提示 Failed to create gacha mappings，但是因为客户端版本为2.8，也会4206

**Comment by Birdulon** [comment]
#1605 should have fixed gacha mappings generation, if anyone encounters `Relic properties are missing weights` it's a resources problem.
