### ISSUE TITLE
[Feature Request] When a character dies, he cannot be revived by any means,

### ISSUE THREAD

**Issue by 1072387333** [Melledy/Grasscutter#1507]
When I made a mistake to kill a character, I found that he could not be revived by any means, including using the heal code of the console

And every time I log in again and switch to this role, I will be forced to log in again because I "can't link to the service"

Maybe I can solve the second problem by eliminating the role, but the role can't revive this problem. I need help

**Comment by KiminaNatsuki** [comment]
Please follow the issue format, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
