### ISSUE TITLE
[Bug]卡池出问题，修改json文件仍无法使用

### ISSUE THREAD

**Issue by ouhuangoaa** [Melledy/Grasscutter#1508]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by mIwaYuhang** [comment]
[Banners.zip](https://github.com/Grasscutters/Grasscutter/files/9111282/Banners.zip)

**Comment by mIwaYuhang** [comment]
> [Banners.zip](https://github.com/Grasscutters/Grasscutter/files/9111282/Banners.zip)

2.8上半场

**Comment by curryyinxh** [comment]
[全角色武器.txt](https://github.com/Grasscutters/Grasscutter/files/9274138/default.txt)
