### ISSUE TITLE
[Bug] Cannot scroll through help command

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#1519]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

The help command is kind of useless now that it's sent all as one message because it cannot be scrolled. The command used to work better when it sent each command as its own individual message, however now it's impossible to scroll through the output of the command. As seen in the video below, it is impossible to get any more information than what's at the bottom.

**Which branch did you use?**
Grasscutter version: 1.2.2-dev
Git Hash: e7fb5362

**Screenshots**

https://user-images.githubusercontent.com/104761702/179389329-24af7756-7de3-4006-ac6e-fe08838a0375.mp4

**Additional context**

The old system sent it as many individual messages. I'm not sure of exactly when things started breaking.

**Comment by 4Benj** [comment]
blame #1427 (I think)... The whole reason I split it into multiple messages was for exactly this reason...

**Comment by Birdulon** [comment]
It was already a single message before #1427. I'll split it up regardless.

**Comment by KingRainbow44** [comment]
suggestion for this: why dont we add pages to the help command? (at least for the in-game version)
