### ISSUE TITLE
[Bug] When I entered the game through version 2.8, the screen remained blank. "Connection timeout" is displayed after a period of time.

### ISSUE THREAD

**Issue by DepartingWind** [Melledy/Grasscutter#1522]
I made sure I downloaded GrassCutter from the 2.8 branch. Following the tutorial instructions, I compiled "grasscutter. Jar" myself using CMD. I also deleted the 2.7 "config.json" file.
When grassCutter is started, CMD appears as follows,
![image](https://user-images.githubusercontent.com/67886621/179402532-4c6542c1-efa2-414c-94eb-114c518c398f.png)
The first time I entered the game, error 4214 popped up.
After that, I modified the file in the official game folder (YuanShen_Data\Managed\Metadata). This time, I successfully entered the game without error.
But the screen kept going blank. A connection timeout is displayed after a period of time.
![image](https://user-images.githubusercontent.com/67886621/179402697-d7d61a96-d50d-4806-8be9-24bf892515be.png)
CMD also seems to be reporting an error.
![image](https://user-images.githubusercontent.com/67886621/179402735-80973dab-dc04-4038-9e8f-a8c269ac7602.png)
I suspect grasscutter made an error loading the resource. Because a lot of things are loaded when you start up The 2.7 Version of GrassCutter. But the 2.8 version of GrassCutter only shows resources successfully loaded.

**Comment by AZthemute** [comment]
This isn't a bug - this is a problem with your database.

You put a map marker somewhere in the old archipelago map. Go to mongodb, go to the grasscutter database and go to players. Check every mapMark in that collection. If you find one with a sceneId of 4, delete it.

**Comment by DepartingWind** [comment]
> This isn't a bug - this is a problem with your database.
> 
> You put a map marker somewhere in the old archipelago map. Go to mongodb, go to the grasscutter database and go to players. Check every mapMark in that collection. If you find one with a sceneId of 4, delete it.

I went back to the old version and checked my map. I realized I hadn't made any marks.
I also tried to go into my database and delete some files that I thought had a "4" in them. But it didn't work.

![image](https://user-images.githubusercontent.com/67886621/179416763-7f5b1c9d-0df8-47ba-832e-fbf1429ff71d.png)
![image](https://user-images.githubusercontent.com/67886621/179416792-a256c048-01f2-4852-87fe-57473556d816.png)
![image](https://user-images.githubusercontent.com/67886621/179416782-bb8f7739-c82a-41ff-8a28-5ef2fe6bbe8e.png)
![image](https://user-images.githubusercontent.com/67886621/179416798-992ad33c-1a6c-4581-b1e5-e9ee74c521c8.png)

The files highlighted in red above are the ones I tried to delete.

**Comment by millet6** [comment]
> 

删除mongodb/data文件夹内所有内容（解压mongodb/DATA.rar备份文件），重新注册就可以了

**Comment by DepartingWind** [comment]
The method of deleting the database and generating a new one did succeed. But the previous data is missing, which is a pity.
However, this 2.8 resource is not complete. Diluc and Fischl's new clothes are not available.

**Comment by KiminaNatsuki** [comment]
> The method of deleting the database and generating a new one did succeed. But the previous data is missing, which is a pity. However, this 2.8 resource is not complete. Diluc and Fischl's new clothes are not available.

https://github.com/Koko-boya/Grasscutter_Resources

**Comment by RTBSG** [comment]
This is caused by enumeration conflict. If you want to keep the data and add the corresponding enumeration type to the file, just do it

**Comment by KiminaNatsuki** [comment]
> This is caused by enumeration conflict. If you want to keep the data and add the corresponding enumeration type to the file, just do it

**Comment by Aemeath5** [comment]
How to do it

**Comment by Aemeath5** [comment]
> > 这是由枚举冲突引起的。如果要保留数据并将相应的枚举类型添加到文件中，只需执行此操作

How to do it

**Comment by RTBSG** [comment]
> > > 这是由枚举冲突引起的。如果要保留数据并将相应的枚举类型添加到文件中，只需执行此操作
> 
> 怎么做
Find the class [mapmarkfromtype] in the file [mapmarkfromtypeouterclass] and add the enumeration attribute

MAP_ MARK_ FROM_ TYPE_ NOE(0)
Of course, it needs to be repackaged

**Comment by Aemeath5** [comment]
> > > > 这是由枚举冲突引起的。如果要保留数据并将相应的枚举类型添加到文件中，只需执行此操作
> > 
> > 
> > 怎么做 在文件 [mapmarkfromtypeouterclass] 中查找类 [mapmarkfromtype] 并添加枚举属性
> 
> MAP_ MARK_ FROM_ TYPE_ NOE（0） 当然，它需要重新包装

赋予值多少呢

**Comment by RTBSG** [comment]
> MAP_ MARK_ FROM_ TYPE_ NOE(0)

MAP_ MARK_ FROM_ TYPE_ NOE(0)

**Comment by AAAAAries** [comment]
Hello! I also encountered the same blank problem, but I used the server terminal installed in CentOS system, and tried to replace the data file, but it was useless. I suspected that there was an error in the mongodb database, but since I was first exposed to Linux system, I dare not easily try to delete the database and re create it. Is there a solution?
