### ISSUE TITLE
[Bug] Cannot give negative amount of an item

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#1523]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

You used to be able to give yourself negative amounts of an item, but that has been broken, most likely ever since the PR that overhauled this command (and many other commands), however I'm not sure. This would give you 2,147,483,647 - [the amount you entered], but in effect it would take away that item from your account.

**Which branch did you use?**

Grasscutter version: 1.2.2-dev
Git Hash: a253c96b

**Screenshots**

![image](https://user-images.githubusercontent.com/104761702/179401826-7ae6ac02-8478-4fc2-99cb-2f06658d8006.png)

**Additional context**

**Comment by KiminaNatsuki** [comment]
#1392

**Comment by AZthemute** [comment]
> #1392

Yup that encompasses my issue, ty!
