### ISSUE TITLE
[Feature Request] How to modify the reset account password

### ISSUE THREAD

**Issue by Aemeath5** [Melledy/Grasscutter#1525]
How to modify the reset account password？Is there a command for this？Also, is it possible to modify the UID of an account with an existing UID?

**Comment by millet6** [comment]
你可以用 mongodb管理工具修改。如：mongodb-compass

**Comment by 4Benj** [comment]
Invalid Issue.
Your last was already closed by a moderator.
Do not open another.
Instead join our [Discord](https://discord.gg/grasscutter) and our community can help you.
