### ISSUE TITLE
[Feature Request] 我想替换 星辉商城中的商品 如何实现？

### ISSUE THREAD

**Issue by millet6** [Melledy/Grasscutter#1528]
![图片](https://user-images.githubusercontent.com/109255084/179448586-abb5f2b2-f4f1-48e4-9f08-14d1e9eaa529.png)

**我修改了 \grasscutter\data\ShopGoodsExcelConfigData.json 内容 "itemId":  并重启服务器**，但它并没有生效，还要修改其他什么文件来实现这个想法？ 我只想替换，不是增加，如果有相关快速修改的工具最好了。希望能得到帮助，谢谢
![图片](https://user-images.githubusercontent.com/109255084/179448660-ef5f2ae3-b4a6-47f3-bf05-75fcd4147fdf.png)

**Comment by mIwaYuhang** [comment]
修改/Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json并正确填写商店ID列表与物品ID

**Comment by mIwaYuhang** [comment]
[
    {//902礼包商城	
        "shopId": 902,//商店id
        "items": [
		    {
                "goodsId": 10048002,//要求每个不一样
                "goodsItem": {//货物id
                    "id": 306,//id
                    "count": 100//数量
                },
                "buyLimit": 100000,//购买限制数量
                "beginTime": 1575129600,//时间
                "endTime": 2051193600,//时间
                "minLevel": 1,//最小冒险等级
                "maxLevel": 99,//最大冒险等级
                "costItemList": [{//花费物品
                        "id": 305,
                        "count": 300
                    }, {
                        "id": 201,
                        "count": 10000
                    }
                ]
            },
		    {
                "goodsId": 10048003,//要求每个不一样
                "goodsItem": {//货物id
                    "id": 306,//id
                    "count": 100//数量
                },
                "buyLimit": 100000,//购买限制数量
                "beginTime": 1575129600,//时间
                "endTime": 2051193600,//时间
                "minLevel": 1,//最小冒险等级
                "maxLevel": 99,//最大冒险等级
                "costItemList": [{//花费物品
                        "id": 305,
                        "count": 300
                    }, {
                        "id": 201,
                        "count": 10000
                    }
                ]
            }
        ] 			
    },      
    {//1001尘辉兑换
    },
    {//1002荣光之风1
    },
    {//1003铁匠武器店
    },
    {//1004蒙德杂货铺
    }, 
    {//1005猎鹿人
    }, 
    {//1006
    },
    {//1007原萃树脂
    },
    {//1008东升
    },
    {//1009岩之印商店
    },
    {//1010卯师傅
    },
    {//1011芙萝拉
    },
    {//1012查尔斯
    },
    {//1013石榴
    },
    {//1014舒茨
    },
    {//1015布洛克
    },
    {//1016神奇的霍普金斯
    },
    {//1017杜拉夫
    },
    {//1018克罗丽丝
    },
    {//1019璃彩
    },
    {//1020月疏
    },
    {//1021阿桂
    },
    {//1022老高
    },
    {//1023老孙
    },
    {//1024绮命
    },
    {//1025张顺
    },
    {//1026快刀陈
    },
    {//1027中原杂碎店
    },
    {//1028石头
    },
    {//1029纪芳
    },
    {//1030朱老板
    },
    {//1031小白
    },
    {//1032老周叔？或者凯叔？
    },
    {//1033琳琅
    },
    {//1034菲尔戈黛特
    },
    {//1035 老周叔？或者凯叔？
    },
    {//1036一大袋摩拉（北国银行）
    },
    {//1037熄星活动
    },
    {//1038叶卡捷琳娜（存疑）
    },
    {//1039哈里斯雪山前营地
    },
    {//1040「白垩与黑龙」活动商店兑换
    },
    {//1041迷你仙灵活动
    },    
    {//1042  宜年 海灯节
    },
    {//1043 某之印商店
    },
    {//1044芙罗拉
    }, 
    {//1045璃月长顺npc
    },
    {//1046万有铺子博来
    },
    {//1047//阿山婆玩具摊
    },
    {//1048尘歌壶
    },
    {//1049
    },    
    {//1050//路爷工坊主人
    },
    {//1051歌德大酒店
    },
    {//1052角色装扮

        "shopId": 1052,
        "items": [{
                "goodsId": 340006,
                "goodsItem": {
                    "id": 340006,
                    "count": 1
                },
                "buyLimit": 1,
                "beginTime": 1575129600,
                "endTime": 2051193600,
                "minLevel": 1,
                "maxLevel": 99,
                "costItemList": [{
                        "id": 203,
                        "count": 1680
                    }
                ]
            }, {
                "goodsId": 340007,
                "goodsItem": {
                    "id": 340007,
                    "count": 1
                },
                "buyLimit": 1,
                "beginTime": 1575129600,
                "endTime": 2051193600,
                "minLevel": 1,
                "maxLevel": 99,
                "costItemList": [{
                        "id": 203,
                        "count": 1680
                    }
                ]
            }, {
                "goodsId": 340008,
                "goodsItem": {
                    "id": 340008,
                    "count": 1
                },
                "buyLimit": 1,
                "beginTime": 1575129600,
                "endTime": 2051193600,
                "minLevel": 1,
                "maxLevel": 99,
                "costItemList": [{
                        "id": 203,
                        "count": 1680
                    }
                ]
            }, {
                "goodsId": 340009,
                "goodsItem": {
                    "id": 340009,
                    "count": 1
                },
                "buyLimit": 1,
                "beginTime": 1575129600,
                "endTime": 2051193600,
                "minLevel": 1,
                "maxLevel": 99,
                "costItemList": [{
                        "id": 203,
                        "count": 1680
                    }
                ]
            }

        ]
    }, 
    {//1053小畑
    },  
    {//1054秋月
    },  
    {//1055凉子
    },  
    {//1056葵
    },  
    {//1057雷之印商店
    },  
    {//1058「志村屋」店主
    },     
    {//1059黑田
    },  
    {//1060木南杏奈
    },  
    {//1061智树
    },  
    {//1062卡琵莉亚
    },  
    {//1063稻妻铁匠铺
    },     
    {//1064楠塔克钓鱼?
    },  
    {//1065嘉玮
    },  
    {//1066鲸井椛
    },     
    {//1067清子
    },  
    {//1068荣光之风2
    },  
    {//1069若紫
    },         
    {//1070山城健太
    },  
    {//15001
    },     
    {//16001
    },  
    {//16002
    },  
    {//20001
    },         
    {//20002
    },  
    {//20003
    },     
    {//20004
    },  
    {//20005
    },  
    {//27001
    },         
    {//28001
    }

]

**Comment by mIwaYuhang** [comment]
> ![图片](https://user-images.githubusercontent.com/109255084/179448586-abb5f2b2-f4f1-48e4-9f08-14d1e9eaa529.png)
> 
> **我修改了 \grasscutter\data\ShopGoodsExcelConfigData.json 内容 “itemId”： 并重启服务器**，但它并没有生效，还要修改其他什么文件来实现这个想法？ 我只想替换，不是增加，如果有相关快速修改的工具最好了。希望能得到帮助，谢谢 ![图片](https://user-images.githubusercontent.com/109255084/179448660-ef5f2ae3-b4a6-47f3-bf05-75fcd4147fdf.png)

参照ID与设置，正确的设置

**Comment by millet6** [comment]
> > ![图片](https://user-images.githubusercontent.com/109255084/179448586-abb5f2b2-f4f1-48e4-9f08-14d1e9eaa529.png)
> > **我修改了 \grasscutter\data\ShopGoodsExcelConfigData.json 内容 “itemId”： 并重启服务器**，但它并没有生效，还要修改其他什么文件来实现这个想法？ 我只想替换，不是增加，如果有相关快速修改的工具最好了。希望能得到帮助，谢谢 ![图片](https://user-images.githubusercontent.com/109255084/179448660-ef5f2ae3-b4a6-47f3-bf05-75fcd4147fdf.png)
> 
> 参照ID与设置，正确的设置

请问 /Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json 和 \grasscutter\data\ShopGoodsExcelConfigData.json 要同时修改吗？两个ShopGoodsExcelConfigData.json要一致吗？

**Comment by mIwaYuhang** [comment]
> /Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json

仅修改 /Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json

**Comment by millet6** [comment]
> > /Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json
> 
> 仅修改 /Resources/ExcelBinOutput/ShopGoodsExcelConfigData.json

好的 谢谢你的帮助
