### ISSUE TITLE
[Bug] 行纪，如何实现正常领奖？How to receive the award normally?

### ISSUE THREAD

**Issue by millet6** [Melledy/Grasscutter#1531]
**Which branch did you use?**
 Grasscutter version: 1.2.2-dev  Development version

1.**Describe the bug** 行纪，奖励无法领取。如何修正它？Discipline, reward can't be received. How to fix it?
BUG见视频  BUGSo please watch this video

https://user-images.githubusercontent.com/109255084/179700107-7e0298c3-0125-4dba-9e82-628a28fbfccb.mp4

2.****Describe the bug** 如何修复蒙德纪念品商店购买功能？How to repair the purchase function of Monde souvenir store?（问题2，暂时解决）

**Comment by mIwaYuhang** [comment]
蒙德纪念品商店的开启需要完成前置任务35901，你需要输入指令/quest add 35901 与 /quest finish 35901

**Comment by millet6** [comment]
> 蒙德纪念品商店的开启需要完成前置任务35901，你需要输入指令/quest add 35901 与 /quest finish 35901

可以让玩家注册就完成这两个任务吗？或者使用某个物品来完成指令/quest add 35901 与 /quest finish 35901？

Can players register to complete these two tasks? Or use an item to complete the instructions /quest add 35901 and /quest finish 35901?

**Comment by mIwaYuhang** [comment]
> > 蒙德纪念品商店的开启需要完成前置任务35901，你需要输入指令/quest add 35901 与 /quest finish 35901
> 
> 可以让玩家注册就完成这两个任务吗？或者使用某个物品来完成指令/quest add 35901 与 /quest finish 35901？
> 
> Can players register to complete these two tasks? Or use an item to complete the instructions /quest add 35901 and /quest finish 35901?
没有实现，你可以在config.json中配置给予新注册玩家player.quest与player.quest.others权限组，这样只需要玩家手动添加这个任务，而不是由管理员来提供

**Comment by ghost** [comment]
Fixed in f98c7e107c3cd43549c3e7dce74b9385a621367b

**Comment by millet6** [comment]
### proto/BattlePassRewardTakeOption.proto
`syntax = "proto3";
import "BattlePassRewardTag.proto";
option java_package = "emu.grasscutter.net.proto";
message BattlePassRewardTakeOption {
	BattlePassRewardTag tag = 10;
	uint32 option_idx = 14;
}
`
代码已更新，但它不生效，（grasscutter-1.2.3-dev.jar 最新的 30分钟前）The code has been updated, but it does not take effect. (grasscutter-1.2.3-dev.jar, the latest 30 minutes ago)
