### ISSUE TITLE
[Bug] OpenStates not working since 1fe304c - cannot log into my account

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#1535]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**
This has been happening ever since 1fe304c:
![image](https://user-images.githubusercontent.com/104761702/179727366-acdee877-fd56-4f4a-9643-ba1f2ca0964d.png)
Any earlier version will work and current versions do not. I'm reporting this as a bug because another person in the discord server is reporting the same problem and I have not done anything like messing with the source code or database to cause this inexplicable issue.. The error does mention openstates, which is weird because 051198c deals with this while 1fe304c doesn't, however that is still the commit where this account first started suffering these problems. I did try 949916a and there was nothing wrong. If needed, I will provide my player data, however messing with said data (i.e. changing my position) results in the same issue.

**Which branch did you use?**
Grasscutter version: 1.2.2-dev
Git Hash: 1fe304c

**Screenshots**

**Additional context**

I doubt that this is anything to do with my position in the game world - the last place I logged out before updating was next to a domain in Mondstadt.

**Comment by 4Benj** [comment]
Please title your issue so it is easier to keep track of.

**Comment by xotakfr** [comment]
Same issue, tried with multiple existing accounts and it didn't worked. I could connect with a new account, and log out and back in.

**Comment by GioroGiori** [comment]
Okay, I think I found the problem

Creating again another account and character and comparing data in mongoDB, the new account in openStateManager have a map object, and inside there are a value 16:1, copy and pasting in a old account character fix the problem

This is a new player
![image](https://user-images.githubusercontent.com/75138090/179815731-ef8670e9-dd5a-4a14-8837-99f3d2d114ce.png)

And this is a old player (created in 2.7 server)
but after put it in player data, the server created this
![image](https://user-images.githubusercontent.com/75138090/179816297-5f798ee4-e1eb-4518-8085-3b0b02fa6621.png)

**Comment by AZthemute** [comment]
> Okay, I think I found the problem
> 
> Creating again another account and character and comparing data in mongoDB, the new account in openStateManager have a map object, and inside there are a value 16:1, copy and pasting in a old account character fix the problem
> 
> -snip-
> 
> And this is a old player (created in 2.7 server) but after put it in player data, the server created this -snip-

![image](https://user-images.githubusercontent.com/104761702/180173857-f3bf7eaa-b92c-4065-bdd3-f6d97f1843de.png)
Uh, mine is empty... I have another account that works but the map field is empty... that account worked btw

**Comment by GanyusLeftHorn** [comment]
@AZthemute Can you try if the problem still exists with the current commit in https://github.com/GanyusLeftHorn/Grasscutter/tree/openstate_refactor ?

**Comment by AZthemute** [comment]
> @AZthemute Can you try if the problem still exists with the current commit in https://github.com/GanyusLeftHorn/Grasscutter/tree/openstate_refactor ?

Yup, this fixes the problem. Although now there is no map field for my profile, I can actually log in to the game. Not sure if I should close this now or when a PR to fix this is merged...
