### ISSUE TITLE
[Bug] 新角色进入游戏之后没有接到主线任务

### ISSUE THREAD

**Issue by NagaResst** [Melledy/Grasscutter#1537]
Grasscutter version: 1.2.2-dev
Git Hash: 3d386035
客户端版本 ：CNRELWin2.8.0_R8078355_S8017153_D8078038
> sudo java -jar grasscutter-1.2.2-dev.jar
20:14:19 <INFO:Grasscutter> Starting Grasscutter...
20:14:19 <INFO:Grasscutter> Game version: 2.8.0
20:14:19 <INFO:Grasscutter> Grasscutter version: 1.2.2-dev-3d386035

拉取源码自己打包添加完资源文件，客户端替换过 global-metadata.dat。可以正常进入游戏。
新建角色之后过完选人动画之后就自己一个人孤零零的站在海边，没有海边对话的动画也没有接取到主线任务。
控制台显示  20:17:28 <WARN:WorldDataManager> City not exist 102

**Comment by AcosX** [comment]
正常现象

**Comment by NagaResst** [comment]
> 正常现象

不会就是没有主线任务的吧

**Comment by zhaodice** [comment]
> > 正常现象
> 
> 不会就是没有主线任务的吧

对啊任务需要用指令手动添加，还不是每个任务都能做

**Comment by 2y8e9h22** [comment]
fuck you

**Comment by nitrog0d** [comment]
mean for what

**Comment by Saint-Theana** [comment]
这不是bug而是没有实现而已，你要知道这个服务器完完全全是从0开始写的而不是官方的完整的服务器，只能说很多东西都还没完成。

**Comment by KiminaNatsuki** [comment]
正常現象。

**Comment by NagaResst** [comment]
all right

**Comment by Bannyfelt13** [comment]
man....

**Comment by Gmskjunior** [comment]
Exit

Em dom., 28 de ago. de 2022 01:37, 镜诗音 ***@***.***> escreveu:

**Comment by 4Benj** [comment]
> Exit Em dom., 28 de ago. de 2022 01:37, 镜诗音 ***@***.***> escreveu:
> […](#)

Dude… just repeating exit over and over won’t do shit, login to your GitHub account and unwatch this repository

**Comment by Gmskjunior** [comment]
Exit

Em dom., 28 de ago. de 2022 01:50, 4Benj_ ***@***.***>
escreveu:
