### ISSUE TITLE
[Feature Request] eamil

### ISSUE THREAD

**Issue by xpppz** [Melledy/Grasscutter#1538]
Why I changed the reward for sending emails inside the config where I can't continue to send a second different email if there are no kind people

**Comment by xpppz** [comment]
If you add an items paragraph below the items code, you will only recognize the second items

**Comment by xpppz** [comment]
If you can please send me the code ...

**Comment by millet6** [comment]
[config.zip](https://github.com/Grasscutters/Grasscutter/files/9158359/config.zip)
文件放入服务端 grasscutter

**Comment by xpppz** [comment]
我是想登录之后一次性发两封邮件奖励

**Comment by millet6** [comment]
写俩代码块 邮件奖励这里

**Comment by xpppz** [comment]
真的不会写 好哥哥 可以给我写个模板嘛

**Comment by mIwaYuhang** [comment]
config.json中控制的是注册玩家发放的邮件奖励，我不理解为什么你需要对一个新注册的玩家发送两次邮件，是想对玩家说明情况吗？

**Comment by xpppz** [comment]
是因为我自己出钱开了个服务器给他们玩 又不想给他们GM 我想的是在邮件里一次性把杂七杂八的东西给他们发完 给他们GM 又怕服务器被玩炸

**Comment by mIwaYuhang** [comment]
> 是因为我自己出钱开了个服务器给他们玩 又不想给他们GM 我想的是在邮件里一次性把杂七杂八的东西给他们发完 给他们GM 又怕服务器被玩炸

可以使用插件，编辑好邮件内容奖励后，再向玩家发送邮件

**Comment by mIwaYuhang** [comment]
> > 是因为我自己出钱开了个服务器给他们玩 又不想给他们GM 我想的是在邮件里一次性把杂七杂八的东西给他们发完 给他们GM 又怕服务器被玩炸
> 
> 可以使用插件，编辑好邮件内容奖励后，再向玩家发送邮件

但目前看来插件似乎很久未更新了，他不能定时发送与每日发送，只能手动发送邮件奖励

**Comment by xpppz** [comment]
请问 怎么手动发送

**Comment by mIwaYuhang** [comment]
> 请问 怎么手动发送
[MeaMailPlus-1.0-SNAPSHOT.zip](https://github.com/Grasscutters/Grasscutter/files/9164904/MeaMailPlus-1.0-SNAPSHOT.zip)
使用这个插件，将他置于根目录的plugins文件夹中并运行服务器，插件会在plugins中创建文件,你可以在\MeaMailPlus\template中设置邮件模板(每个模板都具有唯一的数字ID)

**Comment by mIwaYuhang** [comment]
> > 请问 怎么手动发送 [MeaMailPlus-1.0-SNAPSHOT.zip](https://github.com/Grasscutters/Grasscutter/files/9164904/MeaMailPlus-1.0-SNAPSHOT.zip) 使用这个插件，将他置于根目录的plugins文件夹中并运行服务器，插件会在plugins中创建文件，你可以在\MeaMailPlus\template中设置邮件模板（每个模板都具有唯一的数字ID）

发送邮件:
    /meamail send <模板Id> <uid>
    /meamail sendall <模板Id> <最小冒险等级>
    /meamail sendallonline <模板Id> <最小冒险等级>
其他:
    /meamail reload
    /meamail help

**Comment by xpppz** [comment]
谢谢

**Comment by xpppz** [comment]
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loading...
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Config Loaded!
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded template: BirthDayMail.json (TemplateId: 1004)
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded template: DailyRepetitionMail.json (TemplateId: 1003)
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded template: DailySignInMail.json (TemplateId: 1002)
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded template: InitialMail.json (TemplateId: 1)
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded 4 templates. :D
13:42:34 <INFO:MeaMailPlusCore> [MeaMailPlusCore] Loaded
![QQ截图20220722134402](https://user-images.githubusercontent.com/104549115/180371414-8900f4ca-2378-4649-82da-6eefe167080b.png)
!

**Comment by xpppz** [comment]
我把物品ID加进去 发送邮件后却是空白的 这是为什么

**Comment by mIwaYuhang** [comment]
> 我把物品ID加进去 发送邮件后却是空白的 这是为什么

为什么不发送你的模板图片呢？你这样的截图根本看不出任何的问题

**Comment by mIwaYuhang** [comment]
模板检查，中文版本：
```
{
  "templateId": 1001,              // 你的邮件模板ID，不能重复。
  "title": "Mail title",           // 邮件标题
  "sender": "KiritaniIwako",       // 邮件发送人，你可以设置为 "Server"
  "expireTime": 0,                 // 过期时间，稍后会详细介绍
  "remainTime": 2592000,           // 剩余时间，如果你设置了剩余时间，则过期时间不会生效
  "importance": 0,                 // 邮件重要等级，0为默认，1为收藏
  "body": {                        // 邮件内容，稍后会详细介绍
    "content": "Mail content",
    "items": [
      {
        "id": 223,                 // 物品id
        "count": 1,                // 数量
        "level": 1                 // 等级(0-90?)
      }
    ]
  }
}
```

**Comment by mIwaYuhang** [comment]
> 模板检查，中文版本：
> 
> ```
> {
>   "templateId": 1001,              // 你的邮件模板ID，不能重复。
>   "title": "Mail title",           // 邮件标题
>   "sender": "KiritaniIwako",       // 邮件发送人，你可以设置为 "Server"
>   "expireTime": 0,                 // 过期时间，稍后会详细介绍
>   "remainTime": 2592000,           // 剩余时间，如果你设置了剩余时间，则过期时间不会生效
>   "importance": 0,                 // 邮件重要等级，0为默认，1为收藏
>   "body": {                        // 邮件内容，稍后会详细介绍
>     "content": "Mail content",
>     "items": [
>       {
>         "id": 223,                 // 物品id
>         "count": 1,                // 数量
>         "level": 1                 // 等级(0-90?)
>       }
>     ]
>   }
> }
> ```

并且，邮件内的多物品放置需要,来隔开

**Comment by xpppz** [comment]
![image](https://user-images.githubusercontent.com/104549115/180375877-2071d7a5-c5d5-4d4a-9ca7-26c19d9728bd.png)

**Comment by mIwaYuhang** [comment]
> ![image](https://user-images.githubusercontent.com/104549115/180375877-2071d7a5-c5d5-4d4a-9ca7-26c19d9728bd.png)

既然是物品发放问题，为什么不截取物品

**Comment by xpppz** [comment]
![image](https://user-images.githubusercontent.com/104549115/180376214-b4b8aeb5-7586-4aa9-9fe5-e33925451cf4.png)

**Comment by millet6** [comment]
https://github.com/Coooookies/Grasscutter-MeaMailPlus/blob/main/README_CN.md 有必要看官方文档

**Comment by mIwaYuhang** [comment]
这种报价真是

**Comment by xpppz** [comment]
是数量问题嘛

**Comment by mIwaYuhang** [comment]
> 是数量问题嘛

重新载入游戏模板，控制台键入/meamail reload

**Comment by xpppz** [comment]
试过了还是没作用

**Comment by mIwaYuhang** [comment]
你可以发送你的模板文件解压包

**Comment by xpppz** [comment]
[Uploading MeaMailPlus.zip…]()

**Comment by xpppz** [comment]
正在上传

**Comment by xpppz** [comment]
[MeaMailPlus.zip](https://github.com/Grasscutters/Grasscutter/files/9165353/MeaMailPlus.zip)

**Comment by mIwaYuhang** [comment]
> [MeaMailPlus.zip](https://github.com/Grasscutters/Grasscutter/files/9165353/MeaMailPlus.zip)

模板没有正确的设置

**Comment by mIwaYuhang** [comment]
[jianli.zip](https://github.com/Grasscutters/Grasscutter/files/9165435/jianli.zip)
![imges_204](https://user-images.githubusercontent.com/105578203/180382081-a9d92073-0aaa-4094-8ab0-65962ce7ccd9.png)
![imges_202](https://user-images.githubusercontent.com/105578203/180382125-f353cbed-a0ae-4a4d-9d6d-edce59dfa6ed.png)
![imges_203](https://user-images.githubusercontent.com/105578203/180382139-79b8cf13-b894-4202-9b3e-acd5b17d1f6e.png)

**Comment by xpppz** [comment]
我发你物品ID可以帮我设置一下嘛

**Comment by mIwaYuhang** [comment]
> 我发你物品ID可以帮我设置一下嘛

我发送了正确的文件配置，你可以复制进行更改

**Comment by xpppz** [comment]
好的

**Comment by xpppz** [comment]
![QQ截图20220722151726](https://user-images.githubusercontent.com/104549115/180385181-04daa394-875c-4a04-9493-6896dc19a0b0.png)
![QQ截图20220722151648](https://user-images.githubusercontent.com/104549115/180385201-10f2e013-af9b-4858-a3d5-e64c27027ea6.png)
还是同样的结果

**Comment by mIwaYuhang** [comment]
> ![QQ截图20220722151726](https://user-images.githubusercontent.com/104549115/180385181-04daa394-875c-4a04-9493-6896dc19a0b0.png) ![QQ截图20220722151648](https://user-images.githubusercontent.com/104549115/180385201-10f2e013-af9b-4858-a3d5-e64c27027ea6.png)还是同样的结果

你还是仔细阅读手册吧

**Comment by mIwaYuhang** [comment]
中文手册你需要仔细阅读
https://github.com/Coooookies/Grasscutter-MeaMailPlus/blob/main/README_CN.md

**Comment by millet6** [comment]
![图片](https://user-images.githubusercontent.com/109255084/180387624-02d2321a-4215-41a0-a82c-e25696ad0534.png)
经测试 每日奖励是正常的
