### ISSUE TITLE
[Bug] Usage section of help messages is bugged

### ISSUE THREAD

**Issue by Miralyn** [Melledy/Grasscutter#1539]
**Did you look for other closed issues that have the same problem?**

Yep, nothing similar.

**Describe the bug**

Apparently, something causes the Usage section of the help messages to not show anything.

**Which branch did you use?**

Grasscutter version: 1.2.2-dev
Git Hash: 3d386035
**Screenshots**

![usage bug](https://user-images.githubusercontent.com/41351810/180160128-79c7a0c0-d5df-418c-88d4-d2e638dc9afd.jpg)
example in Russian

**Additional context**

I checked every single available localization file while refactoring the russan one - it appears to be the case with every single one.

**Comment by Miralyn** [comment]
Update: Usage is fine now after one of the recent commit. However, now there are issues with GM Handbook. All of the commands got the text "This value does not exist" inserted before the actual description. For example, account : This value does not exist. Please report this to the Discord: Modify user accounts

**Comment by Birdulon** [comment]
Ah yep, I know the issue. Handbook generation refactor is coming relatively soon.
