### ISSUE TITLE
[Feature Request] Mini seelie 迷你仙灵修复

### ISSUE THREAD

**Issue by keqingyyds** [Melledy/Grasscutter#1542]
This is what I saw in QQ group a long time ago. I won't use it, and I'm not sure whether the file is complete. It is said that it can be used, but I don't understand it. The following is the contents of the file.
这是我很久很久之前在QQ群看到的。我并不会使用它，而且我也不确定文件是否完整。据说是可以使用的，但我并不懂。下面是文件内容。
Dividing line  分割线
public PacketAbilityChangeNotify(EntityAvatar entity, boolean isFollower, int followerId) {
        super(PacketOpcodes.AbilityChangeNotify, true);

        var proto = AbilityChangeNotify.newBuilder().setEntityId(entity.getId());

        var abilityEmbryo
                = entity.getAbilityControlBlock();

        if (isFollower) {
            int abilityId;
            int nameHash;
            int overrideNameHash = 1178079449;

            switch (followerId) {
                case 220016 -> {
                    abilityId = 1;
                    nameHash = 2090211154;
                }
                case 220045 -> {
                    abilityId = 2;
                    nameHash = 1412125698;
                }
                case 220023 -> {
                    abilityId = 2;
                    nameHash = 617606725;
                }
                default -> {
                    abilityId = 3;
                    nameHash = 2090211156;
                }
            }

            abilityEmbryo.addAbilityEmbryoList(AbilityEmbryoOuterClass.AbilityEmbryo.newBuilder().setAbilityId(abilityId)
                                   .setAbilityNameHash(nameHash).setAbilityOverrideNameHash(overrideNameHash).build()).build();
        }

        proto.setAbilityControlBlock(abilityEmbryo);
        this.setData(proto);
    }
Dividing line 分割线
package emu.grasscutter.server.packet.recv;

import emu.grasscutter.game.player.Player;
import emu.grasscutter.net.packet.Opcodes;
import emu.grasscutter.net.packet.PacketHandler;
import emu.grasscutter.net.packet.PacketOpcodes;
import emu.grasscutter.net.proto.SetWidgetSlotReqOuterClass;
import emu.grasscutter.net.proto.WidgetSlotOpOuterClass;
import emu.grasscutter.server.game.GameSession;
import emu.grasscutter.server.packet.send.PacketAbilityChangeNotify;
import emu.grasscutter.server.packet.send.PacketSetWidgetSlotRsp;
import emu.grasscutter.server.packet.send.PacketWidgetSlotChangeNotify;

import java.util.ArrayList;
import java.util.List;

@Opcodes(PacketOpcodes.SetWidgetSlotReq)
public class HandlerSetWidgetSlotReq extends PacketHandler {

    @Override
    public void handle(GameSession session, byte[] header, byte[] payload) throws Exception {
        SetWidgetSlotReqOuterClass.SetWidgetSlotReq req = SetWidgetSlotReqOuterClass.SetWidgetSlotReq.parseFrom(payload);

        List<Integer> nah = new ArrayList<>();
        nah.add(220023);
        nah.add(220045);
        nah.add(220013);
        nah.add(220014);
        nah.add(220015);
        nah.add(220016);
        nah.add(220037);
        nah.add(220038);

        if (nah.contains(req.getMaterialId())) {
            session.send(new PacketAbilityChangeNotify(session.getPlayer().getTeamManager().getCurrentAvatarEntity(), false , req.getMaterialId()));
            session.send(new PacketWidgetSlotChangeNotify(WidgetSlotOpOuterClass.WidgetSlotOp.WIDGET_SLOT_OP_DETACH, true));
            // SetWidgetSlotRsp
            session.send(new PacketWidgetSlotChangeNotify(req.getMaterialId(), true));
            session.send(new PacketAbilityChangeNotify(session.getPlayer().getTeamManager().getCurrentAvatarEntity(), true , req.getMaterialId()));
        } else {
            Player player = session.getPlayer();
            player.setWidgetId(req.getMaterialId());

            // WidgetSlotChangeNotify op & slot key
            session.send
                    (new PacketWidgetSlotChangeNotify(WidgetSlotOpOuterClass.WidgetSlotOp.WIDGET_SLOT_OP_DETACH));

            //only attaching the widget can set it
            if (req.getOp() == WidgetSlotOpOuterClass.WidgetSlotOp.WIDGET_SLOT_OP_ATTACH) {
                // WidgetSlotChangeNotify slot
                session.send(new PacketWidgetSlotChangeNotify(req.getMaterialId()));
            }

        }
        session.send(new PacketSetWidgetSlotRsp(req.getMaterialId()));
    }

}

**Comment by 2y8e9h22** [comment]
不能用

**Comment by wajunye** [comment]
请正确描述你的问题

**Comment by KiminaNatsuki** [comment]
Please follow the issue format first, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
