### ISSUE TITLE
[Bug] How to properly configure the server list  如何正确配置服务器列表

### ISSUE THREAD

**Issue by kuyoos** [Melledy/Grasscutter#1544]
进入其他服的时候显示白屏

White screen when entering other servers

**Comment by KiminaNatsuki** [comment]
至少講清楚一點吧...

**Comment by kuyoos** [comment]
进入服务器列表其他服的时候会出现白屏

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月22日(周五) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Grasscutters/Grasscutter] [Bug] How to properly configure the server list  如何正确配置服务器列表 (Issue #1544)




 
至少講清楚一點吧...

**Comment by Aemeath5** [comment]
> 至少講清楚一點吧...

他说的是多服务器列表选服务器的时进去另一台服务器白屏
