### ISSUE TITLE
[Bug] Can't claim Battle Pass rewards

### ISSUE THREAD

**Issue by xNissX233** [Melledy/Grasscutter#1546]
**Describe the bug**
When trying to claim all the rewards, or one by one by clicking in the reward icon, nothing happens.

**Which branch did you use?**
  Grasscutter version: 1.2.3-dev
  Git Hash: 42df970b

**Additional context**
In previous versions this feature was working, but not in the current dev version.

**Comment by mengguyi** [comment]
you can see https://github.com/Grasscutters/Grasscutter/issues/1531
It may help you

**Comment by ghost** [comment]
Fixed in f98c7e107c3cd43549c3e7dce74b9385a621367b
