### ISSUE TITLE
[Bug] Why dose I connected the Grasscutter, The client say "Time out"

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [Melledy/Grasscutter#1554]
**My Server and Database is all started!**
![PIC](http://180.76.181.108/zb_users/upload/2022/07/202207231658570102257683.png)
**But,When I use client connect the server,It pops up a dialog box "man machine verification",Wait a few second, It say"Connect time out ",This error code  is 204_2,Not show that before when I reBuild 2.8. I can't understand it.**
![PIC](http://180.76.181.108/zb_users/upload/2022/07/202207231658570102320455.jpg)
![PIC](http://180.76.181.108/zb_users/upload/2022/07/202207231658570102806340.jpg)

Why is that?

**Comment by mengguyi** [comment]
看样子你好像没有正确重定向ys的流量，否则不会出现图灵验证

**Comment by ErrorCodesForLzx** [comment]
> 看样子你好像没有正确重定向ys的流量，否则不会出现图灵验证

但是我看见代理服务器有  localhost:443 的 200 ok请求，同时也有 到MHY的请求，不知道哪里有问题，我是按照README中做的啊，而且2.7的时候我已经成功的进入了一次

**Comment by ErrorCodesForLzx** [comment]
> 看样子你好像没有正确重定向ys的流量，否则不会出现图灵验证

求求 大佬看看 
这个是运行的 mitmdump -s proxy.py -k 的日志：
http://180.76.181.108/zb_users/upload/2022/07/20220723180744165857086457702.log

**Comment by mengguyi** [comment]
那个，以后给动漫游戏设置代理时可以开一个管理员权限的cmd，然后输入
<code>set http_proxy=http://host:port</code>
<code>set https_proxy=http://host:port</code>
这样日志里就只会有动漫游戏的信息了，这个日志太乱了

**Comment by mengguyi** [comment]
> **My Server and Database is all started!** ![PIC](https://camo.githubusercontent.com/12a7315e85f0b4e13f8de8fda5620cc6bf83f48958b1628eaddd774f83e30d3b/687474703a2f2f3138302e37362e3138312e3130382f7a625f75736572732f75706c6f61642f323032322f30372f3230323230373233313635383537303130323235373638332e706e67) **But,When I use client connect the server,It pops up a dialog box "man machine verification",Wait a few second, It say"Connect time out ",This error code is 204_2,Not show that before when I reBuild 2.8. I can't understand it.** ![PIC](https://camo.githubusercontent.com/ec0d53809206f737f81127f66d64997c490562f009344d02789a0927a92c95bd/687474703a2f2f3138302e37362e3138312e3130382f7a625f75736572732f75706c6f61642f323032322f30372f3230323230373233313635383537303130323332303435352e6a7067) ![PIC](https://camo.githubusercontent.com/422196ed58834a40ada2d268e407b58d61dbe707835d49d1e816e73bc1258569/687474703a2f2f3138302e37362e3138312e3130382f7a625f75736572732f75706c6f61642f323032322f30372f3230323230373233313635383537303130323830363334302e6a7067)
> 
> Why is that?

等等，你这是Android版的游戏

**Comment by mengguyi** [comment]
你需要给2.8版的客户端打补丁才能正常使用

**Comment by ErrorCodesForLzx** [comment]
> 你需要给2.8版的客户端打补丁才能正常使用

我使用了 apk-mitm 修改过的，而且2.7我还是使用的是Android设备

**Comment by mengguyi** [comment]
我不玩Android版的确定的动漫游戏，你可以试试pc版的能不能正常连接割草机。来确定是否是代理的问题

**Comment by shelby-xyz** [comment]
iOS目前是不是无法登录？我的2.8服务端网络按原来2.7的服务器配置，全部提示4212

**Comment by Lovelumine** [comment]
> 你需要给2.8版的客户端打补丁才能正常使用

现在还需要吗？

**Comment by ouhexi** [comment]
客户端版本是否与服务器版本一致？

**Comment by memetrollsXD** [comment]
Closed due to inactivity
