### ISSUE TITLE
[Bug] 为什么我的游戏页面没有纪行这个按钮？Why doesn't my game page have a battle pass award？

### ISSUE THREAD

**Issue by hpu-hyh** [Melledy/Grasscutter#1559]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by SmurfSilva** [comment]
升级了吗，20级解锁

**Comment by millet6** [comment]
冒险等级20才有

**Comment by Birdulon** [comment]
Battle Pass now unlocks at the correct Adventurer Rank rather than being always unlocked :)
