### ISSUE TITLE
[Bug] Game keeps reporting 4214 after upgrading game to 2.8

### ISSUE THREAD

**Issue by CarterLi** [Melledy/Grasscutter#1567]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

I used to play the game with grasscutter successfully. However after I upgraded the game to 2.8 yesterday the game started to complain Networking issues 4214.

I don't know how to find the root issue. I did try to join the discord server but I failed for some reason.

![image](https://user-images.githubusercontent.com/6134068/180777160-17a5ab0a-eeb7-4c00-bbe6-32307cc0f3d9.png)

**Which branch did you use?**

Grasscutter version: 1.2.3-dev-d6e6aa4c

**Screenshots**

Here is some screenshots.

![image](https://user-images.githubusercontent.com/6134068/180776050-e457321e-1f63-4ee8-b550-db8b86696cb4.png)

![image](https://user-images.githubusercontent.com/6134068/180776184-5d5cc461-f9c6-47e0-91c2-5cbe71c05540.png)

![image](https://user-images.githubusercontent.com/6134068/180776250-6f8cba8f-b5d0-4f97-8f87-0de5fd6e5b7d.png)

**Additional context**

**Comment by TotallyNotOndre** [comment]
Have you tried to patch metadata?
After 2.8 update game start to block redirected connection to private servers.

**Comment by CarterLi** [comment]
Not yet.

How can I do that? @TotalyNotOndre

**Comment by TotallyNotOndre** [comment]
[Here](https://github.com/Grasscutters/Grasscutter/files/9181234/metadata-patch.zip) is patched metadata file.
You need to unzip it into `Genshin Impact Game\GenshinImpact_Data\Managed\Metadata` and remember to do a backup.
I also recomend you to join [Discord](https://discord.gg/T5vZU6UyeG) server to get further help

**Comment by CarterLi** [comment]
My game freezed after I patched the file.

Is that metadata file region specified? I'm using a Chinese client

@TotalyNotOndre 

Discord said that I could not accept the invitation.

**Comment by KiminaNatsuki** [comment]
Try to use another VPN or something, since other mainlander can join the discord without any problems?

**Comment by KiminaNatsuki** [comment]
Also yes, the metadata is region specified.

**Comment by CarterLi** [comment]
Found it here: https://discord.com/channels/970366495253209108/970372249163026432
