### ISSUE TITLE
[Feature Request] config.json 文档/config.json document

### ISSUE THREAD

**Issue by Silverteal** [Melledy/Grasscutter#1570]
**Is your feature request related to a problem? Please describe.**
在现有版本中，config.json由主程序生成，但是没有任何修改config.json的清晰指引，只能自己猜

**Describe the solution you'd like**
在wiki中添加config.json文档

**Comment by SleepyAsh0191** [comment]
Translate:

**Comment by SleepyAsh0191** [comment]
Translate: 
# Title: Add config.json usage in wiki
## description:
In the current version, config,json is generated by main program, but it don't have the edit instruction for config.json, only can guess by myself.

Add config.json doc at wiki.

**Comment by curryyinxh** [comment]
[config配置文件设置指南.txt](https://github.com/Grasscutters/Grasscutter/files/9274133/config.txt)
