### ISSUE TITLE
[Bug] An error occurred using "help"

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1585]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by ERthereal** [comment]
![捕获](https://user-images.githubusercontent.com/58130955/181203090-5b0313b6-ad87-4d6a-b220-bfaf7d251cfc.PNG)

**Comment by Birdulon** [comment]
https://github.com/Penelopeep/SwitchElementTraveller/pull/3 plugin problem
