### ISSUE TITLE
what's quest key

### ISSUE THREAD

**Issue by mengdalida** [Melledy/Grasscutter#1588]
20:02:44 <ERROR:ResourceLoader> Unable to load quest keys.
java.io.FileNotFoundException: .\resources\QuestEncryptionKeys.json (系统找不到指定的文件。)

**Comment by SleepyAsh0191** [comment]
Use this [gist](https://gist.github.com/Hartie95/8b035f144fa17d5c43d17665ee460ba7#file-questencryptionkeys-json) and put it in resources folder,

likes your stacktrace `java.io.FileNotFoundException: .\resources\QuestEncryptionKeys.json`

**Comment by qy527145** [comment]
这是一个bug，代码中是解析./data/路径下的json文件，日志提示的却是./resource/路径下缺失这个json，这两者没有统一。可以把QuestEncryptionKeys.json放在./data下来解决这个问题。
