### ISSUE TITLE
[Bug] Failed to create gacha mappings

### ISSUE THREAD

**Issue by aya-momo** [Melledy/Grasscutter#1589]
**Did you look for other closed issues that have the same problem?**
Yes. But it didn't solve my problem

**Describe the bug**

All resources have been downloaded and mv Resource -> resource

console log:
21:34:54 <WARN:DataLoader> Failed to create gacha mappings. 
java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because the return value of "java.util.Map.get(Object)" is null

**Which branch did you use?**

  Grasscutter version: 1.2.3-dev
  Git Hash: d6e6aa4

**Screenshots**

**Additional context**

**Comment by KingRainbow44** [comment]
a very simple fix for someone to implement: add a null check when generating gacha mappings. I've only seen this issue on Linux-based operating systems so far (from my experience).

**Comment by mengdalida** [comment]
> a very simple fix for someone to implement: add a null check when generating gacha mappings. I've only seen this issue on Linux-based operating systems so far (from my experience).

how to solve

**Comment by JoshDoesStuff** [comment]
> a very simple fix for someone to implement: add a null check when generating gacha mappings. I've only seen this issue on Linux-based operating systems so far (from my experience).

getting it on windows 10, its not just linux based

**Comment by Birdulon** [comment]
Should be fixed by #1605
