### ISSUE TITLE
[Bug] 1.2.3dev.jar cant working on ios，always show me 4214error ，but use 1.2.2dev.jar is all good

### ISSUE THREAD

**Issue by jinjoshua1** [Melledy/Grasscutter#1599]
Grasscutter：1.2.3-dev.jar
4214error

**Comment by KingRainbow44** [comment]
With the release of update `2.8`, the game is required to be **patched**. This simply isn't possible on iOS due to the code signing restrictions on the operating system. To continue using Grasscutter, play on another device which supports client patching.

**Comment by 4Benj** [comment]
> This simply isn't possible on iOS due to the code signing restrictions on the operating system.

It certainly is possible but is going to be extremely annoying to do, especially if the user isn’t jailbroken.

**Comment by 4Benj** [comment]
For a non-jailbroken user, they’d need to download a prepatched ipa file which they’d have to sign themselves (and resign every 7 days). For a jailbroken user, they may be able to just patch the metadata file already installed

**Comment by jinjoshua1** [comment]
我已经修补了，并且可以使用1.2.2jar玩2.8，但是当我换到1.2.3jar就并不行

**Comment by jinjoshua1** [comment]
这个4214错误仅当我换到1.2.3才会出现，1.2.2我可以正常玩

**Comment by xsser** [comment]
> 

+1
我直接安装就是1.2.3 就这样报错
I  run the jar(1.2.3 version) and also got the 4212 warning

**Comment by worship-dog** [comment]
> 我已经修补了，并且可以使用1.2.2jar玩2.8，但是当我换到1.2.3jar就并不行

您好，请问您是怎样修补的ios客户端呢，能指点一下吗
