### ISSUE TITLE
Missing the ISSUE TEMPLATE

### ISSUE THREAD

**Issue by FahimFBA** [Melledy/Grasscutter#160]
The project is currently missing the Issue Templates which might be a good addition to this project so that people can interact with this project with some categorized sections. If you want to add that, then I would like to add a PR with some relevant templates. Please let me know what do you think about that.

**Comment by KingRainbow44** [comment]
if you would like to, yes you can PR a few templates.

**Comment by FahimFBA** [comment]
Ops! I just wanted to add the PR, then I saw that this issue has been resolved already! I am extremely sorry for the late though. As the issue has been resolved, I am closing the issue.
