### ISSUE TITLE
Some accounts open the door for no reason and the server displays the following error on a white screen

### ISSUE THREAD

**Issue by Aemeath5** [Melledy/Grasscutter#1601]
![QQ截图20220730004515](https://user-images.githubusercontent.com/84051485/181806680-4937dc8e-6692-4dcd-a8fa-29ffba3f9869.png)

**Comment by Aemeath5** [comment]
white screen when opening the door

**Comment by KiminaNatsuki** [comment]
didn't even say what happened after
