### ISSUE TITLE
[Bug] Heizhou constellations aren't working

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1603]
**Did you look for other closed issues that have the same problem?**

I did, and never found anything.

**Describe the bug**

Heizhou C3 and C5 aren't working. It supposed to add +3 more levels on talents (E & Q) but it didn't

**Which branch did you use?**

Grasscutter version: 1.2.3-dev
Git Hash: N/A

**Screenshots**

![image](https://user-images.githubusercontent.com/86816436/181917924-ca559358-26d8-4fe8-973b-1ca3ec5c928c.png)
![image](https://user-images.githubusercontent.com/86816436/181917938-984c184e-4c31-496d-8413-2ae39c01e57e.png)

**Additional context**

**Comment by millet6** [comment]
通过指令得到的角色是不加等级的
Pass instruction    /give all x100 lv90 c6 r5  Constellations don't work

**Comment by Birdulon** [comment]
This is a resources problem, Dim's BinOutput folder hasn't been updated to include Heizo's data (or anything else from 2.8 for that matter).
