### ISSUE TITLE
[Bug] Unable to create player due to quest resources

### ISSUE THREAD

**Issue by damtienkhoi** [Melledy/Grasscutter#1604]
Did you look for other closed issues that have the same problem?
Yes, and I couldn't find one with the same problem

Describe the bug
After finishing the "Preparing to load resources" process, I got this problem in console

Which branch did you use?
https://github.com/Grasscutters/Grasscutter/actions/runs/2762173760

Screenshots
![image](https://user-images.githubusercontent.com/96215744/181920588-31ec5450-c9d5-4106-8dfe-254a3bc3b636.png)

**Comment by KingRainbow44** [comment]
actually duplicate of #1601

**Comment by KiminaNatsuki** [comment]
why did you close this one when other didn't follow the format
