### ISSUE TITLE
[Bug] display <ERROR:ResourceLoader> Unable to load quest keys - ./resources/QuestEncryptionKeys.json not found.

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1607]
use Grasscutter-1.2.3-dev.jar
Enter the game, after logging in on to the login screen, 4214 is displayed

**Comment by xsser** [comment]
+1

Unable to load quest keys - ./resources/QuestEncryptionKeys.json not found.

Game version: 2.8.0
Grasscutter version: 1.2.3-dev-ca42a23
