### ISSUE TITLE
[Bug] 这个文件自从上次更改后找不到了

### ISSUE THREAD

**Issue by Needdaima** [Melledy/Grasscutter#1612]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by Needdaima** [comment]
![L0$UHGK {$F7R36FD7@L Y](https://user-images.githubusercontent.com/67779374/182325976-ca7c6b7f-3873-4ba9-bdf5-1a7b1ce6ea5a.png)

**Comment by Needdaima** [comment]
缺少这个文件 ，可以提供吗

**Comment by 2y8e9h22** [comment]
不可以

**Comment by zhaodice** [comment]
https://github.com/TotalyNotOndre/Grasscutter/blob/development/src/main/resources/defaults/data/QuestEncryptionKeys.json
