### ISSUE TITLE
[Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同

### ISSUE THREAD

**Issue by jinjoshua1** [Melledy/Grasscutter#1613]
是这样的，我前几天提交了一个提问，关于1.2.3-dev.jar ios运行报错4214的问题，你们好像理解错了我的意思，问题并不是出在meta上面，同样都是2.8服务端，1.2.2可以使ios的2.8的客户端正常进入游玩，当我换到1.2.3的时候会出现4214但是我已经替换了meta

**Comment by 2y8e9h22** [comment]
我们都没问题，那就是你自己的问题

**Comment by jinjoshua1** [comment]
> 我们没有问题，那就是你自己的问题

你可以去试试ios

**Comment by zhaodice** [comment]
有没有一种可能，这两个版本用了不同的公钥

**Comment by jinjoshua1** [comment]
> 有没有一种可能，这两个版本用了不同的公钥

所以说最新版本的ios meta可以在哪搞到

**Comment by JasonWangex** [comment]
你把 RegionHandler 里面这段注释掉就行，我跟你估计用的同一个 ipa

```              
 if (request.query("dispatchSeed") == null) {
                    // More love for UA Patch players
                    var rsp = new QueryCurRegionRspJson();

                    rsp.content = event.getRegionInfo();
                    rsp.sign = "TW9yZSBsb3ZlIGZvciBVQSBQYXRjaCBwbGF5ZXJz";

                    response.send(rsp);
                    return;
                }
```

**Comment by jinjoshua1** [comment]
> 你把 RegionHandler 里面这段注释掉就行，我跟你估计用的同一个 ipa
> 
> ```
>  if (request.query("dispatchSeed") == null) {
>                     // More love for UA Patch players
>                     var rsp = new QueryCurRegionRspJson();
> 
>                     rsp.content = event.getRegionInfo();
>                     rsp.sign = "TW9yZSBsb3ZlIGZvciBVQSBQYXRjaCBwbGF5ZXJz";
> 
>                     response.send(rsp);
>                     return;
>                 }
> ```

能具体说一下吗，感谢

**Comment by jinjoshua1** [comment]
@JasonWangex

**Comment by JasonWangex** [comment]
@jinjoshua1 
<img width="910" alt="image" src="https://user-images.githubusercontent.com/19605399/182871469-21fdf68c-531d-4d79-93d6-6ba28c660c20.png">

**Comment by jinjoshua1** [comment]
谢谢

**Comment by MiQCPT** [comment]
I need help please someone help me

**Comment by MiQCPT** [comment]
if you understand english, you need to clear cache when running different jar version, hope it helps you

**Comment by MiQCPT** [comment]
if you understand english, you need to clear the game cache when running different jar version, hope it helps

**Comment by Yazawazi** [comment]
Is this problem solved after removing the null check?
In my humble opinion, if your metadata patch is just the RSA key replacement, then you don't need to remove the null check for `dispatchSeed` as that is for `MoleMole.Miscs.GetGlobalDispatchUrl` in the UA patch.
You can print the `query` parameters, or add a breakpoint or add a log at the null check to see if this logic is entered.
If it works after removing the null check, your metadata patch may have modified more than the RSA key, or your IPA file may have been patched with more content.
Or maybe the iOS client doesn't have a `dispatchSeed` parameter, I honestly don't know about that. If so, I will submit a PR for a separate check for the iOS version.

---

这个问题在移除掉空值检查后解决了吗？
依我愚见，如果你的 Metadata Patch 单纯只是 RSA 的替换的话，那么就不需要移除对 `dispatchSeed` 的空值检查，它是为了 UA Patch 中修改过的 `MoleMole.Miscs.GetGlobalDispatchUrl` 而存在的（去除 `dispatchSeed`）。
你可以尝试打印 `query` 参数，或者增加断点 / 日志输出，来检查是否进入了空值检查逻辑。
如果移除掉之后问题解决了，我想你的 Metadata Patch 可能修改了比 RSA Key 更多的内容，或者你的 IPA 文件 Patch 了比 Metadata 还要多的内容。
或者 iOS 客户端压根没有 `dispatchSeed` 参数（我个人认为是不可能的），并且说实话我对 iOS 和 iOS 的 Patch 一无所知。
如果 iOS 的 RSA Patch 会导致 `dispatchSeed` 消失，那么如果可能我会提交一个在 Dispatch 单独对 iOS 检查的 PR。

**Comment by worship-dog** [comment]
> > 我们没有问题，那就是你自己的问题
> 
> 你可以去试试ios

你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢

**Comment by ZxyGch** [comment]
> 



> > > 我们没有问题，那就是你自己的问题
> > 
> > 
> > 你可以去试试ios
> 
> 你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢

我已经成功了

**Comment by worship-dog** [comment]
请问你是怎么做到的呢，简单描述一下吗





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月13日 14:36
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





      
我们没有问题，那就是你自己的问题
  
你可以去试试ios
  
你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢
  
我已经成功了

**Comment by ZxyGch** [comment]
> 请问你是怎么做到的呢，简单描述一下吗
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zxp1314gch ***@***.***&gt; 发送时间: 2022年8月13日 14:36 收件人: Grasscutters/Grasscutter ***@***.***&gt; 抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613) 我们没有问题，那就是你自己的问题 你可以去试试ios 你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢 我已经成功了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

按照上面的方法就可以啊

**Comment by worship-dog** [comment]
emmm我试过了这个方法也不行，可能是因为我没有为客户端打补丁，请问你是怎样给ios客户端打补丁的呢





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月13日 21:02
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





  
请问你是怎么做到的呢，简单描述一下吗
 …
 ------------------ 原始邮件 ------------------ 发件人: zxp1314gch @.&gt; 发送时间: 2022年8月13日 14:36 收件人: Grasscutters/Grasscutter @.&gt; 抄送: 李彬 @.&gt;, Comment @.&gt; 主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613) 我们没有问题，那就是你自己的问题 你可以去试试ios 你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢 我已经成功了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
按照上面的方法就可以啊

**Comment by worship-dog** [comment]
***@***.***





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月13日 21:02
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





  
请问你是怎么做到的呢，简单描述一下吗
 …
 ------------------ 原始邮件 ------------------ 发件人: zxp1314gch @.&gt; 发送时间: 2022年8月13日 14:36 收件人: Grasscutters/Grasscutter @.&gt; 抄送: 李彬 @.&gt;, Comment @.&gt; 主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613) 我们没有问题，那就是你自己的问题 你可以去试试ios 你好，请问你的问题解决了吗,ios是不是没办法在1.2.3成功登录呢 我已经成功了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
按照上面的方法就可以啊

**Comment by worship-dog** [comment]
> 
能否请你留个邮箱或者其他联系方式呢

**Comment by zxp1314gch** [comment]
> > 
> 
> 能否请你留个邮箱或者其他联系方式呢
客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 
提取码：meow 
sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个
这个客户端就是打了补丁的

**Comment by ZxyGch** [comment]
> > 
> 
> 能否请你留个邮箱或者其他联系方式呢


客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow
提取码：meow
sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个
这个客户端就是打了补丁的

**Comment by worship-dog** [comment]
万分感谢！





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月13日 22:05
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





    
能否请你留个邮箱或者其他联系方式呢
  
客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow
 提取码：meow
 sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个
 这个客户端就是打了补丁的

**Comment by worship-dog** [comment]
> > > 
> > 
> > 
> > 能否请你留个邮箱或者其他联系方式呢
> 
> 客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 提取码：meow sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个 这个客户端就是打了补丁的

大佬，这两个ipa文件好像是ipados的，有没有ios的呀

**Comment by ZxyGch** [comment]
> > > 能否请你留个邮箱或者其他联系方式呢
> > 
> > 
> > 客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 提取码：meow sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个 这个客户端就是打了补丁的
> 
> 大佬，这两个ipa文件好像是ipados的，有没有ios的呀

我只有这个版本的

**Comment by ZxyGch** [comment]
[](url)> > > > 
> > > 
> > > 
> > > 能否请你留个邮箱或者其他联系方式呢
> > 
> > 
> > 客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 提取码：meow sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个 这个客户端就是打了补丁的
> 
> 大佬，这两个ipa文件好像是ipados的，有没有ios的呀

我找到解决办法了，使用sideloadly的时候选择高级设置里面的移除设备限制

**Comment by worship-dog** [comment]
大佬威武！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月14日(星期天) 晚上9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





 
&gt; &gt; &gt; &gt;
    
能否请你留个邮箱或者其他联系方式呢
  
客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 提取码：meow sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个 这个客户端就是打了补丁的
  
大佬，这两个ipa文件好像是ipados的，有没有ios的呀
  
我找到解决办法了，使用sideloadly的时候选择高级设置里面的移除设备限制

**Comment by yhw2003** [comment]
我和你遇到了同一个问题

**Comment by leliang1234** [comment]
> 是这样的，我前几天提交了一个提问，关于1.2.3-dev.jar ios运行报错4214的问题，你们好像理解错了我的意思，问题并不是出在meta上面，同样都是2.8服务端，1.2.2可以使ios的2.8的客户端正常进入游玩，当我换到1.2.3的时候会出现4214但是我已经替换了meta



我想问一下这个grasscutter-1.2.2-dev.jar在哪下载的啊？

**Comment by Liu445985235** [comment]
> > 是这样的，我前几天提交了一个提问，关于1.2.3-dev.jar ios运行报错4214的问题，你们好像理解错了我的意思，问题并不是出在meta上面，同样都是2.8服务端，1.2.2可以使ios的2.8的客户端正常进入游玩，当我换到1.2.3的时候会出现4214但是我已经替换了meta
> 
> 我想问一下这个grasscutter-1.2.2-dev.jar在哪下载的啊？
去tg下

**Comment by leliang1234** [comment]
> 

tg是啥？

**Comment by leliang1234** [comment]
> > > 是这样的，我前几天提交了一个提问，关于1.2.3-dev.jar ios运行报错4214的问题，你们好像理解错了我的意思，问题并不是出在meta上面，同样都是2.8服务端，1.2.2可以使ios的2.8的客户端正常进入游玩，当我换到1.2.3的时候会出现4214但是我已经替换了meta
> > 
> > 
> > 我想问一下这个grasscutter-1.2.2-dev.jar在哪下载的啊？
> > 去tg下

有下载连接吗

**Comment by worship-dog** [comment]
> 

我没有再尝试了，我现在连Pc都登录不上，补丁之后仍然4214，使用的最新代码。但我可以进入其他人建立的3.0私服

**Comment by worship-dog** [comment]
我没有用ios玩了，签名过期之后一直没有重签，我也不知道现在能不能用。





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月28日 10:34
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





 ﻿你是说你用了3.0的ios国际官方客户端登录了3.0的ios私服吗？是用了小火箭吗？在 2022年8月28日，上午8:02，李彬 ***@***.***&gt; 写道：﻿
 
 
 我没有再尝试了，我现在连Pc都登录不上，补丁之后仍然4214，使用的最新代码。但我可以进入其他人建立的3.0私服

**Comment by L4cache** [comment]
> Is this problem solved after removing the null check? In my humble opinion, if your metadata patch is just the RSA key replacement, then you don't need to remove the null check for `dispatchSeed` as that is for `MoleMole.Miscs.GetGlobalDispatchUrl` in the UA patch. You can print the `query` parameters, or add a breakpoint or add a log at the null check to see if this logic is entered. If it works after removing the null check, your metadata patch may have modified more than the RSA key, or your IPA file may have been patched with more content. Or maybe the iOS client doesn't have a `dispatchSeed` parameter, I honestly don't know about that. If so, I will submit a PR for a separate check for the iOS version.
> 
> 这个问题在移除掉空值检查后解决了吗？ 依我愚见，如果你的 Metadata Patch 单纯只是 RSA 的替换的话，那么就不需要移除对 `dispatchSeed` 的空值检查，它是为了 UA Patch 中修改过的 `MoleMole.Miscs.GetGlobalDispatchUrl` 而存在的（去除 `dispatchSeed`）。 你可以尝试打印 `query` 参数，或者增加断点 / 日志输出，来检查是否进入了空值检查逻辑。 如果移除掉之后问题解决了，我想你的 Metadata Patch 可能修改了比 RSA Key 更多的内容，或者你的 IPA 文件 Patch 了比 Metadata 还要多的内容。 或者 iOS 客户端压根没有 `dispatchSeed` 参数（我个人认为是不可能的），并且说实话我对 iOS 和 iOS 的 Patch 一无所知。 如果 iOS 的 RSA Patch 会导致 `dispatchSeed` 消失，那么如果可能我会提交一个在 Dispatch 单独对 iOS 检查的 PR。

~请问什么是UA patch？
对了，我玩的是PC版，看到测试版3.0.5无法使用metadata patch了~
已解决 https://anonfiles.com/H0VbR750yf/UserAssembly_zip

**Comment by worship-dog** [comment]
好的，谢谢大佬





------------------ 原始邮件 ------------------
发件人: zxp1314gch ***@***.***&gt;
发送时间: 2022年8月14日 15:33
收件人: Grasscutters/Grasscutter ***@***.***&gt;
抄送: 李彬 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Grasscutters/Grasscutter] [Bug] 1.2.3-dev.jar在patch后依旧4214，1.2.2不会出现此问题，都是2.8的服务端与客户端，仅仅jar不同 (Issue #1613)





    
能否请你留个邮箱或者其他联系方式呢
  
客户端：https://pan.baidu.com/s/1x4Vbnnc9LmoPF1YAYmw40g?pwd=meow 提取码：meow sideloadly自签，先签第一个，进去登录一个账号，下载完整数据，退出，再签第二个 这个客户端就是打了补丁的
  
大佬，这两个ipa文件好像是ipados的，有没有ios的呀
  
我只有这个版本的

**Comment by shelby-xyz** [comment]
ios 目前究竟怎么玩，这个文件怎么使用？
