### ISSUE TITLE
[Bug] After patching, the game throw "Exception has been thrown by the target of an invocation", then stuck

### ISSUE THREAD

**Issue by YujioNako** [Melledy/Grasscutter#1617]
如题，客户端patch且代理开启后，客户端丢出：Exception has been thrown by the target of an invocation后卡住在的登陆前界面<br>
服务端无错误报告/ There's no error on the game server
<br>
使用/Use  Grasscutter version: 1.2.0；Java：17.0.1

**Screenshots**
![微信图片_20220805104131](https://user-images.githubusercontent.com/69411867/182990222-dce20bff-2aef-4d9d-af70-00f47ab75336.png)

**Comment by YujioNako** [comment]
已解决/Have solved problem
可能是服务端resource包未正确载入造成服务端版本低于客户端

**Comment by xuzhong998** [comment]
小白请问具体是怎么解决的呢?/rookie asking how to solve it in detail

**Comment by YujioNako** [comment]
> 小白请问具体是怎么解决的呢?/rookie asking how to solve it in detail

服务端启动时查看版本；客户端在登录界面左下角查看版本；如两者大版本不同（比如2.8和2.7是不兼容的，但2.8.0和2.8.1是兼容的），则更改服务端resource版本或下载对应服务端版本的客户端即可

**Comment by xuzhong998** [comment]
感谢大佬/ thank you boss!

**Comment by sudaoer** [comment]
我遇到了相同的问题，但是请问去哪里找最新的resource啊/ i met the same problem . but where can i find the latest resource?

**Comment by YujioNako** [comment]
> 我遇到了相同的问题，但是请问去哪里找最新的resource啊/ i met the same problem . but where can i find the latest resource?

搜索grasscutter resource，第一个700+star的那个lua就是
并且是持续更新的

**Comment by sudaoer** [comment]
你说的是这个https://github.com/tamilpp25/Grasscutter_Resources 吗，但是我clone了这个复制进去后仍然有这个问题

**Comment by YujioNako** [comment]
> 你说的是这个https://github.com/tamilpp25/Grasscutter_Resources 吗，但是我clone了这个复制进去后仍然有这个问题

是这个。请确认clone到了除草机根目录，并确认启动时显示版本为对应客户端的版本。若clone后启动显示的版本号未改变，建议重新clone一遍整个除草机以覆盖之前版本可能留下的缓存；若启动显示的版本和客户端相同，那就不知道是为何了，建议另发issue。
