### ISSUE TITLE
 [Bug] Dungeon bug 所有副本无法开启挑战 1.2.3-dev 

### ISSUE THREAD

**Issue by millet6** [Melledy/Grasscutter#1623]
### Dungeon bug
 - A clear and concise description of what the bug is. 
- Dungeon [#405 (2022年8月5日 上午2:01:10)](https://ci.grasscutter.ga/job/Grasscutter-Dev/405/changes) 
- All dungeons cannot start the challenge, since # 405 update    See the picture for details
- 所有地牢（副本）无法开始挑战，自#405更新开始，详情看图片

### Which branch did you use?
  - Grasscutter version: 1.2.3-dev
  - Git Hash: be14e3fc

**Screenshots**
![QQ截图20220807162245](https://user-images.githubusercontent.com/109255084/183282698-c3c3bab2-264b-4360-b5e3-5b83faa3b30b.png)
![QQ截图20220807162210](https://user-images.githubusercontent.com/109255084/183282710-52fb5c32-df77-4dfb-82be-72b80959a7fd.png)
![QQ截图20220807162120](https://user-images.githubusercontent.com/109255084/183282725-14763363-968f-4f24-b41f-0c6bd11dabb0.png)

**Additional context**
Avatar There is no interaction prompt when approaching  This happens in all dungeons
角色/头像 靠近没有互交提示，不能开启挑战，这发生在所有副本

**Comment by worship-dog** [comment]
+1

**Comment by pfyy** [comment]
fixed

**Comment by millet6** [comment]
已修复
