### ISSUE TITLE
[Feature Request] 能否禁用/删除 鱼钩地图传送？Is it possible to disable/remove the fishhook map tp?

### ISSUE THREAD

**Issue by qinastar** [Melledy/Grasscutter#1627]
非常感谢大佬研究出锚点解锁，在此之后，是否能够放弃鱼钩传送功能？
或者说，在config添加一个变量控制开关？
又或者说，注释某一段我自行编译一份。
再次感谢大佬！
#1608

**Comment by KingRainbow44** [comment]
You *can* do this with a plugin, but it might be better to move the functionality altogether to another plugin.

**Comment by 2y8e9h22** [comment]
no

**Comment by eternalcomet** [comment]
修改src/main/java/emu/grasscutter/game/managers/mapmark/MapMarksManager.java
的32行
```
if (createMark.getMapMarkPointType() == MapMarkPointType.MAP_MARK_POINT_TYPE_FISH_POOL) {
    this.teleport(player, createMark);
    return;
}
```
注释以上内容

**Comment by qinastar** [comment]
> 修改src/main/java/emu/grasscutter/game/managers/mapmark/MapMarksManager.java 的32行
> 
> ```
> if (createMark.getMapMarkPointType() == MapMarkPointType.MAP_MARK_POINT_TYPE_FISH_POOL) {
>     this.teleport(player, createMark);
>     return;
> }
> ```
> 
> 注释以上内容

非常感谢大佬！

**Comment by eternalcomet** [comment]
我将会提一个pr，将其设置为可通过config.json关闭。

**Comment by eternalcomet** [comment]
我已经解决：无需注释代码，只要下载最新develpoment分支的action，在config.json的gamOptions里面加上`"fishhookTeleport":false`即可。
we can disable this function in config.json via add `"fishhookTeleport"=false`in gameOptions.

**Comment by qinastar** [comment]
> 我已经解决：无需注释代码，只要下载最新develpoment分支的action，在config.json的gamOptions里面加上`"fishhookTeleport":false`即可。 we can disable this function in config.json via add `"fishhookTeleport"=false`in gameOptions.

thxxxxxxxxxxxxxxxxxx!

**Comment by KingRainbow44** [comment]
leaving this issue pinned until it preferably becomes a plugin
