### ISSUE TITLE
搭建[Bug]

### ISSUE THREAD

**Issue by hohonb** [Melledy/Grasscutter#1628]
![1](https://user-images.githubusercontent.com/110122395/183478607-3c5e4ca3-e291-4967-b623-fe1a458bcb36.PNG)
请求大佬们帮忙看看，这个问题实在不会解决

**Comment by hohonb** [comment]
2.7版本也是这个问题
![Uploading 2.PNG…]()

**Comment by KingRainbow44** [comment]
Database issue. Fix your `config.json`'s MongoDB URI.

**Comment by hohonb** [comment]
好的，谢谢大佬，刚才我把除草机重装了一下就好了，可能是文件冲突



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月9日(星期二) 凌晨2:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter] 搭建[Bug] (Issue #1628)






数据库的问题。修复你的config.json的MongoDB URI。

—
直接回复此邮件，在GitHub上查看，或取消订阅.
***@***.***与&gt;.
