### ISSUE TITLE
丢失文件[bug]

### ISSUE THREAD

**Issue by hohonb** [Melledy/Grasscutter#1631]
有些文件不知道为什么缺失了，求大佬帮忙看看，重新下载grasscutter文件然后运行还是有这种情况，文件regionhandler.java中,只是注释了以下图中的内容
![4](https://user-images.githubusercontent.com/110122395/183614408-660f70d1-3b2f-4b80-9839-ab466a803ab8.PNG)
但是重新运行cmd,还是以下情况
![3](https://user-images.githubusercontent.com/110122395/183613497-56b5f033-efdd-4e7d-ab22-d6a6f2449c9c.PNG)
至于为什么注释文件，我看到问题解决中大佬说可以把其注释掉来解决游戏内4214的问题
![PY9ZX1P$2L}DDLBPTRL5VMD](https://user-images.githubusercontent.com/110122395/183615636-30ab1e2e-c2d2-48f4-a293-a0ca428b4219.jpg)
求大佬帮忙看看，如果大佬有discord可以加下hoho#8644帮忙指导，谢谢。

**Comment by zxymiku** [comment]
原神2.8版本后需要path客户端

**Comment by hohonb** [comment]
> 原神2.8版本后需要path客户端

大佬怎么path客户端，是要加＋文件吗

**Comment by zxymiku** [comment]
https://vkceyugu.cdn.bspapp.com/VKCEYUGU-eaa4ef77-e815-459e-abcb-7df8b7cb11cc/a4d29626-61bc-411c-b85f-aac3c4d8a212.exe你可以使用这个软件去path客户端，在里面填入你的游戏根目录，选择GC就可以path客户端了

**Comment by hohonb** [comment]
> 

大佬文件失效了打开是这个样子
![捕获](https://user-images.githubusercontent.com/110122395/183928821-8c5346c5-c731-477f-810d-c767a68c538f.PNG)

**Comment by zxymiku** [comment]
你直接点链接就会这样，我忘记空格了，你复制https到exe这段链接到浏览器就行了，后面的文字不用输入到浏览器

**Comment by hohonb** [comment]
> 你直接点链接就会这样，我忘记空格了，你复制https到exe这段链接到浏览器就行了，后面的文字不用输入到浏览器

感谢大佬，成功运行了。

**Comment by TronZC** [comment]
> 原神2.8版本后需要path客户端

可否重新发一个patch工具，链接无了。
