### ISSUE TITLE
[Bug] wooden boxes will not disappear after attack

### ISSUE THREAD

**Issue by eternalcomet** [Melledy/Grasscutter#1650]
**Did you look for other closed issues that have the same problem?**

yes.

**Describe the bug**

wooden boxes or buckets will not disappear after player attacks them.

**Which branch did you use?**

1.2.3-dev-7b28eafd

**Screenshots**

![Screenshot_2022-08-11-20-32-34-628_org GenshinImp](https://user-images.githubusercontent.com/52032586/184134315-51339e64-b2d7-4f1a-b5e2-2d156b991ae6.jpg)

**Additional context**

**Comment by wumulong-469** [comment]
I've destroyed them, just higher damage, about 6-7w, maybe 65535? :D

**Comment by Kimi898246** [comment]
![image](https://user-images.githubusercontent.com/34180607/184781566-9266b2f7-15a6-4cef-ac91-038df7067e9b.png)

**Comment by KiminaNatsuki** [comment]
> I've destroyed them, just higher damage, about 6-7w, maybe 65535? :D

![image](https://user-images.githubusercontent.com/34180607/184781659-8c08b383-b643-46c4-ac1c-7534530537c8.png)

**Comment by Takiusu** [comment]
I have the same problem

**Comment by ccb6d** [comment]
Indeed, I also have the same problem, there is a crushing effect, but it is useless and crushed

**Comment by Birdulon** [comment]
Fixed on current resources
