### ISSUE TITLE
[Bug] Compilation error

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1651]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

![捕获](https://user-images.githubusercontent.com/58130955/184248364-540f0aca-10f0-4138-bc3d-830770745185.PNG)
**Additional context**

**Comment by Birdulon** [comment]
Deprecation warnings aren't errors or bugs.
This is the compiler warning about a method which is being removed in the next major update, which has been left in for the time being so that plugins can continue to work until then.

**Comment by ERthereal** [comment]
ok,thanks
