### ISSUE TITLE
[Bug] 1.2.3-dev地图只点亮了初始区域，且无法与神像交互。

### ISSUE THREAD

**Issue by WK-ice** [Melledy/Grasscutter#1653]
**Did you look for other closed issues that have the same problem?**
是的，没有类似的问题。

**Describe the bug**
1.2.2-dev一进游戏就点亮了全图，但是升级到1.2.3-dev后只能点亮初始区域，站在七天神像旁边一点反应没有。重新建立账户也没用。

**Which branch did you use?**

**Screenshots**
![image](https://user-images.githubusercontent.com/71493468/184466573-b08928ee-df34-4707-926e-483343b7894d.png)

![image](https://user-images.githubusercontent.com/71493468/184466594-c24f2551-ee27-4e3a-84f3-f727be287119.png)

**Comment by WK-ice** [comment]
branch: development 7b28eaf

**Comment by mIwaYuhang** [comment]
Automatically start subquests of the questline, which is necessary to make statues interactable 30303

**Comment by ZxyGch** [comment]
prop unlockmap 1

**Comment by WK-ice** [comment]
> prop unlockmap 1

Thank you, this solved my problem!

**Comment by xia0ji233** [comment]
> prop unlockmap 1

what's meaning
