### ISSUE TITLE
[Bug] There is QuestEncryptionKeys.json but it is not detected

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1654]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**
![捕获1](https://user-images.githubusercontent.com/58130955/184477796-17ecd363-7bd8-44fa-bc3e-57f8ac65b1ae.PNG)
![捕获](https://user-images.githubusercontent.com/58130955/184477799-43e5bb7a-a3e3-48cd-9e9e-252ce254ce38.PNG)

**Additional context**

**Comment by 2y8e9h22** [comment]
move data

**Comment by imanityed** [comment]
Move the QuestEncryptionKeys.json file to the data directory.

**Comment by KiminaNatsuki** [comment]
> Move the QuestEncryptionKeys.json file to the data directory.
