### ISSUE TITLE
[Bug] 为什么我进入客户端门后显示白屏

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [Melledy/Grasscutter#1655]
环境如下 Windows2018
java 17

MongoDB 5.0（数据库安装后就没有动过了）

而且服务端的config文件绑定ip也修改

客户端2.8

**Comment by zxymiku** [comment]
目前卡白屏要么是数据库出问题了，你可以尝试删除数据库，要么是你服务端所在的系统有问题没兼容JAVA

**Comment by ZxyGch** [comment]
重新建立一个账号再试试

**Comment by lincyppq** [comment]
不行,重新删库都没用

**Comment by ErrorCodesForLzx** [comment]
> 目前卡白屏要么是数据库出问题了，你可以尝试删除数据库，要么是你服务端所在的系统有问题没兼容JAVA

服务器系统都重装了也不行大佬

**Comment by RTBSG** [comment]
有可能你用的服务器版本跟本地游戏不一致 我昨天2.8 玩3.0 就出现了 换成3.0就好了，还有可能数据库问题 ，没打补丁 都可能出现

**Comment by lincyppq** [comment]
游戏不都是2.8.5那个吗，我补丁没问题，我用1.2.2的分支就能正常玩，新的就不行，数据库我删过了没用

**Comment by millet6** [comment]
> 游戏不都是2.8.5那个吗，我补丁没问题，我用1.2.2的分支就能正常玩，新的就不行，数据库我删过了没用

1.2.3是不可以用的 它对应的是2.8客户端，另外2.8.5对应的是内测版客户端和服务端   资源不一样

**Comment by lincyppq** [comment]
> > 游戏不都是2.8.5那个吗，我补丁没问题，我用1.2.2的分支可以正常玩，新的就不行，数据库我删过了没用>> 1.2.3不能用的它对应的是2.8客户端，另外2.8.5对应的是内测版客户端和服务端资源不一样

那应该使用哪个分支呀，麻烦大佬解惑了

**Comment by millet6** [comment]
> 
https://github.com/Grasscutters/Grasscutter  没有任何一个分支可用，因为这样做米哈游会更加敌视Grasscutter项目 你想要的版本可以到别的地方找到

**Comment by millet6** [comment]
github.com 搜 Grasscutter2.8.54 会有很多

**Comment by lincyppq** [comment]
> github.com 搜 Grasscutter2.8.54 会有很多

谢谢大佬

**Comment by KiminaNatsuki** [comment]
Patch your metadata inside your game folder and try again.
