### ISSUE TITLE
[Bug] Statues of the Seven don't work!

### ISSUE THREAD

**Issue by Takiusu** [Melledy/Grasscutter#1661]
**Did you look for other closed issues that have the same problem?**
I tried, but didn't find anything..

**Describe the bug**
When I trying to use any Statue to open map's regions, it's not working, there is no any button/action.

Grasscutter version: 1.2.3-dev
Git Hash: d80f313

**Screenshots**

![image](https://user-images.githubusercontent.com/65616872/184651653-144b42cc-8768-4f61-af64-b81c3cd62f86.png)
![image](https://user-images.githubusercontent.com/65616872/184652095-c333f74c-2fb9-46ab-a6ae-fbd6398468dd.png)

**Comment by eternalcomet** [comment]
Your grasscutter's version is not the latest.Please download the latest build from github actions([link](https://github.com/Grasscutters/Grasscutter/suites/7807273814/artifacts/329489886))or build by yourself.Your git hash indicates that you are using an old version built three months ago.

**Comment by Takiusu** [comment]
> Your grasscutter's version is not the latest.Please download the latest build from github actions([link](https://github.com/Grasscutters/Grasscutter/suites/7807273814/artifacts/329489886))or build by yourself.Your git hash indicates that you are using an old version built three months ago.

I'm sorry, I'm pretty sure I'm using the latest version of Grasscutter. Here is my folder with grasscutter and resources..
![image](https://user-images.githubusercontent.com/65616872/184658179-5fbbb564-ac77-4115-b486-5646b3c26049.png)

**Comment by Birdulon** [comment]
Try a screenshot of the server console's startup like this:

<img width="479" alt="image" src="https://user-images.githubusercontent.com/5397662/184658433-0f112106-2420-4212-883a-6b6c4dc78299.png">

If it's really showing `1.2.3-dev-d80f313c` then there are bigger problems since that commit is from a 1.1.1-dev build.

Does this happen with new accounts? The only statues that should be missing prompts are Starfell Lake and Stormterror's Lair.

**Comment by Takiusu** [comment]
> Try a screenshot of the server console's startup like this:
> 
> <img alt="image" width="479" src="https://user-images.githubusercontent.com/5397662/184658433-0f112106-2420-4212-883a-6b6c4dc78299.png">
> 
> If it's really showing `1.2.3-dev-d80f313c` then there are bigger problems since that commit is from a 1.1.1-dev build.
> 
> Does this happen with new accounts? The only statues that should be missing prompts are Starfell Lake and Stormterror's Lair.

![image](https://user-images.githubusercontent.com/65616872/184659459-7190af3e-242b-4da2-b30a-74246cb9511f.png)

**Comment by Birdulon** [comment]
Yeah b555039 is recent enough and should work

**Comment by eternalcomet** [comment]
you are using the same version as i provided you.What about creating a new account and try again?Do you only have this trouble in certain areas?
You can even delete the database to try again.

Or you may try the command /quest add 303(i'm not sure after which quest player can interact with the statues @Birdulon )

**Comment by millet6** [comment]
> 是 [b555039 ](https://github.com/Grasscutters/Grasscutter/commit/b555039fb107b169758210d380cda6a2aa1de281)足够新，应该可以工作
The statue of seven really doesn't work ， Dungeons don't work 七人雕像确实不起作用 ，地牢（副本）也不起作用

**Comment by Takiusu** [comment]
> you are using the same version as i provided you.What about creating a new account and try again?Do you only have this trouble in certain areas? You can even delete the database to try again.
> 
> Or you may try the command /quest add 303(i'm not sure after which quest player can intercat with the statues @Birdulon )

Yes, I replaced it with grasscutter-1.2.3 that you sent to me, and I didn't notice any others bugs except this statues.

**Comment by Birdulon** [comment]
> Or you may try the command /quest add 303(i'm not sure after which quest player can intercat with the statues @Birdulon )

Yes, should be main quest 303, new accounts should receive the subquest 30302 as well

**Comment by eternalcomet** [comment]
I tested in person,finding that the statues can't be interacted with but the Dungeons are interactable. d279b359

**Comment by Takiusu** [comment]
> Я проверил лично и обнаружил, что со статуями нельзя взаимодействовать, но с подземельями можно взаимодействовать. [д279б35](https://github.com/Grasscutters/Grasscutter/commit/d279b3597acf079e21e504e9799f6ee29d031e92)

Can it be fixed?

**Comment by Takiusu** [comment]
> I tested in person,finding that the statues can't be interacted with but the Dungeons are interactable. [d279b35](https://github.com/Grasscutters/Grasscutter/commit/d279b3597acf079e21e504e9799f6ee29d031e92)

Thank you for confirming it. Can it be fixed?

**Comment by eternalcomet** [comment]
try this version,it may be working.[link](https://github.com/Grasscutters/Grasscutter/suites/7749351331/artifacts/325372435)
there might be some bugs,I will debug later.

**Comment by millet6** [comment]
> try this version,it may be working.[link](https://github.com/Grasscutters/Grasscutter/suites/7749351331/artifacts/325372435) there might be some bugs,I will debug later.

![QQ截图20220816103356](https://user-images.githubusercontent.com/109255084/184787343-f9b49d06-766e-4045-b7f0-424b07119810.png)
![QQ截图20220816103719](https://user-images.githubusercontent.com/109255084/184787348-e6242b6a-85c9-4d09-8885-1877fae0b272.png)

使用您提供的grasscutter 它是这样的，是我的问题吗
Use the grasscutter provided by you. Is it my problem

**Comment by Takiusu** [comment]
Looks like Statues are working well now, I'm closing this issue.
