### ISSUE TITLE
[Bug] There is not a wind field after Venty use his skill.

### ISSUE THREAD

**Issue by worship-dog** [Melledy/Grasscutter#1664]
**Did you look for other closed issues that have the same problem?**
I didn't find the same problem.
我没有找到相同的问题。

**Describe the bug**
There is not a wind field after Venty use his skill.
温迪使用技能后，没有产生风场。

**Which branch did you use?**
  Grasscutter version: 1.2.3-dev
  Git Hash: 7b28eaf

**Screenshots**

![Venty_1](https://user-images.githubusercontent.com/50063740/184783716-0e07d655-6a0a-45fc-aab5-3cb9190af112.jpg)
![Venty_2](https://user-images.githubusercontent.com/50063740/184783669-997d508c-5127-46ae-9ec3-2ac06d595f66.jpg)
![Venty_3](https://user-images.githubusercontent.com/50063740/184783673-4daa5099-d98c-4f87-bc39-210c201b59df.jpg)

**Additional context**
The skill has just entered the CD, and Wendy is still in the air, but there is no wind field.
技能刚刚进入CD，并且温迪仍在空中，但是没有产生风场。

**Comment by millet6** [comment]
产生风场好像是有等级要求，60级？

It seems that there is a grade requirement for generating wind field, grade 60?

**Comment by worship-dog** [comment]
> 产生风场好像是有等级要求，60级？
> 
> It seems that there is a grade requirement for generating wind field, grade 60?

尴尬，，，要解锁天赋才有风场，感谢提醒
