### ISSUE TITLE
[Bug] Welcome message does not work

### ISSUE THREAD

**Issue by longyi8** [Melledy/Grasscutter#1667]
Grasscutter version: 1.2.3-dev-14a7dd9
New resources
Welcome message does not work
This function seems to have occurred after 1.2.3 and has not been repaired for a long time
Grasscutter 版本：1.2.3-dev-14a7dd9
新的resources
config中的Welcome message不起作用
此问题在1.2.3之后貌似就长期出现了，并且未修复

**Comment by longyi8** [comment]
![image](https://user-images.githubusercontent.com/68991513/184858625-f54766a9-847d-438e-8023-807dd5052722.png)

**Comment by millet6** [comment]
删除 config.json 然后重启服务器 

Delete config.json , and then restart the server

**Comment by longyi8** [comment]
> 删除 config.json 然后重启服务器
> 
> 删除 config.json ，然后重启服务器

是的，我已经尝试过删除config文件，但他仍不起作用。
Yes, I have tried to delete the config file, but it still doesn't work.

**Comment by millet6** [comment]
https://github.com/Grasscutters/Grasscutter/pull/1468

**Comment by millet6** [comment]
你可以查看这里 You can check here https://github.com/Grasscutters/Grasscutter/pull/1468

**Comment by longyi8** [comment]
Well, it looks like this feature has been canceled
好吧，看来这项功能已经取消了
