### ISSUE TITLE
[Feature Request] Reimplement Healing

### ISSUE THREAD

**Issue by xotakfr** [Melledy/Grasscutter#1670]
**Is your feature request related to a problem? Please describe.**

My feature request is about the current healing system. Everything is hard-coded.

**Describe the solution you'd like**

Ideally, il will need to use the resources. I don't know Java enough to know how to make it use resources, but i already initiated https://github.com/Koko-boya/Grasscutter_Resources/pull/9

**Describe alternatives you've considered**

The current system is already an alternative

**Additional context**

I wanted to do something other that localization, so i lookend up healing with the help of #development, and they told me to edit resources.

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
