### ISSUE TITLE
[Feature Request] 将服务端主体和客户端连接指引分割为多个仓库/Split server and client guides to different repositories

### ISSUE THREAD

**Issue by Lavoltz** [Melledy/Grasscutter#1671]
**Is your feature request related to a problem? Please describe.**
没有。/No.

**Describe the solution you'd like**

**Describe alternatives you've considered**
如果这个改动难以接受，保持原状/If this is unacceptable, ignore me.

**Additional context**

**Comment by 2y8e9h22** [comment]
？

**Comment by Bannyfelt13** [comment]
I'm not sure if it really has some meaning

**Comment by MlgmXyysd** [comment]
why do this?

**Comment by gucooing** [comment]
感觉不是特别必要，多个服务端连接同一个数据库就能达到同样的效果

**Comment by Gmskjunior** [comment]
Sair

Em qui., 25 de ago. de 2022 16:59, xlpmyxhdr ***@***.***>
escreveu:

**Comment by Gmskjunior** [comment]
Exit

Em qui., 25 de ago. de 2022 20:50, Andrade ***@***.***>
escreveu:
