### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by Aunchers** [Melledy/Grasscutter#1672]
- I have java se 18 and 17
- MongoDB is setup
- mitmproxy is also setup
- on windows using GIT cmd
- Using Cultivation app

When Logging in I get System error - try again later or server is busy when running my own server

**Comment by KiminaNatsuki** [comment]
Please follow the issue format first, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
(please includes your console log next time too)
