### ISSUE TITLE
[Bug] Healing burst can also heal death characters and cannot be revived

### ISSUE THREAD

**Issue by GioroGiori** [Melledy/Grasscutter#1674]
**Did you look for other closed issues that have the same problem?**
Yeah, but because he don't follow the issue format, was closed 

**Describe the bug**
If some of your characters dies, and after that you use a group healing burst (Like Jean Burst or Barbara Burst), the dead character cannot be revived by any means (reviving food, heal command or even statue of seven), causing and internal server error
Aparently, healing skill also heal dead characters, because if you kill your actual character and the game need to switch, you can see the game switch to the dead character and the HP bar is healed

**Which branch did you use?**
  Grasscutter version: 1.2.3-dev
  Git Hash: e8cbb89

**Screenshots**
![image](https://user-images.githubusercontent.com/75138090/185262210-76d8e33e-6010-4a28-9b9f-7959381278ed.png)

![image](https://user-images.githubusercontent.com/75138090/185262220-26b451ce-6419-42f3-afe3-3a52702fc60e.png)

![image](https://user-images.githubusercontent.com/75138090/185262788-1650b1b5-fd07-4e1a-b7d0-37f6a550d1db.png)

**Additional context**
Besides killing the healed-dead character, other way to fixed is simply log out and login

**Comment by ghost** [comment]
Fixed in dbf2b91d03404a4ee37a1fe12fc737c147177170
