### ISSUE TITLE
[Bug] 出现一个空指针，这个homescene变量是空的导致游戏进不去，白屏

### ISSUE THREAD

**Issue by Needdaima** [Melledy/Grasscutter#1681]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by Needdaima** [comment]
![Q`2Z K`(FXZBSLH~`@IWUTS](https://user-images.githubusercontent.com/67779374/185780138-701466d3-e81a-4c32-b904-c9a31461a120.png)

**Comment by 2y8e9h22** [comment]
哈哈哈

**Comment by ytfh44** [comment]
过于经典的bug

**Comment by ytfh44** [comment]
过于经典的bug

**Comment by i19941021** [comment]
这个最新版已经解决了

**Comment by i19941021** [comment]
老版本 替换回 2.7 的 Resources\ExcelBinOutput 下HomeWorld开头的文件也可以解决
