### ISSUE TITLE
[Bug] can't use the give avatars command in latest version

### ISSUE THREAD

**Issue by jianxingxuejian** [Melledy/Grasscutter#1682]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**
create a new account,the give avatars command will throw a NullExecption

**Which branch did you use?**
1.2.3-dev-c517b8a2

**Screenshots**

![QQ截图20220821194849](https://user-images.githubusercontent.com/39818150/185796726-3de97455-6354-4590-9a38-e4e120c42a7b.png)

**Additional context**

**Comment by WorldEndSukaSuka** [comment]
今天改动有点多，可能动到什么了
