### ISSUE TITLE
[Feature Request] Can you add the function of creating a separate GM Handbook folder when creating "GM Handbook - CHS.-CHT.-DE and other txt documents"

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1686]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
Why you need folder? that's bs. And it already generates one .txt file per language. No need for this

**Comment by ERthereal** [comment]
> 为什么需要文件夹？那是bs。它已经为每种语言生成一个.txt文件。不需要这个

My idea was to create a separate "GM Handbook" folder to make the inside of the "Grasscutter" file look cleaner

**Comment by 2y8e9h22** [comment]
你自己改改输出目录不就好了

**Comment by ERthereal** [comment]
> 你自己改改输出目录不就好了

没找到

**Comment by ChisatoNishikigi73** [comment]
> > 你自己改改输出目录不就好了
> 
> 没找到

grasscutter.java,line 106

**Comment by ERthereal** [comment]
> > > 你自己改改输出目录不就好了
> > 
> > 
> > 没找到
> 
> 割草机.java，106行

Thanks!

**Comment by ChisatoNishikigi73** [comment]
> > > > 你自己改改输出目录不就好了
> > > 
> > > 
> > > 没找到
> > 
> > 
> > 割草机.java，106行
> 
> Thanks!

I'll put them in a folder in future PR
