### ISSUE TITLE
Add more detail of merge commits message

### ISSUE THREAD

**Issue by WetABQ** [Melledy/Grasscutter#169]
It's too hard to quickly locate some commits when the commits log contains tons of "Merge pull request ... from  ..."

And I recommend using rebase rather than merge except we need to solve conflicts.

**Comment by memetrollsXD** [comment]
GitHub adds those commits automatically when merging a PR from the website, nothing we can do about it

**Comment by WetABQ** [comment]
![image](https://user-images.githubusercontent.com/25319400/164954512-5868d9f2-11f3-4ff6-8420-329ee3e04e92.png)

**Comment by WetABQ** [comment]
> GitHub adds those commits automatically when merging a PR from the website, nothing we can do about it

![image](https://user-images.githubusercontent.com/25319400/164954528-61811686-569f-4c7b-8883-bc4783fcb150.png)

**Comment by memetrollsXD** [comment]
@Grasscutters/grassclippers Consider this suggestion

(Tagging individually: @KingRainbow44 @Melledy)
