### ISSUE TITLE
When using LAN server, connection error is reported 4206.

### ISSUE THREAD

**Issue by Yazawazi** [Melledy/Grasscutter#170]
Reported by Discord user @yylmzxc#7780, I started the issue on his behalf.
---
Description: He tried to set up a LAN server and tried to log in on another host, but it failed with error 4206.

Related information:
 - According to him, the ports are not occupied;
 - The firewall is set up properly and there is no blocking;
 - The `PublicIP` is modified to his LAN address;
 - The client uses Fiddler Classic and modifies the script to link to his server.
 - The version used is v1.0.0.

Images:
![error](https://user-images.githubusercontent.com/47273265/164954625-c6044aa5-f2e1-42ee-8cb8-c94098a543b1.jpg)
![4206](https://user-images.githubusercontent.com/47273265/164954627-e0c30b12-ffee-4728-87ab-d8ef4530078c.jpg)
![console](https://user-images.githubusercontent.com/47273265/164954631-f23dde16-843f-4e59-8af7-f14c9ae837ca.png)

**Comment by Yazawazi** [comment]
It has been solved, it seems to be a public server. I'm sorry I didn't ask for clarification.

**Comment by fulanlanlu** [comment]
Hello, I have the same problem, how did you solve it
