### ISSUE TITLE
[Feature Request] I'm looking forward to the update version 3.0

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [Melledy/Grasscutter#1701]
How long before we can clone 3.0 GC server source code

**Comment by Roly-lol** [comment]
![WU5ZAF$K UU70MN)B0DTDR](https://user-images.githubusercontent.com/90933865/186330139-e26fa246-c83c-4700-988f-55c90ec48a1c.png)
done

**Comment by SleepyAsh0191** [comment]
#1698
