### ISSUE TITLE
[Bug] 生成手册时卡退

### ISSUE THREAD

**Issue by ytfh44** [Melledy/Grasscutter#1702]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

我更新了resources,然后在生成手册时卡退了
**Which branch did you use?**

 1.2.3-dev-6098b51e
**Screenshots**

![图片](https://user-images.githubusercontent.com/82327657/186358078-66b24f65-fbe6-42b6-9def-f0529700a314.png)

**Additional context**

把resources由2.8升级到3,0

**Comment by rdp-studio** [comment]
大概是程序还没兼容3.0吧?

**Comment by ytfh44** [comment]
> 大概是程序还没兼容3.0吧?

好像是因为kokobaya的resource有毛病

**Comment by Needdaima** [comment]
> > 大概是程序还没兼容3.0吧?
> 
> 好像是因为kokobaya的resource有毛病

好像是割草机有问题，resource没问题

**Comment by mingmono** [comment]
请问如何升级到3.0呢

**Comment by Livingup** [comment]
> 请问如何升级到3.0呢

[https://github.com/Koko-boya/Grasscutter_Resources/tree/3.0](url)

**Comment by mingmono** [comment]
> > 请问如何升级到3.0呢
> 
> [https://github.com/Koko-boya/Grasscutter_Resources/tree/3.0](url)

哦哦 谢谢  我去试试

**Comment by L4cache** [comment]
> > 大概是程序还没兼容3.0吧?
> 
> 好像是因为kokobaya的resource有毛病

https://github.com/Grasscutters/Grasscutter/issues/1687#issuecomment-1224522299
暂时使用2.8版本的这个文件替换吧，并且删除cache文件夹

**Comment by ytfh44** [comment]
最新版的割草机解决了这个问题 ,thanks

**Comment by ChisatoNishikigi73** [comment]
请关闭此issues，PullRequest#1744修复了此问题
