### ISSUE TITLE
[Bug] talent command will not be effective immediately, need to re-login

### ISSUE THREAD

**Issue by jianxingxuejian** [Melledy/Grasscutter#1714]
**Did you look for other closed issues that have the same problem?**
yes

**Describe the bug**
The damage didn't change after edit talent level.
Is it because the damage is calculated locally? Is there any way to fix?

**Which branch did you use?**
1.2.3-dev-1a801192

**Screenshots**

**Additional context**

**Comment by Birdulon** [comment]
Talents update levels immediately on current GC builds, but damage calculation will still be weird on some talents (no relation to the command) because of unimplemented behaviours.
