### ISSUE TITLE
Can't send messages to the server in game

### ISSUE THREAD

**Issue by MuriyaTensei** [Melledy/Grasscutter#172]
There are some commands that prompt me to "Run this command in-game." But I can't send any messages to the server in the game. Whether I entered the command or other words and clicked send but nothing happened

**Comment by CR4Player** [comment]
command send to server need a "!" prefix, like !help, !give 223 100
maybe you forgot this.

**Comment by MuriyaTensei** [comment]
> command send to server need a "!" prefix, like !help, !give 223 100 maybe you forgot this.

Thanks, I really didn't add the prefix, Now it works

**Comment by memetrollsXD** [comment]
Also to keep in mind: Some commands may not give you a reply back
