### ISSUE TITLE
[Feature Request] Add support for older versions of Genshin

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1730]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Hi I would like to suggest adding support for Genshin versions all the way back to 1.0.

**Describe alternatives you've considered**

**Additional context**

**Comment by KingRainbow44** [comment]
Older versions of _anime game_ are not going to be supported by Grasscutter at this time. Check out something like [HuTaoGS](https://github.com/Wangsheng-Funeral-Parlor/HuTao-GS).
