### ISSUE TITLE
[Bug] House's interiors broken walls, floors, doors, etc

### ISSUE THREAD

**Issue by GioroGiori** [Melledy/Grasscutter#1735]
**Did you look for other closed issues that have the same problem?**
No, and I didn't see someting about it

**Describe the bug**
The houses of Serenitea Pot have for some reason too many duplicates of walls, rooms, floor, creating some unaccesible rooms, walls when they're not being, can't access to second floor, over positioned floors, and more, is more notieable in Inazuma house (because you have a wall in the entrance hall), but this happen in Mondstadt Mansion and Liyue house too

**Which branch did you use?**

  Grasscutter version: 1.2.3-dev
  Git Hash: 712d176

**Screenshots**

**Inazuma House**
![image](https://user-images.githubusercontent.com/75138090/188041253-fa643244-97c2-4eb2-ba2b-a44c02773a68.png)
![image](https://user-images.githubusercontent.com/75138090/188041369-2b9ceca9-66db-4602-b035-c62d2bc1d412.png)
![image](https://user-images.githubusercontent.com/75138090/188041397-643e41a9-367f-4ec1-9bbb-0d3601be316b.png)
![image](https://user-images.githubusercontent.com/75138090/188041453-7faf8814-6e62-4e87-80b4-85b5b25db90a.png)
![image](https://user-images.githubusercontent.com/75138090/188041694-27439f77-51d9-4ce8-bcfc-287e5190eb27.png)

![image](https://user-images.githubusercontent.com/75138090/188041543-890180f8-b991-471d-9729-83431b520cee.png)
![image](https://user-images.githubusercontent.com/75138090/188041581-3652b219-9fc5-4be9-88b9-1149a26be2de.png)
![image](https://user-images.githubusercontent.com/75138090/188041594-db517815-d112-4c70-beaa-85c311a9c85b.png)
![image](https://user-images.githubusercontent.com/75138090/188041763-d50f7c7a-1297-4db5-935e-8bf7a190bf24.png)
![image](https://user-images.githubusercontent.com/75138090/188041785-b136a59e-6527-4cac-afd3-15124f411190.png)
![image](https://user-images.githubusercontent.com/75138090/188042457-64d21ba6-ee32-46d6-a9a4-e88c793d58e6.png)

**Mondstadt Mansion**
![image](https://user-images.githubusercontent.com/75138090/188043349-d7efc67c-9abb-4771-8909-11120f38c0b2.png)
![image](https://user-images.githubusercontent.com/75138090/188043368-886abe81-ecff-47a5-bd75-2052ee2db330.png)
![image](https://user-images.githubusercontent.com/75138090/188043391-84c85a77-beb2-4482-a227-21aa80b9b833.png)
![image](https://user-images.githubusercontent.com/75138090/188043413-726e0fea-cd40-4d79-b560-1635a3946836.png)
![image](https://user-images.githubusercontent.com/75138090/188043431-17dc66ff-6156-42cf-b285-711e48046191.png)

**Liyue house**
![image](https://user-images.githubusercontent.com/75138090/188044229-47a821af-c752-493b-8ac3-520d1cfd9e26.png)
![image](https://user-images.githubusercontent.com/75138090/188044250-e63c408e-9299-439b-8db6-3d6c5b0456a7.png)
![image](https://user-images.githubusercontent.com/75138090/188044287-0e8c66db-6854-4409-b771-651e8ab74055.png)
![image](https://user-images.githubusercontent.com/75138090/188044313-1b171598-4e32-415d-ae44-fd25a9a32f92.png)
![image](https://user-images.githubusercontent.com/75138090/188044327-c943dc70-29b8-4c38-a44a-607e0a0d866d.png)
![image](https://user-images.githubusercontent.com/75138090/188044338-4ecda23e-5c03-418d-bb59-3247189e8d9c.png)

**Additional context**
Is requiered Noclip for Akebi most on the cases to enters some rooms and even some unaccesible parts of some rooms

**Comment by xNissX233** [comment]
Yeah, this is a weird behavior and must be fixed. Meanwhile, it's somehow fixable if you retrieve all the furniture in every area of the house.
![Screenshot_20220902_134528](https://user-images.githubusercontent.com/35869848/188133561-447aaaac-7065-4815-a5ad-5e6e5a8bc334.png)

**Comment by GioroGiori** [comment]
If you have this error(because you home was created in 2.7 or before the fix created by pfyy) and you put Furniture using Akebi Noclip, Retrieve Furnishing like RBNXI show
