### ISSUE TITLE
The game won't detect controller automatically when using this,have to set manully

### ISSUE THREAD

**Issue by 1235467** [Melledy/Grasscutter#174]

**Comment by memetrollsXD** [comment]
Detecting controller seems unrelated to this project. Does this happen with GrassClipper? Or are you using the official launcher?

**Comment by 1235467** [comment]
official server does the controller dection part automatically.Seems to be something related with server. I wonder if it is the problem of grasscutter.

**Comment by memetrollsXD** [comment]
There isn't, that's the weird part.. Controller detection is all client side

**Comment by 1235467** [comment]
Thanks for your help.That's quite wierd then.
