### ISSUE TITLE
[Bug] grass Statues don't work!  Unable to light the map

### ISSUE THREAD

**Issue by millet6** [Melledy/Grasscutter#1742]
**Describe the bug**
grass Statues don't work!  Unable to interact with each other
草神无法互交，其他神像正常。

**Which branch did you use?**
  Grasscutter version: 1.3.1-dev

**Screenshots**
![QQ截图20220903192154](https://user-images.githubusercontent.com/109255084/188268221-6cdcf0dd-1793-419e-832d-983b3edf3a79.png)

**Additional context**

**Comment by sans23456** [comment]
是不是红色未解锁状态？如果是的话和我一样
