### ISSUE TITLE
[Bug] There are some bugs in the healing system

### ISSUE THREAD

**Issue by SummerJustNice** [Melledy/Grasscutter#1746]
**Did you look for other closed issues that have the same problem?**

Yes. 是的

**Describe the bug**

The amount of healing is not right. Duplicated healing occured when battling. Many healers have these bugs.
治疗量不正确。战斗时出现了多次重复治疗。很多奶妈都有这些bug。

**Which branch did you use?**

  Grasscutter version: 1.3.1-dev
  Git Hash: 5529674b90e
**Screenshots**

![f41fde712284feb230ad2ea8f38ae54](https://user-images.githubusercontent.com/59387109/188323956-decab29c-244e-459c-8776-98a81fbc8ba0.jpg)

**Additional context**

C6 Kokomi should have healing bonus for low HP characters. 
Considering now the healing abilities are almost hardcoded, is it acceptable to be more "hard" - writing individual healing function for every healer? If it is acceptable, maybe I can help to debug.
六命心海对低血量人物应有治疗加成
考虑到现在的治疗技能基本上是硬编码的，更”硬“一点能否接受呢？也即对每个奶妈独立写治疗函数。如果这可以接受，我可以帮忙debug。

**Comment by flymoonvip** [comment]
Healing with food does not reduce the amount in the backpack
还有食物治疗并不减少背包内的数量

**Comment by shin1804** [comment]
Did ur shinobu can heal other charater? Mine only heal when use E first times then no more heal.

**Comment by KingRainbow44** [comment]
resolved in #2166
