### ISSUE TITLE
[Feature Request] Support unlocking and changing the Realm Music  / 希望支持尘歌壶的音乐切换功能

### ISSUE THREAD

**Issue by NstzJC** [Melledy/Grasscutter#1750]
![image](https://user-images.githubusercontent.com/57438394/188555545-a75a992c-fb85-421f-8b59-c9329a969466.png)

It's not supported now.

**Comment by eternalcomet** [comment]
#1844 is working for this.
这项功能正在开发。

**Comment by Birdulon** [comment]
Fixed by #1844
