### ISSUE TITLE
The console keeps outputting RECV and SEND with nonsense after receiving an Error Code 4209

### ISSUE THREAD

**Issue by DerivativeMarmot** [Melledy/Grasscutter#176]
![error code 4209](https://user-images.githubusercontent.com/78244769/164956645-36f37f16-6ef3-4977-93df-0c69653bd262.jpg)

[log.txt](https://github.com/Grasscutters/Grasscutter/files/8549032/log.txt)
I was first not able to login with an existing account due to 4209 (I have successfully logged in and played previously).
A few hours later, I'm able to login and play, but the console keeps outputting nonsenses. log is provided above.

**Comment by memetrollsXD** [comment]
The “nonsense” you mean is the raw packet data sent with it, no idea how to disable it, but there’s nothing wrong with your game

**Comment by ghost** [comment]
You can disable it by setting `LOG_PACKETS` to `false` in your config.

**Comment by DerivativeMarmot** [comment]
> 

thx

**Comment by DerivativeMarmot** [comment]
> You can disable it by setting `LOG_PACKETS` to `false` in your config.

thx
