### ISSUE TITLE
[Bug] 没错，又是我      游戏的背景音乐不随角色位置改变

### ISSUE THREAD

**Issue by awaae001** [Melledy/Grasscutter#1765]
在游戏中我发现   游戏的背景音乐不随角色位置改变
In the game I found that the background music of the game does not change depending on the position of the character

但 是  在前往其他场景却能正常切换，例如 金苹果群岛  
However, when going to other scenes, it can switch normally  For example, the Golden Apple Islands

同理，我在须弥却播放的是蒙徳的音乐
In the same way, I was playing Maki music in Sumire（There was a problem with the translation）

希望修复此BUG
Hope to fix this bug

**Comment by luluxiaoyu** [comment]
须弥的音乐没有问题吧？

**Comment by 2y8e9h22** [comment]
又是你

**Comment by awaae001** [comment]
ok
