### ISSUE TITLE
[Feature Request] 能否告知一个思路，让我可以更改圣遗物掉落时决定词条以及强化词条的规则？

### ISSUE THREAD

**Issue by ststyst** [Melledy/Grasscutter#1768]
如题；
我希望作者能告知一个思路，让我们可以修改圣遗物决定词条和强化词条的规则，这样或许能让游戏更有意思，谢谢您为这个项目做出的一切。

**Comment by loveustars** [comment]
有无3.0安卓启动器谢谢😭

**Comment by Bannyfelt13** [comment]
> 如题； 我希望作者能告知一个思路，让我们可以修改圣遗物决定词条和强化词条的规则，这样或许能让游戏更有意思，谢谢您为这个项目做出的一切。

不要成为一名瞎子。man。。。。。

**Comment by Birdulon** [comment]
`resources/ExcelBinOutput/ReliquaryAffixExcelConfigData.json` `weight` and `upgradeWeight` values
