### ISSUE TITLE
[Feature Request] 能做到和官服一样的玩法，仅仅多了指令功能和鱼钩传送吗 Can we do the same way as the official clothes, only with more command functions and fish hook transmission

### ISSUE THREAD

**Issue by ozqs** [Melledy/Grasscutter#1769]
目前好像还有自动开启任务不支持，没法过主线剧情等小问题。
**或者简单点，让我们可以给服务器创建脚本，自己实现这些事情？**
比如你做完这个任务执行下一个任务。
打圣遗物本也会有一些奇怪的Bug.

trans:
At present, it seems that there are still some small problems such as the inability to support the automatic start task and the inability to handle the main plot.

Or simply, let's create scripts for the server and implement these things ourselves?

For example, after you finish this task, you can perform the next task.

There will also be some strange bugs when playing relic

**Comment by sj817** [comment]
那为什么不直接玩官服呢

**Comment by longhuan1999** [comment]
任重而道远

**Comment by Bannyfelt13** [comment]
> 目前好像还有自动开启任务不支持，没法过主线剧情等小问题。 **或者简单点，让我们可以给服务器创建脚本，自己实现这些事情？** 比如你做完这个任务执行下一个任务。 打圣遗物本也会有一些奇怪的Bug.
> 
> trans: At present, it seems that there are still some small problems such as the inability to support the automatic start task and the inability to handle the main plot.
> 
> Or simply, let's create scripts for the server and implement these things ourselves?
> 
> For example, after you finish this task, you can perform the next task.
> 
> There will also be some strange bugs when playing relic

现在完全可以自行修复。
取决于个人能力罢了

**Comment by ozqs** [comment]
> 那为什么不直接玩官服呢

1. mc 的生存模式开作弊和不开作弊是完全不一样的（doge
2. 提供了可以离线玩的途径

**Comment by ozqs** [comment]
> > 目前好像还有自动开启任务不支持，没法过主线剧情等小问题。 **或者简单点，让我们可以给服务器创建脚本，自己实现这些事情？** 比如你做完这个任务执行下一个任务。 打圣遗物本也会有一些奇怪的Bug.
> > trans: At present, it seems that there are still some small problems such as the inability to support the automatic start task and the inability to handle the main plot.
> > Or simply, let's create scripts for the server and implement these things ourselves?
> > For example, after you finish this task, you can perform the next task.
> > There will also be some strange bugs when playing relic
> 
> 现在完全可以自行修复。 取决于个人能力罢了

有相关的文档吗，不知道在哪里获取

**Comment by ozqs** [comment]
懂了
希望以后可以出文档（关于Server的使用）
更希望 Grasscutter 越做越好！

**Comment by wangyufeng2006** [comment]
???现在Grasscutter支持剧情了吗
