### ISSUE TITLE
development/keystore.p12 Installation failure in windows 10

### ISSUE THREAD

**Issue by yoyumiya** [Melledy/Grasscutter#177]
Even though it shows that the certificate was successfully added, it does not appear in the Trusted Certification Authorities directory when you start certmgr.msc via win+r.
Compared to the certificate under stable, there is no "security prompt" during the installation process.
The certificate under stable can be installed normally.
![1 (2)](https://user-images.githubusercontent.com/104292656/164968482-2cc18419-ff33-4ef2-971c-1658811e7d3f.png)

**Comment by yoyumiya** [comment]
It still doesn't work on the other Win10 computer. But it shows "security prompt"
![3](https://user-images.githubusercontent.com/104292656/164968403-5b39e2a0-c9a2-4bcb-b41f-2f2e9ecb108d.png)

**Comment by memetrollsXD** [comment]
There are 2 places for root CA: local user and the whole computer. Did you check both?

**Comment by yoyumiya** [comment]
Yes, all cannot be added.

**Comment by fumbling644o** [comment]
Please **do not** install the keystore.p12 file. You should NEVER install a certificate that's widely distributed like that.

mitmproxy and Fiddler can ignore the invalid SSL certificate coming from `localhost:443` (dispatch server).
