### ISSUE TITLE
[Bug] Grasscutter在Centos8中优先绑定IPV6地址的问题

### ISSUE THREAD

**Issue by coolxitech** [Melledy/Grasscutter#1776]
Grasscutter version: 1.3.0-1555010
OS: Centos8 Stream
配置文件中写着IPV4的0.0.0.0，实际绑定的却是IPV6的地址
网上搜索相关udp6的资料后发现有一定的误导性(upd6 ≈ ipv4 and ipv6)
实际上centos中udp和udp6是两种绑定协议,希望开发人员修复该问题，同时支持ipv4和ipv6.
![QQ截图20220913172914](https://user-images.githubusercontent.com/20185794/190085800-4bae51b0-251c-4845-ad68-8ced5d3d5cab.jpg)

**Comment by Birdulon** [comment]
What do you want it to bind to? If `bindAddress` is an empty string Java will bind to the wildcard address.
Are you having trouble connecting via IPv4 with that setup? Documentation suggests that that `udp6` bind should be capable of communicating with IPv4 and IPv6 clients.

**Comment by coolxitech** [comment]
> What do you want it to bind to? If `bindAddress` is an empty string Java will bind to the wildcard address. Are you having trouble connecting via IPv4 with that setup? Documentation suggests that that `udp6` bind should be capable of communicating with IPv4 and IPv6 clients.

But I really can't connect to the udp6 protocol directly. I can connect normally through nginx proxy

**Comment by coolxitech** [comment]
> What do you want it to bind to? If `bindAddress` is an empty string Java will bind to the wildcard address. Are you having trouble connecting via IPv4 with that setup? Documentation suggests that that `udp6` bind should be capable of communicating with IPv4 and IPv6 clients.

After I use nginx to proxy the UDP protocol of the IPV6 address, I can connect normally, but I cannot connect to the IPV4 address

**Comment by coolxitech** [comment]
> > What do you want it to bind to? If `bindAddress` is an empty string Java will bind to the wildcard address. Are you having trouble connecting via IPv4 with that setup? Documentation suggests that that `udp6` bind should be capable of communicating with IPv4 and IPv6 clients.
> 
> After I use nginx to proxy the UDP protocol of the IPV6 address, I can connect normally, but I cannot connect to the IPV4 address

like this.
![netstat](https://user-images.githubusercontent.com/20185794/190128951-bc720282-7597-4898-a5e3-d2f6936ddedc.jpg)

**Comment by coolxitech** [comment]
> > > What do you want it to bind to? If `bindAddress` is an empty string Java will bind to the wildcard address. Are you having trouble connecting via IPv4 with that setup? Documentation suggests that that `udp6` bind should be capable of communicating with IPv4 and IPv6 clients.
> > 
> > 
> > After I use nginx to proxy the UDP protocol of the IPV6 address, I can connect normally, but I cannot connect to the IPV4 address
> 
> like this. ![netstat](https://user-images.githubusercontent.com/20185794/190128951-bc720282-7597-4898-a5e3-d2f6936ddedc.jpg)
![nginx](https://user-images.githubusercontent.com/20185794/190129958-6733bfde-35b0-4782-8e73-0202a8ec6185.jpg)
