### ISSUE TITLE
[Feature Request] 玩家登录后自动执行命令的功能

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1781]
**Is your feature request related to a problem? Please describe.**
比如我想做一个打怪模拟器，那么我就会希望玩家一上线就被传送到特点的场景或者坐标，而不是需要手动输入。又或者说一上线就清空背包，然后发放10个甜甜鸡，然后看玩家能杀多少怪物之类的

**Describe the solution you'd like**
上述想法在当前版本都能实现，唯一的问题是需要玩家自己手动执行代码，要是能在config.json里面加入一个，玩家登录时自动执行代码的工具就好了，就是正常的命令行，玩家上线后自动输给控制台

**Describe alternatives you've considered**
如果不方便的话做成单独的插件，jar的那种也好，让玩家有的选

**Comment by 2y8e9h22** [comment]
我可以做，请联系我。

**Comment by 909101** [comment]
> 我可以做，请联系我。
好的！请问在哪联系你呢

**Comment by i19941021** [comment]
自己写一个就好 ，不算太难 实际测试总代码 300多行就能实现

**Comment by i19941021** [comment]
配置文件读取 Grasscutter 已经提供好接口了，自己自定义一个Config 类就好  读取直接 config = JsonUtils.loadToClass(configFile.getAbsolutePath(), MainConfig.class);

**Comment by 909101** [comment]
> 配置文件读取 Grasscutter 已经提供好接口了，自己自定义一个Config 类就好 读取直接 config = JsonUtils.loadToClass(configFile.getAbsolutePath(), MainConfig.class);

这确实是太难为我们这些技术小白了，大佬要是愿意弄个PR就好了~
