### ISSUE TITLE
[Bug] 1.3.0的GC版本下，无法正常打深渊

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1782]
**Did you look for other closed issues that have the same problem?**
看了，有类似报告，但是测试的没有我的全面

**Describe the bug**
分别用2.8和3.0的国服版本做了测试，resource文件也采用的是对应版本的，但是出现的问题是一样的，就是第九层下半不出怪，第十一层上半怪只出一半，别的层没有测试

**Which branch did you use?**
最新的1.3.0 jar

**Additional context**
目前想到的可能性有：
resource文件不对，那麻烦大佬指路，来一份正确的
深渊配置也许是可以手动修改的，需要修改？

**Comment by 909101** [comment]
突然意识到也有可能是global-metadata的问题，麻烦大佬指点一下到底是哪的问题

**Comment by 2y8e9h22** [comment]
lua脚本的问题
