### ISSUE TITLE
[Feature Request] 有没有去除人物虚化的工具

### ISSUE THREAD

**Issue by Needdaima** [Melledy/Grasscutter#1785]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Bannyfelt13** [comment]
there's nothing with grasscutter 
i suggest that you should close this issue :D

**Comment by bai1996** [comment]
这东西在客户端里面，后端无法改变其展现的逻辑，无能为力了属于是
