### ISSUE TITLE
[Bug] The character's [Seat of Life] talent+3 does not work 【角色的【命之座】的天赋+3不生效】

### ISSUE THREAD

**Issue by bai1996** [Melledy/Grasscutter#1786]
cn：在角色满【命之座】的状态下，天赋等级上限依旧是10
en： When the character is full of [Seat of Life], the maximum talent level is still 10 

cn：使用版本
en：Use version
  Grasscutter version: 1.3.1-dev
  Git Hash: 2a6332b7

**Comment by Birdulon** [comment]
This is a known problem for newer (>2.6) characters with current public resources, as they haven't been properly dumped.
