### ISSUE TITLE
[Bug] bindAddress ignored (always binds to 0.0.0.0)

### ISSUE THREAD

**Issue by ste94pz** [Melledy/Grasscutter#1797]
Hi, if I try to set a bindAddress different than 0.0.0.0 (like 192.168.11.4), it always binds on 0.0.0.0, but in the console I read the address that I put in the configuration. I'm on Ubuntu 22.04.1, openjdk 17.0.4.

Grasscutter version: 1.3.2-dev
Git Hash: 794350a

**Comment by bai1996** [comment]
en:
game { bindAddress,accessAddress } and http { bindAddress,accessAddress },I changed it and tried it. The only change is the console display. It seems that it is not really bound to the specified IP address
cn:
game { bindAddress,accessAddress } and http { bindAddress,accessAddress }，我改了一下试了试，变的只有控制台显示，好像并没有真正的绑定到指定IP

![图片](https://user-images.githubusercontent.com/26263269/192678846-3e71aa86-0ad8-49d1-b65b-30e2ebafd6d1.png)
![图片](https://user-images.githubusercontent.com/26263269/192678855-6cac3943-ff99-4ee3-a66c-8e1909ea3668.png)

en:
 After debugging, I found that the value can be inserted normally, 

cn:
调试了一下，发现值可以正常塞进去，
![图片](https://user-images.githubusercontent.com/26263269/192701795-f72743eb-5705-44ff-b647-a9f370924664.png)

**Comment by shutdown6666** [comment]
> 

大佬，能详细说说怎么操作吗，我也遇到这种情况了……

**Comment by shutdown6666** [comment]
> en： game { bindAddress，accessAddress } 和 http { bindAddress，accessAddress }，我更改了它并尝试了它。唯一的变化是控制台显示。似乎它并没有真正绑定到指定的IP地址cn：game { bindAddress，accessAddress } and http { bindAddress，accessAddress }，我改了一下试了试，变的只有控制台显示，好像并没有真正的绑定到指定IP
> 
> ![图片](https://user-images.githubusercontent.com/26263269/192678846-3e71aa86-0ad8-49d1-b65b-30e2ebafd6d1.png) ![图片](https://user-images.githubusercontent.com/26263269/192678855-6cac3943-ff99-4ee3-a66c-8e1909ea3668.png)
> 
> en：调试后发现该值可以正常插入，
> 
> cn： 调试了一下，发现值可以正常塞进去， ![图片](https://user-images.githubusercontent.com/26263269/192701795-f72743eb-5705-44ff-b647-a9f370924664.png)

大佬，能详细说说怎么操作吗，我也遇到这种情况了......

**Comment by bai1996** [comment]
> 
我只debug查了一下原因，并没有改，是【io.javalin.Javalin】的问题，
0.0.0.0是全部IP可访问，没有改的必要
