### ISSUE TITLE
[Bug] Can't connect with encryption enabled

### ISSUE THREAD

**Issue by ste94pz** [Melledy/Grasscutter#1798]
Hi, I can't log into the server with encryption enabled, as default config, it gives me "system error" after entering username and password. I'm using Cultivation with https checked, with the server on port 9443, because the 443 is already used by apache. If I disable the encryption, everything works. I tried to use both ip address and fqdn as address in Cultivation, and as accessAddress in the server config. The server is on Ubuntu 22.04.1 with openjdk 17.0.4, and the client is on Windows 11 latest version.

Grasscutter version: 1.3.2-dev
Git Hash: 794350a

**Comment by akatatsu27** [comment]
"System Error" usually means you're not even connecting to the server. Since it works without encryption, it means grasscutter correctly binds to the specified port. I personally use fiddler with encryption enabled, so this actually sounds like a cultivation issue, not a grasscutter issue. They must fix connecting to https endpoints for obvious security reasons

**Comment by ste94pz** [comment]
> "System Error" usually means you're not even connecting to the server. Since it works without encryption, it means grasscutter correctly binds to the specified port. I personally use fiddler with encryption enabled, so this actually sounds like a cultivation issue, not a grasscutter issue. They must fix connecting to https endpoints for obvious security reasons

Could you share your fiddler script, please? And, is it possible to set another port in it? My 443 port is already used by Apache, so I'm using the 9443. Thank you.

**Comment by akatatsu27** [comment]
sorry for the late reply.
this is the fiddler script I use:
[fiddlerscript.txt](https://github.com/Grasscutters/Grasscutter/files/9619296/fiddlerscript.txt)
simply change the host and port to the ones you want

**Comment by ste94pz** [comment]
> sorry for the late reply.
> 
> this is the fiddler script I use:
> 
> [fiddlerscript.txt](https://github.com/Grasscutters/Grasscutter/files/9619296/fiddlerscript.txt)
> 
> simply change the host and port to the ones you want

It works, thank you. Sorry for opening the bug 😅

**Comment by akatatsu27** [comment]
> 

well it is a bug... just on the wrong repository. I suggest making a bug report on cultivation (if there isnt already one)
