### ISSUE TITLE
[Bug] Connect to server And Client says Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by Richardzhuge** [Melledy/Grasscutter#1806]
As the title says every time i try to connect to my server i always will get a message from my client says Exception has been thrown by the target of an invocation
就跟标题说的一样，每次我在尝试连接到我的服务器时我都会收到来自我的客户端的一条消息说Exception has been thrown by the target of an invocation。

I can see there has this Issue before and sovle ways is change my sources to the lastes version.But now my client and my server has the same version sources and i still keep get this message on my client. What should i do? how can i solve this problem?help me please.........

我可以看到之前曾经有过这个问题，并且解决方案是更换sourcese到最新版本，但是现在我的客户端和我的服务器source版本是同样的版本，并且我还是持续收到了这个报错。我该怎么做才能解决这个问题呢？请帮帮我！拜托了！

BTW my server sourcese version is 3.0 and my client version is 3.0 too.Java version is jdk17 MongoDB version is 6.0.1 and system is the windows 10 professionl workstation version.And i did try to run my server on a Debian11 and it happened again, same problem.
顺便提一句我的服务器sources版本是3.0并且我的客户端版本也是3.0。java版本是jdk17，芒果数据库（MongoDB）版本是6.0.1，系统版本是Win10专业工作站版，以及我尝试过把我的服务端部署在一台Debian11上，但是它也出现了同样的问题。

![Screenshot 2022-09-25 134352](https://user-images.githubusercontent.com/62455517/192131303-708604e3-0b96-4736-880b-a423a1a5bada.png)
![Screenshot 2022-09-25 2125631513](https://user-images.githubusercontent.com/62455517/192131344-2cf7ff01-eb40-4c0e-9b3c-7a061be837ef.png)

**Comment by YinCQL** [comment]
global-metadata.dat.可能用错版本了 ？

**Comment by Richardzhuge** [comment]
@YinCQL 抱歉，global-metadata.dat是啥？

**Comment by YinCQL** [comment]
https://github.com/Bambi5/Collei_Launcher 使用这个对 metadata 修补，实际上你这个并不属于bug , 如果解决问题，请关闭这个议题，谢谢

**Comment by Richardzhuge** [comment]
@YinCQL 非常感谢您给我这个建议，但是很遗憾修补Meta并没有解决我的问题.......修补Meta后仍然提示这个。不过我想好奇问一下修补这个的作用是什么呢？因为我觉得如果我知道了原理可能会让我离解决问题更进一步。所以能麻烦您解释一下吗？谢谢！

**Comment by YinCQL** [comment]
> @YinCQL 非常感谢您给我这个建议，但是很遗憾修补Meta并没有解决我的问题.......修补Meta后仍然提示这个。不过我想好奇问一下修补这个的作用是什么呢？因为我觉得如果我知道了原理可能会让我离解决问题更进一步。所以能麻烦您解释一下吗？谢谢！

那我可能帮助不了你，你可以加入官方Discord https://discord.com/invite/T5vZU6UyeG 来获取更多帮助（https://github.com/Grasscutters/Cultivation 这个启动器你也可以试试，或许能帮助到你）

**Comment by lniuua** [comment]
补丁分国际服跟国服两种不能混用，请使用正确的补丁修补你的客户端

**Comment by lniuua** [comment]
我遇到过同样的问题，原因是补丁使用错误，国服的客户端使用了国际服的补丁造成的，你可以试试用这个启动器启动游戏https://github.com/gc-toolkit/GenshinLauncher

**Comment by Richardzhuge** [comment]
@YinCQL 好的，不过还是谢谢了，帮我找到了另一个解决思路，我已经加了官方Discord了，不过我貌似不太会在那里发帖.........

**Comment by Richardzhuge** [comment]
@lniuua 好的，我去试试这个启动器，谢谢！

**Comment by KingRainbow44** [comment]
stale issue
