### ISSUE TITLE
能不能加载一个中文语音包？

### ISSUE THREAD

**Issue by AgonySec** [Melledy/Grasscutter#1811]
各位大佬，角色都没有语音，感觉少了点内味，我自己也不会操作，求助

**Comment by kaminosama** [comment]
> 各位大佬，角色都没有语音，感觉少了点内味，我自己也不会操作，求助

这是逆向出来的服务端，还没做完，慢慢等吧

**Comment by ighlES** [comment]
先进官方下好语音

**Comment by Zhaokugua** [comment]
没语音是你游戏没下语音包或者测试服没有语音包，和这个没关系

**Comment by KiminaNatsuki** [comment]
> 没语音是你游戏没下语音包或者测试服没有语音包，和这个没关系
