### ISSUE TITLE
[Bug] Client shown error code 4214 when login

### ISSUE THREAD

**Issue by yangruoyu-yumeisoft** [Melledy/Grasscutter#1820]
Client shown error code 4214 when login.
My client version is OSRELWin3.1.0_R10676272_S10805493_D10772333

**Comment by yangruoyu-yumeisoft** [comment]
It shown "无法连接服务器，请检查网络设置"（Can not connect to server, please check your network settings)

**Comment by simo8102** [comment]
请打客户端补丁

**Comment by HsrShou** [comment]
> 请打客户端补丁

打了2.8的补丁  游戏打不开了  能分享个补丁么？

**Comment by simo8102** [comment]
> > 请打客户端补丁
> 
> 打了2.8的补丁 游戏打不开了 能分享个补丁么？

要打对应版本的 不能3.1打个3.0或者2.8的

**Comment by Asendaushoe** [comment]
用[Cultivation](https://github.com/Grasscutters/Cultivation/blob/main/README_zh-CN.md)

**Comment by 794322460** [comment]
> 

这是啥？ 不能客户端直接链接吗？

**Comment by Asendaushoe** [comment]
> > 
> 
> 这是啥？ 不能客户端直接链接吗？

grasscutters作者做的第三方启动器，可以自动打补丁

**Comment by 794322460** [comment]
> grasscutters作者做的第三方启动器，可以自动打补丁

刚试了Cultivation不行，各种报错，客户端是最新的3.1

**Comment by 794322460** [comment]
Failed to get bg file response: missing field `bg_file` at line 1 column 352720
^ please stop reporting this as an error it's so annoying LMFAO

**Comment by 794322460** [comment]
还有启动的时候：game version is too new xxx，应该说客户端版本比补丁还新吧？

**Comment by yangruoyu-yumeisoft** [comment]
> 请打客户端补丁

Thx, this error has been solved. Use collei_launcher and replace key2 to makes fake UA valid.

**Comment by ouhexi** [comment]
![image](https://user-images.githubusercontent.com/84364479/194694416-8b1e3f09-dec4-4efa-9aad-9ce3ce11e09a.png)
使用Cultivation的时候报了这个错误，应该是要打补丁吧？需要这么操作呢？

**Comment by wjjxl** [comment]
取消注册





---Original---
From: ***@***.***&gt;
Date: Sun, Oct 2, 2022 22:54 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [Grasscutters/Grasscutter] [Bug] Client shown error code 4214when login (Issue #1820)




 
请打客户端补丁
