### ISSUE TITLE
为什么3.0的点了YuanShen.exe没反应呢？

### ISSUE THREAD

**Issue by huangjkl21sadsa** [Melledy/Grasscutter#1822]
服务端那些都是启动好的 代理也挂了 点了就是没反应 把那个补丁恢复了又能进 打了补丁又进不去

**Comment by simo8102** [comment]
> 服务端那些都是启动好的 代理也挂了 点了就是没反应 把那个补丁恢复了又能进 打了补丁又进不去

要打对应版本的 不能3.1打个3.0或者2.8的

**Comment by gucooing** [comment]
呃呃呃，是不是补丁打错了

**Comment by Tangyuan586** [comment]
补丁真难找

**Comment by Zhaokugua** [comment]
补丁打错了，不同版本的补丁都不一样，国服和国际服的也不一样
