### ISSUE TITLE
[Feature Request] templates for creating new users in json 新用户模板

### ISSUE THREAD

**Issue by ytfh44** [Melledy/Grasscutter#1825]
**Is your feature request related to a problem? Please describe.**

I found it difficult to edit the default config(characters weapons etc.)for new users
(I want to do it since i'm running a flavored server)
**Describe the solution you'd like**

use a json file to describe the template status for new users
auto generate it if it's not present
**Describe alternatives you've considered**

write a plugin in java to implement it
**Additional context**

**Comment by Birdulon** [comment]
As far as Grasscutter is concerned, new users should more-or-less match official, and anything extra you want to give them should just be added to the welcome mail config. Anything beyond that should be left to plugins.
