### ISSUE TITLE
[Bug] 无法引用图片

### ISSUE THREAD

**Issue by mxtilx** [Melledy/Grasscutter#1828]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

 
Grasscutter version  1.3.2-dev
 Git Hash  96031865

**Screenshots**

![Screenshot_2022-10-05-19-28-26-96](https://user-images.githubusercontent.com/96869052/194050814-baa30497-8160-4f4b-a65f-a452249ec71f.jpg)
![Screenshot_2022-10-05-19-28-12-81](https://user-images.githubusercontent.com/96869052/194050820-05c5cfea-33ea-437c-8441-756e43dcfb8b.jpg)
在本地打开是可以看见图片的
**Additional context**

**Comment by Birdulon** [comment]
What does this have to do with Grasscutter?

**Comment by mxtilx** [comment]
> What does this have to do with Grasscutter?

你看config.json
![Uploading Screenshot_2022-10-05-20-06-42-46.jpg…]()

**Comment by mxtilx** [comment]
> 这和割草机有什么关系？

你看config.json
![Uploading Screenshot_2022-10-05-20-06-42-46.jpg…]()

**Comment by mxtilx** [comment]
![Screenshot_2022-10-05-20-11-13-49](https://user-images.githubusercontent.com/96869052/194057846-5621a073-1b5e-464d-9605-3a210172d4f8.jpg)

**Comment by TaffyStudio** [comment]
把图片上传到第三方图床再引用链接
