### ISSUE TITLE
[Bug] After changing the ConfigContainer .java in the source code, the compiled grasscutter will get a confi file error when it starts

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1833]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by ERthereal** [comment]
[ConfigContainer.java.txt](https://github.com/Grasscutters/Grasscutter/files/9727906/ConfigContainer.java.txt)
[config.json.txt](https://github.com/Grasscutters/Grasscutter/files/9727911/config.json.txt)

**Comment by akatatsu27** [comment]
Not knowing what you're doing with the source code (and not describing at all what you did) is not a bug. If you're looking to add a feature, make a feature request, or make a PR. For questions regarding writing code for grasscutter you can ask in the development channel of the discord. Please read the bug report form next time.

**Comment by ERthereal** [comment]
> 

sorry
