### ISSUE TITLE
Enabling the special traveller with unique skills

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1835]
In 2.6 there was an activity called Clash of the Lone Blades, 孤剑争逐, which allows traveller to use two unique skills.

It is possible to switch traveller to that version while in the big world? That would be fun!

Yes I wanna play traveller with Physical DMG and parry!

**Comment by KingRainbow44** [comment]
you can look into the different skill depots for the traveler, and set this using something like a command.
