### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by nova452** [Melledy/Grasscutter#1856]
**Is your feature request related to a problem? Please describe.**

SkillParticleGeneration.json is not updated with Nilou, Candace and Cyno.
**Describe the solution you'd like**

Please someone update it, atleast with Nilou...
**Describe alternatives you've considered**

**Additional context**

**Comment by KingRainbow44** [comment]
isn't this a resources issue?

**Comment by KingRainbow44** [comment]
see message above
