### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by azheea** [Melledy/Grasscutter#1861]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**
![843b05cd672a5b311ed7870ff71dbe3f](https://user-images.githubusercontent.com/87923452/195979321-4ea41a16-1d9c-44ee-80f4-83503ccd0822.jpeg)

**Additional context**
读取作为zip的res时出现错误

**Comment by azheea** [comment]
![image](https://user-images.githubusercontent.com/87923452/195979403-7a15fa27-0af5-4a86-862e-912fdac1d1f7.png)

**Comment by Birdulon** [comment]
f3a5bc1 should have solved TextMap cache problems, but a solution for when these happens is to delete the `cache` folder.
