### ISSUE TITLE
[Bug] ：Exception has been thrown by the target of an 对象的目标引发异常

### ISSUE THREAD

**Issue by awaae001** [Melledy/Grasscutter#1866]
服务端版本
grasscutter-1.3.1

本地用户端版本 
国际（GenshinImpact）

使用的补丁文件
![image](https://user-images.githubusercontent.com/108462724/196083433-bb3ee033-6194-4394-bf23-ad7e253d89db.png)

发生的错误
![5%4PXI71HJ90X{}UN203R8V](https://user-images.githubusercontent.com/108462724/196083481-7ffe1afc-5511-433b-83e2-57af40a26f3c.png)

**Comment by Birdulon** [comment]
Can't reproduce, make sure you are using the correct patched `UserAssembly.dll` for your client, using a different version will typically cause this.
