### ISSUE TITLE
Invalid UID

### ISSUE THREAD

**Issue by Rainrain2007** [Melledy/Grasscutter#187]
![image](https://user-images.githubusercontent.com/69844315/164972523-de18d7c4-638c-4bb9-bf7b-85a2bc25bd69.png)

**Comment by alt3ri** [comment]
please, go to discord to ask instead

**Comment by alt3ri** [comment]
> ![image](https://user-images.githubusercontent.com/69844315/164972523-de18d7c4-638c-4bb9-bf7b-85a2bc25bd69.png)

and use account create abc 123
