### ISSUE TITLE
[Bug] 抽卡无法获得角色，角色部分命座不生效

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1870]
GC版本：1.4.0
游戏版本：3.1

现象：
正常抽卡时，抽到的角色无法获得，也无法转化成命座，但是抽到的武器可以正常获得，只有使用/give命令才能获取角色
使用/give avatars lv90 c6命令后，虽然能获得满命的全部角色，但是所有角色的命座3和5不生效，天赋等级不变，但是同时其他命座正常生效

**Comment by 2y8e9h22** [comment]
修复一下这个bug就好了
