### ISSUE TITLE
How do I uninstall Grasscutter?

### ISSUE THREAD

**Issue by DewDropTales** [Melledy/Grasscutter#1873]

**Comment by chiqors** [comment]
What do you mean? Just remove the grasscutter files alongside with grasscutter database on your mongodb. Close this issue, if that's what you wanted.

**Comment by 2y8e9h22** [comment]
😉

**Comment by TotallyNotOndre** [comment]
![uninstall-genshin-impact](https://user-images.githubusercontent.com/40639199/197344910-96508be3-99bb-41d2-85bf-b31146a43ae6.gif)
