### ISSUE TITLE
[Bug] Can't get namecards from charater's fetter level 无法正确领取角色的好感度奖励（名片）

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1882]
GC: v1.4.2
Game: v3.1
Resources: https://github.com/tamilpp25/Grasscutter_Resources

在使用命令/setfetterlevel 10使角色好感度满之后，会提示领取奖励，但是点击领取后无法获得名片，在设置名片里会显示“新”但是依然显示是锁着的，用/give命令也无法解锁名片

强调：我测试用的是最新的GC release版，最新的游戏客户端（国服和海外都测了），最新的资源文件（GC官方discord推荐的），但是问题依然存在，所以可以相信是GC的bug

**Comment by awaae001** [comment]
好像是资源文件的问题，请保持资源文件最新

**Comment by 909101** [comment]
我用最新的资源文件测试过了，问题依然存在

我用的资源文件是GC Discord里面提供的链接：https://github.com/tamilpp25/Grasscutter_Resources

**Comment by 909101** [comment]
经过测试，1.4.2版本的GC依然有这个问题
