### ISSUE TITLE
[Bug]我在使用 .\gradlew jar # 编译时，它出现错误

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1893]
**Describe the bug**

**Which branch did you use?**
我在使用 .\gradlew jar # 编译时，它出现了以下错误:
> Configure project :
Publishing to 4benj-maven

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> 错误: 无效的源发行版：17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
**Screenshots**

![QQ截图20221024175458](https://user-images.githubusercontent.com/110032808/197502170-fbfcbd12-1231-4bb7-8f31-f013c32cd2ab.png)

**Comment by ghost** [comment]
我已经安装了jdk-17.0.4.1_windows-x64_bin，但它还是会报错！

**Comment by Birdulon** [comment]
Can you post the output of `java -version`? It might be running an older version on the same machine even though you've installed `jdk-17.0.4.1`.

**Comment by YOYSALENGLI** [comment]
![QQ截图20221024194411](https://user-images.githubusercontent.com/110032808/197518526-030173eb-6436-420f-b255-714cdc50322a.png)
![QQ截图20221024194529](https://user-images.githubusercontent.com/110032808/197518535-7494fc83-3da7-46ac-8004-3e0e92ec10ab.png)
是这个吗？

**Comment by YOYSALENGLI** [comment]
还是是jdk-17.0.4.1的问题！

**Comment by ghost** [comment]
重新安装，就好了
