### ISSUE TITLE
[Feature Request] Looking forward to updating GadgetSpawns and Spawns

### ISSUE THREAD

**Issue by ShinaKaria** [Melledy/Grasscutter#1896]
Now we can get data of 3.1~4.0
The lua file data is in it
Can someone update GadgetSpawns.json and Spawns.json ?

现在我们可以获得3.1~4.0的数据
lua文件数据就在其中
是否有人可以更新GadgetSpawns.json 和 Spawns.json ?

**Comment by Birdulon** [comment]
Admitting to using leaked resources in a project like this is would make GitHub much less sympathetic to us if we ever get another DMCA takedown request. Please don't ever say such things.
Spawns will be updated eventually.

**Comment by ShinaKaria** [comment]
ok, i don't understand the rule,plz allow me to apologize

**Comment by ShinaKaria** [comment]
> Admitting to using leaked resources in a project like this is would make GitHub much less sympathetic to us if we ever get another DMCA takedown request. Please don't ever say such things. Spawns will be updated eventually.

ok, i don't know the rule,plz allow me to apologize
