### ISSUE TITLE
[Bug] 抽卡详情出现问题

### ISSUE THREAD

**Issue by xia0ji233** [Melledy/Grasscutter#1906]
如题，在我下载的最新的release中，resource 也是 来自 https://github.com/tamilpp25/Grasscutter_Resources 中的资源，但是打开卡池详情和历史记录的时候，卡池显示全俄文，历史记录显示server error，我在 config.json中都配置了中文，但是还是无济于事。
![Uploading image.png…]()

![Uploading image.png…]()

**Comment by Birdulon** [comment]
Should be fixed by c21d216d8d88a3fbb537f85b7692eff55c12a75f and d7af52f94bbfbd57fae223c99c0ead03bf277f4a
