### ISSUE TITLE
[Feature Request] I have the real source code of Genshin Impact

### ISSUE THREAD

**Issue by jipuweimeng** [Melledy/Grasscutter#1910]
I'm chinese， I do not know English ，I have the real source code of Genshin Impact， I will not get ，I can send you the source code，Hope you guys get it up and running， Below is the Baidu link
[LINK DELETED]

**Comment by alt3ri** [comment]
yes, and no one cares

**Comment by alt3ri** [comment]
not related

**Comment by Birdulon** [comment]
Regardless on how anyone wishes copyright law would work, Grasscutter can't and won't use leaked proprietary backend data. Do whatever you want on your own repos and get DMCA'd off of Github, but don't try to take Grasscutter with you.
