### ISSUE TITLE
[Bug] When Grasscutter is started without config.json, Grasscutter automatically creates a config and starts successfully, but after closing Grasscutter, running Grasscutter again will report a config.json error.

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1915]
**Did you look for other closed issues that have the same problem?**

No
**Describe the bug**

When Grasscutter is started without config.json, Grasscutter automatically creates a config and starts successfully, but after closing Grasscutter, running Grasscutter again will report a config.json error. 
I'm wondering if it's my config.json's problem
**Which branch did you use?**

development
**Screenshots**

![1](https://user-images.githubusercontent.com/58130955/198878627-9161420a-91ec-4d6b-baa7-5f13d5e6812b.png)
![2](https://user-images.githubusercontent.com/58130955/198878633-cc43326d-2a60-4acb-afe6-893adc260a17.png)
![3](https://user-images.githubusercontent.com/58130955/198878635-33b32185-fc54-4f6f-b5a6-2e8f0a60c187.png)
![4](https://user-images.githubusercontent.com/58130955/198878636-5d38b793-f689-4b9b-92e0-fece6fff35e8.png)
![5](https://user-images.githubusercontent.com/58130955/198878637-b20467c2-fd87-4c94-9f4e-97618d13d6c9.png)

**Additional context**

My config
[config.json.txt](https://github.com/Grasscutters/Grasscutter/files/9895809/config.json.txt)

**Comment by ERthereal** [comment]
Answer again "Did you look for other closed issues that have the same problem?" I searched for , but I couldn't find it

**Comment by Birdulon** [comment]
![image](https://user-images.githubusercontent.com/5397662/198880353-294386aa-e2ae-4c59-a021-ee1469bc5e79.png)
???

**Comment by ERthereal** [comment]
> UTF-8 encoding is needed here because this is Chinese

**Comment by Birdulon** [comment]
The answer is the same as #1833, changing the source code and getting errors from doing that is not a bug. In your case, you can probably just use `java -Dfile.encoding=UTF-8 -jar grasscutter.jar` to ensure that it will write your config in UTF-8 encoding.

**Comment by ERthereal** [comment]
> 答案与#1833相同，更改源代码并从中获取错误不是错误。在您的情况下，您可能只是用来确保它将以 UTF-8 编码编写您的配置。`java -Dfile.encoding=UTF-8 -jar grasscutter.jar`

thank
