### ISSUE TITLE
[Feature Request] Automatically run commands after player first login or every login 在玩家首次登录后或者每次登录后自动运行命令

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1920]
希望添加个功能，能在玩家首次登录后或者每次登录后自动运行一些命令，这些命令可以以单独的json保存，或者直接保存在config.json中

**Comment by ChisatoNishikigi73** [comment]
感谢你的建议，但是我只把它写在了我自己的private hub里， 因为我觉得gc并不会通过我的prXD
github.com/LycoReco-Cafe/
github.com/LycoReco-Cafe/Grasscutter-Chisato-dev

**Comment by 909101** [comment]
非常感谢，但是你的dev的链接我打开是404

要不你尝试pr一下吧，我看GC对待之前的pr态度挺好的，也会帮忙一起改

**Comment by Birdulon** [comment]
This sort of functionality is better left to plugins.

**Comment by ChisatoNishikigi73** [comment]
> 非常感谢，但是你的dev的链接我打开是404
> 
> 要不你尝试pr一下吧，我看GC对待之前的pr态度挺好的，也会帮忙一起改

因为是private的，如上，我以后会公开仓库在https://github.com/LycoReco-Cafe/Grasscutter-Chisato
