### ISSUE TITLE
[Bug] Can't get reward from charater's fetter level 无法获得角色的好感度奖励

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1921]
GC: v1.4.2
Game: v3.1
Resources: https://github.com/tamilpp25/Grasscutter_Resources

角色满好感度之后会提示领取奖励，但是点击领取后无法获得名片，在设置名片里会显示“新”但是依然显示是锁着的，用/give命令也无法解锁名片

强调：我测试用的是最新的GC release版，最新的游戏客户端（国服和海外都测了），最新的资源文件（GC官方discord推荐的），但是问题依然存在，所以可以相信是GC的bug

**Comment by Birdulon** [comment]
Duplicate (bump attempt?) of #1882
