### ISSUE TITLE
[Bug] Can't change player's element with Statue of The Seven 七天神像无法切换主角的元素

### ISSUE THREAD

**Issue by 909101** [Melledy/Grasscutter#1928]
GC: v1.4.2
Game: v3.1
Resources: https://github.com/tamilpp25/Grasscutter_Resources

Can't change player's element with Statue of The Seven 七天神像无法切换主角的元素七天神像无法切换主角的元素

Please fix it 请修复这个bug

**Comment by Night12138** [comment]
You can use this plugin to switch traveler element https://github.com/Penelopeep/SwitchElementTraveller
你可以用这个插件切换旅行者的元素
Download the release, and put it into your plugin folder, then input `se @<UID> anemo|geo|electro|dendro` to console that change traveler element.
下载插件，放进plugin目录，执行`se @<UID> anemo|geo|electro|dendro`命令切换旅行者元素

**Comment by ghost** [comment]
Not fixed yet, I suggest using the plugin which the guy above my reply recommends.
