### ISSUE TITLE
Failed to connect to MongoDB

### ISSUE THREAD

**Issue by lyt88852** [Melledy/Grasscutter#193]
![2ZGEJTACCB~NX7$RKH)SBAA](https://user-images.githubusercontent.com/104312758/164982777-6984a11a-3915-47c1-9b6d-2816209f73cd.png)
What do I need to do？

**Comment by 1shin-7** [comment]
This is not because grasscutter cannot connect to the database, but there is no data in the `avatar` table

**Comment by DerivativeMarmot** [comment]
create an account and log in first

**Comment by KingRainbow44** [comment]
this isn't a support forum, go to the discord for support.
