### ISSUE TITLE
[Feature Request] Size restriction for log file 限制日志文件大小

### ISSUE THREAD

**Issue by Qimme** [Melledy/Grasscutter#1930]
Hi, I was using GC1.4.1 on Linux. I ran it using this command:_nohup java -jar grasscutter-1.4.1-dev.jar > /dev/null 2>&1 &_.The service ran successfully but there were some error messages being written to the log file constantly and rapidly, the file became so large that it swallow all my disk. I fixed it by using another command to run GC. Maybe there should be a size restriction for log file.
我之前在linux上用这个命令_nohup java -jar grasscutter-1.4.1-dev.jar > /dev/null 2>&1 &_跑GC1.4.1的时候有一段报错信息不断写入日志导致磁盘被占满。我之后用另一个命令运行了GC解决了这个问题。是不是可以加一个限制日志文件大小的功能？

**Comment by Birdulon** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/5397662/199876840-b5707bb5-d085-4b7e-b65a-5bb81a53fad3.png">

Set to `false` if you want to run with something like `nohup` which provides no console.

**Comment by Birdulon** [comment]
Logging problem fixed by 0fb7d50acd4d3851a1c9a3531240ab6e46cb7759
