### ISSUE TITLE
[Bug] java.lang.NullPointerException

### ISSUE THREAD

**Issue by yuhkix** [Melledy/Grasscutter#1931]
**Description of the bug**
Console output: "Cannot invoke "emu.grasscutter.game.battlepass.BattlePassManager.triggerMission(emu.grasscutter.game.props.WatcherTriggerType, int, int)" because the return value of "emu.grasscutter.game.player.Player.getBattlePassManager()" is null" which causes me to not get back into the game for some reason and I can't seem to fix it even with the current released 1.4.2 version.

**Branch I used?**
Grasscutter version: 1.4.3-dev
Github Hash: e8930e92

**Screenshots**
![image](https://user-images.githubusercontent.com/74727805/199802860-3ea979a3-c6a8-4107-b020-7683e2377781.png)

**Additional context**
Before this error occured I changed some stuff in the config.json regarding the server account and the mail new users get.

**Comment by KingRainbow44** [comment]
This is the result of upgrading to a newer version of Grasscutter while your database remains outdated. The current (albeit not the best) solution is to remove the entry for that account and recreate it.
