### ISSUE TITLE
[Bug] 地图部分建筑物无法破坏

### ISSUE THREAD

**Issue by Proton-official** [Melledy/Grasscutter#1934]
版本3.2，地图中的木罐，木箱，枯萎的藤蔓，无法破坏。锁住的宝箱击杀怪物后也不会解锁。

**Comment by millet6** [comment]
E:\3.2服务器\grasscutter\ config.json    修改内容 "enableScriptInBigWorld": true,

**Comment by Proton-official** [comment]
> E:\3.2服务器\grasscutter\ config.json 修改内容 "enableScriptInBigWorld": true,

非常感谢！
