### ISSUE TITLE
[Bug] 深渊5层以后下半打不了，只要是守护地脉不被破坏的也打不了

### ISSUE THREAD

**Issue by lclty** [Melledy/Grasscutter#1935]
深渊路径分叉的地方没法打下半
并且深渊地脉守护不被破坏也没法打 打完怪根本不过

**Comment by yehuoshun** [comment]
这个好像是要有lua脚本的

**Comment by jiellll1219** [comment]
实际上并不怎么依赖lua脚本，这个问题属于jar核心的逻辑问题
It doesn't actually rely much on lua scripts, which is a logical problem at the core of the jar

**Comment by jiellll1219** [comment]
实际上并不怎么依赖lua脚本，这个问题属于jar核心的逻辑问题
It doesn't actually rely much on lua scripts, which is a logical problem at the core of the jar
