### ISSUE TITLE
Can't run on the server

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#195]
I want to run on the server. After I deployed, the 443 port can be used, but 22102 cannot be used. I still report an error 4206 after modifying Publicip for the server IP. It can log in, but it cannot be updated.I have already opened all ports on the firewall
![image](https://user-images.githubusercontent.com/44462661/164984680-639f4072-3f21-459d-a488-1a5fe99ddf1a.png)
![image](https://user-images.githubusercontent.com/44462661/164984685-31ddeee9-2c60-494d-99cc-32e26ef172fa.png)
![image](https://user-images.githubusercontent.com/44462661/164984692-6be7fa91-48f9-4171-a5e2-efe8f66922e5.png)

**Comment by DenSwitch** [comment]
replace the keystore.p12 with the [dev](https://github.com/Grasscutters/Grasscutter/blob/development/keystore.p12) one

**Comment by KingRainbow44** [comment]
this isn't a support forum, go to the discord for support.
