### ISSUE TITLE
[Bug] Exception in thread "main" java.lang.NullPointerException ...

### ISSUE THREAD

**Issue by ouroboros-1w** [Melledy/Grasscutter#1950]
**Did you look for other closed issues that have the same problem?**
Yes.

**Describe the bug.**
The server crashs when starting. I attach a screenshot.
Console Output:
Exception in thread "main" java.lang.NullPointerException: Cannot read field "strings" because "textstrings[j]" is null

**Which branch did you use?**
1)
  Grasscutter version: 1.4.3-dev
  Git Hash: 4d8caf5
2)
  Grasscutter version: 1.4.3
  Git Hash: 5c4c62c1

In both cases, the _version of the game and resources — 3.2_

**Screenshots**
1) With Grasscutter 1.4.3-dev
![Скриншот 16-11-2022 16 27 36](https://user-images.githubusercontent.com/112094971/202156417-46b90405-2151-40a5-afb4-2a65b7be4357.png)
2) With Grasscutter 1.4.3
![Скриншот 16-11-2022 16 32 10](https://user-images.githubusercontent.com/112094971/202157415-ff10442c-b1fa-4ae2-98d1-e730b54e7481.png)

**Comment by obronca** [comment]
delete cache folder in your grasscutter folder

**Comment by ouroboros-1w** [comment]
> delete cache folder in your grasscutter folder

Thx! (it turns out a similar problem has already been discovered, but I couldn't find it by keywords).
