### ISSUE TITLE
[Feature Request] Command to identify nearby entity ID's

### ISSUE THREAD

**Issue by SirDarwin** [Melledy/Grasscutter#1953]
A few days ago I had finally found the ID for Anemo Rings (70350333 but there are multiple of them), but not before spending a good 30 minutes trying to find it. Because before, I had to figure out it was in GadgetExcelConfigData.json in ExcelBinOutput, all of this was assuming it was a gadget, which I was not certain of. All of this could have been prevented if I had a way to identify which entities are around me, as there are plenty of Anemo Rings in the world.

I don't know if it's possible but it would go something like this:
/identify [monster|gadget|character|item] [closest]

"closest" being, well, the closest entity to your location. So if I wanted to find all the monsters near me, I would type:

/identify monster

and would get back:

> Current nearby monsters:
Hilichurl (21010101)
Hydro Slime (20011001)
Ruin Guard (24010101)
Treasure Hoarder Scout (25010201)

Of course, the enemy names might not be written as seen in game internally, so that might have to be looked at. As long as the names are fairly easy to understand I don't think there should be a problem, and worst case scenario you could type "closest" next to an enemy to make sure you have it right.

Also /identify can be shortened to /id

**Comment by KingRainbow44** [comment]
this is one of those things which are probably better off in a plugin (plugin developers this is your callout)

**Comment by NotThorny** [comment]
A little late to the party, but this has already existed as a plugin for a few months. 'Enemies' is one of the types you can find near you, among many others https://github.com/snoobi-seggs/RevealSurroundingsPllllugin
