### ISSUE TITLE
Require Login : https://git.crepe.moe/tamilpp25/Grasscutter_Resources

### ISSUE THREAD

**Issue by Musicminion** [Melledy/Grasscutter#1969]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

https://git.crepe.moe/tamilpp25/Grasscutter_Resources 
This url require login, and I can't register

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by akbaryahya** [comment]
try https://gitlab.com/tamilpp25/Grasscutter_Resources

**Comment by 4Benj** [comment]
Repo taken down due to DMCA request

**Comment by mcat1997** [comment]
404 https://gitlab.com/tamilpp25/Grasscutter_Resources

**Comment by Lynricsy** [comment]
> Repo taken down due to DMCA request

So how can I register the new site?It says "Email is not allowed for sign-up. Please use your regular email address. Check with your administrator." repeatedly after I tried all of my emails.

**Comment by 4Benj** [comment]
> > Repo taken down due to DMCA request
> 
> So how can I register the new site?It says "Email is not allowed for sign-up. Please use your regular email address. Check with your administrator." repeatedly after I tried all of my emails.

You don’t. It’s asking for login because the repository has been taken down and signup has been disabled. Please refer to the discord forum for support (and use the search bar to search for your issue before opening a new one).
