### ISSUE TITLE
How to install grasscutter on ios?

### ISSUE THREAD

**Issue by n6mi44** [Melledy/Grasscutter#197]
Can someone help me how to do it

**Comment by mjh316** [comment]
Have you tried following the wiki at all? https://github.com/Grasscutters/Grasscutter/wiki
You can join the discord and ask in the #support channel if you have issues. https://discord.gg/T5vZU6UyeG
Please don't create an issue just for a handholding request, it'll clog up the actual issue list for the code and repository.

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
