### ISSUE TITLE
when will update the 3.3 version？

### ISSUE THREAD

**Issue by ironmn** [Melledy/Grasscutter#1974]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Kio-td** [comment]
Please don't bother the developers with asking for updates.
It takes time to create these things, especially when a certain game company moves the goal post with every update.
![image](https://user-images.githubusercontent.com/7786316/206716697-845f85b5-6163-4475-b19a-d29998984daf.png)

**Comment by estlio** [comment]
> 请不要打扰开发人员要求更新。创建这些东西需要时间，尤其是当某个游戏公司在每次更新时移动目标柱时。 ![image](https://user-images.githubusercontent.com/7786316/206716697-845f85b5-6163-4475-b19a-d29998984daf.png)

support
