### ISSUE TITLE
[Feature Request] Acknowledge X-Real-IP

### ISSUE THREAD

**Issue by Kio-td** [Melledy/Grasscutter#1975]
**Is your feature request related to a problem? Please describe.**

Users are silly. They do silly things. We use their IP Addresses to keep them accountable with silly things by preventing them from connecting. However, anyone with a reverse proxy knows, this request changes to 127.0.0.1 unless programs are specifically listening for an X-Real-IP header.

**Describe the solution you'd like**

When reverse proxying, it's important servers get the correct information, but it's also bad if it's improperly configured. If you're using a reverse proxy, then the config should include the abilty to accept X-Real-IP headers.

**Describe alternatives you've considered**

Personally, I like using domains, and reverse proxies make load balancing such a sweet, simple task. The only alternative I can see is getting a dedicated container _just_ for grasscutter, and pointing my subdomain to that. *that's not fun.*

**Comment by KingRainbow44** [comment]
implemented in `ff421c0` on `unstable`
