### ISSUE TITLE
[Feature Request] UserAssembly.dll、深境螺旋

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#1976]
# genshin version: 3.3
### 二、Wiki 中能否增加 `UserAssembly.dll` 下载地址？

**Comment by awaae001** [comment]
补丁更换了形式
https://github.com/34736384/RSAPatch
不在是UA补丁了
你也可以使用特殊的启动器
https://github.com/gc-toolkit/Launcher
它自带补丁

附
深境螺旋还要等一会（估计）

**Comment by mhtwcnm1** [comment]
> 补丁更换了形式 https://github.com/34736384/RSAPatch 不在是UA补丁了 你也可以使用特殊的启动器 https://github.com/gc-toolkit/Launcher 它自带补丁
> 
> 附 深境螺旋还要等一会（估计）

请问这个补丁怎么使用，看不懂readme

**Comment by awaae001** [comment]
> 

补丁工具
https://github.com/34736384/RSAPatch
打了就可以进去了

中国用户可用
https://www.123pan.com/s/gk5KVv-zD8A3
补丁下载链接
放在游戏Genshin Impact\Genshin Impact Game 目录下，记得备份原有文件
启动代理和游戏，看到CMD与游戏一起打开并运行即可

**Comment by mhtwcnm1** [comment]
謝謝

awaaer ***@***.***> 于2022年12月27日周二 23:37写道：

**Comment by mintmango4** [comment]
[gc-toolkit/Launcher]有人有这个启动器的档案吗,跪求

**Comment by awaae001** [comment]
没有了，被删了
只能自己打补丁

**Comment by awaae001** [comment]
可以参考#2020

**Comment by Sankyu-3399** [comment]
> [gc-toolkit/Launcher]有人有这个启动器的档案吗，跪求

http://sankyu.pazaru39.ltd:201/down/VjOi3uSTr1Zz.zip
我这里有一份备份，但不是最新版本。
