### ISSUE TITLE
[Bug] 3.3版本中卡池Banners.tsj无法正常加载

### ISSUE THREAD

**Issue by mlmk6698** [Melledy/Grasscutter#1979]
游戏内提示资源加载失败，但是已经正确加载卡池数量(可以看出已经加载)但卡池内容无法加载

**Comment by wwg-1** [comment]
请问您如何进入到3.3版本,使用哪个jar?

**Comment by mcoi-dev** [comment]
同意++

**Comment by estlio** [comment]
> 请问您如何进入到3.3版本,使用哪个jar?

https://github.com/Grasscutters/Grasscutter/pull/1981

**Comment by wwg-1** [comment]
> > 请问您如何进入到3.3版本，使用哪个jar？
> 
> #1981

感谢

**Comment by mlmk6698** [comment]
自行编译的3.3版本jar

**Comment by simo8102** [comment]
[Banners.zip](https://github.com/Grasscutters/Grasscutter/files/10393763/Banners.zip)
下载并解压本文件到data目录下 如果目录下有Banners.tsj请删除它
