### ISSUE TITLE
[Document] Add reference for the flow diagram

### ISSUE THREAD

**Issue by WetABQ** [Melledy/Grasscutter#1982]
This [diagram](https://github.com/Grasscutters/Grasscutter/wiki/Resources#client-connection--auth-flowchart) is excerpted from 
 the blog that is licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), it should add a reference to the original source [原神 2.8 KCP 验证密钥交互流程解析与流量解密](https://sdl.moe/post/magic-sniffer/)

**Comment by KingRainbow44** [comment]
added to wiki
