### ISSUE TITLE
[Bug] Using the announcement command [/a] is invalid

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#1990]
https://user-images.githubusercontent.com/58130955/209418768-7d1dad44-a275-42bb-8466-6de72ca5fdf3.mp4

**Comment by ERthereal** [comment]
Because GitHub can only upload files up to 10MB, the video is slightly shorter
I type [/a y] in the chat box and prompt me [Send an announcement successfully, you can revoke it by /a revoke 52432.] But nothing happens right above the game interface

**Comment by awaae001** [comment]
有没有可能
你没有填写内容或内容太短？

**Comment by ERthereal** [comment]
> 有没有可能 你没有填写内容或内容太短？

no
