### ISSUE TITLE
 [Bug] mona's skin pact of stars and moon 

### ISSUE THREAD

**Issue by 961241279** [Melledy/Grasscutter#2004]
I use the command:  /give 340008 x1 lv1 
to obtain the mona's new skin, but it cant work.
other skins yet.

**Comment by NotThorny** [comment]
Costume unlocks are based on your resources. You need resources with the skinId fields fixed/de-obfuscated, which both Yuuki resources and tamilpp resources should have if you were to update your resources now, whereas when 3.3 released they were not working correctly. 

https://git.crepe.moe/grasscutters/Grasscutter_Resources
OR 
https://gitlab.com/yukiz/GrasscutterResources/-/tree/3.3

![GenshinImpact_7zrT0UKn92](https://user-images.githubusercontent.com/107363768/210187988-b0e1f0d9-2787-44c9-843b-d3057145e284.png)

![GenshinImpact_746iOWrBX9](https://user-images.githubusercontent.com/107363768/210187991-643c229a-56df-4c88-9875-5de02619a5de.png)

**Comment by 961241279** [comment]
![image](https://user-images.githubusercontent.com/45302994/210190906-74a49a62-35f7-42fd-a50c-84eee7bc024e.png)
I updated resources just now. but faced such a problem

**Comment by 961241279** [comment]
How to install this outfit only, because of no need to other resources.

**Comment by 961241279** [comment]
I need both resources, but how to combine two resources of yuuki and tamilpp?
which should be chosen to overwrite another?

**Comment by NotThorny** [comment]
> ![image](https://user-images.githubusercontent.com/45302994/210190906-74a49a62-35f7-42fd-a50c-84eee7bc024e.png) I updated resources just now. but faced such a problem

You need to delete the "cache" folder when changing resources. 

You should only need either tamilpp or yuuki resources (not both), tamilpp should be working already on their own, and yuuki shows an update that was supposed to fix it.

If it isn't working right then just use tamilpp from https://git.crepe.moe/grasscutters/Grasscutter_Resources and the only file that matters for this issue with costumes is AvatarCostumeExcelConfigData.json in ExcelBinOutput which should be working for both.

**Comment by 961241279** [comment]
thanks, my problem solved
