### ISSUE TITLE
[Bug] WARN:emu.grasscutter.server.http.HttpServer [Dispatch]

### ISSUE THREAD

**Issue by WenBing2078** [Melledy/Grasscutter#2005]
When I run grasscutter, it prompts for a missing SSL certificate and downgrades to http. 

19:08:04 <WARN:HttpServer> [Dispatch] 未找到 SSL 证书！已降级到 HTTP 模式
log:2023-01-02T00:30:34Z <WARN:emu.grasscutter.server.http.HttpServer> [Dispatch] 
Related Functions：SslContextFactory.Server sslContextFactory = new SslContextFactory.Server();

![image](https://user-images.githubusercontent.com/109894308/210227359-755a0875-51bd-4c37-b4be-1159fddfeca4.png)

I was playing smoothly on my local server in 3.2, but when I updated to 3.3，grasscutter kept prompting ： SSL certificate not found! Downgraded to HTTP mode
I tried many things but it still prompted that it couldn't find an SSL, so I was going to apply for a free SSL certificate and then the agency prompted me that I needed to verify the domain name. I'm really cracking up，I just want to experience the game locally and applying for an SSL certificate requires strict verification of the domain name.

![image](https://user-images.githubusercontent.com/109894308/210227500-80956b5a-2483-4bbb-ad2a-3225932bc5e8.png)

**Comment by WenBing2078** [comment]
127.0.0.1:10427: server connect 127.0.0.1:443
127.0.0.1:10427: Server TLS handshake failed. The remote server does not speak TLS.
127.0.0.1:10427: POST https://127.0.0.1/log
 << The remote server does not speak TLS.
127.0.0.1:10427: server disconnect 127.0.0.1:443

![image](https://user-images.githubusercontent.com/109894308/210227619-6de0a814-1ef6-452a-b7d3-effc32fa12fe.png)


When grasscutter downgrades to http，proxy server: “The remote server does not speak TLS.”

**Comment by WenBing2078** [comment]
I'm really not sure if the lack of https is due to SSL certificates. Because in version 3.2 I could use grasscutter very smoothly and at that time I didn't know what SSL was until now, well, SSL (Secure Sockets Layer) is a protocol for establishing secure links between networked computers. But applying for an SSL is just too complicated

**Comment by awaae001** [comment]
你可以重新下载 .P12 证书
https://raw.githubusercontent.com/Grasscutters/Grasscutter/development/keystore.p12

**Comment by KingRainbow44** [comment]
place the keystore.p12 in the same directory as your grasscutter installation.
