### ISSUE TITLE
[Bug] Can't login in game

### ISSUE THREAD

**Issue by 961241279** [Melledy/Grasscutter#2012]
GC-data:3.3
GC-resources:3.3
Game:3.3
I used RSA patch (by creating "version.all') and proxy to link to GC.
My account was loaded successfully.
![OM}1LJ6NQEF@SX34(X8OJ%7](https://user-images.githubusercontent.com/45302994/210911518-f567ba42-af59-48a8-9f46-3d6d82ebbfa1.png)

However, when I entered the door, it kept white screen and asked me to login again after several minutes.
When I entered again, the problem remained.
Server's outputs are as following:
![{{7`YXUUQQL8X9~O)BN9XXM](https://user-images.githubusercontent.com/45302994/210911569-dd558bcb-7667-43f8-afc0-295f5f38bdb4.png)
![{1AP 1 T`QS(3DUX7@7)L)F](https://user-images.githubusercontent.com/45302994/210911582-d9461fa3-b21a-440f-a4f9-24648da95a97.png)

If I create the "PublicKey.txt" and use GC public key, the problem will remain yet.

**Comment by 961241279** [comment]
![{{7`YXUUQQL8X9~O)BN9XXM](https://user-images.githubusercontent.com/45302994/210911703-3bbd3cfa-ddfc-4880-909a-a3110d4cb903.png)

**Comment by 961241279** [comment]
when the game kept white screen, the sever printed like this

**Comment by MartinMatianyi** [comment]
Same issue! please check!

**Comment by 961241279** [comment]
due to version inconsistency，closed.
