### ISSUE TITLE
[Feature Request] Add new characters to old versions 

### ISSUE THREAD

**Issue by 961241279** [Melledy/Grasscutter#2013]
I want to play Alhaitham in 3.3 version in the future.
I am playing 3.2 version now.
How to add Faruzan in current version?

**Comment by mcoi-dev** [comment]
(uncertain)  Emm,first of all in 3.3（or even older version） , there isn't a model for Alhatham in the game, so i think you can't do it...
我记得3.3应该是没有艾尔海森的模型的吧，应该不行
