### ISSUE TITLE
wiki problem with version

### ISSUE THREAD

**Issue by xiaoyu824873** [Melledy/Grasscutter#202]
1.can not find [gi-bin-output](https://github.com/radioegor146/gi-bin-output) with version 2.6
![image](https://user-images.githubusercontent.com/21293584/164992266-cba6f1e8-2106-4fa3-afe7-3b4c1810721e.png)
2.use [GenshinData](https://github.com/Dimbreath/GenshinData) and will cause error,like this ,  can login game,but there is no teleport and mission
![image](https://user-images.githubusercontent.com/21293584/164992375-4692b23b-4bbb-4698-8304-7877e2da9177.png)

Please help me,Thanks!

**Comment by memetrollsXD** [comment]
1. Use 2.5.52
2. Teleport and embryo is binoutput issue
3. Quests aren’t implemented
4. if your artifact stats don't work put this in your resources/ExcelBinOutput folder

https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json

https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json

**Comment by xiaoyu824873** [comment]
ok,thanks a lot
