### ISSUE TITLE
[Bug] 登录流程加载资源失败，客户端错误码4214

### ISSUE THREAD

**Issue by punchio** [Melledy/Grasscutter#2020]
**Describe the bug**

17:39:37 <INFO:Grasscutter> 正在启动 Grasscutter...
17:39:37 <INFO:Grasscutter> 游戏版本：3.3.0
17:39:37 <INFO:Grasscutter> Grasscutter 版本：1.4.6-dev-beeaad00
17:39:37 <INFO:ResourceLoader> 正在加载 resources...
17:39:39 <INFO:ResourceLoader> 完成加载 resources。
17:39:39 <INFO:Language> Loading cached 'TextMaps'...
17:39:41 <INFO:HttpServer> [Dispatch] Dispatch 服务器启动于 127.0.0.1:443
17:39:41 <INFO:GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。
        如果你是付费购买的，那你已经被骗了。
        项目地址：https://github.com/Grasscutters/Grasscutter
17:39:41 <INFO:GameServer> 游戏服务器启动于 127.0.0.1:22102
17:39:41 <INFO:Grasscutter> 加载完成！输入 "help" 查看命令列表
17:39:48 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试通过 token 登录
17:39:48 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 已通过 token 登录，UID 为 10001
17:39:48 <INFO:DispatchHandler> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试登录
17:39:48 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 成功交换 token
17:39:48 <INFO:DispatchHandler> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试登录
17:39:48 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa

**Which branch did you use?**
  Grasscutter version: Grasscutter version: 1.4.6-dev-beeaad00

**Screenshots**
![image](https://user-images.githubusercontent.com/1528917/212033019-cd00c286-7046-4e49-9883-934b2e85c5bf.png)

**Additional context**
账号登录了，但是登录游戏失败了。显示访问区域信息失败

**Comment by mcoi-dev** [comment]
我也遇到了这个情况
3.3版本和服务端完全对应
就是不知道是怎么回事
别人用代理一搞就上去了，我代理是上去了，但是就是4214，也不知道是国际服的问题还是什么问题。
我各种代理都试过了，fidder，大神手搓的，mixproxy，等等

**Comment by banto6** [comment]
@punchio @mcoi-dev 

4214可参考这个，亲测成功

https://github.com/Grasscutters/Grasscutter/issues/2001#issuecomment-1365989469

**Comment by mcoi-dev** [comment]
> @punchio @mcoi-dev
> 
> 4214可参考这个，亲测成功
> 
> [#2001 (comment)](https://github.com/Grasscutters/Grasscutter/issues/2001#issuecomment-1365989469)

我试过，fidder代理的，是有cmd窗口，但是就是不行，还是4214

**Comment by awaae001** [comment]
？

**Comment by zxymiku** [comment]
4214是你没path客户端

**Comment by zxymiku** [comment]
> 4214是你没path客户端

可以参考这个项目path客户端https://github.com/Grasscutters/Cultivation

**Comment by xszhappy** [comment]
求该版本的grasscutter：1.4.6-dev-beeaad00，谢谢

**Comment by mcoi-dev** [comment]
> > 4214是你没path客户端
> 
> 可以参考这个项目path客户端https://github.com/Grasscutters/Cultivation

但是这个好像没有3.3的吧，而且今天下午4点都3.4了

**Comment by mcoi-dev** [comment]
> @punchio @mcoi-dev
> 
> 4214可参考这个，亲测成功
> 
> [#2001 (comment)](https://github.com/Grasscutters/Grasscutter/issues/2001#issuecomment-1365989469)

话说我手滑更新了3.4怎么办啊，有大佬分享一下3.3文件吗？

网盘可以用这个：pan.huang1111.cn

**Comment by awaae001** [comment]
据我所知rsa补丁在官方没有更换它的加密方式之前，无论版本更新是照样可以使用的。

**Comment by zxymiku** [comment]
> > @punchio @mcoi-dev
> > 
> > 4214可参考这个，亲测成功
> > 
> > [#2001 (comment)](https://github.com/Grasscutters/Grasscutter/issues/2001#issuecomment-1365989469)
> 
> 话说我手滑更新了3.4怎么办啊，有大佬分享一下3.3文件吗？
> 
> 网盘可以用这个：pan.huang1111.cn

这是官方的下载地址https://autopatchcn.yuanshen.com/client_app/download/pc_zip/20221128113626_LSJsjaUDgixXmWnd/YuanShen_3.3.0.zip

**Comment by yaolunmao** [comment]
> 我也遇到了这个情况 3.3版本和服务端完全对应 就是不知道是怎么回事 别人用代理一搞就上去了，我代理是上去了，但是就是4214，也不知道是国际服的问题还是什么问题。 我各种代理都试过了，fidder，大神手搓的，mixproxy，等等

文件名是PublicKey不是PrivateKey，你看看你是不是搞错了，在云盘下载的就是错的

**Comment by mcoi-dev** [comment]
> 

我是手动去release下载的

也用过一个叫TJGL的自动打补丁的启动器

**Comment by awaae001** [comment]
https://www.123pan.com/s/gk5KVv-tc8A3


这么重要的怎么不告诉我呢？上面的代码已经改了，大家试一下能不能用。

**Comment by yaolunmao** [comment]
> https://www.123pan.com/s/gk5KVv-tc8A3
> 
> 这么重要的怎么不告诉我呢？上面的代码已经改了，大家试一下能不能用。

可能大家都没注意到 我这里好使了

**Comment by yaolunmao** [comment]
> > 
> 
> 我是手动去release下载的
> 
> 也用过一个叫TJGL的自动打补丁的启动器

我是把`PublicKey`和`mhypbase.dll`放进去就好了，本体和`GC`还有`resource`都是3.3的，能出现4214证明你已经代理到了自己的登录器，按理说不应该有问题，你看看你的`PublicKey`内容和[RSAPatch](https://github.com/34736384/RSAPatch)这上面的一不一样

**Comment by KuhnXIE** [comment]
我也是遇到这个问题不知道怎么解决
![AKA7OC~I4ETVHZ$_`ZT@_02](https://user-images.githubusercontent.com/81501749/215633943-1c27aa96-92fa-4ad8-8d47-aa046f29c2ed.jpg)
![`PM5Y6P1DJY`8~F~6BDS}~K](https://user-images.githubusercontent.com/81501749/215633965-52b2cad2-2e1e-4081-be6d-2037c083000e.jpg)

**Comment by KuhnXIE** [comment]
服务器是正常的，客户端资源下载的3.3直接解压没有更新
![@{109H_GCN``Q(8P6GM%WX6](https://user-images.githubusercontent.com/81501749/215635586-9578c122-faa6-4ca9-acb6-f4abc7528eb4.jpg)

**Comment by KuhnXIE** [comment]
我是两台电脑连接，用的启动器，代理是正常的

**Comment by Abilyf** [comment]
3.3版本没有语音吗？

**Comment by KuhnXIE** [comment]
是的，不知道什么原因，我资源包跟语音包都是下载的3.3



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 晚上9:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Grasscutters/Grasscutter] [Bug] 登录流程加载资源失败，客户端错误码4214 (Issue #2020)




 
3.3版本没有语音吗？

**Comment by ghost** [comment]
4214 is a user error + this is a very old and outdated post. @KingRainbow44 can you close this?

**Comment by Aharker1** [comment]
> 我也是遇到这个问题不知道怎么解决 ![AKA7OCI4ETVHZ$_ZT@_02]（https://user-images.githubusercontent.com/81501749/215633943-1c27aa96-92fa-4ad8-8d47-aa046f29c2ed.jpg） ！[PM5Y6P1DJY'8F~6BDS}~K](https://user-images.githubusercontent.com/81501749/215633965-52b2cad2-2e1e-4081-be6d-2037c083000e.jpg)

游戏数据异常

**Comment by ghost** [comment]
> > 我也是遇到这个问题不知道怎么解决 ![AKA7OCI4ETVHZ$_ZT@_02]（[https://user-images.githubusercontent.com/81501749/215633943-1c27aa96-92fa-4ad8-8d47-aa046f29c2ed.jpg）](https://user-images.githubusercontent.com/81501749/215633943-1c27aa96-92fa-4ad8-8d47-aa046f29c2ed.jpg%EF%BC%89) ！[PM5Y6P1DJY'8F~6BDS}~K](https://user-images.githubusercontent.com/81501749/215633965-52b2cad2-2e1e-4081-be6d-2037c083000e.jpg)
> 
> 游戏数据异常

去discord问！
