### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by 0x915** [Melledy/Grasscutter#203]
Use hosts to forward client traffic
use 'account create' successfully created an account

when starting the client , server :
      [INFO] [Dispatch] Client topazlabs.com/127.0.0.1:2423 request: query_region_list

when login (No password is not allowed to login,so I knocked something), fiddler :
    CONNECT api-account-os.hoyoverse.com:443 HTTP/1.1
    Host: api-account-os.hoyoverse.com:443
    User-Agent: UnityPlayer/2017.4.30f1 (UnityWebRequest/1.0, libcurl/7.51.0-DEV)
    CONNECT log-upload-os.mihoyo.com:443 HTTP/1.1
    Host: log-upload-os.mihoyo.com:443
    User-Agent: UnityPlayer/2017.4.30f1 (UnityWebRequest/1.0, libcurl/7.51.0-DEV)

Still stuck at the login screen.

![image](https://user-images.githubusercontent.com/15169084/164993796-da517a25-1b05-47de-aa84-3cc26347c7bf.png)

**Comment by unec2200** [comment]
可能要国际服，国服不行

**Comment by cryingcheems** [comment]
try https://github.com/Grasscutters/GrassClipper

**Comment by KingRainbow44** [comment]
currently, this looks more like an issue with your proxy and not the server. hence this isn't a bug and shouldn't be reported here.

**Comment by 0x915** [comment]
> 尝试 https://github.com/Grasscutters/GrassClipper
I can connect to the server using GrassClipper, but I get a 503 error.
proxy server :
    127.0.0.1:13576: POST https://127.0.0.1:22102/sdk/dataUpload
     << [Errno 10061] Connect call failed ('127.0.0.1', 22102)
    127.0.0.1:13576: client disconnect
    127.0.0.1:13576: server disconnect log-upload-os.mihoyo.com:443 (13.225.94.85:443)
    127.0.0.1:13582: client connect
    127.0.0.1:13581: server connect api-account-os.hoyoverse.com:443 (13.225.94.72:443)
    127.0.0.1:13582: server connect log-upload-os.mihoyo.com:443 (13.225.94.85:443)
    True
    True
