### ISSUE TITLE
[Bug] I can't do quests

### ISSUE THREAD

**Issue by VoteableDuck** [Melledy/Grasscutter#2034]
I use the command to add a quest, but when I arrive at the quest location, there are no characters to talk to, and the system can't tell if I've reached the quest location

**Comment by NotThorny** [comment]
Full questing functionality is not implemented. If you want to see where questing progress is at, you should refer to the in-progress fork for it: https://github.com/Anime-Game-Servers/Grasscutter-Quests

**Comment by thecutefinder** [comment]
@KingRainbow44 Could you close this as a duplicate of one of [https://github.com/Grasscutters/Grasscutter/issues?q=quest the many, many issues asking for quest support or reporting that "quests won't start"]?

**Comment by KingRainbow44** [comment]
duplicate of #165
