### ISSUE TITLE
有1.46的已编译好版本吗？

### ISSUE THREAD

**Issue by jianzhishendi** [Melledy/Grasscutter#2042]
我的Java有问题，设置了系统变量仍在编译时报错，麻烦有心人发个1.46的jar文件，感谢！！

**Comment by Leevle** [comment]
重新配置你的java，java17版本，如果需要可以联系我qq49538642，文件有点大

**Comment by PDMengQAQ** [comment]
tg：https://t.me/PDMengQAQ
QQ:2657075322
Discord:PDMengQAQ#9158
请任选其一联系我

**Comment by PDMengQAQ** [comment]
请在我的主页获取一键端，游玩前务必阅读README.md最后一行

**Comment by MLChinoo** [comment]
> tg：https://t.me/PDMengQAQ QQ:2657075322 Discord:PDMengQAQ#9158 请任选其一联系我

哥联系你了，你家妹妹们真不错，人美声甜服务又好，价格公道，我晚上连开24炮不带停的，下次打炮再来联系你

**Comment by HongchengQ** [comment]
> tg：https://t.me/PDMengQAQ QQ:2657075322 Discord:PDMengQAQ#9158 请任选其一联系我

哥联系你了，你家妹妹们真不错，人美声甜服务又好，价格公道，我晚上连开24炮不带停的，下次打炮再来联系你
