### ISSUE TITLE
[Feature Request] releases中只有1.4.3的jar包，什么时候能更新一下？

### ISSUE THREAD

**Issue by ouhexi** [Melledy/Grasscutter#2045]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MLChinoo** [comment]
s∞n

**Comment by azheea** [comment]
这也没有开个issue的必要吧。。自行编译就行了 没必要等releases

**Comment by zutyhcx** [comment]
在action中能找到

**Comment by pengzhenghao** [comment]
release确实有点过时，今天用release遇到了不少bug，用git clone自己编译的jar跑就没问题了。
