### ISSUE TITLE
为什么支持3.4的pr2041没有合并？Why is pr 2041, which supports 3.4, not merged?

### ISSUE THREAD

**Issue by cakeseven** [Melledy/Grasscutter#2046]
为什么支持3.4的pr2041没有合并？Why is pr 2041, which supports 3.4, not merged?

**Comment by cyjyyd** [comment]
Still some issues out there.pr 2014 is not fully fixed.

**Comment by cakeseven** [comment]
> 2014 there.pr 仍有一些问题尚未完全解决。

I'm talking about pr 2041, not pr 2014, https://github.com/Grasscutters/Grasscutter/pull/2041

**Comment by cakeseven** [comment]
> > 2014 there.pr 仍有一些问题尚未完全解决。
> 
> 我说的是 pr 2041，而不是 pr 2014，#2041

I can't use 3.4

**Comment by azheea** [comment]
你可以选择去该pr的仓库里下载 不必等待合并 就像上面那位说的 pr没有完善 不应马上合并

**Comment by casksteven** [comment]
你这什么离谱的用户名（

**Comment by mcoi-dev** [comment]
现在合并了！

**Comment by mcoi-dev** [comment]
https://pan.huang1111.cn/s/De5QH4

**Comment by mcoi-dev** [comment]
顺便帮忙编译了

**Comment by SakuraLaurel** [comment]
> Reference i

Thank you my bro, useful!
兄弟太强了，我自己编译的总是一堆java报错，你的版本一个错都没有
