### ISSUE TITLE
[Feature Request]  国服客户端替换补丁文件要怎么获取？3.3的，3.4的

### ISSUE THREAD

**Issue by ouhexi** [Melledy/Grasscutter#2047]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mcoi-dev** [comment]
同意++

**Comment by mcoi-dev** [comment]
s∞n

**Comment by mcoi-dev** [comment]
不过应该可能和3.3一样

**Comment by mcoi-dev** [comment]
（自己测了4214，可能改公钥可以）

**Comment by hub707** [comment]
[Uploading p_xxx_a3.tch4_pu_tin[Gxxx_en_xxxx_shin Imp...fo_xxx_lder.zip…]()

**Comment by hub707** [comment]
[Uploading bdeacahsg&p_xxx_a3.tch4_pu_tin[asfababsbXGxxx_en_xxxx_shin I_hhh_mp...fo_xxx_lderasfababsabwzip…]()

**Comment by hub707** [comment]
[Uploading bdeacahsg&p_xxx_a3.tch4_pu_tin[asfababsbXGxxx_en_xxxx_shin I_hhh_mp...fo_xxx_lderasfababsabwzip…]()
[Uploading bdeacahsg&p_xxx_a3.tch4_pu_tin[asfababsbXGxxx_en_xxxx_shin I_hhh_mp...fo_xxx_lderasfababsabwzip…]()

**Comment by hub707** [comment]
/s/iRYKVv-CQSCh

**Comment by hub707** [comment]
PLSDel999ANdmmt _xxx_w&&199923pmmtan@.c m /999s/ p999ut in G...I..Ga999me folder_dmmtel g n   iR999gYKVv-CQnSCh

**Comment by hub707** [comment]
www.123pan.com

**Comment by zyx20070907** [comment]
谁知道补丁咋生成啊

**Comment by zyx20070907** [comment]
谁知道补丁咋生成啊

**Comment by fred913** [comment]
Just go and download RSAPatch from the top of the list at [RSAPatch Releases](https://github.com/34736384/RSAPatch/releases), as it should work for future versions
