### ISSUE TITLE
[Feature Request] Local server on Jailborken iOS device? 越狱的iOS设备是否有可能本地搭建

### ISSUE THREAD

**Issue by GoldBuster** [Melledy/Grasscutter#2048]
Jailbroken iOS (or iPad OS) devices have their terminal and root privilege (sort of), so is there a chance to recompile the grasscutter source code into another architecture in order to support iOS devices? since a lot of people use their iPad to play this game.

**Comment by jianzhishendi** [comment]
应该不行，iOS的系统底层结构不一样

**Comment by KingRainbow44** [comment]
if a JRE/JDK is supported on iOS (not sure if it does) then Grasscutter should be able to run itself perfectly fine
