### ISSUE TITLE
[Bug] Dust Song Pot trust level cant increase 尘歌壶信任等阶无法提升 

### ISSUE THREAD

**Issue by 961241279** [Melledy/Grasscutter#2051]
game 3.4 游戏版本
gc 1.4.6 服务器版本

The trust level and trust value of Dusty Song Pot cannot be increased

It is invalid to use give to obtain the trust value and make the decoration for the first time

尘歌壶信任等阶和信任值无法提升
使用give获取信任值以及首次制作摆设均无效

**Comment by NotThorny** [comment]
These aren't implemented in Grasscutter yet, but you can use my PR for gaining trust and other teapot additions and fixes (currently for 3.3 as that is what gc is updated to at the moment). Crafting decorations or furniture work to give trust, as well as using /give
https://github.com/Grasscutters/Grasscutter/pull/2032
