### ISSUE TITLE
[Bug] 开门白屏

### ISSUE THREAD

**Issue by Batcy** [Melledy/Grasscutter#2058]
开门的时候登录白屏，服务端没报错，有大佬知道是啥情况吗

**Comment by simo8102** [comment]
割草机目前处于3.3版本 3.4要自己合并pr

**Comment by Xiao-yux** [comment]
> 
我使用的是https://github.com/Grasscutters/Grasscutter/actions/runs/4081203973这个，在局域网代理向自己就可以进游戏，如果放在服务器链接就卡白屏是什么情况啊

**Comment by Achioe** [comment]
+1

**Comment by reflexit** [comment]
Latest version on `development` branch works for me locally. I'm using the jar from `Build #2237`.

I copied RSA Patch from 3.3, and performed a clean download of game client, audio package, and gc resources.

**Comment by pengzhenghao** [comment]
I work!! My suggestions:

1. Try to compile the jar file by yourself.
2. Use resource from here:  https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.4/

**Comment by Rakyarvik** [comment]
> > 
> 
> 我使用的是 [https://github.com/Grasscutters/Grasscutter/actions/runs/4081203973 这个，在局域网代理向自己就可以进游戏，如果放在服务器链接就卡白屏是什么情况啊](https://github.com/Grasscutters/Grasscutter/actions/runs/4081203973%E8%BF%99%E4%B8%AA%EF%BC%8C%E5%9C%A8%E5%B1%80%E5%9F%9F%E7%BD%91%E4%BB%A3%E7%90%86%E5%90%91%E8%87%AA%E5%B7%B1%E5%B0%B1%E5%8F%AF%E4%BB%A5%E8%BF%9B%E6%B8%B8%E6%88%8F%EF%BC%8C%E5%A6%82%E6%9E%9C%E6%94%BE%E5%9C%A8%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%93%BE%E6%8E%A5%E5%B0%B1%E5%8D%A1%E7%99%BD%E5%B1%8F%E6%98%AF%E4%BB%80%E4%B9%88%E6%83%85%E5%86%B5%E5%95%8A)

同样的情况，本地可以正常游玩，试着把grasscutter放在局域网中另一台设备上再去连接就会白屏，服务端显示成功交换token，正在尝试登陆  之后就没有后续了


15:34:55 <INFO:RegionHandler> [Dispatch] Client 192.168.26.65 request: query_region_list
15:35:05 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 192.168.26.65 正在尝试通过 token 登录
15:35:05 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 192.168.26.65 已通过 token 登录，UID 为 10001
15:35:05 <INFO:DispatchHandler> [Dispatch] 客户端 192.168.26.65 正在尝试登录
15:35:06 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 192.168.26.65 成功交换 token
15:35:06 <INFO:DispatchHandler> [Dispatch] 客户端 192.168.26.65 正在尝试登录

**Comment by zty012** [comment]
> 割草机目前处于3.3版本 3.4要自己合并pr
> 
> 你可以试下这个https://github.com/Grasscutters/Grasscutter/actions/runs/4081203973
> 
> 或者下载这个代码https://github.com/yeyeyeawa/Grasscutter 自行编译

谢谢，解决了（

**Comment by yufaf** [comment]
我打开cmd会显示加载然后闪退
