### ISSUE TITLE
[Bug] 1.4.6 server crash

### ISSUE THREAD

**Issue by ultard** [Melledy/Grasscutter#2062]
**Did you look for other closed issues that have the same problem?**

No

**Describe the bug**

After build was succesful, i added 3.4 Resources and after this on a start server crashes.
Java: OpenJDK 64-Bit Server VM Temurin-17.0.5+8

**Which branch did you use?**

Grasscutter version: 1.4.6-71a1e31d
Git Hash: 71a1e31

**Screenshots**

![image](https://user-images.githubusercontent.com/63789651/220074194-1f6a6333-106f-4615-b58a-5a692e520f5d.png)
![image](https://user-images.githubusercontent.com/63789651/220074626-0c774b5f-d3df-4dee-8c18-9374da12b5c8.png)

**Comment by NotThorny** [comment]
Change your resources to Yuuki's for 3.4: https://gitlab.com/yukiz/GrasscutterResources/-/tree/3.4
Delete the cache folder after you change the resources.

**Comment by pengzhenghao** [comment]
@NotThorny Thank you so much!! I can run by replacing resources with https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.4/

We should update docs + wiki to better guide user
