### ISSUE TITLE
[Feature Request] Update README and wiki to use YuukiPS's resources

### ISSUE THREAD

**Issue by pengzhenghao** [Melledy/Grasscutter#2063]
**Is your feature request related to a problem? Please describe.**

 YuukiPS provides fixed resources file that support client and grasscutter 3.4 at:

 https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.4/

We should update the README / wiki to reflect this instead of pointing to the official reosource repo which is outdated.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by KingRainbow44** [comment]
this is present on the [new wiki](https://grasscutter.io/wiki/Guide/Running)
