### ISSUE TITLE
[Bug] error 526 while using YuukiPS launcher 

### ISSUE THREAD

**Issue by grasseater238** [Melledy/Grasscutter#2075]
So I connected to grasscutters.xyz and written a port 443, when trying to login it says "server is full, try again later(512)" bruh it can't be .
    I tried to install grasscilpper launcher but it shows Edge WebView on a sec and crashes, the main isssue is error 512.

I'm using yuukips launcer bec it has everything pre installed and don't needs fiddler  

update: I used cultivation launcher this shit still appears

**Comment by NotThorny** [comment]
grasscutters.xyz isn't a server that you can connect to. Set up a local server following the instructions on this github or pick an active public one.

**Comment by KingRainbow44** [comment]
rip grasscutters.xyz, use another public server like [YukkiPS](https://discord.com/channels/965284035985305680/1029654089593802752/1029654089593802752)
