### ISSUE TITLE
资源文件下不了, GitLab注册账号一直没人通过, 是不是换姿势了

### ISSUE THREAD

**Issue by HongJian-Yang** [Melledy/Grasscutter#2087]
**Is your feature request related to a problem? Please describe.**

Your account is pending approval from your GitLab administrator and hence blocked. Please contact your GitLab administrator if you think this is an error.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NotThorny** [comment]
Use the resources here instead:
https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.5
