### ISSUE TITLE
有最新3.5的resource吗，下载地址用不了账号显示一直审核

### ISSUE THREAD

**Issue by jianzhishendi** [Melledy/Grasscutter#2097]
有最新的resource吗，下载地址用不了账号显示一直审核

**Comment by rourouzhu13** [comment]
重复的问题。

**Comment by jianzhishendi** [comment]
git clone 也不行：“
warning: auto-detection of host provider took too long (>2000ms)
warning: see https://aka.ms/gcm/autodetect for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
warning: ----------------- SECURITY WARNING ----------------
warning: | TLS certificate verification has been disabled! |
warning: ---------------------------------------------------
warning: HTTPS connections may not be secure. See https://aka.ms/gcm/tlsverify for more information.
remote: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://git.crepe.moe/help/topics/git/troubleshooting_git#error-on-git-fetch-http-basic-access-denied
fatal: Authentication failed for 'https://git.crepe.moe/grasscutters/Grasscutter_Resources.git/'”

**Comment by rourouzhu13** [comment]
你搜索一下，有人问过了，说过很多次的问题。

**Comment by ghost** [comment]
[https://github.com/Grasscutters/Grasscutter/discussions/2079](url)
Please search before ask such questions. Also you should ask them in Discord server.

**Comment by Ayin-a** [comment]
可以尝试yuuki的https://gitlab.com/YuukiPS/GC-Resources
