### ISSUE TITLE
where is Grasscutter commands??

### ISSUE THREAD

**Issue by Tomiaocat** [Melledy/Grasscutter#210]
![image](https://user-images.githubusercontent.com/23458602/165015730-702b445b-0d21-4450-8148-9189299a41ac.png)

**Comment by luckykeeper** [comment]
use "help" or see Readme https://github.com/Grasscutters/Grasscutter#grasscutter-commands

**Comment by luckykeeper** [comment]
![image](https://user-images.githubusercontent.com/34579433/165016522-ad944f44-cc01-411b-aee2-cd34030a6cda.png)

just like this

**Comment by Tomiaocat** [comment]
> use "help" or see Readme https://github.com/Grasscutters/Grasscutter#grasscutter-commands

![image](https://user-images.githubusercontent.com/23458602/165016509-a74f565c-2623-48d8-9ef3-2321d83abdee.png)
thk , i find it

**Comment by Tomiaocat** [comment]
i'm read code ,but it say Unknown Command
![image](https://user-images.githubusercontent.com/23458602/165016807-e1475231-0428-4e30-952b-2293ba89a32f.png)

**Comment by F-Unction** [comment]
hello, how did you solve it.
console even told me that help is unknown command
