### ISSUE TITLE
[Bug] When I filled out ipv6 in config.json, the client was able to log in, but when I clicked on the door, the screen went blank

### ISSUE THREAD

**Issue by Melodramma** [Melledy/Grasscutter#2113]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by thecutefinder** [comment]
This is likely an issue with your configuration. Please join the Grasscutters Discord server and ask for help in the support channel.

**Comment by Melodramma** [comment]
> 

I tested IPv4 on the internal network without any issues, so this should be due to a bug in Grasscutter's support for IPv6 or a temporary lack of support for IPv6

**Comment by Melodramma** [comment]
> This is likely an issue with your configuration. Please join the Grasscutters Discord server and ask for help in the support channel.

I tested IPv4 on the internal network without any issues, so this should be due to a bug in Grasscutter's support for IPv6 or a temporary lack of support for IPv6

**Comment by KingRainbow44** [comment]
i don't believe the client supports ipv6 for UDP connections

**Comment by KingRainbow44** [comment]
if it does, then it's grasscutter's server implementation (netty) which is restricting it to ipv4 exclusively
