### ISSUE TITLE
[Bug] 我无法访问资源文件的GITLaB 实验室

### ISSUE THREAD

**Issue by awaae001** [Melledy/Grasscutter#2117]
我无法访问资源文件的GITLaB 实验室
![image](https://user-images.githubusercontent.com/108462724/232130485-b1283a71-7720-49e3-9906-7794b2dc5400.png)

I can't access the GITLaB lab for resource files

**Comment by thecutefinder** [comment]
You can get a working link here: https://gitlab.com/YuukiPS/GC-Resources

**Comment by awaae001** [comment]
它是可用的，谢谢
