### ISSUE TITLE
[Bug] 4214 RSAkey无法访问

### ISSUE THREAD

**Issue by awaae001** [Melledy/Grasscutter#2119]
![image](https://user-images.githubusercontent.com/108462724/232182865-a0800a3b-50dc-4be1-bc44-7291aebc0a4f.png)

**Comment by ghost** [comment]
更新RSAPatch https://github.com/34736384/RSAPatch/releases/download/v1.3.0/RSAPatch.dll，问问题可不可以去discord的support。

**Comment by awaae001** [comment]
有没有一种可能我的密钥就是最新的？

**Comment by NotThorny** [comment]
Are you sure you're using 1.3.0 of the RSA patch? This appears to indicate 1.1.0, or you are using a very old game client

**Comment by awaae001** [comment]
可能是我复制的时候将版本复制错误了，我回去再重新尝试一遍。

**Comment by awaae001** [comment]
我从网上又下载了一个新的版本，那个版本可能是过时的旧版本。

**Comment by NotThorny** [comment]
Be sure to use the one @rourouzhu13 sent above: https://github.com/34736384/RSAPatch/releases/download/v1.3.0/RSAPatch.dll
As 3.6 game client does not support earlier versions of the RSA patch
