### ISSUE TITLE
[Bug] Character stats change display reversed when level up?

### ISSUE THREAD

**Issue by EndsM** [Melledy/Grasscutter#2123]
**Did you look for other closed issues that have the same problem?**
I searched "reverse" in issues, it seems no one have said this yet.

**Describe the bug**
When character level up using the item in character tab, the display of stats changes is reversed.
It should be:
Lower stats → Higher stats (green up arrow)
But here is:
Higher stats → Lower stats (red down arrow)

**Which branch did you use?**
Downloaded with cultivation "all-in-one" option about 1 hours ago.
Grasscutter version: 1.4.8-

**Screenshots**

![屏幕截图(26)](https://user-images.githubusercontent.com/24600410/232400613-1183b414-6fd0-45d2-a30e-1ebadefa7ee3.png)

**Additional context**

**Comment by thecutefinder** [comment]
This is a known bug in 3.6 that Yuuki needs to fix in their proto repository.

**Comment by EndsM** [comment]
Thanks for answering this, and apologize for inconvenience this may caused. I think this have answered what I'm confused with
