### ISSUE TITLE
[Bug] invalid gather objects spam

### ISSUE THREAD

**Issue by scooterboo** [Melledy/Grasscutter#2127]
**Did you look for other closed issues that have the same problem?**
Yes nothing for "Invalid gather object"

**Describe the bug**
Occasionally, a wall of "invalid gather objects will appear in console:
![image](https://user-images.githubusercontent.com/1877986/233345228-00d2a5f2-dafc-48ad-bd77-aea0583c73b8.png)
There doesn't seem to be any side effects to this error.

**Which branch did you use?**
(unstable-quests)
  Grasscutter version: 2.0.0-unstable
  Git Hash: d6088315

**Additional context**

This error is logged in line 38 in [game\entity\gadget\GadgetGatherObject.java](https://github.com/Grasscutters/Grasscutter/blob/unstable-quests/src/main/java/emu/grasscutter/game/entity/gadget/GadgetGatherObject.java)
![image](https://user-images.githubusercontent.com/1877986/233346667-a2899188-e824-4e53-829b-167829333f72.png)

All of these config IDs are in my resources\Scripts\Scene\3\scene3_group133003806.lua and have a gadget_id of 70540011
![image](https://user-images.githubusercontent.com/1877986/233348650-f3970a88-571c-4973-b82a-f85ad70384dc.png)

My research shows that 70540011 are the stems of Valberries which can be found here:
![image](https://user-images.githubusercontent.com/1877986/233349485-a81eaa15-9918-40e5-8ff6-771f353fc6c9.png)

**Comment by awaae001** [comment]
可以是没有对应的脚本去执行

**Comment by scooterboo** [comment]
Issue was hidden by 02a9c55b0f8d18006160f439166b86766e99217c
