### ISSUE TITLE
Add configuration files about database authentication

### ISSUE THREAD

**Issue by duanyhui** [Melledy/Grasscutter#213]
Add configuration files about database authentication so that it can log in to the encrypted database

**Comment by exzork** [comment]
if only username and password is needed you can do it under databaseurl ( both DatabaseUrl and DispatchServerDatabaseUrl ) using mongodb://username:password@host:port

**Comment by duanyhui** [comment]
> if only username and password is needed you can do it under databaseurl ( both DatabaseUrl and DispatchServerDatabaseUrl ) using mongodb://username:password@host:port

ok,thanks!
