### ISSUE TITLE
[Feature Request] 为什么还没有3.6版本

### ISSUE THREAD

**Issue by okkj-eng** [Melledy/Grasscutter#2134]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ghost** [comment]
1.早就有了。
2.为什么你们都要在Github提问？Github不是给你们提这种睿智问题的。
3.你加入Discord的#support行不行？#resource里面就有3.6。
