### ISSUE TITLE
how to login?

### ISSUE THREAD

**Issue by Tomiaocat** [Melledy/Grasscutter#214]
![image](https://user-images.githubusercontent.com/23458602/165019301-b66d9e8d-091f-42a1-ac30-0abe55370e57.png)
![image](https://user-images.githubusercontent.com/23458602/165019328-fd44d4e0-19c8-4dca-a970-394fe836cfdc.png)

**Comment by Tomiaocat** [comment]
create user  loen,but unkonw login game

**Comment by 1shin-7** [comment]
check your proxy settings

**Comment by Tomiaocat** [comment]
> check your proxy settings

![image](https://user-images.githubusercontent.com/23458602/165022985-ce7a513d-7f3a-4b0e-925a-c32f5608a203.png)

**Comment by 1shin-7** [comment]
> 

In Windows Setting pls

**Comment by 1shin-7** [comment]
ms-settings:network-proxy

**Comment by Tomiaocat** [comment]
![image](https://user-images.githubusercontent.com/23458602/165024205-2d3c1cf0-60b7-422c-8e9c-00f7099c8c3a.png)

**Comment by 1shin-7** [comment]
> ![image](https://user-images.githubusercontent.com/23458602/165024205-2d3c1cf0-60b7-422c-8e9c-00f7099c8c3a.png)

turn to open and set the port to 8080
~~你都没设置代理怎么能连上啊喂~~

**Comment by Tomiaocat** [comment]
> ms-settings:network-proxy

when V2rayN is run,windows proxy will turn to open and port is10809

**Comment by soloopooo** [comment]
While you are using other proxy programs like clash or v2ray, just use Proxifier to set it and turn off the SYSTEM PROXIES like THIS:
![image](https://user-images.githubusercontent.com/36123081/165025168-b2c45e6c-e039-456d-a4f5-e96dee6101a8.png)
![image](https://user-images.githubusercontent.com/36123081/165025280-385591ac-91ec-4509-bf5c-645c7d320014.png)

![image](https://user-images.githubusercontent.com/36123081/165025210-ead414c3-807b-437d-8861-411690525d4c.png)

**Comment by Tomiaocat** [comment]
> 
turn to open and set the port to 8080,
![image](https://user-images.githubusercontent.com/23458602/165026594-2b0f01a5-874e-4c39-bdef-93549e4afcda.png)
![image](https://user-images.githubusercontent.com/23458602/165026697-c20b0630-a03e-492d-a1e4-658df9615fe2.png)
what is password?

**Comment by timing1337** [comment]
You can put any passwords.
