### ISSUE TITLE
[Bug] Combo token login登录相关

### ISSUE THREAD

**Issue by dfaofeng** [Melledy/Grasscutter#2141]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

  Grasscutter version: 1.5.0
  Git Hash: c4f1208f45c3c649114adb5b8bf185cfbafe785b

**Screenshots**

**Additional context**
请求这个token需要参数

结构体有写.但是没使用,谁知道这个请求参数sign和device怎么生成的?
![屏幕截图 2023-05-02 220404](https://user-images.githubusercontent.com/14891398/235690453-88ddbf86-d7d0-413b-89d4-adfdac53f7ea.png)

![image](https://user-images.githubusercontent.com/14891398/235689822-3b0ad7d8-8a47-4849-8f74-886235a4ba64.png)

**Comment by 66hh** [comment]
device是mhysdk生成的机器码具体咋生成的就得去逆向mhysdk了,这玩意没啥用所以没人去逆向,官服是拿这玩意做风控之类的,还有就是官服的beta版本也是通过这个判断内测玩家有没有换电脑登录

**Comment by 66hh** [comment]
我研究了一下这个机器码分两段,前面那段是SystemInfo.deviceUniqueIdentifier就是unity接口生成的机器码具体可以看
https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html
但后面米哈游还加了一串不知道什么东西

**Comment by dfaofeng** [comment]
> 我研究了一下这个机器码分两段,前面那段是SystemInfo.deviceUniqueIdentifier就是unity接口生成的机器码具体可以看 https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html 但后面米哈游还加了一串不知道什么东西

关键是下面那个sign 不知道加密算法就不能拿到combo的token

**Comment by 66hh** [comment]
sign好像是hash之类的东西具体咋算的得研究研究

**Comment by fenginsc** [comment]
登录时，不显示用户名算BUG吗？
我这边好像显示的是 “，欢迎进入游戏” 有空截个图

**Comment by jianzhishendi** [comment]
> 登录时，不显示用户名算BUG吗？ 我这边好像显示的是 “，欢迎进入游戏” 有空截个图

我的也是

**Comment by dfaofeng** [comment]
sign算法已经知道 参考 [https://github.com/Sorapointa/Sorapointa/blob/dc3b59019d87d8d7f34100255e51d5e8f866b780/sorapointa-dispatch/src/main/kotlin/org/sorapointa/dispatch/data/DispatchData.kt#L191](url)
