### ISSUE TITLE
[Bug] 商城装扮购买不生效

### ISSUE THREAD

**Issue by fenginsc** [Melledy/Grasscutter#2142]
我记得之前的版本是可以购买的，现在也可以购买但不生效，还是提示需要购买。
可以看到凝取结晶已经扣了，但装扮购买不生效
用的是最新的[Grasscutter](https://github.com/Grasscutters/Grasscutter)1.5.0版本，游戏版本是3.6.0
![批注 2023-05-03 171609](https://user-images.githubusercontent.com/50092603/235877950-93267f6e-3d93-430c-925d-b3d44e9f6472.jpg)
![批注 2023-05-03 171628](https://user-images.githubusercontent.com/50092603/235877968-183f1a69-202b-478b-87f5-8553ec5d3d62.jpg)
![批注 2023-05-03 171655](https://user-images.githubusercontent.com/50092603/235878570-898135cf-da14-4ff7-8776-07a90789ec9b.jpg)
![批注 2023-05-03 171737](https://user-images.githubusercontent.com/50092603/235877991-faea386a-31e4-4c7c-9a54-51d96858f4bc.jpg)

**Comment by rourouzhu13** [comment]
截图？

**Comment by MLChinoo** [comment]
check your resources and protos

**Comment by fenginsc** [comment]
> check your resources and protos

Thank you, I replaced the latest resource file and it works!
