### ISSUE TITLE
Multiplayer game

### ISSUE THREAD

**Issue by SiegfriedYin** [Melledy/Grasscutter#215]
Which port do I need to share so that my friends can join my server

**Comment by panhantao** [comment]
1.replace the "PublicIp" setting in config.json with your server ip instead of "127.0.0.1",in both "GameServer" and "DispatchServer"
2.Start the server and proxy on your machine
3.For the machine of your friend, start a proxy connecting to your server, the port should be 8080 by default
4.enjoy

**Comment by panhantao** [comment]
> Which port do I need to share so that my friends can join my server

1.replace the "PublicIp" setting in config.json with your server ip instead of "127.0.0.1",in both "GameServer" and "DispatchServer"
2.Start the server and proxy on your machine
3.For the machine of your friend, start a proxy connecting to your server, the port should be 8080 by default
4.enjoy

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
