### ISSUE TITLE
[Bug] Cooking food results always in burnt/the worst quality

### ISSUE THREAD

**Issue by achilleanfriedrice** [Melledy/Grasscutter#2152]
**Did you look for other closed issues that have the same problem?**
I did, and there were none.

**Describe the bug**
Foods are never perfect quality when being made, whenever I click when it's in the perfect zone it's always suspicious quality.

**Which branch did you use?**
  Grasscutter version: 1.5.0 (using the questing fork that came with the all in one questing from Cultivation)
  Git Hash: c4f1208

**Screenshots**
![image_2023-05-17_164816542](https://github.com/Grasscutters/Grasscutter/assets/120236938/c03cabcb-e6d0-4a5b-b44b-8dabd22b8ad2)
![image](https://github.com/Grasscutters/Grasscutter/assets/120236938/0ec464b6-0171-4893-a751-9b94a1a93c33)

**Additional context**
Like I said this is in the questing fork that's in the all in one.

**Comment by trueworldfacts** [comment]
Thanks for reporting. This sounds like a proto issue. @NickTheHuy do you know the solution to this?

**Comment by Hiro420** [comment]
yes, swap between qte_quality and cook_count, they were wrong

message PlayerCookRsp {
    uint32 qte_quality = 2;
    int32 retcode = 12;
    uint32 cook_count = 14;
    repeated ItemParam item_list = 8;
    repeated ItemParam extral_item_list = 15;
    CookRecipeData recipe_data = 9;
}

message PlayerCookReq {
    uint32 cook_count = 13;
    uint32 assist_avatar = 1;
    uint32 qte_quality = 6;
    uint32 recipe_id = 7;
}

**Comment by Hiro420** [comment]
[cook_fix_proto.zip](https://github.com/Grasscutters/Grasscutter/files/11503703/cook_fix_proto.zip)
this is the compiled fix, had to zip because github

**Comment by KingRainbow44** [comment]
will fix soon:tm:

**Comment by trueworldfacts** [comment]
Going to open a PR

**Comment by Hiro420** [comment]
> Going to open a PR

no need. already fixed

**Comment by trueworldfacts** [comment]
Ah, that's good.

**Comment by trueworldfacts** [comment]
@KingRainbow44 close as completed?

**Comment by KingRainbow44** [comment]
yes i forgot

**Comment by scooterboo** [comment]
ec55b2ec22987908dd3085a6a259fd6a6cff4871 and 4ca172bf4212c1133abcec44a1cfd42e3c1975c2 Rolled this back

**Comment by trueworldfacts** [comment]
:nodisappear:
