### ISSUE TITLE
[Bug] Statues of the Seven don't function properly

### ISSUE THREAD

**Issue by achilleanfriedrice** [Melledy/Grasscutter#2156]
**Did you look for other closed issues that have the same problem?**
Yes and I found none.

**Describe the bug**
Statues of the Seven behave very strangely. Upon logging in at first, the very first SOTS behaves like it normally should when you interact with it. However, when you interact with any other ones, not only do they not function correctly (the one in Windrise only produces the message when you first interact w/ statues in typical gameplay, and defeating the Eye of the Storm by the one closer to the city of Mondstadt does not remove the wind barrier), it also removes functionality of the first SOTS, making it uninteractible, only producing healing when you enter its proximity.

**Which branch did you use?**
`unstable` - unknown version

**Additional context**
The only way I was able to "fix" this was /prop um 1 but the statues remained uninteractible even with the "unlocked" status on the map.

**Comment by achilleanfriedrice** [comment]
Forgot to title this, one second.

**Comment by KingRainbow44** [comment]
is this an issue with unstable? or just with the all in one

**Comment by NotThorny** [comment]
The all in one is using the latest commit and resources. Should be an issue with unstable unless it's been fixed and the user either hasn't used the update jar button, or hasn't re-downloaded all in one since then.
Git hash from the grasscutter version in console should clear up which one is this case.

**Comment by KingRainbow44** [comment]
fixed in 1.6.1

**Comment by JustRad123** [comment]
even tho claimed fixed i experience same issue in 1.7.1

**Comment by JustRad123** [comment]
tried to downgrade to 1.7.0 , not working too
