### ISSUE TITLE
Cannot load ConfigGlobalCombat.json, this error is important, fix it!

### ISSUE THREAD

**Issue by NightManCQ** [Melledy/Grasscutter#2174]
找不到 ConfigGlobalCombat.json ，导致过剧情卡死

**Comment by akbaryahya** [comment]
update res https://gitlab.com/YuukiPS/GC-Resources/-/commit/730d95607ee1b201c518069429eefc8691f3033c use https://gitlab.com/YuukiPS/GC-Resources/-/archive/3.7/GC-Resources-3.7.zip
