### ISSUE TITLE
I can't create a name in the game

### ISSUE THREAD

**Issue by doram0** [Melledy/Grasscutter#218]
I can't create a name in the game,and there is a lot of info printed in the console
![屏幕截图 2022-04-25 133153](https://user-images.githubusercontent.com/75086930/165027106-6951f333-11a9-4a48-9ece-25e72e143566.png)
![屏幕截图 2022-04-25 133238](https://user-images.githubusercontent.com/75086930/165027112-a51ec979-55e3-49a3-86fa-1805fdd97530.png)
![屏幕截图 2022-04-25 133540](https://user-images.githubusercontent.com/75086930/165027132-6f584356-a03c-4573-935a-0ae37361c276.png)

**Comment by lunaticwhat** [comment]
console already said it was database problem. Try clear your mongo database and run the game again

**Comment by doram0** [comment]
> 

I try to clean the database and create a name again,but i still can't create a name and continue to the next step

**Comment by KingRainbow44** [comment]
could be a potential database update error we might have to fix but for now

standard copy paste:
this isnt a support forum, this is an issue tracker. check the discord if you need help.
