### ISSUE TITLE
[Bug] v1.6.0无法编译

### ISSUE THREAD

**Issue by ighlES** [Melledy/Grasscutter#2182]
![image](https://github.com/Grasscutters/Grasscutter/assets/61189870/9322195f-ffd0-4a71-a1bb-89edf23204ad)
v1.6.0无法编译

**Comment by einekuhmachtmuh** [comment]
可以參考這個:
https://jimmyswebnote.com/create-nodejs-project-with-typescript/
另外請盡量用英文問問題，畢竟很多開發者看不懂中文。

**Comment by dfaofeng** [comment]
必须要装node.而且要装ts才能编译

**Comment by TomyJan** [comment]
`./gradlew jar -PskipHandbook=1`

**Comment by ighlES** [comment]
> `./gradlew jar -PskipHandbook=1`

谢谢问题以及解决了
