### ISSUE TITLE
[Bug] 1.6.1 1.6.0核心使用https访问400 无效的SNI

### ISSUE THREAD

**Issue by guyucc** [Melledy/Grasscutter#2184]
![image](https://github.com/Grasscutters/Grasscutter/assets/111928275/2c986d93-35e1-46f5-aaaa-a010a285de32)
去掉证书后用http访问一切正常

**Comment by KingRainbow44** [comment]
as of us using Javalin 5 (this change happened in the unstable branch), you can no longer use the provided `keystore.p12` file to host an HTTPS server. to host an HTTPS server, you will have to get a proper SSL certificate with your server's IP address on it (you can generate it or use a service like LetsEncrypt/pay for one). if you can't do this, then using standard HTTP is fine too
