### ISSUE TITLE
[Bug] Cannot build on latest commit, handbook generation failed.

### ISSUE THREAD

**Issue by Paper-Folding** [Melledy/Grasscutter#2186]
**Did you look for other closed issues that have the same problem?**

yes

**Describe the bug**

Execute `.\gradlew.bat` failed with error: handbook generation failed, it seems it is "@data/commands.json" causing the error, I try to remove `tsc` in `package.json`, end up with "Rollup failed to resolve import '@data/commands.json' " error.  
Current workaround I found is to use `.\gradlew.bat -PskipHandbook=1` and `.\gradlew.bat jar -PskipHandbook=1` to skip handbook building, but it is not ideal.  

**Which branch did you use?**

development

**Screenshots**

**Additional context**

**Comment by KingRainbow44** [comment]
This is a normal error, which occurs when you don’t provide the appropriate data to generate the handbook. I’ll probably implement a fix for this soon.
