### ISSUE TITLE
[Bug] Unable to login, stuck at character select

### ISSUE THREAD

**Issue by moraxs** [Melledy/Grasscutter#2187]
**Describe the bug**
When I enter my username in the game, I can't enter the game and the server gets the following error: **<ERROR:UnknownActivityConditionHandler> Called unknown condition handler NEW_ACTIVITY_COND_FINISH_MUSIC_GAME_ALL_LEVEL.**

**Which branch did you use?**
Releases Grasscutter-1.6.1.jar
Resources:https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.7?ref_type=heads

**Screenshots**
![a77798e23b907adfd18049a355d5f4a](https://github.com/Grasscutters/Grasscutter/assets/98573765/a57029d0-c833-477d-bc1c-6761d436f028)
![748ff85f9813b883e0264a772d435e1](https://github.com/Grasscutters/Grasscutter/assets/98573765/70adf4d1-7b73-4b52-9971-6d5d333eaa5b)

**Comment by KingRainbow44** [comment]
Please run `troubleshoot` in your server console and either upload a log file or show more of your console. It would also be helpful to know some system specs, such as total system memory.

**Comment by moraxs** [comment]
when i run `troubleshoot`，it outputs
![bf636723adce13366d9f8dbb023adab](https://github.com/Grasscutters/Grasscutter/assets/98573765/e64773fc-c97e-4aeb-8421-b70245ce9b9d)
That cg can be skipped by re-entering the game

**Comment by KingRainbow44** [comment]
Is the issue fixed? If not, please show more console logs before and after the issue occurs.

**Comment by blycr** [comment]
I encountered the same problem, how did you solve it?

**Comment by moraxs** [comment]
Wait for about a minute, or log in to the game again
