### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by NightManCQ** [Melledy/Grasscutter#2190]
1. 新创建账号进入游戏时有一封邮件赠送原石，但却不能领取。控制台信息：
![image](https://github.com/Grasscutters/Grasscutter/assets/52961479/e166a74c-1def-46c6-b025-e7815e61b977)
2. 新创建账号进入游戏升级角色时，提示的属性增加或减少的箭头显示错误。

**Comment by KingRainbow44** [comment]
this is currently normal behavior
