### ISSUE TITLE
[Bug] 珐露珊使用元素爆发（Q技能）后会死亡，并且无法使用正常手段复活

### ISSUE THREAD

**Issue by kajin-leo** [Melledy/Grasscutter#2191]
珐露珊使用元素爆发后会自动死亡，如果珐露珊死亡时处于前台状态则将无法进行任意动作，通过指令传送也无法跳出该状态，只能通过重新进入服务器解决；如果珐露珊死亡时处于后台状态，则无法通过恢复类食物或恢复指令恢复状态，也无法直接将珐露珊切换至前台，需要令队伍中处于珐露珊所处位的前一位角色死亡才能切换至珐露珊，并再次通过指令使珐露珊“正确”死亡后使用指令恢复至正常状态。
Faruzan dies automatically after using Elemental Burst. Any interactions cannot be accomplished after the death of Faruzan if Faruzan dies in foreground. This problem can only be solved by a re-login. Contrastingly, if Faruzan dies in background, foods or healing command cannot bring Faruzan back to life, and it is not feasible to switch Faruzan from background to foreground. To solve this, both the former character of Faruzan in the team and Faruzan herself has to be executed through `/kill` command, then healed through `/h` command. 
服务器命令行在这个过程中没有输出相应的错误信息。
Server console seems to have no relevant output regarding this problem. 
珐露珊前台死亡测试
Faruzan Foreground Death Test

https://github.com/Grasscutters/Grasscutter/assets/51558080/ffdd2587-701f-4360-b8ce-02e5139b302a

珐露珊后台死亡测试
Faruzan Background Death Test

https://github.com/Grasscutters/Grasscutter/assets/51558080/412898ff-63f7-4e3e-b9cc-65d371f7f1ce

珐露珊死亡后传送测试
Teleport Test After Faruzan's Death

https://github.com/Grasscutters/Grasscutter/assets/51558080/b0addfb4-7925-4afa-b59b-306257350922

**Comment by KingRainbow44** [comment]
can you run `/troubleshoot` in game or in your server console and send the result here?

**Comment by kajin-leo** [comment]
> can you run `/troubleshoot` in game or in your server console and send the result here?

12:56:00 <INFO:CommandHandler> Troubleshooting/Debug Information
Revision: 1.6.1 (e8bfdc3)
Player Count: 1
Questing Enabled: false
Scripts Enabled: true
Operating System: Windows 10
Resource Information: {
  "repository": "gitlab.com/YuukiPS/GC-Resources",
  "version": "3.7.0",
  "patches": "Amber,Custom",
  "scripts": "OFFICIAL",
  "hasServerResources": true,
  "hasSceneScriptData": true
}
------
FYI the grasscutter.jar file and resource files were downloaded in Cultivation. 
![屏幕截图 2023-06-04 130126](https://github.com/Grasscutters/Grasscutter/assets/51558080/fc654a52-07fc-487c-95a4-a572dc34b574)

**Comment by KingRainbow44** [comment]
this is a resources problem, please check with your resource provider.
