### ISSUE TITLE
[Bug] Startup error

### ISSUE THREAD

**Issue by ERthereal** [Melledy/Grasscutter#2192]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

  Grasscutter version: 1.6.1-dev
  Git Hash: 6D6E6A0
**Screenshots**

![PA``CZ530L35ISX`JQ$1_FR](https://github.com/Grasscutters/Grasscutter/assets/58130955/6a5b54d7-9de3-4309-b5bc-412c9f43366c)

**Additional context**

**Comment by KingRainbow44** [comment]
you are using invalid resources, please consult your resource provider.
