### ISSUE TITLE
[Feature Request] Allow old plug-ins to use

### ISSUE THREAD

**Issue by yuanshengaoshou114** [Melledy/Grasscutter#2194]
I use translation, which may not be accurate.
Many plug-ins of lawn mowers have stopped updating. They don't have open source code.Many plug-ins don't work after this update. Can you make it work again?

**Comment by KingRainbow44** [comment]
this will not be implemented because the existing codebase of Grasscutter has changes that plugins need to account for. upgrade the plugins using something like a java decompiler instead.
