### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by HowlingBlood** [Melledy/Grasscutter#220]
![image](https://user-images.githubusercontent.com/104342597/165028881-403f720c-8c2a-4195-ba0b-11b6721fedbf.png)
![image](https://user-images.githubusercontent.com/104342597/165028889-d3ee0093-6bdc-4da4-bbd4-c4f9dfe11d51.png)

**Comment by Tomiaocat** [comment]
you shoud close proxy

**Comment by HowlingBlood** [comment]
I tried ,but still got this error code

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
