### ISSUE TITLE
[Bug] 1.6.1 ERROR:UnknownActivityConditionHandler

### ISSUE THREAD

**Issue by okyes85** [Melledy/Grasscutter#2205]
Can log in normally
but will appear
![1](https://github.com/Grasscutters/Grasscutter/assets/38574151/2fe9d445-0c11-4db8-865f-8921d5bbb545)

Cannot choose the default character in the game
![2](https://github.com/Grasscutters/Grasscutter/assets/38574151/aa02bfd0-ac5e-4b51-83ee-b15d81fec9f0)

**Comment by KingRainbow44** [comment]
this is not a bug, your traveler has no element, visit the first statue of the seven, the activity handler is not a bug.
