### ISSUE TITLE
Questions about the gradlew.bat

### ISSUE THREAD

**Issue by Art0rias198** [Melledy/Grasscutter#221]
Sorry for the stupid question @@. Once I open the gradlew.bat for the setup, it closes immediately with a few texts shows within a second:
![螢幕擷取畫面 2022-04-25 140444](https://user-images.githubusercontent.com/104342462/165030408-315ea641-bc27-441f-b6ed-2ef2a1659262.png)
Not sure if it is normal or not...
I do open the MongoDB before opening the gradlew.bat, or I will need an extra setup on my  MongoDB?
![螢幕擷取畫面 2022-04-25 140547](https://user-images.githubusercontent.com/104342462/165030643-62b2c015-e374-427d-b7d7-0b0b1b5ad037.png)
Again, apologies for my poor computer skills...

**Comment by 4Benj** [comment]
You need to open the folder in command prompt and run `gradlew jar` to actually build (it actually says `To run a build, run gradlew <task>` and in our case the task is called jar). iirc running the gradlew.bat file standalone will download the latest gradle version and the dependences for the project but running `gradlew jar` already takes care of that for you anyway.

**Comment by lunaticwhat** [comment]
It's normal tho. Actually you dont need to run `gradlew.bat` before compile. just type in `gradlew jar` directly in the cmd. 
but for some reason on some machine gradle wrapper couldn't setup its environment so we need to run `gradlew.bat`.

**Comment by Art0rias198** [comment]
So I just need to type in gradlew jar in the cmd?
but this happen...
![image](https://user-images.githubusercontent.com/104342462/165036027-9d0f9eb6-ebfd-4f81-adc4-190fc58a1223.png)

**Comment by biubiupiu320** [comment]
> So I just need to type in gradlew jar in the cmd? but this happen... ![image](https://user-images.githubusercontent.com/104342462/165036027-9d0f9eb6-ebfd-4f81-adc4-190fc58a1223.png)

You need to execute the command in the root directory of the project.

**Comment by 4Benj** [comment]
> So I just need to type in gradlew jar in the cmd? but this happen... ![image](https://user-images.githubusercontent.com/104342462/165036027-9d0f9eb6-ebfd-4f81-adc4-190fc58a1223.png)

Navigate to your grasscutter directory using `cd <directory_path>`. If it's on another drive, first type the drive letter followed by `:`. For Example:
`B:` (Grasscutter is on B:\ drive)
`cd B:\servers\grasscutter` (Grasscutter is in the servers\grasscutter folder from the root of the `B:`)
`gradlew jar` (Build grasscutter)

**Comment by Art0rias198** [comment]
FUCK me. I shouldn't study literature in college. 
![Screenshot 2022-04-25 152946](https://user-images.githubusercontent.com/104342462/165041223-767d2193-c53a-4a99-b617-40f40d6fc355.png)
Something goes wrong? I guess...

**Comment by Art0rias198** [comment]
I tried to run it again and it's still happened....
![image](https://user-images.githubusercontent.com/104342462/165056707-4f5197b6-42b9-48b4-899f-03138557f04f.png)

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
