### ISSUE TITLE
[Bug] drop.json未能生效 drop.json does not take effect

### ISSUE THREAD

**Issue by Adelaide114514** [Melledy/Grasscutter#2213]
在我gc核心更新至3.7版本后 无论是原版drop.json或者是魔改后drop.json 或是不放drop使用核心内部自带的都无掉落产生 这将是一个重大的问题 核心也更换了不少

After I gc core update to version 3.7 Whether the original drop. Json or the magic changed after drop. The json or not to put the drop is no drop to produce the core internal used to own It would be a major problem The core also change a lot

**Comment by KingRainbow44** [comment]
drops have been moved to resources to match what they should be, try checking there first
