### ISSUE TITLE
how do i add a reliquary？

### ISSUE THREAD

**Issue by biubiupiu320** [Melledy/Grasscutter#222]
All reliquary don't have main prop and affix. How can i solve this problem?

**Comment by tb114514** [comment]
兄弟怎么搞开的，我服务起了，端口也能查到，就是连不上，你是怎么解决的

**Comment by biubiupiu320** [comment]
> 兄弟怎么搞开的，我服务起了，端口也能查到，就是连不上，你是怎么解决的

要开代理把流量转发到本地服务才能连上。他说了两个软件，mitmproxy和fiddler，我比较推荐fiddler。下载fiddler之后，首先工具栏选tools下的第一个选项Options，点开之后HTTPS标签页勾选Decrpty HTTPS，Connections标签页把端口改成8181。然后保存关闭。到主页右边找到FiddlerScript标签页，把里面的代码全删了，把这个链接里面的代码复制进去。https://github.com/Grasscutters/Grasscutter/wiki/Resources#fiddler-classic-jscript。
然后打开国服客户端就行，在要进入登录界面的时候，fiddler会弹窗，点yes就行。

**Comment by YaeRiko** [comment]
> > 兄弟怎么搞开的，我服务起了，端口也能查到，就是连不上，你是怎么解决的
> 
> 要开代理把流量转发到本地服务才能连上。他说了两个软件，mitmproxy和fiddler，我比较推荐fiddler。下载fiddler之后，首先工具栏选tools下的第一个选项Options，点开之后HTTPS标签页勾选Decrpty HTTPS，Connections标签页把端口改成8181。然后保存关闭。到主页右边找到FiddlerScript标签页，把里面的代码全删了，把这个链接里面的代码复制进去。[https://github.com/Grasscutters/Grasscutter/wiki/Resources#fiddler-classic-jscript。](https://github.com/Grasscutters/Grasscutter/wiki/Resources#fiddler-classic-jscript%E3%80%82) 然后打开国服客户端就行，在要进入登录界面的时候，fiddler会弹窗，点yes就行。

哥们，fiddler网上教的少，能教下到底怎么还原fiddler吗，没用过，现在回不去了

**Comment by biubiupiu320** [comment]
> > > 兄弟怎么搞开的，我服务起了，端口也能查到，就是连不上，你是怎么解决的
> > 
> > 
> > 要开代理把流量转发到本地服务才能连上。他说了两个软件，mitmproxy和fiddler，我比较推荐fiddler。下载fiddler之后，首先工具栏选tools下的第一个选项Options，点开之后HTTPS标签页勾选Decrpty HTTPS，Connections标签页把端口改成8181。然后保存关闭。到主页右边找到FiddlerScript标签页，把里面的代码全删了，把这个链接里面的代码复制进去。[https://github.com/Grasscutters/Grasscutter/wiki/Resources#fiddler-classic-jscript。](https://github.com/Grasscutters/Grasscutter/wiki/Resources#fiddler-classic-jscript%E3%80%82) 然后打开国服客户端就行，在要进入登录界面的时候，fiddler会弹窗，点yes就行。
> 
> 哥们，fiddler网上教的少，能教下到底怎么还原fiddler吗，没用过，现在回不去了

怎么还原是啥意思。不想用了直接x掉就行啊。

**Comment by YaeRiko** [comment]
。。。雀食是这样的，我有点nt了

**Comment by yvhekun** [comment]
我也想知道怎么添加有词条的圣遗物

**Comment by 1shin-7** [comment]
replace those json to `resources/ExcelBinOutput`

https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json

https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json

**Comment by yvhekun** [comment]
还研究出了怎么改词条
![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)

**Comment by TheDream0323** [comment]
> 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)

hxd，怎么弄的啊...我只有主词条没有夫词条..

**Comment by Mospisa** [comment]
> 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)

怎么做到的？求教

**Comment by SiegfriedYin** [comment]
同问

**Comment by yvhekun** [comment]
> > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> 
> hxd，怎么弄的啊...我只有主词条没有夫词条..

看楼上的替换掉文件，再进数据库里去改

**Comment by TheDream0323** [comment]
> > > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> > 
> > 
> > hxd，怎么弄的啊...我只有主词条没有夫词条..
> 
> 看楼上的替换掉文件，再进数据库里去改

就是替换了文件  但是只有主词条...

**Comment by yvhekun** [comment]
> > > > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> > > 
> > > 
> > > hxd，怎么弄的啊...我只有主词条没有夫词条..
> > 
> > 看楼上的替换掉文件，再进数据库里去改
> 
> 就是替换了文件  但是只有主词条...

应该要重新生成圣遗物吧，之前的还是没有词条，或者你看看有没有替换错，再替换一次

**Comment by KingRainbow44** [comment]
the title shows signs of asking for help, not a bug.
if this isn't the case feel free to reopen the issue.

standard copy paste:
this isnt a support forum, this is an issue tracker. check the discord if you need help.

**Comment by ImZjm** [comment]
> > > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> > 
> > 
> > hxd，怎么弄的啊...我只有主词条没有夫词条..
> 
> 看楼上的替换掉文件，再进数据库里去改

数据库里面要怎么改词条

**Comment by yvhekun** [comment]
> > > > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> > > 
> > > 
> > > hxd，怎么弄的啊...我只有主词条没有夫词条..
> > 
> > 看楼上的替换掉文件，再进数据库里去改
> 
> 数据库里面要怎么改词条

圣遗物在items里面，然后搜出你有的圣遗物，其中appendpropIdList: Array那个就是你圣遗物的词条，修改那个数字就行了

**Comment by tb114514** [comment]
> > > > > 还研究出了怎么改词条 ![image](https://user-images.githubusercontent.com/62101581/165098803-97b7c7fe-3771-4bb7-9d65-d3f3f1325e2b.png)
> > > > 
> > > > 
> > > > hxd，怎么弄的啊...我只有主词条没有夫词条..
> > > 
> > > 
> > > 看楼上的替换掉文件，再进数据库里去改
> > 
> > 
> > 数据库里面要怎么改词条
> 
> 圣遗物在items里面，然后搜出你有的圣遗物，其中appendpropIdList: Array那个就是你圣遗物的词条，修改那个数字就行了

那个怎么改啊，能具体发个图吗

**Comment by SiegfriedYin** [comment]
![屏幕截图 2022-04-26 132955](https://user-images.githubusercontent.com/46700441/165228339-7d90fd55-710c-45d6-b26f-79418b73766c.png)
在这个项目下增加条目就行，注意数值类型为Int32
0~3为初始词条，从4开始为每次强化的词条
例如501204就是暴击率3.9%，501224是暴击伤害7.8%
具体其他词条代表的数值还在摸索，如果有大哥弄出来了请踢我一脚

**Comment by yvhekun** [comment]
> ![屏幕截图 2022-04-26 132955](https://user-images.githubusercontent.com/46700441/165228339-7d90fd55-710c-45d6-b26f-79418b73766c.png)
> 在这个项目下增加条目就行，注意数值类型为Int32
> 0~3为初始词条，从4开始为每次强化的词条
> 例如501204就是暴击率3.9%，501224是暴击伤害7.8%
> 具体其他词条代表的数值还在摸索，如果有大哥弄出来了请踢我一脚

501064是5.8攻击
501234是6.8充能
501244是23精通

**Comment by biubiupiu320** [comment]
> ![屏幕截图 2022-04-26 132955](https://user-images.githubusercontent.com/46700441/165228339-7d90fd55-710c-45d6-b26f-79418b73766c.png) 在这个项目下增加条目就行，注意数值类型为Int32 0~3为初始词条，从4开始为每次强化的词条 例如501204就是暴击率3.9%，501224是暴击伤害7.8% 具体其他词条代表的数值还在摸索，如果有大哥弄出来了请踢我一脚

我已经研究明白了。ExcelBinOutput文件夹下面有两个文件，ReliquaryAffixExcelConfigData.json和ReliquaryMainPropExcelConfigData.json。Affix这个文件是副词条文件，Main是主词条文件。这两个文件打开后，里面有共同的字段Id和PropType。Id字段就是跟数据库里面mainPropId和appendPropIdList对应的，PropType字段代表这个词条是什么类型的(这个自己翻译一下就知道了)。想要修改一个圣遗物的主词条，直接到ReliquaryMainPropExcelConfigData.json这个文件找自己想要的主词条Id，然后把数据库里面的mainPropId字段改了就行(主词条数值好像不能改，是固定的)。想修改副词条就到ReliquaryAffixExcelConfigData.json这个文件找自己想要的副词条和数值(PropValue字段代表的就是数值)对应的Id，然后修改appendPropIdList这个字段(想怎么改就怎么改，你把这个字段数组清空了只写一个也行)。
