### ISSUE TITLE
[Bug] Grasscutter3.7跟原神3.7有多個BUG

### ISSUE THREAD

**Issue by gg54452454** [Melledy/Grasscutter#2235]

**Comment by ghost** [comment]
> **DataEase 版本** 未知
> 
> **运行方式(安装包运行 or 源码运行 ?)** 源码运行(Cultivation.exe)
> 
> **浏览器版本** GOOGLE CHROME 114.0.5735.134
> 
> **Bug 描述** 原神官方下載的3.7版本 遊戲過程有使用GcTools-v1.10.0的指令工具並依需求在遊戲內聊天框輸入指令+我的能力有限無法再模擬出一樣的狀況拍攝遊戲照片上來
> 
> 1. 新創’帳號選完兄或妹跟名稱再經過過場動畫結束後，要進入提瓦特地圖，主線開始前，畫面會卡在讀取中，關閉遊戲重新登入，主線才開始從海邊有螃蟹場景，旅行者釣起派蒙的啟端開始過主線任務
> 2. 主線疑 (隨風而來的騎士:使用安柏消滅空中的史萊姆)，接著需要切換角色2(安柏)射擊空中的風史萊姆，當角色隊伍已配有4個角色(有輸入獲得4隻以上~全部角色)的時候，會造成角色2不會自動加入安柏，遊戲就會整個卡死，只能1234換角色，最終只能重創角色從頭開始玩(隊伍內的2號位置等於不能有其他角色)
> 3. 聊天處輸入指令，只要獲得全部物品，遊戲會嚴重LAG，要對角色進行裝扮或更換風之翼，遊戲會無反應(=物品不能獲得超過好幾千以上)
> 4. 獲得全部武器或物品後，會獲得部分沒圖案的武器跟物品跟部分無數值的武器
> 5. 指令獲得部分或全部角色後有玩該角色的專屬任務後會出現幾種奇怪狀況，當試用角色在密境內的隊伍第5號位置，離開秘境後，第5號位置的角色不會消失，快速配隊時，需要手動取消第5號角色，該角色會變成直接獲得，因為角色圖案右上角的試用2個字不見了(包含安柏.凱亞.麗莎.香笭，之後角色任務會不會發生，我尚未玩到)，他還會把原本的命之座.角色等級.技能等級都重置成試用角色狀態跟對應角色有出的有用指令獲得的時裝也會消失，導致依當初用指令獲得角色命之座角色等及技能等級都要重新弄，命之座如再用指令，直接變6命座或用角色專屬的命座道具增加命座，重弄後導致那些受影響角色，有2個命之座會增加3等的EQ技能，會被消失，EQ技能不會有藍字說他有增加EQ技能等級，天賦書將技能等級只能到10，就算輸入指令上限到10也是一樣狀況，而且他指令輸入等級範圍上限可以到達15，當輸入指令獲得11~15等的EQ技能會變成0無效狀態
> 6. 未知是主線還是迪盧克任務(疑暗夜英雄危機)，旅行者要到晨曦酒莊外面跟迪盧克對話後，要消滅深淵法師，如果任務，在此卡住沒提示在哪消滅，任務不能完成，就算輸入指令直接完成也沒用，還是卡在要消滅深淵法師，如輸入指令去重接，重新手動跟迪盧克對話後，任務有提示在酒莊下方靠近河邊的位置可以消滅深淵法師，但是根本看不到深淵法師，輸入指令測試幾次重新接任跟完成任務(我當下並沒輸入此任務以外的其他的指令)，然後出現大BUG，會出現璃月~稻棲之間，還沒過的傳說邀約支線任務跟空白跟測試任務，然後出現沒完成空白任務跟古云任務不能傳送到其他地點，暫時去完成其他任務，因為出現空白任務我沒辦法用指令隱藏對應的空白任務
> 7. 將角色移動試用角色密境場景，他會從密境最上方不正常的位置下來，如果又卡在上述無法傳送問題，他會一直重複切換場景跟提示上面2個任務沒有完成不能傳送，這個時候遊戲就沒辦法玩了，強制手動關閉遊戲重登再進去也一樣一直重複同樣狀況(只能又要重創帳號頭開始玩)
> 8. 天賦武器素材密境，不能進去打，疑似沒加入每日要打的對應素材
> 9. 聖遺物密境跟獲得凱亞.安柏.麗莎獎勵的密境有BUG，選擇離開密境，會卡在密境裡面出不來跟不能移動也還看不到自己的角色跟切換角色，只能輸入指令重登或關遊戲重登或疑似可以等離開密境倒數時間結束被遊戲強制傳送出密境(但要等999秒)
> 10. 七天神像無法用對應的神瞳升級，回血量只能用最初的85000，輸入回血量相關的指令無效，(雪山冷冬之樹.稻棲神櫻樹.須彌的夢之樹疑似也不能對話升級)

去discord問，在這裡問沒有在discord好。

**Comment by KingRainbow44** [comment]
these are mostly intended/unimplemented features, as such, none will be addressed
