### ISSUE TITLE
What are the differences between these models? Or where?

### ISSUE THREAD

**Issue by Tomiaocat** [Melledy/Grasscutter#225]
![CTR@ JAH2X%0@9UFSOGB)8J](https://user-images.githubusercontent.com/23458602/165038766-9e51d7eb-7f79-4982-b2ca-58993d40466d.png)

**Comment by 4Benj** [comment]
Handbook creates the GM_Handbook.txt file.
I'm not sure about game or auth modes but it looks like an early implementation of the configurable run modes in config I implemented earlier but it doesn't seem like it does anything. I must have missed that those values already exist.

**Comment by Tomiaocat** [comment]
> 



> Handbook creates the GM_Handbook.txt file. I'm not sure about game or auth modes but it looks like an early implementation of the configurable run modes in config I implemented earlier but it doesn't seem like it does anything. I must have missed that those values already exist.

I thought I could play games in it, but after I actually ran it, I found that I couldn't do anything in it. I had to walk in it

**Comment by 4Benj** [comment]
> I thought I could play games in it, but after I actually ran it, I found that I couldn't do anything in it. I had to walk in it

In what?

**Comment by Tomiaocat** [comment]
> > I thought I could play games in it, but after I actually ran it, I found that I couldn't do anything in it. I had to walk in it
> 
> In what?

 In what?

 there:
![I}TQBZSWU}8UWT)_T94FT J](https://user-images.githubusercontent.com/23458602/165041357-8eeef0ec-8327-4884-a38a-548f4049f3bf.jpg)

**Comment by Tomiaocat** [comment]
I don't see NPCs or monsters

**Comment by 4Benj** [comment]
Ohhhhh...
Yeah, we don't have automatic spawning yet. NPC should still spawn in the cities but not in the wild and monsters have to be spawned in using the `/spawn` command

**Comment by Tomiaocat** [comment]
> 

3qu  ,i will have try
