### ISSUE TITLE
[Feature Request] Hope to support version 3.8 soon

### ISSUE THREAD

**Issue by momo54181** [Melledy/Grasscutter#2258]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MLChinoo** [comment]
never

**Comment by kelsegs** [comment]
grasscutter DIED in 3.8

**Comment by KingRainbow44** [comment]
its gonna take a bit 😔

**Comment by simple-shadow** [comment]
Adaptation takes time. Developers may be busy with their lives. Please be patient as revisions are made.

**Comment by minhoag** [comment]
Pay the dev 3000$ a month for a year then, they will work for you and you will have 3.8 GIO. If you can’t? Stop asking
