### ISSUE TITLE
[Bug] i can'nt offer the Anemoculus to the statue

### ISSUE THREAD

**Issue by tienleokaka** [Melledy/Grasscutter#2267]
help me, please i can'nt offer the Anemoculus to the statue
I play normally and haven't used any commands yet 
![Screenshot_34](https://github.com/Grasscutters/Grasscutter/assets/139669190/f1fda4c6-deab-4fbe-8915-fa4d7f23f620)
![Screenshot_33](https://github.com/Grasscutters/Grasscutter/assets/139669190/ddf6d998-3bf5-4e65-98d6-a8b3c6d9bb69)
![Screenshot_36](https://github.com/Grasscutters/Grasscutter/assets/139669190/57f3443b-ac1c-4550-ac5f-2da1986ad6a0)

**Comment by cyno-cyno** [comment]
Don’t ask again!

**Comment by scooterboo** [comment]
Some things aren't implemented yet. Mainly we are focused on quests.

**Comment by tienleokaka** [comment]
> 

Sorry?

**Comment by tienleokaka** [comment]
> 

Can't handle this case? :(

**Comment by KingRainbow44** [comment]
associated with [this conversation](https://discord.com/channels/965284035985305680/1129988125989535844/1130010034756132934) on Discord
