### ISSUE TITLE
Elemental skill (E) does not be affectted by constellation

### ISSUE THREAD

**Issue by KanNguyenKiet** [Melledy/Grasscutter#228]
Some elemental skills of characters such as Xiao, Ganyu, Shenhe don't increase their stack when unlock constellations (Xiao C1, Ganyu C2,  Shenhe C1), idk it is a bug or I make some mistakes when installing server :(

**Comment by memetrollsXD** [comment]
Not implemented, charged skills are done by AvatarDataNotify and not SceneTeamUpdateNotify. So far no Pull Requests implementing these constellations

**Comment by fanshu-520** [comment]
https://user-images.githubusercontent.com/79776977/166135909-bc9eb012-16ee-46cf-b1c9-a557d73c978c.MP4

if you disconnect the server and reconnect the extra skills will disappear
