### ISSUE TITLE
[Feature Request] implement QUEST_EXEC_ACTIVE_ITEM_GIVING and QUEST_CONTENT_FINISH_ITEM_GIVING

### ISSUE THREAD

**Issue by scooterboo** [Melledy/Grasscutter#2280]
**Is your feature request related to a problem? Please describe.**

QUEST_EXEC_ACTIVE_ITEM_GIVING and QUEST_CONTENT_FINISH_ITEM_GIVING are found in quests where you need to submit an item to an NPC.

Example quests with these enums:
48902
48903
48904

1200602

1111222

201210
201216

1100513

**Describe the solution you'd like**

make grasscutter do the thing

**Describe alternatives you've considered**

Make QUEST_EXEC_ACTIVE_ITEM_GIVING trigger QUEST_CONTENT_FINISH_ITEM_GIVING. This would make a submission quest instafinish, but would anger Hartie.

**Additional context**

This is the third biggest bug holding back quest progress.

**Comment by KingRainbow44** [comment]
or i can just implement it rq

**Comment by KingRainbow44** [comment]
fixed in #2314

**Comment by KingRainbow44** [comment]
I CLOSED THE WRONG ISSUE LOL

**Comment by scooterboo** [comment]
I'm actually pretty happy with what you have implemented.
200920/200916 can be seen as a bug and be handled separately.
