### ISSUE TITLE
[Bug] No response was received after interacting with the roots after completing the Domain of Blessing

### ISSUE THREAD

**Issue by Phong940253** [Melledy/Grasscutter#2282]
**Did you look for other closed issues that have the same problem?**

Yes

**Describe the bug**

No response was received after interacting with the roots after completing the Domain of Blessing.

**Which branch did you use?**

Grasscutter version: 1.6.2-76e940bc

**Screenshots**

![ảnh](https://github.com/Grasscutters/Grasscutter/assets/40328498/567f3c6a-5a48-4f1f-9a98-b42f870b8d3a)

After the interaction no response occurs
![ảnh](https://github.com/Grasscutters/Grasscutter/assets/40328498/7b790bcf-9262-4658-a6e4-f98e517a21c8)

**Additional context**

**Comment by Curr-Ronaldo** [comment]
请问有res资源文件嘛
