### ISSUE TITLE
我搭建起来怎么角色不能攻击，有大佬解答一下么

### ISSUE THREAD

**Issue by Curr-Ronaldo** [Melledy/Grasscutter#2285]
游戏搭建起来过后，角色不能进行普攻，是哪里没设置对嘛 有无佬解答一下昂！

**Comment by MLChinoo** [comment]
check your resources

**Comment by Curr-Ronaldo** [comment]
res资源现在在哪里可以下载昂

> 



> 检查您的资源

**Comment by makexiao113** [comment]
我是到了第二个锚点才能攻击的

**Comment by NDECenziken** [comment]
给你我珍藏的res地址https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.7?ref_type=heads
这个res会有人维护，修复bug

**Comment by Adelaide114514** [comment]
#2214 寻找你的答案
