### ISSUE TITLE
大佬们，游戏有音效声，但角色没有说话声音

### ISSUE THREAD

**Issue by 14790897** [Melledy/Grasscutter#2289]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by ghost** [comment]
语音包

**Comment by 14790897** [comment]
> 语音包

大佬请问语音包去哪下载？是用那个安装程序安装一下嘛，我一开始下的是那个40几GB的压缩包

**Comment by ghost** [comment]
别在Github问可以吗？我来亲自解决。

**Comment by NotThorny** [comment]
All of them are available on the archive repository:
https://github.com/MAnggiarMustofa/GI-Download-Library/blob/main/GenshinImpact/Audio/3.7.0.md

**Comment by 14790897** [comment]
> All of them are available on the archive repository: https://github.com/MAnggiarMustofa/GI-Download-Library/blob/main/GenshinImpact/Audio/3.7.0.md
than kyou
