### ISSUE TITLE
Could I ask that how to open the console to use the command?

### ISSUE THREAD

**Issue by fatboy112233** [Melledy/Grasscutter#229]
This is my first time to do this.I just a green hand here and I have no idea about the server(MongoDB).Please give me a hand.
![屏幕截图(33)](https://user-images.githubusercontent.com/75034012/165050590-b8f05581-b82c-446e-b5aa-740ee42fb3d4.png)

![屏幕截图 2022-04-25 162329](https://user-images.githubusercontent.com/75034012/165050629-53b16c16-33cc-4f86-815d-9e755dd71046.png)
![屏幕截图 2022-04-25 162357](https://user-images.githubusercontent.com/75034012/165050659-0882b408-5f2b-492c-ad1c-d266af987ccb.png)
![屏幕截图 2022-04-25 162427](https://user-images.githubusercontent.com/75034012/165050684-c0b5f336-e59f-4691-a1d3-3ca99eb24691.png)

**Comment by F-Unction** [comment]
Just type `help` in the server console and enter.
