### ISSUE TITLE
[Bug] 打败风魔龙，完成序章第一幕后未解锁结界

### ISSUE THREAD

**Issue by Muhu-C** [Melledy/Grasscutter#2290]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by Muhu-C** [comment]
现在结界还卡在蒙德城周围，部分传送锚点无法打开，走过去就会有派蒙说”前面的区域以后再探索吧“

**Comment by Rush-525** [comment]
你可以在游戏中的控制台输入/unlockall 解锁所有限制，但似乎解锁时候蒙德的商店会变得不可用

**Comment by makexiao113** [comment]
现在感觉bug还是挺多的，秘境打完没有触发结算

**Comment by KingRainbow44** [comment]
what's the exact bug here, someone please translate

**Comment by FHU-yezi** [comment]
> what's the exact bug here, someone please translate

When a new traveler finish the Mondstadt task, the barrier around Stromterror’s Lair would not disappear and we can't walk in.

**Comment by zhimiguance** [comment]
期待
