### ISSUE TITLE
[Bug] wish dont play scene

### ISSUE THREAD

**Issue by ultard** [Melledy/Grasscutter#2293]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

i cant wish to baners, when i click button nothing happens.

**Which branch did you use?**

**Screenshots**

![изображение](https://github.com/Grasscutters/Grasscutter/assets/63789651/f572940a-2ba8-42fb-918c-f31a7ffbbe93)

**Additional context**

**Comment by KingRainbow44** [comment]
follow format, edit then reopen or make a new issue
