### ISSUE TITLE
I can use netstat to scan the server port of 22102 but I can't connect with telnet

### ISSUE THREAD

**Issue by tb114514** [Melledy/Grasscutter#230]
I can use netstat to scan the server port of 22102 but I can't connect with telnet
![捕获](https://user-images.githubusercontent.com/104314428/165051954-8a2c11f5-c478-4123-a7e9-1682efa19264.PNG)
.

**Comment by cryingcheems** [comment]
y u need use telnet?
use create account command in grasscutter.jar launch command window,pls!

**Comment by tb114514** [comment]
> 你需要使用原则吗？
Connection test instructions

**Comment by tb114514** [comment]
> y u need use telnet? use create account command in grasscutter.jar launch command window,pls!



> 你需要使用telnet吗？ 在 Grasscutter.jar 启动命令窗口中使用创建帐户命令，请！
![捕获d](https://user-images.githubusercontent.com/104314428/165056691-4b286c2b-109d-4f5c-8b25-441b4c768d02.PNG)

The user has been created

**Comment by F-Unction** [comment]
so why you need telnet

**Comment by tb114514** [comment]
我测试端口服务是否开启

**Comment by F-Unction** [comment]
You need't to test, it was certainly opened

**Comment by cryingcheems** [comment]
try use `netstat -ano | findstr "22102"`

**Comment by tb114514** [comment]
![捕的获](https://user-images.githubusercontent.com/104314428/165058007-e00db16d-5cf1-4f89-ae0a-48b1d979b4e6.PNG)

**Comment by cryingcheems** [comment]
> ![捕的获](https://user-images.githubusercontent.com/104314428/165058007-e00db16d-5cf1-4f89-ae0a-48b1d979b4e6.PNG)

yeah! it's open

**Comment by tb114514** [comment]
我再看看

**Comment by F-Unction** [comment]
It looks like you want to verify the server is working or not.
Telnet is a tool to verify the port is open or not. To use it, you should close your server and use `telnet open port` first, then, you use `telnet` To see the port is available or not.
And for the server, you don't need to worry about it. Server will tell you about it if the port is unavailable.

**Comment by tb114514** [comment]
> 看起来您想验证服务器是否正常工作。 Telnet 是一个验证端口是否打开的工具。要使用它，您应该`telnet open port`先关闭服务器并使用它，然后，您使用`telnet`来查看端口是否可用。 而对于服务器，您无需担心。如果端口不可用，服务器会告诉你。
![屏幕截图(5)](https://user-images.githubusercontent.com/104314428/165060696-844746be-c4bb-4b87-893a-19acd98b4550.png)
I started it with the client GrassClipper and that was it

**Comment by tb114514** [comment]
> 您的服务器工作正常。 Telnet 是一个需要`telnet open port`先查看端口是否关闭验证的工具。使用您，应该使用它，然后，您使用来`telnet`查看它是否可用。 而对于服务器，您不必担心它是否正常。如果端口不可用，服务器会告诉你。
![屏幕截图(5)](https://user-images.githubusercontent.com/104314428/165061065-55f3ce10-feb6-4640-bb7c-ab8ffff66833.png)

**Comment by tb114514** [comment]
![屏幕截图(5)](https://user-images.githubusercontent.com/104314428/165061146-86f45a0b-9012-4993-957d-b845705c6426.png)

**Comment by tb114514** [comment]
> 您的服务器工作正常。 Telnet 是一个需要`telnet open port`先查看端口是否关闭验证的工具。使用您，应该使用它，然后，您使用来`telnet`查看它是否可用。 而对于服务器，您不必担心它是否正常。如果端口不可用，服务器会告诉你。

我图怎么发不上去

**Comment by F-Unction** [comment]
> > 您的服务器工作正常。 Telnet 是一个需要`telnet open port`先查看端口是否关闭验证的工具。使用您，应该使用它，然后，您使用来`telnet`查看它是否可用。 而对于服务器，您不必担心它是否正常。如果端口不可用，服务器会告诉你。
> 
> 我图怎么发不上去

你图发上去了 但是能不能把服务器的日志露出来

**Comment by tb114514** [comment]
> > > 您的服务器工作正常。 Telnet 是一个需要`telnet open port`先查看端口是否关闭验证的工具。使用您，应该使用它，然后，您使用来`telnet`查看它是否可用。 而对于服务器，您不必担心它是否正常。如果端口不可用，服务器会告诉你。
> > 
> > 
> > 我图怎么发不上去
> 
> 你图发上去了 但是能不能把服务器的日志露出来
日志路径在哪啊

**Comment by F-Unction** [comment]
服务器控制台窗口 看看有没有报错

**Comment by F-Unction** [comment]
[install_instuction.pdf](https://github.com/Grasscutters/Grasscutter/files/8553322/install_instuction.pdf)
follow the instruction.

**Comment by tb114514** [comment]
> > > 您的服务器工作正常。 Telnet 是一个需要`telnet open port`先查看端口是否关闭验证的工具。使用您，应该使用它，然后，您使用来`telnet`查看它是否可用。 而对于服务器，您不必担心它是否正常。如果端口不可用，服务器会告诉你。
> > 
> > 
> > 我图怎么发不上去
> 
> 你图发上去了 但是能不能把服务器的日志露出来
![捕](https://user-images.githubusercontent.com/104314428/165062397-3cbdbcf5-9934-42ff-8afe-f98db03f84ca.PNG)



> 服务器外观检查有没有报错

**Comment by tb114514** [comment]
> [install_instuction.pdf](https://github.com/Grasscutters/Grasscutter/files/8553322/install_instuction.pdf) follow the instruction.

好的我看看

**Comment by tb114514** [comment]
> [install_instuction.pdf](https://github.com/Grasscutters/Grasscutter/files/8553322/install_instuction.pdf) follow the instruction.

谢谢谢谢谢谢谢谢谢搞定了谢谢谢谢谢谢
