### ISSUE TITLE
The drawn character cannot attack and cannot release skills.

### ISSUE THREAD

**Issue by kafeim** [Melledy/Grasscutter#231]
The drawn character cannot attack and cannot release skills.

**Comment by guch8017** [comment]
Review the program output from console. If there is an error log saying that the program failed to load some data, it will cause this problem. Refer to the [wiki](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server) and follow the step and try again (especially the 2.ii step)

**Comment by kafeim** [comment]
![image](https://user-images.githubusercontent.com/38217057/165057823-ac3b4f2a-2ddd-4097-93b7-0e65f650af43.png)


The release skills have actions but no special effects, and normal attacks cannot attack. It is normal for the protagonist to release skills and normal attacks

**Comment by kafeim** [comment]
> 查看控制台的程序输出。如果有错误日志说程序未能加载某些数据，就会导致这个问题。参考[wiki](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server)并按照步骤重试（尤其是2.ii步骤）


![image](https://user-images.githubusercontent.com/38217057/165058683-5dbb67c6-cb91-45df-968c-f20045fff7d4.png)


The release skills have actions but no special effects, and normal attacks cannot attack. It is normal for the protagonist to release skills and normal attacks

**Comment by memetrollsXD** [comment]
Please use https://github.com/radioegor146/gi-bin-output/tree/master/2.5.52/Data/_BinOutput for BinOutput

**Comment by akbarsar** [comment]
> Please use https://github.com/radioegor146/gi-bin-output/tree/master/2.5.52/Data/_BinOutput for BinOutput

Hi, this repository was taken down. What can i do to fix the issue now?

**Comment by memetrollsXD** [comment]
https://github.com/Koko-boya/Grasscutter_Resources/
