### ISSUE TITLE
[Bug] 4.0版本更新后 角色倒下后不自动切换 和 角色无法食用

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#2310]
1.在角色倒下后，不会自动切换其他角色。
![屏幕截图 2023-08-27 090451](https://github.com/Grasscutters/Grasscutter/assets/121497312/f45457dc-777e-44f3-bf5f-e6164bcd9028)
2.角色倒下后，无法食用复活类食物（如提瓦特煎蛋）
显示服务器内部错误（如图）
![image](https://github.com/Grasscutters/Grasscutter/assets/121497312/f5a4d568-8129-4b3a-a28c-06c7718e36d6)
请问要如何解决这两个问题

**Comment by FFVenti** [comment]
English:
1. when the character is fallen, the system will keep him on the field.And i can't switch other character .
2. when the character is fallen, he/she can't eat recovery dishes, like "Teyvat Fried Egg".And it will show"Internal Server Error".
i need help, pls. thx!

**Comment by Cuthon** [comment]
而且角色似乎无法通过神像以外的手段来回血，就连使用技能也无法回血，只能使用指令

**Comment by lipervol** [comment]
我找到了解决方法：
在src\main\java\emu\grasscutter\game\player\TeamManager.java下更改以下部分：
![image](https://github.com/Grasscutters/Grasscutter/assets/47234928/82c8f81b-7013-4015-a90e-f86bcfe6baee)
将这段代码注释掉重新编译即可。
以下部分不知道是不是需要改（待验证）：
在src\main\java\emu\grasscutter\game\entity\GameEntity.java中
![image](https://github.com/Grasscutters/Grasscutter/assets/47234928/67557e22-c5a0-4927-a966-2d72c07e4e38)
将isDead定义为public Boolean isDead
在E:\java_project\GSServer-GC\src\main\java\emu\grasscutter\game\entity\EntityAvatar.java中更改以下部分：
![image](https://github.com/Grasscutters/Grasscutter/assets/47234928/16404da2-9baa-4930-a26e-c032fe1971a3)
然后重新编译即可，祝你游戏愉快

**Comment by lipervol** [comment]
验证后：上一条评论的第二处和第三处改动是必要的，此外，还需要在src\main\java\emu\grasscutter\game\entity\EntityAvatar.java改动以下部分：
![image](https://github.com/Grasscutters/Grasscutter/assets/47234928/7772d601-d045-47e1-af97-c1943a37c4da)
全部改完之后重新编译，经过测试可以完美解决问题

**Comment by lipervol** [comment]
好吧，其实还有几处需要改，我说一下BUG的原因：BUG的原因是角色死亡后生命值不一定为0，我发现角色在准备倒下的时候受到攻击会恢复生命值，此外特殊死亡也会回满生命值，需要在damage函数中使其在判断角色死亡后直接return，同样在判断角色特殊死亡后生命值使其归0即可

**Comment by KingRainbow44** [comment]
just pushed the fix to this, thanks for helping!

**Comment by Deskable** [comment]
经测试复活问题解决 @lipervol

另外想问下食物复活问题是怎么解决的?
