### ISSUE TITLE
[Bug] Too many requests may cause players to drop

### ISSUE THREAD

**Issue by PDMengQAQ** [Melledy/Grasscutter#2324]
When the number of players reaches 8 or more, the game client may struggle to handle additional login requests, resulting in players getting disconnected or experiencing a blank screen.
![02cf57bce4e1e80bd945743522100b83](https://github.com/Grasscutters/Grasscutter/assets/109350933/f8bd3e6f-5aed-4b3c-a584-11b9ea0f2966)
We couldn't deal with this problem,
Thank you for your help

**Comment by Adelaide114514** [comment]
人数上升后玩家不仅掉线白屏还会随机抽选幸运玩家重复登陆被kick[并不是重复登陆 单纯随机抽选玩家kick]
After the number of players increases, not only will they be disconnected and the screen will be blank, but they will also randomly select lucky players to be kicked for repeated
![9dabcb59cf0b62776b4278295aa026fb](https://github.com/Grasscutters/Grasscutter/assets/105539565/b8829f1f-a469-44c0-adba-8429d777bc00)
 login

**Comment by PDMengQAQ** [comment]
The issue has been resolved
It will be pulled request by Ad later :D
