### ISSUE TITLE
[Bug] There's no console option when you close Big World Scripts and Quests.

### ISSUE THREAD

**Issue by guyucc** [Melledy/Grasscutter#2330]
There's no console option when you close Big World Scripts and Quests.
![f24f36a4d45df1d27fa2939cd783ba23](https://github.com/Grasscutters/Grasscutter/assets/111928275/77bf6b0d-f8f9-4735-968c-01da0e65b520)

**Comment by guyucc** [comment]
> info
01:13:03 <INFO:CommandMap> Command used by server console: info
01:13:03 <INFO:CommandHandler> Created by Meledy
- currently maintained by KingRainbow44
- formerly maintained by Birdulon

Other Credits
 - Slushy Team (akio, azzu, Areha11Fz, tamil; protocol)
 - Yuki (resource minifying & packaging)
 - Dimbreath (dumping most resources)
01:13:03 <INFO:CommandHandler> Server Information
Revision: 1.7.0 (89efa35f8)
Player Count: 2
Questing Enabled: false
Scripts Enabled: false
Operating System: true
Using Fast Require: Windows 10
Resource Information: {
  "repository": "gitlab.com/YuukiPS/GC-Resources",
  "version": "4.0.0",
  "patches": "Amber,Custom",
  "scripts": "OFFICIAL",
  "hasNoLocals": false,
  "hasServerResources": true,
  "hasSceneScriptData": true
}

**Comment by KingRainbow44** [comment]
what do you mean
> there's no console option

you ran the info command, are you talking about the in-game bot for sending commands to?

**Comment by guyucc** [comment]
> what do you mean
> 
> > there's no console option
> 
> you ran the info command, are you talking about the in-game bot for sending commands to?

yes

**Comment by guyucc** [comment]
> what do you mean
> 
> > there's no console option
> 
> you ran the info command, are you talking about the in-game bot for sending commands to?

And there will be no chat option in the bottom left corner of the new account after turning off quests and big world scripts.

**Comment by KingRainbow44** [comment]
this is probably a client/packet order issue
you can find the bot in the friends menu to talk to; if not reconnect to the server
