### ISSUE TITLE
My character skills cant heal

### ISSUE THREAD

**Issue by DilucXChongyun** [Melledy/Grasscutter#2336]
Hello all,
I have downloaded all of the resources and the latest data. I have realized that my character skills dont heal anyone. Barbara skill and Ult do not, Jean's doesn't, Kuki's doesn't. Any and all help would be apreciated. I believe I am running version 1.7.1 of Grasscutter off of Java

**Comment by lipervol** [comment]
键值没有更新，我修改了一下，在Grasscutter-development\src\main\java\emu\grasscutter\data\binout\AbilityModifier.java中找到并替换以下内容后重新编译即可：
```
        @SerializedName(
                value = "amount",
                alternate = {"LNFMOCKIAGK", "PDLLIFICICJ", "cdRatio"})
        public DynamicFloat amount = DynamicFloat.ZERO;

        @SerializedName(value = "GMFELAKANEF")
        public DynamicFloat amountByCasterAttackRatio = DynamicFloat.ZERO;

        @SerializedName(value = "unused")
        public DynamicFloat amountByCasterCurrentHPRatio = DynamicFloat.ZERO;

        @SerializedName(
            value = "PKPBLCNMPIG",
            alternate = {"HFNJHOGGFKB", "GEJGGCIOLKN"})
        public DynamicFloat amountByCasterMaxHPRatio = DynamicFloat.ZERO;

        public DynamicFloat amountByGetDamage = DynamicFloat.ZERO;

        @SerializedName(value = "amountByTargetMaxHPRatio")
        public DynamicFloat amountByTargetCurrentHPRatio = DynamicFloat.ZERO;

        @SerializedName(value = "GGLMMJHNGMO")
        public DynamicFloat amountByTargetMaxHPRatio = DynamicFloat.ZERO;

```
此外，我发现之前的脚本忽略了元素精通和防御力对角色治疗量的影响，我在Grasscutter-development\src\main\java\emu\grasscutter\game\ability\actions\ActionHealHP.java中修改了以下内容后解决了这个问题：
```
        Object2FloatMap<String> props = ability.getAbilitySpecials();
        props.put("FIGHT_PROP_CUR_DEFENSE",owner.getFightProperty(FightProperty.FIGHT_PROP_CUR_DEFENSE));
        props.put("FIGHT_PROP_ELEMENT_MASTERY",owner.getFightProperty(FightProperty.FIGHT_PROP_ELEMENT_MASTERY));

        var amountByCasterMaxHPRatio = action.amountByCasterMaxHPRatio.get(props,0);
        var amountByCasterAttackRatio = action.amountByCasterAttackRatio.get(props,0);
        var amountByCasterCurrentHPRatio = action.amountByCasterCurrentHPRatio.get(props,0);
        var amountByTargetCurrentHPRatio = action.amountByTargetCurrentHPRatio.get(props,0);
        var amountByTargetMaxHPRatio = action.amountByTargetMaxHPRatio.get(props,0);
        var amountToRegenerate = action.amount.get(props,0);
```

**Comment by Deskable** [comment]
> 键值没有更新，我修改了一下，在Grasscutter-development\src\main\java\emu\grasscutter\data\binout\AbilityModifier.java中找到并替换以下内容后重新编译即可：
> 
> ```
>         @SerializedName(
>                 value = "amount",
>                 alternate = {"LNFMOCKIAGK", "PDLLIFICICJ", "cdRatio"})
>         public DynamicFloat amount = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "GMFELAKANEF")
>         public DynamicFloat amountByCasterAttackRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "unused")
>         public DynamicFloat amountByCasterCurrentHPRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(
>             value = "PKPBLCNMPIG",
>             alternate = {"HFNJHOGGFKB", "GEJGGCIOLKN"})
>         public DynamicFloat amountByCasterMaxHPRatio = DynamicFloat.ZERO;
> 
>         public DynamicFloat amountByGetDamage = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "amountByTargetMaxHPRatio")
>         public DynamicFloat amountByTargetCurrentHPRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "GGLMMJHNGMO")
>         public DynamicFloat amountByTargetMaxHPRatio = DynamicFloat.ZERO;
> ```
> 
> 此外，我发现之前的脚本忽略了元素精通和防御力对角色治疗量的影响，我在Grasscutter-development\src\main\java\emu\grasscutter\game\ability\actions\ActionHealHP.java中修改了以下内容后解决了这个问题：
> 
> ```
>         Object2FloatMap<String> props = ability.getAbilitySpecials();
>         props.put("FIGHT_PROP_CUR_DEFENSE",owner.getFightProperty(FightProperty.FIGHT_PROP_CUR_DEFENSE));
>         props.put("FIGHT_PROP_ELEMENT_MASTERY",owner.getFightProperty(FightProperty.FIGHT_PROP_ELEMENT_MASTERY));
> 
>         var amountByCasterMaxHPRatio = action.amountByCasterMaxHPRatio.get(props,0);
>         var amountByCasterAttackRatio = action.amountByCasterAttackRatio.get(props,0);
>         var amountByCasterCurrentHPRatio = action.amountByCasterCurrentHPRatio.get(props,0);
>         var amountByTargetCurrentHPRatio = action.amountByTargetCurrentHPRatio.get(props,0);
>         var amountByTargetMaxHPRatio = action.amountByTargetMaxHPRatio.get(props,0);
>         var amountToRegenerate = action.amount.get(props,0);
> ```

这些键值完全替换吗?不太好用,

**Comment by Deskable** [comment]
> 键值没有更新，我修改了一下，在Grasscutter-development\src\main\java\emu\grasscutter\data\binout\AbilityModifier.java中找到并替换以下内容后重新编译即可：
> 
> ```
>         @SerializedName(
>                 value = "amount",
>                 alternate = {"LNFMOCKIAGK", "PDLLIFICICJ", "cdRatio"})
>         public DynamicFloat amount = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "GMFELAKANEF")
>         public DynamicFloat amountByCasterAttackRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "unused")
>         public DynamicFloat amountByCasterCurrentHPRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(
>             value = "PKPBLCNMPIG",
>             alternate = {"HFNJHOGGFKB", "GEJGGCIOLKN"})
>         public DynamicFloat amountByCasterMaxHPRatio = DynamicFloat.ZERO;
> 
>         public DynamicFloat amountByGetDamage = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "amountByTargetMaxHPRatio")
>         public DynamicFloat amountByTargetCurrentHPRatio = DynamicFloat.ZERO;
> 
>         @SerializedName(value = "GGLMMJHNGMO")
>         public DynamicFloat amountByTargetMaxHPRatio = DynamicFloat.ZERO;
> ```
> 
> 此外，我发现之前的脚本忽略了元素精通和防御力对角色治疗量的影响，我在Grasscutter-development\src\main\java\emu\grasscutter\game\ability\actions\ActionHealHP.java中修改了以下内容后解决了这个问题：
> 
> ```
>         Object2FloatMap<String> props = ability.getAbilitySpecials();
>         props.put("FIGHT_PROP_CUR_DEFENSE",owner.getFightProperty(FightProperty.FIGHT_PROP_CUR_DEFENSE));
>         props.put("FIGHT_PROP_ELEMENT_MASTERY",owner.getFightProperty(FightProperty.FIGHT_PROP_ELEMENT_MASTERY));
> 
>         var amountByCasterMaxHPRatio = action.amountByCasterMaxHPRatio.get(props,0);
>         var amountByCasterAttackRatio = action.amountByCasterAttackRatio.get(props,0);
>         var amountByCasterCurrentHPRatio = action.amountByCasterCurrentHPRatio.get(props,0);
>         var amountByTargetCurrentHPRatio = action.amountByTargetCurrentHPRatio.get(props,0);
>         var amountByTargetMaxHPRatio = action.amountByTargetMaxHPRatio.get(props,0);
>         var amountToRegenerate = action.amount.get(props,0);
> ```

实际使用,有效果
客户端版本:4.0
服务端版本:1.7.1
2023

**Comment by KingRainbow44** [comment]
just applied both changes here to `development`, thank you for helping!
