### ISSUE TITLE
I'm having this error right here, what should I do?

### ISSUE THREAD

**Issue by damtienkhoi** [Melledy/Grasscutter#234]
![image](https://user-images.githubusercontent.com/96215744/165062136-0f329f01-a82b-43fd-8cd2-4996d4af5df3.jpeg)

**Comment by hannaxd** [comment]
Your MongoDB connection times out so check whether or not your MongoDB server is running and the connection string and port are correct

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
