### ISSUE TITLE
能给个指令大全吗？

### ISSUE THREAD

**Issue by YazawaTvT** [Melledy/Grasscutter#2354]
刚刚上手搞不明白，地图全没开、抽奖界面也没有咋搞啊

**Comment by curryyinxh** [comment]
1.There is a tool called "grasscutter tools" that can conveniently execute all commands remotely; it should be able to assist you.2."grasscutter tools" というツールがあり、すべてのコマンドを便利にリモートで実行できます。お手伝いできると思います。3.Il y a un outil appelé "grasscutter tools" qui peut exécuter toutes les commandes à distance de manière très pratique; il devrait pouvoir vous aider.4."grasscutter tools"라는 도구가 있어 모든 명령을 원격으로 편리하게 실행할 수 있으며, 당신을 도울 수 있을 것입니다.5.هناك أداة تسمى "grasscutter tools" يمكنها تنفيذ جميع الأوامر عن بُعد بسهولة، يجب أن تكون قادرًا على مساعدتك.

**Comment by KingRainbow44** [comment]
this is not where you get support, ask in our discord.
