### ISSUE TITLE
[Bug] Quest AR requirement doesnt make the player need such AR level

### ISSUE THREAD

**Issue by JustRad123** [Melledy/Grasscutter#2358]
**Did you look for other closed issues that have the same problem?**
yup , didnt see one issue related to it in English

**Describe the bug**
Despite the quests being AR locked in Quest menu u can do them anyway when u follow the gold rectangle on the map , all dialog works anyway , just quest menu issue

**Which branch did you use?**
1.7.1(local host)

**Screenshots**
![image](https://github.com/Grasscutters/Grasscutter/assets/110855987/9cd8972f-b458-4c16-899e-2b9ed4d60880)
![image](https://github.com/Grasscutters/Grasscutter/assets/110855987/d0916c0c-962b-4328-8a2f-ca4cbae25f45)

**Additional context**
i did use the command unlockall , maybe its the cause but , no idea at all

**Comment by NotThorny** [comment]
unlockall will open _all_ openstates, which includes quest-locked progression areas and limits. If you've run a command to unlock openstates then no quest-related issues can be properly addressed, since you've already broken quest progression by doing so.
