### ISSUE TITLE
I'm trying to build but got this error, anyone know how to fix it?

### ISSUE THREAD

**Issue by MimiKikiNyami** [Melledy/Grasscutter#236]
![unk (3)](https://user-images.githubusercontent.com/70386609/165077062-7c3ed3af-a8e0-400b-8a00-b4ceffde2973.png)

**Comment by lunaticwhat** [comment]
have you tried to setup the environment with running gradlew.bat ?

**Comment by MimiKikiNyami** [comment]
I have
![8_24_33](https://user-images.githubusercontent.com/70386609/165098333-f1cc3246-5a5e-4a81-8e08-ee198cb60afa.png)
![8_24_46](https://user-images.githubusercontent.com/70386609/165098337-1a0814b7-376e-4828-9349-de2f0bfd890e.png)
![8_25_05](https://user-images.githubusercontent.com/70386609/165098339-c93e28e4-486a-437a-a388-8e80b35a4498.png)

**Comment by lunaticwhat** [comment]
can you double check again your java installation in your program files ?
if i remember correctly the java folder doesnt named like that.
or also you can check if your jdk is working with` java -version` in any cmd window

**Comment by MimiKikiNyami** [comment]
is it like this?
![Screen](https://user-images.githubusercontent.com/70386609/165099761-923c19db-ede7-4248-b6b8-3fea7e13e9b6.png)

**Comment by lxzlxzliuxuzhao** [comment]
You can try the java 8.

**Comment by MimiKikiNyami** [comment]
i tried but still got that error

**Comment by lunaticwhat** [comment]
your `java -version` report telling it's a **Runtime Enviroinment**, not **Development Kit** so that is why you couldn't compile Grasscutter.

**Comment by exzork** [comment]
> I have ![8_24_33](https://user-images.githubusercontent.com/70386609/165098333-f1cc3246-5a5e-4a81-8e08-ee198cb60afa.png) ![8_24_46](https://user-images.githubusercontent.com/70386609/165098337-1a0814b7-376e-4828-9349-de2f0bfd890e.png) ![8_25_05](https://user-images.githubusercontent.com/70386609/165098339-c93e28e4-486a-437a-a388-8e80b35a4498.png)

remove the first entry on the third image ( oracle javapath )

**Comment by MimiKikiNyami** [comment]
I tried uninstalling all java and reinstalling jdk and still get the same error anyway thank you so much

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
