### ISSUE TITLE
使用openVpn建立内网环境能够成功进入游戏，但是使用frp或者端口映射则无法成功进入游戏但可登录

### ISSUE THREAD

**Issue by chutiangekmm** [Melledy/Grasscutter#2364]
使用openVpn建立内网环境能直接访问grasscutter够成功进入游戏。
但是使用frp或者端口映射密码验证可以通过。但会卡在资源更新这一步无法进入游戏。
系统环境win11
服务器环境ubuntu
java17

{
  "folderStructure": {
    "resources": "./resources/",
    "data": "./data/",
    "packets": "./packets/",
    "scripts": "resources:Scripts/",
    "plugins": "./plugins/",
    "cache": "./cache/"
  },
  "databaseInfo": {
    "server": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    },
    "game": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    }
  },
  "language": {
    "language": "zh_CN",
    "fallback": "en_US",
    "document": "EN"
  },
  "account": {
    "autoCreate": false,
    "EXPERIMENTAL_RealPassword": false,
    "defaultPermissions": [],
    "maxPlayer": -1
  },
  "server": {
    "debugWhitelist": [],
    "debugBlacklist": [],
    "runMode": "HYBRID",
    "logCommands": false,
    "fastRequire": true,
    "http": {
      "startImmediately": false,
      "bindAddress": "0.0.0.0",
      "bindPort": 4433,
      "accessAddress": "172.18.96.10",
      "accessPort": 0,
      "encryption": {
        "useEncryption": false,
        "useInRouting": false,
        "keystore": "./keystore.p12",
        "keystorePassword": "123456"
      },
      "policies": {
        "cors": {
          "enabled": true,
          "allowedOrigins": [
            "*"
          ]
        }
      },
      "files": {
        "indexFile": "./index.html",
        "errorFile": "./404.html"
      }
    },
    "game": {
      "bindAddress": "0.0.0.0",
      "bindPort": 22102,
      "accessAddress": "172.18.96.10",
      "accessPort": 0,
      "loadEntitiesForPlayerRange": 300,
      "enableScriptInBigWorld": true,
      "enableConsole": true,
      "kcpInterval": 20,
      "logPackets": "NONE",
      "isShowPacketPayload": false,
      "isShowLoopPackets": false,
      "cacheSceneEntitiesEveryRun": false,
      "gameOptions": {
        "inventoryLimits": {
          "weapons": 2000,
          "relics": 2000,
          "materials": 2000,
          "furniture": 2000,
          "all": 30000
        },
        "avatarLimits": {
          "singlePlayerTeam": 4,
          "multiplayerTeam": 4
        },
        "sceneEntityLimit": 1000,
        "watchGachaConfig": false,
        "enableShopItems": true,
        "staminaUsage": true,
        "energyUsage": true,
        "fishhookTeleport": true,
        "trialCostumes": false,
        "questing": {
          "enabled": true
        },
        "resinOptions": {
          "resinUsage": false,
          "cap": 160,
          "rechargeTime": 480
        },
        "rates": {
          "adventureExp": 1.0,
          "mora": 1.0,
          "leyLines": 1.0
        },
        "handbook": {
          "enable": false,
          "allowCommands": true,
          "limits": {
            "enabled": false,
            "interval": 3,
            "maxRequests": 10,
            "maxEntities": 25
          },
          "server": {
            "enforced": false,
            "address": "127.0.0.1",
            "port": 4433,
            "canChange": true
          }
        }
      },
      "joinOptions": {
        "welcomeEmotes": [
          2007,
          1002,
          4010
        ],
        "welcomeMessage": "Welcome to a Grasscutter server.",
        "welcomeMail": {
          "title": "Welcome to Grasscutter!",
          "content": "Hi there!\r\nFirst of all, welcome to Grasscutter. If you have any issues, please let us know so that Lawnmower can help you! \r\n\r\nCheck out our:\r\n<type=\"browser\" text=\"Discord\" href=\"https://discord.gg/T5vZU6UyeG\"/>\n",
          "sender": "Lawnmower",
          "items": [
            {
              "itemId": 13509,
              "itemCount": 1,
              "itemLevel": 1
            },
            {
              "itemId": 201,
              "itemCount": 99999,
              "itemLevel": 1
            }
          ]
        }
      },
      "serverAccount": {
        "avatarId": 10000007,
        "nameCardId": 210001,
        "adventureRank": 1,
        "worldLevel": 0,
        "nickName": "Server",
        "signature": "Welcome to Grasscutter!"
      },
      "visionOptions": [
        {
          "name": "VISION_LEVEL_NORMAL",
          "visionRange": 80,
          "gridWidth": 20
        },
        {
          "name": "VISION_LEVEL_LITTLE_REMOTE",
          "visionRange": 16,
          "gridWidth": 40
        },
        {
          "name": "VISION_LEVEL_REMOTE",
          "visionRange": 1000,
          "gridWidth": 250
        },
        {
          "name": "VISION_LEVEL_SUPER",
          "visionRange": 4000,
          "gridWidth": 1000
        },
        {
          "name": "VISION_LEVEL_NEARBY",
          "visionRange": 40,
          "gridWidth": 20
        },
        {
          "name": "VISION_LEVEL_SUPER_NEARBY",
          "visionRange": 20,
          "gridWidth": 20
        }
      ]
    },
    "dispatch": {
      "regions": [],
      "dispatchUrl": "ws://127.0.0.1:1111",
      "encryptionKey": "u/N6Upo2q7MGEqIoi6cTXPy3ehGpYbeiehV1wa9VLf4=",
      "dispatchKey": "IBsqboosf3fSk7qJ6ZFcUzurhvizbs4nP0TTtDadb4Q=",
      "defaultName": "Grasscutter",
      "logRequests": "NONE"
    },
    "debugMode": {
      "serverLoggerLevel": {
        "levelInt": 10000,
        "levelStr": "DEBUG"
      },
      "servicesLoggersLevel": {
        "levelInt": 20000,
        "levelStr": "INFO"
      },
      "logPackets": "ALL",
      "isShowPacketPayload": false,
      "isShowLoopPackets": false,
      "logRequests": "ALL"
    }
  },
  "version": 12
}

![image](https://github.com/Grasscutters/Grasscutter/assets/30683090/1944d5b4-b03a-482e-977b-aa16e34d0cc2)

![image](https://github.com/Grasscutters/Grasscutter/assets/30683090/9962c716-2dcc-434f-9e5a-004905176218)

![image](https://github.com/Grasscutters/Grasscutter/assets/30683090/87380968-4b95-4547-9f59-46ec6355f14a)

![UE3T4Y A3C_0)~Y7W@I)S3](https://github.com/Grasscutters/Grasscutter/assets/30683090/7190534a-6e23-4828-87b0-f8ba88ac5218)

![image](https://github.com/Grasscutters/Grasscutter/assets/30683090/18b3e68b-7805-4668-94c0-985555493f86)

完全找不到头绪 所以来请教一下各位

**Comment by HongchengQ** [comment]
accessPort设置成你内网穿透的外网端口

**Comment by QiuShi5** [comment]
> accessPort设置成你内网穿透的外网端口

感谢问题解决了端口穿透如您所说 server 和 game 的 accessPort 换成外网的端口就可以了。  
如果使用frp转发的话 对应的 accessAddress同时换成frp的外网 ip 即可

**Comment by pingwutm-iip** [comment]
大佬求分享公网的config，我现在可以登录但是选双子命名然后点确认没反应。

**Comment by jh-fdg** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Grasscutters/Grasscutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月12日(星期二) 中午1:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Grasscutters/Grasscutter] 使用openVpn建立内网环境能够成功进入游戏，但是使用frp或者端口映射则无法成功进入游戏但可登录 (Issue #2364)





 
大佬求分享公网的config，我现在可以登录但是选双子命名然后点确认没反应。
