### ISSUE TITLE
error 10061  Connect call failed ('127.0.0.1', 22102) when i login

### ISSUE THREAD

**Issue by chenyuanyuandeguiji** [Melledy/Grasscutter#237]
![屏幕截图 2022-04-25 195242](https://user-images.githubusercontent.com/38393416/165084019-a9f3f1e8-56d8-41e4-b8a6-e6ebd3bc173a.png)

**Comment by chenyuanyuandeguiji** [comment]
i know, i opend other proxy software.

**Comment by 0x915** [comment]
> 
我也遇到这个，但我可以确定系统没有第二个网络代理程序
，服务端已经迁移到局域网另外的主机架设
