### ISSUE TITLE
[Bug] 角色倒下后,无法使用食物复活

### ISSUE THREAD

**Issue by Deskable** [Melledy/Grasscutter#2376]
同#2310
Grasscutter version: 1.7.1-047feaf4  倒下角色食物错误
角色倒下后，无法食用复活类食物（如提瓦特煎蛋）
显示服务器内部错误（如图）

![屏幕截图(48)](https://github.com/Grasscutters/Grasscutter/assets/46278804/46137971-c51d-476c-8579-f9f18dc4f937)

**Comment by Deskable** [comment]
> 同#2310 Grasscutter version: 1.7.1-047feaf4 倒下角色食物错误 角色倒下后，无法食用复活类食物（如提瓦特煎蛋） 显示服务器内部错误（如图）
> 
> ![屏幕截图(48)](https://user-images.githubusercontent.com/46278804/268522026-46137971-c51d-476c-8579-f9f18dc4f937.png)

另外:Grasscutter version: 1.7.1-2643c6b3  是正常的倒下角色可以使用食物复活

**Comment by Aiikisaraki** [comment]
我这边Grasscutter version: 1.7.1-ec2bfffd是战斗死亡可以用食物复活，指令，淹死摔死等非正常死亡无法通过食物复活只能到就近神像复活

**Comment by Deskable** [comment]
文件版本Grasscutter version: 1.7.1-2643c6b3可以正常使用食物复活,但无法使用角色技能恢复生命(自己编译的也不行)
