### ISSUE TITLE
[Feature Request] shop.json

### ISSUE THREAD

**Issue by DarkSissi** [Melledy/Grasscutter#2383]
**Is your feature request related to a problem? Please describe.**

游戏内的商城能否和原版一样呢？我无法找到合适的json文件去修改它，shop.json似乎不是用来控制游戏内商城的。

Can the in-game store be the same as the original version? I can't find a suitable JSON file to modify it. It seems that shop.json is not used to control the in-game store.

**Describe the solution you'd like**

需要一个json文件替换使得游戏内商城与原版基本一致或者告诉我哪个文件是修改游戏内商城的

I need a JSON file replacement to make the in-game store similar to the original version, or please tell me which file is used to modify the in-game store.

**Comment by jie65535** [comment]
你可以尝试用 [GcTools](http://github.com/jie65535/GrasscutterCommandGenerator) 的**商店编辑器**打开RES里的商店文件 `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (是的，GCT支持加载这个)，然后再改成 `Shop.json` 保存到GC的 `data` 目录下 `.\Grasscutter\data\Shop.json`。

You can try to use the **Store editor** of [GcTools](http://github.com/jie65535/GrasscutterCommandGenerator) to open the Shop Goods file `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (yes, GCT Support loading this), then save it to `.\Grasscutter\data\Shop.json`.

**Comment by DarkSissi** [comment]
> 你可以尝试用 [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) 的**商店编辑器**打开RES里的商店文件 `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (是的，GCT支持加载这个)，然后再改成 `Shop.json` 保存到GC的 `data` 目录下 `.\Grasscutter\data\Shop.json`。
> 
> You can try to use the **Store editor** of [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) to open the Shop Goods file `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (yes, GCT Support loading this), then save it to `.\Grasscutter\data\Shop.json`.

懂了，但是cultivation下载的一体化中并没有resource文件夹，我使用everything也找不到ShopGoodsExcelConfigData.json这个文件，这个文件在哪里呢，蟹蟹你！

**Comment by loverping** [comment]
> > 你可以尝试用 [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) 的**商店编辑器**打开RES里的商店文件 `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (是的，GCT支持加载这个)，然后再改成 `Shop.json` 保存到GC的 `data` 目录下 `.\Grasscutter\data\Shop.json`。
> > You can try to use the **Store editor** of [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) to open the Shop Goods file `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (yes, GCT Support loading this), then save it to `.\Grasscutter\data\Shop.json`.
> 
> 懂了，但是cultivation下载的一体化中并没有resource文件夹，我使用everything也找不到ShopGoodsExcelConfigData.json这个文件，这个文件在哪里呢，蟹蟹你！

如果你使用的是一体化的资源的话，这个资源在resource.zip里面你可以使用压缩工具从里面提取

**Comment by DarkSissi** [comment]
> > > 你可以尝试用 [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) 的**商店编辑器**打开RES里的商店文件 `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (是的，GCT支持加载这个)，然后再改成 `Shop.json` 保存到GC的 `data` 目录下 `.\Grasscutter\data\Shop.json`。
> > > You can try to use the **Store editor** of [GcTools](https://github.com/jie65535/GrasscutterCommandGenerator) to open the Shop Goods file `.\Resources\ExcelBinOutput\ShopGoodsExcelConfigData.json` (yes, GCT Support loading this), then save it to `.\Grasscutter\data\Shop.json`.
> > 
> > 
> > 懂了，但是cultivation下载的一体化中并没有resource文件夹，我使用everything也找不到ShopGoodsExcelConfigData.json这个文件，这个文件在哪里呢，蟹蟹你！
> 
> 如果你使用的是一体化的资源的话，这个资源在resource.zip里面你可以使用压缩工具从里面提取

谢谢 我已经找到了该文件
