### ISSUE TITLE
Unknown error -4308-1

### ISSUE THREAD

**Issue by Villanellee** [Melledy/Grasscutter#242]
I opened the database and server, and used the launcher to play games. I even chose a character in the game, but after I waited for a long time in this white interface, I reported an error (picture 1) and returned to the login interfac
![QQ截图20220425205046](https://user-images.githubusercontent.com/104367858/165097699-32c1df6d-96dd-4f9f-aad3-b0bc79b5c793.png)
e

**Comment by Villanellee** [comment]
When I try to log in again, I will still wait in the same interface for a long time, and then report an error agai
![EY_4(P@92X44B%A(ZV6 QJO](https://user-images.githubusercontent.com/104367858/165097920-81918f5f-8d72-405c-9d7c-fdcef72c7684.png)
n

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
