### ISSUE TITLE
[Bug] 游戏开门进入后提示连接超时

### ISSUE THREAD

**Issue by 156209258y** [Melledy/Grasscutter#2425]
![Screenshot_2023-11-06-06-26-57-233_com miHoYo Yua](https://github.com/Grasscutters/Grasscutter/assets/108350083/b5bdb78b-acd9-4b66-9ed3-dc359c6b181d)
登录这些都是正常的   手机端  443  27017 都是正常访问

**Comment by 156209258y** [comment]
> ![Screenshot_2023-11-06-06-26-57-233_com miHoYo Yua](https://user-images.githubusercontent.com/108350083/280558653-b5bdb78b-acd9-4b66-9ed3-dc359c6b181d.jpg) 登录这些都是正常的 手机端 443 27017 都是正常访问

**Comment by pureages** [comment]
兄弟解决了吗？什么原因呢

**Comment by miaomiao2970** [comment]
啊啊啊啊啊啊啊啊啊
