### ISSUE TITLE
[Bug] 击败瓦特林，任务怎么都过不了，通过命令完成任务也不行，重新做也不行："Defeat Tartaglia, can't pass the quest no matter what I do. Using commands to complete the quest doesn't work either, and starting over doesn't help."

### ISSUE THREAD

**Issue by trash-fish** [Melledy/Grasscutter#2428]
击败瓦特林，任务怎么都过不了，通过命令完成任务也不行，重新做也不行
现在很难受的一点就是，每次进游戏都要看几分钟的动画，如何解决呢

![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/d221a3c7-4e35-406f-9556-d6afb4047145)

版本：4.0.0

**Comment by NovaExiles** [comment]
我也过不了，打一半龙没了

**Comment by trash-fish** [comment]
![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/61b2203c-cc11-4ee5-9714-fc9299414cfd)
,我每次开游戏，这个几分钟的动画跳过不了，太烦人了

**Comment by trash-fish** [comment]
Defeat Tartaglia, can't pass the quest no matter what I do. Using commands to complete the quest doesn't work either, and starting over doesn't help. One frustrating aspect is that I have to watch a few minutes of animation every time I enter the game. How can I solve this?

**Comment by Noscread** [comment]
怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗

**Comment by pbz134** [comment]
> Wie starte ich eine Mission? Nach dem Betreten des Spiels gibt es keine Missionen. Einige Dinge, für deren Freischaltung der Missionsfortschritt erforderlich ist, können nicht freigeschaltet werden, z. B. die Windgottstatue, das Freischalten von Regionen, Gebete usw., aber sie können nicht freigeschaltet werden . Muss ich irgendetwas tun?

Have you downloaded and enabled the questing features?

**Comment by NovaExiles** [comment]
> 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗

利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便

**Comment by trash-fish** [comment]
> > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> 
> 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便

我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，

**Comment by NovaExiles** [comment]
> > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > 
> > 
> > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> 
> 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，

我不能打风魔龙，就用指令跳过了。然后看完动画就正常进入后面剧情了

**Comment by NovaExiles** [comment]
> > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > 
> > 
> > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> 
> 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，

指令不能跳过吗 /quest finish 39402

**Comment by trash-fish** [comment]
> > > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > > 
> > > 
> > > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> > 
> > 
> > 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，
> 
> 指令不能跳过吗 /quest finish 39402

好家伙我也是用指令跳过了，结果我用命令任务都过不了，每次进游戏都要看动画，这个命令不行

**Comment by NovaExiles** [comment]
> > > > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > > > 
> > > > 
> > > > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> > > 
> > > 
> > > 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，
> > 
> > 
> > 指令不能跳过吗 /quest finish 39402
> 
> 好家伙我也是用指令跳过了，结果我用命令任务都过不了，每次进游戏都要看动画，这个命令不行

04呢？/quest finish 39404  再不行也没办法了，我也是新手，没啥东西

**Comment by g-youdong** [comment]
> > > > > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > > > > 
> > > > > 
> > > > > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> > > > 
> > > > 
> > > > 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，
> > > 
> > > 
> > > 指令不能跳过吗 /quest finish 39402
> > 
> > 
> > 好家伙我也是用指令跳过了，结果我用命令任务都过不了，每次进游戏都要看动画，这个命令不行
> 
> 04呢？/quest finish 39404 再不行也没办法了，我也是新手，没啥东西

![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/6bad4ba8-e917-4c09-b5f4-26eb228cb9cf)

没办法了，我记得zhi之前试过了，现在也不行

**Comment by trash-fish** [comment]
> > > > > > 怎么开启任务啊，进入游戏后什么任务也没有，一些要任务进度解锁的东西都解锁不了，像风神像，地区解锁，祈愿什么的，都解锁不了，需要做什么吗
> > > > > 
> > > > > 
> > > > > 利用指令 /quest add 任务id 添加任务 ，也可以用GrasscuttersTools添加任务 推荐后者，更方便
> > > > 
> > > > 
> > > > 我这个有办法解决吗？老看前面的动画真服了，mongodb操作什么数据也不知道，
> > > 
> > > 
> > > 指令不能跳过吗 /quest finish 39402
> > 
> > 
> > 好家伙我也是用指令跳过了，结果我用命令任务都过不了，每次进游戏都要看动画，这个命令不行
> 
> 04呢？/quest finish 39404 再不行也没办法了，我也是新手，没啥东西

![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/ce18496e-fef1-4a8f-b37b-06f43616119a)

没办法了，我记得zhi之前试过了，现在也不行

**Comment by trash-fish** [comment]
![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/7275f57a-bbfc-444a-b98a-2b262a5c43a0)

**Comment by trash-fish** [comment]
我的图片咋发不出来了！！！

**Comment by NovaExiles** [comment]
> 我的图片咋发不出来了！！！

只能开新号了😥

**Comment by trash-fish** [comment]
> > 我的图片咋发不出来了！！！
> 
> 只能开新号了😥

我的fake，我看了第三个了！！！！！！！！！之前白屏都没法解决

**Comment by NovaExiles** [comment]
> > > 我的图片咋发不出来了！！！
> > 
> > 
> > 只能开新号了😥
> 
> 我的fake，我看了第三个了！！！！！！！！！之前白屏都没法解决

我也好几个了，最开始那个安柏射史莱姆，让按2切换安柏，我队里当时好几个角色，切不了安柏，就卡那里了，当时完成任务指令也没用

**Comment by trash-fish** [comment]
> > > > 我的图片咋发不出来了！！！
> > > 
> > > 
> > > 只能开新号了😥
> > 
> > 
> > 我的fake，我看了第三个了！！！！！！！！！之前白屏都没法解决
> 
> 我也好几个了，最开始那个安柏射史莱姆，让按2切换安柏，我队里当时好几个角色，切不了安柏，就卡那里了，当时完成任务指令也没用

我白屏俩号，有个秘境一开门，手动不完成的话用指令，出去直接白屏，再也进不去了，然后用任务跳过也不知道，有索引越界的错误

**Comment by NovaExiles** [comment]
> > > > > 我的图片咋发不出来了！！！
> > > > 
> > > > 
> > > > 只能开新号了😥
> > > 
> > > 
> > > 我的fake，我看了第三个了！！！！！！！！！之前白屏都没法解决
> > 
> > 
> > 我也好几个了，最开始那个安柏射史莱姆，让按2切换安柏，我队里当时好几个角色，切不了安柏，就卡那里了，当时完成任务指令也没用
> 
> 我白屏俩号，有个秘境一开门，手动不完成的话用指令，出去直接白屏，再也进不去了，然后用任务跳过也不知道，有索引越界的错误

能玩就行了，本来我都当抽卡模拟器的，能打任务我感觉就不错了。看看后面大佬们做不做任务脚本吧

**Comment by trash-fish** [comment]
> > > > > > 我的图片咋发不出来了！！！
> > > > > 
> > > > > 
> > > > > 只能开新号了😥
> > > > 
> > > > 
> > > > 我的fake，我看了第三个了！！！！！！！！！之前白屏都没法解决
> > > 
> > > 
> > > 我也好几个了，最开始那个安柏射史莱姆，让按2切换安柏，我队里当时好几个角色，切不了安柏，就卡那里了，当时完成任务指令也没用
> > 
> > 
> > 我白屏俩号，有个秘境一开门，手动不完成的话用指令，出去直接白屏，再也进不去了，然后用任务跳过也不知道，有索引越界的错误
> 
> 能玩就行了，本来我都当抽卡模拟器的，能打任务我感觉就不错了。看看后面大佬们做不做任务脚本吧

![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/c3bfd987-49a6-47ea-9913-718dff875abd)
这个问题是不是你还存在呢，一直卡图，我就是因为这个没法传送导致的这个巨龙任务一直过不了吧

**Comment by trash-fish** [comment]
目前无法进行传送，需完成任务「异常的权柄」

**Comment by NovaExiles** [comment]
> 目前无法进行传送，需完成任务「异常的权柄」

我任务是一步一步过来的，所以现在没卡，你是不是没做最开始的任务

**Comment by trash-fish** [comment]
> > 目前无法进行传送，需完成任务「异常的权柄」
> 
> 我任务是一步一步过来的，所以现在没卡，你是不是没做最开始的任务

我是4.0的版本，这个异常的权柄，就根本没法过，少史莱姆

**Comment by NovaExiles** [comment]
> > > 目前无法进行传送，需完成任务「异常的权柄」
> > 
> > 
> > 我任务是一步一步过来的，所以现在没卡，你是不是没做最开始的任务
> 
> 我是4.0的版本，这个异常的权柄，就根本没法过，少史莱姆

我也是4.0啊，任务从鸟瞰风物开始的

**Comment by trash-fish** [comment]
> > > > 目前无法进行传送，需完成任务「异常的权柄」
> > > 
> > > 
> > > 我任务是一步一步过来的，所以现在没卡，你是不是没做最开始的任务
> > 
> > 
> > 我是4.0的版本，这个异常的权柄，就根本没法过，少史莱姆
> 
> 我也是4.0啊，任务从鸟瞰风物开始的

！！！！解决了，我去数据库里面查到了这个任务，我给删了就行了，db.quests.find({   "childQuests.39402": { $exists: true } })，db.quests.remove({"_id": ObjectId("65431b2938df4654a338a096")})



！！！
![image](https://github.com/Grasscutters/Grasscutter/assets/70623599/2317690e-1d5b-4f1e-afb2-9c5270c3d69e)

**Comment by NovaExiles** [comment]
> > > > > 目前无法进行传送，需完成任务「异常的权柄」
> > > > 
> > > > 
> > > > 我任务是一步一步过来的，所以现在没卡，你是不是没做最开始的任务
> > > 
> > > 
> > > 我是4.0的版本，这个异常的权柄，就根本没法过，少史莱姆
> > 
> > 
> > 我也是4.0啊，任务从鸟瞰风物开始的
> 
> ！！！！解决了，我去数据库里面查到了这个任务，我给删了就行了，db.quests.find({ "childQuests.39402": { $exists: true } })，db.quests.remove({"_id": ObjectId("65431b2938df4654a338a096")})
> 
> ！！！ ![image](https://user-images.githubusercontent.com/70623599/281053581-2317690e-1d5b-4f1e-afb2-9c5270c3d69e.png)

佬，叫我我都看不懂👍🏻
