### ISSUE TITLE
stay loading and cannot login

### ISSUE THREAD

**Issue by MXJinjing** [Melledy/Grasscutter#244]
I can create new accounts but cannot login in the game.
![image](https://user-images.githubusercontent.com/104336156/165125868-5bc728f1-3df7-45af-ae79-e6b36e89bfd7.png)

**Comment by thomasxu1991** [comment]
just trust the p12 certificate file

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
