### ISSUE TITLE
[Bug] The store displays an abnormal 99 Mora cost, and the files in shop.json and resource are invalid. After reloading, you can redeem it at the original price and display a false 99 Mora cost (not required)

### ISSUE THREAD

**Issue by r78ik7** [Melledy/Grasscutter#2452]
config.json里"enableShopItems": true
shop.json是复制ShopGoodsExcelConfigData的内容，商店稍微正常了一些，但是标价图片和购买市价不同，外面显示99摩拉，实际需要/reload变正常价格，摩拉不消耗
grasscuttter tools by jie65535对Shopgoodsexcel的条目读取显示
异常文本
异常类型：ArgumentOutOfRangeException
0的值对于“value”无效，“value”应介于“minimum”与“maximum”之间
参数名：value
grasscutter本体日志仅一条未发现原因的报错
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402002.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403186.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403513.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001112.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
10:09:44 <ERROR:SceneGroup> An error occurred while loading group 133305051 in scene 3.
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403003.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316134.lua
![图片1](https://github.com/Grasscutters/Grasscutter/assets/153067678/956281af-1ff8-473b-8fc6-eed7c1fb59ed)
"EnableShopItems" in config.json: true

Shop.json copies the content of ShopGoodsExcelConfigData. The store is slightly more normal, but the price image is different from the purchase market price. The external display shows 99 Mora, and the actual need for/reload to change to the normal price. Mora is not consumed

Grasscutter tools by jie65535 for reading entries in Shopgoodsexcel

Abnormal Text

Exception type: ArgumentOutOfRangeException

The value of 0 is invalid for 'value', which should be between 'minimum' and 'maximum'

Parameter name: value

There is only one error message in the Grasscutter ontology log with no reason found
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402002.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403186.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403513.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001112.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
10:09:44 <ERROR:SceneGroup> An error occurred while loading group 133305051 in scene 3.
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403003.lua
10:09:44 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316134.lua
I'm sorry, this is a machine flip. I'm sorry

**Comment by r78ik7** [comment]
对商店价格的修改无法生效，无论修改哪个修改商店的文件

**Comment by NotThorny** [comment]
This is a protos issue, if you use the All-in-one from Cultivation, it is using fixed protos and these issues inside the shop will not appear. You'll still have to `reload` the server after starting it each time for the shop goods to appear though.

**Comment by r78ik7** [comment]
After a significant adjustment to shop.json, the products in the store looked normal, and the modified price took effect within a certain range. However, is the price of the 99 Mora image an editable item?

> This is a protos issue, if you use the All-in-one from Cultivation, it is using fixed protos and these issues inside the shop will not appear. You'll still have to `reload` the server after starting it each time for the shop goods to appear though.

**Comment by Nebelun** [comment]
I would like to port that over if possible. Is the All-in-one image using protobufs or another solution? I ran into the shops.json error as well on my linux server.

**Comment by r78ik7** [comment]
> I would like to port that over if possible. Is the All-in-one image using protobufs or another solution? I ran into the shops.json error as well on my linux server.

The shop.json error can be resolved by copying another shop file from the resource, but the display errors in texture, quantity, and price cannot be resolved at this time. If the price display is changed after reloading, it is still an error. I am not a geek, and I hope this image repair can be resolved in my lifetime (even if it is a way for us to make changes ourselves). Currently, there are still a huge number of bugs, and I do not have high expectations.

**Comment by NotThorny** [comment]
> > I would like to port that over if possible. Is the All-in-one image using protobufs or another solution? I ran into the shops.json error as well on my linux server.
> 
> The shop.json error can be resolved by copying another shop file from the resource, but the display errors in texture, quantity, and price cannot be resolved at this time. If the price display is changed after reloading, it is still an error. I am not a geek, and I hope this image repair can be resolved in my lifetime (even if it is a way for us to make changes ourselves). Currently, there are still a huge number of bugs, and I do not have high expectations.

Those issues are already fixed in the All-in-One from Cultivation, the shop is fully functional and correct for price and amount. The few items that don't have textures have been in Grasscutter forever, they aren't from this issue and if you click on them you'll find they aren't actually real items.

You can make the fixes yourself if you really want to, but again, they are already in the All-in-One. If you want to fix it yourself, get a copy of the protos and make the field swaps required in the shop proto, rebuild the jar from source with it.

**Comment by r78ik7** [comment]
> > > I would like to port that over if possible. Is the All-in-one image using protobufs or another solution? I ran into the shops.json error as well on my linux server.
> > 
> > 
> > The shop.json error can be resolved by copying another shop file from the resource, but the display errors in texture, quantity, and price cannot be resolved at this time. If the price display is changed after reloading, it is still an error. I am not a geek, and I hope this image repair can be resolved in my lifetime (even if it is a way for us to make changes ourselves). Currently, there are still a huge number of bugs, and I do not have high expectations.
> 
> Those issues are already fixed in the All-in-One from Cultivation, the shop is fully functional and correct for price and amount. The few items that don't have textures have been in Grasscutter forever, they aren't from this issue and if you click on them you'll find they aren't actually real items.
> 
> You can make the fixes yourself if you really want to, but again, they are already in the All-in-One. If you want to fix it yourself, get a copy of the protos and make the field swaps required in the shop proto, rebuild the jar from source with it.

Thank you very much! Some time ago, there was a problem with my vpn and I couldn't download all in one. Now the problem in the store has been solved. I hope that Grasscutter will survive when Genshin Impact is near the end, and even can experience the plot completely. Thanks again, and I hope it's OK，love from CN（By the way, this is still a mechanical translation）
