### ISSUE TITLE
Latest Stable branch causes Unkown command

### ISSUE THREAD

**Issue by DerivativeMarmot** [Melledy/Grasscutter#246]
I compiled the grasscutter.jar file using java16 (leads to compile error using java8), and successfully start the server. But the server does not recognize the commands (**[INFO] Unknown command**).
After I switch back to java8 and start the server. Everything back to normal.

Environment:
arch Linux
java-16-adoptopenjdk
java-8-openjdk

---------------
1. Can someone fix #148 by simply change a little bit (because it's still causing problem in latest stable branch)
2. and also the problem of generated artifacts with no affix or main
these two problems are really simple to solve but are asked by the most people

**Comment by memetrollsXD** [comment]
We can maybe provide a link to an already fixed excelbinoutput. Stable branch does not support JDK 16 yet, but dev branch does
