### ISSUE TITLE
[Bug] 一直准备下载资源，并报错4206

### ISSUE THREAD

**Issue by SPJ2025** [Melledy/Grasscutter#2476]
**Did you look for other closed issues that have the same problem?**

尝试过很多次其他Issue里的解决办法但是无效

**Describe the bug**

自己在本地电脑（非服务器）搭建Grasscutter成功，在本地电脑上可以连接上，使用内网穿透的地址也可以连接上，但是在另外一个城市使用别的电脑启动游戏可以登录，但是一直显示准备下载资源，并报错无法连接服务器4206

**Which branch did you use?**

 Grasscutter 版本：1.7.4-6e1913a  普通分支和开发分支一样

**Screenshots**

![image](https://github.com/Grasscutters/Grasscutter/assets/135490719/f06a6043-387c-4d84-99b8-a9f6d57132af)
![f701a1310edfc676d7a60d76535bd50b](https://github.com/Grasscutters/Grasscutter/assets/135490719/35174526-88a8-418c-b9bf-1122117eb0c9)
![9a509f2bda996dd4771fd0c30106bc70](https://github.com/Grasscutters/Grasscutter/assets/135490719/4f5cf8b4-48e1-46ad-b459-720391d79eb8)

**Additional context**

**Comment by ZH4201** [comment]
解决了吗？

**Comment by TePillow** [comment]
缺少语音包

**Comment by ljz15626528087** [comment]
怎么解决
