### ISSUE TITLE
[Bug] Missing Scripts

### ISSUE THREAD

**Issue by KanzakiYui** [Melledy/Grasscutter#2483]
**Did you look for other closed issues that have the same problem?**

Yes

**Describe the bug**

There are some missing scripts reported in console:

02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316134.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403513.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402002.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403186.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133403003.lua
02:11:02 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001112.lua

**Which branch did you use?**

Grasscutter version: 1.7.4-2b9cbe38e

**Additional context**

I am using GC-Resources-4.0.zip this file which is automatically downloaded as per README.md guide. I searched the folder and didn't found above mentioned lua scripts.

Do I need to found those scripts somewhere else?

**Comment by KingRainbow44** [comment]
This is not a bug. Despite the console raving about it being an 'error', these scripts don't exist. They shouldn't impact gameplay too much, but if it does, it's likely already been encountered.
