### ISSUE TITLE
[Bug] Call unchecked GetServerTime

### ISSUE THREAD

**Issue by a79402** [Melledy/Grasscutter#2496]
![image](https://github.com/Grasscutters/Grasscutter/assets/30279674/bc649456-2c1f-4f75-9b3c-59f1d4ef8d97)
How to fix this issue? Thanks!

**Comment by Hartie95** [comment]
Warn doesn't necessarily mean there is a problem, it more means, if something is wrong, check these places, they might contain the reason.
Also unchecked in this case just means its not verified, that it behaves the same as what the scripts expect, could be 100% correct, or could be slightly wrong.

**Comment by a79402** [comment]
> hecked in this case just means its not verifie
