### ISSUE TITLE
Holy Relic has no affixes

### ISSUE THREAD

**Issue by kafeim** [Melledy/Grasscutter#250]
How to add affixes to holy relics without affixes?

**Comment by tb114514** [comment]
参考已经关闭的问题

**Comment by sdiad** [comment]
我看了之前那个问题，但是并没有在items中找到自己拥有的圣遗物

**Comment by sdiad** [comment]
> 参考已经关闭的问题



> 参考已经关闭的问题

hxd，你弄好了吗

**Comment by xiyq** [comment]
将这些 json 替换为resources/ExcelBinOutput

https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json

https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json

> > 参考已经关闭的问题
> 
> > 参考已经关闭的问题
> 
> hxd，你弄好了吗

**Comment by sdiad** [comment]
> 将这些 json 替换为resources/ExcelBinOutput
> 
> https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json
> 
> https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json
> 
> > > 参考已经关闭的问题
> > 
> > 
> > > 参考已经关闭的问题
> > 
> > 
> > hxd，你弄好了吗

这两文件我都替换了，就是数据库里没找到可以修改的地方
