### ISSUE TITLE
[Feature Request] 能否构建一个4.6版本的Releases?或者如何自行构建新版本的核心？已有新的数据泄出。https://gitlab.com/YuukiPS/GC-Resources/-/tree/4.6

### ISSUE THREAD

**Issue by sadbeeee** [Melledy/Grasscutter#2506]
#如题

**Comment by HongchengQ** [comment]
只有一个res是没有用的 还需要对客户端进行patch 以及对proto解混淆 这些都是特别难的 或者说是需要大量劳动力的

**Comment by sadbeeee** [comment]
额不是很懂。不过之前的patch补丁似乎没有失效，只是因为服务端版本不匹配导致的4212吧...至于proto确实还没有找到，这个会有什么影响？

**Comment by bj114514** [comment]
或者我可不可以跳过这些强制执行构建？

**Comment by sadbeeee** [comment]
或者我可不可以跳过这些强制进行构建？
另外，我发现有很多周边工具已经支持了4.5或者4.6，它们又是从何而来？是有内测通道可以拿到更新的服务器吗？

**Comment by mumingluan** [comment]
Resources - 服务端所需的游戏资源数据
RSA Patch - 用于绕过客户端与服务端进行 dispatch 通信密钥验证（或者说替换这个验证的公钥）的客户端补丁
Protobuf - 客户端与服务端通信所使用的协议库

要在 Grasscutter 使用新版本的 Resources，只需替换 Resources 文件夹，这是外置于 JAR 的；
如果收到 4214 错误，通常就是因为 RSA 密钥没有替换成功，并非游戏版本与服务端不匹配问题；
Resources 只需从游戏客户端生成，Proto 和其他数据则麻烦得多；
周边工具（例如 GrasscutterTools）只需 Resources 即可构建新版本，它们需要的游戏物品、角色数据都存在于 Resources 中，无需关心其他数据。

**Comment by sadbeeee** [comment]
唉:-(我确实是孤陋寡闻了😥我只能说，请你们加油吧，希望能恢复一开始的更新频率

**Comment by sadbeeee** [comment]
问题是那些周边应用搞那么新干嘛，核心版本都跟不上有毛线用，只能添加一些无效的ID反而拉胯使用体验😓真的没有内测渠道什么的吗？

**Comment by HongchengQ** [comment]
> 问题是那些周边应用搞那么新干嘛，核心版本都跟不上有毛线用，只能添加一些无效的ID反而拉胯使用体验😓真的没有内测渠道什么的吗？

ps又不是只有gc 你核心什么版本就用什么版本的res就行 你要是4.0非要用4.6的res我也没话说 发表这样的评论别人只能当你是乐子

**Comment by oureveryday** [comment]
4.5 fork版本（可以配合4.6 resources使用）：https://github.com/XeonSucksLAB/UnknownAnimeGamePS

补丁：https://git.xeondev.com/reversedrooms/hk4e-patch

https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20231030132335_iOEfPMcbrXpiA8Ca/ScatteredFiles/GenshinImpact_Data/Plugins/mihoyonet.dll

4.6 proto大佬正在搞，不过补丁有了

**Comment by Ryanjiang2009** [comment]
> 只有一个res是没有用的 还需要对客户端进行patch 以及对proto解混淆 这些都是特别难的 或者说是需要大量劳动力的

我可以帮忙，无偿。免费劳动力（可以负责解混淆，但是不是特别了解）。

**Comment by GuguguBear** [comment]
4.6目前还没有办法正常架设起来是吗？
各位的资讯一般在哪里看，TG的话也麻烦给个，我想加进去等最新消息白嫖。

**Comment by ruyzb5645usejk** [comment]
新版本出来没多长时间resource就能出来，和ps进度不是一个概念。

**Comment by miaomiao2970** [comment]
插眼（

**Comment by Jimmy32767255** [comment]
现在5.0版本的核心都有人做出来了(当然，是非官方的)，项目官方这边我个人认为也还是跟进一下进度好，不要一直停留在4.0

**Comment by ruyzb5645usejk** [comment]
> 现在5.0版本的核心都有人做出来了(当然，是非官方的)，项目官方这边我个人认为也还是跟进一下进度好，不要一直停留在4.0

grasscutter主仓库已支持5.0，更新缓慢可能是原神本身热度下降，做的人少了导致的。

**Comment by miaomiao2970** [comment]
撤眼

**Comment by Jimmy32767255** [comment]
> > 现在5.0版本的核心都有人做出来了(当然，是非官方的)，项目官方这边我个人认为也还是跟进一下进度好，不要一直停留在4.0
> 
> grasscutter主仓库已支持5.0，更新缓慢可能是原神本身热度下降，做的人少了导致的。

哦哦

**Comment by ghost** [comment]
> > 现在5.0版本的核心都有人做出来了(当然，是非官方的)，项目官方这边我个人认为也还是跟进一下进度好，不要一直停留在4.0
> 
> grasscutter主仓库已支持5.0，更新缓慢可能是原神本身热度下降，做的人少了导致的。

我用那个unstable分支的jar时候，报Res错误了，不报Res错误也卡在白屏那里，索性就不用了，你能用吗
