### ISSUE TITLE
Getting "Unknown Command" | Latest Dev Branch

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#251]
Hello, I'm getting "unknown command" error from latest dev branch.

I compiled it with JDK 17 and tried to use it. Sadly, all commands didn't work, even server side commands like "account create <username> <uid>" didn't work too.

That's all, thanks.

**Comment by soloopooo** [comment]
use JDK 8u202 to compile. Newer than JDK 15 can be unable to input server commands.

Edit: this is my fault. I didn't see "Latest Dev Branch".

**Comment by xiu920411** [comment]
I guess the use of JDK 18 is different from that of JDK 17. You can try JDK 18 compilation

**Comment by soloopooo** [comment]
> I guess the use of JDK 18 is different from that of JDK 17. You can try JDK 18 compilation

I just tested with JDK 18.0.1. Nothing happens but Unknown Command.
![image](https://user-images.githubusercontent.com/36123081/165225950-9aa92511-5bfc-4168-b4d4-2097ad6f0c4e.png)

**Comment by yangjiahao0036** [comment]
![image](https://user-images.githubusercontent.com/34952645/165229424-36330286-e8cd-42f4-ab8a-88186808a038.png)


input the package path in here.(emu.grasscutter.command.commands)
I can input commands normally after modifying here.

**Comment by xiu920411** [comment]
The version of org.reflections has been upgraded to 0.9.12, so this is a dependency library upgrade problem

**Comment by Lynricsy** [comment]
I have the same problem.Have you solved it yet?

**Comment by soloopooo** [comment]
> I have the same problem.Have you solved it yet?


Plz use @yangjiahao0036 's method,

**Comment by KingRainbow44** [comment]
> ![image](https://user-images.githubusercontent.com/34952645/165229424-36330286-e8cd-42f4-ab8a-88186808a038.png)
> 
> input the package path in here.(emu.grasscutter.command.commands) I can input commands normally after modifying here.

while this fixes the issue short term, the reflector is meant to be used across the entire package...
this works for now as a workaround yes, but later will need to be properly fixed/debugged

**Comment by xiu920411** [comment]
> > ![image](https://user-images.githubusercontent.com/34952645/165229424-36330286-e8cd-42f4-ab8a-88186808a038.png)
> 
> > 
> 
> > input the package path in here.(emu.grasscutter.command.commands) I can input commands normally after modifying here.
> 
> 
> 
> while this fixes the issue short term, the reflector is meant to be used across the entire package...
> 
> this works for now as a workaround yes, but later will need to be properly fixed/debugged

The fundamental reason is the lack of reflection-0.10.2.jar in lib ，add it in and compile it

Tested, command OK!![image](https://user-images.githubusercontent.com/76403660/165410251-59ff2739-09d9-4c56-8fc6-0f7e4d14cb3e.jpeg)
