### ISSUE TITLE
[Bug] Code 4206

### ISSUE THREAD

**Issue by TangZhX-T** [Melledy/Grasscutter#2513]
本机开服务端，本机玩
客户端可以正常连接服务端、正常登录，但是一直卡在正在下载资源并报错4206

![image](https://github.com/Grasscutters/Grasscutter/assets/126883220/e395d5e2-1840-4886-8b8d-d99a702663fd)

请问应如何处理？我用的是Cultivation

**Comment by ruyzb5645usejk** [comment]
不是bug，配置错误。

**Comment by TangZhX-T** [comment]
> 不是bug，配置错误。

请问应该调哪里？在issue转了几圈都没找到相关的

**Comment by TangZhX-T** [comment]
不好意思，换了国际客户端就没问题了
