### ISSUE TITLE
[Feature Request] Enhance HandlerGetPlayerTokenReq logic

### ISSUE THREAD

**Issue by issueMel** [Melledy/Grasscutter#2514]
**Is your feature request related to a problem? Please describe.**

We can reduce the time of get player which account banned, if change the code position from HandlerGetPlayerTokenReq.java:97 to HandlerGetPlayerTokenReq.java:44.
```java
if (session.getAccount().isBanned()) {
    ...
}
```
**Describe the solution you'd like**

Change the code from HandlerGetPlayerTokenReq.java:97 to HandlerGetPlayerTokenReq.java:44. Could I make a pull request for this?

**Describe alternatives you've considered**

**Additional context**

**Comment by KingRainbow44** [comment]
yes you can absolutely PR this!

**Comment by issueMel** [comment]
PacketGetPlayerTokenRsp.java:44 need player getAvatarCount() , so we still need setPlayer before check account state.
If I find a way to replace it, i will make a pr for this.
