### ISSUE TITLE
Connection always timed out/总是连接超时

### ISSUE THREAD

**Issue by RAINighty** [Melledy/Grasscutter#252]
![image](https://user-images.githubusercontent.com/97167694/165210122-7509f117-826d-46ec-8a9e-f715e41e71e6.png)
how to fix it?

**Comment by RAINighty** [comment]
![K9F~4QNW_RN 193TWGE QT9](https://user-images.githubusercontent.com/97167694/165211104-ecb68701-5f2d-40f5-a582-6e34cffffed1.png)

**Comment by Mashiro2000** [comment]
你的远程服务器还是本地服务器？

**Comment by Zhaokugua** [comment]
可能是你gameserver的udp端口没开

**Comment by RAINighty** [comment]
> 可能是你gameserver的udp端口没开

开放了TCP22102和UDP22102

**Comment by RAINighty** [comment]
> 你的远程服务器还是本地服务器？

远程服务器

**Comment by Zhaokugua** [comment]
> > 可能是你gameserver的udp端口没开
> 
> 开放了TCP22102和UDP22102

确定防火墙或者安全组都放开了吗，重启一下防火墙？

**Comment by RAINighty** [comment]
> > > 可能是你gameserver的udp端口没开
> > 
> > 
> > 开放了TCP22102和UDP22102
> 
> 确定防火墙或者安全组都放开了吗，重启一下防火墙？

防火墙是关闭的，安全组确认添加了上述两个端口，重启服务器后仍然连接超时

**Comment by Zhaokugua** [comment]
> > > > 可能是你gameserver的udp端口没开
> > > 
> > > 
> > > 开放了TCP22102和UDP22102
> > 
> > 
> > 确定防火墙或者安全组都放开了吗，重启一下防火墙？
> 
> 防火墙是关闭的，安全组确认添加了上述两个端口，重启服务器后仍然连接超时

config.json里面的PublicIp都改成服务器的了吧

**Comment by RAINighty** [comment]
> > > > > 可能是你gameserver的udp端口没开
> > > > 
> > > > 
> > > > 开放了TCP22102和UDP22102
> > > 
> > > 
> > > 确定防火墙或者安全组都放开了吗，重启一下防火墙？
> > 
> > 
> > 防火墙是关闭的，安全组确认添加了上述两个端口，重启服务器后仍然连接超时
> 
> config.json里面的PublicIp都改成服务器的了吧

我是傻逼，gameserver的publicip没改，现在能进了，我是傻逼

**Comment by JkLoveLiu** [comment]
> > > > > > 可能是你gameserver的udp端口没开
> > > > > 
> > > > > 
> > > > > 开放了TCP22102和UDP22102
> > > > 
> > > > 
> > > > 确定防火墙或者安全组都放开了吗，重启一下防火墙？
> > > 
> > > 
> > > 防火墙是关闭的，安全组确认添加了上述两个端口，重启服务器后仍然连接超时
> > 
> > 
> > config.json里面的PublicIp都改成服务器的了吧
> 
> 我是傻逼，gameserver的publicip没改，现在能进了，我是傻逼

publicip改成哪个可以进去的，我改过几次但还是进不去

**Comment by Zhaokugua** [comment]
> > > > > > > 可能是你gameserver的udp端口没开
> > > > > > 
> > > > > > 
> > > > > > 开放了TCP22102和UDP22102
> > > > > 
> > > > > 
> > > > > 确定防火墙或者安全组都放开了吗，重启一下防火墙？
> > > > 
> > > > 
> > > > 防火墙是关闭的，安全组确认添加了上述两个端口，重启服务器后仍然连接超时
> > > 
> > > 
> > > config.json里面的PublicIp都改成服务器的了吧
> > 
> > 
> > 我是傻逼，gameserver的publicip没改，现在能进了，我是傻逼
> 
> publicip改成哪个可以进去的，我改过几次但还是进不去

如果是在服务器上的话直接改成服务器的公网IP即可

**Comment by emp-java** [comment]
> 可能是你gameserver的udp端口没开

谢谢大佬，不过为什么要开udp的端口

**Comment by lishuiqiao** [comment]
> > 可能是你gameserver的udp端口没开
> 
> 谢谢大佬，不过为什么要开udp的端口

游戏登录通信是使用tcp 数据通信是用udp的

**Comment by lclty** [comment]
> 
![屏幕截图(14)](https://user-images.githubusercontent.com/102938905/200155100-053c31f9-85fa-4953-a2dc-fc5c7264d2b3.png)

大佬我安全组TCP和UDP全端口开 json里边也是两个都改了 但是登录还是连接超时
