### ISSUE TITLE
[Bug] 请教如何开启触摸？我希望串流在移动设备上玩

### ISSUE THREAD

**Issue by try1995** [Melledy/Grasscutter#2526]
请教如何开启触摸？我希望串流在移动设备上玩。
我需要使用如下命令
 GenshinImpact.exe use_mobile_platform -is_cloud 1 -platform_type CLOUD_THIRD_PARTY_MOBILE -popupwindow -borderless
但是使用客户端启动无法加入这个参数，搞个快捷方式使用命令也不行

**Comment by NotThorny** [comment]
Just launch the game with those args. I have done it with Cultivation and confirmed there's no issues with doing so. You can send those launch args with shortcut or other method if you'd like, but using Cultivation is genuinely very easy.

![ShareX_8ebsNRa75C](https://github.com/user-attachments/assets/92abd2c5-c5a8-4ef8-ac66-8c3318bbbc38)

**Comment by try1995** [comment]
> Just launch the game with those args. I have done it with Cultivation and confirmed there's no issues with doing so. You can send those launch args with shortcut or other method if you'd like, but using Cultivation is genuinely very easy.
> 
> ![ShareX_8ebsNRa75C](https://private-user-images.githubusercontent.com/107363768/358874134-92abd2c5-c5a8-4ef8-ac66-8c3318bbbc38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODk2MzcsIm5iZiI6MTcyMzk4OTMzNywicGF0aCI6Ii8xMDczNjM3NjgvMzU4ODc0MTM0LTkyYWJkMmM1LWM1YTgtNGVmOC1hYzY2LThjMzMxOGJiYmMzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQxMzU1MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MzAwY2QwNDgxZDU4Y2ZkNjdiOGMwZTE2ZDY3M2NjYmI2NTEyYzg0ZDkxNGU5YTNkOGE5ZTYzMjIyOTM2MTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W-9Yu4IWKxdCMe4fd4KNeagJwOGBu0dFzgM0PeCQ14s)

my version is 1.12.0, it dont have launch args option
![image](https://github.com/user-attachments/assets/385c4c41-6228-42df-8648-d5a3c518aa99)
how download v1.4.5?

**Comment by NotThorny** [comment]
You can get it here https://github.com/NotThorny/Cultivation/releases

**Comment by try1995** [comment]
> You can get it here https://github.com/NotThorny/Cultivation/releases

thx
