### ISSUE TITLE
[Bug] throw exception when start server

### ISSUE THREAD

**Issue by vali16** [Melledy/Grasscutter#2529]
```
19:23:30 <INFO:Grasscutter> Loading Grasscutter...
19:23:30 <INFO:Grasscutter> 正在启动 Grasscutter...
19:23:30 <INFO:Grasscutter> 游戏版本：5.0.0
19:23:30 <INFO:Grasscutter> Grasscutter 版本：1.7.5-dev-d11e13a
19:23:31 <WARN:HttpServer> [Dispatch] 未找到 SSL 证书！已回滚到 HTTP 模式
19:23:31 <INFO:ResourceLoader> 正在加载 resources...
19:23:32 <WARN:HttpServer> [Dispatch] 无法连接路由
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 14457059026087496718 at line 9 column 42 path $.preloadLuaList[0]
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:320)
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:310)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:929)
        at emu.grasscutter.utils.JsonUtils.loadToClass(JsonUtils.java:53)
        at emu.grasscutter.utils.JsonUtils.loadToClass(JsonUtils.java:67)
        at emu.grasscutter.data.ResourceLoader.lambda$loadQuests$35(ResourceLoader.java:559)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at emu.grasscutter.data.ResourceLoader.loadQuests(ResourceLoader.java:556)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:101)
        at emu.grasscutter.utils.lang.Language.loadTextMaps(Language.java:369)
        at emu.grasscutter.utils.lang.Language.loadTextMaps(Language.java:322)
        at emu.grasscutter.utils.lang.Language.getTextMapKey(Language.java:312)
        at emu.grasscutter.utils.lang.Language.getTextMapKey(Language.java:317)
        at emu.grasscutter.tools.Tools.createGachaMappingJsons(Tools.java:218)
        at emu.grasscutter.server.http.documentation.GachaMappingRequestHandler.<init>(GachaMappingRequestHandler.java:14)
        at emu.grasscutter.server.http.documentation.DocumentationServerHandler.applyRoutes(DocumentationServerHandler.java:11)
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:146)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:152)
Caused by: java.lang.NumberFormatException: Expected a long but was 14457059026087496718 at line 9 column 42 path $.preloadLuaList[0]
        at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:967)
        at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:318)
        ... 24 common frames omitted
19:23:32 <INFO:ResourceLoader> 正在加载 resources...
Exception in thread "main" java.lang.Exception: Script loader already initialized
        at emu.grasscutter.scripts.ScriptLoader.init(ScriptLoader.java:45)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:87)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:168)
```

**gracesscutter:**
grasscutter-1.7.5-dev.jar
**resources:**
https://gitlab.com/YuukiPS/GC-Resources/-/archive/5.0/GC-Resources-5.0.zip
**java:**
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)

**Comment by ghost** [comment]
Res有问题，自己排除一下

**Comment by KingRainbow44** [comment]
The resources you have provided aren't currently working. You have to wait for them to fully update in order to use `unstable`.

**Comment by lingchenma** [comment]
貌似是 20501.json 文件导致的，为啥其它几个可以正常加载成功？992.json 也有这个比较大的值，preloadLuaList，这些文件都是干啥的呀？

**Comment by ghost** [comment]
谁知道呢，里面有点错服务器就报错了

**Comment by lingchenma** [comment]
就是这个文件导致的，20501.json 跳过这个文件就能正常运行了，我试过了

**Comment by lingchenma** [comment]
或者直接删除这个文件，就行了

**Comment by lingchenma** [comment]
但是还有一些其它的问题，比如神像无法回血，无法交互，之类的问题，5.0 有这个问题，4.0就是好的，还不清楚这个要怎么修复，大佬有空一起研究一下吗？

**Comment by ghost** [comment]
可能是服务器的问题吧

**Comment by lingchenma** [comment]
我有个grasscutter.jar ，没有开源，是可以正常运行的没有这个报错，但是有其它的bug，就是我上面说的这些bug，

**Comment by ghost** [comment]
服务器如果没有用到正确的proto，有些功能也是用不了的，或者服务器没有实现这个功能

**Comment by ghost** [comment]
之前我为了实现雷电转二阶段把我整得头都大(本人纯小白

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/e27c6d3e-fa58-4ccb-b906-6a3d5078fd8f)
代码zhe这样写，先试试应该能捕获到NumberFormatException异常

**Comment by ghost** [comment]
数值超出了long的最大存储数值

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/773e2244-7e84-4d8a-8820-957c28244566)
到这个就会触发异常

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/f2beb645-d69c-467c-9c42-f0b43618ee47)

**Comment by ghost** [comment]
> 数值超出了long的长度

然后就报错了

**Comment by lingchenma** [comment]
那就是rec 文件错误了？还是不应该这么大？

**Comment by ghost** [comment]
不清楚

**Comment by lingchenma** [comment]
那就是这个长度超过了long值的限制

**Comment by ghost** [comment]
![63962d5f-ed0e-4420-a898-207eb9103399](https://github.com/user-attachments/assets/e791a8ff-c81f-4a46-bfe9-c61bd2abc2b3)
看看这吧

**Comment by ghost** [comment]
AI生成的，不一定准确

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/ab015328-1a16-4fe8-b721-dbe49077e1ad)
![image](https://github.com/user-attachments/assets/9801c9df-be54-4357-9b21-647c27e073c2)
就是这个问题了，值超过了java 的long最大上限

**Comment by lingchenma** [comment]
为啥这个类 MainQuestData 里面没有 luaPath 变量？

**Comment by ghost** [comment]
不懂

**Comment by lingchenma** [comment]
ok 换成 private BigInteger[] preloadLuaList; 成功了
![image](https://github.com/user-attachments/assets/f34f7bb9-44d3-4260-b901-ee2943efa840)

**Comment by ghost** [comment]
你测一下吧，先要知道这个文件是干什么的

**Comment by lingchenma** [comment]
居然那个 没有开源的 grasscutter.jar 没有这个字段 preloadLuaList，所以没有报错

**Comment by lingchenma** [comment]
我不清楚，要怎么测试呀，是测试哪里呀？

**Comment by ghost** [comment]
如果是Quest的话，任务吧

**Comment by lingchenma** [comment]
卡白屏，你知道是啥问题吗？
![image](https://github.com/user-attachments/assets/fdeb6623-6073-4a19-9c60-48f801d19875)
会出现频繁断开连接，

**Comment by ghost** [comment]
有UID出来吗

**Comment by lingchenma** [comment]
测试任务是不是太多了？

**Comment by lingchenma** [comment]
白屏的时候，有UID，没有出现元素图标

**Comment by ghost** [comment]
把服务重启试试

**Comment by lingchenma** [comment]
我编译成jar 单独运行了，这次启动成功了，不过有其它报错
![image](https://github.com/user-attachments/assets/95e2406b-b88c-484c-b4f0-e8594077c463)

**Comment by ghost** [comment]
这个正常

**Comment by lingchenma** [comment]
还是和上次一样会卡这个任务
![image](https://github.com/user-attachments/assets/93f05c80-59c4-420f-8bcd-b9a1e281f477)
，后面的风魔龙眼泪交互，和这个有没有关系？

**Comment by ghost** [comment]
不一定

**Comment by lingchenma** [comment]
这个preloadLuaList变量我看都没有用到，应该没有啥影响吧？

**Comment by ghost** [comment]
大概吧

**Comment by lingchenma** [comment]
无法采集壁虎材料，你知道是啥原因吗？

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/363c781d-b9b1-465c-9155-0e6fc4daeb38)
还会出现这样的bug

**Comment by Ylsaoe** [comment]
GC端我大概也就体验打Boss的，别的我不是很关心

https://github.com/user-attachments/assets/b1b1a815-3410-4101-87e5-63651031d178

**Comment by lingchenma** [comment]
我找到了，大概应该还是的EnvAnimalGatherConfigData 里面的 EnvAnimalGatherExcelConfigData.json 没有配置一些文件默认值导致的

**Comment by ghost** [comment]
https://github.com/Kei-Luna/LunaGC_5.0.0/pull/22

**Comment by lingchenma** [comment]
你知道rec资源是怎么提取吗？

**Comment by ghost** [comment]
你可以去问会dump资源的人

**Comment by lingchenma** [comment]
哦哦，知道了，rec 里面好像有个工具，应该是做dump用的

**Comment by lingchenma** [comment]
SetEntityServerGlobalValueByEntityId 这个函数是做啥的？

**Comment by ghost** [comment]
> https://github.com/Kei-Luna/LunaGC_5.0.0/pull/22

这个可以解决雷电二阶段的问题，在ScriptLib类里

**Comment by lingchenma** [comment]
哦哦，晚点看看

**Comment by Ylsaoe** [comment]
![image](https://github.com/user-attachments/assets/7913eb7b-557e-43e8-a17a-79723039fe74)
这个注释掉的方法没有用上就很难绷

**Comment by lingchenma** [comment]
ok 找到问题了，蜥蜴那个道具，新版本是改了变量名称的，但是代码用的还是旧版本的名称，所以会报错

**Comment by ghost** [comment]
这确实值得注意

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/91cd6a65-41bc-4113-80ee-d0c1a3644a2b)
好了

**Comment by Ylsaoe** [comment]
> 哦哦，知道了，rec 里面好像有个工具，应该是做dump用的
说到这个dump，我还真不懂逆向

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/3c9a4814-c153-4c25-81eb-39e0b93fff0e)
你知道这个，是属于什么交互的吗？我看看能不能修这个bug
![image](https://github.com/user-attachments/assets/2da49abe-513a-4bca-b566-13b04467d3c2)

**Comment by ghost** [comment]
你翻译一下它的文件名，你就知道他是干嘛的了

**Comment by Ylsaoe** [comment]
我还没去研究过，今天太累了，我也不是很想去研究了

**Comment by lingchenma** [comment]
关键，没有看到报错信息，没法入手找

**Comment by ghost** [comment]
我去看看

**Comment by Ylsaoe** [comment]
> 我去看看

好吧，太难了

**Comment by lingchenma** [comment]
不清楚为啥4.0 是好的

**Comment by ghost** [comment]
> 不清楚为啥4.0 是好的

看看proto吧

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/bc64a6a7-1ac7-4ddc-a1fc-850b2ca78119)
是这些文件吗？

**Comment by ghost** [comment]
嗯

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/79fba3ae-ee8c-4ed0-9a8c-00202048d43b)

**Comment by lingchenma** [comment]
这些定义是啥？是否启用这个类吗？我看这些这些类都是内部类

**Comment by ghost** [comment]
> 这些定义是啥？是否启用这个类吗？我看这些这些类都是内部类

你还是去了解一下protobuf的定义吧

**Comment by lingchenma** [comment]
这些定义成1 是不是不对呀？需要正确的通行id 才能通信？

**Comment by ghost** [comment]
嗯

**Comment by lingchenma** [comment]
那可以打个log 看看，那些正常 发过来的id ，没有被服务器处理，应该可以吧？

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/44640c56-e932-470a-a891-0661f745a111)
有个丢失的枚举，id ，看着没有捕获，所以好像没有打印log

**Comment by Ylsaoe** [comment]
![ac8368de30a76d14f68f716107381357c17af81a](https://github.com/user-attachments/assets/1aa2894e-0297-4e9b-9785-de4e72a28757)

**Comment by ghost** [comment]
https://github.com/Kei-Luna/LunaGC_Proto_5.0.0
去看看这个吧，然后看看每个proto文件里的cmdid是啥

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/92e2ee35-88ee-4b9d-973a-8104b5bd38f0)
 好像只有这个三个文件有id

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/bf3319cb-d0c4-4f80-a14a-05eb421aaf68)
看这个吧，都是反序列化的，一堆看不懂的

**Comment by ghost** [comment]
这个就得你自己去排查了，或者https://gitlab.com/YuukiPS/GC-Proto

**Comment by Ylsaoe** [comment]
有些pr还不是5.0的

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/4e0035ba-2155-4262-8efe-a5b64e0a5c82)
这个你知道是按照哪个来吗？

**Comment by Ylsaoe** [comment]
> ![image](https://private-user-images.githubusercontent.com/178367112/384673086-bf3319cb-d0c4-4f80-a14a-05eb421aaf68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMjk0OTYsIm5iZiI6MTczMTIyOTE5NiwicGF0aCI6Ii8xNzgzNjcxMTIvMzg0NjczMDg2LWJmMzMxOWNiLWQwYzQtNGY4MC1hMTRhLTA1ZWI0MjFhYWY2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwODU5NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYWU4MDliNDNiYmUwMmU4MjkxOTQ1MjEzNTMzMzZiM2IzNTQwZTRhMjcwZGNmMDkyNTFmZWVjNjUwZmMzMDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5Sm4r5LJGmjH5M-Msl7Blqg-cpsUu4CbQScdgmVv24g) 看这个吧，都是反序列化的，一堆看不懂的

主要还是看这吧

**Comment by lingchenma** [comment]
all-in-one.proto 有的没有，比如PlayerEnterChildMapLayerNotify 这个

**Comment by Ylsaoe** [comment]
我要泪目了

**Comment by Ylsaoe** [comment]
给你看个示例吧

**Comment by Ylsaoe** [comment]
![image](https://github.com/user-attachments/assets/5d1bfaa4-e8ed-4401-a083-0ac1645a582a)
比如这是一个你不知道的proto名

**Comment by Ylsaoe** [comment]
你要自己去分析它是哪个proto

**Comment by lingchenma** [comment]
客户端，会发过来正确的 cmdid 吗？

**Comment by Ylsaoe** [comment]
原先的ServerGlobalValueChangeNotify跟它像的话，就去试一下对不对
![image](https://github.com/user-attachments/assets/5e8ad627-e19e-496d-9c59-1d2400c93b16)
![image](https://github.com/user-attachments/assets/63ffcdb7-6c7f-4ce6-a3e9-cfcbc85372b5)

**Comment by ghost** [comment]
> 客户端，会发过来正确的 cmdid 吗？

不知道，你要是想要任务正常就去玩真端去吧，GC是不行的

**Comment by ghost** [comment]
你去社区问问吧

**Comment by lingchenma** [comment]
![image](https://github.com/user-attachments/assets/adb91e09-42ec-49a2-b2e9-ae839a899c29)
![image](https://github.com/user-attachments/assets/b79c14f4-8259-44f3-8ae6-2b6980f5f929)
找到了，客户端确实会发送正确的cmdid

**Comment by Ylsaoe** [comment]
不懂

**Comment by lingchenma** [comment]
那个，交互道具没有，应该是客户端缺失配置导致的不显示的问题吧？我看客户端，没有向服务器发送请求，进入神像和离开神像都是可以收到请求

**Comment by ghost** [comment]
哪个道具

**Comment by lingchenma** [comment]
就是那个风魔龙的眼泪，看不到交互物

**Comment by Ylsaoe** [comment]
这样吧，我上3.2真端看看吧

**Comment by Ylsaoe** [comment]
我先看看pr

**Comment by ghost** [comment]
> 就是那个风魔龙的眼泪，看不到交互物

去discord说吧

**Comment by lingchenma** [comment]
有链接吗

**Comment by Ylsaoe** [comment]
你dc什么名

**Comment by Lingchen218** [comment]
legendary_courgette_70267 这个吗？
![image](https://github.com/user-attachments/assets/a4bf1107-c59c-4672-9298-f7db4db1a2a6)

**Comment by Ylsaoe** [comment]
嗯
