### ISSUE TITLE
Client TLS handshake failed

### ISSUE THREAD

**Issue by hanbao233xD** [Melledy/Grasscutter#253]
logs:
Loading script proxy.py
Proxy server listening at http://*:8080
127.0.0.1:60185: client connect
127.0.0.1:60185: server connect 203.107.54.189:443
127.0.0.1:60185: GET https://203.107.54.189/query_security_file?file_key=CNRELWin2.6.0
              << 200 OK 2.6k
127.0.0.1:60185: client disconnect
127.0.0.1:60185: server disconnect 203.107.54.189:443
127.0.0.1:60196: client connect
127.0.0.1:60196: server connect 203.107.54.189:443
127.0.0.1:60196: GET https://203.107.54.189/query_security_file?file_key=CNRELWin2.6.0
              << 200 OK 2.6k
127.0.0.1:60196: client disconnect
127.0.0.1:60196: server disconnect 203.107.54.189:443
127.0.0.1:60301: client connect
127.0.0.1:60301: server connect 101.246.177.101:443
127.0.0.1:60301: Client TLS handshake failed. Client and mitmproxy cannot agree on a TLS version to use. You may need to adjust mitmproxy's tls_version_client_min option.
127.0.0.1:60301: client disconnect
127.0.0.1:60301: server disconnect 101.246.177.101:443

**Comment by soloopooo** [comment]
local proxy didn't properly configured. if properly configured, the server connect will be some "domains".
```
Loading script .\proxy.py
Proxy server listening at http://*:8080
127.0.0.1:57837: client connect
127.0.0.1:57842: client connect
127.0.0.1:57837: server connect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57837: client disconnect
127.0.0.1:57837: server disconnect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57842: server connect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57842: client disconnect
127.0.0.1:57842: server disconnect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57854: client connect
127.0.0.1:57859: client connect
127.0.0.1:57854: server connect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57859: server connect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57859: client disconnect
127.0.0.1:57859: server disconnect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57854: server connect 127.0.0.1:443
127.0.0.1:57854: GET https://127.0.0.1/query_security_file?file_key=CNRELWin2.6.0
              << 200 OK 5b
127.0.0.1:57854: client disconnect
127.0.0.1:57854: server disconnect dispatchcnglobal.yuanshen.com:443 (127.193.0.107:443)
127.0.0.1:57854: server disconnect 127.0.0.1:443
```

**Comment by lulu8879** [comment]
i have same issue, idk why got those issue in middle game
solved by re-run the server

**Comment by memetrollsXD** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
