### ISSUE TITLE
[Bug] java.lang.NumberFormatException: For input string: "Energy"

### ISSUE THREAD

**Issue by gptlang** [Melledy/Grasscutter#2540]
**Describe the bug**
https://github.com/Grasscutters/Grasscutter/blob/9c36daa3fa8be5f9ec26fbb2b36f3e1dceff977d/src/main/java/emu/grasscutter/data/binout/AbilityModifier.java#L348-L350

param3 is meant to be an int but in some places it's "Energy" instead in https://gitlab.com/YuukiPS/GC-Resources.

**Which branch did you use?**
1.7.4-9c36daa3f

**Comment by gptlang** [comment]
```
rg -l '"param3": "Energy"' | xargs sed -i 's/"param3": "Energy"/"param3": 0/'
```
Fixes that specific issue but there's still multiple bugs relating to wrong data types?

**Comment by Hartie95** [comment]
There should be more cases where it's not an int. In my fork we are moving param1-3 to the dynamic float type:
https://github.com/Anime-Game-Servers/Grasscutter-Quests/pull/161/files#diff-a2ec6570999f1c3957400bc1e3fd08d22db206d76f2fadb99fbec5ce9e192b65R149
