### ISSUE TITLE
how to get BinOutput v2.6

### ISSUE THREAD

**Issue by graydovee** [Melledy/Grasscutter#258]
[gin-bin-output](https://github.com/radioegor146/gi-bin-output) only has v2.2 and 2.5.52
[GenshinData](https://github.com/Dimbreath/GenshinData) only has  a old version and a obfuscated version
where can we get deobfuscated BinOutput v2.6?

**Comment by Lynricsy** [comment]
Use 2.5.52.

**Comment by alt3ri** [comment]
please go to #support channel in discord instead.
