### ISSUE TITLE
Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.

### ISSUE THREAD

**Issue by MoonShadowIllusion** [Melledy/Grasscutter#259]
Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.

These two files already exist. How can I solve this error

**Comment by 1shin-7** [comment]
Replace these two files with the following versions
- [ReliquaryMainPropExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json)

- [ReliquaryAffixExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json)

**Comment by MoonShadowIllusion** [comment]
> Replace these two files with the following versions
> 
> * [ReliquaryMainPropExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json)
> * [ReliquaryAffixExcelConfigData.json](https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json)

ok
