### ISSUE TITLE
[ERROR] Scene point files cannot be found, you cannot use teleport waypoints!  [ERROR] No spawn data loaded!

### ISSUE THREAD

**Issue by JkLoveLiu** [Melledy/Grasscutter#260]
[19:52:25] [ERROR] Scene point files cannot be found, you cannot use teleport waypoints!
[19:52:25] [ERROR] No spawn data loaded!

two errors
and
The client does not respond after entering the command

**Comment by 1shin-7** [comment]
- Check the existence of the file
    - resources/BinOutput/Scene/Point
    - data/Spawns.json
- Running commands ingame need to be added `!` Or `/` prefix

**Comment by tb114514** [comment]
> * 检查文件是否存在
>   
>   * 资源/BinOutput/场景/点
>   * 数据/Spawns.json
> * 游戏内运行命令需要加`!`或`/`前缀

那Spawns.json从哪下载

**Comment by tb114514** [comment]
> * 检查文件是否存在
>   
>   * 资源/BinOutput/场景/点
>   * 数据/Spawns.json
> * 游戏内运行命令需要加`!`或`/`前缀

给个资源地址

**Comment by tb114514** [comment]
> * 检查文件是否存在
>   
>   * 资源/BinOutput/场景/点
>   * 数据/Spawns.json
> * 游戏内运行命令需要加`!`或`/`前缀

蟹蟹

**Comment by 1shin-7** [comment]
> > * 检查文件是否存在
> >   
> >   * 资源/BinOutput/场景/点
> >   * 数据/Spawns.json
> > * 游戏内运行命令需要加`!`或`/`前缀
> 
> 给个资源地址
> 

啊 看wiki就行哦

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by tb114514** [comment]
> > > * 检查文件是否存在
> > >   
> > >   * 资源/BinOutput/场景/点
> > >   * 数据/Spawns.json
> > > * 游戏内运行的任务需要添加`!`或`/`显眼的游戏
> > 
> > 
> > 给个资源地址
> 
> 啊看wiki就行哦

没找到啊，具体给个链接呗
