### ISSUE TITLE
error 4206

### ISSUE THREAD

**Issue by JinZongxiao** [Melledy/Grasscutter#264]
`{
  "DispatchServerIp": "127.0.0.1",
  "DispatchServerPublicIp": "",
  "DispatchServerPort": 443,
  "DispatchServerKeystorePath": "./keystore.p12",
  "DispatchServerKeystorePassword": "123456",
  "UseSSL": true,
  "GameServerName": "Test",
  "GameServerIp": "127.0.0.1",
  "GameServerPublicIp": "",
  "GameServerPort": 22102,
  "UploadLogPort": 80,
  "DatabaseUrl": "mongodb://localhost:27017",
  "DatabaseCollection": "grasscutter",
  "RESOURCE_FOLDER": "./resources/",
  "DATA_FOLDER": "./data/",
  "PACKETS_FOLDER": "./packets/",
  "DUMPS_FOLDER": "./dumps/",
  "KEY_FOLDER": "./keys/",
  "LOG_PACKETS": false,
  "Game": {
    "ADVENTURE_EXP_RATE": 1.0,
    "MORA_RATE": 1.0,
    "DOMAIN_DROP_RATE": 1.0
  },
  "ServerOptions": {
    "InventoryLimitWeapon": 2000,
    "InventoryLimitRelic": 2000,
    "InventoryLimitMaterial": 2000,
    "InventoryLimitFurniture": 2000,
    "InventoryLimitAll": 30000,
    "MaxAvatarsInTeam": 4,
    "MaxAvatarsInTeamMultiplayer": 4,
    "MaxEntityLimit": 1000,
    "WelcomeEmotes": [
      2007,
      1002,
      4010
    ],
    "WelcomeMotd": "Welcome to Grasscutter emu"
  }
}`

this is my config.json

**Comment by JinZongxiao** [comment]
![image](https://user-images.githubusercontent.com/39488451/165344043-16b355c4-6471-46dd-98c1-f7cdc80dcf48.png)

**Comment by Secretboy-SMR** [comment]
execute dir and let me have a look

**Comment by JinZongxiao** [comment]
> execute dir and let me have a look

![image](https://user-images.githubusercontent.com/39488451/165346374-3410ca0f-7db1-4909-b7fb-70712747acf3.png)

**Comment by JinZongxiao** [comment]
4206之后我修改了一下config文件，usessl=true，password=123456，勾八服务器都进不去了，救救我，大佬。

**Comment by alt3ri** [comment]
install the keystore.p12

**Comment by JinZongxiao** [comment]
after 4206,I amend config.json usessl=true，password=123456,damn I can't log into the server,help me! Big lao!

**Comment by JinZongxiao** [comment]
> install the keystore.p12

安装了，还是报错no ssl cert found

**Comment by JinZongxiao** [comment]
server goes like
![image](https://user-images.githubusercontent.com/39488451/165348592-0237b948-16c0-4b77-ac6d-7536b127749f.png)

**Comment by JinZongxiao** [comment]
why connection always J8 disconnect

**Comment by alt3ri** [comment]
go to #support-other channel in Discord so some Chinese people can support you
去 Discord 中的#support-other 频道，这样一些中国人可以支持你
Sorry, I've to use Google Translate because I don't know Chinese
抱歉，我不会中文，只能用谷歌翻译

**Comment by JinZongxiao** [comment]
> go to #support-other channel in Discord so some Chinese people can support you
> 去 Discord 中的#support-other 频道，这样一些中国人可以支持你
> Sorry, I've to use Google Translate because I don't know Chinese
> 抱歉，我不会中文，只能用谷歌翻译

thanks for ur patient reply.I know English.I mean I’ve installed keystone.Do you mean Click and install this file? Or install with cmd.

**Comment by alt3ri** [comment]
Yes, click and install the file directly

**Comment by JinCODER** [comment]
> 

I’ve done.it still goes like the pic I’ve sent above.

**Comment by JinZongxiao** [comment]
> Yes, click and install the file directly

I’ve done.it still goes like the pic I’ve sent above.

**Comment by memetrollsXD** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
