### ISSUE TITLE
artifacts generated by "give" command  have no stat

### ISSUE THREAD

**Issue by 1-lavender-1** [Melledy/Grasscutter#266]
![image](https://user-images.githubusercontent.com/104431284/165353370-f5522058-ed1c-45d8-b98d-91d37689d0f5.png)
![image](https://user-images.githubusercontent.com/104431284/165353934-fa6db567-208d-466e-a200-45b879ceb7a3.png)

I can't change my artifacts' stats even in MongoDB Compass

**Comment by jinmvp** [comment]
U used the wrong ID, there's 4 of them. The one u used is non substats, try use GM handbook and search for the ID u use, there will be like 3 of them below that ID. Use that u will see the substats.

**Comment by memetrollsXD** [comment]
Replace these in your resources/ExcelBinOutput folder:

https://github.com/Dimbreath/GenshinData/blob/104c21c6530885e450975b13830639e9ca649799/ExcelBinOutput/ReliquaryMainPropExcelConfigData.json

https://github.com/Dimbreath/GenshinData/blob/a92b5842daa911c095f47ef235b2bcd4b388d65a/ExcelBinOutput/ReliquaryAffixExcelConfigData.json
