### ISSUE TITLE
ERROR with 12-4301

### ISSUE THREAD

**Issue by WinterG26** [Melledy/Grasscutter#267]
![IMG_0759](https://user-images.githubusercontent.com/19148211/165362411-bab0b9af-e18e-4e14-8a79-70cde02baad2.PNG)

**Comment by WinterG26** [comment]
it looks like no same problem in other issues

**Comment by alt3ri** [comment]
go to #support-other channel in Discord so some Chinese people can support you
去 Discord 中的#support-other 频道，这样一些中国人可以支持你
Sorry, I've to use Google Translate because I don't know Chinese
抱歉，我不会中文，只能用谷歌翻译

**Comment by memetrollsXD** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by thomasxu1991** [comment]
same error, waiting for a solution.

**Comment by TheLostTree** [comment]
Please visit the [Discord](https://discord.gg/T5vZU6UyeG) and give more information in the #support channel.
