### ISSUE TITLE
[Database] use actual value of enum to store instead of enum name

### ISSUE THREAD

**Issue by WetABQ** [Melledy/Grasscutter#273]
Caused by #226

![image](https://user-images.githubusercontent.com/25319400/165416226-f704a8c8-37ef-4f3d-a1c8-ddb2fb51368e.png)

**Comment by WetABQ** [comment]
@KingRainbow44 @Melledy @memetrollsXD

**Comment by ghost** [comment]
This has been handled already (albiet in a bad way), but its no longer an issue.
