### ISSUE TITLE
I cannot connect to the server through the public network ip

### ISSUE THREAD

**Issue by Dough-su** [Melledy/Grasscutter#274]
**Describe the bug**
I can run this server on this machine, but after deploying to the server,I have modified the configuration files for config.json and fiddler， I can't log in through the public network ip, and there is no error, but the fiddler shows that the connection to the server is red.

**Screenshots**
![image](https://user-images.githubusercontent.com/27874181/165417124-42396195-b792-4655-8970-8a1995f6cc14.png)
![image](https://user-images.githubusercontent.com/27874181/165417403-c56f0826-9c29-462e-b692-563b7503fd84.png)
![image](https://user-images.githubusercontent.com/27874181/165417427-103676e2-1228-4efd-98fe-f80a86309c44.png)
**Desktop 
 - OS: [ Windows10]

**Comment by 9426224** [comment]
Check config.json,  a **KeystorePassword** is required, the value is "123456"

**Comment by Dough-su** [comment]
> Check config.json, a **KeystorePassword** is required, the value is "123456"

I tried this method and turned off ssl. 
But still can't connect locally.
![image](https://user-images.githubusercontent.com/27874181/165448851-248f6f2f-3e13-46d0-a498-c071203b5b81.png)

**Comment by MysEon** [comment]
> > Check config.json, a **KeystorePassword** is required, the value is "123456"
> 
> I tried this method and turned off ssl. But still can't connect locally. ![image](https://user-images.githubusercontent.com/27874181/165448851-248f6f2f-3e13-46d0-a498-c071203b5b81.png)

Have you solved the problem?

**Comment by KingRainbow44** [comment]
if you're trying to connect locally, you have to use `127.0.0.1` or your **local** IPv4 address (from something like `ipconfig`). using a public IP is only applicable if you want to port forward, but this comes with the trade-off that **you** cannot locally connect.
