### ISSUE TITLE
why can't i login again，bug？

### ISSUE THREAD

**Issue by YaeRiko** [Melledy/Grasscutter#285]
I can't log in again,and i don't know when it started.
Is this a bug?

**Comment by Scirese** [comment]
You didnt post any detail of the problem.how can we help you?
WE ARE DEVELOPERS ,NOT FORTUNE TELLERS

**Comment by alt3ri** [comment]
Please, don't make an Github account just to open an issue

**Comment by Hangsang** [comment]
R U FUCKING DUMB QQQQQQQQQ

**Comment by 4Benj** [comment]
This is for reporting issues, not for support. Please post your issue in the appropriate [Discord](https://discord.gg/T5vZU6UyeG) support channel WITH RELEVANT LOGS.

**Comment by 1shin-7** [comment]
![19538625352441.jpg](https://user-images.githubusercontent.com/49867372/165465110-ac3aaf22-df1e-42c7-b9a0-32d516bda43c.jpg)

**Comment by Yazawazi** [comment]
There are no error logs, so I would venture to guess that you are using the dev branch, and suggest dropping the grasscutter database first haha.

**Comment by YaeRiko** [comment]
eeeee now i'm pretty sure it's my problem, it is now back to normal, but this is still the case after click esc and quit game, point the login no response, solution is turn off and on again

**Comment by Yazawazi** [comment]
error logs pls, tqvm

**Comment by YaeRiko** [comment]
I'm a code noob, and frankly, I shouldn't post this query because it's a miracle that I can open this program...........

**Comment by 01101sam** [comment]
> I'm a code noob, and frankly, I shouldn't post this query because it's a miracle that I can open this program...........

Please, try not to use this program and your problem is fixed.
Thank you for having interest for this repo, but this is not the repo for starters.
