### ISSUE TITLE
How to increase Entries of relic

### ISSUE THREAD

**Issue by Lubin502831** [Melledy/Grasscutter#29]

**Comment by Lubin502831** [comment]
My English is not very good, it should be skillAffix of Relics

**Comment by KingRainbow44** [comment]
The GitHub issue tracker is **not** a support forum. Join our [support Discord](https://discord.gg/T5vZU6UyeG) and ask in the `#support` channel instead.

**Comment by memetrollsXD** [comment]
It looks like the support discord just disabled invites, I'm currently asking about it (@KingRainbow44)
