### ISSUE TITLE
 Kazuha and Ayaka have something wrong

### ISSUE THREAD

**Issue by Genshinjub** [Melledy/Grasscutter#294]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by memetrollsXD** [comment]
Please re-submit an issue with the details filled in.

(Your issue sounds like you need to use the 2.5.52 BinOutput from https://github.com/radioegor146/gi-bin-output/)
