### ISSUE TITLE
[Latest Dev] Server command input cannot accept Non-ASCII characters.

### ISSUE THREAD

**Issue by soloopooo** [Melledy/Grasscutter#301]
**Describe the bug**
When using /sendmail, the console cannot accept non-ascii characters. But in-game can be handled correctly.

**To Reproduce**
Type non-ascii characters in server console.

**Expected behavior**
Non-ascii characters should also be accepted.

**Screenshots**
![image](https://user-images.githubusercontent.com/36123081/165515621-2c48316e-26f4-43b2-84d3-c10652c203c4.png)
![image](https://user-images.githubusercontent.com/36123081/165515877-c98cf7e0-4258-45f2-ae82-22ab3b3f3384.png)
![image](https://user-images.githubusercontent.com/36123081/165516079-1edb450e-286a-4f35-aff6-ed15f9b6ecdf.png)

**Desktop (please complete the following information):**
 - OS: Windows 11, Running JDK 18
 - Version Dev

**Additional context**

**Comment by alt3ri** [comment]
it's the console fault, not the game or command fault

**Comment by soloopooo** [comment]
> it's the console fault, not the game or command fault

I think it's Java's thing because it is run on Pwsh 7.3.3 under Windows Terminal.

Nothing should be incompatible in Non-ASCII characters in these 2 things.

**Comment by KingRainbow44** [comment]
related to #302
