### ISSUE TITLE
How do I log in when I first enter the game

### ISSUE THREAD

**Issue by NoDoon** [Melledy/Grasscutter#303]
When I first logged in, it said something like this. The username was not found when I logged in after registering the account
![QQ截图20220427175432](https://user-images.githubusercontent.com/66499633/165524447-1e799ef7-175b-42be-9c21-f94b2b50b541.png)
<uid:0 -time: 1651053117088-auid: -rtt:O [0,0,0]>NullReferenceException: A null value was found where an object instance was

**Comment by Scirese** [comment]
There will be some bug if u use CNREL,switch to OSREL will solve it.

**Comment by Alan-Raddam** [comment]
Using game version CNREL will cause this problem, though you can safely ignore this error. It shouldn't impact any implemented features. If you are annoyed about it, you can switch to OSREL.
