### ISSUE TITLE
start.cmd can't find mitmdump and mongoDB

### ISSUE THREAD

**Issue by Lynricsy** [Melledy/Grasscutter#305]
**Describe the bug**
start.cmd can't find mitmdump and mongoDB although I've already added them to `PATH`.

**To Reproduce**
Use `start.cmd`.

**Expected behavior**
Start MongoDB,mitmdump and the server.

**Screenshots**
![image](https://user-images.githubusercontent.com/62173814/165543433-dca71c57-6d25-497b-b713-67ea119f7c73.png)
![image](https://user-images.githubusercontent.com/62173814/165544133-2b06148d-36a6-4ca8-a977-342839837dc6.png)

**Desktop (please complete the following information):**
 - OS: Windows 22579
 - Version GitHub Action Build #296 

**Additional context**
[22:35:48] [INFO] Welcome to Grasscutter
[22:35:48] [INFO] To proper exit this console, use [Ctrl + C] and enter N not Y.
[22:35:48] [INFO]
[22:35:48] [INFO] Initializing...
[22:35:48] [WARN] mitmdump not found, server only mode.
[22:35:48] [WARN] MongoDB daemon not found, server only mode.
[22:35:48] [INFO] Starting server...
Error: Unable to access jarfile grasscutter.jar
[22:35:48] [INFO] Server stopped
[22:35:48] [INFO] MongoDB daemon not started, no need to clean up.
[22:35:48] [INFO] Proxy daemon not started, no need to clean up.
[22:35:48] [INFO] See you again :)

**Comment by Becods** [comment]
~~[Prerequisites](https://github.com/Grasscutters/Grasscutter/wiki/Running#prerequisites)~~

~~> # Prerequisites~~
~~> [MongoDB](https://www.mongodb.com/try/download/community)~~
~~> [JDK8u202](https://mirrors.huaweicloud.com/java/jdk/8u202-b08)~~

Sorry.

You need to download a release JAR from [releases](https://github.com/Melledy/Grasscutter/releases) or [build the server yourself](https://github.com/Melledy/Grasscutter/wiki/Building).
And manually start the mongodb daemon.
This is the fastest way to solve the problem.

Or I think you're using the development version, rename `grasscutter-1.0.0-dev.jar` to `grasscutter.jar` and try again. Note that the development version requires jdk17 or higher.

**Comment by MlgmXyysd** [comment]
You need to put `grasscutter.jar` `mongod.exe` `mitmdump.exe` in folder manually.

Grab `mongod.exe` [here](https://www.mongodb.com/try/download/community) (Package -> zip)

Grab `mitmdump.exe` [here](https://mitmproxy.org/downloads/) (mitmproxy-x.x.x-windows.zip)

**Comment by mofayukeji** [comment]
you can try change start_config.bat  ->" set MONGODB_PATH" and "set MITMDUMP_PATH" input the Installation directory like this :C:\Program Files (x86)\mitmproxy\bin\    or    C:\Program Files\MongoDB\Server\5.0\bin\

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
