### ISSUE TITLE
Is there a shadowrocket configuration?

### ISSUE THREAD

**Issue by AliYa-chen** [Melledy/Grasscutter#307]
Is there a shadowrocket configuration?
I try to use host and DNS game feedback display 4201.....

**Comment by soloopooo** [comment]
Please manually add the HTTP PROXY {serverip}:8080 to your shadowrocket. Needs your server and your apple devices under the same lan or your server can be directly accessed on Internet.

**Comment by AliYa-chen** [comment]
> Please manually add the HTTP PROXY {serverip}:8080 to your shadowrocket. Needs your server and your apple devices under the same lan or your server can be directly accessed on Internet.

可是服务器一直显示4201 很头疼

**Comment by soloopooo** [comment]
Is there any output on your server proxy console?

For mitmdump, there will be such outputs: 
![image](https://user-images.githubusercontent.com/36123081/165554442-72bfa2b7-60f1-4589-b31e-4fe48a40f73d.png)

**Comment by AliYa-chen** [comment]
> Is there any output on your server proxy console?
> 
> For mitmdump, there will be such outputs: ![image](https://user-images.githubusercontent.com/36123081/165554442-72bfa2b7-60f1-4589-b31e-4fe48a40f73d.png)

I can link normally on PC, but not on shadowrocket. I don't know how to configure it

**Comment by soloopooo** [comment]
Be sure using Shadowrocket's Global proxy, no bypass domain. 

Therefore, ALL network traffics to original game server can be redirected to local server.


EDIT: You don't need to use shadowrocket. Just use IOS's WIFI configuration, there is HTTP Proxy setting. But you need to install mitm's Root CA as well.

And, make sure you have properly configured `config.json`.

**Comment by AliYa-chen** [comment]
> Be sure using Shadowrocket's Global proxy, no bypass domain.
> 
> Therefore, ALL network traffics to original game server can be redirected to local server.

Do you have instant messaging tools like QQ or wechat?

**Comment by soloopooo** [comment]
> > Be sure using Shadowrocket's Global proxy, no bypass domain.
> > Therefore, ALL network traffics to original game server can be redirected to local server.
> 
> Do you have instant messaging tools like QQ or wechat?

Sorry for inconvenience. I can't send instant messages now.

**Comment by AliYa-chen** [comment]
> > > Be sure using Shadowrocket's Global proxy, no bypass domain.
> > > Therefore, ALL network traffics to original game server can be redirected to local server.
> > 
> > 
> > Do you have instant messaging tools like QQ or wechat?
> 
> Sorry for inconvenience. I can't send instant messages now.

ok.... 我还是无法解决这个问题   节点类型为http {serverip}:443  并使用全局代理  还是4201

**Comment by soloopooo** [comment]
安装代理的根证书。

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by liuyuays** [comment]
> > Please manually add the HTTP PROXY {serverip}:8080 to your shadowrocket. Needs your server and your apple devices under the same lan or your server can be directly accessed on Internet.
> 
> 可是服务器一直显示4201 很头疼

你好，请问你的解决了 4201 这个问题吗？我的也一直 4201
