### ISSUE TITLE
I had two problems.Hoping for a powerful man help me!!

### ISSUE THREAD

**Issue by sange3333333** [Melledy/Grasscutter#309]
The first one is that I cannot teleport.How can I unlock the feature?
The second one is that some characters (such as Kazuha and Kokomi who appear later) is out of control.I cannot attack,use elemental burst.How can I solve the problem?
Thank you so much!

**Comment by 9588A9588** [comment]
Compile the latest source code yourself

**Comment by 9588A9588** [comment]
Grasscutter-development branch

**Comment by sange3333333** [comment]
> Grasscutter-development branch

My sincere thanks to you! Can I get it from https://github.com/Koko-boya/Grasscutter_Resources ?

**Comment by 9588A9588** [comment]
> > Grasscutter-开发分支
> 
> 我由衷的感谢你！我可以从https://github.com/Koko-boya/Grasscutter_Resources获得它吗？

https://github.com/Grasscutters/Grasscutter/tree/development
