### ISSUE TITLE
Fail to login with error code 4206

### ISSUE THREAD

**Issue by ZhiShengYuan** [Melledy/Grasscutter#310]
`this is happend in dev version`
when I try to create an account, I got this error

>java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @310232f1
>        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
>        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
>        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
>        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
>        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
>        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
>        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:529)
>        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
>        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
>        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
>        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
>        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
>        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
>        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:102)
>        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:44)
>        at emu.grasscutter.database.DatabaseHelper.getAccountByName(DatabaseHelper.java:81)
>        at emu.grasscutter.database.DatabaseHelper.createAccountWithId(DatabaseHelper.java:28)
>        at emu.grasscutter.command.commands.AccountCommand.execute(AccountCommand.java:44)
>        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:139)
>        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:128)
>        at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)

I tried recreate all file(include databases),but useless,my OS is `Linux debian 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux` and my java version is 

>openjdk 17.0.2 2022-01-18
>OpenJDK Runtime Environment (build 17.0.2+8-Debian-1deb11u1)
>OpenJDK 64-Bit Server VM (build 17.0.2+8-Debian-1deb11u1, mixed mode, sharing)

this problem also happened in the recommended JDK version 

>openjdk 17.0.3 2022-04-19
>OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
>OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

So is there any suggestion to solve this problem?

**Comment by lixworth** [comment]
试试 jdk8

**Comment by ZhiShengYuan** [comment]
> 试试 jdk8

solved,it's my fault
i forgot change -b to dev

**Comment by ZhiShengYuan** [comment]
> 试试 jdk8

but there is another problem that fails to connect with the server with error code 4206, the "PublicIp" in `config.json` is correct, and the certification is trusted by the client

**Comment by ZhiShengYuan** [comment]
> > 试试 jdk8
>
> but there is another problem that fails to connect with the server with error code 4206, the "PublicIp" in `config.json` is correct, and the certification is trusted by the client

and the LAST log is 

>[00:11:05] [INFO] Game Server started on port 22102
>[00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53348 is trying to log in via token
>[00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53348 logged in via token as 10001
>[00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53350 succeed to exchange combo token

**Comment by circlestarzero** [comment]
> > 试试 jdk8
> 
> but there is another problem that fails to connect with the server with error code 4206, the "PublicIp" in `config.json` is correct, and the certification is trusted by the client

I met this problem, too. Is there any solution?

**Comment by ClayCoffee** [comment]
> > > 试试 jdk8
> > 
> > 
> > but there is another problem that fails to connect with the server with error code 4206, the "PublicIp" in `config.json` is correct, and the certification is trusted by the client
> 
> and the LAST log is
> 
> > [00:11:05] [INFO] Game Server started on port 22102
> > [00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53348 is trying to log in via token
> > [00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53348 logged in via token as 10001
> > [00:11:08] [INFO] [Dispatch] Client 192.168.1.21/192.168.1.21:53350 succeed to exchange combo token  

Me too. Whitescreen also appears after logging in

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
