### ISSUE TITLE
It is free to add mandatory announcements stating that changing the project.

### ISSUE THREAD

**Issue by yijiangchengming** [Melledy/Grasscutter#311]
**Is your feature request related to a problem? Please describe.**
Some people have paid to spread this project for profit, which is not conducive to the development of this project.

**Describe the solution you'd like**
I hope to add a mandatory notice when logging in the game stating that this project is free, and any charge from it is a scam. 

**Additional context**
![-7c5779a6af8eb181](https://user-images.githubusercontent.com/30022966/165576690-5d9d1dd1-a973-4ad0-98de-4d3fb5a7e71f.jpg)

**Comment by alt3ri** [comment]
You can add it in the source code. I don't think this is Grasscutter because it said 2.0. And people shouldn't make profits from an open-source program.

**Comment by memetrollsXD** [comment]
It's unethical and allowed according to our [LICENSE](https://github.com/Grasscutters/Grasscutter/blob/stable/LICENSE). Even if we add something against it, they can just remove it without any problems

**Comment by Alan-Raddam** [comment]
In current dev branch, there has been a clear warning saying that "This is a free software. If you have paid for this, you may have been scammed.". But personally, I have to say that setting up private server in China undoubtedly violates Copyright Law of the PRC according to previous judgement, and he is taking the risk of being sent into prison if mihoyo want to take legal actions.
