### ISSUE TITLE
有没有铁汁出一个视频教程啊，Java编译那块儿不知道是什么，B站已经有倒卖狗了！

### ISSUE THREAD

**Issue by 1879063397** [Melledy/Grasscutter#314]
Please！Help!

**Comment by MESFET5198** [comment]
Look for some ready-made JAR packages

**Comment by Lynricsy** [comment]
Please go to support channel on Discord to ask for help.GitHub Issue is not a place for asking for usage.

**Comment by lilmayofuksu** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by Lynricsy** [comment]
Also,you can directly download from GitHub Action and then use it without building it by urself.If you don't know how to download from GitHub Action,then the build from release is also OK.

**Comment by Lynricsy** [comment]
Please close this Issue by urself.

**Comment by alt3ri** [comment]
Please, tell to the person selling this program to stop it, or go to the prison.
