### ISSUE TITLE
"Give" Command will send message multiple times

### ISSUE THREAD

**Issue by MrAru** [Melledy/Grasscutter#319]
**Describe the bug**
Whenever one call the `/give` command, the success message will pop up multiple times.
The count of the appearing message seems equal to the number of items you required.
For an example, say one call `/give 10001 76520 1000`, and there will be 1000 messages pop up to notice you "Got <76520> x 1000".
I think this may due to some for-loops in https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/command/commands/GiveCommand.java

**To Reproduce**
1. Login, start message with the dummy char `Server`
2. Send `/give 10001 76520 1000` or any other `/give` command. Make sure the number of required item is bigger than 1.
3. Look at the crazy messages!

**Expected behavior**
The message should only be send once.

**Screenshot**
![image](https://user-images.githubusercontent.com/26517155/165622178-3ea56873-4490-4dd2-baa0-9640b66ca4fc.png)

**Desktop (please complete the following information):**
Windows, development branch, latest commit

**Comment by memetrollsXD** [comment]
According to your command (`/give 10001 76520 1000`):

`/give [player] <itemId|itemName> [amount] [level]`

- This will give items to UID 10001
- This will give item ID 76520
- This will give said item 1000 times

Are you sure you didn't mean `/give 76520 <amount> <level>`?

**Comment by MrAru** [comment]
> Are you sure you didn't mean `/give 76520 <amount> <level>`?

I know this sounds weird, but it is what I mean: send 1000 same items to player at once, not send them one item with level 1000. Please refer to the screenshot above, where I call `/give 76520 10001 10`, and as you can see, at the middle left of the screen there are lots of pop up messages which have the same content ("Got 76520 x 10". Only five message can be seen since there are maximal five messages can be placed on the screen at the same time, then the first message will disappear and new message comes in. The total number of these messages are the same as the number of items you invoked). And I think this message should be noticed only once. The actual amount of items you got in your bag is correct after calling `/give` function.

**Comment by alt3ri** [comment]
It's because you are giving yourself "unstackable item", in this case, is Artifact. This is the same with Weapon. So this isn't an issue, just a normal bug if you give yourself a huge amount of unstackable item.

**Comment by MrAru** [comment]
So this is not a bug relevant to the GC code... Thanks for your helping and this issue will be closed. Sorry for any misleading in the description :smiley:
