### ISSUE TITLE
Can not get any mora.

### ISSUE THREAD

**Issue by mikuyourworld** [Melledy/Grasscutter#321]
Can not get any mora by using gm command or destroy items.
![example picture](https://i.postimg.cc/K1hZwXQy/1.png)
![example picture](https://i.postimg.cc/21dzfHXL/2.png)

**Comment by mikuyourworld** [comment]
by the way i am using dev version.

**Comment by Lynricsy** [comment]
You can use `drop` instead.

**Comment by mikuyourworld** [comment]
> You can use `drop` instead.

I tried, I can see the drop animation, but nothing happened.
