### ISSUE TITLE
Full offline support maybe 

### ISSUE THREAD

**Issue by Pull256** [Melledy/Grasscutter#326]
When I disconnected the internet, the game will display an error 4201, which means "No network connection".
I think the proxy setting does not cut down all connections with mihoyo, may be the game itself need internet connection to mihoyo for update?
If possible, it should be possible to remove the network detection in some way to prevent the game from updating or chanting Mihayo to find out what we are doing.

Thanks for all the developers of this software.

**Comment by memetrollsXD** [comment]
The server should already support having no internet, are you sure you redirected all traffic?

**Comment by Pull256** [comment]
I just make a small test with fidder to find out why it happened, here are my result.
The fidder script I use have 24 rules downloaded from github.
When I start the game and enter the login screen, the game send many request to _log-upload-os.mihoyo.com:443_. But when the internet is disconnected, the DNS lookup will failed and throw an error which can be seen in fidder response headers like this: "HTTP/1.1 502 Fiddler - DNS Lookup Failed". Under this situation I can not login to the game.
When I reconnect the Internet the responce headers will change into "HTTP/1.1 200 Connection Established", and the game can be logined.
I don't know if my guess is accurate, because I don't know much about network. Here is the file output by fidder, hope it works.
**Thanks to the developers who are concerned about this issue, I don't think it's very urgent and maybe in the future we can get a complete solution to this problem (or maybe it's just a glitch in my settings o(╥﹏╥)o).** 

[FidderPackage.zip](https://github.com/Grasscutters/Grasscutter/files/8598936/FidderPackage.zip)

**Comment by lunaticwhat** [comment]
closed to clean up the workspace !
