### ISSUE TITLE
How to change the pools of the character and weapon?

### ISSUE THREAD

**Issue by LemonMiaocat** [Melledy/Grasscutter#328]
Sorry my java technique is poor,running the Server having taken my one day because of the 443 port problem  ,SSL Certificate lost  and the  "grasscutter.jar"  with some bugs.For me , a student who only learned mysql ,javaWeb,linux , some computer and system theory  and now is suffered from looking for work,I think is so difficult  to run the Server .I don't think that run the Server easily  just  can by double clicking  the file which is called " start.cmd "  ,because if you just run it and your enviroment path does not satisfy the requirement to the program ,then the program will pass from your eyes in one seconds ,only if you can use the powershell or cmd to run and you can see the Exception althrough Server run failed.To run Server successfully,I using much time to search the answer from baidu or CSDN , Please pardon me, I really think that is not friendly to the one as me.When I first using ideaIDE to open the source , I feel my brain is being broken , I havn't seen one explanation to the code.
When I enter the game ,I have found much bugs ,What I only can do is 抽卡.

**Comment by Skrtono** [comment]
1、先使用git clone克隆项目到本地

**Comment by Skrtono** [comment]
1

**Comment by Skrtono** [comment]
修改data文件夹下的 Banners.json文件
`{`
		`"gachaType": 200,							// <---- 添加卡池请从400开始添加`
		`"scheduleId": 803,							// <---- 这个id需要每个池子不一样`
		`"bannerType": "STANDARD",					// <----  这个有3种类型，standard表示常驻池，event表示限时活动祈愿池，weapon表示限时祈愿武器池`
		`"prefabPath": "GachaShowPanel_A016",		// <---- prefabPath... `
		`"previewPrefabPath": "UI_Tab_GachaShowPanel_A016",		// <---- 这个是抽卡的预览背景id`
		`"titlePath": "UI_GACHA_SHOW_PANEL_A016_TITLE",		// <---- 这个是抽卡的标题id，有可能与之前两项的id不同（一般这3项的id只需保持一致即可）`
		`"costItem": 224,							// <---- 这个表示祈愿用的道具，224是相遇之缘，223是纠缠之缘 - 选择一个作为该卡池的抽卡道具(提示：请不要随便修改祈愿道具除了蓝球和粉球，有可能会引发bug，比如修改成摩拉抽卡可能导致卡住)`
		`"beginTime": 0,								// <---- 祈愿什么时候开始（默认设置为0）`
		`"endTime": 1924992000,						// <---- 这个卡池持续多长时间（默认为这个极大的数字）`
		`"sortId": 1000,								// <---- 暂时未搞清楚功能，可能与卡池在屏幕的左右顺序有关`
		`"rateUpItems1": [],							// <----通常为5星的up角色或物品（可修改，查看gm手册可修改为任意角色或者物品）`
		`"rateUpItems2": [1034]						// <----  通常为4星的up物品或者角色(可修改，查看gm手册可修改为任意角色或者物品)`
	`},`

**Comment by Skrtono** [comment]
可以的话 最好加一下Discord频道讨论 里面的Support-other都是国人在讨论

**Comment by LemonMiaocat** [comment]
> 可以的话 最好加一下Discord频道讨论 里面的Support-other都是国人在讨论

写的很详细，谢谢啦~ヾ(^∀^)ﾉ

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
