### ISSUE TITLE
The server is busy, please try again later (504)

### ISSUE THREAD

**Issue by EIysia** [Melledy/Grasscutter#330]
![QQ图片20220428184047](https://user-images.githubusercontent.com/104319189/165735360-fd327b48-2fb4-48da-a2cc-d35fc33bc65e.png)

**Comment by Scirese** [comment]
This is an issue tracker, not a support forum. Please visit the Discord for further support.
GitHub issue不是技术支持论坛。需要技术支持请去Discord，里面有专门的中文频道。

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
