### ISSUE TITLE
Command "permission" doesn`t work

### ISSUE THREAD

**Issue by SummerOfIce** [Melledy/Grasscutter#332]
After I entered the game ,I tried  to send command to Server but the server prompted me I have no permission to run it.Then I run the ''/permission add 10001 *'' on the CMD console,but it prompted me''No value present".I want to know what the problem is and how to solve it,please.

![X20JVZ5SJ0~JUYZ6X520_Q4](https://user-images.githubusercontent.com/73223207/165752862-46eddc69-8278-4bcf-8ff7-6d3067bf4e1b.jpg)
![TCO8 R_O4X`IAM0K2LGUS7](https://user-images.githubusercontent.com/73223207/165754327-18221140-4492-4a75-9a9e-bac0b27898e4.png)

**Comment by memetrollsXD** [comment]
Is this on stable or dev branch?

**Comment by SummerOfIce** [comment]
> 

stable

**Comment by dondaha** [comment]
I found if you open "AutomaticallyCreateAccounts" in "config.json", it will happen on the automatically created accounts. And the accounts you create in the console are all right.

**Comment by SummerOfIce** [comment]
> I found if you open "AutomaticallyCreateAccounts" in "config.json", it will happen on the automatically created accounts. And the accounts you create in the console are all right.

Thanks,I'll try it later.

**Comment by SummerOfIce** [comment]
I download the development edition,and now everything works well.
