### ISSUE TITLE
Unable to talk to server

### ISSUE THREAD

**Issue by eirv** [Melledy/Grasscutter#339]
Unable to talk to server, for example "help![Screenshot_2022-04-29-05-40-25-434_com.miHoYo.GenshinImpact.jpg](https://user-images.githubusercontent.com/64970244/165851092-28833949-abd3-446d-aece-1beed9db4e8d.jpg)"

**Comment by memetrollsXD** [comment]
This is expected behaviour. Please use `/help` or `!help` to execute commands

**Comment by alt3ri** [comment]
please, read the README.md or Wiki or PDF carefully before asking this type of question

**Comment by eirv** [comment]
> please, read the README.md or Wiki or PDF carefully before asking this type of question

thank you
