### ISSUE TITLE
Unauthorized! How can I give grasscutter.jar an access?

### ISSUE THREAD

**Issue by sange3333333** [Melledy/Grasscutter#343]
![unauthorized](https://user-images.githubusercontent.com/99001530/165883575-78875695-99e1-4268-9397-b67b287bbab8.png)
![unauthorized](https://user-images.githubusercontent.com/99001530/165883577-35cbc31a-0385-43c3-ae49-d5b8c6c67206.png)

**Comment by lilmayofuksu** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG)

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
