### ISSUE TITLE
When put this in a remote server, the login is all right, but after the door-opening animation, the connection timed out

### ISSUE THREAD

**Issue by emp-java** [Melledy/Grasscutter#346]
![2022-04-29 124534](https://user-images.githubusercontent.com/100832559/165894273-fbf92604-691e-4629-b5cc-13dab51335ac.png)

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by bamboo512** [comment]
There are two "PublicIP" in config.json.
Change them both to the IP address of your remote server.

**Comment by emp-java** [comment]
Thank you but I'v tested if the publicIp is still localhost, it errors with code 4206. Finally I find it's the udp port should be opened on the server.

**Comment by Raysamatoken** [comment]
> Thank you but I'v tested if the publicIp is still localhost, it errors with code 4206. Finally I find it's the udp port should be opened on the server.
Hello,I met your problem too. My Server is Win2012R2. How can i open the udp port? My Minecraft Server was work fine.

**Comment by Raysamatoken** [comment]
> Thank you but I'v tested if the publicIp is still localhost, it errors with code 4206. Finally I find it's the udp port should be opened on the server.

Hello,I met your problem too. My Server is Win2012R2. How can i open the udp port? My Minecraft Server was work fine.

**Comment by emp-java** [comment]
> > Thank you but I'v tested if the publicIp is still localhost, it errors with code 4206. Finally I find it's the udp port should be opened on the server.
> 
> Hello,I met your problem too. My Server is Win2012R2. How can i open the udp port? My Minecraft Server was work fine.

我用的是阿里云的服务器，在控制台安全组开端口就行了，其他云服务器的类似，再其他的服务器我就不了解了。具体可以百度试试。

**Comment by DevilProMT** [comment]
> ![2022-04-29 124534](https://user-images.githubusercontent.com/100832559/165894273-fbf92604-691e-4629-b5cc-13dab51335ac.png)
Did you figure it ? i got the same error

**Comment by bamboo512** [comment]
> ![2022-04-29 124534](https://user-images.githubusercontent.com/100832559/165894273-fbf92604-691e-4629-b5cc-13dab51335ac.png)
> Did you figure it ? i got the same error

I fixed it by generating new certificate file (keystone.p12 containing your domain)
A Chinese version tutorial is available [here](https://yhsnlkm.github.io/2019/12/19/%E6%95%B0%E5%AD%97%E7%AD%BE%E5%90%8D/%E4%BD%BF%E7%94%A8XCA%E5%B7%A5%E5%85%B7%E7%94%9F%E6%88%90%E7%AD%BE%E5%90%8D%E8%AF%81%E4%B9%A6-1/)
