### ISSUE TITLE
Meet “ [ERROR] LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information”while playing

### ISSUE THREAD

**Issue by czy20010112** [Melledy/Grasscutter#348]
stable branches; server-sys red hat8.5; java8u202; mongodb4.4 ; client cn client; way of connecting fillder; 
i was playing in the server and suddently the connection failed ,using another account can succeed in login but old one can't.
then restart the server, both can enter the server and nothing went wrong (i guess) ,but the console of server still report the error..here is some of the access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
	io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:600)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 983
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Long2ObjectOpenHashMap.java:1222)

**Comment by alt3ri** [comment]
It's a normal issue, just continue to play

**Comment by czy20010112** [comment]
> It's a normal issue, just continue to play

Errrr OK.... get that ，thanks
