### ISSUE TITLE
My Grasscutter cannot start and will quit automatically

### ISSUE THREAD

**Issue by WhiteEurya** [Melledy/Grasscutter#349]
When I start my Grasscutter , it will half load and quit automatically, just like this:
![image](https://user-images.githubusercontent.com/94689267/165910877-955e3e3f-15f4-4030-91d4-724f61650cff.png)
I don't know what is going on. Hope you guys can help me.

**Comment by alt3ri** [comment]
![image](https://user-images.githubusercontent.com/95161279/165912364-52409c70-9e2f-4678-aaa0-aa6bd48a98cb.png)
can you search among these issues. There're solutions for you

**Comment by WhiteEurya** [comment]
> ![image](https://user-images.githubusercontent.com/95161279/165912364-52409c70-9e2f-4678-aaa0-aa6bd48a98cb.png) can you search among these issues. There're solutions for you

However, the conflict process is MongoDB...

**Comment by 4Benj** [comment]
Then change the port of mongoDB

**Comment by WhiteEurya** [comment]
> Then change the port of mongoDB

OK! I will try it, thank you for you all!

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
