### ISSUE TITLE
Command "giveall" dosen't give all the items.

### ISSUE THREAD

**Issue by Lynricsy** [Melledy/Grasscutter#352]
It seems to give a random set of items.I think it should be improved.

**Comment by CK-Tex** [comment]
Does your inventory says 2000/2000? If it is, some of the items are not successfully given for insufficient inventory storage. For me the issue is different, after using giveall (with my inventory maximum storage changed in config.json) and exit my account, I cannot log back in.

**Comment by CK-Tex** [comment]
> Does your inventory says 2000/2000? If it is, some of the items are not successfully given for insufficient inventory storage. For me the issue is different, after using giveall (with my inventory maximum storage changed in config.json) and exit my account, I cannot log back in.

#341 for reference

**Comment by lhhxxxxx** [comment]
> It seems to give a random set of items.I think it should be improved.

you can change the size of backpack in config though it seems have another bug

**Comment by BaiSugar** [comment]
> 它似乎给出了一组随机的项目。我认为应该改进。

It's not random, it's a range

**Comment by BaiSugar** [comment]
In the latest version, most of the quest items have been removed, if there are items that cannot be displayed, please try to log in the game again (this seems to be a bug)
