### ISSUE TITLE
Something Wrong in My Grasscutters

### ISSUE THREAD

**Issue by ZeroXcAG** [Melledy/Grasscutter#357]
I start my Grasscutter, and is happen ,and the cmd will close late
![QQ截图20220429202827](https://user-images.githubusercontent.com/104631749/165944482-1e73825c-7512-45ee-847f-95b61c5fa92b.png)

**Comment by lilmayofuksu** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by Alan-Raddam** [comment]
It seems that Grasscutter failed to connect to MongoDB. Check if mongodb is correctly running. 

**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**
