### ISSUE TITLE
Exception in monitor thread while connecting to server localhost:27017

### ISSUE THREAD

**Issue by 2054686334** [Melledy/Grasscutter#358]
![image](https://user-images.githubusercontent.com/63030840/165959354-388b110b-7bda-47c3-a6cf-61f6f805b4b0.png)
When I start my Grasscutter , it will half load and quit automatically,
And if MongoDB is running ,it will like this......
![image](https://user-images.githubusercontent.com/63030840/165959814-18959108-f516-4d24-9bab-bd23c54898a9.png)

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
