### ISSUE TITLE
when i gradlew jar happened a error

### ISSUE THREAD

**Issue by weqasds** [Melledy/Grasscutter#359]
![image](https://user-images.githubusercontent.com/103436220/165960245-451e3e4b-7518-4dbf-b364-0be64883b7a1.png)
So am I missing something, and if so, where should I download the missing files

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
