### ISSUE TITLE
BUG: characters receive damage during elemental burst invincibility frames

### ISSUE THREAD

**Issue by 1-lavender-1** [Melledy/Grasscutter#361]
Kazuha is in his elemental burst i-frames, but he still receives damage even  in Zhongli's jade shield
![elemental burst](https://user-images.githubusercontent.com/104431284/165978667-7fca58e6-fa59-4d97-b28b-d909986793bb.png)

**Comment by KingRainbow44** [comment]
this feature hasn't been implemented yet, hence this won't be "fixed"
