### ISSUE TITLE
gi-bin-output is closed by DMCA

### ISSUE THREAD

**Issue by Illustar0** [Melledy/Grasscutter#367]
[gi-bin-output](https://github.com/radioegor146/gi-bin-output) in [wiki-Starting the Server-2-ii](https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server) is closed by DMCA

**Comment by lunaticwhat** [comment]
yes this is a known issue. But since we dont want to mess with copyrights, so there might be an another way to links the _Resources_ stuff or the best way is to let the players find it themselves.

**Comment by hash070** [comment]
haha,米哈游急了（吃瓜

**Comment by Illustar0** [comment]
确实急了，直接发DMCA，不过BinOutput似乎并不难找
————
Really urgent, send DMCA directly, but BinOutput does not seem to be difficult to find

**Comment by memetrollsXD** [comment]
~~[If only there was a discord server where you could ask for help and resources even if it goes against the companies TOS..](https://discord.gg/T5vZU6UyeG)~~

**Comment by Ljzd-PRO** [comment]
> 确实急了，直接发DMCA，不过BinOutput似乎并不难找
> ————
> Really urgent, send DMCA directly, but BinOutput does not seem to be difficult to find

要怎么获取BinOutput呢？

**Comment by KiminaNatsuki** [comment]
> > 确实急了，直接发DMCA，不过BinOutput似乎并不难找
> > ————
> > Really urgent, send DMCA directly, but BinOutput does not seem to be difficult to find
> 
> 要怎么获取BinOutput呢？

https://github.com/Koko-boya/Grasscutter_Resources

**Comment by Ljzd-PRO** [comment]
> > > 确实急了，直接发DMCA，不过BinOutput似乎并不难找
> > > ————
> > > Really urgent, send DMCA directly, but BinOutput does not seem to be difficult to find
> > 
> > 
> > 要怎么获取BinOutput呢？
> 
> https://github.com/Koko-boya/Grasscutter_Resources

谢谢

**Comment by Ryanjiang2009** [comment]
> > > 确实急了，直接发DMCA，不过BinOutput似乎并不难找
> > > ————
> > > Really urgent, send DMCA directly, but BinOutput does not seem to be difficult to find
> > 
> > 
> > 要怎么获取BinOutput呢？
> 
> https://github.com/Koko-boya/Grasscutter_Resources

小心m hy看到这个，最好混淆一下防止被批 量  搜|索

**Comment by Ryanjiang2009** [comment]
https://gitl【删】ab.com/Yuu【删】kiPS/GC【删】-R【删】esour【删】ces
