### ISSUE TITLE
BUG:Fatal damage to the monster can't be seen.

### ISSUE THREAD

**Issue by MihoyoDad** [Melledy/Grasscutter#374]
**Describe the bug**
If your  damage can kill the monster,then the damage number won't appear.
It is terrible for people who loves Big Number. 
I tried to record a video，and watch it at low speed.But still failed.

![image](https://user-images.githubusercontent.com/104514551/166102840-2e301fed-892d-4e88-8566-2fefc37e2ad0.png)

**Comment by alt3ri** [comment]
well I did encountered it long time ago, I thought it was normal

**Comment by MihoyoDad** [comment]
It happens too often compared with official servers, especially for hundreds of thousands of high damage.
I think it's a bug.Maybe some logic compensation is missing

**Comment by alt3ri** [comment]
just ignore it, mobs'll die anyways

**Comment by memetrollsXD** [comment]
I think it has to do because of an if case, that it won't send the dmg packet but just death one

**Comment by ghost** [comment]
Fixed in 50a8db2
