### ISSUE TITLE
After gradlew jar,commands can't run properly.

### ISSUE THREAD

**Issue by CzHUV** [Melledy/Grasscutter#375]
![wrong](https://user-images.githubusercontent.com/100004265/166104421-9a2af870-3996-4977-ab91-255d55c5789a.png)

**Comment by KingRainbow44** [comment]
what branch are you on? and what java version are you using?

**Comment by CzHUV** [comment]
>  and what java version are you using?

![Java ver](https://user-images.githubusercontent.com/100004265/166417021-8a0871e3-9b48-4104-9fee-9ea8f2a4a538.PNG)

> what branch are you on?

I only changed the wrong string in "build.gradle" and then build,didn't change anything else.
Also,I've tried twice (build from source),they all got this ending.
btw,if you straight download the .jar file,you will even stuck at the "java -jar grasscutter.jar".
Did I do anything wrong?If I did,How should I change it?

**Comment by KingRainbow44** [comment]
> you will even stuck at the "java -jar grasscutter.jar"

can you clarify what you mean by this?

**Comment by Ljzd-PRO** [comment]
> if you straight download the .jar file,you will even stuck at the "java -jar grasscutter.jar".

Maybe using [Oracle’s JDK17](https://www.oracle.com/java/technologies/downloads/#java8) will work. And use `java -mx1024m -jar grasscutter.jar` with memory setting.

**Comment by CzHUV** [comment]
@KingRainbow44 
After I changed my java version(Oracle Java 17)and used the command `java -mx1024m -jar grasscutter.jar`,it looks like this:
![err](https://user-images.githubusercontent.com/100004265/166648774-824545bb-58f5-4aab-b0fb-04709ebad07c.PNG)

No error text changes,just like the version that I haven't changed before.

**Comment by CzHUV** [comment]
btw,the same error text (`...TypeAnnotationScanner was not configured`) also outputs when the self-built version didn't setup "build.gradle" file correctly.maybe your pre-built version have the same error?

**Comment by CzHUV** [comment]
Oh,don't mind the error texts(from line 2 to line 4),I didn't copy those key files.
But no matter you change or not,command line will output the same error texts.

**Comment by Gilinfen** [comment]
我也是遇到了这个问题
![image](https://user-images.githubusercontent.com/87110607/166669761-5c2fc757-e757-4af1-bf16-efd3a683007e.png)
这个是我指令格式不对吗，如果我不加最后一个一 是可以正常使用的，但我看指令列表里面是可以在获取武器的时候加上精炼等级，还有就是使用 /giveart 会告诉我是未知指令
![image](https://user-images.githubusercontent.com/87110607/166670013-cfb964c1-585a-4160-adf0-e524d923c07f.png)

**Comment by unknown10777** [comment]
@7foxx giveart未知重新进行gradlew.bat make即可

**Comment by Gilinfen** [comment]
![image](https://user-images.githubusercontent.com/87110607/166670013-cfb964c1-585a-4160-adf0-e524d923c07f.png)


> @7foxx giveart未知重新进行gradlew.bat make即可哎没有用

**Comment by Ljzd-PRO** [comment]
> 我也是遇到了这个问题
> ![image](https://user-images.githubusercontent.com/87110607/166669761-5c2fc757-e757-4af1-bf16-efd3a683007e.png)
> 这个是我指令格式不对吗，如果我不加最后一个一 是可以正常使用的，但我看指令列表里面是可以在获取武器的时候加上精炼等级，还有就是使用 /giveart 会告诉我是未知指令
> ![image](https://user-images.githubusercontent.com/87110607/166670013-cfb964c1-585a-4160-adf0-e524d923c07f.png)

我在终端里都是不加`/`的，只有在游戏里使用才加，会不会是这个原因

**Comment by unknown10777** [comment]
@7foxx 首先你要确保java -version是17.0.3

**Comment by Gilinfen** [comment]
@unknown10777 我的是 17.0.3的，我是在dev分支上跑的
@Ljzd-PRO 我试过没有用，你们都是在那个分支上跑的

**Comment by CzHUV** [comment]
> 我也是遇到了这个问题 ![image](https://user-images.githubusercontent.com/87110607/166669761-5c2fc757-e757-4af1-bf16-efd3a683007e.png) 这个是我指令格式不对吗，如果我不加最后一个一 是可以正常使用的，但我看指令列表里面是可以在获取武器的时候加上精炼等级，还有就是使用 /giveart 会告诉我是未知指令 ![image](https://user-images.githubusercontent.com/87110607/166670013-cfb964c1-585a-4160-adf0-e524d923c07f.png)

不是，你和我的都不是同一个问题，我的问题是服务端连`stop`都不认了

**Comment by Ljzd-PRO** [comment]
> @unknown10777 我的是 17.0.3的，我是在dev分支上跑的
> @Ljzd-PRO 我试过没有用，你们都是在那个分支上跑的

@7foxx 我用的是Ubuntu，也是dev，包括Action里的。之前我倒是遇到过版本问题，不过表现不是这样的，运行`grasscutter.jar`直接报错，提示Java运行时版本太低，网上搜了一下报错里的class file 版本对应的是JDK8，但是使用`java -version`查询得到的结果却是Oracle JDK 17。通过`which java`查询到的位置是`/usr/bin/java`，并不是Oracle JDK的安装目录，所以就卸载掉了所有的openjdk，最后成功运行。

**Comment by 7foxx** [comment]
> @7foxx 我用的是Ubuntu，也是dev，包括Action里的。之前我倒是遇到过版本问题，不过表现不是这样的，运行`grasscutter.jar`直接报错，提示Java运行时版本太低，网上搜了一下报错里的class file 版本对应的是JDK8，但是使用`java -version`查询得到的结果却是Oracle JDK 17。通过`which java`查询到的位置是`/usr/bin/java`，并不是Oracle JDK的安装目录，所以就卸载掉了所有的openjdk，最后成功运行。
@Ljzd-PRO 这个版本太低的问题我也遇到过，刚刚发现是不是我游戏资源文件的问题，我用的是https://github.com/Dimbreath/GenshinData这个仓库的资源，
https://github.com/Koko-boya/Grasscutter_Resources我朋友用这个仓库的资源可以成功，我还没试

**Comment by Gilinfen** [comment]
@7foxx 我用的是Ubuntu，也是dev，包括Action里的。之前我倒是遇到过版本问题，不过表现不是这样的，运行grasscutter.jar直接报错，提示Java运行时版本太低，网上搜了一下报错里的class file 版本对应的是JDK8，但是使用java -version查询得到的结果却是Oracle JDK 17。通过which java查询到的位置是/usr/bin/java，并不是Oracle JDK的安装目录，所以就卸载掉了所有的openjdk，最后成功运行。
@Ljzd-PRO 这个版本太低的问题我也遇到过，刚刚发现是不是我游戏资源文件的问题，我用的是
https://github.com/Dimbreath/GenshinData
这个仓库的游戏资源
https://github.com/Koko-boya/Grasscutter_Resources
我朋友用这个仓库的资源可以使用指令设置 在获取武器的时候可以设置突破等级，但使用圣遗物指令获取词条不行
