### ISSUE TITLE
伤害存在上限，超高面板的雷神开大只有197530.78伤害

### ISSUE THREAD

**Issue by AgainstSky** [Melledy/Grasscutter#376]
雷神面板拉的很高了，在九条万叶班尼特组队下开大依然只有197530.78伤害

**Comment by weqasds** [comment]
> 雷神面板拉的很高了，在九条万叶班尼特组队下开大依然只有197530.78伤害

我也是，

**Comment by XZB-1248** [comment]
You should use English here to make everyone understand what are you talking about.
别用中文。免得有相似问题的老外提出类似的issue。
不会英语就去找谷歌。

**Comment by XZB-1248** [comment]
You should use English here to make everyone understand what you're talking about.
别用中文。免得有相似问题的老外提出类似的issue。
不会英语就去找谷歌。

**Comment by StillMi** [comment]
Please close it yourself and try again in English

**Comment by Zxis233** [comment]
JUST TRANSLATE IT IN ENGLISH PLZ

**Comment by alt3ri** [comment]
CLOSE THIS PLEASE

**Comment by qwert46369** [comment]
？

**Comment by SleepyAsh0191** [comment]
Translate:伤害存在上限，超高面板的雷神开大只有197530.78伤害

**Comment by SleepyAsh0191** [comment]
Translate：
The damage have limit, I used Raiden Shogun which have high pratice, it can only make 197530 damage when press Q.
Party are Kujou sara, Bannett and Kazuha.

Sry for my poor grammar.

but you can just ask it in Discord server and enter the support-zh channel, they use Chinese to discuss（这边提平常性问题没太大用，进discord的support-zh频道去提问，那里的人都是用中文讨论的）
