### ISSUE TITLE
GenshinData Version already expired.

### ISSUE THREAD

**Issue by fenginsc** [Melledy/Grasscutter#377]
https://github.com/Dimbreath/GenshinData
The version provided is **OSRELWin2.6.0_R6305792_S6240328_D6303587**
The latest version is **OSRELWin2.6.0_R6708157_S6988297_D6731353**
If you can't keep these files up to date, please tell me how to find them, how to get them.
thanks.

**Comment by alt3ri** [comment]
still usable

**Comment by fenginsc** [comment]
> still usable

But I can't enter the game, every time I enter it prompts that an update is required.

error code: 4206

**Comment by F-Unction** [comment]
it was your problem, we can enter the game without error

**Comment by fenginsc** [comment]
> it was your problem, we can enter the game without error

I can log in normally, but I need to update the game after logging in. At this time, an error will appear. I have updated the game on the official server.

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

also the update message isn't a result of the data you use, but the login response & query region rsp
additionally 4206 isn't the update msg code (i think)
