### ISSUE TITLE
There is an upper limit of damage. The Thor of the ultra-high panel has only 197530.78 damage

### ISSUE THREAD

**Issue by AgainstSky** [Melledy/Grasscutter#379]
There is an upper limit of damage. The Thor of the ultra-high panel has only 197530.78 damage

**Comment by alt3ri** [comment]
在不和谐中转到#support-zh 频道

**Comment by lhhxxxxx** [comment]
Use machine translation against machine flip ()

Translate:
Thor=The God of Thunder=雷神=雷電将軍=らいでんしょうぐん=Raiden Shougun
panel=面板=where the stats shows=stats
不和谐=discord
machine flip=机翻=机器翻译=machine translation

**Comment by Scirese** [comment]
> There is an upper limit of damage. The Thor of the ultra-high panel has only 197530.78 damage

米哈游设置了9999999伤害上限，不改客户端没法突破。
————————————————————
Mihoyo has set a damage limit of 9999999, which is impossible to break without modifying the game cilent.

**Comment by AgainstSky** [comment]
> 

但是这个19万伤害和9999999的距离还很大

**Comment by Scirese** [comment]
> > 
> 
> 但是这个19万伤害和9999999的距离还很大

Github issue 不是支持论坛，不要往这里发这种问题，请去[discord](https://discord.gg/T5vZU6UyeG)
——————————————————————————
Github issue is not a support forum.Don't post the question here,please head to discord

**Comment by Scirese** [comment]
请自己把issue关掉./please close the issue by yourself.
