### ISSUE TITLE
client login error 系统错误，请稍后再试

### ISSUE THREAD

**Issue by Ljzd-PRO** [Melledy/Grasscutter#380]
The logs of redirect server were correct, Grasscutter server did not output any log after it started successfully.

![IMG_1202](https://user-images.githubusercontent.com/63289359/166113457-5091033a-d58a-4b67-bd21-9f94d806b5b2.PNG)![IMG_1200](https://user-images.githubusercontent.com/63289359/166113463-ecdb045e-6a5e-4e46-ba84-41648766dab4.PNG)![IMG_1201](https://user-images.githubusercontent.com/63289359/166113472-09341371-e9ef-4953-9a03-ae1d71f139c1.PNG)

**Comment by Ljzd-PRO** [comment]
reopen the app.

**Comment by zty012** [comment]
> reopen the app.

@Ljzd-PRO which app? launcher or grasscutter?

**Comment by Ljzd-PRO** [comment]
> > reopen the app.
> 
> @Ljzd-PRO which app? launcher or grasscutter?

reopen the game

**Comment by zibange** [comment]
我也遇到这个错误了，是因为我挂着梯子(open vpn)导致的。关闭梯子(close vpn)就解决了
genshin  version 3.7   
// Cultivation  version 1.1.1
//Grasscutter version: 1.6.3
You can refer to it
