### ISSUE TITLE
IOS client crash 

### ISSUE THREAD

**Issue by mahaoqqsx** [Melledy/Grasscutter#391]
IOS client crash 
Build #383  starts

**Comment by 4Benj** [comment]
Please set `DebugMode` to "ALL" in the config and send the last request received by the server before the crash here.

**Comment by fanshu-520** [comment]
----------------------------------------------------------------------------------
[13:45:53] [[34mINFO[0;39m] [Dispatch] Client 127.0.0.1 is trying to log in
[13:45:53] [[34mINFO[0;39m] [Dispatch] Client 127.0.0.1 logged in as 10001
[13:45:53] [[34mINFO[0;39m] JAVALIN REQUEST DEBUG LOG:
Request: POST [/hk4e_global/mdk/shield/api/login]
    Matching endpoint-handlers: [BEFORE=*, POST=/hk4e_global/mdk/shield/api/login]
    Headers: {x-rpc-channel_version=1.29.0, Accept=*/*, x-rpc-device_id=7F46509A-B8EA-4F95-BA06-891533E7CA0D, x-rpc-mdk_version=1.29.0, User-Agent=Genshin%20Impact/364 CFNetwork/1331.0.7 Darwin/21.4.0, Connection=keep-alive, x-rpc-risky=id=none;c=;s=;v=, Host=127.0.0.1, Accept-Encoding=gzip, deflate, br, x-rpc-game_biz=hk4e_global, x-rpc-channel_id=1, x-rpc-device_fp=9226649357, x-rpc-sys_version=15.4, x-rpc-device_name=Genshin+Impact, Accept-Language=zh-CN,zh-Hans;q=0.9, x-rpc-language=zh-cn, Content-Length=244, x-rpc-client_type=1, x-rpc-device_model=iPhone13,2, Content-Type=application/json}
    Cookies: {}
    Body: {
  "account" : "genshinmeme",
  "is_crypto" : true,
  "password" : "oeNAiMnp64pq1r0OIYA9zBXDANPLJefpxyBzb96w2jMrFqJeycu1kpAXc59VyOSI6IVhheje7yT0zFljeP0h15Dp7rwzr5qEeRwH09VH7pXs20OVEpt01nmdcrGVoJiZpk4uj0H+he763MBBCT9Vopw0RDJM70wylcwaahE6hck="
}
    QueryString: null
    QueryParams: {}
    FormParams: {{
  "account" : "genshinmeme",
  "is_crypto" : true,
  "password" : "oeNAiMnp64pq1r0OIYA9zBXDANPLJefpxyBzb96w2jMrFqJeycu1kpAXc59VyOSI6IVhheje7yT0zFljeP0h15Dp7rwzr5qEeRwH09VH7pXs20OVEpt01nmdcrGVoJiZpk4uj0H he763MBBCT9Vopw0RDJM70wylcwaahE6hck=["
}]}
Response: [200], execution took 202.58 ms
    Headers: {Server=Javalin, Date=Sun, 01 May 2022 05:45:53 GMT, Content-Type=text/plain}
    Body is 561 bytes (starts on next line):
    {"message":"OK","retcode":0,"data":{"account":{"uid":"10001","name":"","email":null,"mobile":"","is_email_verify":"0","realname":"","identity_card":"","token":"7b2d8b4be10289493ed2aba5903c6a3b479dfe04e0b0289adee979dffbe8eb7c","safe_mobile":"","facebook_name":"","twitter_name":"","game_center_name":"","google_name":"","apple_name":"","sony_name":"","tap_name":"","country":"US","reactivate_ticket":"","area_code":"**","device_grant_ticket":""},"device_grant_required":false,"realname_operation":"NONE","realperson_required":false,"safe_mobile_required":false}}
----------------------------------------------------------------------------------

**Comment by 4Benj** [comment]
#392 and #394 is attempting to fix this.
#392 has already been pushed and should fix the issue with the /verify route. However, there are still issues

**Comment by 4Benj** [comment]
#394 has now been pushed and iOS devices should work like they did before.

**Comment by wuwuwu223** [comment]
hello ,how to set proxy in playcover?
