### ISSUE TITLE
Command /clear will throw an error

### ISSUE THREAD

**Issue by mikuyourworld** [Melledy/Grasscutter#397]
Version: lastest dev
Issue: /clear <art|wp|mat|all> will thorw an error
This command will remove half amount of items in your inventory...not all the items which should be removed and throw this error

`java.lang.ArrayIndexOutOfBoundsException: Index 800 out of bounds for length 513`

**Comment by KingRainbow44** [comment]
can you send the full stack trace?

**Comment by mikuyourworld** [comment]
![QQ图片20220503024841](https://user-images.githubusercontent.com/30253025/166298791-d01621fe-bb13-487e-94f3-24de25f1cd6e.png)
![QQ图片20220503024845](https://user-images.githubusercontent.com/30253025/166298797-50288da7-05e5-414f-941a-74415f29e818.jpg)
