### ISSUE TITLE
The client failed to connect to the server

### ISSUE THREAD

**Issue by Pigeon2333** [Melledy/Grasscutter#399]
When I use GrassClipper to connect to my private server (running on a remote server), the client tells me that the network is busy (502) and the GrassCutter console has the following error 
![N_~4{A7B)Z0 J5$X}`6)KBU](https://user-images.githubusercontent.com/68182691/166136093-4d6f4484-8cf4-4382-8337-1c8addc6af0f.png)

**Comment by 4Benj** [comment]
This is the issue tracker for Grasscutter, not GrassClipper. Please report issue you have with GrassClipper on the [appropriate issue tracker](https://github.com/Grasscutters/GrassClipper/issues).
Additionally, in the grassclipper README, there is a troubleshooting section with your [issue listed](https://github.com/Grasscutters/GrassClipper#error-502)
