### ISSUE TITLE
the command typed into terminal will be covered by the logs

### ISSUE THREAD

**Issue by Ljzd-PRO** [Melledy/Grasscutter#403]
Can it be like Minecraft server terminal or MongoDB, MySQL terminal?

**Comment by alt3ri** [comment]
can you provide the screenshot?

**Comment by Ljzd-PRO** [comment]
it's hard to take screenshot, it would be like this:
```
[17:30:26] [INFO] RECV: UnionCmdNotify (55)
0a3b08db0212360a34080710021a2e088380800812
[17:30:27] [INFO] SEND: WorldPlayerRTTNotify (26)
0a0508914e100a
acco
[17:30:27] [INFO] RECV: UnionCmdNotify (55)
0a3b08db0212360a340807100
unt 
[17:30:29] [INFO] RECV: UnionCmdNotify (55)
0a3b08db0212360a34080710021a2e0883808008121e0a0f0d30303cc515383a55431dedc686c512051544f381421a002002320018db87022084202801
ad
[17:30:29] [INFO] RECV: PingReq (37)
10b5a6b993062513269142
d 
[17:30:29] [INFO] SEND: PingRsp (93)
18b5a6b99306
[17:30:30] [INFO] SEND: WorldPlayerRTTNotify (26)
0a0508914e100a
play
[17:30:30] [INFO] SEND: WorldPlayerRTTNotify (26)
0a0508914e100a
er 10001
```
The command `account add player 10001` was split by the logs.

**Comment by alt3ri** [comment]
turn off log packet in config.json
![image](https://user-images.githubusercontent.com/95161279/166142838-c2b388b8-e185-42f2-949b-237fd6da421d.png)

**Comment by Ljzd-PRO** [comment]
> turn off log packet in config.json
> ![image](https://user-images.githubusercontent.com/95161279/166142838-c2b388b8-e185-42f2-949b-237fd6da421d.png)

There will be fewer log, but it still not like the console such as Minecraft Server or MySQL console, key like"⬆️""⬇️" can't be use.
