### ISSUE TITLE
ios cant choose main avator

### ISSUE THREAD

**Issue by wuwuwu223** [Melledy/Grasscutter#414]
after I look the gc , it refreshed and reload the gc again.
![9B643B6B-25F2-4C5A-9AB7-7EE121B01E12](https://user-images.githubusercontent.com/81224214/166160225-766f3a75-70c2-41f5-9eb8-e5351f142bb4.jpeg)

**Comment by memetrollsXD** [comment]
Common issue, happens because on restart, the server doesn’t recognise client until it reconnects
