### ISSUE TITLE
BUG: Characters' talent doesn't work

### ISSUE THREAD

**Issue by 1-lavender-1** [Melledy/Grasscutter#419]
Raiden's talent "Enlightened One" should grants her electro DMG bonus, but it doesn't work
![d0bea8d6b97d2afce835af70794785b](https://user-images.githubusercontent.com/104431284/166187489-288e4db7-8b76-4b1a-9a2e-f31a5165d1f9.png)
![6b7e4371ab4a3534f5f66aa8c22ec39](https://user-images.githubusercontent.com/104431284/166187614-c1b0f126-28ce-47e2-99a8-041d6664270a.png)

**Comment by IroriRoean** [comment]
its not implemented yet, you would find that many other characters don't work either like tartaglia's passive to raise each attack talent by 1
