### ISSUE TITLE
Friend request cannot be agreed or rejected

### ISSUE THREAD

**Issue by yukiryo** [Melledy/Grasscutter#420]
Latest dev
![61BB96E7-B0CA-4425-9D72-0893815DDF0A](https://user-images.githubusercontent.com/58250223/166188488-3689c51a-1cd7-47ac-8d6e-a92deb2af235.png)

**Comment by ghost** [comment]
It seems to work for me on PC, are there any error messages in the server console when you try to accept/decline a friend request?

**Comment by yuexuanblog** [comment]
I have the same problem Friend application cannot be passed or rejected

**Comment by yuexuanblog** [comment]
I have the same problem. Friend application cannot be passed or rejected

**Comment by omg-xtao** [comment]
Only your friend can agree or reject your request, which is a display issue due to a commit. Sending requests to other friends with the latest version of dev will not have this display problem.

**Comment by yuexuanblog** [comment]
Now I use the development branch, but I still can't agree or reject the friend request when I used the stable branch

**Comment by trueworldfacts** [comment]
420
