### ISSUE TITLE
Unable to load the Gacha Manager Watch Service

### ISSUE THREAD

**Issue by Ljzd-PRO** [Melledy/Grasscutter#424]
```
[ERROR] Unable to load the Gacha Manager Watch Service. If ServerOptions.watchGacha is true it will not auto-reload
java.io.IOException: User limit of inotify instances reached or too many open files
        at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:62)
        at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)
        at emu.grasscutter.game.gacha.GachaManager.startWatcher(GachaManager.java:292)
        at emu.grasscutter.game.gacha.GachaManager.<init>(GachaManager.java:56)
        at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:59)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:85)
```
branch development.

**Comment by 4Benj** [comment]
> User limit of inotify instances reached or too many open files

What operating system are you running?

**Comment by Ljzd-PRO** [comment]
> > User limit of inotify instances reached or too many open files
> 
> What operating system are you running?

Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-40-generic x86_64)

**Comment by 4Benj** [comment]
I literally just figured it out as you posted that, it says `LinuxWatchService` right there lol.
Alright, upon (brief) research, this is commonly a Linux configuration issue but also sometimes occurs on MacOS, but I don't think it's an issue with Grasscutter itself. 

I'm not going to offer any support around this issue as I don't want to potentially fuck up your install as this seems to a kernel security feature and I don't have a linux machine I can test this on. However, I will point you to some resources which will hopefully allow you solve it yourself or provide grounds for further research into this matter.
https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached
https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total (Includes a MacOS solution)

**Comment by Ljzd-PRO** [comment]
Thanks

**Comment by 4Benj** [comment]
If you do end up resolving your issue please leave a comment with the solution on this issue in case someone else encounters it in the future.

**Comment by Ljzd-PRO** [comment]
> I literally just figured it out as you posted that, it says `LinuxWatchService` right there lol. Alright, upon (brief) research, this is commonly a Linux configuration issue but also sometimes occurs on MacOS, but I don't think it's an issue with Grasscutter itself.
> 
> I'm not going to offer any support around this issue as I don't want to potentially fuck up your install as this seems to a kernel security feature and I don't have a linux machine I can test this on. However, I will point you to some resources which will hopefully allow you solve it yourself or provide grounds for further research into this matter. https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total (Includes a MacOS solution)

https://stackoverflow.com/questions/32281277/too-many-open-files-failed-to-initialize-inotify-the-user-limit-on-the-total
This solution works.
