### ISSUE TITLE
add defaultPermissions

### ISSUE THREAD

**Issue by easy-do** [Melledy/Grasscutter#429]
emu.grasscutter.database.DatabaseHelper
46line 
		//TODO add defaultPermissions
		String[] permissions = Grasscutter.getConfig().getDispatchOptions().defaultPermissions;
		for (int i = 0; i < permissions.length; i++) {
			account.addPermission(permissions[i]);
		}

**Comment by 4Benj** [comment]
Why was an issue created for a TODO comment?

**Comment by easy-do** [comment]
> 为什么要为 TODO 评论创建问题？
I don't use GitHub very much. I'm trying to pull request

**Comment by 4Benj** [comment]
In order to make a pull request, fork the repository, push your changes to it, then click the `contribute` button on **your** github repository and `Open Pull Request`. You then can fill out the title and description similar to opening an issue.

**Comment by easy-do** [comment]
> In order to make a pull request, fork the repository, push your changes to it, then click the `contribute` button on **your** github repository and `Open Pull Request`. You then can fill out the title and description similar to opening an issue.
Thank you. I'm following the tutorial

**Comment by easy-do** [comment]
> In order to make a pull request, fork the repository, push your changes to it, then click the `contribute` button on **your** github repository and `Open Pull Request`. You then can fill out the title and description similar to opening an issue.

Thank you. I'm following the tutorial

**Comment by mahaoqqsx** [comment]
Invalid setting permissions 1-9
