### ISSUE TITLE
Have `account delete` remove ALL of an account's data

### ISSUE THREAD

**Issue by KudouShinnyan** [Melledy/Grasscutter#435]
My account can't play normally. I want to play the same account and uid. After I delete the account and recreate it, it's still the same. Is there any way to clear the data of that account?

**Comment by memetrollsXD** [comment]
The accounts/ collection is very different from the players/ collection in MongoDB.. Try deleting the players/ one for a full reset and delete all documents in items/

**Comment by KudouShinnyan** [comment]
> The accounts/ collection is very different from the players/ collection in MongoDB.. Try deleting the players/ one for a full reset and delete all documents in items/

![image](https://user-images.githubusercontent.com/68854981/166226362-f4e7b1b1-5dae-4545-9524-4119c3fddd3d.png)
What command should I use

**Comment by KudouShinnyan** [comment]
@KingRainbow44 Which version of grasscutter can delete the data while deleting the account? I tried to download the latest version in actions, but it couldn't delete the data. After the account was deleted, I tried to create the same account and uid, the status of the account was the same as before

**Comment by KudouShinnyan** [comment]
> The accounts/ collection is very different from the players/ collection in MongoDB.. Try deleting the players/ one for a full reset and delete all documents in items/

According to you, should the account data be stored in mongodb? If yes, I think it should be the data folder of mongodb. If I empty the data folder directly, I'm afraid of deleting the files related to the program by mistake. I uninstall mongodb and clear all the files related to mongodb, and then reinstall mongodb. The data of the account has been cleared successfully

**Comment by zenithyoqi** [comment]
you can delete the account data in mongodb but you should connet first.

**Comment by zenithyoqi** [comment]
you need open the mongodbcompass and connet .Then go to the datebases finaly the accounts data in the grasscutter file

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道

I've kept the issue open because it is a suggestion
