### ISSUE TITLE
Place a copy of 'GenshinData' in the resources folder.

### ISSUE THREAD

**Issue by TimRen6** [Melledy/Grasscutter#447]
![image](https://user-images.githubusercontent.com/86187096/166255415-70028a8d-6a49-4d2a-a12f-c10578d7c0bb.png)

**Comment by Mashiro2000** [comment]
emm，文件放错位置了

**Comment by Mashiro2000** [comment]
这边是[中文文档](https://github.com/Grasscutters/Grasscutter/blob/development/README_zh-CN.md)

**Comment by Mashiro2000** [comment]
keys和data我记得是放在工作目录而不是resources文件夹里面

**Comment by TimRen6** [comment]
我可他看一下你的目录吗
