### ISSUE TITLE
The 'sendmail' command can‘t send mail to offline players

### ISSUE THREAD

**Issue by JimWails** [Melledy/Grasscutter#449]
In the lastest development branch, 'sendmail' command can’t send any mail to offline players, including ’sendmail all‘command.
Two days ago，the dev branch can still send mail to offline players.
Is this a bug?

**Comment by KingRainbow44** [comment]
![image](https://user-images.githubusercontent.com/27646710/166390117-c05df998-5b3c-4c13-9acc-4d32aa4c93f5.png)
magix moment
