### ISSUE TITLE
[Latest dev + stable] Issue with lighting in Enkanomiya and Thee Realms Gateway Offering map

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#450]
![image](https://user-images.githubusercontent.com/104761702/166322449-b5d6b2ff-3636-44d3-a9a5-d1b154b26695.png)
Only happens for a certain region around Dainichi Mikoshi.

Edit: After testing around a little, it seems to have something to do with the weather. When I change weather to 1, everything looks normal:
![image](https://user-images.githubusercontent.com/104761702/166323957-3deff419-b4bd-4a4e-816d-306ac732bbcb.png)
The bug shown in the first screenshot only occurs at weather 0, after waiting for 10-15 seconds. Anything else doesn't seem to cause major issues.

**Comment by xmplay** [comment]
pretty sure enkanomiya lightning is handled by weather so that's why it happens, just set the weather to the default enka one

**Comment by AZthemute** [comment]
> pretty sure enkanomiya lightning is handled by weather so that's why it happens, just set the weather to the default enka one
Ah, okay. Then the best thing to do is to have the server, by default, set enka's weather to its default.

**Comment by KingRainbow44** [comment]
prob shoulda read the comments before labeling as a bug
