### ISSUE TITLE
Client resource update error when I build with vps server

### ISSUE THREAD

**Issue by afeer123** [Melledy/Grasscutter#451]
![image](https://user-images.githubusercontent.com/86306447/166326622-603c3c6f-9ebd-4efc-9065-d217141b9ba4.png)

**Comment by afeer123** [comment]
But if I build locally it works perfectly

**Comment by Becods** [comment]
![g](https://s3.bmp.ovh/imgs/2022/05/03/0e46e82e9b6a7e9d.png)

**Comment by KingRainbow44** [comment]
build or run? if you're talking about running, check your config. if you are building then this would be a bug.

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/166401487-a6c42b2b-9a55-49eb-9095-bd6bd45c76ac.png)

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/166402824-2714383f-b596-46fc-8c73-beb9d30a4571.png)

**Comment by afeer123** [comment]
![image](https://user-images.githubusercontent.com/86306447/166403010-70cc08db-08d6-40c7-893b-30f7e27a7fe8.png)

**Comment by afeer123** [comment]
window sever 2012 r2

**Comment by afeer123** [comment]
When I build it locally it can download resources into the server

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
