### ISSUE TITLE
可以看一下你们的目录吗？我的一直在显示 Place a copy of 'GenshinData' in the resources folder.

### ISSUE THREAD

**Issue by TimRen6** [Melledy/Grasscutter#456]
![image](https://user-images.githubusercontent.com/86187096/166407031-2de613c1-3c5d-400a-8a67-1b87e984df33.png)
![image](https://user-images.githubusercontent.com/86187096/166407042-cd4b8624-e1aa-4b59-84d4-77eb0f2e611c.png)
![image](https://user-images.githubusercontent.com/86187096/166407062-e223eeb2-85cc-41ef-8e94-ad31f4b6a9a4.png)

**Comment by hit2004** [comment]
核心不对

**Comment by TimRen6** [comment]
> 核心不对
什么意思？

**Comment by miseryCN** [comment]
https://github.com/Grasscutters/Grasscutter/wiki/Running#prerequisites
按照要求来

**Comment by ghost** [comment]
Pls try to execute the `java -jar .\grasscutter.jar` command in the folder `C:\Users\Administrator\Desktop\Grasscutter\` , but not `C:\Users\Administrator` .

**Comment by SunsetMkt** [comment]
工作目录可能不对，先`cd`到Grasscutter文件夹再执行

**Comment by DazeCake** [comment]
这种问题建议去discord问而不是在这里开issue，issue不应该作为support，建议自行close，传送门: https://discord.gg/T5vZU6UyeG

**Comment by Ljzd-PRO** [comment]
工作目录不正确，在哪执行jar程序就会认为哪里是当前目录，除非专门设置工作目录的环境变量，像systemctl service那样。
