### ISSUE TITLE
Healing!Healing!bug...fix,pls

### ISSUE THREAD

**Issue by hit2004** [Melledy/Grasscutter#458]
such a huge Bug, can not stand.

**Comment by Scirese** [comment]
Dont post garbage here,PLEASE

**Comment by hit2004** [comment]
> 

which garbage you mention, look at the heal fuction of all avatars,  is it work properly?

**Comment by hit2004** [comment]
> Dont post garbage here,PLEASE

which garbage you mention, look at the heal fuction of all avatars, is it work properly?

**Comment by hit2004** [comment]
> Dont post garbage here,PLEASE

which garbage you mention, look at the heal fuction of all avatars, does it work properly?

**Comment by thaykhangne** [comment]
> > Dont post garbage here,PLEASE
> 
> which garbage you mention, look at the heal fuction of all avatars, does it work properly?

are you expecting all these people who work FOR FREE to do something to satisfy your request? if you want something fixed, either fix it yourself, contribute something or wait for others to fix it AT THEIR WILL. you ain;'t paying shit yet you have the audacity to ask in such tone. fck off.

**Comment by miseryCN** [comment]
不要催，有能力自己去提pr，没能力等着就行。这种问题开发组不会想不到

**Comment by hit2004** [comment]
> > > Dont post garbage here,PLEASE
> > 
> > 
> > which garbage you mention, look at the heal fuction of all avatars, does it work properly?
> 
> are you expecting all these people who work FOR FREE to do something to satisfy your request? if you want something fixed, either fix it yourself, contribute something or wait for others to fix it AT THEIR WILL. you ain;'t paying shit yet you have the audacity to ask in such tone. fck off.

mind you words, it works with your brain. dummy

**Comment by hit2004** [comment]
> > > Dont post garbage here,PLEASE
> > 
> > 
> > which garbage you mention, look at the heal fuction of all avatars, does it work properly?
> 
> are you expecting all these people who work FOR FREE to do something to satisfy your request? if you want something fixed, either fix it yourself, contribute something or wait for others to fix it AT THEIR WILL. you ain;'t paying shit yet you have the audacity to ask in such tone. fck off.

mind you words, it works with your brain. dummy

**Comment by alt3ri** [comment]
> such a huge Bug, can not stand.

If you can't stand, then sit down and be humble.

**Comment by hit2004** [comment]
> 不要催，有能力自己去提pr，没能力等着就行。这种问题开发组不会想不到

你是哪根葱，支那来的？发表一下意见还要跟你汇报，这么牛去米哈游拿钱好咧

**Comment by hit2004** [comment]
> > such a huge Bug, can not stand.
> 
> If you can't stand, then sit down and be humble.

dont agree with u. you should be more aggressive about it. dont turn down the expectation of supporters. if you dont care. just let alone.then no one care about you and your teammates.

**Comment by alt3ri** [comment]
Who's gonna support a selfish guy like you? Btw this is code issues section, not your problem issues section.

**Comment by xmplay** [comment]
just make it yourself dumbass

**Comment by memetrollsXD** [comment]
Feature is to be implemented

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
