### ISSUE TITLE
Can I take a look at your file folder? mine keeps showing ‘Place a copy of 'GenshinData' in the resources folder.’

### ISSUE THREAD

**Issue by TimRen6** [Melledy/Grasscutter#459]
![image](https://user-images.githubusercontent.com/86187096/166409491-555450fc-8446-4aa2-8b43-5e050b22cae8.png)
![image](https://user-images.githubusercontent.com/86187096/166409501-cfa2897a-09e8-425d-9137-46e954f33dd5.png)
https://user-images.githubusercontent.com/86187096/166407062-e223eeb2-85cc-41ef-8e94-ad31f4b6a9a4.png

**Comment by AZthemute** [comment]
Read step 6 of this guide:
https://alt3ri.me/other/grasscutter_guide.pdf
You should've taken Textmap, Subtitle, Readable ans ExcelBinOutput from the Genshindata zip file ONLY.
Then, in the gi-bin-output zip file, find _BinOutput inside the 2.5.52 folder and paste THAT into the resources folder. Then rename the folder to remove the underscrore at the start.
![image](https://user-images.githubusercontent.com/104761702/166411822-3881b181-ab6f-4174-8757-f27251a5b7bc.png)
Here's my resources folder for reference.

**Comment by TimRen6** [comment]
Thanks!!!!! I'll try it
