### ISSUE TITLE
Change the license from Apache -> GPL

### ISSUE THREAD

**Issue by f389722475** [Melledy/Grasscutter#460]
recently,the grasscutter were found to be used for illegal profits on a large scale,For example, Taobao, Tencent QQ.etc.I hope the development team to see this message,do a discord channel verification or simple encryption to prevent it.

**Comment by Scirese** [comment]
maybe also use GPL lisence instead of apache

**Comment by KingRainbow44** [comment]
currently, a license change is planned

**Comment by Birdulon** [comment]
bcd8d39
