### ISSUE TITLE
Help！Wrong：4206 can not connect to the local server

### ISSUE THREAD

**Issue by DeliciousBuding** [Melledy/Grasscutter#462]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/101502465/166411516-6340b081-6d14-4136-9409-66db3af7584d.png">

**Comment by DeliciousBuding** [comment]
<img width="224" alt="image" src="https://user-images.githubusercontent.com/101502465/166411744-dcae65ba-4ec7-494a-aff4-e679d8a5f9f6.png">

**Comment by AZthemute** [comment]
Re-download the keys folder and keystore.p12 file. Also tell us if this is stable or dev branch because they have different keys (at least with my experience).

**Comment by mikualpha** [comment]
> Re-download the keys folder and keystore.p12 file. Also tell us if this is stable or dev branch because they have different keys (at least with my experience).

Same problem on **dev** branch.
In addition, find a 404 error in mitmproxy, these maybe can help someone(or it's unrelated)...
```
127.0.0.1:9197: POST https://127.0.0.1:443/hk4e_cn/combo/granter/api/compareProtocolVersion?
             << 404 Not Found 85b
127.0.0.1:9189: GET https://127.0.0.1:443/admin/mi18n/plat_oversea/m2020030410/m2020030410-version.json
             << 404 Not Found 85b
127.0.0.1:9186: GET https://127.0.0.1:443/admin/mi18n/plat_oversea/m2020030410/m2020030410-version.json
             << 404 Not Found 85b
```

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
