### ISSUE TITLE
I have a port conflict problem

### ISSUE THREAD

**Issue by PlutoCRown** [Melledy/Grasscutter#465]
When I start mongoDB, the grass cutter will show Address already in use :bind .
![image](https://user-images.githubusercontent.com/80192484/166420282-77fcd777-7183-442d-bf99-effe866f8198.png)
Of course, closing MongoDB will show that there is no link to MongoDB.
I tried to change the port of MongoDB and configure the config.json of grasscutter, but still did not solve the problem, still the same error as in the picture。

**Comment by miseryCN** [comment]
there is 2 side in config.json for Mongodb, change all ?

**Comment by PlutoCRown** [comment]
>

**Comment by gtf016** [comment]
I have the same problem.

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道

**Comment by PlutoCRown** [comment]
yes,dataBaseURL and DispatchServerDataBaseURL




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月3日(星期二) 下午4:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter] I have a port conflict problem (Issue #465)





 
there is 2 side in config.json for Mongodb, change all ?
