### ISSUE TITLE
Here is a problem related to the instruction / spawn

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#468]
When generating entities, the command should have been spawn < entityid|entityname > [level] [amount], but when I use it, I find that the level and amount are misplaced
In other words, it actually becomes spawn < entityid|entityname > [amount] [level]
For example, when I use / spawn 20040101 90 1, I actually generate 90 level 1 monsters
Only when / spawn 20040101 1 90 is used can a level 90 monster be generated correctly

**Comment by dogdie233** [comment]
Fix in #439.
I forgot update README XD.
