### ISSUE TITLE
Player won't leave domain scene if the player closes the client directly

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#470]
### **Problem description**
Player will not change into the default scene (main world) if the player close the client while playing in the domain scene. When the player reconnects to the server, the character will keep staying in the domain scene.
### **Runtime environment**
Server OS: Windows 11 Build 22598.ni_release
Server IP: 127.0.0.1 (Srv & Client both on a same device.)
Client Ver: OSRELWin2.6.0_R6708157_S6731353_D6731353
Proxy: mitmproxy
Grasscutter JAR File Ver: 1.0.3-dev | Last pull & build at 17:50 on 2022/5/3

**Comment by KiminaNatsuki** [comment]
It's like that in original certain anime game too, so I don't see this as a bug..?

**Comment by ghost** [comment]
> It's like that in original certain anime game too, so I don't see this as a bug..?

Oh, sorry. I probably forgot to test this problem on the official server before raising the issue. I will close this issue.
