### ISSUE TITLE
what's wrong with this?

### ISSUE THREAD

**Issue by xiaomoL444** [Melledy/Grasscutter#475]
This problem has been bothering me for a while
I first installed JDK17 according to the instructions and compiled it smoothly
but when i installed JDK-8u202 this appeared
![image](https://user-images.githubusercontent.com/69074564/166455069-5201f59f-dee7-4e47-98c5-654787af1f6c.png)
When I uninstalled JDK-8u202 and installed jdk-18.0.1.1, I still got an error
![image](https://user-images.githubusercontent.com/69074564/166455992-b369fe15-2a11-4400-b732-ac292eebb9a2.png)
help me
i'am using google translate

**Comment by Julienraptor01** [comment]
The problem is that you don't have mongoDB
