### ISSUE TITLE
 No SSL cert found! Falling back to HTTP server. Address already in use: bind

### ISSUE THREAD

**Issue by TimRen6** [Melledy/Grasscutter#477]
What's wrong?
How to deal with it? 
![image](https://user-images.githubusercontent.com/86187096/166463045-b1595d9a-7e19-4991-a10d-d34cf6156812.png)

**Comment by dillfrescott** [comment]
How did you fix this?

**Comment by Id-ware** [comment]
i changed the empty field next to `KeystorePassword` to 123456 (it's inside config.json) and saved it
