### ISSUE TITLE
About activity and battle passes

### ISSUE THREAD

**Issue by Kazuha2022** [Melledy/Grasscutter#484]
I hope to add the activity button and battle pass button, which will make the main interface look more realistic (just add two buttons, whether there is anything in it or not)

**Comment by FXDYJ** [comment]
emmm，请对作者说英语，你可以用百度翻译，不然作者看不懂

**Comment by Kazuha2022** [comment]
> 嗯嗯，请对作者说英语，你可以用百度翻译，emmm

ok

**Comment by JkLoveLiu** [comment]
然而我并不认为这样是好的。缺少这两个按钮将此与正服进行区分从而避免一些不必要的麻烦。
However I don't think this is good. The lack of these two buttons distinguishes this from the real server and avoids some unnecessary troubles

**Comment by FXDYJ** [comment]
？

**Comment by GLaDOS114514** [comment]
> 然而我并不认为这样是好的。缺少这两个按钮将此与正服进行区分从而避免一些不必要的麻烦。 However I don't think this is good. The lack of these two buttons distinguishes this from the real server and avoids some unnecessary troubles

事实上我认为这个项目本身的存在性已经会带来*很大的*法律麻烦，Actually I think the existence of this project itself can cause _massive_ legal issues. lol

**Comment by alt3ri** [comment]
Yes, and please close the issue.
