### ISSUE TITLE
HELP!!!! Error code:-9203

### ISSUE THREAD

**Issue by ALyCE233** [Melledy/Grasscutter#485]
I try to use proxy software like "Quantumult X" to proxy this game, but it keeps reporting error "-9203"
我尝试使用Quantumult X去代理游戏时它就一直报-9203
However, when I use the system proxy for IOS, I don't get any errors
但是使用苹果设置里面那个代理却可以正常用
![QQ图片20220503232617](https://user-images.githubusercontent.com/88792719/166484366-d65d2a4e-4770-4cb2-8dd2-4a4ff6d8cdba.png)
![QQ图片20220503232623](https://user-images.githubusercontent.com/88792719/166484380-ce87e262-d7b9-4b92-9836-2a8488229844.png)
I think these two should be the cause of the problem
我寻思这两个是造成问题的根本

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
