### ISSUE TITLE
Help me....

### ISSUE THREAD

**Issue by KaSock** [Melledy/Grasscutter#486]
I don't know what's wrong, I quit and deploy again, and I have restarted the computer, but still can't deploy

\
![image](https://user-images.githubusercontent.com/56071624/166488158-9bc966d0-5354-4656-a9a7-4ef612a7e691.png)
\
I'll give you all the information you want, provided I'm awake

**Comment by KaSock** [comment]
I found an optional solution, which is to reinstall mongdb, but that doesn't solve the root problem

**Comment by Mateoust** [comment]
Check if your `mongodb` is running normally, and Error please check your `Resources` folder.
`Resources` look here [Koko-boya/Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)
（Google Translate）

**Comment by Genshinjub** [comment]
It doesn't seem to install mongodb
