### ISSUE TITLE
4201Error.

### ISSUE THREAD

**Issue by channile** [Melledy/Grasscutter#487]
使用Fiddler出现的4201错误
fiddler内容[![OAoDwd.png](https://s1.ax1x.com/2022/05/04/OAoDwd.png)](https://imgtu.com/i/OAoDwd)  
原神错误内容[![OAocfP.png](https://s1.ax1x.com/2022/05/04/OAocfP.png)](https://imgtu.com/i/OAocfP)
求解

**Comment by channile** [comment]
localhost更改为127.0.0.1仍无法解决

**Comment by linkq** [comment]
用这个登陆器https://github.com/Grasscutters/GrassClipper-X.git

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
