### ISSUE TITLE
Exception in thread "main" java.net.BindException: Address already in use: bind

### ISSUE THREAD

**Issue by zhanshijinwat** [Melledy/Grasscutter#490]
When I run “java -jar grasscutter.jar”, I can't connect with MongoDB, it prompt me “the bind in use”, but I can sure MongoDB is using the port.
![image](https://user-images.githubusercontent.com/32569844/166618888-4f2e84e1-3e6d-4841-adee-7ec93a2a8fdd.png)

**Comment by zhanshijinwat** [comment]
When I run “java -jar grasscutter.jar”, I can't connect with MongoDB, it prompt me “the bind in use”, but I can sure MongoDB is using the port.
![image](https://user-images.githubusercontent.com/32569844/166619033-202b8923-ca0d-42a5-bbe0-b3923da56af1.png)

**Comment by AdemJensen** [comment]
This doesn't seems to be an issue with connection of MongoDB, it says it cannot listen to port, check your 443 port please.

**Comment by AdemJensen** [comment]
See the log above, the Mongo connection has succeeded.

**Comment by Vanitas-Sama** [comment]
i have same issues.. how to fix it?
![image_2022-05-04_155233900](https://user-images.githubusercontent.com/104894578/166650356-37ec17bd-2ffc-44a8-b0a7-a0e5f7fc6277.png)

**Comment by AdemJensen** [comment]
> i have same issues.. how to fix it? ![image_2022-05-04_155233900](https://user-images.githubusercontent.com/104894578/166650356-37ec17bd-2ffc-44a8-b0a7-a0e5f7fc6277.png)

Check your SSL certificate file `keystore.p12` is under the same directory with `grasscutter.js`, if confirmed, try to edit `config.js` and set `DispatchServer.KeystorePassword` to `123456`.

**Comment by AdemJensen** [comment]
The cause of error is because CERT file wasn't loaded successfully, so it downgrades to HTTP mode, and causing some error...

**Comment by zhanshijinwat** [comment]
It works!!!!!!! Change the DispatchServer.KeystorePassword to 123456.Thank you,Dalao.

**Comment by prprinu** [comment]
It works for me as well! Thank you so much!

**Comment by Vanitas-Sama** [comment]
nice.. worked.. thank you~

**Comment by KKLEL** [comment]
> > i have same issues.. how to fix it? ![image_2022-05-04_155233900](https://user-images.githubusercontent.com/104894578/166650356-37ec17bd-2ffc-44a8-b0a7-a0e5f7fc6277.png)
>  Check your SSL certificate file `keystore.p12` is under the same directory with `grasscutter.js`, if confirmed, try to edit `config.js` and set `DispatchServer.KeystorePassword` to `123456`.
>
I also have the same issue... why this solution didn't work for me

**Comment by lunaticwhat** [comment]
Commonly issue. Closed to clean up the workspace.
