### ISSUE TITLE
[Bug report] DispatchServer.start has a http bind bug

### ISSUE THREAD

**Issue by sakuya-kai** [Melledy/Grasscutter#493]
code line 166 has created a http server, but code line 182 ,the try-catch code , create http server once again.
![image](https://user-images.githubusercontent.com/28559801/166621566-f5396b8f-dcbe-4014-ac53-9140c717560f.png)

**Comment by 4Benj** [comment]
The dispatch server has been completed refactored within the dev branch and iirc with current plans a merge will happen in the coming days
