### ISSUE TITLE
关于所有治疗角色治疗能力失效的问题the failure of healing ability of all healing characters

### ISSUE THREAD

**Issue by andyjiaxintang** [Melledy/Grasscutter#494]
芭芭拉心海等奶妈治疗能力都失效了

**Comment by Scirese** [comment]
相关逻辑还没完善
---------------
Related logics are not implemented yet.

**Comment by lunaticwhat** [comment]
Healing aren't implemented yet. Closed to clean up the workspace.

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
