### ISSUE TITLE
Need a Telegram

### ISSUE THREAD

**Issue by Mashiro2000** [Melledy/Grasscutter#496]
It is recommended to open a "Telegram" group,
The "Discord" I applied for was blocked, saying I was a robot
I need to find an organization

**Comment by KudouShinnyan** [comment]
(机器人君)

**Comment by hanbao233xD** [comment]
hahaha

**Comment by ssr20001** [comment]
Me too
It's hard to use Discord in some special area

**Comment by dMxb12** [comment]
机器人桑？

**Comment by Ljzd-PRO** [comment]
I heard that the Telegram group has been created now, but I don’t know how to get the link to enter it.

**Comment by KudouShinnyan** [comment]
> I heard that the Telegram group has been created now, but I don’t know how to get the link to enter it.
![Screenshot_20220506-044626_Telegram](https://user-images.githubusercontent.com/68854981/167023490-6a78d10a-953a-4f86-b8ae-b6d5da472290.png)
(If search directly like this, it seems that only the Russian one is group related)

**Comment by KudouShinnyan** [comment]
![Screenshot_20220506-051317_Telegram](https://user-images.githubusercontent.com/68854981/167026584-443f0f70-6114-4b48-b922-35f9bbeb25f5.png)
![Screenshot_20220506-051346_Telegram](https://user-images.githubusercontent.com/68854981/167026588-20c1886c-aff9-4e82-8a8f-26d48ab6b8be.png)
