### ISSUE TITLE
创建账号页面为空白，请问如何自动创建账户呢？

### ISSUE THREAD

**Issue by SuYong1** [Melledy/Grasscutter#501]

**Comment by Mashiro2000** [comment]
`account create <username> [uid]`

**Comment by SuYong1** [comment]
> 

但是，这个是要登录后，才能输入这个指令，我现在是一个账号都没有

**Comment by Mashiro2000** [comment]
> > 
> 
> 但是，这个是要登录后，才能输入这个指令，我现在是一个账号都没有

服务端输入命令，你可以尝试输入`help`获取更多帮助

**Comment by Mashiro2000** [comment]
![image](https://user-images.githubusercontent.com/40681822/166642188-b3a62bc9-ade1-4aa5-95eb-fd20f5b024b0.png)

**Comment by SuYong1** [comment]
> ![image](https://user-images.githubusercontent.com/40681822/166642188-b3a62bc9-ade1-4aa5-95eb-fd20f5b024b0.png)

 我使用了putty连接，默认是22102端口，但是连接不上，是需要额外配置什么吗

**Comment by Mashiro2000** [comment]
你的远程服务器还是本地服务器，windows还是linux

**Comment by SuYong1** [comment]
> 你的远程服务器还是本地服务器，windows还是linux

win10+本地服务器

**Comment by Mashiro2000** [comment]
运行jar包，然后在控制台输入命令`help`

**Comment by SuYong1** [comment]
> 运行jar包，然后在控制台输入命令`help`

感谢，搞定了
