### ISSUE TITLE
最新dev版本中文翻译存在问题

### ISSUE THREAD

**Issue by miseryCN** [Melledy/Grasscutter#504]
![image](https://user-images.githubusercontent.com/32919541/166654474-2169bbf0-a7f9-4762-85d4-40db33f83606.png)

如图，字符串未正确格式化，显示s%

**Comment by Scirese** [comment]
#505，and,its not the latest dev.

**Comment by MapleNe** [comment]
不使用整合包就可以了

**Comment by naiyou240** [comment]
将目录下的languages全部删除即可
