### ISSUE TITLE
在Drop.json里关于怪物掉落物的错误

### ISSUE THREAD

**Issue by FoehnMLK** [Melledy/Grasscutter#512]
在Drop.json里写的是每个怪物都会掉落风之印ID:305，难道不应该是掉落元素微粒ID:2024吗？
所有怪物都会掉落的除了摩拉和冒险经验之外，我第一个想到的就是元素微粒

**Comment by a267764** [comment]
好的替换思路，但这是怪物死亡后的掉落，替换之后会显示？

**Comment by FoehnMLK** [comment]
> 替换后的好主意，但这是怪物死亡后的，替换之后会显示掉？

会显示拾取信息的确也是个问题
