### ISSUE TITLE
Some character talents fail 部分角色的天赋失效

### ISSUE THREAD

**Issue by Qzpz65** [Melledy/Grasscutter#514]
Such as thunder general and mandrill 如雷电将军和魈

**Comment by a267764** [comment]
角色命之座方面都有部分问题

**Comment by Nauw1010** [comment]
What is the reason that the constellations which make the E ability to have another chance to use (e.g. Ganyu's 2nd constellation, Shenhe's 1st constellation, Xiao's 1st constellation, etc.) fail? 是什麽原因讓那些使得E技能擁有額外使用次數的命之座失效的呢？（甘雨2命，申鶴1命，魈1命等）。

**Comment by memetrollsXD** [comment]
Please use the BinOutput from here: https://github.com/Koko-boya/Grasscutter_Resources

**Comment by Qzpz65** [comment]
> 请从此处使用 BinOutput：https://github.com/Koko-boya/Grasscutter_Resources

What s this？ ls there a problem with the talent charging conversion of general thunder and lighing
