### ISSUE TITLE
[ERROR] Error loading resource file: [WeaponCurveExcelConfigData.json]com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 5 column 14 path $[0].curveInfos[0]

### ISSUE THREAD

**Issue by xuanyuandy** [Melledy/Grasscutter#515]
I don't know if this problem is caused by java version , my os is win11 ,java version is 

```
java 18 2022-03-22
Java(TM) SE Runtime Environment (build 18+36-2087)
Java HotSpot(TM) 64-Bit Server VM (build 18+36-2087, mixed mode, sharing)
```

**Comment by memetrollsXD** [comment]
Looks like it's a problem with your ExcelBinOutput and not related to your java version or Grasscutter

**Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

**Comment by gszshdzz** [comment]
2.7不能用releases的jar，在actions里下载最新的jar，删数据库
（translated）2.7 You cannot use the relays of the jar, download the latest jar in the actions, delete the database
