### ISSUE TITLE
in-game abilities are limited.

### ISSUE THREAD

**Issue by RynSkii** [Melledy/Grasscutter#521]
i start my server normally, using start.cmd mongodb and fiddler, but when i join i cannot do so many things, such as fight with wished/added characters, sprint with ayaka or use abilities of characters. also when i teleport to a waypoint it says internal server error. anyone knows how to fix that? also can't message dummy

**Comment by xmplay** [comment]
read.

**Comment by RynSkii** [comment]
> read.

read what

**Comment by RynSkii** [comment]
it seems like i can't find that on wikis troubleshooting, because it's not a problem with ports and idk what might be the issue

**Comment by xmplay** [comment]
fourth line of the readme

**Comment by ghost** [comment]
> i start my server normally, using start.cmd mongodb and fiddler, but when i join i cannot do so many things, such as fight with wished/added characters, sprint with ayaka or use abilities of characters. also when i teleport to a waypoint it says internal server error. anyone knows how to fix that? also can't message dummy

Hello, it is more likely BinOutput issue. It's on Readme which was added few days ago.

**Comment by ghost** [comment]
Also, take note. Not all teleport waypoints work, that includes domain teleport waypoint.

**Comment by RynSkii** [comment]
thank you so much for help!! i insatlled the new binoutput!
