### ISSUE TITLE
teleport to somewhere.(build #420)

### ISSUE THREAD

**Issue by GearOvO** [Melledy/Grasscutter#523]
After replacing the latest grasscutter (build #420), is there any way to achieve fast teleport in bonus ?
When I mark the location of the map, I can't teleport to the specified location anymore.

**Comment by gentlespoon** [comment]
Hi GearOvO.
In my recent PR, I have updated the code to allow markings on the map. We should update the docs soon.
While you can make marks on the map now, the fish hook marking (the last one) will still teleport you anywhere you want.

**Comment by GearOvO** [comment]
Thank you very much for answering my question, it worked!

**Comment by gentlespoon** [comment]
Good to know that it works. Would you please close this issue as it is resolved?
