### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by mahaoqqsx** [Melledy/Grasscutter#526]
[07:43:25] [ERROR] LEAK: ByteBuf.release() was not called before it's garbage-co
llected. See https://netty.io/wiki/reference-counted-objects.html for more infor
mation.

**Comment by 4Benj** [comment]
Not enough information provided. Please provide stack-trace.
I'm closing this one as it is possibly related to #544 which it provided the full error message.
If you do not think it is related please reopen the issue
