### ISSUE TITLE
Physical strength value bug

### ISSUE THREAD

**Issue by xiguadoudou** [Melledy/Grasscutter#529]
When it is transferred to the domain of Guyun for the first time, the physical strength will be abnormally reduced, and ordinary attacks and elemental warfare techniques cannot be used
![image](https://user-images.githubusercontent.com/89190859/166850807-28b4326b-7694-4021-a0a2-0a4041948874.png)

**Comment by gentlespoon** [comment]
We are working on it.

**Comment by gentlespoon** [comment]
Should be fixed by now.

**Comment by lunaticwhat** [comment]
Closed to clean up the workspace.
