### ISSUE TITLE
使用过程中发现服装ID输入全部无效  No response to fashion code input

### ISSUE THREAD

**Issue by lcq224** [Melledy/Grasscutter#531]
During my use, I found that all the fashion ID inputs were invalid and asked the boss to solve it,The above is machine translation,Sorry for any trouble.

**Comment by lcq224** [comment]
应该是服装代码

**Comment by lcq224** [comment]
It should be the clothing id

**Comment by lcq224** [comment]
使用过程中发现服装ID输入全部无效，求大佬解决

**Comment by SleepyAsh0191** [comment]
请自行替换 AvatarCostumeExcelConfigData.json 为正确的版本。

Please replace your json file with the correct version.

**Comment by lcq224** [comment]
> 请替换 AvatarCostumeExcelConfigData.json 为自己的正确版本。
> 
> 请将您的 json 文件替换为正确的版本。

您好，请问去哪里替换正确的json文件呢？我下载了代码文件，只有4mb，里面没有 AvatarCostumeExcelConfigData.json这个文件，求教，万分感激。
Hello, where can I replace the correct JSON file? I downloaded the code file, only 4MB, and there is no avatarcostumeexcelconfigdata in it JSON this file, ask for advice, thank you very much.
以上为机器翻译，如难以理解，实在抱歉。
The above is machine translation. I'm sorry if it's difficult to understand.

**Comment by SleepyAsh0191** [comment]
> > 请替换 AvatarCostumeExcelConfigData.json 为自己的正确版本。
> > 请将您的 json 文件替换为正确的版本。
> 
> 您好，请问去哪里替换正确的json文件呢？我下载了代码文件，只有4mb，里面没有 AvatarCostumeExcelConfigData.json这个文件，求教，万分感激。 Hello, where can I replace the correct JSON file? I downloaded the code file, only 4MB, and there is no avatarcostumeexcelconfigdata in it JSON this file, ask for advice, thank you very much. 以上为机器翻译，如难以理解，实在抱歉。 The above is machine translation. I'm sorry if it's difficult to understand.



前往 `\resources\ExcelBinOutput` 文件夹，然后将原文件替换为 [此处](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json) 提供的 json 文件。

Go to  `\resources\ExcelBinOutput` folder, then replace the original file with [this file](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json).

**Comment by qingchunnh** [comment]
https://github.com/Koko-boya/Grasscutter_Resources 可以使用这个试试看

**Comment by lcq224** [comment]
> https://github.com/Koko-boya/Grasscutter_Resources 可以使用这个试试看

这些版本是通用的吗，直接替换还是？

**Comment by lcq224** [comment]
> > > 请替换 AvatarCostumeExcelConfigData.json 为自己的正确版本。
> > > 请将您的 json 文件替换为正确的版本。
> > 
> > 
> > 您好，请问去哪里替换正确的json文件呢？我下载了代码文件，只有4mb，里面没有 AvatarCostumeExcelConfigData.json这个文件，求教，万分感激。 Hello, where can I replace the correct JSON file? I downloaded the code file, only 4MB, and there is no avatarcostumeexcelconfigdata in it JSON this file, ask for advice, thank you very much. 以上为机器翻译，如难以理解，实在抱歉。 The above is machine translation. I'm sorry if it's difficult to understand.
> 
> 前往 `\resources\ExcelBinOutput` 文件夹，然后将原文件替换为 [此处](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json) 提供的 json 文件。
> 
> Go to `\resources\ExcelBinOutput` folder, then replace the original file with [this file](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json).
十分感谢，已经解决了，感谢大佬帮助！

**Comment by qingchunnh** [comment]
> > https://github.com/Koko-boya/Grasscutter_Resources 可以使用这个试试看
> 
> 这些版本是通用的吗，直接替换还是？

看介绍

**Comment by lcq224** [comment]
> > > https://github.com/Koko-boya/Grasscutter_Resources可以使用这个试试看
> > 
> > 
> > 这些版本是通用的吗，直接替换还是？
> 
> 看介绍
好，十分感谢!

**Comment by lcq224** [comment]
> > > 请替换 AvatarCostumeExcelConfigData.json 为自己的正确版本。
> > > 请将您的 json 文件替换为正确的版本。
> > 
> > 
> > 您好，请问去哪里替换正确的json文件呢？我下载了代码文件，只有4mb，里面没有 AvatarCostumeExcelConfigData.json这个文件，求教，万分感激。 Hello, where can I replace the correct JSON file? I downloaded the code file, only 4MB, and there is no avatarcostumeexcelconfigdata in it JSON this file, ask for advice, thank you very much. 以上为机器翻译，如难以理解，实在抱歉。 The above is machine translation. I'm sorry if it's difficult to understand.
> 
> 前往 `\resources\ExcelBinOutput` 文件夹，然后将原文件替换为 [此处](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json) 提供的 json 文件。
> 
> Go to `\resources\ExcelBinOutput` folder, then replace the original file with [this file](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json).

你好，非常抱歉又来打扰您，请问进入秘境与深境螺旋之类的是只能用切换场景id来实现的吗？如果是这样的话，例如精通秘境冰封废渊得场景id是40200，我输入之后显示错误，或者直接没反应，请问这该如何解决呢？
Hello, I'm sorry to bother you again. Can you only switch the scene ID to enter the secret environment and deep environment spiral? If this is the case, for example, if the scene ID of mastering the frozen waste abyss in the secret realm is 40200, an error will be displayed after I input it, or there will be no response directly. How can I solve this?
以上为机器翻译，如难以理解，实在抱歉。
The above is machine translation. I'm sorry if it's difficult to understand.

**Comment by dogdie233** [comment]
> > > > 请替换 AvatarCostumeExcelConfigData.json 为自己的正确版本。
> > > > 请将您的 json 文件替换为正确的版本。
> > > 
> > > 
> > > 您好，请问去哪里替换正确的json文件呢？我下载了代码文件，只有4mb，里面没有 AvatarCostumeExcelConfigData.json这个文件，求教，万分感激。 Hello, where can I replace the correct JSON file? I downloaded the code file, only 4MB, and there is no avatarcostumeexcelconfigdata in it JSON this file, ask for advice, thank you very much. 以上为机器翻译，如难以理解，实在抱歉。 The above is machine translation. I'm sorry if it's difficult to understand.
> > 
> > 
> > 前往 `\resources\ExcelBinOutput` 文件夹，然后将原文件替换为 [此处](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json) 提供的 json 文件。
> > Go to `\resources\ExcelBinOutput` folder, then replace the original file with [this file](https://anonfiles.com/Ndz6ofddye/AvatarCostumeExcelConfigData_json).
> 
> 你好，非常抱歉又来打扰您，请问进入秘境与深境螺旋之类的是只能用切换场景id来实现的吗？如果是这样的话，例如精通秘境冰封废渊得场景id是40200，我输入之后显示错误，或者直接没反应，请问这该如何解决呢？ Hello, I'm sorry to bother you again. Can you only switch the scene ID to enter the secret environment and deep environment spiral? If this is the case, for example, if the scene ID of mastering the frozen waste abyss in the secret realm is 40200, an error will be displayed after I input it, or there will be no response directly. How can I solve this? 以上为机器翻译，如难以理解，实在抱歉。 The above is machine translation. I'm sorry if it's difficult to understand.

秘境功能目前是无法正常使用的，切换到`development`分支用`/enterdungeon <秘境id>`或`/changescene <场景id>`进入秘境(不能正常玩就是了)

**Comment by lcq224** [comment]
好的！十分感谢您的帮助！现在我用/givechaer xxxxx 90调出角色并且装上90级武器时，会出现元素能量异常的情况{元素能量一直处于满能量状态，释放元素爆发时元素能量不变，一直处于满能量状态}   重启客户端也没用，请问这是什么问题呢？

**Comment by czy20010112** [comment]
> 好的！十分感谢您的帮助！现在我用/givechaer xxxxx 90调出角色并且装上90级武器时，会出现元素能量异常的情况{元素能量一直处于满能量状态，释放元素爆发时元素能量不变，一直处于满能量状态} 重启客户端也没用，请问这是什么问题呢？

充能现在还没做，所以都是无限大。这些问题尽量去discord群，这里是issue不是support。

**Comment by lcq224** [comment]
> discord群
好的！请问discord群在哪呢？方便指个路吗？

**Comment by czy20010112** [comment]
> > discord群
> > 好的！请问discord群在哪呢？方便指个路吗？

https://discord.gg/T5vZU6UyeG readme里有。。。

**Comment by czy20010112** [comment]
> > discord群
> > 好的！请问discord群在哪呢？方便指个路吗？

问题解决了请关闭issue）

**Comment by lcq224** [comment]
> > > discord群
> > > 好的！请问discord群在哪呢？方便指个路吗？
> 
> 问题解决了请关闭issue）

好，谢谢。我关闭了
