### ISSUE TITLE
The feedback after using the command is incorrect

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#540]
When I use /give 223 10, the information fed back to me is shown in the figure, but the correct item and character ID are not fed bac
![1](https://user-images.githubusercontent.com/89347877/166903377-58823824-604a-4e79-ad76-67475fdb0a8d.png)
![2](https://user-images.githubusercontent.com/89347877/166903389-a7854339-7adf-4396-b4be-bd1fe757316f.png)
k

**Comment by memetrollsXD** [comment]
Is this with the latest dev commit?

**Comment by yuexuanblog** [comment]
> 这是最新的开发提交吗？

YES

**Comment by yuexuanblog** [comment]
After deleting the languages folder and reopening the generated languages folder, the problem has been solved
