### ISSUE TITLE
Permission class command does not take effect correctly

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#541]
When I use the permission command, the command does not take effect, and the information shown in the figure is fed back. Maybe we should update READ.md
![3](https://user-images.githubusercontent.com/89347877/166903472-dd0db747-4d24-4978-a129-9183c5085c58.png)

**Comment by memetrollsXD** [comment]
Please use UID instead of username. #557 changes the documentation for this
