### ISSUE TITLE
[ERROR]LEAK: ByteBuf.release() was not called before it's garbage-collected. 

### ISSUE THREAD

**Issue by dongriiiii** [Melledy/Grasscutter#544]
I deployed grasscutter on the server. During the game, the server suddenly reported an error, showing a network error and unable to log in to the game. The account in the game has no impact, but once you exit, you can't log in to the account, and restarting the server can't solve it.
The following is the error message：

LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
        io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
        io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
        io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:600)
        io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        java.base/java.lang.Thread.run(Thread.java:833)

**Comment by 4Benj** [comment]
What is the error when you try and login?

**Comment by dongriiiii** [comment]
> 当您尝试登录时，会出现什么错误？
network error/网络错误
![38BCCE424D144FAF7A9D38AED3574748](https://user-images.githubusercontent.com/87489560/166928969-efa23e90-5b33-4090-aa07-e87130d71b47.jpg)

**Comment by 4Benj** [comment]
Is this in the dev branch?

**Comment by dongriiiii** [comment]
> Is this in the dev branch?

Both dev branch and stable branch have tried

**Comment by memetrollsXD** [comment]
The error is unrelated to your problems, please visit our Discord for further support

**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
