### ISSUE TITLE
China Server SDK

### ISSUE THREAD

**Issue by rainbowwarmth** [Melledy/Grasscutter#546]
When can I become a Chinese Genshin server

**Comment by fjlycx** [comment]
我可以评论嘛？

**Comment by rainbowwarmth** [comment]
Why do you want to comment












linke
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, May 5, 2022 21:37 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Grasscutters/Grasscutter] China Server SDK (Issue #546)




 
我可以评论嘛？

**Comment by mengguyi** [comment]
没有看懂你说的什么，”When can I become a Chinese Genshin server“我猜测你想问国服客户端能否使用。PC端好像能用，iOS端能用，Android端必须用国际服。
还是说你想问“How can I become a Chinese Genshin server”

**Comment by rainbowwarmth** [comment]
But up to now, computer IOS is still the SDK of international service












linke
***@***.***


---Original---
From: ***@***.***&gt;
Date: Thu, May 5, 2022 21:41 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Grasscutters/Grasscutter] China Server SDK (Issue #546)




 
没有看懂你说的什么，”When can I become a Chinese Genshin server“我猜测你想问国服客户端能否使用。PC端好像能用，iOS端能用，Android端必须用国际服。
 还是说你想问“How When can I become a Chinese Genshin server”

**Comment by yijiangchengming** [comment]
这似乎是一样的api,你可以尝试将所有流量重定向到你的服务器。从而分辨需要重定向哪些流量。

**Comment by rainbowwarmth** [comment]
It is not directed to the national service api


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Grasscutters/Grasscutter"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月6日(星期五) 中午1:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Grasscutters/Grasscutter] China Server SDK (Issue #546)





 
这似乎是一样的api,你可以尝试将所有流量重定向到你的服务器。从而分辨需要重定向哪些流量。

**Comment by lunaticwhat** [comment]
Not related to issues section. You can ask in our [Discord server](https://discord.gg/T5vZU6UyeG). Closed to clean up the workspace.
