### ISSUE TITLE
It seems some constellations and talents still do not work

### ISSUE THREAD

**Issue by NMDWSM0** [Melledy/Grasscutter#554]
In the stable version, The C2 of Raiden Shougun and the talent which convert recharge to elec dmg still donot work. And I have use the latest vetsion of "GrassCutters_Resources" published 6days ago.Have The problems been solved in the 2.7branch or dev branch?

**Comment by LRY89757** [comment]
A good problem, it seems like maybe the problem of your sys, win11?😜

**Comment by Emsigant** [comment]
The features are not implemented yet

**Comment by lunaticwhat** [comment]
its a known problem with almost character's cons doesn't work. will be fix in the future !
