### ISSUE TITLE
"emu.grasscutter.data.def.AvatarTalentData.getAddProps()" is null

### ISSUE THREAD

**Issue by cfuncode** [Melledy/Grasscutter#555]

**Comment by cfuncode** [comment]
![image](https://user-images.githubusercontent.com/36926346/166985084-f6e284af-2fbc-4036-97a0-b044b7f28ce0.png)
![image](https://user-images.githubusercontent.com/36926346/166985194-3402fe5f-212e-4292-ba55-5c7af7b848cf.png)
![image](https://user-images.githubusercontent.com/36926346/166985287-12076083-c4f8-43f1-b5da-bf6c989d03be.png)

要怎么解决？

**Comment by coderstory** [comment]
好像是配置文件残缺了

**Comment by JulienZeng** [comment]
更新 resources 资源

**Comment by cfuncode** [comment]
> 好像是配置文件残缺了

不是，是代码问题。在我本机跑有问题。解决了：https://github.com/Grasscutters/Grasscutter/pull/585
