### ISSUE TITLE
游玩过程中发现的问题

### ISSUE THREAD

**Issue by Cardgodk** [Melledy/Grasscutter#556]
1.雷电将军的固有天赋 额外充能效率转换成雷元素伤害加成无效
2.所有治疗类角色的治疗技能无法起到治疗效果
3.角色无限大招（可能是因为E技能无法产生元素微粒所以你们故意设置的吧 猜测哈哈哈）
3.角色胡桃的E技能无法扣除血量 导致一些依赖低血量的技能天赋无法生效包括专属武器护摩之杖
4.怪物 深渊咏者在被击打至低血量出现护盾的时候没有无敌效果 导致可以直接打死不用破盾
目前貌似就发现这些比较重要的问题 其他不是很重要的问题就没说啦 哈哈哈 致谢所有参研人员

**Comment by Thomitics** [comment]
Please use English since most of the main developers are English speakers.

**Comment by Lynricsy** [comment]
Please use English since most of the main developers of this project are English speakers.

**Comment by KiminaNatsuki** [comment]
Translate:
1. Raiden Shogun's Passive Talent, Extra ER can't grant her electro elemental damage
2. All healing based character can't heal with their skills
3. Character has infinite burst (It's possible that elemental skills can't generate elemental orbs so you guys set it that way lmao)
4. Hu Tao's elemental skills can't reduce her HP, this led to some skill that's based on low HP won't work (including staff of homa)
5. Abyss Lector's shield didn't grant it invisibility, so people can just kill it without breaking the shield
I only found these kinda important problems, so i didn't list the minor problems lmao, thanks to all who's in development team.

(kimi's note: i always think chinese to english is hard enough lol)

**Comment by 1-lavender-1** [comment]
These are all known issues, they are not implemented yet

这些都是已知的问题，相关特性还没有开发

**Comment by memetrollsXD** [comment]
You can manually set Hu Taos HP with the /stat command

**Comment by Cardgodk** [comment]
> 请使用英语，因为该项目的大多数主要开发人员都是讲英语的人。

Okay, I'll pay attention to it later. Thank you

**Comment by Cardgodk** [comment]
> 翻译：
> 
> 1. 雷电将军的被动天赋，额外的ER无法给予她的电元素伤害
> 2. 所有基于治疗的角色都无法用他们的技能治愈
> 3. 角色有无限的爆发力（元素技能可能无法生成元素球体，所以你们会这样设置lmao）
> 4. 胡涛的元素技能无法降低她的HP，这导致一些基于低HP的技能不会起作用（包括homa的员工）
> 5. Abyss Lector的盾牌没有赋予它隐形性，所以人们可以在不破坏盾牌的情况下杀死它，我只发现了这些重要的问题，所以我没有列出lmao的小问题，感谢开发团队中的所有人。
> 
> （kimi的注：我一直认为中文到英文已经够难了哈哈）

Thank you very much for helping me react hahaha.

**Comment by Cardgodk** [comment]
> 这些都是已知问题，尚未实现
> 
> 这些都是已知的问题，相关特性还没有开发



> 这些都是已知问题，尚未实现
> 
> 这些都是已知的问题，相关特性还没有开发

知道啦 我就是想分享下我发现的问题

**Comment by Cardgodk** [comment]
> You can manually set Hu Taos HP with the /stat command

But every time you release your skills, you need to give an instruction, which is very troublesome.

**Comment by KaSock** [comment]
这些问题其实已经有人说了，**无敌锁血**什么的，基本都没有，剑鬼起身能被打死之类的，无相系列**包裹**自己还能被范围伤害(例如钟离Q)打到，有能力的话可以自己写然后pr

**Comment by Cardgodk** [comment]
> 这些问题其实已经有人说了，**无敌锁血**什么的，基本都没有，剑鬼起身能被打死之类的，无相系列**包裹**自己还能被范围伤害(例如钟离Q)打到，有能力的话可以自己写然后pr

了解了 感谢
