### ISSUE TITLE
Is there an official group in this thing? Can you say it?这个东西有官方的群吗？能不能说一下？

### ISSUE THREAD

**Issue by blukogift** [Melledy/Grasscutter#561]

**Comment by nkxingxh** [comment]
你能看看readme吗

**Comment by minhngoc25a** [comment]
这个项目有一个Discord服务器。它被列在README文件中，但这里有链接。

https://discord.gg/T5vZU6UyeG

**Comment by SummerOfIce** [comment]
The discord app can't be registered at all,even though I used a vpn.It always prompts me that "the operation timed out,please try again".I prefer use Telegram.

**Comment by minhngoc25a** [comment]
> The discord app can't be registered at all,even though I used a vpn.It always prompts me that "the operation timed out,please try again".I prefer use Telegram.

Change to a commercial VPN instead because public VPNs are shared with many users. Or, you can use a DPI blocking circumvention tool such as GoodByeDPI, or a DNS over HTTPS client like Cloudflare 1.1.1.1.
