### ISSUE TITLE
a lot of null pointer exception

### ISSUE THREAD

**Issue by hash070** [Melledy/Grasscutter#562]
when the server running for a while,it will consistently show "null pointer exception"(players could enter and play the game normally)
just like the following images
![image](https://user-images.githubusercontent.com/62081013/167060523-dc78e95e-62f2-434c-8350-6e672527d786.png)
![image](https://user-images.githubusercontent.com/62081013/167060860-4253dd68-4e0f-4178-b1d3-f2f1d6dbe2ff.png)
server is using the dev-branch files with #456 Build progrom in the GitHub Actions
environment:jdk-18   mongodb:4.4(docker)

**Comment by Xiao-yux** [comment]
该怎么办？

**Comment by hash070** [comment]
And It will stop after few hours without any bad effects to players from strat to end.
It seems like a harmless bug.

**Comment by hash070** [comment]
It has been fixed by build#529 in GitHub Actions
