### ISSUE TITLE
安卓原神无法登录/Android cannot log in

### ISSUE THREAD

**Issue by keqingyyds** [Melledy/Grasscutter#564]
Server TLS handshake failed. connection closed
Unable to establish TLS connection with server
怎么解决？用的国际服，root证书。

**Comment by dMxb12** [comment]
你这是代理没设置好吧

**Comment by hash070** [comment]
电脑能连的话就是代理没设置好，去discord问问吧，issue不是这样提的

**Comment by lunaticwhat** [comment]
There is a support section on our discord for Chinese language ! Come and people will help you with that problem.
