### ISSUE TITLE
Suggestions: do anyone plan to do something to see the under skirts ? 

### ISSUE THREAD

**Issue by czy20010112** [Melledy/Grasscutter#565]
just as title .don't know how to describe the "banned angle of view"

**Comment by hash070** [comment]
Oh that's a good idea
But I think that does not matter with the server,may be you should make some changes with your local genshin client file.

**Comment by misaka10843** [comment]
> just as title .don't know how to describe the "banned angle of view"

This function is to modify the client.
The server is at most to determine whether you have modified the client, if modified will be sealed (official server)

**Comment by gentlespoon** [comment]
(* /ω＼*) No.

**Comment by alt3ri** [comment]
No
