### ISSUE TITLE
Upgrade to BEYOND Java 8

### ISSUE THREAD

**Issue by KingRainbow44** [Melledy/Grasscutter#57]
At the moment Grasscutter is locked to Java 8. (if this isn't true, someone let me know)
The reasons for this are:
- The MongoDB mapper (at its current version) is not compatible with Java versions beyond 9.
- The client seems to not be able to connect to the **game server**

I've already attempted updating the MongoDB wrapper to 16 with success, but the second issue is still applicable.
Worst case scenario: the KCP server will need updating to support newer versions of Java.
Best case scenario: I screwed something up while trying to update.

If anyone wants the updated database wrapper, let me know!

EDIT:
- [ ] Refactor KCP system
- [ ] Refactor dispatch system
With both of these, Java 8+ should be supported just fine.

**Comment by KingRainbow44** [comment]
Another good reason for doing this is because it seems people in the `#support` channel have a **ton** of issue with the Java version, since most have a newer version installed/don't know how to multiple versions of Java at the same time.

**Comment by MlgmXyysd** [comment]
> * The MongoDB mapper (at its current version) is not compatible with Java versions beyond 9.

Can we migrated it to MySQL?

**Comment by KingRainbow44** [comment]
> Can we migrated it to MySQL?

the idea isn't to migrate database (since the entire server literally RELYS on the mongo wrapper) and besides like I said, I already have the wrapper working on Java 16

**Comment by 4Benj** [comment]
> Can we migrated it to MySQL?

for the type of data we are saving MongoDB is more suitable in my opinion

**Comment by KingRainbow44** [comment]
Finished with #130!
