### ISSUE TITLE
dev[744aa47] 初始角色不能普通攻击(拔刀)和释放技能

### ISSUE THREAD

**Issue by HuanzuoSP** [Melledy/Grasscutter#572]
![image](https://user-images.githubusercontent.com/43463220/167084239-df981b81-9a56-406a-bdc4-7731ae6da94c.png)

**Comment by hash070** [comment]
我也是开发板，没有这种问题，是不是你资源文件配置有误？
试一下这个整理好的资源文件
https://github.com/Koko-boya/Grasscutter_Resources

**Comment by HuanzuoSP** [comment]
> 我也是开发板，没有这种问题，不是你的资源文件配置有误？ 试一下这个整理好的资源文件 https://github.com/Koko-boya/Grasscutter_Resources

重启客户端 解决了
