### ISSUE TITLE
How to update grasscutter

### ISSUE THREAD

**Issue by lincexu** [Melledy/Grasscutter#576]
How to update to the latest grasscutter while retaining previous data？

**Comment by KudouShinnyan** [comment]
Find the version you want to use from Actions. After entering the page, click grasscutter to download it, then unzip it and replace your original grasscutter.jar with the unzipped file

**Comment by Arikatsu** [comment]
also delete ur config.json, so that it regenerates a new one after updating

**Comment by lunaticwhat** [comment]
Just fetch the branch you want (stable or dev) and recomplie the jar. Remember (Recommended) to delete the config.json to clear old settings
