### ISSUE TITLE
代理不了（errno 10048）

### ISSUE THREAD

**Issue by Angel884** [Melledy/Grasscutter#584]
![image](https://user-images.githubusercontent.com/105055563/167140151-e5057cab-524d-4a2e-be41-a1ee9bec9bc3.png)
有没有大佬帮帮我，感谢

**Comment by ClayCoffee** [comment]
8080端口已经被占了

**Comment by Angel884** [comment]
我知道，但我重启也不行，也没用其他代理软件。

> 8080端口已经被占了

**Comment by Angel884** [comment]
行了，在cmd用netstat -ano|findstr +端口号查看对应进程，再在任务管理器关闭这个进程就行。

**Comment by lunaticwhat** [comment]
It's good to see you solved your problems. Closed to clean up the workspace.
