### ISSUE TITLE
/talent command doesn't work properly

### ISSUE THREAD

**Issue by SunshineVX** [Melledy/Grasscutter#587]
After a talent level is changed,it will be reseted to 1 somehow.

**Comment by SunshineVX** [comment]
This appears when a character joins or quits the team.

**Comment by lunaticwhat** [comment]
have you try to re-login into the game after changing talent levels ?
everything related to user database modification should be need a re-login.

**Comment by SunshineVX** [comment]
> have you try to re-login into the game after changing talent levels ? everything related to user database modification should be need a re-login.

But it worked well in previous versions.I just notice this problem today after i update it to latest dev.

**Comment by lunaticwhat** [comment]
thanks for those bug reports. marked as to-do.

**Comment by DaisenSun** [comment]
I have encountered the same problem. After testing, in the current version, there is no change after the talent upgrade and before the upgrade. I don't know what the problem is

**Comment by Danii57** [comment]
yeah its happening to me too.
