### ISSUE TITLE
[Issue] Issue when compile

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#588]
I use development branches  and use "gradle jar" but when compile it reported this.
LuaSerializer.java:73: warning: non-varargs call of varargs method with inexact argument type for last parameter;
                        object = type.getDeclaredConstructor().newInstance(null);
                                                                           ^
  cast to Object for a varargs call
  cast to Object[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
Is there a issue or just problem when compile? JDK 17.0.3.1 mongodb 5.0.8

**Comment by liamhnam** [comment]
same here

**Comment by arub3do** [comment]
This is a `warning`.
Just ignore it, you can still successfully compile and run.
