### ISSUE TITLE
I can't create a new account.

### ISSUE THREAD

**Issue by cold-runner** [Melledy/Grasscutter#591]
When I run commend in commend line  ```account create username 123345```
It return like this 
![Snipaste_2022-05-06_22-46-21](https://user-images.githubusercontent.com/86516312/167156790-3d5db21a-6397-4294-9c9e-86c7b273e9f1.png)

**Comment by lunaticwhat** [comment]
Can you provide more info about which branch you re currently using ?

**Comment by KiminaNatsuki** [comment]
i think the issue is just the [] around the username

**Comment by unknown10777** [comment]
Download codes and recomplie with java-17.0.3 will solve this problem.
Run cmd in the folder where you store unzipped codes and type `gradlew.bat make` . Then you'll see a .jar at current directory.

**Comment by unknown10777** [comment]
> Can you provide more info about which branch you re currently using ?

Please check the link for grasscutter.jar in 'readme.md'. I have the same problem while using the file precompiled.

**Comment by Gelmezon** [comment]
you can start server with this code
```
java -jar grasscutter.jar -add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED
```
