### ISSUE TITLE
Accidental death of character

### ISSUE THREAD

**Issue by MapleNe** [Melledy/Grasscutter#593]
When I fall down and attack many times and talk to NPC, the character will die
or fall down attack one time
当我多次下落攻击之后和NPC对话角色就会死亡
pls watch video
请看视频
[video](https://discord.com/channels/965284035985305680/967477370997076079/972155080935624744)
https://imgur.com/a/2gRrXw9

**Comment by lunaticwhat** [comment]
provided video links doesn't work

**Comment by MapleNe** [comment]
> provided video links doesn't work

on discord channel #support-zh

**Comment by lunaticwhat** [comment]
> > provided video links doesn't work
> 
> on discord channel #support-zh

can you mention me @lunatic#1911 ?

**Comment by MapleNe** [comment]
> > > provided video links doesn't work
> > 
> > 
> > on discord channel #support-zh
> 
> can you mention me @lunatic#1911 ?

okay

**Comment by lunaticwhat** [comment]
I see. Might be a bug with character taken damage handler and may related to pr #551

**Comment by gentlespoon** [comment]
Could be related to #551. I'll have a look at this.

**Comment by gentlespoon** [comment]
Can confirm is caused by #551. But wth does talking to NPC send a MotionState.MOTION_FALL_ON_GROUND packet?

**Comment by gentlespoon** [comment]
@Melledy

**Comment by gentlespoon** [comment]
@MapleNe  Try again.

**Comment by lunaticwhat** [comment]
fixed with PR #601. Closed to clean up the workspace.
