### ISSUE TITLE
Fix Wiki/Documentation

### ISSUE THREAD

**Issue by MidnightQuery** [Melledy/Grasscutter#596]
https://github.com/Grasscutters/Grasscutter/wiki/Running

- JDK8u202 link does not work anymore
- Guide lead to stable build but the Keystore file is for development build
- Fix GenshinData

It was a dumpster fire for me to get the server working

**Comment by lunaticwhat** [comment]
wiki will get overhauled after we merge the dev branch into stable. stay tune !
