### ISSUE TITLE
What kind of question is that

### ISSUE THREAD

**Issue by Cardgodk** [Melledy/Grasscutter#597]
![c9fbd10045075ebbb9d0c87cb4571f5](https://user-images.githubusercontent.com/105013385/167194000-c909f3e5-5b2c-4c0f-99fc-4d8af1dc4f5c.png)

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
