### ISSUE TITLE
That's why

### ISSUE THREAD

**Issue by Cardgodk** [Melledy/Grasscutter#598]
![c9fbd10045075ebbb9d0c87cb4571f5](https://user-images.githubusercontent.com/105013385/167194667-d66b8981-af97-4866-8f94-ce5da0c044d5.png)

**Comment by minhngoc25a** [comment]
You'll be restricted in this repo if you keep spamming and abusing the issue tracker like that.

**Comment by lilmayofuksu** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
