### ISSUE TITLE
stamina problem

### ISSUE THREAD

**Issue by Danii57** [Melledy/Grasscutter#602]
I right now have the latest development version and gliding and climbing stamina works but running and charged attacks don't consume stamina and I think it should, pls solve it.

**Comment by lunaticwhat** [comment]
yes this is a known issue and stamina system hasnt properly implemented yet. 
known contributors who work on stamina system @[gentlespoon](https://github.com/gentlespoon) and @[BaiSugar](https://github.com/baisugar)

**Comment by gentlespoon** [comment]
I am aware of running stamina issue. Working on it already.
Charged attack stamina cost will be implemented later this week.

**Comment by gentlespoon** [comment]
@Danii57 see if dashing costs stamina now?

**Comment by Danii57** [comment]
Oh actually I cannot right now but I'll sure try tomorrow, ty.

**Comment by Danii57** [comment]
it's working, ty :)

**Comment by lunaticwhat** [comment]
glad to hear that the issue has been fixed. Closed to clean up the workspace.
