### ISSUE TITLE
There has some bugs with the Abyss tower 

### ISSUE THREAD

**Issue by a267764** [Melledy/Grasscutter#604]
About abyss tower .
First ,I can get in to the AByss, but when I meet some organ in the tower.I just can complete the challenge,but I couldn't enter the next layer.
Second ,if I choose the layer which must be two teams.I can get in ,but I can't start the challenge.
Third , the enemies in the abyss are too fragile.Their values are too low.Please increase their values.
Thanks for reading,please forgive my bad english.

**Comment by Akka0** [comment]
1.Now fix at #594 
2/3. Still in dev
