### ISSUE TITLE
[ERROR] Failed to load language file: zh-CN.json

### ISSUE THREAD

**Issue by qiuye536** [Melledy/Grasscutter#608]
<img width="682" alt="Snipaste_2022-05-07_10-48-13" src="https://user-images.githubusercontent.com/60189811/167235060-51e8a311-9f9f-404b-b29f-be9906008bd0.png">

**Comment by SunshineVX** [comment]
They haven't added this file yet

**Comment by qiuye536** [comment]
> They haven't added this file yet

okay

**Comment by RealHeart** [comment]
Has been #613 added.
However, a default language should be set. Used when the file cannot be found.

**Comment by fanshu-520** [comment]
the problem still exist
![O(P {PNI62DQV6FOMQ8QS99](https://user-images.githubusercontent.com/79776977/167242341-9fdf300e-86e9-439a-8195-ef1a76093618.png)
