### ISSUE TITLE
The seat of life for the HuTao

### ISSUE THREAD

**Issue by a267764** [Melledy/Grasscutter#620]
HuTao six life effect on her life value is less than 25% is not triggered.

**Comment by gentlespoon** [comment]
Chinglish correction: he is talking about Hu Tao constellation 6

**Comment by KiminaNatsuki** [comment]
Oh well, these are all known issues, they are not implemented yet.

**Comment by lunaticwhat** [comment]
known issues about charaters cons. There are already alot of issues opened about this problem. Closed to clean up the workspace.
