### ISSUE TITLE
Suggestion: display the name of the item instead of the item ID

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#622]
If you can, can you change the feedback after using the instruction from the item ID to the item name
![1](https://user-images.githubusercontent.com/89347877/167245992-c5bb77b8-c60a-4c12-b649-b3504895589d.png)
For example: replace 223 with 纠缠之缘

**Comment by mengguyi** [comment]
我认为这是一个不错的提议，但是原神是一个多语言的游戏。这样做就必须让翻译做的比较好。否则服务端的反馈就可能会比较奇怪
I think this is a good proposal, but Genshin is a multilingual game. In this way, we must make the translation better. Otherwise, the feedback from the server may be strange
(Baidu Translate)

**Comment by alt3ri** [comment]
I'll remember this and make it come true

**Comment by yuexuanblog** [comment]
> I'll remember this and make it come true

That's wonderful

**Comment by Sonnyup** [comment]
> I'll remember this and make it come true

That's wonderful 😁👍
