### ISSUE TITLE
[504

### ISSUE THREAD

**Issue by ghs456** [Melledy/Grasscutter#627]
[504

_Originally posted by @ghs456 in https://github.com/Grasscutters/Grasscutter/issues/626#issuecomment-1120199305_

**Comment by SunshineVX** [comment]
HERE IS NOT THE PLACE WHERE YOU CAN ASK SUCH QUESTIONS. Or you have to provide detailed information.

**Comment by lunaticwhat** [comment]
Please ask for more info in our Discord. Closed to cleanup the workspace.
