### ISSUE TITLE
(Newest dev) /pos command not working properly

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#629]
![image](https://user-images.githubusercontent.com/104761702/167256372-9ff9978a-aea2-490d-8653-f75d420df6e0.png)

Console tells me this:

![image](https://user-images.githubusercontent.com/104761702/167256369-c1288b15-e518-40cf-aa91-cc7c437f97be.png)

The command works when downgrading to an older build. The problem is also not with my build, as I have re-downloaded the code and rebuilt a couple of times.

**Comment by zhaodice** [comment]
command what you have sent should be provided

**Comment by AZthemute** [comment]
> command what you have sent should be provided

I sent /pos

**Comment by zhaodice** [comment]
> > command what you have sent should be provided
> 
> I sent /pos

`/pos` only? I think it need some params specified

**Comment by AZthemute** [comment]
> > > command what you have sent should be provided
> > 
> > 
> > I sent /pos
> 
> `/pos` only? I think it need some params specified

No, it doesn't. /pos with no paramaters gives your own position.

**Comment by zhaodice** [comment]
you're right , this is a bug and I tried fix it.
