### ISSUE TITLE
Give artifact command broken

### ISSUE THREAD

**Issue by honeyed-lemons** [Melledy/Grasscutter#632]
After entering command, it gives the response as if i didnt enter anything. Probably due to the language update
![image](https://user-images.githubusercontent.com/53302665/167258206-1c609397-4257-4c26-807c-8147b18bef09.png)

**Comment by AZthemute** [comment]
Not getting this problem. Try rebuilding or redownloading the code.

**Comment by honeyed-lemons** [comment]
OH shit youre right, sorry for the trouble
