### ISSUE TITLE
Feedback 、survey、characrerArchive、notices，Cannot open and close

### ISSUE THREAD

**Issue by lopelem** [Melledy/Grasscutter#633]
In the interface：Feedback 、survey、characrerArchive、notices，Cannot open and close。
原神界面中，反馈，问卷，公告，角色图签不能打开也不能关闭。（建议当前界面都能打开和关闭，可以先没有功能，但需要能打开和关闭）
任务界面有些不能关闭会卡住客户端）

bug和优化
1.靠近神像不能缓慢恢复血量（bug）
2.退出游戏重新进入游戏，玩家的当前队伍的血量会全部恢复（bug）（血量正常是需要玩家自己去恢复的。靠吃食物或者靠神像。）
3.角色冲破后，突破的奖励不能领取。（需要修复）
4.当前在水中待机的时候会恢复体力。（bug）正常来说是不能恢复体力的，在水中和空中都会持续消耗体力。
5.玩家最好能够根据神像接触自动绑定新的团队死亡后的恢复点，现在死亡后会回到初始点。（建议）

**Comment by CCasusensa** [comment]
please use english

**Comment by MapleNe** [comment]
不能用就是没写没实现

**Comment by lunaticwhat** [comment]
they are known issues because most of them aren't implemented yet.
