### ISSUE TITLE
[Latest dev] /givechar does not work

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#635]
![image](https://user-images.githubusercontent.com/104761702/167260274-522cbf7d-a657-48e5-9f32-565920bcc633.png)

Message that I haven't finished typing is the command I inputted. Tried with different characters and levels... same issue

No, this error is not caused by an invalid ID. The server says this when you type an invalid ID:
![image](https://user-images.githubusercontent.com/104761702/167260478-5204602b-0587-4d64-a010-2057f3e124e8.png)

**Comment by zhaodice** [comment]
you're right , this is a bug and I tried fix it.

**Comment by minhngoc25a** [comment]
`/help` will usually show you a command list and also their syntax. The syntax of `givechar` is `/givechar <UID> <ID>`. You didn't put in your UID, and the dev branch hasn't had the system message for syntax error yet.
