### ISSUE TITLE
gradlew jar error

### ISSUE THREAD

**Issue by hello0word** [Melledy/Grasscutter#641]
Build file 'C:\Users\X\Downloads\Grasscutter-development\build.gradle' line: 108

* What went wrong:
Could not determine the dependencies of task ':jar'.
> Could not resolve all dependencies for configuration ':runtimeClasspath'.
   > Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven(http://maven.aliyun.com/nexus/content/repositories/jcenter)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details.

**Comment by lunaticwhat** [comment]
Java SE Development Kit hasn't setup correctly. Please check your JDK installation and its variable PATH
