### ISSUE TITLE
账号验证失败 错误码:12-4301

### ISSUE THREAD

**Issue by 13187949038** [Melledy/Grasscutter#642]
原神国际版客户端已登录成功，在进入世界时提示“账号验证失败，错误码：12-4301”，目前代理方式我用的是改hosts，用mitm也是一样的结果

版本：v1.0.0

Thanks

**Comment by hash070** [comment]
Please use English to describe your issue for the reason that the developers in this project are mainly English speakers.
可以去Discord中文讨论区问问是怎么回事，还有，建议使用dev分支的代码和最新的构建

**Comment by SleepyAsh0191** [comment]
请关闭 issue ，并将问题询问至 Discord.
Plz close the issue, and go to our Discord server.

**Comment by lunaticwhat** [comment]
commonly known issue. Please use our Discord we have CN support channel.
众所周知的问题。请使用我们的 Discord，我们有 CN 支持频道。
