### ISSUE TITLE
(Latest dev) /scene command does not output result correctly

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#648]
### This only happens when switching to a new scene. (here, I was in scene 1 before switching)
![image](https://user-images.githubusercontent.com/104761702/167268637-713f27be-da2c-4e9b-944e-ecc4bfa341dd.png)

### This one happens when you switch to a non-existent scene.
![image](https://user-images.githubusercontent.com/104761702/167268653-f215768e-be1c-4945-ac72-dbdfa0368a9b.png)

Switching to a scene you are already in and "Invalid arguments" both work correctly.

**Comment by Spellfox** [comment]
update your files, it's working normally
![Screenshot_41](https://user-images.githubusercontent.com/99099873/167269678-98295b8e-47df-4e81-bc23-40a967dc55eb.png)
