### ISSUE TITLE
Problems found when playing online

### ISSUE THREAD

**Issue by Cardgodk** [Melledy/Grasscutter#668]
**Describe the bug**
1. There will be obvious Caton action when watching the other party release skills
2. When both sides attack the monster together, the monster and the other side will be in the wrong position
3. You can't play in the dungeon together

**Which branch did you use?**
Development branch

The above tests have ruled out the cause of server delay

**Comment by lunaticwhat** [comment]
yeah this is why coop is still broken as we've said in the GC introducing. Thanks for more bugs reporting.

**Comment by Cardgodk** [comment]
> 

Do you know where the files about character energy and dungeon fall are? Although I'm a novice, I want to try

**Comment by Cardgodk** [comment]
> 是的，这就是为什么我们在GC介绍中所说的那样，鸡舍仍然破碎。感谢您的更多错误报告。

Do you know where the files about character energy and dungeon fall are? Although I'm a novice, I want to try

**Comment by lunaticwhat** [comment]
> > 是的，这就是为什么我们在GC介绍中所说的那样，鸡舍仍然破碎。感谢您的更多错误报告。
> 
> Do you know where the files about character energy and dungeon fall are? Although I'm a novice, I want to try

You can visit our [Discord](https://discord.gg/T5vZU6UyeG) for more infomation, we have a CN speaking channel here for Chinese people !

**Comment by Cardgodk** [comment]
> > > 是的，这就是为什么我们在GC介绍中所说的那样，鸡舍仍然破碎。感谢您的更多错误报告。
> > 
> > 
> > 你知道关于角色能量和地牢坠落的文件在哪里吗？虽然我是新手，但我想尝试
> 
> 您可以访问我们的[Discord](https://discord.gg/T5vZU6UyeG)以获取更多信息，我们在这里为中国人提供CN口语频道！

好的 十分感谢

**Comment by lunaticwhat** [comment]
好没问题。我将关闭此问题以清理工作区。
