### ISSUE TITLE
[Issue] Kokomi cant heal

### ISSUE THREAD

**Issue by KanNguyenKiet** [Melledy/Grasscutter#675]
**Did you look for other closed issues that have the same problem?**

No

**Describe the issue**

Kokomi cant heal teamate when use elemental and burst skill

**Which branch did you use?**

stable

**Comment by memetrollsXD** [comment]
Not implemented and a work in progress. Just like zhongli shield healing and other suggestions

**Comment by lunaticwhat** [comment]
Already discussed at closed issues #494 #469 #458 and #432. Healing is not implemented yet.

**Comment by KingRainbow44** [comment]
resolved in https://github.com/Grasscutters/Grasscutter/pull/2166
