### ISSUE TITLE
[Issue] 启动服务错误

### ISSUE THREAD

**Issue by ACode-Nie** [Melledy/Grasscutter#678]
![image](https://user-images.githubusercontent.com/82274375/167291969-d286851d-26e6-42a8-9824-53b69102cec7.png)

![image](https://user-images.githubusercontent.com/82274375/167291980-53107910-1ad8-45a0-8bd5-29f20ef5c60f.png)

很多类似错误，然后游戏会在选择主角命名后卡死，报错
![image](https://user-images.githubusercontent.com/82274375/167292019-191a2c2e-b970-4fb1-9cc3-4bd5ee11a66c.png)

**Comment by ACode-Nie** [comment]
这些文件我能确定在resources文件夹下存在

**Comment by SunshineVX** [comment]
建议重新下载resources

**Comment by ACode-Nie** [comment]
> 建议重新下载resources
https://github.com/Dimbreath/GenshinData
https://github.com/zhsitao/gi-bin-output
看教程是这两个仓库的文件，gi-bin-output 提供 BinOutput 文件，GenshinData 提供 ExcelBinOutput、Readable、Subtitle、TextMap 文件

**Comment by ACode-Nie** [comment]
也许我用的是国服客户端2.6版本，而[gi-bin-output 只有 2.5.52 导致的？

**Comment by Mateoust** [comment]
Try from Download Resources from [Koko-boya/Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

**Comment by hash070** [comment]
Obviously,your resources file is not correct.
The resources in this repositories works fine for the newest grasscutter server.
推荐这个仓库的资源文件
[Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

**Comment by ACode-Nie** [comment]
成功了，感谢各位的帮助
