### ISSUE TITLE
Can not connect on iPhone with proxy

### ISSUE THREAD

**Issue by iBobbyTS** [Melledy/Grasscutter#681]
I used the 1.1.0 release. It is deployed on macOS 12.4. The server starts as usual. 
<img width="1344" alt="Screen Shot 2022-05-08 at 18 58 11" src="https://user-images.githubusercontent.com/46138297/167293039-6cb52648-936c-4955-9d61-d99e0417b68d.png">
The proxy command is like this: 
`mitmdump -s proxy.py --ssl-insecure --set block_global=false —listen-port 8080`
<img width="1344" alt="Screen Shot 2022-05-08 at 19 04 24" src="https://user-images.githubusercontent.com/46138297/167293296-227fe1e2-8b29-4fe7-b305-6f9c156f0dd4.png">
I used iOS system proxy to route the game to my computer, I am able to login to the account though the server. 
![plgct](https://user-images.githubusercontent.com/46138297/167293225-460bd752-7774-46d3-9cba-e9701d1dade1.jpg)
But unable to really enter the game, it says connection lost. 
![IMG_0CBE8FC7C018-1](https://user-images.githubusercontent.com/46138297/167293251-ccf8982c-60b4-4c1c-9ecf-9b79da8d283a.jpeg)
I can't find where's the problem, can anyone help me please.

**Comment by lunaticwhat** [comment]
dispatch server worked but the game server wasn't. Check your proxy setup

**Comment by wmn1525** [comment]
config.json 里面的publicip没改
