### ISSUE TITLE
Golden Apple Archipelago map is not solid.

### ISSUE THREAD

**Issue by AZthemute** [Melledy/Grasscutter#685]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the issue**

The Golden Apple Archipelago map is almost completely not solid. I say almost because the water and one "layer" of the map is solid, see video attached if my explanation is not clear.

**Which branch did you use?**

Development, but this has been happening since 1.0 at least (that's the first version I tried)

**Screenshots**

https://cdn.discordapp.com/attachments/748188072826372299/972828448705884210/2022-05-08_12-37-04.mp4 Click here to download the video.

**Additional context**

None.

**Comment by Birdulon** [comment]
The client doesn't have the collision geometry for this map outside of version 1.6, it's not really in the scope of this project.

**Comment by AZthemute** [comment]
> The client doesn't have the collision geometry for this map outside of version 1.6, it's not really in the scope of this project.

Would it be possible at all to re-implement it, client or server mod?

**Comment by Birdulon** [comment]
> > The client doesn't have the collision geometry for this map outside of version 1.6, it's not really in the scope of this project.
> 
> Would it be possible at all to re-implement it, client or server mod?

As a client mod yes. The server doesn't really care either way.

**Comment by AZthemute** [comment]
> > > The client doesn't have the collision geometry for this map outside of version 1.6, it's not really in the scope of this project.
> > 
> > 
> > Would it be possible at all to re-implement it, client or server mod?
> 
> As a client mod yes. The server doesn't really care either way.

Ah, okay. Maybe some day.
