### ISSUE TITLE
[Issue] Can't update the client if I put the server remotely

### ISSUE THREAD

**Issue by stevenli510** [Melledy/Grasscutter#687]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**
If I put the server and client on the same machine, it works like a charm.
But if I put the server remotely, the login will be stuck during updating the client..
Error code "4206" returned by the client.
No errors on the server. I tried to capture the fiddler and network trace during both working and non-working scenarios, didn't find anything different.

The only difference I noticed is the server console output, for details, please check the screenshot below.

Anyone also tried to put the server remotely and made it work?

**Which branch did you use?**

Same issue applies to both stable and development branch.

**Screenshots**

In working scenario, I found there are 2 connections after the login:
<img width="442" alt="working" src="https://user-images.githubusercontent.com/54136985/167297156-049cf987-0df0-4ffc-a431-1421022fb4c9.PNG">

In non-working scenario, nothing after the initial login:
<img width="478" alt="GSIP_Nonworking" src="https://user-images.githubusercontent.com/54136985/167297247-4eba44ec-d770-48f4-bbf0-6ff878678997.png">

The client returned the error like below:

<img width="468" alt="Noworking_client" src="https://user-images.githubusercontent.com/54136985/167297306-fd566cfe-3595-4a08-9aed-5e676dfafec3.PNG">

**Additional context**

**Comment by lunaticwhat** [comment]
commonly proxy issue. you can visit our discord for more help!
