### ISSUE TITLE
[Bug] Stamina does not decrease while conducting charged attack

### ISSUE THREAD

**Issue by Yoimiya49** [Melledy/Grasscutter#693]
**Describe the bug**
Stamina does not decrease while conducting charged attack

**Which branch did you use?**
Stable branch

**Screenshots**

**Additional context**
If the stamina has decreased by running and then conduct charged attack, the stamina bar will maintain at the value when the character stopped running.

**Comment by lunaticwhat** [comment]
There are alot of issues about stamina. Thank you for reporting the bug!
