### ISSUE TITLE
[Issue] The game is fine, but the proxy has a problem/游戏端正常但是代理出现问题

### ISSUE THREAD

**Issue by ZNFY** [Melledy/Grasscutter#694]
**Did you look for other closed issues that have the same problem?**
<Not>

**Describe the issue**
<The operating environment is Alibaba Cloud Windows Server 2019, the game side is successfully started, but there is a problem with the proxy, the login interface of the private server can be displayed, but after clicking login, the game will not enter the game and stay on the login interface. 
The corresponding port has been opened (443, 22102, and the port of the proxy), and it has been successfully run under the same conditions as the local virtual machine.
运行环境为阿里云windows server2019，游戏端成功启动，但是代理出现问题，能显示私服的登陆界面，但在点击登陆后不会进入游戏而停留在登陆界面。
对应端口已经打开（443，22102，以及代理的端口），在本地虚拟机同等条件下已经成功运行过。>

**Which branch did you use?**
<Stable branch>

**Screenshots**
<
![image](https://user-images.githubusercontent.com/29276969/167299513-8beb8497-fac6-4f08-a0b6-34f3d6d391f3.png)
![image](https://user-images.githubusercontent.com/29276969/167299539-d1dc0195-1d08-4428-a619-c421c298797e.png)
![image](https://user-images.githubusercontent.com/29276969/167299618-11ab37e2-5c4e-4251-ac8f-ee0076d747cf.png)
>

**Additional context**
<Hope to hear back, thank you very much!/希望得到大佬解答，非常感谢！>

**Comment by GoJasen** [comment]
我也是阿里云，端口全开但是就是一直网络错误，腾讯云却可以运行。我也不知道什么原因，知道了踢我。
I am also Alibaba Cloud, the ports are fully open, but there is always a network error, but Tencent Cloud can run. I don't know what the reason is, but know to kick me.

**Comment by WRS-MMM** [comment]
阿里云好像把某些后缀ban掉了，百度智能云某些区域可以，某些区域不行，所以建议选一个没ban掉的服务器部署

**Comment by GoJasen** [comment]
> 阿里云好像把某些后缀ban掉了，百度智能云某些区域可以，某些区域不行，所以建议选一个没ban掉的服务器部署

没有解决办法了是吗，只有把服务器退掉，重新再部署一个新的对吗。

**Comment by WRS-MMM** [comment]
> > 阿里云好像把某些后缀ban掉了，百度智能云某些区域可以，某些区域不行，所以建议选一个没ban掉的服务器部署
> 
> 
> 
> 没有解决办法了是吗，只有把服务器退掉，重新再部署一个新的对吗。

**Comment by WRS-MMM** [comment]
> > 阿里云好像把某些后缀ban掉了，百度智能云某些区域可以，某些区域不行，所以建议选一个没ban掉的服务器部署
> 
> 
> 
> 没有解决办法了是吗，只有把服务器退掉，重新再部署一个新的对吗。
目前好像是这样，因为我在百度云上海，北京，区域，同样方法部署都是爆win64那个错误，而在广州区域部署，没有任何问题，更新再部署也没啥问题，并成功部署了两台，目前我看能部署的大部分都是腾讯云，而不能部署，被ban后缀的大部分是阿里云和百度云

**Comment by victor-lcr** [comment]
我也遇到了一样的问题，不过通过一个易语言程序在windows上能正常游戏了。
我不知道这是什么原因导致的，同样也是阿里云的windows server
你可以去尝试一下[https://victor-cr.lanzouw.com/i340t04k2are]

**Comment by ZNFY** [comment]
> 我也遇到了一样的问题，不过通过一个易语言程序在windows上能正常游戏了。 我不知道这是什么原因导致的，同样也是阿里云的windows server 你可以去尝试一下[https://victor-cr.lanzouw.com/i340t04k2are]

请问是要把这个程序运行在服务器上面吗？

**Comment by victor-lcr** [comment]
这个程序在客户端运行，并且客户端还要安装服务端证书

**Comment by ZNFY** [comment]
> 这个程序在客户端运行，并且客户端还要安装服务端证书

好的，我这就去试试，谢谢你！

**Comment by ZNFY** [comment]
> 这个程序在客户端运行，并且客户端还要安装服务端证书

你好！这个程序起到了作用！游戏正常运行了，再次感谢你

**Comment by WRS-MMM** [comment]
我有一个问题，你发的那个软件为什么无论写哪一个ip，代理都是生成两个127.0.0.1呢，请问该软件还有什么其他的的要求吗？

**Comment by WRS-MMM** [comment]
抱歉，这可能单纯是百度云服务器问题，其他服务器可以参考这个方案解决，百度云服务器用此方法暂时不能解决

**Comment by GoJasen** [comment]
> 我也遇到了一样的问题，不过通过一个易语言程序在windows上能正常游戏了。 我不知道这是什么原因导致的，同样也是阿里云的windows server 你可以去尝试一下[https://victor-cr.lanzouw.com/i340t04k2are]

安卓上会有同样的代理程序吗？
Will there be the same agent on Android?

**Comment by victor-lcr** [comment]
> 我有一个问题，你发的那个软件为什么无论写哪一个ip，代理都是生成两个127.0.0.1呢，请问该软件还有什么其他的的要求吗？

这个软件类似于是在客户端运行代理程序（代理程序的ip肯定是127.0.0.1，填写的ip是指向服务器的），不过使用了Fiddler的内核，让代理的过程变得简单。

**Comment by victor-lcr** [comment]
> > 我也遇到了一样的问题，不过通过一个易语言程序在windows上能正常游戏了。 我不知道这是什么原因导致的，同样也是阿里云的windows server 你可以去尝试一下[https://victor-cr.lanzouw.com/i340t04k2are]
> 
> 安卓上会有同样的代理程序吗？ Will there be the same agent on Android?

非常遗憾，Android设备上没有这样的软件，你可以参考一些教程来使Android能正常游戏.
