### ISSUE TITLE
[Issue] Build appears Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

### ISSUE THREAD

**Issue by clover1420** [Melledy/Grasscutter#695]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

Build appears Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
**Which branch did you use?**

Development branch
**Screenshots**

**Additional context**

**Comment by clover1420** [comment]
> **您是否查找了具有相同问题的其他已关闭问题？**
> 
> **描述问题**
> Build appears Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
> **您使用了哪个分支？**
> development
> **截图**
> 
> **其他上下文**

**Comment by lunaticwhat** [comment]
this issue can be ignored if the build is still successfully
