### ISSUE TITLE
[Bug] Spiral Abyss 5th floor

### ISSUE THREAD

**Issue by xmgnew** [Melledy/Grasscutter#698]
**In the latest dev version, the spiral abyss progress are saved, so I want to beat until floor 8 to access floor 9 and above. But when I got to floor 5, the mission says "kill 20 monsters" instead of "kill all the monster in x minute", and I got stuck after defeating all of them.**

Note: I'm using the latest dev (build#99) and I downloaded the newest "data" and "proto" file.

**Here is the video link showing the bug: https://drive.google.com/file/d/1A6tMUNfdyyXaTSCOTMA4heJQquayNbdH/view?usp=sharing **

**Comment by xmgnew** [comment]
Note: I'm using the latest dev (#99) and I downloaded the newest "data" and "proto" file.

**Comment by lunaticwhat** [comment]
should be data issues. thanks for letting us know the bug !

**Comment by suyanoyata** [comment]
how'd you get in abyss? when i try to enter there's no rooms (using also dev build)

upd: nevermind i figured out by myself

**Comment by Spellfox** [comment]
I had the same problem, only here the monster count doesn't go beyond 0/2

**Comment by fanshu-520** [comment]
same problem

**Comment by NeoMika** [comment]
same problem

**Comment by Akka0** [comment]
Try the PR #718 may fix some but still in dev...

**Comment by xmgnew** [comment]
Loot at issue #719 , the new dev (build#103) fixed spiral abyss 5th floor, but some new bugs are coming out
