### ISSUE TITLE
[Bug] Stamina will not decrease or recover when rapidly jumping

### ISSUE THREAD

**Issue by xmgnew** [Melledy/Grasscutter#699]
**After sprinting, then let the character keep jumping, the stamina will not decrease or recover. This happens the same when the character is both sprinting and jumping, the stamina will not decrease. **

**This video shows the bug (I'm using the latest dev version): https://drive.google.com/file/d/1ayQuthMra7jdu5Gpx5Qj5MOHYzd9vwHC/view?usp=sharing**

**Comment by lunaticwhat** [comment]
stamina issues are well-known to be bugging. We are still working to properly implementing stamina.
