### ISSUE TITLE
[Bug] Hu Tao E skill not decrease her health, and all healers can't heal

### ISSUE THREAD

**Issue by Arsyonas** [Melledy/Grasscutter#707]
When im using Hu Tao her E is not decrease her health at all, and for all healers cannot heal.. like Kokomi, Bennet, and Barbara

**Comment by 6ixfalls** [comment]
I believe those features aren't implemented yet. However, healing seems to work on the development build.

**Comment by lunaticwhat** [comment]
all heal related functions are not properly implemented yet. 
already discussed in #675 #494 #469 #458 #342 so we will close this issue !
