### ISSUE TITLE
No physical exertion

### ISSUE THREAD

**Issue by yuexuanblog** [Melledy/Grasscutter#714]
Maybe we can consider increasing unlimited physical strength to godmode

**Comment by SunshineVX** [comment]
good

**Comment by gentlespoon** [comment]
It will be considered when the base stamina system is finished.

**Comment by tiantian520tt** [comment]
Yeah,I think so, too

**Comment by gentlespoon** [comment]
For now if you want infinite stamina just turn it off in the config.

**Comment by 1-lavender-1** [comment]
> For now if you want infinite stamina just turn it off in the config.

I tried to switch "OpenStamina" from "true" to "false" in config.json, but I found that it still costs stamina and never restore it. I am not sure whether it is a bug.

**Comment by gentlespoon** [comment]
It is indeed a bug. https://github.com/Grasscutters/Grasscutter/pull/728/
