### ISSUE TITLE
[Feature Request] I think we can add quests and stories to spice up the game

### ISSUE THREAD

**Issue by zenithyoqi** [Melledy/Grasscutter#715]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zenithyoqi** [comment]
I think we can add quests and stories to spice up the game

**Comment by tiantian520tt** [comment]
Thank you for your reply! Many players have the same wish as you. However, the task and plot will increase the development difficulty of developers. Please rest assured that developers will complete the development one day! Thank them!

**Comment by zenithyoqi** [comment]
> 

yes，you are right

**Comment by lunaticwhat** [comment]
quests are not easy to add into the game. Devs are working hard on it stay tune !

**Comment by zenithyoqi** [comment]
> 任务不容易添加到游戏中。开发人员正在努力保持调谐！

Well, thank you very much for your efforts
