### ISSUE TITLE
[Issue] Golden Apple Archipelago no collision

### ISSUE THREAD

**Issue by suyanoyata** [Melledy/Grasscutter#716]
**Describe the issue**
When I get in Golden Apple Archipelago there's no collision so I am wondering can contributors do something about it? I mean terrain has collision (I can walk on them) but mountains do not (I fall in them, can go through them)

**Which branch did you use?**
dev and stable

**Screenshots**
![image](https://user-images.githubusercontent.com/90862425/167347483-4981946a-2023-4f31-94b5-22af61261959.png)
![image](https://user-images.githubusercontent.com/90862425/167347575-4a1f7257-067e-4363-a927-34cb3005ce70.png)

**Additional context**
I know that event ended almost year ago and it's impossible to access it without chaning scene so I am just asking

**Comment by Birdulon** [comment]
See #685 
Please keyword search for results including closed issues before creating an issue in the future.
