### ISSUE TITLE
There is a problem with the secret

### ISSUE THREAD

**Issue by Oweik** [Melledy/Grasscutter#724]
I can enter the secret realm, but after entering, I am not in the correct position, but in a place outside the map, in a state of falling
![屏幕截图 2022-05-09 165735](https://user-images.githubusercontent.com/100178606/167377121-7f08e77f-9771-4027-b8cb-b3450ff0358b.png)
.

**Comment by SunshineVX** [comment]
So all dungeons have this problem?If so, you may need to add Scripts under the resources folder.

**Comment by SunshineVX** [comment]
You may use this. [Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

**Comment by Oweik** [comment]
> 你可以用这个。[Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

Thanks, solved it after adopting your suggestion
