### ISSUE TITLE
当前界面的一些问题

### ISSUE THREAD

**Issue by lopelem** [Melledy/Grasscutter#725]
1.编辑资料——名片不能保存。
![image](https://user-images.githubusercontent.com/37797437/167382762-091cf61d-f84f-4a69-985e-aef94d056110.png)
2.任务界面中的传说任务按钮点击后，不能关闭界面。
![image](https://user-images.githubusercontent.com/37797437/167383126-d0eacbd1-671c-44e1-b7e3-4220954d30b9.png)
![image](https://user-images.githubusercontent.com/37797437/167383236-734a0b93-8855-40f0-92e4-18317255d758.png)
3.点击公告按钮不能打开
![image](https://user-images.githubusercontent.com/37797437/167383816-e51920a1-1bd0-4bf2-a95b-b70b5cc9a736.png)
4.反馈和问卷点击后提示服务器内部错误
![image](https://user-images.githubusercontent.com/37797437/167383816-e51920a1-1bd0-4bf2-a95b-b70b5cc9a736.png)

**Comment by lopelem** [comment]
![image](https://user-images.githubusercontent.com/37797437/167384097-0c9c4c2c-54d1-4e7f-99c8-cda42ba06c2f.png)
公告加载失败

**Comment by lopelem** [comment]
![image](https://user-images.githubusercontent.com/37797437/167384473-99334f71-69e3-450d-82f0-d21c3ee4fc1a.png)
角色丽莎的血量为0/0

**Comment by yuexuanblog** [comment]
English recommended

**Comment by Yoimiya49** [comment]
> English recommended

Translation：

1. Namecard in profile can’t be changed.

2. When entering the entrusted mission page, the close button can’t be interacted.

3. Notices page can’t be opened.（"Failed to load notices"）

4. It shows "Internal server error" when click Feedback or survey button.

**Comment by lunaticwhat** [comment]
Namecard can be change directly in mongodb

Alot of functions are not implemented yet, You can visit our [Discord server](https://discord.gg/T5vZU6UyeG) for more info.
