### ISSUE TITLE
[Issue]   How to add 5 star artifact? 

### ISSUE THREAD

**Issue by mengdalida** [Melledy/Grasscutter#734]
I use give command to add artifacts but it's default 3 stars.
I am using the command **give @uid 71345 1 20** to add artifacts .

About Advanture rank, I haven't found any command to add

**Comment by don1103** [comment]
change3to5，71544plz

**Comment by mengdalida** [comment]
@don1103  thanks， I find level 5 has different name.

**Comment by lunaticwhat** [comment]
You can visit our [Discord server](https://discord.gg/T5vZU6UyeG) for more info about commands.
