### ISSUE TITLE
[Bug] ayaka and mona dont lose stamina when they sprint

### ISSUE THREAD

**Issue by XihuanAL** [Melledy/Grasscutter#737]
**Describe the bug**

Perhaps because of their unique sprint, they will not continue to consume stamina during the sprint

**Which branch did you use?**

Stable branch

**Comment by Yoimiya49** [comment]
The same if Kokomi sprint on the water when press Q. Maybe the analogous bug in #693

**Comment by gentlespoon** [comment]
Ayaka and Mona's talent move has been implemented in #775.

Charged attacks and Kokomi's elemental burst will be implemented later this week.

**Comment by lunaticwhat** [comment]
Thank you @gentlespoon
