### ISSUE TITLE
[Feature Request]  suggest to support "nutrition bags"

### ISSUE THREAD

**Issue by mengdalida** [Melledy/Grasscutter#738]
Player can add hp by command "z"

**Comment by Yoimiya49** [comment]
Maybe the current version cannot use those items like nutrition bag or camera.

**Comment by AZthemute** [comment]
> Maybe the current version cannot use those items like nutrition bag or camera.

All gadgets are non-functional as far as I know, correct me if I'm wrong as there have been updates since I last played.

**Comment by Yoimiya49** [comment]
> > Maybe the current version cannot use those items like nutrition bag or camera.
> 
> All gadgets are non-functional as far as I know, correct me if I'm wrong as there have been updates since I last played.

Yes, it keeps in release 1.1.0 at least.

**Comment by lunaticwhat** [comment]
not a bad idea but this kind of concept is not easy to implement because it may need to modify the client
