### ISSUE TITLE
[Bug] Monster spawn infinite in town

### ISSUE THREAD

**Issue by mrcyclo** [Melledy/Grasscutter#745]
The latest dev

Floor 6 room 3. If I kill monster, it re-spawn immediately and I will trap in this level.

Video here:
https://drive.google.com/file/d/1T1pRh1Aa_U3SkqIWKn7vlQl7z9q68GPy/view?usp=sharing

Sorry, my English so bad.

**Comment by Akka0** [comment]
Try my fix in #746

**Comment by xmgnew** [comment]
> Try my fix in #746
In the newest dev, I believe that the monster spawn have been fixed, but there are still some issues in floor 9 or above. There is a chance to stuck in the floor, with no monsters spawning or jumping to next level.
