### ISSUE TITLE
[Issue]Floor 9 chamber 1 jumping to Floor 9 chamber 2 ignored team 2

### ISSUE THREAD

**Issue by Spellfox** [Melledy/Grasscutter#749]
I'm using the latest version of the emulator and build #609, when making floor 9 chamber 1 team 1, the team 2 part is ignored and goes straight to floor 9 chamber 2 team 1, and the monsters have infinite spawn as shown in the video, when using build #615 that is in Pull Request, the counter gets to 16/16, but the black loading screen goes into loop making the game crash...

https://www.youtube.com/watch?v=yR3H1a_bggY
[Emulator log.log](https://github.com/Grasscutters/Grasscutter/files/8654334/Emulator.log.log)

**Comment by fkc4** [comment]
My Holy Relic has no affixes, oh my friend ! help me!

**Comment by sunboy0617** [comment]
Same problem with you!

**Comment by JrantKing** [comment]
Same problem

**Comment by lunaticwhat** [comment]
Abyss issue related. Thanks for the info we will look into this.
