### ISSUE TITLE
[Issue] NullPointerException

### ISSUE THREAD

**Issue by Ranger-ran** [Melledy/Grasscutter#752]
**Describe the bug**

When I run the grasscutter.jar, there is a NullPointerException. I tried to use two grasscutter.jar, one is downloaded from [actions](https://nightly.link/Grasscutters/Grasscutter/workflows/build/stable/Grasscutter.zip), another is builded by myself. Both of them have the same problem.

**Which branch did you use?**

Stable branch

**Screenshots**

![image](https://user-images.githubusercontent.com/38161300/167491734-d32a96cf-734b-4b1b-9485-3bebc0e66d32.png)
![image](https://user-images.githubusercontent.com/38161300/167495487-2469add6-152a-45da-b3ed-3a591d980b61.png)

**Additional context**

my computer CPU is AMD.

**Comment by fkc4** [comment]
My Holy Relic has no affixes, oh my friend ! help me!

**Comment by nigpo** [comment]
Change your system language to English or Chinese for temporary fix.

**Comment by fkc4** [comment]
> 将系统语言更改为英语或中文以进行临时修复。
My friend, I can't

**Comment by Ranger-ran** [comment]
> Change your system language to English or Chinese for temporary fix.

thank you！I change the system language to English，The program runs normally，even if I change the system language to Chinese now. I don't know what happened.
