### ISSUE TITLE
SPRINT reduce stamina when "OpenStamina":false

### ISSUE THREAD

**Issue by Rambin** [Melledy/Grasscutter#755]
https://github.com/Grasscutters/Grasscutter/blob/f4f2cf6a96ff5ae40f03b0c7290f5127a7f11c63/src/main/java/emu/grasscutter/game/managers/StaminaManager/StaminaManager.java#L261
SPRINT reduce stamina when "OpenStamina":false
Missing check of config.OpenStamina here

**Comment by gentlespoon** [comment]
Fixed in #728 and #769.
