### ISSUE TITLE
整理了以下一键获取90级角色+6命星+极限圣遗物+90级武器的文档，希望能够帮助到大家

### ISSUE THREAD

**Issue by FoehnMLK** [Melledy/Grasscutter#756]
[一键指令服务端版.txt](https://github.com/Grasscutters/Grasscutter/files/8656476/default.txt)
[一键指令客户端版.txt](https://github.com/Grasscutters/Grasscutter/files/8656477/default.txt)

**Comment by liou1xiang2yu** [comment]
多谢

**Comment by Axin02** [comment]
谢谢

**Comment by KiminaNatsuki** [comment]
requesting to close this "issue", since this it's just commands about getting c6 level 90 chara / artifacts / level 90 weapons and not a issue

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
