### ISSUE TITLE
[Issue]深渊无法多人进入/The dungeon cannot have many people

### ISSUE THREAD

**Issue by keqingyyds** [Melledy/Grasscutter#757]
深渊只要有人进去了其他人就进不去，而且还有可能被随机传送到1/1
If someone enters the dungeon, others cannot enter，I'm using translation software. I can't speak English

**Comment by akbaryahya** [comment]
I also have the same problem it seems because the cause of the getsession is null, so when an error occurs it will make other people teleport to the dungeon and people who want to go to the dungeon can't enter because those who have teleported have already entered

**Comment by NeoMika** [comment]
官服深渊不是只能单人打吗？

**Comment by keqingyyds** [comment]
> 官服深渊不是只能单人打吗？

是说没有办法进多个人，没办法开始，懂么

**Comment by xmgnew** [comment]
官服在多人联机模式下也不能一起进深渊吧？只有房主能进。这个可能有点难修复

**Comment by keqingyyds** [comment]
> 官服在多人联机模式下也不能一起进深渊吧？只有房主能进。这个可能有点难修复

…你就没听明白，全服务器只有一个人能进深渊，懂了么？

**Comment by xmgnew** [comment]
> …你就没听明白，全服务器只有一个人能进深渊，懂了么？

我确实没理解，“全服务器只有一个人能进深渊”是指，例如一个服务器里有5个人，那么一个人进了深渊后，剩下的四个人都进不去深渊么？

**Comment by keqingyyds** [comment]
> > …你就没听明白，全服务器只有一个人能进深渊，懂了么？
> 
> 我确实没理解，“全服务器只有一个人能进深渊”是指，例如一个服务器里有5个人，那么一个人进了深渊后，剩下的四个人都进不去深渊么？



> > …你就没听明白，全服务器只有一个人能进深渊，懂了么？
> 
> 我确实没理解，“全服务器只有一个人能进深渊”是指，例如一个服务器里有5个人，那么一个人进了深渊后，剩下的四个人都进不去深渊么？

那不然呢

**Comment by zhaodice** [comment]
A和B在同一个服务器，但A和B没有互相联机，A打深渊，B就不能打了，是这样吧

**Comment by keqingyyds** [comment]
> A和B在同一个服务器，但A和B没有互相联机，A打深渊，B就不能打了，是这样吧

准确来说是全服务器都进不去了

**Comment by lonpencil** [comment]
带哥能不能教一手怎么联机啊
