### ISSUE TITLE
[Bug] the log file is very huge on linux server

### ISSUE THREAD

**Issue by Omoinemie** [Melledy/Grasscutter#758]
I run it on ubuntu server, but the log file is very huge with many "EOF detected.".
![unknown](https://user-images.githubusercontent.com/31991443/167529754-319b5034-4a08-497a-917a-25f104c3210d.png)
![Snipaste_2022-05-10_10-23-50](https://user-images.githubusercontent.com/31991443/167529799-2d66063e-7165-4286-a139-ce0383d57ec0.jpg)

**Comment by leonier** [comment]
I think Grasscutter should add a headless mode that don't require stdin.

**Comment by gentlespoon** [comment]
There are people trying to implement HTTP API so the server no longer solely relies on STDIN.

The problem OP has can be solved by updating to the latest version and use the proper resource files.

**Comment by liizfq** [comment]
i tried to update the 1.1.2-dev and update the latest resource dir .but the bug was not resolved.

> There are people trying to implement HTTP API so the server no longer solely relies on STDIN.
> 
> The problem OP has can be solved by updating to the latest version and use the proper resource files.

**Comment by liizfq** [comment]
I resolved the problem throught modify Grasscutter.java startConsole().
`catch (EndOfFileException e) {
        if(input.length()!=0){
	        Grasscutter.getLogger().info("EOF detected.");
        }
        continue;
}`

**Comment by 4Benj** [comment]
I think #946 is a solution to this, it has not yet been merged.

**Comment by exzork** [comment]
my pr #946  completely disable console input line, so you can't use server console command if you set enableConsole to false

**Comment by UrsusArctos** [comment]
I'm on 1.2.2-development and this problem persists.
I run grasscutter as an OpenRC service on Linux headless box and log file gets filled with "EOF detected" at a rate of **8 to 9 thousand** log lines per second. This can't be right. How do I fix that?
