### ISSUE TITLE
Not working on android

### ISSUE THREAD

**Issue by Scirese** [Melledy/Grasscutter#76]
The game can't logon correctly on android. The login screen flashes and then nothing happend.
I have properly installed mitmproxy certs to /system and trusted it.
I thought it was because im running server remotely,but after i moved the server to a chroot Linux container(Arch linux) on the phone,the issue still.
The mitmproxy seems redirecting the server traffic correctly. But i just cant login.

Android 12,OSREL

**Comment by Scirese** [comment]
![捕获](https://user-images.githubusercontent.com/62688390/164442354-f724a9a0-2c01-49af-b3ba-1df9b7dca0f4.PNG)
The mitmproxy seems redirecting the server traffic correctly.

**Comment by Scirese** [comment]
And the grasscutter server seems running correctly too
![捕获](https://user-images.githubusercontent.com/62688390/164442590-2c8f6343-c78f-4fdd-bb15-4ceb61ee1d01.PNG)
.

**Comment by Scirese** [comment]
I used all the same configuration both on pc and android,pc can logon correctly but android cannot,why?

**Comment by Scirese** [comment]
Screen Record (Chinese)
https://user-images.githubusercontent.com/62688390/164452470-3b8a4c0b-89c0-41f8-8b07-bcf2ac60de13.mp4

**Comment by Scirese** [comment]
Configuration File

**Comment by Scirese** [comment]
Configuration File
Mongodb Server is fine
https://pastebin.com/ufwSfU0F

**Comment by Wansn-w** [comment]
is ur phone running andorid 11+?

**Comment by Scirese** [comment]
> Please confirm that you installed the CA certificate to the system directory instead of the user directory

![Screenshot_20220421-203957_Settings](https://user-images.githubusercontent.com/62688390/164459933-65c19ac4-d012-4771-b775-653aa664902b.png)

**Comment by MlgmXyysd** [comment]
> > Please confirm that you installed the CA certificate to the system directory instead of the user directory
> 
> ![Screenshot_20220421-203957_Settings](https://user-images.githubusercontent.com/62688390/164459933-65c19ac4-d012-4771-b775-653aa664902b.png)

Let me ask, what method do you use to add to the system

**Comment by Scirese** [comment]
> > > Please confirm that you installed the CA certificate to the system directory instead of the user directory
> > 
> > 
> > ![Screenshot_20220421-203957_Settings](https://user-images.githubusercontent.com/62688390/164459933-65c19ac4-d012-4771-b775-653aa664902b.png)
> 
> Let me ask, what method do you use to add to the system

Magisk module

**Comment by MlgmXyysd** [comment]
> Magisk module

Post your module list here

**Comment by Scirese** [comment]
> > Magisk module
> 
> Post your module list here

![Screenshot_20220421-204740_Ninimu](https://user-images.githubusercontent.com/62688390/164461212-6626030f-8d85-48f7-bed9-9ff6f1a8286a.png)
![Screenshot_20220421-204734_Ninimu](https://user-images.githubusercontent.com/62688390/164461217-e20d031d-52c5-4e68-b956-cde3ab668ffc.png)
![Screenshot_20220421-204723_Ninimu](https://user-images.githubusercontent.com/62688390/164461219-d13a5fc9-2ccd-4203-a8b1-25629b0350bf.png)
 The certificate is in that httpcanary module

**Comment by MlgmXyysd** [comment]
> The certificate is in that httpcanary module

1) You should NOT use these garbage modules, these can cause all problems, remove first.
![image](https://user-images.githubusercontent.com/17919858/164461559-d4c7145a-13ce-4df5-a6af-2a58ab395aec.png)
2) It may not be enough to install only on the system, a copy of user space needs to be reserved.
3) Make sure the cert context is `u:object_r:system_file:s0`
4) Merge #53 and #75 to your local source, remove current `config.json`, recompile and run. (Don't forget replace `127.0.0.1` to your LAN ip in config after run)

Do the above and check if the problem still exists

**Comment by Scirese** [comment]
> > The certificate is in that httpcanary module
> 
> 1. You should NOT use these garbage modules, these can cause all problems, remove first.
>    ![image](https://user-images.githubusercontent.com/17919858/164461559-d4c7145a-13ce-4df5-a6af-2a58ab395aec.png)
> 2. It may not be enough to install only on the system, a copy of user space needs to be reserved.
> 3. Make sure the cert context is `u:object_r:system_file:s0`
> 4. Merge #53 and #75 to your local source, remove current `config.json`, recompile and run. (Don't forget replace `127.0.0.1` to your LAN ip in config after run)
> 
> Do the above and check if the problem still exists


> 
You means i need to merge these pr and compile the server by my self?

By the way,secontext is fine
![Screenshot_20220421-210259_MT管理器~2](https://user-images.githubusercontent.com/62688390/164463938-3093a4f7-0754-46b3-bff3-82418e045aa0.png)

**Comment by MlgmXyysd** [comment]
> You means i need to merge these pr and compile the server by my self?
> 
> By the way,secontext is fine ![Screenshot_20220421-210259_MT管理器~2](https://user-images.githubusercontent.com/62688390/164463938-3093a4f7-0754-46b3-bff3-82418e045aa0.png)

Yes, but before that, do 1 and 2 first.

**Comment by Scirese** [comment]
> > You means i need to merge these pr and compile the server by my self?
> > By the way,secontext is fine ![Screenshot_20220421-210259_MT管理器~2](https://user-images.githubusercontent.com/62688390/164463938-3093a4f7-0754-46b3-bff3-82418e045aa0.png)
> 
> Yes, but before that, do 1 and 2 first.

Althrough I dont think LSPosed will cause these problem ,I will disable them for additional insurance.
Compile would take some time due to my old low-end computer XD.Before that ,just keep this issue open.

**Comment by MlgmXyysd** [comment]
> Through I dont think LSPosed will cause these problem ,I will disable them for additional insurance.

A lot of data from other projects tell me that these low-quality modules will lead to serious system issues. Users should remove it.

> Before that ,just keep this issue open.

Sure

**Comment by Scirese** [comment]
I cloned and compiled the latest dev branch and the issue still.

**Comment by MlgmXyysd** [comment]
> I cloned and compiled the latest dev branch and the issue still.

Did you forget to modify the configuration?

**Comment by BaiSugar** [comment]
Try to modify SRC \ Main \ Java \ EMU \ GrassCutter \ Server \ Dispatch under DispatchServer.java 363 line code
![C9}3I%OH0K }0{HL8 9NSD](https://user-images.githubusercontent.com/97774724/164575243-56d91f88-5762-4f1f-8e91-02984370a3b0.png)
,
new DispatchHttpJsonHandler("{\"retcode\":0,\"message\":\"OK\",\"data\":{\"id\":\"none\",\"action\":\"ACTION_NONE\",\"geetest\":null}}")

**Comment by Scirese** [comment]
> > I cloned and compiled the latest dev branch and the issue still.
> 
> Did you forget to modify the configuration?

I deleted the orig config ,and modified the new config correctly.

**Comment by BaiSugar** [comment]
> 尝试修改 SRC \ Main \ Java \ EMU \ GrassCutter \ Server \ Dispatch under DispatchServer.java 363 行代码 ![C9}3I%OH0K }0{HL8 9NSD](https://user-images.githubusercontent.com/97774724/164575243-56d91f88-5762-4f1f-8e91-02984370a3b0.png) ，new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”）

And recompile

**Comment by Scirese** [comment]
> 

I will try

**Comment by Scirese** [comment]
> new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")

> Task :compileJava FAILED
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要')'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                               ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                      ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                           ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                  ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                     ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                       ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                          ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                              ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                  ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                    ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                       ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                           ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                              ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                                    ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                                       ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                                                  ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 不是语句
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")
                                                                                                                                     ^
/home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java:376: 错误: 需要';'
                                new DispatchHttpJsonHandler("{"retcode":0,"message":"OK","data":{"id":"none","action":"ACTION_NONE","geetest":null}}")

 build error
gradle -v output:
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 16:40:07 UTC
Revision:     <unknown>

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Linux 4.19.226-IllusionX+ aarch64

**Comment by BaiSugar** [comment]
You lack char \

new DispatchHttpJsonHandler("{\"retcode\":0,\"message\":\"OK\",\"data\":{\"id\":\"none\",\"action\":\"ACTION_NONE\",\"geetest\":null}}")

**Comment by BaiSugar** [comment]
> > new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”）
> 
> > 任务 ：compileJava FAILED /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要'）' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';'< new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”）
> 
> ## 构建错误
> gradle -v 输出：
> ## 等级 7.4.2
> 构建时间： 2022-03-31 16：40：07 UTC 修订：
> 
> Kotlin: 1.5.31 Groovy: 3.0.9 Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM: 1.8.0_202 (Oracle Corporation 25.202-b08) OS: Linux 4.19.226-IllusionX+ aarch64

You lack char \
After I sent, GitHub will automatically delete the code in the \ , please add it manually (please combine the picture above)

**Comment by Scirese** [comment]
> > > new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”）
> > 
> > 
> > > 任务 ：compileJava FAILED /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要'）' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';'< new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 不是语句 new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”） ^ /home/kiana/Grasscutter/src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java：376： 错误： 需要';' new DispatchHttpJsonHandler（“{”retcode“：0，”message“：”OK“，”data“：{”id“：”none“，”action“：”ACTION_NONE“，”geetest“：null}}”）
> > 
> > 
> > ## 构建错误
> > gradle -v 输出：
> > ## 等级 7.4.2
> > 构建时间： 2022-03-31 16：40：07 UTC 修订：
> > Kotlin: 1.5.31 Groovy: 3.0.9 Ant: Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM: 1.8.0_202 (Oracle Corporation 25.202-b08) OS: Linux 4.19.226-IllusionX+ aarch64
> 
> You lack char After I sent, GitHub will automatically delete the code in the \ , please add it manually (please combine the picture above)

ok,build successfully

**Comment by BaiSugar** [comment]
`		server.createContext( // api-account-os.hoyoverse.com
				"/account/risky/api/check", 
				new DispatchHttpJsonHandler("{\"retcode\":0,\"message\":\"OK\",\"data\":{\"id\":\"none\",\"action\":\"ACTION_NONE\",\"geetest\":null}}")
		);`

**Comment by Scirese** [comment]
Ok ,Now I Can play ,Thanks for everyone!!!
