### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aimiliyaai** [Melledy/Grasscutter#761]
Part of the town model is missing

mail delete null
![QQ图片20220510110808](https://user-images.githubusercontent.com/58596511/167534876-781fd85a-59fa-4f63-8d8b-368b0216cbe0.png)
![QQ图片20220510110841](https://user-images.githubusercontent.com/58596511/167534947-e203e557-99ea-4fa6-af3e-0e8626760893.png)
![QQ图片20220510110923](https://user-images.githubusercontent.com/58596511/167535023-b1bbc9fd-983f-4c18-8334-ac9f785977d2.png)

**Comment by lunaticwhat** [comment]
most of them are gadget and they arent implemented yet. Devs are working hard on this !
