### ISSUE TITLE
[Issue]  How to reconginized code from games?

### ISSUE THREAD

**Issue by mengdalida** [Melledy/Grasscutter#766]
I have tried  to debug and receive msg from game with Nutrition bag.
get the header and payload

_header = [24, -32, 98, 40, 1, 48, -50, -127, -85, -28, -118, 48]
payload = [10, 8, 10, 6, 8, 2, 16, -21, -53, 6]_

But acutally, I didn't know what it's meaning, and it seems not satify the rules of proto3.
So I want to know how teams learn code usage of other command. Decompile？ Or other method? 

thank you.

**Comment by lunaticwhat** [comment]
hi, you can join us on our [Discord server ](https://discord.gg/T5vZU6UyeG) to discuss more about this!
We have development channel for anything related about development!
