### ISSUE TITLE
[Bug] delete account can not delete all data relate to the account by pr #747

### ISSUE THREAD

**Issue by EndEdge** [Melledy/Grasscutter#767]
**Describe the bug**
I use account delete command to delete my account, but after I login I found my avatars and items were still exist.

**Which branch did you use?**
development

**Screenshots**
When I debug the program, I found this code can not delete all of the document but a few of them in mongoDB.

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/19302257/167573804-7e222c15-52ca-44d4-bf09-b19a7c446064.png">

![image](https://user-images.githubusercontent.com/19302257/167571395-2b72347c-2622-46b2-a6d0-b1d2ed3d921d.png)

**Additional context**
I'm not familiar in mongodb, maybe it has another function to delete them.

**Comment by GanyusLeftHorn** [comment]
So it deleted some, but not all of your avatars? Can you show me the content of your avatars collection?

**Comment by EndEdge** [comment]
{
    _id: ObjectId("6273db6f401d243f5aecd6c3"),
    ownerId: 1,
    avatarId: 10000053,
    level: 1,
    exp: 0,
    promoteLevel: 0,
    satiation: 0,
    satiationPenalty: 0,
    currentHp: 993.8521728515625,
    fetters: [
      53030, 53034, 53042, 53038, 53022, 53046, 53018,
      53403, 53074, 53010, 53054, 53070, 53058, 53057,
      53078, 53050, 53014, 53031, 53029, 53037, 53301,
      53053, 53045, 53043, 53051, 53065, 53067, 53015,
      53017, 53079,   138, 53202, 53201, 53059, 53009,
      53208, 53066, 53016, 53080, 53073, 53023, 53032,
      53302, 53012, 53020, 53028, 53036, 53052, 53044,
      53060, 53401, 53207, 53024, 53040, 53072, 53056,
      53075, 53206, 53068, 53071, 53203, 53402, 53039,
      53064, 53033, 53035, 53041, 53021, 53013, 53019,
      53303, 53027, 53011, 53061, 53063, 53204, 53049,
      53047, 53077, 53205, 53076, 53069, 53062, 53048,
      53055
    ],
    skillLevelMap: { '10531': 1, '10532': 1, '10535': 1 },
    skillExtraChargeMap: {},
    proudSkillBonusMap: { '5339': 3 },
    skillDepotId: 5301,
    coreProudSkillLevel: 3,
    talentIdList: [ 531, 532, 533 ],
    proudSkillList: [ 532301 ],
    flyCloak: 140001,
    costume: 0,
    bornTime: 1651759983,
    fetterLevel: 1,
    fetterExp: 0,
    nameCardRewardId: 241036,
    nameCardId: 210083
  },
  {
    _id: ObjectId("6273db9b401d243f5aecd6d8"),
    ownerId: 1,
    avatarId: 10000045,
    level: 1,
    exp: 0,
    promoteLevel: 0,
    satiation: 0,
    satiationPenalty: 0,
    currentHp: 1030.3238525390625,
    fetters: [
      37202, 37067, 37071, 37206, 37063, 37059, 37055,
      37047, 37035, 37031, 37051, 37011, 37015, 37028,
      37036, 37032, 37043, 37039, 37201, 37072, 37060,
      37052, 37046, 37207, 37302, 37038, 37044, 37058,
      37024, 37074, 37401, 37301, 37030, 37023, 37016,
      37009,   133, 37073, 37069, 37208, 37204, 37053,
      37045, 37061, 37037, 37049, 37033, 37017, 37402,
      37403, 37010, 37014, 37022, 37021, 37029, 37303,
      37050, 37018, 37057, 37203, 37025, 37070, 37068,
      37064, 37205, 37054, 37062, 37040, 37042, 37056,
      37026, 37019, 37020, 37012, 37013, 37034, 37027,
      37048, 37041
    ],
    skillLevelMap: { '10451': 1, '10452': 1, '10453': 1 },
    skillExtraChargeMap: {},
    proudSkillBonusMap: {},
    skillDepotId: 4501,
    coreProudSkillLevel: 0,
    talentIdList: [],
    proudSkillList: [ 452301 ],
    flyCloak: 140001,
    costume: 0,
    bornTime: 1651760027,
    fetterLevel: 1,
    fetterExp: 0,
    nameCardRewardId: 241030,
    nameCardId: 210063
  },
  {
    _id: ObjectId("6273dbae401d243f5aecd6df"),
    ownerId: 1,
    avatarId: 10000014,
    level: 1,
    exp: 0,
    promoteLevel: 0,
    satiation: 0,
    satiationPenalty: 0,
    currentHp: 820.6118774414062,
    fetters: [
      6201, 6205, 6110, 6153, 6114, 6137, 6403, 6126,
      6118, 6150, 6125, 6133, 6165, 6122, 6154, 6161,
      6129, 6204, 6206, 6164, 6107, 6162, 6105, 6121,
      6134, 6128, 6127, 6135, 6149, 6156, 6148, 6142,
      6141, 6106, 6163, 6120, 6113, 6207, 6203, 6100,
      6155, 6112, 6132, 6140, 6136, 6143, 6144, 6139,
      6147, 6119, 6151, 6108, 6104, 6111, 6115, 6208,
      6303, 6101, 6103, 6160, 6301, 6146,  106, 6138,
      6401, 6130, 6402, 6123, 6131, 6117, 6124, 6116,
      6109, 6102, 6166, 6302, 6159, 6152, 6145, 6202
    ],
    skillLevelMap: { '10070': 1, '10071': 1, '10072': 1 },
    skillExtraChargeMap: {},
    proudSkillBonusMap: {},
    skillDepotId: 1401,
    coreProudSkillLevel: 0,
    talentIdList: [],
    proudSkillList: [ 142301 ],
    flyCloak: 140001,
    costume: 201401,
    bornTime: 1651760046,
    fetterLevel: 1,
    fetterExp: 0,
    nameCardRewardId: 241007,
    nameCardId: 210009
  },
  {
    _id: ObjectId("6273dcbf401d243f5aecd707"),
    ownerId: 1,
    avatarId: 10000003,
    level: 1,
    exp: 0,
    promoteLevel: 0,
    satiation: 0,
    satiationPenalty: 0,
    currentHp: 1143.9840087890625,
    fetters: [
      4208, 4101, 4109, 4117, 4204, 4403, 4145, 4129,
      4113, 4157, 4153, 4156, 4164, 4303, 4402, 4149,
      4125, 4128, 4132, 4121, 4205,  102, 4120, 4118,
      4106, 4104, 4161, 4154, 4155, 4147, 4148, 4140,
      4141, 4134, 4133, 4126, 4119, 4112, 4162, 4105,
      4103, 4206, 4131, 4127, 4111, 4115, 4202, 4163,
      4143, 4302, 4167, 4142, 4150, 4135, 4107, 4139,
      4203, 4114, 4146, 4102, 4110, 4207, 4100, 4108,
      4122, 4124, 4138, 4136, 4152, 4158, 4151, 4301,
      4401, 4165, 4166, 4123, 4116, 4137, 4201, 4144,
      4130
    ],
    skillLevelMap: { '10031': 1, '10033': 1, '10034': 1 },
    skillExtraChargeMap: {},
    proudSkillBonusMap: {},
    skillDepotId: 301,
    coreProudSkillLevel: 0,
    talentIdList: [],
    proudSkillList: [ 32301 ],
    flyCloak: 140001,
    costume: 0,
    bornTime: 1651760319,
    fetterLevel: 1,
    fetterExp: 0,
    nameCardRewardId: 241006,
    nameCardId: 210008
  }

**Comment by EndEdge** [comment]
I think it's not the problem in data, just use the wrong code to delete.

**Comment by GanyusLeftHorn** [comment]
Yeah, looks like I'm an idiot. You have to set an option to make it delete more than one matching document. I'll fix it later.

**Comment by EndEdge** [comment]
I've figured out the solution, you can see my pull request of this.
