### ISSUE TITLE
[Wiki]The document Java JDK link is 404

### ISSUE THREAD

**Issue by XiaoMouz** [Melledy/Grasscutter#771]
- Wrong in:https://github.com/Grasscutters/Grasscutter/wiki/Running#Prerequisites The JDK8u202 link is a 404 link
- The new Download Link is(Huawei Cloud): https://mirrors.huaweicloud.com/java/jdk/8u202-b08/
- And latest is build by Java-SE 17,shouldn't let user use JDK8u202....

> Submit this issue because your not have Document Issue template,and Wiki not have edit access

**Comment by memetrollsXD** [comment]
[Done!](https://github.com/Grasscutters/Grasscutter/wiki/Running)

**Comment by XiaoMouz** [comment]
ty
