### ISSUE TITLE
[Bug] Command /pos cannot be used

### ISSUE THREAD

**Issue by Yoimiya49** [Melledy/Grasscutter#773]
When use command /position in client, it won't show the value of position. (%.3F or %d)

**Which branch did you use?**
Stable branch（1.1）

**Screenshots**
![308e15baab5bc4c0.jpg](https://user-images.githubusercontent.com/71269079/167601745-9cee8610-65bd-4850-a209-8a4918f47c8b.jpg)

**Comment by Mateoust** [comment]
这个问题在最新版本的Dev中修复了，需要自行构建jar包或者从这里下载新的 https://ci.grasscutter.ga/job/Grasscutter-Dev/

This problem is fixed in the latest version of Dev, you need to build the jar package yourself or download the new one from here https://ci.grasscutter.ga/job/Grasscutter-Dev/

**Comment by lunaticwhat** [comment]
fixed in dev build !
