### ISSUE TITLE
[Issue] 无法登陆

### ISSUE THREAD

**Issue by HA-JD** [Melledy/Grasscutter#783]
![image](https://user-images.githubusercontent.com/47666701/167637447-0e106760-5349-4354-8520-e917eeceb783.png)
![image](https://user-images.githubusercontent.com/47666701/167637548-73438273-5d62-474d-bcd3-fb0f1d5c87cc.png)
![image](https://user-images.githubusercontent.com/47666701/167637596-87f9a0da-6fac-488f-8ab3-6c3efb90e30d.png)
Is this my configuration error code?or mitmdump error?

**Comment by HA-JD** [comment]
Unable to log in.

**Comment by lunaticwhat** [comment]
are you using dedicated server ?
can you post your config.json

**Comment by HA-JD** [comment]
Wrap it in someone else's lazy man.I think I may be missing some documents.

**Comment by HA-JD** [comment]
Thank you for your reply
