### ISSUE TITLE
[Issue] Errors in config.json cause it to be overwritten without warnings

### ISSUE THREAD

**Issue by leonier-test** [Melledy/Grasscutter#794]
**Did you look for other closed issues that have the same problem?**
None are similar to the problem I met.

**Describe the issue**
Even if there is only a slight JSON syntax error in config.json, the file will be overwritten unnoticed by a default config.json file when starting Grasscutter or using reload command in Grasscutter.
I think it's better to warn user of such errors and apply default configuration, rather than silently overwriting the whole file with default values.
BTW, every time when Grasscutter runs, the config.json will be touched (modification time changed). Isn't it common practice that don't write configuration files when the configuration is unchanged?

**Which branch did you use?**
Development branch

**Comment by mcxiaoke** [comment]
may be use two config files and merge it on start, config.json config.user.json

**Comment by leonier-test** [comment]
Seemed #863 is a better approach.
