### ISSUE TITLE
[Issue] Server friends disappeared, unable to enter commands

### ISSUE THREAD

**Issue by jeeri50701** [Melledy/Grasscutter#796]
![unknown](https://user-images.githubusercontent.com/25354315/167745516-f0db85f7-4310-4d38-8362-f6d1ca9b3929.png)
There is no way to enter commands

**Comment by lunaticwhat** [comment]
can you try to remove config.json and reload the server ?

**Comment by alt3ri** [comment]
Can you screenshot the friendlist in chat and send it here

**Comment by jeeri50701** [comment]
I tried it, still the same
Change the same file to another PC. The server friend is in normal condition

**Comment by lunaticwhat** [comment]
better try reinstall grasscutter. this is abnormal and shouldn’t happens

**Comment by jeeri50701** [comment]
I also tried reinstall grasscutter, still the same
same steps on another PC everything works fine

**Comment by lunaticwhat** [comment]
sound weird. can you provide the server console from starting up to ingame ?

**Comment by jeeri50701** [comment]
This is after entering the game
![001](https://user-images.githubusercontent.com/25354315/167960197-29012c33-8fd9-4b98-9218-f18be2f832db.jpg)
This is when it gets stuck in the friend interface
![002](https://user-images.githubusercontent.com/25354315/167960223-f660aaaa-b3a9-4d16-bbb9-bafc1b019e24.jpg)

**Comment by alt3ri** [comment]
Did you modified something in packet/send/ folder?

**Comment by jeeri50701** [comment]
No
same files same steps on another PC everything works fine

**Comment by lunaticwhat** [comment]
can you create a new account and try again ?

**Comment by jeeri50701** [comment]
still the same

**Comment by exzork** [comment]
I got this bug too, it's fixed by reload command + relog / restarting the server

**Comment by MidnightQuery** [comment]
can you try pressing slash(/)
seem to be a toggle to hide the server from chat participant.
press slash while in game, not having the chat ui on. or any other ui

**Comment by lunaticwhat** [comment]
closed to clean the workspace. please respond if you have solved / not solved the issue.
