### ISSUE TITLE
[Issue] Build failed and could not be parsed

### ISSUE THREAD

**Issue by clover1420** [Melledy/Grasscutter#808]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

Build failed and could not be parsed

**Which branch did you use?**

Development 

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/47273274/167793192-a2c2a6b7-42c4-4a7f-9ab2-3b9c6f4cc788.png)

**Comment by mingjun97** [comment]
This looks like your network issues.

**Comment by lunaticwhat** [comment]
should be network issue so gradle couldn't got its dependencies
