### ISSUE TITLE
[Issue] Prompt after logging in the game. If the text of the email sent is Chinese, there will be garbled. 

### ISSUE THREAD

**Issue by GearOvO** [Melledy/Grasscutter#809]
Prompt after logging in the game. If the text of the email sent is Chinese, there will be garbled. 
Development branch---Build #682
Wait for me for a while, I will try to show the screenshots in the game as much as possible.

**Comment by GearOvO** [comment]
https://tuchuangs.com/imgs/2022/05/11/a001fc6aca5173dd.png
https://tuchuangs.com/imgs/2022/05/11/a8823bacecae7126.png

**Comment by KiminaNatsuki** [comment]
basically corrupted chinese text since it's in wrong format or something

**Comment by leonier** [comment]
UTF-16 or GBK wrongly interpreted by the client as UTF-8?

**Comment by yinleren6** [comment]
**Temporary** solution: set the config document to **GB-18030** encoding

**临时**解决办法：将config文档设置为**GB-18030**编码

**Comment by lunaticwhat** [comment]
> **Temporary** solution: set the config document to **GB-18030** encoding
> 
> **临时**解决办法：将config文档设置为**GB-18030**编码

thank you for the solution !
