### ISSUE TITLE
[Issue] I need help with this

### ISSUE THREAD

**Issue by elias0057** [Melledy/Grasscutter#828]
I follow this guide: https://alt3ri.me/other/grasscutter_guide.pdf
When i start the server i get this error
![imagen_2022-05-11_132759868](https://user-images.githubusercontent.com/77704890/167920401-f9bbb3af-b5d8-474a-8c1b-e6d55cb07586.png)
I need help i dont know how to sol this.

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
