### ISSUE TITLE
Handbook utility generate null for all non-EN monster

### ISSUE THREAD

**Issue by umiiii** [Melledy/Grasscutter#83]
If you change `TextMap/TextMapEN.json` to another langauge, say, `TextMap/TextMapCHS.json`, the monster part will always generate a null part.

Example (using TextMapCHS.json)
```
// Monsters
20010101 : null
20010201 : null
20010202 : null
20010301 : null
20010302 : null
20010401 : null
20010402 : null
...
```

Compared to the original TextMapEN.json one:
```
// Monsters
20010101 : Dendro Slime
20010201 : Large Dendro Slime
20010202 : 
20010301 : Anemo Slime
20010302 : Anemo Slime (Mechanicus)
20010401 : Large Anemo Slime
20010402 : Large Anemo Slime (Mechanicus)
20010403 : 
20010501 : Electro Slime
20010502 : Electro Slime (Mechanicus)
20010601 : Large Electro Slime
20010602 : Large Electro Slime (Mechanicus)
20010604 : 
```

**Comment by Wansn-w** [comment]
Use the generated [handbooks](https://drive.google.com/file/d/1GbWPXTA-CtN3DTZtg2hq0Y5Qtf0gCK0S/view?usp=sharing) or put `dump_handbook.py` into resource folder and run the following command to automatically generate handbooks：

 ```shell
python dump_handbook.py
```
**ps:** `--help` argument for more help

**Comment by fumbling644o** [comment]
There isn't anything wrong with the code other than encoding assumptions. It looks like the `TextMap` file is missing the entries for the names of monsters.

Take the Dendro Silme for example. Its `TextMap` hash is `2989346297`. If you open up `TextMapEN` and search for `2989346297`, you'll find the correct value there. The same goes for `TextMapCHT`: it's correct in that file, too. However, `TextMapCHS` does not contain the key.

**Comment by PasserbyAlpha** [comment]
> 

maybe those blanks can be filled by referring EN version?  I will try it later

**Comment by PasserbyAlpha** [comment]
> It works but not well. There are too many missing id in CHS text map...
![翻译结果](https://user-images.githubusercontent.com/104211635/164884930-55e24452-0c24-4666-b8f1-e9c1b5614544.png)

**Comment by Wansn-w** [comment]
[Handbook_FullLang_Script-v0.8.0.zip](https://github.com/Grasscutters/Grasscutter/files/8546607/Handbook_FullLang_Script-v0.8.0.zip) try this & i add more categories in this version

**Comment by mengdalida** [comment]
> TextMap/TextMapEN.json

can you give me the english version of enemies list

**Comment by mengdalida** [comment]
@PasserbyAlpha   thank you, no need to give, I can be chose in command line

**Comment by 4Benj** [comment]
Is this still an issue?
