### ISSUE TITLE
[Bug] Problems regarding Artifact Dungeons

### ISSUE THREAD

**Issue by Hutaohebao** [Melledy/Grasscutter#830]
**Describe the bug**

1. Cannot enter "Hidden Palace Of Zhou Formula" and "Peak Of Vindagnyr"
2. Cannot claim the rewards due to the air wall for "The Lost Valley" and "Momiji-Dyed Court"
3. Lack of the second wave of monsters and thus stuck for "Slumbering Court" and "Domain Of Guyun"

**Which branch did you use?**

Development branch

**Comment by KingRainbow44** [comment]
domains and the like have not been completely finished.

**Comment by KingRainbow44** [comment]
Due to this issue being inactive, I will be closing it. Feel free to make a new issue.
