### ISSUE TITLE
[Solved]How to enable falling damage

### ISSUE THREAD

**Issue by Wubianshilsj** [Melledy/Grasscutter#834]
As the title proposed, I noticed that falling damage is not applied in the Grasscutter, so there should be a way to enable it

**Comment by GanyusLeftHorn** [comment]
Fall damage is already implemented in the development build. Update to that if you want it.

**Comment by BedamatiMohanty** [comment]
What wxactly is failing? your local or remote deployment? try advanced features for remote deployment in docker ... docker.com. Please read this along with helm charts. very powerful tool

**Comment by gentlespoon** [comment]
Fall damage is already implemented.
Check if you have the latest changes on the development branch. Also, check if you have enabled god mode - gravity is not an issue when you are invincible.

For a moment I thought it may be broken again. You almost scared the sh!t out of me.

**Comment by lunaticwhat** [comment]
update your grasscutter. lastest development build already fixed this.

**Comment by Wubianshilsj** [comment]
OK thanks everyone I have updated the grasscutter and the problem solved
