### ISSUE TITLE
渊下宫地图无法正常显示

### ISSUE THREAD

**Issue by victor-lcr** [Melledy/Grasscutter#835]
**Describe the bug**
CN:在渊下宫地图中，无法正常显示，在米哈游服务器中不会出现该问题
EN:In the map of yuanxiagong, it cannot be displayed normally. This problem will not appear in the mihoyo's server(Using translation software)

**Which branch did you use?**
Releases  v1.1.0

**Screenshots**
![20220512131148](https://user-images.githubusercontent.com/69039383/168012825-9381aea3-8d2b-4fff-bf04-d2df64b3734e.png)

**Comment by lunaticwhat** [comment]
this is a known bug and should be fixed in the future !

**Comment by zhaodice** [comment]
you can use this command:

`/weather 1`

**Comment by zhaodice** [comment]
渊下宫的当前默认天气存在光污染，手动用指令修改一下天气就没问题了

**Comment by lunaticwhat** [comment]
please use weather command to change the environment lighting manual or wait until we fixed this issue later !
