### ISSUE TITLE
[Feature Request] Dust song pot

### ISSUE THREAD

**Issue by luoningjiang** [Melledy/Grasscutter#839]
**Is your feature request related to a problem? Please describe.**

I think anybody wants to join other’s Dust song pot and thy want to create the owner’s Dust song pot! 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BedamatiMohanty** [comment]
How is this different from spotify premium feature? or linkedin premium feature? Do you want to give the licensed version for free?

**Comment by Yazawazi** [comment]
`尘歌壶` English translation is not `Dust Song Pot`, but `Teapot` or `Serenitea Pot`.

https://genshin-impact.fandom.com/wiki/Serenitea_Pot

**Comment by BedamatiMohanty** [comment]
Ok. Then please try aternity translator becuase i find it much better it works with all browsers. else check the html encoding in your UI page may be its UTF8 and not 16 that is being used. Hence the problem.

**Comment by gentlespoon** [comment]
Lol, I actually liked the name Dust Song Pot.

**Comment by KiminaNatsuki** [comment]
> Lol, I actually liked the name Dust Song Pot.

lmao nice translation

**Comment by Yazawazi** [comment]
I am working on this: https://github.com/Grasscutters/Grasscutter/pull/869

**Comment by lunaticwhat** [comment]
> I am working on this: #869

thank you !
