### ISSUE TITLE
[问题]token is invalid

### ISSUE THREAD

**Issue by yukiryo** [Melledy/Grasscutter#849]
There is this problem on iOS, but not on pc
no output on the server side
gcauth is not installed
![FB4EC7DD-6EB0-4D74-8F59-51D1902B6165](https://user-images.githubusercontent.com/58250223/168135029-9ec156ad-3143-4e9d-a226-55ecf12e062c.jpeg)

**Comment by exzork** [comment]
> 

make sure you modify your rocket / or whatever the software is ( i forgot ) to use your server and not someone else server.

**Comment by yukiryo** [comment]
I am sure that is correct
