### ISSUE TITLE
[Issue] Can't log in on someone's server.

### ISSUE THREAD

**Issue by Mat6Mat** [Melledy/Grasscutter#851]
Basically, I installed GrassClipper succesfully and I wanted to play with other people too so we attempted to use Hamachi. I added the Ipv4 as the ip address and left the port untouched. It all went FINE until the part with the door, where I clicked on it to start up the game but I was greeted by a White Screen and the error code says "Log In Failed, Try again" If I try again it's the same thing, a loop. I really want to play co-op with hacks to try builds and stuff.

**Comment by Hutaohebao** [comment]
I met the same issue yesterday. First, check if the UDP port on the server-side is enabled. If still not working, try Radmin or ZeroTier and see if it works.

**Comment by diona-katzlein** [comment]
I try make server using ZeroTier. All running fine but when try login in-game got message Erro Code: 4206
Logs on Grasscutter:
11:08:45 <INFO:DispatchServer> [Dispatch] Client 10.147.20.111 is trying to log in via token
11:08:45 <INFO:DispatchServer> [Dispatch] Client 10.147.20.111 logged in via token as 10002
11:08:46 <INFO:DispatchServer> [Dispatch] Client 10.147.20.111 succeed to exchange combo token

Logs on mitmproxy:
127.0.0.1:6471: GET https://10.147.20.111/combo/box/api/config/sdk/combo?biz_key=hk4e_global&client_type=3
             << 200 OK 140b
127.0.0.1:6473: POST https://10.147.20.111/hk4e_global/combo/granter/api/compareProtocolVersion?
             << 200 OK 209b
127.0.0.1:6470: GET https://10.147.20.111/hk4e_global/mdk/shield/api/loadConfig?client=3&game_key=hk4e_global
             << 200 OK 533b
127.0.0.1:6469: POST https://10.147.20.111/sdk/dataUpload
             << 200 OK 10b
127.0.0.1:6472: GET https://10.147.20.111/hk4e_global/combo/granter/api/getConfig?app_id=4&channel_id=1&client_type…
             << 200 OK 392b

What i should do?

**Comment by LaoSparrow** [comment]
I got a similar issue like yours in #836 , try my solution in this issue

**Comment by dongriiiii** [comment]
edit "config.json" change all "Public Ip" from "127.0.0.1" to your server's ![IMG_20220513_180611.jpg](https://user-images.githubusercontent.com/87489560/168261788-a641e0d0-b89a-4ed4-a479-c6d6b9497b40.jpg)

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
