### ISSUE TITLE
[Issue] I don't have the .jar file for grasscutter, where do I get that?

### ISSUE THREAD

**Issue by MrNightForts** [Melledy/Grasscutter#853]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

**Which version did you use?**

**Screenshots**

**Additional context**

**Comment by GanyusLeftHorn** [comment]
Seriously? _At least_ read the README before opening an issue ...

**Comment by diona-katzlein** [comment]
the jar u can download on [Release V1.1.0](https://github.com/Grasscutters/Grasscutter/releases/tag/v1.1.0) but if you wanna compile, just download stable or dev then compile.

At least read the README before opening an issue
