### ISSUE TITLE
[Issue] How to enable announcement display?

### ISSUE THREAD

**Issue by kuyoos** [Melledy/Grasscutter#859]
Compiled from the latest version of the dev minute source code currently used grasscutter-1.1.1-dev

Login to the game but the announcement doesn't show up

I want him to show how to change

sorry i'm using google translate

**Comment by lopelem** [comment]
需要把服务端里面的keystore.p12这个证书导入到你本地的客户端登录的电脑上

**Comment by swarswa** [comment]
[keystore.p12] What is a certificate protected private key @lopelem

**Comment by swarswa** [comment]
keystore. P12 what is the certificate protected private key password @lopelem
