### ISSUE TITLE
[Feature Request]加入pvp模式（Join PVP mode）

### ISSUE THREAD

**Issue by W0228sy** [Melledy/Grasscutter#860]
是否可以加入pvp模式（玩家之间可以造成伤害），以此增强目前没有剧情任务的可玩性

Can you add PVP mode (damage can be caused between players) to enhance the playability of tasks without plot at present

**Comment by KiminaNatsuki** [comment]
basically genshin pvp

should be fun but not really official :pensive:

**Comment by W0228sy** [comment]
> 基本上是原神pvp
> 
> 应该很有趣，但不是很正式😔
我觉得私服加上这个功能应该效果会非常好，并且很有特色，可以更好的吸引人

I think the effect of adding this function to the private service should be very good, and it is very distinctive, which can be more attractive

**Comment by 4Benj** [comment]
Sadly this will be very difficult to implement due to the game client not sending any damage events to the server when attacking another player.
It is technically possible but the solution will most likely be very hacky and difficult

**Comment by liujiaqi7998** [comment]
How about use an monster replace palyer to  attacking another player.
可以用怪物代替玩家实现对另一个玩家伤害吗？

**Comment by 4Benj** [comment]
> How about use an monster replace palyer to attacking another player.

That is one of the ideas I meant by “hacky”

**Comment by liujiaqi7998** [comment]
但是我认为，把这个功能做成插件会更好一些。

**Comment by liujiaqi7998** [comment]
But I think Maybe made the plugin to support this will be better.
但是我认为也许做了插件来支持这个会更好。
