### ISSUE TITLE
Illegal use and transmission function

### ISSUE THREAD

**Issue by laocaiji2333** [Melledy/Grasscutter#871]
I have completed the tutorial, but I have presented the server:
Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
Is there any good solution

**Comment by Mateoust** [comment]
Use the Resource file here: [Koko-boya/Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

**Comment by lunaticwhat** [comment]
Use resources from https://github.com/Koko-boya/Grasscutter_Resources or just leave it. That error might not causing any problem with your gameplay
