### ISSUE TITLE
[Bug] When Linux is used to run the server, the server often stops due to high I/O usage

### ISSUE THREAD

**Issue by Marchen-zcl** [Melledy/Grasscutter#876]
When Linux is used to run the server, the server often stops due to high I/O usage
Atop query is found to be Java and mongodb problem

**Comment by exzork** [comment]
> When Linux is used to run the server, the server often stops due to high I/O usage Atop query is found to be Java and mongodb problem

which branch and version you're running? you can get that information from log when server started if using dev branch

**Comment by Marchen-zcl** [comment]
> > When Linux is used to run the server, the server often stops due to high I/O usage Atop query is found to be Java and mongodb problem
> 
> which branch and version you're running? you can get that information from log when server started if using dev branch

It‘s the dev version, but there was no error message while I was watching, and by the time the error occurred the server had stopped running

**Comment by KiminaNatsuki** [comment]
Closing inactive issues to clear up workspace, feel free to resubmit if this haven't been fixed yet, plus follow the issue format next time.
