### ISSUE TITLE
[Issue] how can i do command "quest"?

### ISSUE THREAD

**Issue by genshinimpacti** [Melledy/Grasscutter#878]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

**Which version did you use?**

**Screenshots**

**Additional context**

**Comment by tiantian520tt** [comment]
Hello!
When you execute /quest, you should know:
/quest add can add new tasks
/quest finish can complete a task
You can refer to the corresponding ID table as follows (but the Chinese version)
[ID.txt](https://github.com/Grasscutters/Grasscutter/files/8691985/ID.txt)
[quest.txt](https://github.com/Grasscutters/Grasscutter/files/8691986/quest.txt)

**Comment by genshinimpacti** [comment]
thanks alot

**Comment by tiantian520tt** [comment]
You are welcome.
