### ISSUE TITLE
[Bug] Can't change Voice-Over Language in full offline

### ISSUE THREAD

**Issue by RISEN-B** [Melledy/Grasscutter#880]
**Describe the bug**

I have all the voice files, but can only use the system default voice.

other hint: calculating ...

**Which branch did you use?**

1.1.1-dev-57a9cae

**Screenshots**

Hint
Failed to download resource file or network error. Please try again.
Code:-9000
Confirm

**Additional context**

**Comment by KiminaNatsuki** [comment]
Can you at least provide more details?

**Comment by RISEN-B** [comment]
> Can you at least provide more details?

I try to play the game in full offline, so reinstall the game (unzip the official zip and the English voice zip). Clean up the reg and other related files.

After opening the game for the first time, close the game and put other voice files (zh, jp, kor) in the game.

But the game can't detect the other voice files. Hint: calculating ...

I found the log prompt: errMsg = -9000-Invalid URI: The format of the URI could not be determined: /output/client/StandaloneWindows64/release_res_versions_external; , useTime = 15s

I found a way to switch voice: modify the audio_lang_14 file, and restart game.

**Comment by memetrollsXD** [comment]
Change in official server

**Comment by grantterra** [comment]
> > Can you at least provide more details?
> 
> I try to play the game in full offline, so reinstall the game (unzip the official zip and the English voice zip). Clean up the reg and other related files.
> 
> After opening the game for the first time, close the game and put other voice files (zh, jp, kor) in the game.
> 
> But the game can't detect the other voice files. Hint: calculating ...
> 
> I found the log prompt: errMsg = -9000-Invalid URI: The format of the URI could not be determined: /output/client/StandaloneWindows64/release_res_versions_external; , useTime = 15s
> 
> I found a way to switch voice: modify the audio_lang_14 file, and restart game.

Thank you so much

**Comment by DevilPaean** [comment]
> > Can you at least provide more details?
> 
> I try to play the game in full offline, so reinstall the game (unzip the official zip and the English voice zip). Clean up the reg and other related files.
> 
> After opening the game for the first time, close the game and put other voice files (zh, jp, kor) in the game.
> 
> But the game can't detect the other voice files. Hint: calculating ...
> 
> I found the log prompt: errMsg = -9000-Invalid URI: The format of the URI could not be determined: /output/client/StandaloneWindows64/release_res_versions_external; , useTime = 15s
> 
> I found a way to switch voice: modify the audio_lang_14 file, and restart game.

thank you bro!!!!!!!!!!!!!!!!!!!!!!! finally i can use japanese voice.......
