### ISSUE TITLE
[Issue] Some characters cannot attack

### ISSUE THREAD

**Issue by xiaomoL444** [Melledy/Grasscutter#881]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**
 Some characters cannot attack or the elemental combat technique element burst has no effect

**Which version did you use?**

**Screenshots**
![1652505631859](https://user-images.githubusercontent.com/69074564/168411958-ad9ec33c-6674-4a45-b4f8-f3beb0c40513.gif)

**Additional context**

**Comment by akbarsar** [comment]
Hi, sorry to bother but how did this get fixed? I’m having the same issue.

**Comment by xiaomoL444** [comment]
> Hi, sorry to bother but how did this get fixed? I’m having the same issue.

i downloaded the latest resource then the problem was solved
