### ISSUE TITLE
[Feature Request] 增加随机生成物品命令

### ISSUE THREAD

**Issue by Omoinemie** [Melledy/Grasscutter#883]
比如随机生成100个五星冰之花，随机生成200个任意四星圣遗物狗粮

**Comment by CarterLi** [comment]
这东西有什么用？

**Comment by arub3do** [comment]
> [Feature Request] 增加随机生成物品命令
> [Feature Request] Add random item generation command

gc 应该只提供基本的物品生成命令。
额外的生成要求适合做成插件。

----

GC should only provide basic item generation commands.
Additional generation requirements are suitable to be made into plugins.
