### ISSUE TITLE
[Issue] Banner probability issue

### ISSUE THREAD

**Issue by xmgnew** [Melledy/Grasscutter#887]
In the latest dev, when I pull in the banner, it goes back to the 90 pull pity. I checked my Banners.json, I am very sure that I never changed it before, and the json file sets the pity to 1 (each pull will be gold). But in the game, I still get 90 pull pity. I don't know what's wrong.

**Comment by Birdulon** [comment]
Post json file

**Comment by xmgnew** [comment]
> Post json file

This is the json file I am using: https://drive.google.com/file/d/16DCoQBNCUtujqeIqolZxl_IUShhD8Qd-/view?usp=sharing

**Comment by Birdulon** [comment]
Ah right, you want every pull to be a 5star. `softPity` and `hardPity` aren't in the dev branch anymore, replace them with `"weights5": [[1,100000]]`

**Comment by xmgnew** [comment]
> Ah right, you want every pull to be a 5star. `softPity` and `hardPity` aren't in the dev branch anymore, replace them with `"weights5": [[1,100000]]`

Thanks, after changing, the probability backs to normal. But there will be weapons appear in the character banner, how should I change that?

**Comment by Birdulon** [comment]
`"fallbackItems5Pool2": []` in any banner you don't want standard 5star weapons in

**Comment by xmgnew** [comment]
> `"fallbackItems5Pool2": []` in any banner you don't want standard 5star weapons in

Thanks!!! The banners are back to normal now
