### ISSUE TITLE
[Issue] Cannot invoke "java.lang.Float.floatValue()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null

### ISSUE THREAD

**Issue by ifrvn** [Melledy/Grasscutter#888]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

Someone has reported to me that his game stucked at white screen after login. Here's the error from server:
![image](https://user-images.githubusercontent.com/21982381/168441420-80449dc9-5277-4992-a003-29aafb798a19.png)

so i added some logs to figure it out, turns out it's trying to get the value of  `FIGHT_PROP_ROCK_SUB_HURT` at `emu.grasscutter.data.def.ReliquaryLevelData.getPropValue(ReliquaryLevelData.java:39)`

but the resources which i'm using from https://github.com/Koko-boya/Grasscutter_Resources/blob/main/Resources/ExcelBinOutput/ReliquaryLevelExcelConfigData.json  doesn't have this proptype.

ps. I wonder what's the difference between `FIGHT_PROP_ROCK_ADD_HURT` and `FIGHT_PROP_ROCK_SUB_HURT`, tks!

**Which version did you use?**

Grasscutter version: 1.1.1-dev-46f16c6

**Screenshots**

**Additional context**

**Comment by exzork** [comment]
ADD is dmg bonus and SUB is dmg reduction i think

**Comment by ifrvn** [comment]
> 

thank u! you're right.

i've added all elements dmg reduction (`FIGHT_PROP_[element]_SUB_HURT`) to `ReliquaryLevelExcelConfigData.json` using the same value of `FIGHT_PROP_FIRE_SUB_HURT` in the file, and now it's working. but i still don't have the value of `FIGHT_PROP_PHYSICAL_SUB_HURT`, so using physical dmg reduction as the main prop of artifact could still cause the problem.

maybe @Koko-boya could help to fix it?

[ReliquaryLevelExcelConfigData.zip](https://github.com/Grasscutters/Grasscutter/files/8694231/ReliquaryLevelExcelConfigData.zip)

**Comment by Koko-boya** [comment]
> > 
> 
> thank u! you're right.
> 
> i've added all elements dmg reduction (`FIGHT_PROP_[element]_SUB_HURT`) to `ReliquaryLevelExcelConfigData.json` using the same value of `FIGHT_PROP_FIRE_SUB_HURT` in the file, and now it's working. but i still don't have the value of `FIGHT_PROP_PHYSICAL_SUB_HURT`, so using physical dmg reduction as the main prop of artifact could still cause the problem.
> 
> maybe @Koko-boya could help to fix it?
> 
> [ReliquaryLevelExcelConfigData.zip](https://github.com/Grasscutters/Grasscutter/files/8694231/ReliquaryLevelExcelConfigData.zip)

Current Genshin don't have DMG Reduction main stat artifact as you k, of course it wont work without excel data modification

By manually adding (process you done) can make the main stat work for elements because there is the property for those exist `ReliquaryMainPropExcelConfigData.json`. i checked there is no physical res main stat property exist that's why it wont work 

_i don't think this will be the reason for game stuck at white screen_

**Comment by ifrvn** [comment]
> > > 
> > 
> > thank u! you're right.
> > 
> > i've added all elements dmg reduction (`FIGHT_PROP_[element]_SUB_HURT`) to `ReliquaryLevelExcelConfigData.json` using the same value of `FIGHT_PROP_FIRE_SUB_HURT` in the file, and now it's working. but i still don't have the value of `FIGHT_PROP_PHYSICAL_SUB_HURT`, so using physical dmg reduction as the main prop of artifact could still cause the problem.
> > 
> > maybe @Koko-boya could help to fix it?
> > 
> > [ReliquaryLevelExcelConfigData.zip](https://github.com/Grasscutters/Grasscutter/files/8694231/ReliquaryLevelExcelConfigData.zip)
> 
> Current Genshin don't have DMG Reduction main stat artifact as you k, of course it wont work without excel data modification
> 
> By manually adding (process you done) can make the main stat work for elements because there is the property for those exist `ReliquaryMainPropExcelConfigData.json`. i checked there is no physical res main stat property exist that's why it wont work 
> 
> _i don't think this will be the reason for game stuck at white screen_ 

In file [FightProperty.java#L34-L51](https://github.com/Grasscutters/Grasscutter/blob/development/src/main/java/emu/grasscutter/game/props/FightProperty.java#L34-L51) it contains all dmg reduction props, so commands like `/giveart 95554 10014 501054,1 501064,1 501204,1 501224,6 21` is legal to run, and it should generate an artifact with rock dmg reduction as main stat. But since there's no `FIGHT_PROP_ROCK_SUB_HURT` in excel data, it caused an error which i had posed in the issue.
 
I think we should figure out a proper way to fix the bug, either add those dmg reduction to excel data or change code to prevent people from using dmg reduction as main stat property. Just my thoughts.

**Comment by ghost** [comment]
This is caused by (a custom) main stat not having a key in `ReliquaryLevelExcelConfigData`. If you edit a main stat for an artifact, you need to also add the appropriate values in `ReliquaryLevelExcelConfigData`.
