### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by lbvic** [Melledy/Grasscutter#895]
**Describe the issue**

 LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
**Which version did you use?**

**Screenshots**

![image](https://user-images.githubusercontent.com/96934569/168455199-9c67a5a6-ed9e-4bdf-b6f5-158c133f5d5b.png)

**Additional context**

![image](https://user-images.githubusercontent.com/96934569/168455208-808b8985-64e7-4f1b-8a6c-e680a03d5161.png)

**Comment by KingRainbow44** [comment]
fill out the form properly, this issue should have been fixed on the development branch

**Comment by lbvic** [comment]
ok

**Comment by lbvic** [comment]
I have finished this question
