### ISSUE TITLE
[Issue] 更新新版dev后连接超时

### ISSUE THREAD

**Issue by Omoinemie** [Melledy/Grasscutter#896]
Grasscutter version: 1.1.1-dev
[  Git Hash: d80f313](https://github.com/Grasscutters/Grasscutter/actions/runs/2324120104)
-->
I test on my local PC, it's worked fine, but I run it on my cloud server, it always showed connect time out!
就是新版config变了后，能正常登录，但就是连不上，防火墙关了也不行。

![Snipaste_2022-05-15_11-12-36](https://user-images.githubusercontent.com/31991443/168455690-530107a8-974c-4e31-ada6-e05d6d89c390.jpg)

**Comment by mingjun97** [comment]
Got the same issue. Fixed by delete the `config.json` and modify it on the freshly generated one.

**Comment by mingjun97** [comment]
Personal tips for you.. You may want to mask your public IP.

**Comment by Omoinemie** [comment]
> Personal tips for you.. You may want to mask your public IP.

你说是这里吗？改成公网IP？我用的nginx反代，所以关了ssl
![Snipaste_2022-05-15_18-01-27](https://user-images.githubusercontent.com/31991443/168467302-08da5dd1-cf93-4282-914c-cec33fa0fed0.jpg)

**Comment by mingjun97** [comment]
> > Personal tips for you.. You may want to mask your public IP.
> 
> 你说是这里吗？改成公网IP？我用的nginx反代，所以关了ssl ![Snipaste_2022-05-15_18-01-27](https://user-images.githubusercontent.com/31991443/168467302-08da5dd1-cf93-4282-914c-cec33fa0fed0.jpg)

No. I mean the log pasted by you. It has your public IP out there, which somehow put your server in danger.

**Comment by unknown10777** [comment]
> > Personal tips for you.. You may want to mask your public IP.
> 
> 你说是这里吗？改成公网IP？我用的nginx反代，所以关了ssl ![Snipaste_2022-05-15_18-01-27](https://user-images.githubusercontent.com/31991443/168467302-08da5dd1-cf93-4282-914c-cec33fa0fed0.jpg)

他的意思是你的日志露出了你的ip，会把你的服务器置于危险中，例如ddos

**Comment by unknown10777** [comment]
建议删除config重新生成一个并且重新编辑

**Comment by Omoinemie** [comment]
> 建议删除config重新生成一个并且重新编辑

都试过了，防火墙关了，各种各样都试过了

**Comment by Omoinemie** [comment]
> 建议删除config重新生成一个并且重新编辑
漏了一个地方，改了就进去了
![Snipaste_2022-05-15_18-30-46](https://user-images.githubusercontent.com/31991443/168468327-d987c5ba-fb19-4985-a0a8-3bedaf9a6c98.jpg)

**Comment by nigpo** [comment]
用我最新提交的pr即可

**Comment by nigpo** [comment]
这个是最新更新连接管理器引入的严重BUG，主要原因是bind加入了hosts，我最新提交的PR已经修复了这个问题，似乎所有反向代理的连接方法都受到了影响，还有双网卡或者多网卡设备也是
