### ISSUE TITLE
Run this project on the server, Linux, the startup is successful, how to connect the mobile phone

### ISSUE THREAD

**Issue by Epoch-guo** [Melledy/Grasscutter#901]
Run this project on the server, Linux, the startup is successful, how to connect the mobile phone 
Does Linux also need a proxy?

**Comment by lunaticwhat** [comment]
You need proxy on you phone

**Comment by jinghuashang** [comment]
So how does the mobile phone proxy? I am Redmi k50 and there seems to be no proxy software that can be used

**Comment by hujiayucc** [comment]
看看路由器是否有自定义host功能，如果是小米的可以下个小米WIFI APP绑定路由器自定义host
