### ISSUE TITLE
[Feature Request] Can the items obtained from the wish list be translated into Chinese

### ISSUE THREAD

**Issue by swarswa** [Melledy/Grasscutter#902]
Wish list to obtain items in Chinese
![QQ截图20220515130100](https://user-images.githubusercontent.com/104618785/168458008-2f86794b-0ad6-482c-a714-e02fd3a55bc5.png)

**Comment by mIwaYuhang** [comment]
[gacha_mappings.zip](https://github.com/Grasscutters/Grasscutter/files/8694393/gacha_mappings.zip)

**Comment by swarswa** [comment]
@mIwaYuhang thank you

**Comment by mingjun97** [comment]
Alternately, you can do `java -jar grasscutter.jar -gachamap` and input `CHS` for chinese version gacha mapping.
