### ISSUE TITLE
stat commands not saving 

### ISSUE THREAD

**Issue by n6mi44** [Melledy/Grasscutter#91]
Setstat command doesnt save the statistic

**Comment by Lubin502831** [comment]
It is stated in the document that it will not work after offline

**Comment by KingRainbow44** [comment]
hopefully, someone can get around to adding an option for saving stats

**Comment by alt3ri** [comment]
I forgot to add the save option. I'll add it tmr because it's late here

**Comment by Mashiro2000** [comment]
> 我忘了添加保存选项。我会添加它tmr，因为这里很晚了

Has the problem been solved
I still can't save stats in the latest development version

**Comment by Mashiro2000** [comment]
> I forgot to add the save option. I'll add it tmr because it's late here

Has the problem been solved?
I still can't save statistics in the latest development version
