### ISSUE TITLE
1.1.0，/talent设置天赋等级后无法保存

### ISSUE THREAD

**Issue by Liujunhua007** [Melledy/Grasscutter#911]
serve提示设置成功，但实际上等级没变

**Comment by SleepyAsh0191** [comment]
Translate: 
# Version 1.1.0, set talent level via /talent command is not working and cannot be saved.

"Server" replied success but I cannot see the change in game.

**Comment by Birdulon** [comment]
Fixed in c2d41ca which is in version 1.1.2
