### ISSUE TITLE
I cant teleport after some quests

### ISSUE THREAD

**Issue by NeoMika** [Melledy/Grasscutter#913]
![YuanShen_2022_05_15_21_25_46_543](https://user-images.githubusercontent.com/86155975/168475247-e0c05918-1199-44de-ae27-34a146a69d4b.png)

**Comment by NeoMika** [comment]
Before quests 7228001-7228019 i can teleport,but after those cant
![YuanShen_2022_05_15_21_28_42_715](https://user-images.githubusercontent.com/86155975/168475475-b4458819-2ae0-4451-a5a5-f4646a2a227f.png)

**Comment by misaka10843** [comment]
Some tasks require server-side scripting support, so for now the task can be picked up, can be completed, but not necessarily carried out
You can try to teleport directly to the specified scene, but there may be some problems

有些任务需要服务端脚本支持，所以现在暂且是任务能领取，能完成，但是不一定能进行
你可以试试直接传送至指定场景，但是可能会出现某些问题

**Comment by Radminister** [comment]
大佬请问我第一次安装， 我也出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}（就是您的第二张图里的红色警告）是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。

**Comment by lentarest** [comment]
这个问题我遇到过，我是使用了一款软件“MongoDBCompass”，直接对账号内的任务进行管理，删除了一部分任务，然后就可以进行正常的传送

**Comment by FeiFei-SS** [comment]
> 大佬请问我第一次安装， 我也出现了WARN:AbstractHandler No Server set for PrefixableHandler@1bb172dd{STARTING}（就是您的第二张图里的红色警告）是什么情况？而且我不开加速器的话一直提示无法连接网络4201。但是开了之后登录时cmd就会显示java.io.IOException: 提供了一个无效的参数。

建議查看我的教程[原神私服搭建教程-Private Server](https://www.rainkavik.com/archives/254/)也許能幫助到你
