### ISSUE TITLE
[Bug] Some character board audio lost

### ISSUE THREAD

**Issue by NeoMika** [Melledy/Grasscutter#914]
![YuanShen_2022_05_15_22_06_36_775](https://user-images.githubusercontent.com/86155975/168476974-f9639b89-e89a-4920-a1bc-7794d9ea53ac.png)
not sure its client bug or server bug
this also happen in some quests

**Comment by memetrollsXD** [comment]
This is a client-side bug and isn't related to Grasscutter.
