### ISSUE TITLE
[Bug] Kokomi doesn't heal and Ocean-Hued Clam 4-Piece Bonus not working properly.

### ISSUE THREAD

**Issue by spomacmega** [Melledy/Grasscutter#915]
**Describe the bug**
I was using kokomi and seems like her E skill doesn't heal and even when using Q skill, she still doesn't heal.
Ocean-Hued Clam 4-Piece Bonus not working properly and the Sea-Dyed Foam Bubble doesn't show up.

**Which branch did you use?**
Stable branch v1.1.0

**Comment by lassedds** [comment]
This is known already reason is just well the effects arent coded yet

**Comment by 4Benj** [comment]
Please learn how to search #886 #675 #707 #556 #494 #458
