### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by administratorxjp** [Melledy/Grasscutter#918]
**Did you look for other closed issues that have the same problem?**

no
**Describe the issue**

Please join the specialties on the ground, such as strawberries, peppers, flowers and blue fruits. Maybe we need them more than the task. Thank you
**Which version did you use?**

  Grasscutter version: 1.1.1-dev

**Screenshots**

**Additional context**

**Comment by lunaticwhat** [comment]
This will be added in the future !

**Comment by KiminaNatsuki** [comment]
"strawberries, peppers, flowers and blue fruits"
he mean all these plants and ores should spawn lol

**Comment by KingRainbow44** [comment]
world material spawning has not been implemented yet.

**Comment by Birdulon** [comment]
Implemented by #1368
