### ISSUE TITLE
[Bug] Can not change default IP address after upgrade to newest dev branch.

### ISSUE THREAD

**Issue by nigpo** [Melledy/Grasscutter#919]
After upgrade to newest branch and change the server ip address that I wanna, I will lost connection of game after login.
We can change GameServer java file and HttpServer and remove host for bug fixed.

**Comment by ghost** [comment]
Have you checked your config file? We did a config file rework a while ago.

**Comment by ghost** [comment]
#993

**Comment by nigpo** [comment]
Solve with latest dev version.

**Comment by nigpo** [comment]
#993 Solved.
