### ISSUE TITLE
Hello, can you give a tutorial on Android mobile phone connection?[Issue] 

### ISSUE THREAD

**Issue by MC-xilie** [Melledy/Grasscutter#923]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

**Which version did you use?**

**Screenshots**

**Additional context**

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
