### ISSUE TITLE
Cannnot enter Spiral Abyss  [WARN:"No script found for scene 33100"]

### ISSUE THREAD

**Issue by jianqiylz** [Melledy/Grasscutter#925]
**Describe the issue**
When I entered Spiral Abyss, I keep on falling. I am using the resources at https://github.com/Koko-boya/Grasscutter_Resources/.
But the scripts seems out of date. How can I find the latest Scripts? Thaaaaaanks!

**Which version did you use?**
  Grasscutter version: 1.1.2-dev

**Comment by lopelem** [comment]
![image](https://user-images.githubusercontent.com/37797437/168482322-9a32786f-4c91-4420-af82-4b0ee69384e9.png)
检查你config的截图的文件名字的大小写

**Comment by jianqiylz** [comment]
> 

真的是！太感谢了！

**Comment by maoyuhao94** [comment]
修改大小写后无法进入游戏怎么办？显示服务器断开连接
