### ISSUE TITLE
[Issue] Fail to start Express, saying that prot 443 is in use which I do not think so

### ISSUE THREAD

**Issue by yihuanlin** [Melledy/Grasscutter#930]
**Describe the issue**
Encountered an error when executing the command "java -jar grasscutter-1.1.0.jar":
Failed to start Express
Exception in thread "main" java.lang.RuntimeException: Port already in use. Make sure no other process is using port 443 and try again.

But port 443 is not in use

**Which version did you use?**
1.1.0
(Terminal line prompts the same error message)

**Screenshots**
<img width="871" alt="Screenshot 2022-05-15 at 18 58 54" src="https://user-images.githubusercontent.com/85040891/168487105-68b6722d-8606-4a95-a906-2dc67984357e.png">
<img width="867" alt="Screenshot 2022-05-15 at 18 59 53" src="https://user-images.githubusercontent.com/85040891/168487148-46588bd2-f8d6-4f5f-bac6-c3b1c13f3cd9.png">

**Additional context**
I am using a clean install of Ubuntu 18.04.1 hosted on Google Cloud.

**Comment by lunaticwhat** [comment]
You may want to try restart you computer before checking for port usage

**Comment by yihuanlin** [comment]
> You may want to try restart you computer before checking for port usage

Thank you for your reply. I have tried restarting and even reinstalling my OS but still got the same error message.
Below is what I did after a clean install:
```
sudo apt update && sudo apt upgrade -y
sudo apt install openjdk-17-jdk -y
sudo dpkg --configure -a
sudo apt-get install -f
sudo apt install mongodb -y
sudo systemctl enable mongodb
sudo apt install unzip -y
sudo apt install subversion -y

rm config.json
wget https://nightly.link/Grasscutters/Grasscutter/workflows/build/stable/Grasscutter.zip
unzip Grasscutter.zip
java -jar grasscutter-1.1.0.jar
svn checkout https://github.com/Koko-boya/Grasscutter_Resources.git/trunk
mv ./trunk/Resources resources
rm -f -r trunk
svn checkout https://github.com/Grasscutters/Grasscutter/trunk/keys
svn checkout https://github.com/Grasscutters/Grasscutter/trunk/data
svn export  https://github.com/Grasscutters/Grasscutter/trunk/keystore.p12
java -jar grasscutter-1.1.0.jar -handbook

java -jar grasscutter-1.1.0.jar
```

**Comment by 4Benj** [comment]
You can figure out what process is using a certain port using `netstat -ltnp | grep -w ':443'  `.

**Comment by Extrwave** [comment]
ensure you do not install the web server such as apache，this will use 443 port
or you can check the config of webserver, to avoid it

**Comment by yihuanlin** [comment]
> ensure you do not install the web server such as apache，this will use 443 port
> or you can check the config of webserver, to avoid it

Thank you for your reply. But I think I don’t have any web servers (nginx/apache) installed coz it is a clean install. I also checked that port 443 was not in use

**Comment by yihuanlin** [comment]
> netstat -ltnp

Thank you for your reply. But I think port 443 was actually not in use. The second screenshot attached is the result of netstat -ltnp which doesn't show 443 was in use. I have also tried ur code and nothing was returned.

**Comment by Extrwave** [comment]
> > ensure you do not install the web server such as apache，this will use 443 port
> > or you can check the config of webserver, to avoid it
> 
> Thank you for your reply. But I think I don’t have any web servers (nginx/apache) installed coz it is a clean install. I also checked that port 443 was not in use

can you show me your `config.json`，did you used the same port 443 on gameserver and dispatchserver？

**Comment by Birdulon** [comment]
> `java -jar grasscutter-1.1.0.jar`

Note that ports 0-1023 are restricted to root on linux systems. If you want to use port 443 for Grasscutter, you'll either have to run it with sudo (`sudo java -jar grasscutter-1.1.0.jar`, this is generally not a good idea for security reasons) or use a reverse proxy in something like apache or nginx with Grasscutter using another port, such as 44300, and have apache/nginx redirect incoming traffic from port 443 to 44300.

I personally just use Grasscutter with port 44300 and point my mitmproxy there instead, Grassclipper also makes it easy enough to target servers running on different ports.

**Comment by yihuanlin** [comment]
> > `java -jar grasscutter-1.1.0.jar`
> 
> Note that ports 0-1023 are restricted to root on linux systems. If you want to use port 443 for Grasscutter, you'll either have to run it with sudo (`sudo java -jar grasscutter-1.1.0.jar`, this is generally not a good idea for security reasons) or use a reverse proxy in something like apache or nginx with Grasscutter using another port, such as 44300, and have apache/nginx redirect incoming traffic from port 443 to 44300.
> 
> I personally just use Grasscutter with port 44300 and point my mitmproxy there instead, Grassclipper also makes it easy enough to target servers running on different ports.

Thank you so much. It works with sudo. I am running it on a VPS designated grasscutter so I guess the security issue might not be a big deal?

**Comment by yihuanlin** [comment]
> > `java -jar grasscutter-1.1.0.jar`
> 
> Note that ports 0-1023 are restricted to root on linux systems. If you want to use port 443 for Grasscutter, you'll either have to run it with sudo (`sudo java -jar grasscutter-1.1.0.jar`, this is generally not a good idea for security reasons) or use a reverse proxy in something like apache or nginx with Grasscutter using another port, such as 44300, and have apache/nginx redirect incoming traffic from port 443 to 44300.
> 
> I personally just use Grasscutter with port 44300 and point my mitmproxy there instead, Grassclipper also makes it easy enough to target servers running on different ports.

Sorry for reopening it. I sucessfully launched the server but it seems that some resources are not acessible remotely and my cilent is unable to connect.
![Screenshot 2022-05-16 113143](https://user-images.githubusercontent.com/85040891/168574981-8244c4fa-607a-4d31-b67f-590fcb35f483.png)

![Screenshot 2022-05-16 113244](https://user-images.githubusercontent.com/85040891/168574965-a2341c6f-1cc4-479b-b1ed-c4a9e7a2c4b1.png)
.

**Comment by Birdulon** [comment]
Check firewall rules on the game server port (22102), restart mitmproxy and game.

**Comment by yihuanlin** [comment]
> Check firewall rules on the game server port (22102), restart mitmproxy and game.

Thank you. I have tried that but still got the same error message. I think it is https://mydomain.com/admin/mil8n/plat_oversea/m2020030410/m2020030410-version.json that is not accessible (404, maybe missing that file?) other files are fine.

It shows client logged in my sever side:
<img width="868" alt="Screenshot 2022-05-16 at 13 56 20" src="https://user-images.githubusercontent.com/85040891/168597434-25293477-59c1-493d-a0af-13dab2649be8.png">

Please find my firewall configuration below:
<img width="1412" alt="Screenshot 2022-05-16 at 13 50 54" src="https://user-images.githubusercontent.com/85040891/168596943-bdd31f59-5076-4aad-9610-672a032aab66.png">

**Comment by Morgan-mmy** [comment]
please show us the config.json file to ensure whether your config is correct

**Comment by zxl-qq927489674** [comment]
config.json in "KeystorePassword" add "123456"

**Comment by 4Benj** [comment]
> Thank you. I have tried that but still got the same error message. I think it is https://mydomain.com/admin/mil8n/plat_oversea/m2020030410/m2020030410-version.json that is not accessible (404, maybe missing that file?) other files are fine.

This was fixed in a “recent” commit on the dev branch.

**Comment by Morgan-mmy** [comment]
邮件已收到，我会尽快查看并回复您的！thanks！
