### ISSUE TITLE
 "emu.grasscutter.game.gacha.GachaBanner.getRateUpItems1()" is null[Issue] 

### ISSUE THREAD

**Issue by its-avery** [Melledy/Grasscutter#932]
I looked if anybody has the same problem, but i couldnt find any issues. 

When i try to use java -jar grasscutter.jar then it loades and says  "emu.grasscutter.game.gacha.GachaBanner.getRateUpItems1()" is null.
I dont know what the problem is please help.

![grafik](https://user-images.githubusercontent.com/92790519/168500707-a3a336eb-f1ac-44ef-8a2f-8efbd7828f9c.png)

**Comment by Birdulon** [comment]
What version of grasscutter is this? That looks like it's running an older version with a modern `Banners.json`.
Do you have multiple `.jar` files in your grasscutter directory?

**Comment by its-avery** [comment]
i used the newest version of jar

**Comment by its-avery** [comment]
solved it idk how
