### ISSUE TITLE
[Bug] /quest add not working in the latest dev

### ISSUE THREAD

**Issue by xmgnew** [Melledy/Grasscutter#938]
In the latest dev, when using command "/quest add <ID>", it will give an error "ID not found". I tried it with multiple quest ID, it all gives the same error.

**Comment by mIwaYuhang** [comment]
If you have added already completed quests, please delete the 'quests' from the database, this will allow you to complete the quest

**Comment by xmgnew** [comment]
> If you have added already completed quests, please delete the 'quests' from the database, this will allow you to complete the quest

Where is the database? I can't find it

**Comment by mIwaYuhang** [comment]
> > 如果您添加了已完成的任务，请从数据库中删除“任务”，这将允许您完成任务
> 
> 数据库在哪里？我找不到它

Using MongoDB

**Comment by xmgnew** [comment]
![image](https://user-images.githubusercontent.com/95559022/168568871-1f8d4673-7177-4c10-ab6b-71db00a11db8.png)

Is this the database? the files are all in weird names, which one shoud I delete? can you please teach me

**Comment by mIwaYuhang** [comment]
> ![图像](https://user-images.githubusercontent.com/95559022/168568871-1f8d4673-7177-4c10-ab6b-71db00a11db8.png)
> 
> 这是数据库吗？这些文件都是奇怪的名字，我应该删除哪一个？你能教我吗

enable this software

**Comment by xmgnew** [comment]
> 
> enable this software

The image you sent is the same as I posted just now, which software should I enable?

**Comment by mIwaYuhang** [comment]
> > 启用此软件
> 
> 您发送的图像与我刚才发布的图像相同，我应该启用哪个软件？

If you don't have MongoDB installed, it's just a decompressed file, please download the installer from the MongoDB official website

**Comment by mIwaYuhang** [comment]
> > > 启用此软件
> > 
> > 
> > 您发送的图像与我刚才发布的图像相同，我应该启用哪个软件？
> 
> 如果您没有安装MongoDB，它只是一个解压缩文件，请从MongoDB官方网站下载安装程序

MongoDB5.0.8msi :https://www.mongodb.com/try/download/community

**Comment by xmgnew** [comment]
I have mongoDB installed, do you mean that I need to open the "MongoDB Compass"? I don't know how to use that software
![image](https://user-images.githubusercontent.com/95559022/168572161-278d21a7-7415-408a-84bd-5da936760e1d.png)

**Comment by mIwaYuhang** [comment]
> 我已经安装了mongoDB，你的意思是我需要打开“MongoDB指南针”吗？我不知道如何使用该软件 ![图像](https://user-images.githubusercontent.com/95559022/168572161-278d21a7-7415-408a-84bd-5da936760e1d.png)

Click Connect

**Comment by mIwaYuhang** [comment]
![image](https://user-images.githubusercontent.com/105578203/168572781-fd3f0777-db75-4818-9c0b-f3c25f232fcb.png)
![image](https://user-images.githubusercontent.com/105578203/168572910-bf3a5296-dc96-40c4-9b61-c7b7df7e6d54.png)

**Comment by xmgnew** [comment]
Thanks so much!! Everything is working now! Thank you for being so patient in helping me
