### ISSUE TITLE
[Bug] There has some bugs on Enter Abyss tower

### ISSUE THREAD

**Issue by Extrwave** [Melledy/Grasscutter#939]
**Describe the bug**

I'm really sorry for using machine translation because of my English proficiency:
When the server has more than one player online, click into the abyss does not respond, the background display is to pass other players into the abyss, at the same time open the abyss again floor records also change, not their own records, you can reproduce this BUG with  a very high probability.

**Which branch did you use?**
Development branch，package on windows，and run in centos8

**Screenshots**

![](https://drive.ethreal.cn/Loader/Snipaste_2022-05-16_16-42.png)

**Additional context**

**Comment by bilibili12315** [comment]
: )

**Comment by KiminaNatsuki** [comment]
Known problem.
