### ISSUE TITLE
[Bug] Server uses file paths that relative to working directory, not executable directory

### ISSUE THREAD

**Issue by curoviyxru** [Melledy/Grasscutter#943]
**Describe the bug**
wpstudioru#8232 encountered a bug that prevents a server from launch. He tried to launch server from home directory with `java -jar %absolute_path_to_jar%` command, but server exited with error. Grasscutter should use file paths that relative to JAR executable directory, not working directory.

**Which branch did you use?**
Development branch - 1.1.2

**Screenshots**
![image](https://user-images.githubusercontent.com/61984636/168646718-665b12f3-5062-4225-964f-6bd447ee6b50.png)

**Additional context**
If you're launching server from directory where JAR file is located, it works, else not.

**Comment by Morgan-mmy** [comment]
you should goto the workplace to run java -jar where the jar file exists, goto the relative path to run.

**Comment by KingRainbow44** [comment]
this is how java works. we won’t be fixing this “issue.”
