### ISSUE TITLE
[Bug] 角色衣装无法使用/Character clothing is unavailable

### ISSUE THREAD

**Issue by AcosX** [Melledy/Grasscutter#945]
**Describe the bug**

使用/g 授予玩家衣装后，服务器显示授予成功，但实际上角色界面显示没有
使用创世结晶从商店购买也是一样的

**Screenshots**

![Screenshot_2022-05-17-06-40-44-559_com miHoYo GenshinImpact](https://user-images.githubusercontent.com/46348773/168694162-aba1a95c-2193-41e2-b9f4-d76ff58c50df.jpg)
![Screenshot_2022-05-17-06-40-24-451_com miHoYo GenshinImpact](https://user-images.githubusercontent.com/46348773/168694165-8a9c9941-9915-4942-a98b-55c9d810dce4.jpg)

**Comment by SleepyAsh0191** [comment]
duplicate with #531

请自行关闭 issue，并根据issue#531的方法解决时装问题
