### ISSUE TITLE
[Issue] internet loss after opening grasscutter

### ISSUE THREAD

**Issue by Azrail-dev** [Melledy/Grasscutter#947]
**Did you look for other closed issues that have the same problem?** yes
 

**Describe the issue**

after opening grasscutter 
I lost connection instantly

**Which version did you use?**

Java 17
Grasscutter version wad the latest one i think it was 9.3?

**Screenshots**
none because im using my phone right now and my pc doesn't have Internet 

**Additional context**

**Comment by alt3ri** [comment]
Turn off the proxy after you quit grasscutter

**Comment by KiminaNatsuki** [comment]
turn off your proxy in windows settings if you didn't close it correctly

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
