### ISSUE TITLE
melon loader is being deleted everytime i run genshin from grassclipper

### ISSUE THREAD

**Issue by wxvelight** [Melledy/Grasscutter#948]
Yes i looked and nothing seems to answer my problem

Once i download melon loader insert it into genshin impact then add a mod then open the game my genshin impact game closes and so does the consoles and when i look back in files melon loader is gone

java 1.7

ive tried getting rid of windows defender but nothing worked

**Comment by alt3ri** [comment]
did you really read the instruction carefulyl?

**Comment by TheLostTree** [comment]
Ah yes a melonloader question on the grasscutter github referring to an issue with grassclipper.

**Comment by wxvelight** [comment]
does anyone kno

**Comment by KiminaNatsuki** [comment]
Not related to Grasscutter...?

**Comment by 4Benj** [comment]
Closing due to irrelevance. Please submit this issue on the [Grassclipper](https://github.com/Grasscutters/GrassClipper) issue tracker...

**Comment by 4Benj** [comment]
I have been made aware of a guide which fixes this issue. Before opening a Grassclipper issue please [read this](https://github.com/lassedds/Melonloader-AnimeGaming)

**Comment by wxvelight** [comment]
ive done all that can u show me the guide please thank you

**Comment by Taiga74164** [comment]
skill issue tbh

**Comment by lunaticwhat** [comment]
> skill issue tbh

so rude
