### ISSUE TITLE
是否可以加入指定角色到多少等级和删除指定角色的功能呢？

### ISSUE THREAD

**Issue by daxiwow** [Melledy/Grasscutter#950]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

**Which version did you use?**

**Screenshots**

**Additional context**

**Comment by aquawius** [comment]
Translate: Is it possible to add a given character to a given level and delete a given character?

I think u can give yourself exp in game, so character level request is useless, maybe Grasscutters may consider deleting characters.

**Comment by daxiwow** [comment]
> Translate: Is it possible to add a given character to a given level and delete a given character?
> 
> I think u can give yourself exp in game, so character level request is useless, maybe Grasscutters may consider deleting characters.

thanks

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
