### ISSUE TITLE
[Bug]多人游戏里选择秘境邀请不了队友邀请选项提示已邀请但是2P并没有任何提示

### ISSUE THREAD

**Issue by zhuyinQAQ** [Melledy/Grasscutter#952]

**Comment by Kimi898246** [comment]
Title Translation: Cannot invite teammate into the domain.
(the game will say invited but 2P isn't showing)

**Comment by KiminaNatsuki** [comment]
Closing inactive issues to clear up workspace, feel free to resubmit if this haven't been fixed yet, plus follow the issue format next time.
