### ISSUE TITLE
[Issue] 怎么更改角色的技能，比如增加钟离的岩脊数量

### ISSUE THREAD

**Issue by CSXFanMeng** [Melledy/Grasscutter#953]

**Comment by KiminaNatsuki** [comment]
Title Translation: How to edit character's skills, for example, adding Zhongli's pillar numbers?

**Comment by mokurin000** [comment]
I guess this should be done by editing client instead of the server

**Comment by memetrollsXD** [comment]
**This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.**

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
