### ISSUE TITLE
[Bug] Characters will get damaged even under the shield's protect, when lots enemies around

### ISSUE THREAD

**Issue by WorldlineChanger** [Melledy/Grasscutter#959]
**Describe the bug**

Characters will get damaged even the shield still exists (I'm using Zhongli's sheild and it didn't break). This problem may happen while there are amounts of enemies(10 or more) around.
Maybe because the attacks are too frequently in that situation?

**Which branch did you use?**

development
1.1.0

**Comment by Morgan-mmy** [comment]
yes, just go away.

**Comment by WorldlineChanger** [comment]
> yes, just go away.

It is a bug, don't be like this.

**Comment by Morgan-mmy** [comment]
邮件已收到，我会尽快查看并回复您的！thanks！
