### ISSUE TITLE
[Issue] the appwont let me in it keeps duplicating

### ISSUE THREAD

**Issue by mayvp** [Melledy/Grasscutter#963]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

everytime i press the launch button it keeps duplicating

**Which version did you use?**

1.1.0

**Screenshots**

**Additional context**

**Comment by 4Benj** [comment]
What launch button? Please provide more detail when submitting an issue

**Comment by mayvp** [comment]
> 
its already done im just having problems on logging in ... it keeps saying server busy but i already done like every part of it just not the launch local server command i have a problem of that too

**Comment by AZthemute** [comment]
What's duplicating, exactly? Provide screenshots or a video recording if you can.

**Comment by Morgan-mmy** [comment]
can login, but cant join your service? put on some screenshots or log errors text for us to help u, dude

**Comment by memetrollsXD** [comment]
Please re-submit with more context
