### ISSUE TITLE
[Feature Request] Display UIDs next to names upon using list command

### ISSUE THREAD

**Issue by vhcrack** [Melledy/Grasscutter#969]
**Is your feature request related to a problem? Please describe.**

Whenever I try to look someone up on the server using the list command, there is no UID displayed next to their name, which makes player management somewhat frustrating. If I want to give a player online an item, message them or use any other player targeted command on them, I have to ask for their UID first or guess what their UID is.

**Describe the solution you'd like**

Upon using the list command, it lists the names of each player online and their UID on the side.

One way it could display is this -
 
Players Online (2):
Test (@10001), Admin (@10002)

**Describe alternatives you've considered**

Maybe consider implementing a "lookup" command, where you can use the command to look up a person's UID (online/offline) based off their name.

**Additional context**

**Comment by jie65535** [comment]
use `/list uid` can show player uid

**Comment by Betterthanthat1** [comment]
How do I get all the issues off my phone
