### ISSUE TITLE
[Feature Request] 加入命令操作日志

### ISSUE THREAD

**Issue by 66hh** [Melledy/Grasscutter#981]
**Is your feature request related to a problem? Please describe.**

在控制台/日志中加入玩家操作日志（这对防熊服很有帮助）
**Describe the solution you'd like**

在CommandMap.java的invoke函数中加入getLogger().info()就像下面这样（下面这个只是个例子不太规范）
        if (player == null) {
            getLogger().info("控制台使用命令 " + rawMessage);
        } else {
            getLogger().info("玩家 " + player.getNickname() + " uid:" + Integer.toString(player.getUid()) + " 使用命令 " + rawMessage);
        }
**Describe alternatives you've considered**

**Additional context**

**Comment by nigpo** [comment]
这个倒是只需要加一个Logger，因为自带的日志logback支持回溯，直接将原本的日志加到日志系统即可，
在你log文件夹的logback.txt里面，有时候这个文件能有200GB。

**Comment by nigpo** [comment]
#1019
已加入
