### ISSUE TITLE
[Bug] Android 安卓客户端登录界面文字成代码了

### ISSUE THREAD

**Issue by 2y8e9h22** [Melledy/Grasscutter#982]
![Screenshot_2022-05-19-04-48-05-644_com miHoYo GenshinImpact](https://user-images.githubusercontent.com/70102795/169153196-d49d817b-ab5f-41e4-bfc9-1918ec19f09e.jpg)
![Screenshot_2022-05-19-04-47-57-260_com miHoYo GenshinImpact](https://user-images.githubusercontent.com/70102795/169153195-be8e2c99-5ac7-4ec5-b292-ead27c5bbe8f.jpg)
**登录界面的这些文字全成这样的代码了**

**Comment by FoehnMLK** [comment]
我也遇到了同样的问题

**Comment by misaka10843** [comment]
似乎是语言文件的问题？

**Comment by kuilei0926** [comment]
连一下官方服务器就可以了

**Comment by FoehnMLK** [comment]
> 连一下官方服务器就可以了

这个操作并没有解决我遇到的的问题

**Comment by MoonShadowIllusion** [comment]
现在安卓可以玩了吗

**Comment by izhuolin** [comment]
我的也出现这种情况 只有使用回昨天的版本就可以恢复

**Comment by WorldlineChanger** [comment]
你好，可以请问下你用的是哪个代理转发软件吗？

**Comment by sjc74364** [comment]
@WorldlineChanger 可以使用surfboard进行代理

[General]
dns-server = 114.114.114.114, 8.8.8.8, system

#代理服务器地址
[Proxy]
ProxyHTTP = http, 127.0.0.1, 8080, ,


[Proxy Group]
SelectGroup = select, ProxyHTTP

[Rule]
#国际服检查更新，放行
DOMAIN,autopatchhk.yuanshen.com,DIRECT
#国际服
PROCESS-NAME,com.miHoYo.GenshinImpact,ProxyHTTP
FINAL,DIRECT

**Comment by WorldlineChanger** [comment]
@sjc74364 非常感谢

**Comment by MoonShadowIllusion** [comment]
> [General] dns-server = 114.114.114.114, 8.8.8.8, system
> 
> #代理服务器地址 [Proxy] ProxyHTTP = http, 127.0.0.1, 8080, ,
> 
> [Proxy Group] SelectGroup = select, ProxyHTTP
> 
> [Rule] #国际服检查更新，放行 DOMAIN,autopatchhk.yuanshen.com,DIRECT #国际服 PROCESS-NAME,com.miHoYo.GenshinImpact,ProxyHTTP FINAL,DIRECT

无root 可以用吗

**Comment by sjc74364** [comment]
@Winter-is-comingXK 可以用，但安装mitmproxy和fiddler的证书到系统需要root
