### ISSUE TITLE
怎么修改角色 的移动速度和跳跃高度。等等

### ISSUE THREAD

**Issue by MyFreeGame** [Melledy/Grasscutter#989]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LittleMio** [comment]
This is an issue tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

GitHub issue 不是技术支持论坛。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道
