### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by thomas0829** [Melledy/Grasscutter#991]
Hi, I have faced a weird error during dataloader after I update my grasscutter.jar file from 5/16 to 5/17, it didn't actually cause any problems but still fell a little bit strange. 
![image](https://user-images.githubusercontent.com/30018643/169229340-e6d1935d-1059-497a-a531-c890e02d58a1.png)

I just tried delete all the data folder or renew the files inside the file folder but still appear the error.
Hope someone could annswer me, thanks!

**Comment by 4Benj** [comment]
Do the data files get generated automatically?

**Comment by Kimi898246** [comment]
Sorry, but could you show the error fully?

**Comment by 4Benj** [comment]
Could you update to the latest commit (5e56b49) and post the error again?

**Comment by thomas0829** [comment]
> Could you update to the latest commit ([5e56b49](https://github.com/Grasscutters/Grasscutter/commit/5e56b4932081cb52afcd478620083066b8683455)) and post the error again?

Since I'm not really understand on the while processing, I should copy the whole code and change the file inside the not compiled file and compile again?

**Comment by 4Benj** [comment]
> Since I'm not really understand on the while processing, I should copy the whole code and change the file inside the not compiled file and compile again?

If you've downloaded through git you should be able to just do ``git pull origin development``. If you just downloaded the .zip, just redownload it again and setup the server again (NOTE: You shouldn't need to download the data files with the latest development build).
Either way, you need to run ``gradlew jar`` to compile the server again.

**Comment by thomas0829** [comment]
After trying some folder names, I found the problem that my folder name have a space between two words which occured the bug. Thanks for answering my problems.
