### ISSUE TITLE
Main characters elemental bursts doesn't work.

### ISSUE THREAD

**Issue by Rallus-Zenturi** [Melledy/Grasscutter#994]
Main characters Aether ; Lumine ANY elemental burst doesn't work. 
Though it was embryo issue but no, if you'll delete burst ability in other character, the elemental burst icon still will glow and can be initiated. It might be some kind of energy issue.

Branch used - Grasscutter version: 1.1.2-dev

**Screenshots**
![image](https://user-images.githubusercontent.com/43311503/169302360-6385c39b-6f92-477a-9c06-5ae9b005099c.png)
![image](https://user-images.githubusercontent.com/43311503/169302384-ba166c5f-f6fb-441c-b531-4ac5ad139c8e.png)
![image](https://user-images.githubusercontent.com/43311503/169303485-83f684be-7fa2-48eb-9a78-e87385549ef3.png)

Additionally I would like to suggest implementation of feature
Interacting with Statues of the Seven and allowing to players to switch main characters skilldepots without editing db manually.

**Comment by Birdulon** [comment]
Traveler can't gain any energy even when you set their fightprops, it might be related to quest flags on the client.

**Comment by lunaticwhat** [comment]
all are known issues, thanks.
